-- Arkansas. The state had four stops.
--
-- Two are replaced rather than merged, and both were found by the name check
-- built for exactly this a few minutes ago.
--
-- Gravity Hill at Helena-West Helena sits 2,309 metres from a stop held as
-- "Sulphur Springs Gravity Hill". Same hill, different name, and a scan
-- coordinate two kilometres out — so the slug check saw nothing and the
-- proximity check saw two separate places.
--
-- World's Largest Christmas Pickle is held at Barling, nine kilometres from
-- where this batch puts it in Fort Smith. The apostrophe difference meant only
-- the second slug convention found it at all.
--
-- Eleven internal proximity flags, all kept, and one of them is worth
-- explaining. The 25-foot Red Ryder BB gun stands five metres from the door of
-- the Daisy Airgun Museum, and the USS Razorback is moored thirteen metres
-- from the maritime museum that runs it.
--
-- Earlier states dropped this kind of pair — Rusty the Giant Sloth was removed
-- because he is the University of Iowa museum's own specimen. The difference
-- is whether you can see the thing without paying: Rusty is behind a ticket
-- desk, the BB gun is on the pavement. One is a feature of a stop and the
-- other is a two-minute stop of its own, for a traveller who is not going
-- inside.
--
-- 121 stops, every one with a source.

delete from public.stops
where state = 'AR'
  and slug in ('sulphur-springs-gravity-hill-helena-ar', 'world-s-largest-christmas-pickle');

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Popeye Statue', 'popeye-statue', 'roadside-oddities', 35.47681, -94.22141, 'Alma', 'AR', 'An eight-foot bronze Popeye stands in downtown Alma, a tribute to the town’s long connection to spinach processing. It is one of Arkansas’s best-known oversized character statues and an easy roadside photo stop.', 'roadside', 'https://www.arkansas.com/alma', null, 'America/Chicago', now()),
  ('Bonnie & Clyde Victim Memorial', 'bonnie-clyde-victim-memorial', 'weird-history', 35.47645, -94.22125, 'Alma', 'AR', 'A local memorial recalls Alma marshal Henry Humphrey, who was fatally wounded during an encounter with Bonnie and Clyde in 1933. It connects a quiet Arkansas downtown with one of the country’s most notorious outlaw stories.', 'roadside', 'https://www.roadsideamerica.com/location/stateIndex.php?state=AR', null, 'America/Chicago', now()),
  ('Mark Martin Museum', 'mark-martin-museum', 'museums', 35.76961, -91.64097, 'Batesville', 'AR', 'A free museum devoted to Arkansas-born NASCAR driver Mark Martin displays race cars, trophies, uniforms, helmets and other memorabilia from his career. It sits inside the Mark Martin Automotive complex.', 'open', 'https://www.markmartinmuseum.com/', null, 'America/Chicago', now()),
  ('Bauxite Historical Association Museum', 'bauxite-historical-association-museum', 'museums', 34.55537, -92.52099, 'Bauxite', 'AR', 'This small local museum interprets the mining history of Bauxite, the Arkansas town literally named for the ore beneath it. Displays include mining artifacts, town history and some unusual pieces tied to the region’s industrial past.', 'limited', 'https://www.arkansas.com/bauxite', null, 'America/Chicago', now()),
  ('Bauxite Miner Family Statue', 'bauxite-miner-family-statue', 'roadside-oddities', 34.55558, -92.52114, 'Bauxite', 'AR', 'A miner-family monument pays tribute to the workers and families who built Bauxite around the aluminum ore industry. It is a compact roadside marker for one of Arkansas’s strangest company-town histories.', 'roadside', 'https://www.roadsideamerica.com/location/stateIndex.php?state=AR', null, 'America/Chicago', now()),
  ('Beaver Bridge', 'beaver-bridge', 'roadside-oddities', 36.47174, -93.76853, 'Beaver', 'AR', 'The one-lane Beaver Bridge spans the White River on an unusually narrow suspension deck. Nicknamed the Little Golden Gate Bridge, it has become one of the Ozarks’ most recognizable quirky road crossings.', 'roadside', 'https://www.arkansas.com/beaver', null, 'America/Chicago', now()),
  ('Museum of Native American History', 'museum-of-native-american-history', 'museums', 36.37118, -94.22933, 'Bentonville', 'AR', 'MONAH presents thousands of Native American artifacts spanning thousands of years, including pottery, tools, clothing and ceremonial objects. Its compact but wide-ranging collection makes it one of northwest Arkansas’s strongest history stops.', 'open', 'https://www.monah.org/', null, 'America/Chicago', now()),
  ('Walmart Museum', 'walmart-museum', 'museums', 36.37254, -94.20909, 'Bentonville', 'AR', 'The Walmart Museum occupies the company’s original Bentonville storefront and traces the retailer from a small five-and-dime to a global chain. Historic signs, office objects and early store artifacts make it an unusual piece of commercial history.', 'open', 'https://corporate.walmart.com/about/walmart-museum', null, 'America/Chicago', now()),
  ('Crystal Bridges Museum of American Art', 'crystal-bridges-museum-of-american-art', 'museums', 36.38167, -94.20367, 'Bentonville', 'AR', 'Crystal Bridges combines major American art collections with distinctive architecture embedded in an Ozark ravine. The grounds also hold unusual outdoor sculpture and relocated architectural works.', 'open', 'https://crystalbridges.org/', null, 'America/Chicago', now()),
  ('Bachman-Wilson House', 'bachman-wilson-house', 'roadside-oddities', 36.3812, -94.20445, 'Bentonville', 'AR', 'Frank Lloyd Wright’s Bachman-Wilson House was dismantled in New Jersey and rebuilt on the Crystal Bridges grounds in Arkansas. It is a rare chance to walk around a relocated Wright Usonian house.', 'open', 'https://crystalbridges.org/architecture/bachman-wilson-house/', null, 'America/Chicago', now()),
  ('Cosmic Cavern', 'cosmic-cavern', 'roadside-oddities', 36.43596, -93.49737, 'Berryville', 'AR', 'Cosmic Cavern is a privately operated show cave known for underground lakes and elaborate formations. The cave stays unusually warm for the Ozarks and has been open to visitors for decades.', 'limited', 'https://cosmiccavern.com/', null, 'America/Chicago', now()),
  ('Giant Razorback', 'giant-razorback', 'roadside-oddities', 36.36473, -93.56763, 'Berryville', 'AR', 'A supersized homemade Razorback hog stands along the highway near Berryville. Originally built as a parade float, it now serves as a weathered but distinctive Arkansas roadside mascot.', 'roadside', 'https://onlyinark.com/places-and-travel/northwest-arkansas-oddities-and-roadside-attractions/', null, 'America/Chicago', now()),
  ('Memory Lane Museum', 'memory-lane-museum', 'museums', 36.36441, -93.56787, 'Berryville', 'AR', 'This small private museum preserves an eclectic collection of Americana, antiques and regional memorabilia. It is the kind of dense, owner-curated roadside collection that fits OddWay better than a conventional history museum.', 'limited', 'https://www.roadsideamerica.com/location/stateIndex.php?state=AR', null, 'America/Chicago', now()),
  ('Bull Shoals Caverns', 'bull-shoals-caverns', 'roadside-oddities', 36.38219, -92.58192, 'Bull Shoals', 'AR', 'Bull Shoals Caverns is a living limestone cave with underground streams, mineral formations and a small waterfall. Guided tours turn the cave into one of northern Arkansas’s classic subterranean stops.', 'limited', 'https://bullshoalscaverns.com/', null, 'America/Chicago', now()),
  ('Natural Bridge of Arkansas', 'natural-bridge-of-arkansas', 'roadside-oddities', 35.65611, -92.44972, 'Clinton', 'AR', 'A massive natural sandstone bridge spans a wooded hollow north of Clinton. The privately operated attraction has been a roadside Ozarks stop for generations.', 'limited', 'https://naturalbridgeofarkansas.com/', null, 'America/Chicago', now()),
  ('Toad Suck', 'toad-suck', 'weird-history', 35.07647, -92.53764, 'Conway', 'AR', 'Toad Suck is a real Arkansas place-name tied to a long-running local legend about riverboat crews stopping near the Arkansas River. The odd name has become a civic identity, complete with signs and an annual festival.', 'roadside', 'https://www.conwayark.com/toad-suck-daze', null, 'America/Chicago', now()),
  ('Wampus Cat Mural and Local Legend', 'wampus-cat-mural-and-local-legend', 'folklore', 35.0882, -92.4421, 'Conway', 'AR', 'Conway has embraced the Wampus Cat, a Southern folklore creature, as a local mascot. Public art and school imagery keep the cryptid-like legend visible around town.', 'roadside', 'https://www.roadsideamerica.com/location/stateIndex.php?state=AR', null, 'America/Chicago', now()),
  ('Crossett Light', 'crossett-light', 'haunted', 33.1019, -91.9633, 'Crossett', 'AR', 'For generations, visitors have reported a mysterious light appearing along an old rail corridor outside Crossett. Explanations range from distant headlights to ghost stories, but the Crossett Light remains part of Arkansas folklore.', 'limited', 'https://encyclopediaofarkansas.net/entries/Folklore-and-Folklife-406/', null, 'America/Chicago', now()),
  ('Johnny Cash Boyhood Home', 'johnny-cash-boyhood-home', 'weird-history', 35.59739, -90.24499, 'Dyess', 'AR', 'Johnny Cash grew up in this five-room farmhouse in the New Deal-era Dyess Colony. Restored as a historic site, it preserves the landscape and living conditions that shaped much of Cash’s music.', 'limited', 'https://dyesscash.astate.edu/', null, 'America/Chicago', now()),
  ('Dyess Colony Administration Building', 'dyess-colony-administration-building', 'weird-history', 35.59025, -90.21525, 'Dyess', 'AR', 'The restored colony administration building interprets the experimental New Deal agricultural community where the Cash family settled. It gives context to one of Arkansas’s most unusual planned communities.', 'open', 'https://dyesscash.astate.edu/', null, 'America/Chicago', now()),
  ('1886 Crescent Hotel', '1886-crescent-hotel', 'haunted', 36.40836, -93.73733, 'Eureka Springs', 'AR', 'The Crescent Hotel is Arkansas’s most famous haunted hotel, with stories tied to its years as a hospital run by controversial physician Norman Baker. The hotel openly embraces its ghost lore and operates regular ghost tours.', 'open', 'https://crescent-hotel.com/', null, 'America/Chicago', now()),
  ('Christ of the Ozarks', 'christ-of-the-ozarks', 'roadside-oddities', 36.40887, -93.72509, 'Eureka Springs', 'AR', 'A 65-foot concrete statue of Jesus towers above Eureka Springs from Magnetic Mountain. Its stark proportions and isolated hilltop setting make it one of the Ozarks’ most recognizable giant roadside figures.', 'open', 'https://www.greatpassionplay.org/christ-of-the-ozarks.html', null, 'America/Chicago', now()),
  ('Great Passion Play', 'great-passion-play', 'roadside-oddities', 36.40739, -93.72362, 'Eureka Springs', 'AR', 'This long-running outdoor biblical production occupies a large hillside complex complete with theatrical sets, museums and religious attractions. Its scale and setting make it unusual even outside performance nights.', 'limited', 'https://www.greatpassionplay.org/', null, 'America/Chicago', now()),
  ('Sacred Arts Museum', 'sacred-arts-museum', 'museums', 36.40777, -93.7242, 'Eureka Springs', 'AR', 'Located at the Great Passion Play complex, the Sacred Arts Museum houses a large collection of religious artworks and artifacts. It is a distinctive companion stop to the giant Christ of the Ozarks statue.', 'limited', 'https://www.greatpassionplay.org/', null, 'America/Chicago', now()),
  ('Berlin Wall Segment at Great Passion Play', 'berlin-wall-segment-at-great-passion-play', 'weird-history', 36.409, -93.72557, 'Eureka Springs', 'AR', 'A preserved section of the Berlin Wall stands within the Great Passion Play grounds in the Arkansas Ozarks. Its presence beside religious attractions makes for an unexpectedly surreal historical juxtaposition.', 'open', 'https://www.greatpassionplay.org/', null, 'America/Chicago', now()),
  ('Thorncrown Chapel', 'thorncrown-chapel', 'roadside-oddities', 36.41694, -93.77028, 'Eureka Springs', 'AR', 'Designed by E. Fay Jones, Thorncrown Chapel rises from the woods as a tall glass-and-timber structure with hundreds of windows. It is one of Arkansas’s most distinctive pieces of modern architecture.', 'open', 'https://thorncrown.com/', null, 'America/Chicago', now()),
  ('Blue Spring Heritage Center', 'blue-spring-heritage-center', 'roadside-oddities', 36.46609, -93.81244, 'Eureka Springs', 'AR', 'An intensely blue natural spring emerges from the Ozark landscape at this historic site. The grounds combine geology, Native American history and landscaped trails around the spring basin.', 'limited', 'https://www.bluespringheritage.com/', null, 'America/Chicago', now()),
  ('Quigley’s Castle', 'quigleys-castle', 'roadside-oddities', 36.31874, -93.68533, 'Eureka Springs', 'AR', 'Elise Quigley designed this eccentric stone-covered home around her lifelong rock collection. Plants grow through parts of the interior, while the grounds are filled with stonework, gardens and handmade details.', 'limited', 'https://quigleyscastle.com/', null, 'America/Chicago', now()),
  ('Pivot Rock and Natural Bridge', 'pivot-rock-and-natural-bridge', 'roadside-oddities', 36.41827, -93.74897, 'Eureka Springs', 'AR', 'This old-school roadside attraction features weathered limestone formations, including a narrow-based balanced rock and natural bridge. Its century-old tourist-trap character is part of the appeal.', 'limited', 'https://www.pivotrock.com/', null, 'America/Chicago', now()),
  ('Magnetic Spring', 'magnetic-spring', 'folklore', 36.40849, -93.7219, 'Eureka Springs', 'AR', 'One of Eureka Springs’ many named springs, Magnetic Spring was historically promoted for supposed healing or magnetic qualities. A roadside basin and sign preserve the town’s era of spring-water health claims.', 'roadside', 'https://www.eurekaspringsar.gov/', null, 'America/Chicago', now()),
  ('Turpentine Creek Wildlife Refuge', 'turpentine-creek-wildlife-refuge', 'roadside-oddities', 36.30668, -93.7276, 'Eureka Springs', 'AR', 'This big-cat refuge rescues lions, tigers and other large animals from private ownership and roadside situations. Visitors can walk the habitat area and even stay overnight near the animals.', 'open', 'https://www.turpentinecreek.org/', null, 'America/Chicago', now()),
  ('Blanchard Springs Caverns', 'blanchard-springs-caverns', 'roadside-oddities', 35.96386, -92.17933, 'Fifty-Six', 'AR', 'Blanchard Springs Caverns is a massive living cave system beneath the Ozark National Forest. Guided routes pass towering rooms, flowstone, columns and active underground formations.', 'limited', 'https://www.arkansas.com/state-parks/explore/parks/blanchard-springs-caverns', null, 'America/Chicago', now()),
  ('Blanchard Spring', 'blanchard-spring', 'roadside-oddities', 35.9585, -92.17749, 'Fifty-Six', 'AR', 'The spring that gives the recreation area its name erupts from the base of the karst landscape below the cavern system. Its clear water and dramatic outlet make it a distinct stop from the cave tours above.', 'open', 'https://www.fs.usda.gov/', null, 'America/Chicago', now()),
  ('Fort Smith National Historic Site Gallows', 'fort-smith-national-historic-site-gallows', 'weird-history', 35.38813, -94.42933, 'Fort Smith', 'AR', 'A reconstructed federal gallows recalls the executions carried out under the jurisdiction of Judge Isaac Parker’s court. The site interprets law, punishment and federal authority on the edge of Indian Territory.', 'open', 'https://www.nps.gov/fosm/', null, 'America/Chicago', now()),
  ('Fort Smith National Historic Site Jail and Courtroom', 'fort-smith-national-historic-site-jail-and-courtroom', 'weird-history', 35.3885, -94.42917, 'Fort Smith', 'AR', 'The preserved federal court complex includes jail spaces and Judge Isaac Parker’s courtroom. Exhibits cover outlaws, marshals, executions and frontier justice in unusually direct detail.', 'open', 'https://www.nps.gov/fosm/', null, 'America/Chicago', now()),
  ('Miss Laura’s Visitor Center', 'miss-lauras-visitor-center', 'weird-history', 35.3911, -94.43133, 'Fort Smith', 'AR', 'Fort Smith’s visitor center occupies Miss Laura’s, a restored former bordello from the city’s historic red-light district. It is one of the rare surviving buildings of its kind in the region.', 'open', 'https://www.fortsmith.org/', null, 'America/Chicago', now()),
  ('U.S. Marshals Museum', 'u-s-marshals-museum', 'museums', 35.39018, -94.43191, 'Fort Smith', 'AR', 'The national museum explores the long history of the U.S. Marshals, including the frontier era, federal law enforcement and famous deputies such as Bass Reeves. Its location in Fort Smith directly connects it to Parker-era history.', 'open', 'https://marshalsmuseum.org/', null, 'America/Chicago', now()),
  ('Fort Smith Trolley Museum', 'fort-smith-trolley-museum', 'museums', 35.38593, -94.43006, 'Fort Smith', 'AR', 'Historic streetcars, railroad equipment and an operating heritage trolley line fill this compact museum. Resident ''trolley cats'' have also become a quirky unofficial feature of the site.', 'limited', 'https://www.fstm.org/', null, 'America/Chicago', now()),
  ('Mr. Peanut Statue', 'mr-peanut-statue', 'roadside-oddities', 35.35275, -94.39408, 'Fort Smith', 'AR', 'A giant Mr. Peanut figure stands outside the local Planters facility, accompanied by smaller versions of the famous mascot. The oversized industrial-brand icon is a classic Arkansas photo stop.', 'roadside', 'https://onlyinark.com/places-and-travel/northwest-arkansas-oddities-and-roadside-attractions/', null, 'America/Chicago', now()),
  ('World’s Largest Christmas Pickle', 'worlds-largest-christmas-pickle', 'roadside-oddities', 35.35467, -94.4182, 'Fort Smith', 'AR', 'A huge pickle wearing a Santa hat stands outside a Christmas attraction in Fort Smith. The deliberately absurd sculpture riffs on the Christmas-pickle ornament tradition.', 'roadside', 'https://onlyinark.com/places-and-travel/northwest-arkansas-oddities-and-roadside-attractions/', null, 'America/Chicago', now()),
  ('Boggy Creek Monster Mart', 'boggy-creek-monster-mart', 'cryptids', 33.2612, -93.8872, 'Fouke', 'AR', 'This roadside store and mini-museum celebrates the Fouke Monster, the hairy creature made famous by The Legend of Boggy Creek. Displays, souvenirs and local stories make it the essential Arkansas cryptid stop.', 'open', 'https://www.facebook.com/BoggyCreekMonsterMart/', null, 'America/Chicago', now()),
  ('Fouke Monster Festival Grounds', 'fouke-monster-festival-grounds', 'cryptids', 33.26144, -93.88691, 'Fouke', 'AR', 'Fouke periodically hosts events centered on the local Boggy Creek Monster legend, bringing researchers, fans and folklore vendors together. The town itself has become part of the cryptid story.', 'limited', 'https://www.foukechamber.com/', null, 'America/Chicago', now()),
  ('Gurdon Light Viewing Area', 'gurdon-light-viewing-area', 'haunted', 33.91357, -93.17033, 'Gurdon', 'AR', 'A mysterious light has been reported for decades along an abandoned railroad corridor outside Gurdon. The phenomenon is one of Arkansas’s best documented pieces of ghost-light folklore.', 'limited', 'https://encyclopediaofarkansas.net/entries/gurdon-light-1198/', null, 'America/Chicago', now()),
  ('Hoo-Hoo Monument', 'hoo-hoo-monument', 'weird-history', 33.92012, -93.15462, 'Gurdon', 'AR', 'A monument marks Gurdon as the birthplace of the Concatenated Order of Hoo-Hoo, a lumber-industry fraternal organization founded in 1892. The group’s black-cat symbolism and strange name make the marker especially OddWay-ready.', 'roadside', 'https://www.hoohoo.org/', null, 'America/Chicago', now()),
  ('Ruland Junction Train Museum', 'ruland-junction-train-museum', 'museums', 35.49162, -92.03261, 'Heber Springs', 'AR', 'A small railroad museum preserves local train artifacts, model displays and rail history in Heber Springs. It is an offbeat, enthusiast-run transportation stop.', 'limited', 'https://www.roadsideamerica.com/location/stateIndex.php?state=AR', null, 'America/Chicago', now()),
  ('Gravity Hill', 'gravity-hill', 'haunted', 34.54856, -90.62574, 'Helena-West Helena', 'AR', 'On this local road, vehicles appear to roll uphill when placed in neutral. The effect is an optical illusion, but generations of visitors have layered ghost stories and supernatural explanations onto it.', 'roadside', 'https://onlyinark.com/places-and-travel/central-and-eastern-arkansas-oddities-and-roadside-attractions/', null, 'America/Chicago', now()),
  ('Delta Cultural Center', 'delta-cultural-center', 'museums', 34.52192, -90.58589, 'Helena-West Helena', 'AR', 'The Delta Cultural Center interprets blues music, river history and life in the Arkansas Delta. Its exhibits connect the region’s music to broader American cultural history.', 'open', 'https://www.deltaculturalcenter.com/', null, 'America/Chicago', now()),
  ('Fort Curtis', 'fort-curtis', 'weird-history', 34.52926, -90.58806, 'Helena-West Helena', 'AR', 'A reconstructed Civil War fort recalls the Union occupation of Helena and the Battle of Helena. Earthworks, interpretation and the unusual urban setting make it a distinct battlefield stop.', 'open', 'https://www.arkansas.com/helena-west-helena', null, 'America/Chicago', now()),
  ('Pillow-Thompson House', 'pillow-thompson-house', 'roadside-oddities', 34.53158, -90.58982, 'Helena-West Helena', 'AR', 'This elaborate Queen Anne mansion is one of Helena’s most striking surviving historic homes. Tours reveal ornate woodwork, period rooms and the grandeur of Delta-era wealth.', 'limited', 'https://www.phillipscountyarkansas.com/', null, 'America/Chicago', now()),
  ('President William Jefferson Clinton Birthplace Home', 'president-william-jefferson-clinton-birthplace-home', 'weird-history', 33.66858, -93.59139, 'Hope', 'AR', 'Bill Clinton’s first home is preserved as a National Historic Site in Hope. The small house offers an unusually intimate look at the early life of a future president.', 'open', 'https://www.nps.gov/wicl/', null, 'America/Chicago', now()),
  ('Klipsch Museum of Audio History', 'klipsch-museum-of-audio-history', 'museums', 33.73497, -93.6174, 'Hope', 'AR', 'Located near the historic Klipsch factory site, this museum preserves the life and inventions of audio pioneer Paul W. Klipsch. Vintage speakers, engineering prototypes and workshop material make it a niche technology-history stop.', 'limited', 'https://www.klipschmuseum.org/', null, 'America/Chicago', now()),
  ('Arkansas Alligator Farm & Petting Zoo', 'arkansas-alligator-farm-petting-zoo', 'roadside-oddities', 34.51816, -93.06834, 'Hot Springs', 'AR', 'Operating since 1902, this old-school animal attraction includes live alligators and a famously strange preserved ''merman'' display. The mix of roadside zoo history and odd taxidermy is pure OddWay.', 'open', 'https://alligatorfarmzoo.com/', null, 'America/Chicago', now()),
  ('Gangster Museum of America', 'gangster-museum-of-america', 'weird-history', 34.51253, -93.05412, 'Hot Springs', 'AR', 'This museum explores Hot Springs’ era as a gambling and organized-crime haven visited by figures such as Al Capone. Exhibits focus on casinos, bootlegging, law enforcement and the city’s underworld history.', 'open', 'https://tgmoa.com/', null, 'America/Chicago', now()),
  ('The Galaxy Connection', 'the-galaxy-connection', 'museums', 34.50373, -93.05684, 'Hot Springs', 'AR', 'A fan-built museum displays Star Wars toys, vintage action figures and pop-culture collectibles. Its dense, nostalgic collection is closer to a private obsession made public than a conventional museum.', 'limited', 'https://www.facebook.com/thegalaxyconnection/', null, 'America/Chicago', now()),
  ('Tiny Town', 'tiny-town', 'roadside-oddities', 34.51685, -93.06232, 'Hot Springs', 'AR', 'Tiny Town is a handmade miniature city filled with model trains, moving scenes, tunnels and tiny buildings. Much of the display was created by a single family over decades.', 'limited', 'https://www.tinytowntrains.com/', null, 'America/Chicago', now()),
  ('Josephine Tussaud Wax Museum', 'josephine-tussaud-wax-museum', 'museums', 34.51502, -93.05472, 'Hot Springs', 'AR', 'This vintage wax museum preserves the slightly uncanny atmosphere of old roadside wax attractions. Historical figures, celebrities and themed scenes fill multiple floors in downtown Hot Springs.', 'open', 'https://www.waxmuseumhotprings.com/', null, 'America/Chicago', now()),
  ('Bathhouse Row', 'bathhouse-row', 'weird-history', 34.51304, -93.05347, 'Hot Springs', 'AR', 'Eight historic bathhouses line Central Avenue over Hot Springs’ naturally heated thermal water. The architecture and long history of medical bathing make the district unlike any other national park streetscape.', 'open', 'https://www.nps.gov/hosp/learn/historyculture/bathhouse-row.htm', null, 'America/Chicago', now()),
  ('Fordyce Bathhouse', 'fordyce-bathhouse', 'museums', 34.51372, -93.05345, 'Hot Springs', 'AR', 'The restored Fordyce Bathhouse serves as the national park visitor center and preserves elaborate treatment rooms, tubs, exercise equipment and hydrotherapy spaces from the spa era.', 'open', 'https://www.nps.gov/hosp/learn/historyculture/fordyce-bathhouse.htm', null, 'America/Chicago', now()),
  ('Buckstaff Bathhouse', 'buckstaff-bathhouse', 'weird-history', 34.51272, -93.05339, 'Hot Springs', 'AR', 'Buckstaff is one of the few historic Bathhouse Row facilities still operating as a traditional bathhouse. Visitors can experience the old Hot Springs bathing ritual in a functioning historic building.', 'open', 'https://www.buckstaffbaths.com/', null, 'America/Chicago', now()),
  ('Arlington Resort Hotel & Spa', 'arlington-resort-hotel-spa', 'haunted', 34.51694, -93.05284, 'Hot Springs', 'AR', 'The landmark Arlington has accumulated decades of ghost stories alongside its long history as a grand resort hotel. Paranormal accounts often focus on guest rooms, hallways and the building’s older sections.', 'open', 'https://www.arlingtonhotel.com/', null, 'America/Chicago', now()),
  ('Hot Springs Mountain Tower', 'hot-springs-mountain-tower', 'roadside-oddities', 34.52163, -93.04194, 'Hot Springs', 'AR', 'A tall observation tower rises above Hot Springs National Park and the Ouachita Mountains. The current tower continues a long local tradition of lookout structures on the mountain.', 'open', 'https://hotspringstower.com/', null, 'America/Chicago', now()),
  ('Mammoth Spring State Park', 'mammoth-spring-state-park', 'roadside-oddities', 36.49621, -91.53282, 'Mammoth Spring', 'AR', 'One of the world’s largest springs forms a lake before feeding the Spring River. The park also preserves an old hydroelectric plant and railroad depot around the enormous water source.', 'open', 'https://www.arkansasstateparks.com/parks/mammoth-spring-state-park', null, 'America/Chicago', now()),
  ('Mammoth Spring Depot', 'mammoth-spring-depot', 'museums', 36.49673, -91.53212, 'Mammoth Spring', 'AR', 'A restored Frisco railroad depot inside Mammoth Spring State Park contains transportation exhibits and regional artifacts. Its location beside the massive spring makes it a compact double OddWay stop.', 'open', 'https://www.arkansasstateparks.com/parks/mammoth-spring-state-park', null, 'America/Chicago', now()),
  ('Jacob Wolf House', 'jacob-wolf-house', 'weird-history', 36.21046, -92.28701, 'Norfork', 'AR', 'Built in 1829, the Jacob Wolf House served as an early territorial courthouse and is one of Arkansas’s oldest surviving public structures. The log building preserves frontier government history in an unusually intact setting.', 'open', 'https://www.arkansasheritage.com/arkansas-preservation/properties/jacob-wolf-house', null, 'America/Chicago', now()),
  ('Crater of Diamonds State Park', 'crater-of-diamonds-state-park', 'roadside-oddities', 34.0325, -93.67443, 'Murfreesboro', 'AR', 'Visitors can search a plowed volcanic field for real diamonds and keep what they find. It is one of the only public diamond-bearing sites in the world where found stones belong to the visitor.', 'open', 'https://www.arkansasstateparks.com/parks/crater-diamonds-state-park', null, 'America/Chicago', now()),
  ('Ka-Do-Ha Indian Village Museum', 'ka-do-ha-indian-village-museum', 'museums', 34.0616, -93.71837, 'Murfreesboro', 'AR', 'This privately operated attraction combines archaeological interpretation, reconstructed village elements and gem-mining activities. Its old-school roadside presentation makes it distinct from Arkansas’s state-run mound sites.', 'limited', 'https://www.kadoha.com/', null, 'America/Chicago', now()),
  ('Bob Jackson Memorial Museum of Funeral Service', 'bob-jackson-memorial-museum-of-funeral-service', 'museums', 35.60477, -91.28171, 'Newport', 'AR', 'This appointment-based museum explores funeral history through antique hearses, caskets, embalming tools and mortuary equipment. It is one of the state’s most macabre specialist collections.', 'limited', 'https://onlyinark.com/places-and-travel/central-and-eastern-arkansas-oddities-and-roadside-attractions/', null, 'America/Chicago', now()),
  ('Jacksonport State Park', 'jacksonport-state-park', 'weird-history', 35.64273, -91.31331, 'Newport', 'AR', 'The restored 1872 courthouse and surrounding riverfront preserve a once-important White River port town. Exhibits cover steamboats, Civil War activity and regional river history.', 'open', 'https://www.arkansasstateparks.com/parks/jacksonport-state-park', null, 'America/Chicago', now()),
  ('Norphlet Crater', 'norphlet-crater', 'weird-history', 33.31672, -92.6624, 'Norphlet', 'AR', 'A dramatic oil-well blowout in 1922 left a crater-like scar and became part of the story of Arkansas’s early oil boom. The site is remembered locally as the Norphlet Crater.', 'roadside', 'https://encyclopediaofarkansas.net/', null, 'America/Chicago', now()),
  ('Arkansas Museum of Natural Resources', 'arkansas-museum-of-natural-resources', 'museums', 33.33695, -92.71433, 'Smackover', 'AR', 'This state museum interprets the south Arkansas oil boom with drilling equipment, recreated boomtown scenes and industrial artifacts. Outdoor machinery gives it a strong roadside-mechanical feel.', 'open', 'https://www.arkansasheritage.com/arkansas-museums/arkansas-museum-of-natural-resources', null, 'America/Chicago', now()),
  ('Old Mill at T.R. Pugh Memorial Park', 'old-mill-at-t-r-pugh-memorial-park', 'weird-history', 34.76916, -92.26455, 'North Little Rock', 'AR', 'The Old Mill is a 1930s recreation of an old gristmill built with concrete made to resemble weathered wood. It became famous after appearing in the opening of Gone with the Wind.', 'open', 'https://www.northlittlerock.org/the-old-mill/', null, 'America/Chicago', now()),
  ('USS Razorback', 'uss-razorback', 'museums', 34.7521, -92.26688, 'North Little Rock', 'AR', 'Visitors can tour the USS Razorback, a World War II-era submarine moored on the Arkansas River. Tight passageways, machinery and crew spaces remain accessible through guided tours.', 'limited', 'https://aimmuseum.org/', null, 'America/Chicago', now()),
  ('Arkansas Inland Maritime Museum', 'arkansas-inland-maritime-museum', 'museums', 34.7522, -92.26696, 'North Little Rock', 'AR', 'The museum interprets naval history around the USS Razorback and the tugboat Hoga. Its landlocked location on the Arkansas River makes the collection especially unexpected.', 'limited', 'https://aimmuseum.org/', null, 'America/Chicago', now()),
  ('Old State House Museum', 'old-state-house-museum', 'haunted', 34.74906, -92.27259, 'Little Rock', 'AR', 'Arkansas’s old capitol building is now a museum, but it is also frequently included in Little Rock ghost lore. Historic political spaces and reports of apparitions give the building a dual history-and-haunting appeal.', 'open', 'https://www.arkansasheritage.com/old-state-house-museum', null, 'America/Chicago', now()),
  ('Historic Arkansas Museum', 'historic-arkansas-museum', 'museums', 34.74642, -92.26904, 'Little Rock', 'AR', 'A cluster of preserved early Little Rock buildings surrounds galleries devoted to Arkansas history and material culture. The site includes some of the city’s oldest surviving structures.', 'open', 'https://www.arkansasheritage.com/historic-arkansas-museum', null, 'America/Chicago', now()),
  ('MacArthur Museum of Arkansas Military History', 'macarthur-museum-of-arkansas-military-history', 'haunted', 34.73838, -92.26534, 'Little Rock', 'AR', 'The museum occupies the historic Little Rock Arsenal tower, birthplace of Douglas MacArthur. The building’s age and military past have also generated long-running local ghost stories.', 'open', 'https://www.littlerock.gov/residents/parks-and-recreation/macarthur-museum-of-arkansas-military-history/', null, 'America/Chicago', now()),
  ('Human Dissection Monument', 'human-dissection-monument', 'weird-history', 34.73854, -92.2648, 'Little Rock', 'AR', 'A marker in MacArthur Park commemorates the first documented human dissection in Arkansas. The subject matter makes it one of downtown Little Rock’s stranger historical monuments.', 'roadside', 'https://onlyinark.com/places-and-travel/central-and-eastern-arkansas-oddities-and-roadside-attractions/', null, 'America/Chicago', now()),
  ('ESSE Purse Museum', 'esse-purse-museum', 'museums', 34.73404, -92.27351, 'Little Rock', 'AR', 'ESSE uses handbags and their contents to tell the story of 20th-century women’s lives and changing social roles. It is one of the few museums in the country built around the history of the purse.', 'open', 'https://essepursemuseum.com/', null, 'America/Chicago', now()),
  ('Mosaic Templars Cultural Center', 'mosaic-templars-cultural-center', 'museums', 34.74234, -92.27775, 'Little Rock', 'AR', 'This Arkansas Heritage museum interprets African American history and the Mosaic Templars of America, a fraternal organization founded in Little Rock in 1882.', 'open', 'https://www.arkansasheritage.com/mosaic-templars-cultural-center', null, 'America/Chicago', now()),
  ('H.U. Lee International Gate and Garden', 'h-u-lee-international-gate-and-garden', 'roadside-oddities', 34.74838, -92.26934, 'Little Rock', 'AR', 'An ornate Korean gateway and garden honor taekwondo pioneer H.U. Lee in downtown Little Rock. The monumental gate was constructed in Korea and reassembled in Arkansas.', 'open', 'https://www.littlerock.gov/', null, 'America/Chicago', now()),
  ('La Petite Roche', 'la-petite-roche', 'weird-history', 34.74863, -92.26544, 'Little Rock', 'AR', 'A small exposed rock and marker preserve the geological feature that gave Little Rock its name. The original river landmark was noted by French explorer Jean-Baptiste Bénard de la Harpe in 1722.', 'roadside', 'https://onlyinark.com/places-and-travel/central-and-eastern-arkansas-oddities-and-roadside-attractions/', null, 'America/Chicago', now()),
  ('Mount Holly Cemetery', 'mount-holly-cemetery', 'weird-history', 34.7381, -92.27847, 'Little Rock', 'AR', 'Known as the ''Westminster Abbey of Arkansas,'' Mount Holly contains ornate monuments and the graves of governors, senators, soldiers and other notable Arkansans. Its age and elaborate funerary art make it a strong cemetery stop.', 'open', 'https://mounthollycemetery.org/', null, 'America/Chicago', now()),
  ('Museum of Discovery', 'museum-of-discovery', 'museums', 34.74754, -92.26426, 'Little Rock', 'AR', 'Arkansas’s oldest science museum mixes hands-on exhibits with oddities from natural history and technology. Its collection roots stretch back to an early cabinet-style museum.', 'open', 'https://museumofdiscovery.org/', null, 'America/Chicago', now()),
  ('Arkansas State Capitol', 'arkansas-state-capitol', 'roadside-oddities', 34.74648, -92.28933, 'Little Rock', 'AR', 'The Arkansas State Capitol is built on the site of the former state penitentiary and incorporates stone quarried by prison labor. Its grand dome and unusual site history give it more OddWay relevance than a typical capitol.', 'open', 'https://www.sos.arkansas.gov/state-capitol', null, 'America/Chicago', now()),
  ('Little Rock Central High School National Historic Site', 'little-rock-central-high-school-national-historic-site', 'weird-history', 34.73695, -92.29988, 'Little Rock', 'AR', 'The school became the center of the 1957 desegregation crisis when the Little Rock Nine entered under federal protection. The preserved school and NPS visitor center interpret one of the defining confrontations of the civil rights era.', 'open', 'https://www.nps.gov/chsc/', null, 'America/Chicago', now()),
  ('Plum Bayou Mounds Archeological State Park', 'plum-bayou-mounds-archeological-state-park', 'weird-history', 34.64592, -92.06037, 'Scott', 'AR', 'Formerly known as Toltec Mounds, this park protects a major prehistoric ceremonial complex with multiple earthen mounds. The tallest surviving mound in Arkansas is part of the site.', 'open', 'https://www.arkansasstateparks.com/parks/plum-bayou-mounds-archeological-state-park', null, 'America/Chicago', now()),
  ('Plantation Agriculture Museum', 'plantation-agriculture-museum', 'museums', 34.69527, -92.09709, 'Scott', 'AR', 'A cotton gin, farm equipment and recreated exhibits tell the story of plantation agriculture in the Arkansas Delta. The museum preserves both the machinery and social history of the region’s cotton economy.', 'open', 'https://www.arkansasstateparks.com/parks/plantation-agriculture-museum', null, 'America/Chicago', now()),
  ('Parkin Archeological State Park', 'parkin-archeological-state-park', 'weird-history', 35.27195, -90.55777, 'Parkin', 'AR', 'This state park preserves a major Mississippian village site believed to be the Casqui settlement visited by the de Soto expedition in 1541. A surviving mound and archaeological remains sit beside the St. Francis River.', 'open', 'https://www.arkansasstateparks.com/parks/parkin-archeological-state-park', null, 'America/Chicago', now()),
  ('Louisiana Purchase State Park', 'louisiana-purchase-state-park', 'weird-history', 34.64572, -91.05197, 'Blackton', 'AR', 'A limestone monument deep in a headwater swamp marks the initial point used to survey lands acquired in the Louisiana Purchase. A boardwalk leads through cypress and tupelo forest to the surprisingly remote marker.', 'open', 'https://www.arkansasstateparks.com/parks/louisiana-purchase-state-park', null, 'America/Chicago', now()),
  ('Arkansas Post National Memorial', 'arkansas-post-national-memorial', 'weird-history', 34.01946, -91.34535, 'Gillett', 'AR', 'Arkansas Post preserves the site of an early European settlement, trading post and Civil War battlefield near the Arkansas River. Layers of colonial, Indigenous and military history overlap in one landscape.', 'open', 'https://www.nps.gov/arpo/', null, 'America/Chicago', now()),
  ('Rohwer Relocation Center Memorial Cemetery', 'rohwer-relocation-center-memorial-cemetery', 'weird-history', 33.77057, -91.28564, 'Rohwer', 'AR', 'The cemetery and memorial preserve the most visible remains of the Rohwer Japanese American incarceration camp. Monuments and headstones stand amid farmland where thousands were confined during World War II.', 'open', 'https://rohwer.astate.edu/', null, 'America/Chicago', now()),
  ('Sultana Disaster Museum', 'sultana-disaster-museum', 'weird-history', 35.2148, -90.19628, 'Marion', 'AR', 'This museum tells the story of the 1865 explosion and sinking of the steamboat Sultana, one of the deadliest maritime disasters in U.S. history. Many victims were recently released Union prisoners of war.', 'open', 'https://sultanadisastermuseum.com/', null, 'America/Chicago', now()),
  ('Hemingway-Pfeiffer Museum and Educational Center', 'hemingway-pfeiffer-museum-and-educational-center', 'weird-history', 36.38007, -90.19443, 'Piggott', 'AR', 'Ernest Hemingway wrote portions of A Farewell to Arms in a converted barn behind the Pfeiffer family home. The preserved house and writing studio create an unusually specific literary pilgrimage site.', 'limited', 'https://hemingway.astate.edu/', null, 'America/Chicago', now()),
  ('Southern Tenant Farmers Museum', 'southern-tenant-farmers-museum', 'weird-history', 35.49163, -90.35877, 'Tyronza', 'AR', 'The museum occupies the former building where the Southern Tenant Farmers Union was organized in 1934. Exhibits cover sharecropping, labor organizing and the harsh economics of Delta agriculture.', 'open', 'https://stfm.astate.edu/', null, 'America/Chicago', now()),
  ('Lakeport Plantation', 'lakeport-plantation', 'weird-history', 33.25688, -91.15547, 'Lake Village', 'AR', 'This restored antebellum plantation house interprets architecture, enslaved labor and plantation life in the Mississippi Delta. Preservation work intentionally exposes layers of the building’s construction history.', 'limited', 'https://lakeport.astate.edu/', null, 'America/Chicago', now()),
  ('Hampson Archeological Museum State Park', 'hampson-archeological-museum-state-park', 'weird-history', 35.5689, -90.04183, 'Wilson', 'AR', 'The museum displays artifacts from the nearby Nodena site, a major Mississippian settlement. Pottery, tools and human-scale reconstructions reveal a sophisticated culture that flourished in the Delta before European contact.', 'open', 'https://www.arkansasstateparks.com/parks/hampson-archeological-museum-state-park', null, 'America/Chicago', now()),
  ('Prairie Grove Battlefield State Park', 'prairie-grove-battlefield-state-park', 'weird-history', 35.98619, -94.30577, 'Prairie Grove', 'AR', 'One of Arkansas’s best-preserved Civil War battlefields surrounds a museum and historic village. Walking and driving routes cross fields and ridges that remain strikingly similar to the 1862 landscape.', 'open', 'https://www.arkansasstateparks.com/parks/prairie-grove-battlefield-state-park', null, 'America/Chicago', now()),
  ('Historic Washington State Park', 'historic-washington-state-park', 'weird-history', 33.77421, -93.68344, 'Washington', 'AR', 'An entire 19th-century Arkansas town has been preserved as a state park, including courthouses, homes, shops and a blacksmith shop associated with Bowie-knife history. The result feels more like entering a preserved town than visiting a single museum.', 'open', 'https://www.arkansasstateparks.com/parks/historic-washington-state-park', null, 'America/Chicago', now()),
  ('Powhatan Historic State Park', 'powhatan-historic-state-park', 'weird-history', 36.08183, -91.11938, 'Powhatan', 'AR', 'A restored 1888 courthouse and nearby historic buildings preserve a once-important Black River port community. The small hilltop complex feels unusually intact for a town that lost most of its former importance.', 'open', 'https://www.arkansasstateparks.com/parks/powhatan-historic-state-park', null, 'America/Chicago', now()),
  ('Davidsonville Historic State Park', 'davidsonville-historic-state-park', 'weird-history', 36.15473, -91.05376, 'Pocahontas', 'AR', 'Archaeological remains mark one of Arkansas Territory’s earliest towns, which was largely abandoned by the 1830s. Trails and interpretation reveal foundations and streets from a community that effectively vanished.', 'open', 'https://www.arkansasstateparks.com/parks/davidsonville-historic-state-park', null, 'America/Chicago', now()),
  ('Pocahontas Meteor', 'pocahontas-meteor', 'folklore', 36.26146, -90.97123, 'Pocahontas', 'AR', 'A large rock on the Randolph County Courthouse lawn was long celebrated as a meteorite supposedly recovered from the Black River. Geologists later identified it as ordinary rock, but the false meteor remains beloved local folklore.', 'roadside', 'https://onlyinark.com/places-and-travel/central-and-eastern-arkansas-oddities-and-roadside-attractions/', null, 'America/Chicago', now()),
  ('Ravenden Raven', 'ravenden-raven', 'roadside-oddities', 36.23397, -91.25191, 'Ravenden', 'AR', 'A large black raven statue greets travelers in Ravenden, turning the town’s name into a literal roadside mascot. It is simple, strange and exactly the kind of tiny-town marker OddWay is built to surface.', 'roadside', 'https://www.roadsideamerica.com/location/stateIndex.php?state=AR', null, 'America/Chicago', now()),
  ('Museum of Automobiles', 'museum-of-automobiles', 'museums', 35.13047, -92.91334, 'Morrilton', 'AR', 'Located atop Petit Jean Mountain, the Museum of Automobiles displays vintage and rare cars in an unexpected rural setting. The collection includes vehicles tied to Arkansas motoring history.', 'open', 'https://museumofautos.com/', null, 'America/Chicago', now()),
  ('Petit Jean Grave', 'petit-jean-grave', 'folklore', 35.12776, -92.92753, 'Morrilton', 'AR', 'A grave-like stone mound near the overlook is tied to the legend of Petit Jean, a young woman said to have disguised herself to follow her fiancé to America. The tale gave the mountain and state park their names.', 'open', 'https://www.arkansasstateparks.com/parks/petit-jean-state-park', null, 'America/Chicago', now()),
  ('Old Spanish Treasure Cave', 'old-spanish-treasure-cave', 'folklore', 36.48373, -94.45826, 'Sulphur Springs', 'AR', 'Guided tours pass through an Ozark cave associated with a long-running legend of hidden Spanish treasure. The attraction mixes real cave geology with treasure-hunt folklore.', 'limited', 'https://spanish-treasure-cave.com/', null, 'America/Chicago', now()),
  ('Daisy Airgun Museum', 'daisy-airgun-museum', 'museums', 36.33364, -94.12081, 'Rogers', 'AR', 'The Daisy Museum preserves more than a century of BB-gun history, including Red Ryder models, prototypes, advertising and manufacturing artifacts. It is a niche but distinctly American industrial collection.', 'open', 'https://daisymuseum.com/', null, 'America/Chicago', now()),
  ('World’s Largest Daisy BB Gun', 'worlds-largest-daisy-bb-gun', 'roadside-oddities', 36.33366, -94.12076, 'Rogers', 'AR', 'A 25-foot-tall Red Ryder BB gun replica stands outside the Daisy Museum in downtown Rogers. Installed in 2021, it is one of Arkansas’s most literal ''world’s largest'' roadside attractions.', 'roadside', 'https://www.arkansas.com/plan-your-trip/plan/trip-ideas-itineraries/the-worlds-largest-daisy-bb-gun', null, 'America/Chicago', now()),
  ('War Eagle Cavern', 'war-eagle-cavern', 'roadside-oddities', 36.29541, -93.90472, 'Rogers', 'AR', 'The entrance to War Eagle Cavern sits directly on Beaver Lake, leading into a cave with an underground stream, domes and waterfalls. Visitors can even approach the attraction by boat.', 'limited', 'https://wareaglecavern.com/', null, 'America/Chicago', now()),
  ('Pea Ridge National Military Park', 'pea-ridge-national-military-park', 'weird-history', 36.45438, -94.03468, 'Garfield', 'AR', 'Pea Ridge preserves one of the most intact Civil War battlefields in the country. The battlefield includes Elkhorn Tavern, artillery positions, historic roads and extensive preserved terrain.', 'open', 'https://www.nps.gov/peri/', null, 'America/Chicago', now()),
  ('Rush Ghost Town', 'rush-ghost-town', 'weird-history', 36.129, -92.5755, 'Yellville', 'AR', 'Abandoned mining buildings and foundations remain along the Buffalo National River at Rush, once a zinc-boom community. Trails lead past ruined structures and mine-era remnants in a remote valley.', 'open', 'https://www.nps.gov/buff/learn/historyculture/rush-historic-district.htm', null, 'America/Chicago', now()),
  ('Ozark Folk Center State Park', 'ozark-folk-center-state-park', 'folklore', 35.86989, -92.11769, 'Mountain View', 'AR', 'This state park preserves living Ozark traditions through music, crafts, blacksmithing, herbal gardens and demonstrations. It is one of the strongest places in Arkansas to encounter folklore as a living practice rather than just a museum display.', 'limited', 'https://www.arkansasstateparks.com/parks/ozark-folk-center-state-park', null, 'America/Chicago', now()),
  ('Arkansas Air and Military Museum', 'arkansas-air-and-military-museum', 'museums', 36.00839, -94.16909, 'Fayetteville', 'AR', 'Historic aircraft crowd a wooden hangar at Fayetteville’s Drake Field, including military planes, racing aircraft and experimental designs. The vintage hangar itself adds to the atmosphere.', 'open', 'https://www.arkansasairandmilitary.com/', null, 'America/Chicago', now()),
  ('Eiffel Tower Replica', 'eiffel-tower-replica', 'roadside-oddities', 35.29203, -93.72839, 'Paris', 'AR', 'Downtown Paris has its own miniature Eiffel Tower, complete with a public plaza and Arkansas personality. The obvious name-based joke has become the town’s signature photo stop.', 'roadside', 'https://www.parisarkansas.com/', null, 'America/Chicago', now()),
  ('Mount Magazine Signal Hill', 'mount-magazine-signal-hill', 'roadside-oddities', 35.16794, -93.64448, 'Paris', 'AR', 'Signal Hill marks Arkansas’s highest natural point, but the summit is surprisingly subtle rather than dramatic. A stone map-shaped marker identifies the high point in the forest.', 'open', 'https://www.arkansasstateparks.com/parks/mount-magazine-state-park', null, 'America/Chicago', now()),
  ('Beatles at the Ridge Monument', 'beatles-at-the-ridge-monument', 'weird-history', 36.06834, -90.95654, 'Walnut Ridge', 'AR', 'A large sculpture recreates the Beatles’ Abbey Road walk in Walnut Ridge, commemorating the band’s brief 1964 visit to the local airport. It is one of Arkansas’s strangest pieces of pop-music public art.', 'roadside', 'https://www.beatlesattheridge.com/', null, 'America/Chicago', now()),
  ('Guitar Walk', 'guitar-walk', 'weird-history', 36.06792, -90.95628, 'Walnut Ridge', 'AR', 'An outdoor walkway shaped like a giant guitar celebrates musicians connected to northeast Arkansas and nearby rockabilly history. Interpretive plaques turn the oversized instrument into a walkable music exhibit.', 'open', 'https://www.beatlesattheridge.com/', null, 'America/Chicago', now()),
  ('Parachute Inn Boeing 737', 'parachute-inn-boeing-737', 'roadside-oddities', 36.12556, -90.92532, 'Walnut Ridge', 'AR', 'A retired Boeing 737 became part of a restaurant complex near Walnut Ridge’s airport, creating one of the state’s more surreal aviation roadside sights. The aircraft itself is the attraction even when the business changes.', 'limited', 'https://www.roadsideamerica.com/location/stateIndex.php?state=AR', null, 'America/Chicago', now()),
  ('Arkansas Entertainers Hall of Fame', 'arkansas-entertainers-hall-of-fame', 'museums', 34.22623, -92.00371, 'Pine Bluff', 'AR', 'Inside the Pine Bluff Convention Center, this hall of fame collects costumes, instruments and memorabilia from famous Arkansans in music, film, television and literature.', 'limited', 'https://arentertainershalloffame.org/', null, 'America/Chicago', now()),
  ('Arkansas Railroad Museum', 'arkansas-railroad-museum', 'museums', 34.22681, -92.00106, 'Pine Bluff', 'AR', 'The museum preserves large steam and diesel locomotives, railroad cars and shop equipment connected to the Cotton Belt line. Much of the collection occupies an enormous working-era railroad shop.', 'limited', 'https://arkansasrailroadmuseum.org/', null, 'America/Chicago', now()),
  ('Mammoth Orange Cafe', 'mammoth-orange-cafe', 'roadside-oddities', 34.44555, -92.18349, 'Redfield', 'AR', 'This tiny orange-shaped roadside stand has served travelers along U.S. 65 for decades. Its giant citrus form is a surviving example of novelty roadside architecture.', 'open', 'https://onlyinark.com/places-and-travel/central-and-eastern-arkansas-oddities-and-roadside-attractions/', null, 'America/Chicago', now()),
  ('Roundtop Filling Station', 'roundtop-filling-station', 'roadside-oddities', 34.81585, -92.22405, 'Sherwood', 'AR', 'A tiny round 1930s filling station survives beside the road in Sherwood. Its circular plan and compact canopy make it a rare piece of early automobile architecture.', 'roadside', 'https://www.roadsideamerica.com/location/stateIndex.php?state=AR', null, 'America/Chicago', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;

select count(*) as arkansas from public.stops where state = 'AR';
