-- Colorado. This closes the Denver corridor.
--
-- The state had four stops and three of them are the same places as entries in
-- this file, under scan-era names. They are deleted rather than merged, which
-- is a change from how every other state has been handled, and the reason is
-- coordinates.
--
-- The on-conflict clause updates descriptions and sources but deliberately
-- leaves latitude and longitude alone — overwriting a checked coordinate with
-- an unchecked one is the wrong default. Here that default is backwards: the
-- old rows came from an automated scan and are wrong by more than a kilometre.
-- Ashcroft Ghost Town is 1.2km out and the Ghost Town Museum 1.4km, which on a
-- mountain road is the difference between finding it and driving past.
--
-- So the scan rows go and the researched ones replace them. Sasquatch Outpost
-- is the same story at 686 metres, under a shorter name.
--
-- Well sourced: colorado.com, nps.gov and blm.gov are the top three.
--
-- Three proximity flags kept. The cryonics museum really is 30 metres from the
-- Stanley Hotel's tour desk, because it is in the basement.
--
-- 150 stops, every one with a source.

/*
  Delete first, so the insert below creates fresh rows with correct positions
  rather than updating the old ones and keeping their coordinates.
*/
delete from public.stops
where state = 'CO'
  and slug in ('ashcroft-ghost-town', 'ghost-town-wild-west-museum', 'sasquatch-outpost');

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('UFO Watchtower', 'ufo-watchtower', 'ufos', 37.78856, -105.88722, 'Hooper', 'CO', 'A 10-foot observation platform in the San Luis Valley built for sky-watchers, surrounded by UFO sighting lore and a small ''healing garden.'' Camping is offered on site, making it one of Colorado''s most direct extraterrestrial-themed road-trip stops.', 'open', 'https://www.colorado.com/center/ufo-watchtower', null, 'America/Denver', now()),
  ('Sasquatch Outpost & Sasquatch Encounter Discovery Museum', 'sasquatch-outpost-sasquatch-encounter-discovery-museum', 'cryptids', 39.40605, -105.47505, 'Bailey', 'CO', 'A Bigfoot-focused store and small museum devoted to Sasquatch reports, footprint casts and regional encounter stories. The stop is built around cryptozoology rather than a generic souvenir shop, which makes it a strong OddWay fit.', 'open', 'https://www.colorado.com/bailey/attractions-entertainment/museums/sasquatch-outpost', null, 'America/Denver', now()),
  ('Colorado Gators Reptile Park', 'colorado-gators-reptile-park', 'roadside-oddities', 37.70545, -105.87057, 'Mosca', 'CO', 'A geothermal-water fish farm that evolved into a reptile rescue filled with alligators, crocodilians, snakes and other unusual animals in the San Luis Valley. The improbable high-desert setting is a major part of the appeal.', 'open', 'https://coloradogators.com/', null, 'America/Denver', now()),
  ('Cano''s Castle', 'canos-castle', 'roadside-oddities', 37.08128, -106.00611, 'Antonito', 'CO', 'A towering self-built complex faced with beer cans, hubcaps and scrap metal, created by Vietnam veteran Dominic ''Cano'' Espinoza. It is best treated as a public-road viewing stop; the structures are private property and were damaged by a 2022 fire.', 'roadside', 'https://www.colorado.com/antonito/cano%27s-castle', null, 'America/Denver', now()),
  ('Coney Island Boardwalk Hot Dog', 'coney-island-boardwalk-hot-dog', 'roadside-oddities', 39.4085, -105.4933, 'Bailey', 'CO', 'A restaurant inside a giant hot-dog-shaped building that has moved around Colorado before settling in Bailey. The building itself is the attraction, with food service providing a legitimate reason to stop rather than just photograph it from the road.', 'open', 'https://www.colorado.com/bailey/dining-restaurants/casual-dining/coney-island-boardwalk', null, 'America/Denver', now()),
  ('May Natural History Museum', 'may-natural-history-museum', 'museums', 38.70907, -104.84801, 'Colorado Springs', 'CO', 'An old-school insect museum displaying thousands of preserved butterflies, beetles, spiders, scorpions and other arthropods collected over generations. Its densely packed cases and family-run roadside-museum feel are far stranger than a conventional natural-history gallery.', 'limited', 'https://www.coloradospringsbugmuseum.com/', null, 'America/Denver', now()),
  ('Herkimer the Giant Beetle', 'herkimer-the-giant-beetle', 'roadside-oddities', 38.70264, -104.82743, 'Colorado Springs', 'CO', 'A 48-times-scale Hercules beetle named Herkimer has marked the Highway 115 turn for the May Museum since the 1950s. Restored in 2022, it is a legitimate giant roadside landmark rather than a temporary promotional prop.', 'roadside', 'https://www.coloradospringsbugmuseum.com/herkimer-worlds-largest-beetle.html', null, 'America/Denver', now()),
  ('Tiny Town & Railroad', 'tiny-town-railroad', 'roadside-oddities', 39.60667, -105.225, 'Morrison', 'CO', 'A long-running miniature village filled with roughly one-sixth-scale buildings plus a small-gauge railroad. Its tiny streets and architecture make it a literal scaled-down town rather than a standard amusement park.', 'limited', 'https://www.colorado.com/morrison/attractions-entertainment/amusement-parks-play-centers-indoor-entertainment/tiny-town-railroad', null, 'America/Denver', now()),
  ('Indian Hills Punny Sign', 'indian-hills-punny-sign', 'roadside-oddities', 39.61957, -105.2421, 'Indian Hills', 'CO', 'The Indian Hills Community Center sign is locally famous for a rotating stream of groan-worthy puns and one-liners. The sign is visible from the public road; the community center itself is not an attraction unless an event is open to the public.', 'roadside', 'https://indianhillsco.org/community-center/', null, 'America/Denver', now()),
  ('Kit Carson County Carousel', 'kit-carson-county-carousel', 'roadside-oddities', 39.30912, -102.27071, 'Burlington', 'CO', 'A 1905 Philadelphia Toboggan Company carousel with hand-carved animals and its original band organ, preserved on the eastern plains. It is a National Historic Landmark and still operates for riders during its public season.', 'limited', 'https://www.kitcarsoncountycarousel.com/', null, 'America/Denver', now()),
  ('Carousel of Happiness', 'carousel-of-happiness', 'roadside-oddities', 39.96011, -105.51007, 'Nederland', 'CO', 'A restored historic carousel populated with hand-carved animals created over decades by Vietnam veteran Scott Harrison. The combination of folk sculpture, moving figures and a century-old carousel mechanism makes it unusually personal.', 'open', 'https://carouselofhappiness.org/', null, 'America/Denver', now()),
  ('Petrified Wood Gas Station', 'petrified-wood-gas-station', 'roadside-oddities', 38.09447, -102.62018, 'Lamar', 'CO', 'A 1930s former filling station faced with enormous quantities of petrified wood, built specifically to stop highway travelers. The structure survives along Main Street and is best treated as an exterior roadside stop.', 'roadside', 'https://www.colorado.com/articles/quirky-roadside-attractions-colorado', null, 'America/Denver', now()),
  ('World''s Largest Fork', 'worlds-largest-fork', 'roadside-oddities', 37.8499, -106.9264, 'Creede', 'CO', 'A roughly 40-foot aluminum fork created by local artists to out-measure an earlier giant fork in Missouri. It is pure oversized-roadside-object territory and an easy add-on while exploring Creede.', 'roadside', 'https://www.colorado.com/articles/quirky-roadside-attractions-colorado', null, 'America/Denver', now()),
  ('Seven Keys Lodge Key Collection', 'seven-keys-lodge-key-collection', 'museums', 40.30855, -105.53411, 'Estes Park', 'CO', 'The historic lodge formerly known as the Baldpate Inn maintains a huge collection of keys donated by visitors from around the world. The Key Room turns an operating mountain lodge into one of Colorado''s stranger object-collection stops.', 'limited', 'https://sevenkeyslodge.com/', null, 'America/Denver', now()),
  ('Casa Bonita', 'casa-bonita', 'roadside-oddities', 39.74258, -105.07057, 'Lakewood', 'CO', 'A sprawling pink Mexican restaurant built around indoor cliffs, waterfalls, divers, caves and theatrical spectacle. Entry is controlled by the restaurant''s current reservation/ticket system, so this is a planned stop rather than a casual walk-in.', 'limited', 'https://www.casabonitadenver.com/', null, 'America/Denver', now()),
  ('International Church of Cannabis', 'international-church-of-cannabis', 'roadside-oddities', 39.70915, -104.98244, 'Denver', 'CO', 'A former Lutheran church transformed by the Elevationists into a brightly painted immersive art space with a psychedelic interior. Public experiences are separate from the congregation''s religious services, so visitors should use posted tour/event access.', 'limited', 'https://elevationists.org/', null, 'America/Denver', now()),
  ('Forney Museum of Transportation', 'forney-museum-of-transportation', 'museums', 39.7778, -104.97078, 'Denver', 'CO', 'A sprawling collection of vehicles and transportation artifacts ranging from antique cars and motorcycles to locomotives and unusual one-off machines. Its breadth and density make it a stronger OddWay stop than a normal automotive showroom.', 'open', 'https://www.forneymuseum.org/', null, 'America/Denver', now()),
  ('Wings Over the Rockies Air & Space Museum', 'wings-over-the-rockies-air-space-museum', 'museums', 39.72107, -104.89554, 'Denver', 'CO', 'Aviation and space hardware fills a former Lowry Air Force Base hangar, including military aircraft and Cold War-era technology. The preserved base setting adds a layer of strange military history to the aircraft collection.', 'open', 'https://wingsmuseum.org/', null, 'America/Denver', now()),
  ('Shelby American Collection', 'shelby-american-collection', 'museums', 40.06601, -105.20256, 'Boulder', 'CO', 'A specialist collection of Shelby Cobras, GT40s and other historically important performance cars. Public hours are limited compared with a conventional museum, so visitors should verify the collection''s schedule before routing here.', 'limited', 'https://shelbyamericancollection.org/', null, 'America/Denver', now()),
  ('Museum of Colorado Prisons', 'museum-of-colorado-prisons', 'weird-history', 38.43931, -105.24719, 'Cañon City', 'CO', 'A prison museum inside the former Colorado Women''s Prison beside an active correctional complex. Cells, confiscated objects and execution-related material make it one of the state''s strongest dark-history museums.', 'open', 'https://prisonmuseum.org/', null, 'America/Denver', now()),
  ('Museum of the Mountain West', 'museum-of-the-mountain-west', 'museums', 38.48812, -107.81331, 'Montrose', 'CO', 'A privately assembled collection of recreated Old West storefronts and thousands of period artifacts laid out like a small town. It feels closer to walking through a collector-built settlement than visiting a conventional gallery.', 'open', 'https://museumofthemountainwest.org/', null, 'America/Denver', now()),
  ('Ghost Town Museum', 'ghost-town-museum', 'museums', 38.84057, -104.86065, 'Colorado Springs', 'CO', 'Historic structures and artifacts were moved indoors and arranged as a walk-through mining-era town. It offers the atmosphere of a ghost town without requiring a rough mountain road or entry into unstable abandoned buildings.', 'open', 'https://ghosttownmuseum.com/', null, 'America/Denver', now()),
  ('Michael Garman''s Magic Town', 'michael-garmans-magic-town', 'roadside-oddities', 38.84708, -104.86187, 'Colorado Springs', 'CO', 'A dense one-sixth-scale cityscape built by sculptor Michael Garman, packed with tiny rooms, alleys, characters and optical effects. The miniature streets reward slow looking and feel more like an inhabited model city than a normal sculpture gallery.', 'open', 'https://michaelgarman.com/museum-info/', null, 'America/Denver', now()),
  ('Rocky Mountain Motorcycle Museum', 'rocky-mountain-motorcycle-museum', 'museums', 38.83478, -104.82299, 'Colorado Springs', 'CO', 'A compact upstairs museum packed with early and mid-century motorcycles, racing history and rider memorabilia. Its free, volunteer-run collection is easy to miss from street level and unusually dense once inside.', 'open', 'https://www.themotorcyclemuseum.com/', null, 'America/Denver', now()),
  ('Pueblo Weisbrod Aircraft Museum', 'pueblo-weisbrod-aircraft-museum', 'museums', 38.28185, -104.49649, 'Pueblo', 'CO', 'Two hangars and an outdoor field hold military aircraft, missiles, engines and aviation artifacts at Pueblo Memorial Airport. The collection''s Cold War hardware and retired warbirds give it a strong machinery-and-military OddWay angle.', 'open', 'https://pwam.org/', null, 'America/Denver', now()),
  ('Denver Museum of Miniatures, Dolls & Toys', 'denver-museum-of-miniatures-dolls-toys', 'roadside-oddities', 39.74571, -104.96065, 'Denver', 'CO', 'A specialist museum devoted to dollhouses, miniatures, dolls and toys, with exhibits that compress domestic spaces and entire scenes into tiny scale. It is a niche collection rather than a general children''s museum.', 'open', 'https://www.dmmdt.org/', null, 'America/Denver', now()),
  ('Koshare Museum', 'koshare-museum', 'museums', 37.97203, -103.54461, 'La Junta', 'CO', 'A distinctive collection of Southwestern and Native American art housed beside the unusual Koshare Kiva. Visitors should treat the Indigenous material as museum interpretation and respect the institution''s rules around ceremonies and cultural objects.', 'open', 'https://koshares.com/museum/', null, 'America/Denver', now()),
  ('Fort Garland Museum & Cultural Center', 'fort-garland-museum-cultural-center', 'weird-history', 37.4241, -105.43158, 'Fort Garland', 'CO', 'A preserved frontier fort associated with Kit Carson and the U.S. Army''s expansion into the San Luis Valley. Modern exhibits also confront the complicated Indigenous, Hispano and military histories tied to the site.', 'open', 'https://www.historycolorado.org/fort-garland-museum-cultural-center', null, 'America/Denver', now()),
  ('El Pueblo History Museum & Trading Post Excavation', 'el-pueblo-history-museum-trading-post-excavation', 'weird-history', 38.26741, -104.61114, 'Pueblo', 'CO', 'The museum incorporates the archaeological remains of the 1840s El Pueblo trading post alongside a reconstructed adobe plaza. It is a rare place where a downtown museum and an excavated frontier settlement occupy the same stop.', 'open', 'https://www.historycolorado.org/el-pueblo-history-museum', null, 'America/Denver', now()),
  ('Trinidad History Museum: Baca House & Bloom Mansion', 'trinidad-history-museum-baca-house-bloom-mansion', 'weird-history', 37.1693, -104.5022, 'Trinidad', 'CO', 'Two very different 19th-century homes sit nearly side by side: the adobe Baca House and ornate Bloom Mansion. Together they preserve a compact cross-section of borderland, mercantile and industrial-boom history.', 'open', 'https://www.historycolorado.org/trinidad-history-museum', null, 'America/Denver', now()),
  ('Stanley Hotel Historic & Paranormal Tours', 'stanley-hotel-historic-paranormal-tours', 'haunted', 40.38331, -105.51831, 'Estes Park', 'CO', 'The 1909 Stanley Hotel is tied to decades of ghost stories and famously helped inspire Stephen King''s The Shining. Its guided history and paranormal tours present the legends as stories associated with the property rather than proof of supernatural activity.', 'limited', 'https://www.stanleyhotel.com/tours/', null, 'America/Denver', now()),
  ('International Cryonics Museum at The Stanley Hotel', 'international-cryonics-museum-at-the-stanley-hotel', 'museums', 40.38346, -105.51802, 'Estes Park', 'CO', 'A small museum at the Stanley interprets cryonics and the preservation of Bredo Morstoel, the man behind Nederland''s Frozen Dead Guy lore. The exhibit focuses on cryogenic preservation history; access is through the hotel''s scheduled tour program.', 'limited', 'https://www.stanleyhotel.com/tours/', null, 'America/Denver', now()),
  ('Molly Brown House Museum', 'molly-brown-house-museum', 'haunted', 39.73751, -104.98077, 'Denver', 'CO', 'The restored home of Titanic survivor and activist Margaret Brown is also part of Denver''s long-running ghost-tour lore. The documented history is the core attraction; paranormal claims are best treated as later stories attached to the house.', 'open', 'https://mollybrown.org/', null, 'America/Denver', now()),
  ('Brown Palace Hotel', 'brown-palace-hotel', 'haunted', 39.74411, -104.98787, 'Denver', 'CO', 'Denver''s 1892 Brown Palace has accumulated stories of unexplained sounds, apparitions and lingering former guests over more than a century of operation. It remains an active hotel, so public access should stay within hotel, dining or tour spaces.', 'open', 'https://www.colorado.com/articles/haunted-colorado-hot-spots-ghost-hunters', null, 'America/Denver', now()),
  ('Cheesman Park', 'cheesman-park', 'weird-history', 39.73281, -104.96646, 'Denver', 'CO', 'This city park occupies the former Mount Prospect Cemetery, where thousands of burials were removed during a scandal-plagued conversion to parkland. Reports that some graves were left behind underpin much of the park''s modern ghost lore.', 'open', 'https://www.colorado.com/articles/haunted-colorado-hot-spots-ghost-hunters', null, 'America/Denver', now()),
  ('Hotel Colorado', 'hotel-colorado', 'haunted', 39.54827, -107.32459, 'Glenwood Springs', 'CO', 'The grand 1893 hotel is wrapped in stories of spectral figures, phantom smells and wartime-era hauntings. It is still an operating hotel, so the OddWay interest is its documented age and folklore rather than unrestricted exploration.', 'open', 'https://www.colorado.com/articles/haunted-colorado-hot-spots-ghost-hunters', null, 'America/Denver', now()),
  ('Hotel Jerome', 'hotel-jerome', 'haunted', 39.1908, -106.8199, 'Aspen', 'CO', 'Aspen''s 1889 hotel carries a persistent legend about the ''water boy,'' a child apparition reportedly associated with the pool. The story is folklore attached to a still-operating luxury hotel and should be presented that way.', 'open', 'https://www.colorado.com/articles/haunted-colorado-hot-spots-ghost-hunters', null, 'America/Denver', now()),
  ('Strater Hotel', 'strater-hotel', 'haunted', 37.27124, -107.88175, 'Durango', 'CO', 'The ornate 1887 Strater is one of Durango''s best-preserved Victorian-era landmarks and has accumulated its own catalog of ghost stories. Visitors can experience the public hotel spaces without treating guest-only areas as an attraction.', 'open', 'https://strater.com/', null, 'America/Denver', now()),
  ('Victor Hotel', 'victor-hotel', 'haunted', 38.70985, -105.13985, 'Victor', 'CO', 'A historic mining-town hotel with a former elevator shaft, period rooms and local tales of a spectral miner known as Eddie. The building remains in use, so haunting stories are an added layer to a legitimate lodging stop.', 'open', 'https://www.colorado.com/articles/haunted-colorado-hot-spots-ghost-hunters', null, 'America/Denver', now()),
  ('Teller House', 'teller-house', 'haunted', 39.80031, -105.51255, 'Central City', 'CO', 'The 1872 Teller House is famous for its painted ''Face on the Barroom Floor'' and for ghost stories attached to Central City''s mining-boom past. Access depends on Central City Opera programming and public opening hours.', 'limited', 'https://centralcityopera.org/', null, 'America/Denver', now()),
  ('Central City Opera House', 'central-city-opera-house', 'haunted', 39.80117, -105.51364, 'Central City', 'CO', 'Colorado''s 1878 opera house survives from the mining boom and is associated with backstage and balcony ghost lore. It remains a working performance venue, so visits should follow event or tour access rather than treating it as an abandoned site.', 'limited', 'https://centralcityopera.org/', null, 'America/Denver', now()),
  ('Hotel de Paris Museum', 'hotel-de-paris-museum', 'haunted', 39.70822, -105.69402, 'Georgetown', 'CO', 'A remarkably intact 19th-century hotel museum preserving the story of French immigrant Louis Dupuy and Georgetown''s silver era. Its period rooms have also accumulated paranormal lore, but the documented hotel history is the main draw.', 'limited', 'https://www.hoteldeparismuseum.org/', null, 'America/Denver', now()),
  ('Miramont Castle Museum', 'miramont-castle-museum', 'haunted', 38.85934, -104.92246, 'Manitou Springs', 'CO', 'This rambling 1890s mansion combines multiple architectural styles, narrow passages and period interiors under one roof. Local haunting stories add to an already strange building, while the museum provides legitimate public access.', 'open', 'https://miramontcastle.org/', null, 'America/Denver', now()),
  ('Columbia Cemetery', 'columbia-cemetery', 'folklore', 40.00836, -105.28323, 'Boulder', 'CO', 'Boulder''s oldest cemetery holds pioneers, miners and other early residents beneath a wide mix of historic markers. Ghost stories are part of local lore, but this is an active historic cemetery and should be visited quietly during permitted hours.', 'open', 'https://bouldercolorado.gov/services/columbia-cemetery', null, 'America/Denver', now()),
  ('Evergreen Cemetery Chapel', 'evergreen-cemetery-chapel', 'folklore', 38.81676, -104.81025, 'Colorado Springs', 'CO', 'The historic chapel sits within one of Colorado Springs'' oldest cemeteries and is often included in local haunted-history accounts. The cemetery is a burial ground first, so OddWay routing should respect posted hours and any chapel access restrictions.', 'limited', 'https://www.coloradosprings.gov/cemetery', null, 'America/Denver', now()),
  ('Mount Pisgah Cemetery', 'mount-pisgah-cemetery', 'folklore', 38.74657, -105.19658, 'Cripple Creek', 'CO', 'A high-elevation cemetery filled with mining-era graves overlooking Cripple Creek. Local ghost stories and dramatic headstones make it an atmospheric stop, but cemetery etiquette and daylight access should govern visits.', 'open', 'https://www.colorado.com/articles/haunted-colorado-hot-spots-ghost-hunters', null, 'America/Denver', now()),
  ('Linwood Cemetery & Doc Holliday Memorial', 'linwood-cemetery-doc-holliday-memorial', 'folklore', 39.53961, -107.31942, 'Glenwood Springs', 'CO', 'A steep trail leads to the pioneer cemetery where a memorial marks the uncertain burial area of gambler and gunfighter Doc Holliday. The exact grave location is unknown, which is part of the site''s enduring mystery.', 'limited', 'https://www.visitglenwood.com/things-to-do/history/doc-hollidays-grave/', null, 'America/Denver', now()),
  ('Gold Camp Road Tunnels', 'gold-camp-road-tunnels', 'haunted', 38.8053, -104.9032, 'Colorado Springs', 'CO', 'Old railroad tunnels along Gold Camp Road are central to one of Colorado Springs'' most persistent ghost legends, involving supposed voices and handprints. The supernatural story is folklore; the surviving tunnels and former rail grade are the tangible stop.', 'open', 'https://www.visitcos.com/blog/haunted-places-in-colorado-springs/', null, 'America/Denver', now()),
  ('Old Homestead House Museum', 'old-homestead-house-museum', 'weird-history', 38.74623, -105.17779, 'Cripple Creek', 'CO', 'This preserved 1896 parlor house interprets Cripple Creek''s legal red-light district and the women who worked there during the gold boom. Its subject matter gives it a distinctly different angle from the town''s mining museums and casinos.', 'limited', 'https://oldhomesteadhouse.com/', null, 'America/Denver', now()),
  ('Outlaws & Law Men Jail Museum', 'outlaws-law-men-jail-museum', 'weird-history', 38.74697, -105.17847, 'Cripple Creek', 'CO', 'The former Teller County jail preserves cells, law-enforcement artifacts and stories of prisoners from the mining era. The building''s original carceral spaces make this a compact dark-history stop rather than a generic local museum.', 'limited', 'https://www.visitcripplecreek.com/attractions/outlaws-law-men-jail-museum/', null, 'America/Denver', now()),
  ('St. Elmo Ghost Town', 'st-elmo-ghost-town', 'weird-history', 38.7036, -106.3452, 'St. Elmo', 'CO', 'One of Colorado''s best-preserved mining ghost towns, with a surviving main street, cabins and a seasonal general store. Many buildings are privately owned, so visitors should stay on public ways and enter only structures explicitly open to the public.', 'limited', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Independence Ghost Town', 'independence-ghost-town', 'weird-history', 39.1072, -106.6059, 'Independence', 'CO', 'Ruins of a high-elevation gold camp sit beside Independence Pass, including cabin walls and interpretive remains from the short-lived 1879 boom. Snow closes the pass seasonally, and visitors should remain on established trails around the fragile structures.', 'limited', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Ashcroft Ghost Town', 'ashcroft-ghost-town', 'weird-history', 39.05559, -106.79956, 'Ashcroft', 'CO', 'A preserved silver-mining settlement south of Aspen with standing buildings and interpretive access. The site is managed for visitation, but winter access and seasonal road conditions can substantially change how it is reached.', 'limited', 'https://aspenhistory.org/visit/ashcroft-ghost-town/', null, 'America/Denver', now()),
  ('Tincup Historic Mining Town', 'tincup-historic-mining-town', 'weird-history', 38.75523, -106.47985, 'Tincup', 'CO', 'A remote former mining town that still has seasonal residents, an old cemetery and historic cabins around a high-country crossroads. It is not an abandoned playground; private homes and property remain mixed among the historic fabric.', 'limited', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Vicksburg Historic Mining Camp', 'vicksburg-historic-mining-camp', 'weird-history', 38.9889, -106.4288, 'Vicksburg', 'CO', 'A small, unusually orderly mining settlement in Clear Creek Canyon with restored cabins lining its historic lane. Several buildings remain privately maintained, so the public-road and interpretive areas are the appropriate focus.', 'limited', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Winfield Ghost Town', 'winfield-ghost-town', 'weird-history', 38.9847, -106.4409, 'Winfield', 'CO', 'A former silver-mining town at the end of a mountain valley with surviving cabins and interpretive signs. The road is rough and seasonal, and standing structures should not be entered unless specifically marked for public access.', 'limited', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Dearfield Ghost Town', 'dearfield-ghost-town', 'weird-history', 40.2905, -104.2594, 'Dearfield', 'CO', 'The remains of Colorado''s best-known Black agricultural colony stand along U.S. 34, including Oliver Toussaint Jackson''s home and other surviving structures. The site is historically important and fragile, so exterior viewing and designated access are the safe default.', 'roadside', 'https://www.historycolorado.org/dearfield', null, 'America/Denver', now()),
  ('Capitol City Ghost Town', 'capitol-city-ghost-town', 'weird-history', 38.0072, -107.4667, 'Capitol City', 'CO', 'Scattered structures and ruins mark the former silver town once promoted as a potential Colorado capital. Reaching it requires a rough mountain road south of Engineer Pass country, making conditions and vehicle capability part of the visit.', 'limited', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Animas Forks Ghost Town', 'animas-forks-ghost-town', 'weird-history', 37.93123, -107.57068, 'Animas Forks', 'CO', 'A high-elevation mining ghost town on the Alpine Loop with multiple preserved buildings and BLM interpretation. The approach from Silverton is generally a summer route; roads beyond the town can require four-wheel drive.', 'limited', 'https://www.blm.gov/visit/animas-forks', null, 'America/Denver', now()),
  ('Ironton Ghost Town', 'ironton-ghost-town', 'weird-history', 37.9328, -107.6803, 'Ironton', 'CO', 'Remnants of a once-busy Red Mountain mining settlement lie near the Million Dollar Highway, with cabins and mine-era traces among the forest. Public roads offer access, but individual buildings and mine workings may be unsafe or private.', 'limited', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Red Mountain Town Site', 'red-mountain-town-site', 'weird-history', 37.9036, -107.7026, 'Red Mountain', 'CO', 'A few remains mark the former silver camp below Red Mountain Pass, once packed with mines, mills and saloons. The high-altitude terrain, snow and active/private mining parcels make this primarily a roadside and trail-history stop.', 'limited', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Crystal Ghost Town', 'crystal-ghost-town', 'weird-history', 39.0592, -107.1012, 'Crystal', 'CO', 'A remote former mining settlement best known for the photogenic Crystal Mill just down the road. The settlement includes private property and rough access, so visitors should stay on legal roads and respect all posted boundaries.', 'limited', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Gothic Historic Mining Town', 'gothic-historic-mining-town', 'weird-history', 38.9592, -106.9898, 'Gothic', 'CO', 'A former silver town now occupied by the Rocky Mountain Biological Laboratory, with historic buildings surviving among active research facilities. Public road travel passes through, but laboratory buildings and residences are not abandoned attractions.', 'limited', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Bonanza Historic Mining Town', 'bonanza-historic-mining-town', 'weird-history', 38.2947, -106.1422, 'Bonanza', 'CO', 'A tiny surviving legal town surrounded by the remnants of a much larger silver-mining district. Historic buildings and mine traces remain, but the community is still inhabited and private property should be treated accordingly.', 'roadside', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Caribou Ghost Town', 'caribou-ghost-town', 'weird-history', 39.98056, -105.57778, 'Caribou', 'CO', 'Ruins and scattered remains mark the high-country silver town west of Nederland. The surrounding landscape mixes public land with private parcels and old mine hazards, so this is a stay-on-road/trail location rather than a structure-exploration stop.', 'limited', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Nevadaville Ghost Town', 'nevadaville-ghost-town', 'weird-history', 39.79527, -105.5325, 'Nevadaville', 'CO', 'A nearly vanished mining settlement immediately above Central City, with historic buildings still standing among private parcels. Because a handful of properties remain occupied or privately owned, viewing from public roads is the correct approach.', 'roadside', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Camp Hale 10th Mountain Division Historic Site', 'camp-hale-10th-mountain-division-historic-site', 'weird-history', 39.44304, -106.3228, 'Red Cliff', 'CO', 'Concrete foundations and other traces of the enormous World War II mountain-warfare training camp remain in the Eagle River valley. The landscape is now protected within Camp Hale–Continental Divide National Monument and can be explored from designated public roads and trails.', 'open', 'https://www.fs.usda.gov/recarea/whiteriver/recarea/?recid=84126', null, 'America/Denver', now()),
  ('Keota Ghost Town', 'keota-ghost-town', 'weird-history', 40.7028, -104.0752, 'Keota', 'CO', 'A prairie ghost town on Colorado''s northeastern plains with a cemetery, foundations and a small number of surviving structures. Public roads reach the area, but surrounding ranchland is private and should not be crossed without permission.', 'roadside', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Uravan Townsite', 'uravan-townsite', 'weird-history', 38.36832, -108.73649, 'Uravan', 'CO', 'The former uranium and vanadium company town was demolished and remediated after mining contamination, leaving little of the settlement itself. Interpretive context and the empty townsite make it a particularly eerie example of a deliberately erased community.', 'roadside', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Gillett Ghost Town Site', 'gillett-ghost-town-site', 'weird-history', 38.7819, -105.1228, 'Gillett', 'CO', 'Little remains of this Cripple Creek district boomtown, once home to a racetrack and mining population. The value is in the vanished-town landscape and mining context, not in entering ruins or claims.', 'roadside', 'https://www.colorado.com/articles/colorado-ghost-towns', null, 'America/Denver', now()),
  ('Argo Mill & Tunnel', 'argo-mill-tunnel', 'weird-history', 39.74287, -105.50661, 'Idaho Springs', 'CO', 'A huge red-and-white gold mill built at the portal of the Argo Tunnel, once designed to drain and serve mines across the district. Tours interpret ore processing, hard-rock mining and the catastrophic tunnel history that shaped Idaho Springs.', 'open', 'https://historicidahosprings.com/historic-sites/argo-mill-and-tunnel/', null, 'America/Denver', now()),
  ('Hidee Gold Mine', 'hidee-gold-mine', 'weird-history', 39.78773, -105.49746, 'Central City', 'CO', 'A working-tour mine where visitors travel underground and can try basic hard-rock mining under staff supervision. It is open year-round but requires a scheduled tour and appropriate clothing for underground conditions.', 'limited', 'https://hideegoldmine.com/', null, 'America/Denver', now()),
  ('Capital Prize Gold Mine', 'capital-prize-gold-mine', 'weird-history', 39.70955, -105.69247, 'Georgetown', 'CO', 'A guided underground tour follows an original mine adit into Griffith Mountain above Georgetown. Reservations are important, and the stop is about controlled mine access rather than wandering historic workings independently.', 'limited', 'https://www.capitalprizegoldmine.com/', null, 'America/Denver', now()),
  ('Country Boy Mine', 'country-boy-mine', 'weird-history', 39.47861, -106.01167, 'Breckenridge', 'CO', 'A preserved Breckenridge mine offering guided underground tours, gold panning and mining-history interpretation. Visitors enter only through the operated attraction; surrounding historic mine features should not be explored independently.', 'limited', 'https://countryboymine.com/', null, 'America/Denver', now()),
  ('Phoenix Gold Mine', 'phoenix-gold-mine', 'weird-history', 39.74894, -105.56557, 'Idaho Springs', 'CO', 'A family-run mine attraction where guided tours enter historic workings and discuss gold extraction in the Idaho Springs district. The underground component makes this a stronger OddWay stop than a surface-only mining display.', 'limited', 'https://www.phoenixgoldmine.com/', null, 'America/Denver', now()),
  ('High Line Railroad Park', 'high-line-railroad-park', 'weird-history', 39.47349, -106.03976, 'Breckenridge', 'CO', 'An outdoor rail-history park built around Engine No. 9, a rotary snowplow and other equipment tied to the narrow-gauge lines that once served the high country. It is an easy way to see the machinery behind Colorado''s mountain rail era without entering an active rail corridor.', 'open', 'https://breckhistory.org/high-line-railroad-park/', null, 'America/Denver', now()),
  ('Bachelor Syracuse Mine Tour', 'bachelor-syracuse-mine-tour', 'weird-history', 38.05944, -107.67842, 'Ouray', 'CO', 'A guided mine experience outside Ouray that takes visitors into historic workings beneath Gold Hill. Operations can be affected by mountain weather or wildfire conditions, so current tour status should be checked before routing.', 'limited', 'https://www.visitouray.com/minetour', null, 'America/Denver', now()),
  ('Old Hundred Gold Mine Tour', 'old-hundred-gold-mine-tour', 'weird-history', 37.82944, -107.57611, 'Silverton', 'CO', 'Visitors ride a mine train underground into Galena Mountain to see drills, ore cars and mining demonstrations. The attraction operates seasonally in the high San Juans and is distinct from abandoned mine portals elsewhere in the district.', 'limited', 'https://minetour.com/', null, 'America/Denver', now()),
  ('Last Chance Mine', 'last-chance-mine', 'weird-history', 37.88392, -106.93664, 'Creede', 'CO', 'A preserved silver mine high above Creede offering guided underground tours, mineral displays and the remains of an extensive historic operation. The steep Bachelor Loop approach and seasonal schedule make advance planning important.', 'limited', 'https://lastchancemine.com/', null, 'America/Denver', now()),
  ('Matchless Mine', 'matchless-mine', 'weird-history', 39.25611, -106.27055, 'Leadville', 'CO', 'The famous Leadville silver mine associated with Horace and Baby Doe Tabor survives as a museum site with original structures and equipment. Public entry is seasonal and controlled by the National Mining Hall of Fame and Museum.', 'limited', 'https://www.mininghalloffame.org/matchless-mine', null, 'America/Denver', now()),
  ('Washington Mine & Milling Exhibit', 'washington-mine-milling-exhibit', 'weird-history', 39.46773, -106.02265, 'Breckenridge', 'CO', 'A preserved mining complex with an ore-processing exhibit, headframe and underground components interpreted by Breckenridge History. Tours and opening periods vary, so it should be treated as a scheduled historic site rather than open ruins.', 'limited', 'https://breckhistory.org/explore/', null, 'America/Denver', now()),
  ('Lomax Placer Mine', 'lomax-placer-mine', 'weird-history', 39.48343, -106.0531, 'Breckenridge', 'CO', 'A small preserved placer-mining site showing hydraulic and sluicing-era techniques along the edge of Breckenridge. Seasonal programs add demonstrations and interpretation to a compact collection of mining equipment.', 'limited', 'https://breckhistory.org/explore/', null, 'America/Denver', now()),
  ('Paris Mill', 'paris-mill', 'weird-history', 39.29577, -106.10708, 'Alma', 'CO', 'A rare surviving mountain ore mill west of Alma, preserved as an industrial landmark rather than an unrestricted abandoned building. Interior access is not routinely public, so OddWay should treat the structure as an exterior historical stop unless a sanctioned tour is offered.', 'roadside', 'https://www.parkcountyco.gov/387/Alma-Area', null, 'America/Denver', now()),
  ('Mayflower Gold Mill', 'mayflower-gold-mill', 'weird-history', 37.8284, -107.6284, 'Silverton', 'CO', 'An exceptionally intact 20th-century ore-processing mill preserving flotation equipment, tram infrastructure and assay spaces. The San Juan County Historical Society opens it seasonally for self-guided or interpreted visits.', 'limited', 'https://www.sanjuancountyhistoricalsociety.org/mayflower-mill', null, 'America/Denver', now()),
  ('Yankee Girl Mine Headframe', 'yankee-girl-mine-headframe', 'weird-history', 37.91469, -107.69638, 'Red Mountain', 'CO', 'The tall Yankee Girl headframe is one of the most recognizable survivors of the Red Mountain mining district. It is visible from the public route, while the mine property and openings themselves should remain strictly off-limits.', 'roadside', 'https://www.ouraycountyhistoricalsociety.org/', null, 'America/Denver', now()),
  ('Idarado Legacy Trail', 'idarado-legacy-trail', 'weird-history', 37.9348, -107.7865, 'Telluride', 'CO', 'An interpretive trail follows the east end of Telluride''s valley toward the historic Idarado mill and explains the mining landscape along the way. The route provides legal public access to the district without sending visitors into mine workings.', 'open', 'https://www.telluride.com/activity/idarado-legacy-trail/', null, 'America/Denver', now()),
  ('Vindicator Valley Trail', 'vindicator-valley-trail', 'weird-history', 38.72594, -105.1233, 'Victor', 'CO', 'A signed loop passes headframes, foundations and mine remnants in the Cripple Creek-Victor gold district. The trail is specifically designed for historical access, which is safer than approaching the area''s many unmarked shafts and claims.', 'open', 'https://victorcolorado.com/trails/', null, 'America/Denver', now()),
  ('American Eagles Overlook', 'american-eagles-overlook', 'weird-history', 38.70885, -105.16913, 'Victor', 'CO', 'A high mining-district overlook beside the remains of the American Eagles operation, with broad views across historic and active gold-mining terrain. Rough seasonal roads and changing mine activity make current access checks worthwhile.', 'limited', 'https://victorcolorado.com/', null, 'America/Denver', now()),
  ('Alpine Tunnel Historic District', 'alpine-tunnel-historic-district', 'weird-history', 38.64583, -106.40889, 'Pitkin', 'CO', 'The collapsed portal and railroad grade mark what was once the highest railroad tunnel in North America. The remote Continental Divide site is reached by seasonal backcountry roads and trails rather than by entering the sealed tunnel.', 'limited', 'https://www.fs.usda.gov/recarea/gmug/recarea/?recid=32966', null, 'America/Denver', now()),
  ('Georgetown Loop Railroad', 'georgetown-loop-railroad', 'weird-history', 39.69495, -105.72413, 'Silver Plume', 'CO', 'A reconstructed narrow-gauge line climbs the steep Clear Creek canyon on looping track and the high Devil''s Gate bridge. Seasonal trains pair mining history with a deliberately dramatic piece of railroad engineering.', 'limited', 'https://www.georgetownlooprr.com/', null, 'America/Denver', now()),
  ('Cumbres & Toltec Scenic Railroad — Antonito Depot', 'cumbres-toltec-scenic-railroad-antonito-depot', 'weird-history', 37.067, -106.017, 'Antonito', 'CO', 'The Colorado terminal of the historic narrow-gauge Cumbres & Toltec sends steam trains over high passes toward Chama, New Mexico. The yard and depot preserve an unusually complete working slice of Denver & Rio Grande narrow-gauge history.', 'limited', 'https://cumbrestoltec.com/', null, 'America/Denver', now()),
  ('Durango & Silverton Narrow Gauge Railroad — Durango Depot', 'durango-silverton-narrow-gauge-railroad-durango-depot', 'weird-history', 37.2754, -107.8807, 'Durango', 'CO', 'Steam-powered narrow-gauge trains depart the historic Durango depot for the San Juan Mountains using a railroad descended from the Denver & Rio Grande. The working locomotives and original route make the depot itself a substantial OddWay stop.', 'open', 'https://durangotrain.com/', null, 'America/Denver', now()),
  ('Leadville Railroad Depot', 'leadville-railroad-depot', 'weird-history', 39.247, -106.2921, 'Leadville', 'CO', 'A scenic railroad operates from Leadville over former mining and freight trackage high in the Rockies. The ride passes mine remnants and high-elevation railroad infrastructure rather than functioning as a standard commuter excursion.', 'limited', 'https://www.leadvillerailroad.com/', null, 'America/Denver', now()),
  ('Cripple Creek & Victor Narrow Gauge Railroad', 'cripple-creek-victor-narrow-gauge-railroad', 'weird-history', 38.74748, -105.17217, 'Cripple Creek', 'CO', 'A short narrow-gauge steam excursion runs from Cripple Creek past old mines and toward the abandoned Anaconda district. Its route is essentially a moving tour through a gold-boom landscape.', 'limited', 'https://cripplecreekrailroad.com/', null, 'America/Denver', now()),
  ('National Mining Hall of Fame & Museum', 'national-mining-hall-of-fame-museum', 'weird-history', 39.24766, -106.29203, 'Leadville', 'CO', 'A large museum inside Leadville''s former high school covers mining technology, minerals, disasters and the people inducted into the National Mining Hall of Fame. The reconstructed mine exhibits and mineral displays give it more depth than a local-history stop.', 'open', 'https://mininghalloffame.org/', null, 'America/Denver', now()),
  ('Creede Underground Mining Museum', 'creede-underground-mining-museum', 'weird-history', 37.85734, -106.92808, 'Creede', 'CO', 'Miners blasted this museum directly into the rock above Creede, creating an underground complex of mining exhibits and community spaces. The setting itself is part of the attraction even though it is not an original production mine.', 'open', 'https://undergroundminingmuseum.com/', null, 'America/Denver', now()),
  ('Victor Lowell Thomas Museum', 'victor-lowell-thomas-museum', 'weird-history', 38.71055, -105.1391, 'Victor', 'CO', 'A small museum in Victor preserves mining artifacts, local history and material connected to broadcaster Lowell Thomas. Its location in a largely intact gold-boom town makes it a useful interpretive anchor before visiting nearby headframes and trails.', 'limited', 'https://victormuseum.com/', null, 'America/Denver', now()),
  ('Western Museum of Mining & Industry', 'western-museum-of-mining-industry', 'weird-history', 38.9879, -104.8012, 'Colorado Springs', 'CO', 'A museum devoted to western mining technology with working machinery, steam equipment, assay displays and large outdoor artifacts. Demonstrations make the industrial processes tangible instead of presenting only static photographs.', 'open', 'https://wmmi.org/', null, 'America/Denver', now()),
  ('Gilpin History Museum', 'gilpin-history-museum', 'weird-history', 39.8024, -105.516, 'Central City', 'CO', 'Housed in an 1870 school, this museum interprets Central City''s mining boom with a recreated streetscape, mining room and the eccentric ''Mountain Submarine.'' Public hours are seasonal, with off-season access generally by arrangement.', 'limited', 'https://www.gilpinhistory.org/gilpin-history-museum', null, 'America/Denver', now()),
  ('Lafayette Miners Museum', 'lafayette-miners-museum', 'weird-history', 39.99819, -105.0896, 'Lafayette', 'CO', 'A former coal miner''s home now holds artifacts and stories from Lafayette''s coal camps, strikes and immigrant communities. Limited opening hours make it best for deliberate visits rather than spontaneous routing.', 'limited', 'https://www.lafayettehistory.com/miners-museum', null, 'America/Denver', now()),
  ('Dinosaur Ridge', 'dinosaur-ridge', 'museums', 39.69417, -105.2, 'Morrison', 'CO', 'A famous Front Range track-and-bone site where exposed rock preserves dinosaur footprints and Jurassic fossils along the former Alameda Parkway roadcut. Interpretive stops make the geology visible in place rather than only inside a museum.', 'open', 'https://dinoridge.org/', null, 'America/Denver', now()),
  ('Triceratops Trail', 'triceratops-trail', 'museums', 39.74309, -105.22107, 'Golden', 'CO', 'A short trail beside the Colorado School of Mines campus preserves dinosaur tracks, palm impressions and traces of the ancient environment left in vertical sandstone walls. The fossils are outdoors and can be seen from the marked public trail.', 'open', 'https://www.mines.edu/museumofearthscience/triceratops-trail/', null, 'America/Denver', now()),
  ('Morrison Natural History Museum', 'morrison-natural-history-museum', 'museums', 39.64891, -105.19414, 'Morrison', 'CO', 'A small working museum near the historic Morrison Formation quarries, with real fossils, casts and hands-on interpretation focused on local dinosaur discoveries. Its scale and direct connection to the surrounding fossil beds make it stronger for OddWay than a generic natural-history stop.', 'open', 'https://www.mnhm.org/', null, 'America/Denver', now()),
  ('Dinosaur Journey Museum', 'dinosaur-journey-museum', 'museums', 39.15182, -108.73934, 'Fruita', 'CO', 'The Museum of Western Colorado''s paleontology branch displays local Jurassic fossils, a working fossil-preparation lab and dinosaur reconstructions close to the region''s major quarry sites. It works well as a base before visiting the nearby outdoor fossil trails.', 'open', 'https://www.museumofwesternco.com/museum-of-western-colorado/dinosaur-journey/', null, 'America/Denver', now()),
  ('Dinosaur Hill', 'dinosaur-hill', 'museums', 39.13284, -108.73598, 'Fruita', 'CO', 'A BLM interpretive trail circles the hill where Elmer Riggs excavated an Apatosaurus skeleton in 1901. Quarry scars and interpretive signs connect the landscape directly to the early history of western dinosaur collecting.', 'open', 'https://www.blm.gov/visit/dinosaur-hill-trailhead', null, 'America/Denver', now()),
  ('Trail Through Time at Rabbit Valley', 'trail-through-time-at-rabbit-valley', 'museums', 39.18943, -109.00048, 'Mack', 'CO', 'A self-guided BLM loop crosses active and historic dinosaur-quarry country near the Utah line, with interpretive panels explaining fossils still embedded in the Morrison Formation. Visitors must leave all fossils and rock in place.', 'open', 'https://www.blm.gov/visit/trail-through-time', null, 'America/Denver', now()),
  ('Garden Park Fossil Area', 'garden-park-fossil-area', 'museums', 38.53022, -105.21877, 'Cañon City', 'CO', 'This BLM landscape north of Cañon City helped launch American dinosaur paleontology, producing famous Jurassic discoveries during the Bone Wars era. Public roads and interpretive areas let travelers visit the fossil landscape without entering protected quarry workings.', 'open', 'https://www.blm.gov/programs/national-conservation-lands/colorado/garden-park-fossil-area', null, 'America/Denver', now()),
  ('Cleveland Quarry Recreation Site', 'cleveland-quarry-recreation-site', 'museums', 38.53247, -105.21899, 'Cañon City', 'CO', 'Within Garden Park, this developed BLM site interprets one of the area''s historic dinosaur quarries and provides access to a short trail toward the Marsh Quarry area. It is a specific, routable fossil-history stop rather than a broad regional pin.', 'open', 'https://www.blm.gov/visit/cleveland-quarry-rec-site', null, 'America/Denver', now()),
  ('Skyline Drive Dinosaur Trackway', 'skyline-drive-dinosaur-trackway', 'museums', 38.45913, -105.25075, 'Cañon City', 'CO', 'Along Cañon City''s narrow one-way Skyline Drive, an interpretive pullout points out a line of ankylosaur tracks preserved high in the tilted rock. The same razorback road was built by prison labor in 1905, giving the stop an unusual overlap of fossil and dark local history.', 'roadside', 'https://www.canoncity.org/370/Skyline-Drive', null, 'America/Denver', now()),
  ('Florissant Fossil Beds National Monument', 'florissant-fossil-beds-national-monument', 'roadside-oddities', 38.91361, -105.2828, 'Florissant', 'CO', 'The monument preserves an Eocene lake ecosystem with enormous petrified redwood stumps and exceptionally detailed fossil insects and leaves. Trails begin near the visitor center, and collecting fossils or petrified wood is prohibited.', 'open', 'https://www.nps.gov/flfo/index.htm', null, 'America/Denver', now()),
  ('Rocky Mountain Dinosaur Resource Center', 'rocky-mountain-dinosaur-resource-center', 'museums', 38.99374, -105.05131, 'Woodland Park', 'CO', 'A fossil museum and working laboratory with mounted skeletons, marine reptiles and visible preparation work. The collection emphasizes real paleontology and casts from specimens prepared by the affiliated laboratory.', 'open', 'https://www.rmdrc.com/', null, 'America/Denver', now()),
  ('Mines Museum of Earth Science', 'mines-museum-of-earth-science', 'roadside-oddities', 39.75189, -105.22484, 'Golden', 'CO', 'Colorado School of Mines maintains a geology museum packed with minerals, meteorites, fossils and mining artifacts. The combination of unusual specimens and Colorado mining science makes it a useful OddWay indoor stop.', 'open', 'https://www.mines.edu/museumofearthscience/', null, 'America/Denver', now()),
  ('Denver Museum of Nature & Science — Prehistoric Journey', 'denver-museum-of-nature-science-prehistoric-journey', 'museums', 39.74754, -104.94286, 'Denver', 'CO', 'The museum''s major paleontology galleries trace life from ancient seas through dinosaurs and Ice Age mammals, with a fossil-preparation lab visible to visitors. It is a large mainstream museum, but the depth of Colorado fossil material earns it a place in the state index.', 'open', 'https://www.dmns.org/', null, 'America/Denver', now()),
  ('University of Colorado Museum of Natural History', 'university-of-colorado-museum-of-natural-history', 'roadside-oddities', 40.00716, -105.27275, 'Boulder', 'CO', 'A university museum with paleontology, geology and anthropology collections used for research as well as public exhibits. Fossils and Southwest cultural material give it a stronger OddWay fit than a general campus museum.', 'open', 'https://www.colorado.edu/cumuseum/', null, 'America/Denver', now()),
  ('Fruita Paleontological Area — Devil''s Canyon Trailhead', 'fruita-paleontological-area-devils-canyon-trailhead', 'museums', 39.14, -108.759, 'Fruita', 'CO', 'BLM land south of Fruita protects fossil-bearing badlands associated with important Jurassic discoveries. The Devil''s Canyon trailhead provides a lawful public access point into the surrounding landscape; fossils must not be collected.', 'open', 'https://www.blm.gov/visit/mcinnis-canyons-national-conservation-area', null, 'America/Denver', now()),
  ('Riggs Hill', 'riggs-hill', 'museums', 39.0736, -108.6514, 'Grand Junction', 'CO', 'A short interpretive trail crosses two historic dinosaur quarry sites where Elmer Riggs and later crews worked the Morrison Formation. The hill preserves the story in the actual excavation landscape just outside Grand Junction.', 'open', 'https://www.museumofwesternco.com/famous-fossil-sites/', null, 'America/Denver', now()),
  ('Harpers Corner', 'harpers-corner', 'roadside-oddities', 40.53017, -109.01076, 'Dinosaur', 'CO', 'At the end of Dinosaur National Monument''s Colorado-side scenic road, a trail reaches a high peninsula above deeply cut canyons and dramatic folded rock. The overlook exposes the strange geology of the monument far beyond its dinosaur fossils.', 'open', 'https://www.nps.gov/dino/planyourvisit/harpers-corner.htm', null, 'America/Denver', now()),
  ('Echo Park', 'echo-park', 'weird-history', 40.51963, -108.98048, 'Dinosaur', 'CO', 'Deep inside Dinosaur National Monument, Echo Park sits where the Green and Yampa Rivers meet beneath Steamboat Rock. Access is by a steep seasonal dirt road unsuitable in wet conditions, so this is a condition-dependent backcountry stop rather than a casual roadside pullout.', 'limited', 'https://www.nps.gov/dino/planyourvisit/echo-park.htm', null, 'America/Denver', now()),
  ('Dillon Pinnacles', 'dillon-pinnacles', 'roadside-oddities', 38.47051, -107.25302, 'Sapinero', 'CO', 'A trail in Curecanti National Recreation Area approaches eroded volcanic spires rising above Blue Mesa Reservoir. The pinnacles are the remains of ash and breccia from ancient eruptions, creating one of the state''s stranger roadside-accessible geologic landscapes.', 'open', 'https://www.nps.gov/cure/planyourvisit/dillon-pinnacles-trail.htm', null, 'America/Denver', now()),
  ('Dotsero Crater', 'dotsero-crater', 'roadside-oddities', 39.6588, -107.03333, 'Dotsero', 'CO', 'Colorado''s youngest volcano is a maar-and-scoria volcanic complex only a few thousand years old, with Interstate 70 crossing its old lava flow. BLM provides public access, but the approach is rougher than a normal developed attraction.', 'limited', 'https://www.blm.gov/visit/dotsero-crater-rec-site', null, 'America/Denver', now()),
  ('Wheeler Geologic Area', 'wheeler-geologic-area', 'roadside-oddities', 37.87891, -106.78417, 'Creede', 'CO', 'Remote volcanic tuff has eroded into towers, fins and narrow passages that once formed Colorado''s first national monument. Reaching the formations requires a long hike or difficult high-clearance route, so the pin represents a backcountry destination rather than drive-up access.', 'limited', 'https://www.fs.usda.gov/recarea/riogrande/recarea/?recid=28910', null, 'America/Denver', now()),
  ('Paint Mines Interpretive Park', 'paint-mines-interpretive-park', 'roadside-oddities', 39.01485, -104.2692, 'Calhan', 'CO', 'Bands of pink, orange, white and purple clay form hoodoos and sculpted gullies used by Indigenous peoples for pigments. Visitors must remain on designated trails because the formations and archaeological resources are fragile.', 'open', 'https://communityservices.elpasoco.com/parks-and-recreation/paint-mines-interpretive-park/', null, 'America/Denver', now()),
  ('Rattlesnake Arches', 'rattlesnake-arches', 'roadside-oddities', 39.13713, -108.833, 'Fruita', 'CO', 'A remote concentration of large natural sandstone arches hides in McInnis Canyons National Conservation Area. The upper access road is seasonal and high-clearance dependent, while hiking approaches are long, so conditions should be checked before routing.', 'limited', 'https://www.blm.gov/visit/rattlesnake-arches', null, 'America/Denver', now()),
  ('Manitou Cliff Dwellings', 'manitou-cliff-dwellings', 'museums', 38.86313, -104.91254, 'Manitou Springs', 'CO', 'This commercial museum complex contains Ancestral Puebloan masonry that was dismantled from a site in southwest Colorado and reconstructed in Manitou Springs in the early 1900s. Its relocation history makes it an unusual, sometimes controversial archaeology stop rather than an intact original village.', 'open', 'https://www.cliffdwellingsmuseum.com/', null, 'America/Denver', now()),
  ('Cliff Palace', 'cliff-palace', 'weird-history', 37.16663, -108.473, 'Mesa Verde National Park', 'CO', 'Mesa Verde''s largest cliff dwelling contains more than 150 rooms and remains one of the most recognizable Ancestral Pueblo sites in the United States. Entry requires a reserved ranger-led tour during the operating season, though overlooks are available without entering the dwelling.', 'limited', 'https://www.nps.gov/meve/learn/historyculture/cliff_palace.htm', null, 'America/Denver', now()),
  ('Balcony House', 'balcony-house', 'weird-history', 37.16239, -108.46519, 'Mesa Verde National Park', 'CO', 'A mid-sized cliff dwelling reached on one of Mesa Verde''s most strenuous public tours, including a 32-foot ladder, narrow tunnel and exposed climb. Entry is ranger-led and reservation-only during the tour season.', 'limited', 'https://www.nps.gov/meve/learn/historyculture/cp_balcony_house_tour.htm', null, 'America/Denver', now()),
  ('Square Tower House', 'square-tower-house', 'weird-history', 37.16611, -108.49148, 'Mesa Verde National Park', 'CO', 'The park''s tallest standing cliff structure rises four stories inside a large alcove and can be seen from the Mesa Top Loop. Interior access is only through designated ranger programs when offered; otherwise the public experience is from established overlooks.', 'limited', 'https://www.nps.gov/meve/planyourvisit/cliff_dwelling_tours.htm', null, 'America/Denver', now()),
  ('Spruce Tree House Overlook', 'spruce-tree-house-overlook', 'weird-history', 37.18401, -108.4884, 'Mesa Verde National Park', 'CO', 'Spruce Tree House has been closed to direct entry since 2015 because of rockfall danger, but NPS maintains public overlooks behind the Mesa Verde Museum. The overlook gives a lawful view of one of the park''s largest and best-preserved cliff dwellings without routing visitors into the closed site.', 'roadside', 'https://www.nps.gov/meve/learn/historyculture/cd_spruce_tree_house.htm', null, 'America/Denver', now()),
  ('Sun Temple', 'sun-temple', 'weird-history', 37.16471, -108.47543, 'Mesa Verde National Park', 'CO', 'A large D-shaped ceremonial structure on Mesa Top Loop shows unusually fine masonry and an apparently unfinished plan. It is self-guided from the established trail, and visitors must stay off the fragile walls.', 'open', 'https://www.nps.gov/meve/learn/historyculture/mt_sun_temple.htm', null, 'America/Denver', now()),
  ('Step House', 'step-house', 'weird-history', 37.19694, -108.53592, 'Mesa Verde National Park', 'CO', 'Step House preserves both an earlier pithouse occupation and a later cliff dwelling in the same alcove, showing centuries of change at Mesa Verde. During Wetherill Mesa''s operating season it is normally self-guided with rangers present, but road and fire conditions can temporarily affect access.', 'limited', 'https://www.nps.gov/meve/planyourvisit/cliff_dwelling_tours.htm', null, 'America/Denver', now()),
  ('Long House', 'long-house', 'weird-history', 37.18722, -108.53794, 'Mesa Verde National Park', 'CO', 'The second-largest cliff dwelling in Mesa Verde stretches nearly 300 feet and includes more than 150 rooms, kivas and a large plaza. Visits require a reserved ranger-led tour and seasonal access to Wetherill Mesa.', 'limited', 'https://www.nps.gov/meve/learn/historyculture/cd_long_house_tour.htm', null, 'America/Denver', now()),
  ('Badger House Community', 'badger-house-community', 'weird-history', 37.18697, -108.53103, 'Mesa Verde National Park', 'CO', 'A Wetherill Mesa trail links several mesa-top homes spanning hundreds of years of Ancestral Pueblo occupation, from pithouses to masonry pueblos. Access is seasonal and should be checked against current Wetherill Mesa conditions.', 'limited', 'https://www.nps.gov/meve/planyourvisit/wetherill-mesa.htm', null, 'America/Denver', now()),
  ('Petroglyph Point Trail', 'petroglyph-point-trail', 'weird-history', 37.17263, -108.49271, 'Mesa Verde National Park', 'CO', 'A rugged loop from the Chapin Mesa area reaches one of Mesa Verde''s best-known petroglyph panels along the canyon wall. The route involves steep stone steps and narrow sections, and all rock art must be viewed without touching or altering it.', 'limited', 'https://www.nps.gov/meve/planyourvisit/petroglyph-point-trail.htm', null, 'America/Denver', now()),
  ('Mesa Verde Museum', 'mesa-verde-museum', 'museums', 37.1845, -108.4883, 'Mesa Verde National Park', 'CO', 'One of the National Park Service''s oldest museums interprets Ancestral Pueblo lifeways with cultural objects, exhibits and an orientation film. The building itself is part of the park''s historic administrative district and sits beside the Spruce Tree House overlooks.', 'open', 'https://www.nps.gov/meve/planyourvisit/museum.htm', null, 'America/Denver', now()),
  ('Canyons of the Ancients Visitor Center & Museum', 'canyons-of-the-ancients-visitor-center-museum', 'museums', 37.47625, -108.54617, 'Dolores', 'CO', 'BLM''s museum for Canyons of the Ancients contains archaeological collections and exhibits from one of the densest known concentrations of archaeological sites in the United States. It is also the best first stop for current road and site conditions before entering the monument.', 'open', 'https://www.blm.gov/visit/canyons-ancients-national-monument-visitor-center-and-museum', null, 'America/Denver', now()),
  ('Escalante Pueblo', 'escalante-pueblo', 'weird-history', 37.47783, -108.54564, 'Dolores', 'CO', 'A paved trail from the Canyons of the Ancients museum climbs to a partially excavated pueblo with a Great Kiva and broad views across the Montezuma Valley. The site is protected; visitors should stay on the designated route and leave all artifacts in place.', 'open', 'https://www.blm.gov/visit/canyons-ancients-national-monument-visitor-center-and-museum', null, 'America/Denver', now()),
  ('Lowry Pueblo National Historic Landmark', 'lowry-pueblo-national-historic-landmark', 'weird-history', 37.58476, -108.9201, 'Pleasant View', 'CO', 'This 1,000-year-old ancestral Pueblo community includes roughly 40 rooms, multiple kivas and a Great Kiva beneath a protective roof. BLM maintains it as one of the most accessible major archaeological sites in Canyons of the Ancients.', 'open', 'https://www.recreation.gov/gateways/1710', null, 'America/Denver', now()),
  ('Sand Canyon Pueblo', 'sand-canyon-pueblo', 'weird-history', 37.3992, -108.77712, 'Cortez', 'CO', 'A short trail reaches the remains of a large late-1200s pueblo at the head of Sand Canyon, once containing hundreds of rooms and many kivas. Only low masonry and room outlines remain, and visitors must stay on established trails.', 'open', 'https://www.blm.gov/programs/national-conservation-lands/colorado/canyons-of-the-ancients', null, 'America/Denver', now()),
  ('Goodman Point Pueblo', 'goodman-point-pueblo', 'weird-history', 37.41291, -108.72537, 'Cortez', 'CO', 'A large ancestral Pueblo community protected as part of Hovenweep National Monument lies beyond a short approach from the public parking area. The archaeological landscape is sensitive and should be visited only by established routes without entering structures or disturbing artifacts.', 'limited', 'https://www.nps.gov/hove/planyourvisit/placestogo.htm', null, 'America/Denver', now()),
  ('Painted Hand Pueblo', 'painted-hand-pueblo', 'weird-history', 37.45394, -108.97191, 'Cortez', 'CO', 'A remote Canyons of the Ancients site is known for a tower complex and the painted handprint that gave the place its modern name. Access uses primitive roads and trails, so the parking-area pin is intentionally used instead of routing directly onto the archaeological structure.', 'limited', 'https://www.blm.gov/programs/national-conservation-lands/colorado/canyons-of-the-ancients', null, 'America/Denver', now()),
  ('Holly Group — Hovenweep', 'holly-group-hovenweep', 'weird-history', 37.3911, -109.04205, 'Montezuma County', 'CO', 'Hovenweep''s Holly unit contains towers, masonry rooms and a petroglyph panel around the head of Keeley Canyon. NPS recommends high-clearance vehicles for the unimproved access road and requires visitors to remain on defined trails.', 'limited', 'https://www.nps.gov/hove/planyourvisit/holly.htm', null, 'America/Denver', now()),
  ('Horseshoe Group — Hovenweep', 'horseshoe-group-hovenweep', 'weird-history', 37.40888, -109.02928, 'Montezuma County', 'CO', 'Horseshoe House and nearby tower structures sit along the rim of Hackberry Canyon in one of Hovenweep''s remote Colorado units. Access uses an unimproved BLM road followed by a primitive trail, with high clearance strongly recommended.', 'limited', 'https://www.nps.gov/hove/planyourvisit/horseshoe.htm', null, 'America/Denver', now()),
  ('Hackberry Group — Hovenweep', 'hackberry-group-hovenweep', 'weird-history', 37.40805, -109.02511, 'Montezuma County', 'CO', 'Hackberry is the largest complex in Hovenweep and remains culturally significant to descendant Pueblo communities. It shares the rough access corridor with Horseshoe and should be visited respectfully from the established trail only.', 'limited', 'https://www.nps.gov/hove/planyourvisit/horseshoe.htm', null, 'America/Denver', now()),
  ('Cutthroat Castle Group — Hovenweep', 'cutthroat-castle-group-hovenweep', 'weird-history', 37.44277, -108.9815, 'Montezuma County', 'CO', 'Hovenweep''s hardest-to-reach outlying unit contains a three-story D-shaped masonry building and scattered towers set within a drainage instead of on a canyon rim. The approach is a rough unimproved road and primitive trail with no services.', 'limited', 'https://www.nps.gov/hove/planyourvisit/cutthroat.htm', null, 'America/Denver', now()),
  ('Chimney Rock National Monument', 'chimney-rock-national-monument', 'weird-history', 37.175, -107.3028, 'Pagosa Springs', 'CO', 'More than 200 Ancestral Pueblo sites occupy a high mesa beneath the twin spires of Chimney Rock and Companion Rock, including a Chacoan-style Great House. Public vehicle access is seasonal and fee-based, with additional guided and night-sky programs offered on selected dates.', 'limited', 'https://www.recreation.gov/activitypass/AP2195', null, 'America/Denver', now()),
  ('Amache National Historic Site', 'amache-national-historic-site', 'weird-history', 38.04962, -102.32903, 'Granada', 'CO', 'The preserved Granada Relocation Center site documents the unjust World War II incarceration of more than 10,000 Japanese Americans. Foundations, reconstructed buildings, cemetery features and interpretive material remain across the former camp landscape.', 'open', 'https://www.nps.gov/amch/index.htm', null, 'America/Denver', now()),
  ('Sand Creek Massacre National Historic Site', 'sand-creek-massacre-national-historic-site', 'weird-history', 38.54442, -102.50438, 'Eads', 'CO', 'This sacred landscape preserves the site where U.S. troops attacked a Cheyenne and Arapaho village in 1864, killing mostly women, children and elders. NPS trails and overlooks interpret the event and its continuing legacy; access includes several miles of dirt road.', 'open', 'https://www.nps.gov/sand/index.htm', null, 'America/Denver', now()),
  ('Bent''s Old Fort National Historic Site', 'bents-old-fort-national-historic-site', 'weird-history', 38.03978, -103.42665, 'La Junta', 'CO', 'A reconstructed 1840s adobe trading fort stands on the Santa Fe Trail where traders, travelers and Indigenous nations interacted on the borderlands. Living-history interpretation and the massive adobe reconstruction make it an unusually immersive historical stop.', 'open', 'https://www.nps.gov/beol/index.htm', null, 'America/Denver', now()),
  ('Ludlow Massacre Memorial', 'ludlow-massacre-memorial', 'weird-history', 37.33925, -104.58378, 'Ludlow', 'CO', 'A monument and archaeological landscape mark the 1914 attack on striking coal miners and their families during the Colorado Coalfield War. Visitors should treat the memorial and burial-related areas as commemorative ground rather than a paranormal attraction.', 'open', 'https://www.historycolorado.org/ludlow-tent-colony-site', null, 'America/Denver', now()),
  ('Boggsville Historic Site', 'boggsville-historic-site', 'weird-history', 38.0417, -103.2127, 'Las Animas', 'CO', 'A few restored adobe buildings and foundations survive from an 1860s settlement on a branch of the Santa Fe Trail associated with Thomas Boggs, John Prowers and Kit Carson. The site has seasonal staffed hours, while self-guided interpretation is available more broadly.', 'limited', 'https://www.nps.gov/places/boggsville-historic-site.htm', null, 'America/Denver', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;

select count(*) as colorado from public.stops where state = 'CO';
