-- Connecticut, first batch.
--
-- Twenty-three categories arrived outside the enum, the most of any batch so
-- far, and every one was an accurate description of its stop: vampire-lore for
-- the Jewett City vampires, paleontology for the dinosaur trackway parks,
-- odd-shops for the Book Barn.
--
-- The mapping now lives in scripts/import-categories.mts rather than being
-- rewritten for each state. Four batches in a row needed it, and deciding
-- afresh every time meant 'ruins' could mean one thing in Ohio and another
-- here. It throws on anything unmapped rather than guessing, because a wrong
-- category files a stop where nobody browsing for it will look.
--
-- Note the sourcing: 48 of these 50 cite Atlas Obscura. They are credited by
-- name without a link, as agreed, but this is the least varied batch yet and
-- the entries would be stronger with the state parks and historical society
-- pages that exist for most of them.
--
-- 50 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Holy Land USA', 'holy-land-usa', 'roadside-oddities', 41.54925, -73.02981, 'Waterbury', 'CT', 'A former religious theme park covers a Waterbury hillside with miniature biblical buildings, grottoes and other handmade structures beneath a huge illuminated cross. The attraction fell into decay after closing in the 1980s but is now being gradually restored, leaving an unusual mix of folk art, ruins and active pilgrimage site.', 'open', 'https://www.atlasobscura.com/places/holy-land-usa', null, 'America/New_York', now()),
  ('Abandoned Fairy Village', 'abandoned-fairy-village', 'weird-history', 41.53916, -73.08517, 'Waterbury', 'CT', 'Tiny stone houses, miniature stairways and a strange little throne sit nearly swallowed by the woods beside an old service road. Local stories have connected the handmade ruins with fairies or elves, although their actual origin is much more earthly. Reach the area only by lawful public access and do not park on Old Waterbury Road.', 'limited', 'https://www.atlasobscura.com/places/abandoned-fairy-village', null, 'America/New_York', now()),
  ('Seaside Sanatorium', 'seaside-sanatorium', 'weird-history', 41.30155, -72.12957, 'Waterford', 'CT', 'This dramatic shoreline complex opened in 1934 as a tuberculosis hospital designed around sunlight and sea air, then later served other institutional uses before closing in 1996. The grounds are now a state park, while the striking abandoned hospital buildings remain fenced and off-limits.', 'open', 'https://www.atlasobscura.com/places/seaside-sanitorium', 'https://ctparks.com/parks/seaside-state-park', 'America/New_York', now()),
  ('Gungywamp', 'gungywamp', 'weird-history', 41.38348, -72.0608, 'Groton', 'CT', 'Gungywamp is a baffling archaeological landscape of stone chambers, walls, rings and other features representing centuries of Indigenous and colonial activity. Its unusual structures have also inspired plenty of speculative theories. Access is controlled and should be through an authorized guided program rather than independent exploration.', 'limited', 'https://www.atlasobscura.com/places/gungywamp', 'https://dpnc.org/', 'America/New_York', now()),
  ('Gay City State Park Ruins', 'gay-city-state-park-ruins', 'weird-history', 41.72251, -72.43621, 'Hebron', 'CT', 'The forest hides stone foundations, cellar holes, a small cemetery and mill ruins left by an abandoned settlement that became known as Gay City. Stories of unexplained deaths and hauntings grew around the vanished community, but the physical ruins themselves are real and can be reached from public park trails.', 'open', 'https://www.atlasobscura.com/places/gay-city-state-park', 'https://ctparks.com/parks/gay-city-state-park', 'America/New_York', now()),
  ('The Old Leatherman''s Cave', 'the-old-leathermans-cave', 'folklore', 41.64017, -73.08796, 'Watertown', 'CT', 'One of the caves associated with the mysterious nineteenth-century wanderer known only as the Old Leatherman sits along his former Connecticut circuit. Dressed almost entirely in handmade leather, he repeatedly walked a roughly 365-mile route through Connecticut and New York while refusing to reveal much about himself.', 'open', 'https://www.atlasobscura.com/places/the-old-leathermans-cave', null, 'America/New_York', now()),
  ('The Singing Bridge', 'the-singing-bridge', 'roadside-oddities', 41.27786, -72.46758, 'Westbrook', 'CT', 'The bridge over the Patchogue River became famous for the musical hum produced as vehicle tires crossed its metal roadway. Rebuilding altered the original structure, but the town preserved the bridge''s unusual open-grate character and its long-running ''singing'' identity.', 'roadside', 'https://www.atlasobscura.com/places/the-singing-bridge', null, 'America/New_York', now()),
  ('Grave of Midnight Mary', 'grave-of-midnight-mary', 'folklore', 41.29941, -72.94975, 'New Haven', 'CT', 'Mary E. Hart''s grave carries an ominous inscription that helped inspire one of New Haven''s best-known cemetery legends. Later stories claimed she was buried alive and now punishes anyone who visits after midnight, although the dramatic tale is folklore rather than documented history.', 'open', 'https://www.atlasobscura.com/places/grave-midnight-mary', null, 'America/New_York', now()),
  ('Museum of Natural and Other Curiosities', 'museum-of-natural-and-other-curiosities', 'museums', 41.76585, -72.6733, 'Hartford', 'CT', 'Hidden inside Connecticut''s Old State House is a recreated early American cabinet of curiosities packed with taxidermy, unusual specimens and historical oddments. Its best-known residents include a two-headed calf and a giant preserved alligator.', 'open', 'https://www.atlasobscura.com/places/museum-natural-other-curiosities', 'https://wp.cga.ct.gov/osh/', 'America/New_York', now()),
  ('The Cushing Center', 'the-cushing-center', 'museums', 41.30318, -72.93348, 'New Haven', 'CT', 'Yale''s Cushing Center preserves more than 2,200 neurosurgical case studies along with human brain and tumor specimens collected by pioneering neurosurgeon Harvey Cushing. It is one of Connecticut''s most unusual medical collections; visitor access policies can change, so check ahead.', 'limited', 'https://www.atlasobscura.com/places/cushing-brain-collection', 'https://library.medicine.yale.edu/cushingcenter', 'America/New_York', now()),
  ('Book Barn', 'book-barn', 'roadside-oddities', 41.32184, -72.20824, 'Niantic', 'CT', 'Hundreds of thousands of used books are scattered through buildings, sheds and themed corners at this sprawling book compound. Cats, goats, strange decorations and sections with names such as Hades and The Haunted make it feel more like a literary scavenger hunt than a normal bookstore.', 'open', 'https://www.atlasobscura.com/places/book-barn', 'https://www.bookbarnniantic.com/', 'America/New_York', now()),
  ('Jewett City Vampires', 'jewett-city-vampires', 'folklore', 41.60638, -71.98696, 'Griswold', 'CT', 'After tuberculosis killed multiple members of the Ray family, frightened relatives exhumed corpses in the 1850s and burned remains in an attempt to stop what they believed was a vampire-like curse. The episode belongs to a documented New England tradition in which disease was blamed on the restless dead.', 'open', 'https://www.atlasobscura.com/places/jewett-city-vampires', null, 'America/New_York', now()),
  ('Charles Island', 'charles-island', 'folklore', 41.1912, -73.055, 'Milford', 'CT', 'Charles Island is wrapped in stories of curses, buried treasure and an alleged Captain Kidd connection. At low tide a sandbar can appear to connect it with shore, but currents and rapidly changing tides make crossing dangerous, and seasonal wildlife closures prohibit access during nesting periods.', 'limited', 'https://www.atlasobscura.com/places/cursed-charles-island', null, 'America/New_York', now()),
  ('Dinosaur State Park', 'dinosaur-state-park', 'museums', 41.65118, -72.65851, 'Rocky Hill', 'CT', 'Thousands of Early Jurassic dinosaur tracks were uncovered here by accident in 1966. Hundreds remain visible beneath a retro-futuristic geodesic dome, while many more were reburied for preservation below the surrounding landscape.', 'open', 'https://www.atlasobscura.com/places/dinosaur-state-park', 'https://ctparks.com/parks/dinosaur-state-park', 'America/New_York', now()),
  ('Judges Cave', 'judges-cave', 'weird-history', 41.33857, -72.96666, 'New Haven', 'CT', 'A jumble of boulders in West Rock became the hiding place of English regicides Edward Whalley and William Goffe after the restoration of King Charles II. The natural shelter is now marked as Judges Cave and can be reached by park trails.', 'open', 'https://www.atlasobscura.com/places/judges-cave', null, 'America/New_York', now()),
  ('World''s Tallest Uncle Sam Statue', 'worlds-tallest-uncle-sam-statue', 'roadside-oddities', 41.3979, -73.4501, 'Danbury', 'CT', 'A gigantic fiberglass Uncle Sam towers over the Danbury Railway Museum property. The roughly 38-foot figure is a classic product of the giant roadside-statue era and returned to Danbury after spending years at other locations.', 'open', 'https://www.roadsideamerica.com/story/2510', 'https://www.danburyrail.org/', 'America/New_York', now()),
  ('Thread City Crossing — Frog Bridge', 'thread-city-crossing-frog-bridge', 'folklore', 41.70997, -72.20954, 'Willimantic', 'CT', 'Four enormous bronze frogs perch on equally enormous thread spools at the corners of this bridge. The sculptures combine Willimantic''s textile history with the famous 1750s ''Battle of the Frogs,'' when mysterious nighttime noises terrified residents before being traced to masses of frogs.', 'roadside', 'https://www.atlasobscura.com/places/thread-city-crossing-bridge', null, 'America/New_York', now()),
  ('Wells Dinosaur Haven', 'wells-dinosaur-haven', 'roadside-oddities', 41.49196, -72.09998, 'Uncasville', 'CT', 'A private backyard has been transformed into a homemade dinosaur park filled with large hand-built prehistoric creatures. Visitors have historically been welcomed with permission, but this is residential property: ask first and never wander onto the grounds uninvited.', 'private', 'https://www.atlasobscura.com/places/wells-dinosaur-haven', null, 'America/New_York', now()),
  ('The Grave of XYZ', 'the-grave-of-xyz', 'weird-history', 41.38548, -72.42816, 'Deep River', 'CT', 'A tiny stone marked only ''XYZ'' identifies the burial place of an unidentified bank robber killed during an 1899 attempted robbery. For decades, local lore said a mysterious woman dressed in black appeared at the grave every year around the anniversary of his death.', 'open', 'https://www.atlasobscura.com/places/the-grave-of-xyz-deep-river-connecticut', null, 'America/New_York', now()),
  ('Old New-Gate Prison & Copper Mine', 'old-new-gate-prison-copper-mine', 'weird-history', 41.96272, -72.745, 'East Granby', 'CT', 'America''s first state prison was created inside an old copper mine, where prisoners were lowered into underground chambers that proved almost impossible to manage. The preserved ruins and mine tunnels can be toured seasonally.', 'limited', 'https://www.atlasobscura.com/places/old-newgate-prison', 'https://portal.ct.gov/DECD/Content/Historic-Preservation/04_State_Museums/Old-New-Gate-Prison-and-Copper-Mine', 'America/New_York', now()),
  ('Barker Character, Comic and Cartoon Museum', 'barker-character-comic-and-cartoon-museum', 'museums', 41.53143, -72.8944, 'Cheshire', 'CT', 'Tens of thousands of character toys, lunchboxes, figures, advertising pieces and cartoon collectibles crowd this family-run museum. The collection spans generations of American pop culture and has the dense, slightly overwhelming feel of a giant toy attic.', 'open', 'https://www.atlasobscura.com/places/barker-character-comic-and-cartoon-museum-2', 'https://www.barkermuseum.com/', 'America/New_York', now()),
  ('PEZ Visitor Center', 'pez-visitor-center', 'museums', 41.26367, -72.99754, 'Orange', 'CT', 'PEZ''s Connecticut visitor center holds the world''s largest public collection of PEZ memorabilia, a giant dispenser and windows into the working candy factory. It turns one of the world''s strangest candy-delivery systems into a full museum stop.', 'open', 'https://www.atlasobscura.com/places/pez-visitor-center', 'https://us.pez.com/pages/hours-and-location', 'America/New_York', now()),
  ('New England Carousel Museum', 'new-england-carousel-museum', 'museums', 41.67103, -72.93949, 'Bristol', 'CT', 'Antique carousel horses and other hand-carved animals fill this museum devoted to the art and mechanics of the American carousel. Visitors can also see restoration work and ride a working indoor carousel.', 'open', 'https://www.atlasobscura.com/places/new-england-carousel-museum', 'https://www.thecarouselmuseum.org/', 'America/New_York', now()),
  ('Ancient Burying Ground', 'ancient-burying-ground', 'weird-history', 41.76466, -72.67426, 'Hartford', 'CT', 'Hartford''s oldest surviving cemetery holds generations of the city''s earliest residents in an increasingly compressed downtown landscape. Thousands were buried here, sometimes in layered graves, while later city development transformed the land around the burial ground.', 'open', 'https://www.atlasobscura.com/places/ancient-burying-ground', null, 'America/New_York', now()),
  ('Crypt at Center Church-on-the-Green', 'crypt-at-center-church-on-the-green', 'weird-history', 41.30786, -72.92657, 'New Haven', 'CT', 'When Center Church was constructed over part of New Haven''s old burying ground, the builders preserved a section of the cemetery beneath the building. The resulting basement crypt surrounds visitors with 137 marked gravestones and additional burials believed to remain beneath the floor.', 'limited', 'https://www.atlasobscura.com/places/the-crypt-at-center-church-on-the-green', 'https://centerchurchonthegreen.org/', 'America/New_York', now()),
  ('Grave of Arthur Twining Hadley', 'grave-of-arthur-twining-hadley', 'weird-history', 41.31378, -72.92705, 'New Haven', 'CT', 'Former Yale president Arthur Twining Hadley was reportedly buried wearing a Japanese samurai costume given to him during his travels. The grave itself is understated, but the bizarre burial detail has made it one of New Haven''s stranger cemetery stories.', 'open', 'https://www.atlasobscura.com/places/grave-of-arthur-twining-hadley', null, 'America/New_York', now()),
  ('Ephraim Huit Grave', 'ephraim-huit-grave', 'weird-history', 41.85688, -72.63852, 'Windsor', 'CT', 'The 1644 gravestone of minister Ephraim Huit is generally regarded as Connecticut''s oldest surviving dated headstone and one of the oldest legible dated grave markers in the country. Its unusual carved inscription has survived for nearly four centuries.', 'open', 'https://www.atlasobscura.com/places/ephraim-huit-grave', null, 'America/New_York', now()),
  ('Joseph Barratt''s Grave', 'joseph-barratts-grave', 'museums', 41.55841, -72.66281, 'Middletown', 'CT', 'Physician and amateur naturalist Joseph Barratt chose a fittingly strange monument: his grave incorporates casts connected with Connecticut dinosaur tracks and fossil plant material. It is an eccentric intersection of nineteenth-century science and funerary art.', 'open', 'https://www.atlasobscura.com/places/joseph-barratts-grave', null, 'America/New_York', now()),
  ('Shade Swamp Sanctuary — Abandoned Zoo', 'shade-swamp-sanctuary-abandoned-zoo', 'weird-history', 41.70512, -72.86087, 'Farmington', 'CT', 'Stone and concrete remnants of a Depression-era wildlife facility hide in the woods of today''s Shade Swamp Sanctuary. Old cages and foundations give the otherwise ordinary nature preserve the atmosphere of an abandoned woodland zoo.', 'open', 'https://www.atlasobscura.com/places/shade-swamp-sanctuary', null, 'America/New_York', now()),
  ('Blue Lady of Yantic Cemetery', 'blue-lady-of-yantic-cemetery', 'weird-history', 41.53937, -72.0892, 'Norwich', 'CT', 'A distinctive blue-green bronze woman watches over a grave in Yantic Cemetery. The statue has inspired local stories about who she represents and what she once held, and after being stolen in 2010 she was recovered and returned to the cemetery.', 'open', 'https://www.atlasobscura.com/places/maud-s-grave', null, 'America/New_York', now()),
  ('Demon Murder Trial Sites', 'demon-murder-trial-sites', 'haunted', 41.39046, -73.44739, 'Danbury', 'CT', 'Danbury became the center of national attention during the 1981 murder trial of Arne Cheyenne Johnson, whose defense attempted to argue that demonic possession played a role in the killing. The court rejected possession as a legal defense, but the case became one of Connecticut''s most famous intersections of true crime and paranormal belief.', 'roadside', 'https://www.atlasobscura.com/places/demon-murder-trial-sites', null, 'America/New_York', now()),
  ('Snake Rock', 'snake-rock', 'roadside-oddities', 41.62837, -72.46252, 'Marlborough', 'CT', 'A large roadside boulder has been repeatedly painted into a bright reptilian creature, usually interpreted as a snake or turtle. The identity of the original artist is murky, and generations of repainting have turned it into a persistent piece of local roadside folk art.', 'roadside', 'https://www.atlasobscura.com/places/snake-rock', null, 'America/New_York', now()),
  ('Sleeping Giant Observation Tower & Hobbomock Legend', 'sleeping-giant-observation-tower-hobbomock-legend', 'folklore', 41.42097, -72.89924, 'Hamden', 'CT', 'The long ridge resembles a giant figure lying on its back and is tied to Indigenous traditions involving the giant spirit Hobbomock. A stone observation tower built in the 1930s stands at the end of one of the park''s best-known hikes.', 'open', 'https://www.atlasobscura.com/places/sleeping-giant-observation-tower', 'https://ctparks.com/parks/sleeping-giant-state-park', 'America/New_York', now()),
  ('Traffic Control Tower', 'traffic-control-tower', 'weird-history', 41.53769, -72.80267, 'Meriden', 'CT', 'This tiny 1925 tower once held a police officer who manually controlled traffic lights at a busy Meriden intersection. Restored as a monument, it preserves an odd transitional stage between hand signals and automated traffic systems.', 'roadside', 'https://www.atlasobscura.com/places/traffic-control-tower', null, 'America/New_York', now()),
  ('Hubbard Park — Black Dog Legend', 'hubbard-park-black-dog-legend', 'folklore', 41.54959, -72.83563, 'Meriden', 'CT', 'The Hanging Hills around Hubbard Park are home to the legend of a small black dog whose appearances supposedly grow increasingly ominous: seeing it once brings joy, twice brings sorrow and a third sighting foretells death. The story is folklore, but it has been repeated for generations.', 'open', 'https://www.atlasobscura.com/places/hubbard-park', 'https://www.meridenct.gov/parks-and-recreation/parks/hubbard-park/', 'America/New_York', now()),
  ('Satan''s Kingdom State Recreation Area', 'satans-kingdom-state-recreation-area', 'folklore', 41.85725, -72.95835, 'New Hartford', 'CT', 'Despite the ominous name, Satan''s Kingdom is now a popular river recreation area. Competing stories have tried to explain the name through rough terrain, outlaw hideouts and local folklore, giving an otherwise scenic park one of Connecticut''s best place names.', 'open', 'https://www.atlasobscura.com/places/satans-kingdom', null, 'America/New_York', now()),
  ('Boothe Memorial Park', 'boothe-memorial-park', 'roadside-oddities', 41.23521, -73.10946, 'Stratford', 'CT', 'The eccentric Boothe brothers filled their property with unusual structures and collections, many of which survive in today''s public park. Highlights include a miniature lighthouse, an old tollbooth, a blacksmith shop with dozens of sides and the wonderfully strange Technocratic Cathedral.', 'open', 'https://www.atlasobscura.com/places/boothe-memorial-park', 'https://www.stratfordct.gov/content/39832/39846/39914.aspx', 'America/New_York', now()),
  ('Powder Hill Dinosaur Park', 'powder-hill-dinosaur-park', 'museums', 41.50272, -72.73062, 'Middlefield', 'CT', 'Exposed rock at this small park preserves Early Jurassic dinosaur footprints that visitors can see and touch without entering a museum. It is a compact but unusually direct encounter with Connecticut''s prehistoric past.', 'open', 'https://www.atlasobscura.com/places/powder-hill-dinosaur-park', null, 'America/New_York', now()),
  ('Coltsville & the Blue Onion Dome', 'coltsville-the-blue-onion-dome', 'weird-history', 41.75386, -72.67473, 'Hartford', 'CT', 'Samuel Colt built an enormous nineteenth-century industrial complex and planned community around his firearms factory. Its most immediately strange feature is the bright blue onion-shaped dome topped by a gilded colt, still visible above Hartford''s skyline.', 'open', 'https://www.atlasobscura.com/places/coltsville', 'https://www.nps.gov/colt/', 'America/New_York', now()),
  ('Wangunk Statue', 'wangunk-statue', 'roadside-oddities', 41.56181, -72.64634, 'Middletown', 'CT', 'A monumental stylized stone head stands near the Connecticut River as a memorial connected with the Wangunk people who lived in the region. The oversized sculpture is both a public artwork and an unusual visual landmark.', 'open', 'https://www.atlasobscura.com/places/wangunk-statue', null, 'America/New_York', now()),
  ('William Kent Charitable Foundation', 'william-kent-charitable-foundation', 'roadside-oddities', 41.44697, -72.72748, 'Durham', 'CT', 'The former home and studio of reclusive artist William Kent preserves a huge body of woodcuts, sculptures and other unconventional work. The farmhouse functions more like a time capsule of an intensely personal artistic world than a conventional gallery, with visits generally arranged in advance.', 'limited', 'https://www.atlasobscura.com/places/william-kent-charitable-foundation', 'https://www.williamkentfoundation.org/', 'America/New_York', now()),
  ('American Museum of Tort Law', 'american-museum-of-tort-law', 'museums', 41.9228, -73.07543, 'Winsted', 'CT', 'Founded by Ralph Nader, this museum is devoted to civil wrongs, product-liability cases and the lawsuits that changed American consumer safety. Exhibits turn famous cases involving automobiles, dangerous products and corporate negligence into an unexpectedly strange museum subject.', 'limited', 'https://www.atlasobscura.com/places/american-museum-of-tort-law', 'https://www.tortmuseum.org/', 'America/New_York', now()),
  ('Submarine Force Museum & USS Nautilus', 'submarine-force-museum-uss-nautilus', 'museums', 41.3875, -72.087, 'Groton', 'CT', 'The world''s first nuclear-powered submarine, USS Nautilus, is preserved beside the official U.S. Navy Submarine Force Museum. Visitors can descend into the submarine''s cramped interior and explore the strange engineering of life underwater.', 'open', 'https://www.atlasobscura.com/places/submarine-force-museum', 'https://ussnautilus.org/', 'America/New_York', now()),
  ('Gillette Castle State Park', 'gillette-castle-state-park', 'roadside-oddities', 41.423, -72.4284, 'East Haddam', 'CT', 'Actor William Gillette, famous for portraying Sherlock Holmes, built this eccentric stone castle above the Connecticut River with secret doors, custom wooden locks, unusual built-in furniture and an estate railroad. The grounds are broadly accessible while interior castle tours are seasonal.', 'limited', 'https://www.atlasobscura.com/places/gillette-castle-state-park', 'https://ctparks.com/parks/gillette-castle-state-park', 'America/New_York', now()),
  ('Norwich Horton Sphere', 'norwich-horton-sphere', 'roadside-oddities', 41.51205, -72.07586, 'Norwich', 'CT', 'A huge rusting steel sphere rises behind a former industrial property like an abandoned science-fiction prop. The roughly 37-foot Horton sphere was an industrial pressure vessel; it remains fenced off, so this is strictly a lawful public-road viewing stop.', 'roadside', 'https://www.atlasobscura.com/places/norwich-horton-sphere', null, 'America/New_York', now()),
  ('Machimoodus State Park — Moodus Noises', 'machimoodus-state-park-moodus-noises', 'folklore', 41.50236, -72.47731, 'Moodus', 'CT', 'For generations the area was famous for mysterious subterranean booms and rumblings remembered in Indigenous traditions and later colonial folklore. Geologists eventually linked the ''Moodus Noises'' to shallow microearthquakes, giving the park a rare combination of genuine geology and centuries of strange stories.', 'open', 'https://ctparks.com/parks/machimoodus-state-park', 'https://ctparks.com/parks/machimoodus-state-park', 'America/New_York', now()),
  ('Witch''s Dungeon Classic Movie Museum', 'witchs-dungeon-classic-movie-museum', 'museums', 41.67346, -72.86261, 'Plainville', 'CT', 'One of America''s longest-running classic monster attractions displays life-size horror figures, movie memorabilia and handmade recreations inspired by Universal-era monsters. Created by Cortlandt Hull, whose family had ties to classic horror cinema, the museum operates on a limited schedule.', 'limited', 'https://www.atlasobscura.com/places/witchs-dungeon', 'https://www.preservehollywood.org/', 'America/New_York', now()),
  ('Severed Arm of Saint Edmund', 'severed-arm-of-saint-edmund', 'weird-history', 41.32232, -71.96281, 'Stonington', 'CT', 'A chapel at Enders Island preserves a mummified arm traditionally identified as a relic of Saint Edmund of Canterbury. The centuries-old human relic makes an unexpectedly macabre stop within an otherwise peaceful Catholic retreat setting; visitors should respect chapel rules and scheduled access.', 'limited', 'https://www.atlasobscura.com/places/severed-arm-saint-edmund', 'https://endersisland.org/', 'America/New_York', now()),
  ('Ballard Institute and Museum of Puppetry', 'ballard-institute-and-museum-of-puppetry', 'museums', 41.80471, -72.24277, 'Storrs', 'CT', 'More than 2,500 puppets from different cultures and theatrical traditions make up this University of Connecticut collection. Changing exhibitions range from folk puppetry to highly experimental creations, making it one of the state''s stranger specialized museums.', 'open', 'https://www.atlasobscura.com/places/ballard-institute-museum-of-puppetry', 'https://bimp.uconn.edu/', 'America/New_York', now()),
  ('Beinecke Rare Book Library — Voynich Manuscript', 'beinecke-rare-book-library-voynich-manuscript', 'folklore', 41.31153, -72.92714, 'New Haven', 'CT', 'Yale''s extraordinary rare-book library is home to the Voynich Manuscript, the famously undeciphered illustrated codex whose strange script has resisted generations of researchers. The original manuscript is not normally on public display, but the library itself is open to visitors and keeps a facsimile available.', 'open', 'https://www.atlasobscura.com/places/beinecke-rare-book-manuscript-library', 'https://beinecke.library.yale.edu/', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;

select count(*) as connecticut from public.stops where state = 'CT';
