-- Connecticut, third batch.
--
-- Historic Connecticut Toll Booths dropped: identical coordinates to Boothe
-- Memorial Park, which is where the booths were moved to. Zero metres apart
-- means one pin on the map whichever way it is filed.
--
-- Seven more categories mapped. The one worth explaining is food-history,
-- which covers Louis' Lunch: a claim about where the hamburger was invented
-- is a historical claim regardless of what is being served today, and the
-- argument about 1900 is the reason to stop.
--
-- Four other proximity flags kept — Danbury, Hartford and New Haven simply
-- have several stops within a few streets.
--
-- Note the sourcing: 49 of these 50 cite Roadside America, credited without a
-- link. Between this and the 48 from Atlas Obscura in the first batch,
-- Connecticut leans harder on aggregators than any other state in the index.
-- Worth a pass with the state's own tourism and historical society pages.
--
-- 49 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Eagle Rock', 'eagle-rock', 'roadside-oddities', 41.64707, -72.40763, 'Amston', 'CT', 'A large natural rock outcrop beside Route 66 has been painted into a giant American bald eagle, with local volunteers periodically refreshing the image. It is a simple but unmistakable piece of Connecticut roadside folk art.', 'roadside', 'https://www.roadsideamerica.com/tip/3449', null, 'America/New_York', now()),
  ('Transcontinental Airway Arrow', 'transcontinental-airway-arrow', 'weird-history', 41.43967, -72.99229, 'Bethany', 'CT', 'A huge concrete arrow survives from the era when pilots navigated early U.S. airmail routes by following giant ground markers and beacon towers. The preserved arrow sits at the historic Bethany Airport site and is one of the clearest remnants of pre-radio air navigation in the state.', 'open', 'https://www.roadsideamerica.com/tip/89842', null, 'America/New_York', now()),
  ('P.T. Barnum Birthplace Statue', 'pt-barnum-birthplace-statue', 'weird-history', 41.3712, -73.41382, 'Bethel', 'CT', 'A life-size bronze P.T. Barnum stands outside the Bethel Public Library in the showman''s hometown. The statue was commissioned for the 200th anniversary of Barnum''s birth and gives OddWay travelers a direct stop tied to America''s most famous promoter of curiosities.', 'open', 'https://www.roadsideamerica.com/story/60492', null, 'America/New_York', now()),
  ('P.T. Barnum Statue at Seaside Park', 'pt-barnum-statue-at-seaside-park', 'weird-history', 41.16176, -73.19073, 'Bridgeport', 'CT', 'An imposing seated statue of circus impresario P.T. Barnum overlooks the waterfront park he helped create for Bridgeport. Installed after his death, it connects the city directly to the man whose museums, sideshows and spectacles helped define nineteenth-century American entertainment.', 'open', 'https://www.roadsideamerica.com/story/10867', 'https://www.bridgeportct.gov/government/departments/parks-recreation/seaside-park-history', 'America/New_York', now()),
  ('St. Margaret Shrine — Vatican Gardens Knockoff', 'st-margaret-shrine-vatican-gardens-knockoff', 'roadside-oddities', 41.19223, -73.21466, 'Bridgeport', 'CT', 'The grounds of St. Margaret Shrine form a sprawling maze of grottoes, statues, miniature shrines, stonework and gardens inspired partly by European Catholic pilgrimage sites. It feels unexpectedly elaborate for a neighborhood Connecticut shrine and is free to walk during posted hours.', 'open', 'https://www.roadsideamerica.com/location/ct', 'https://www.stmargaretshrine.org/', 'America/New_York', now()),
  ('Lake Compounce — America''s Oldest Amusement Park', 'lake-compounce-americas-oldest-amusement-park', 'weird-history', 41.63882, -72.92295, 'Bristol', 'CT', 'Operating since 1846, Lake Compounce is widely recognized as the oldest continuously operating amusement park in the United States. Its mix of modern rides and surviving historic amusement-park traditions makes it a useful OddWay stop beyond the normal theme-park angle.', 'limited', 'https://www.roadsideamerica.com/tip/25260', 'https://www.lakecompounce.com/', 'America/New_York', now()),
  ('North America''s Tallest Elevator Test Tower', 'north-americas-tallest-elevator-test-tower', 'roadside-oddities', 41.65213, -72.91495, 'Bristol', 'CT', 'A roughly 383-foot elevator research tower rises over Bristol like a windowless skyscraper. Built for testing high-speed elevator systems, it is not a public attraction inside, but its strange scale makes it visible from public roads around the facility.', 'roadside', 'https://www.roadsideamerica.com/tip/8718', null, 'America/New_York', now()),
  ('Large Santa of Vale Road', 'large-santa-of-vale-road', 'roadside-oddities', 41.42771, -73.39389, 'Brookfield', 'CT', 'A giant waving Santa Claus stands year-round outside a storage property on Vale Road. The restored fiberglass figure has become an all-season roadside landmark where Christmas never really ends.', 'roadside', 'https://www.roadsideamerica.com/tip/60708', null, 'America/New_York', now()),
  ('Kid Groot Tree Carving', 'kid-groot-tree-carving', 'roadside-oddities', 41.52091, -72.89538, 'Cheshire', 'CT', 'A dead roadside tree was carved into an oversized version of Kid Groot from Guardians of the Galaxy. The sculpture is illuminated after dark and is occasionally dressed for holidays, giving the residential roadside piece an evolving personality.', 'roadside', 'https://www.roadsideamerica.com/tip/85729', null, 'America/New_York', now()),
  ('Miracle Survivor Mary Statue', 'miracle-survivor-mary-statue', 'roadside-oddities', 41.57138, -72.33705, 'Colchester', 'CT', 'A statue of Mary survived a 2004 explosion and fire that destroyed the former St. Mary''s Ukrainian Catholic Church around it. The congregation preserved the surviving figure at the rebuilt church as a physical reminder of the disaster.', 'open', 'https://www.roadsideamerica.com/tip/9620', null, 'America/New_York', now()),
  ('John Oliver Memorial Sewer Plant', 'john-oliver-memorial-sewer-plant', 'folklore', 41.4033, -73.42287, 'Danbury', 'CT', 'After comedian John Oliver mocked Danbury on television, the mayor jokingly threatened to name the city''s sewage plant after him — and the city ultimately followed through. A sign now officially identifies the John Oliver Memorial Sewer Plant, turning a municipal facility into a comedy landmark.', 'roadside', 'https://www.roadsideamerica.com/tip/71591', null, 'America/New_York', now()),
  ('Sybil Ludington Statue', 'sybil-ludington-statue', 'weird-history', 41.39291, -73.45137, 'Danbury', 'CT', 'A bronze Sybil Ludington rides through downtown Danbury in memory of the teenage messenger traditionally credited with a long Revolutionary War nighttime ride. Historians debate parts of the famous story, which gives the monument an interesting mix of history and legend.', 'open', 'https://www.roadsideamerica.com/tip/23188', null, 'America/New_York', now()),
  ('Two-Faced Dog Rock', 'two-faced-dog-rock', 'roadside-oddities', 41.41873, -73.44998, 'Danbury', 'CT', 'A roadside boulder has been painted as a cartoon dog with a different expression on each visible side. The rock was repainted in 2016, transforming one formerly snarling face into a sadder and friendlier-looking dog.', 'roadside', 'https://www.roadsideamerica.com/tip/86255', null, 'America/New_York', now()),
  ('Praying Mantis Reading Lord of the Flies', 'praying-mantis-reading-lord-of-the-flies', 'roadside-oddities', 41.38257, -72.44544, 'Deep River', 'CT', 'A large scrap-metal praying mantis sits reading Lord of the Flies — an appropriately insect-themed literary joke. The sculpture moved from the local library in 2025 and now stands at the Pandemonium Rainforest Project.', 'open', 'https://www.roadsideamerica.com/tip/73599', 'https://www.pandemoniumrainforestproject.org/', 'America/New_York', now()),
  ('Lincoln Career Column', 'lincoln-career-column', 'roadside-oddities', 41.7687, -72.66353, 'East Hartford', 'CT', 'One of the pieces on the Hartford-area Lincoln Financial Sculpture Walk compresses major stages of Abraham Lincoln''s life and career into a vertical sculptural column. It is part history lesson and part unconventional presidential monument.', 'open', 'https://www.roadsideamerica.com/tip/65811', null, 'America/New_York', now()),
  ('Lincoln Welcomes Your Conversation', 'lincoln-welcomes-your-conversation', 'roadside-oddities', 41.76846, -72.66276, 'East Hartford', 'CT', 'A life-size young Abraham Lincoln sits on a boulder with his hand extended toward an empty neighboring rock, deliberately inviting visitors to sit beside him. The 2006 sculpture is one of the more interactive presidential monuments in Connecticut.', 'open', 'https://www.roadsideamerica.com/tip/65809', null, 'America/New_York', now()),
  ('Action Wildlife Taxidermy Museum', 'action-wildlife-taxidermy-museum', 'museums', 41.83254, -73.19709, 'Goshen', 'CT', 'Beyond the live-animal park, Action Wildlife maintains a museum filled with mounted animals and natural-history displays. The unusual concentration of taxidermy makes it a distinct stop within the larger wildlife property; current park admission includes museum access.', 'limited', 'https://www.roadsideamerica.com/location/ct', 'https://www.actionwildlifefoundation.com/', 'America/New_York', now()),
  ('Gozzi''s Colorful Turkeys', 'gozzis-colorful-turkeys', 'roadside-oddities', 41.30931, -72.72274, 'Guilford', 'CT', 'Each holiday season, Gozzi''s Turkey Farm displays live turkeys whose feathers are dyed vivid colors including pink, purple and green. The tradition has become a peculiar local Thanksgiving and Christmas-season ritual rather than a normal farm visit.', 'limited', 'https://www.roadsideamerica.com/tip/14180', null, 'America/New_York', now()),
  ('Ernest Borgnine Park', 'ernest-borgnine-park', 'weird-history', 41.34427, -72.92923, 'Hamden', 'CT', 'A tiny patch of land at a shopping-center corner is officially dedicated to Hamden-born actor Ernest Borgnine. Its modest size compared with the Oscar-winning actor it honors is part of the charm.', 'open', 'https://www.roadsideamerica.com/tip/22258', null, 'America/New_York', now()),
  ('Mini Lincoln Meets Harriet Beecher Stowe', 'mini-lincoln-meets-harriet-beecher-stowe', 'roadside-oddities', 41.76521, -72.66715, 'Hartford', 'CT', 'Miniature bronze versions of Abraham Lincoln and Harriet Beecher Stowe face one another across an outdoor table on the riverwalk. The sculpture commemorates their real 1862 meeting but intentionally presents the famously tall Lincoln at a surprisingly tiny scale.', 'open', 'https://www.roadsideamerica.com/story/48207', null, 'America/New_York', now()),
  ('Sculpturedale', 'sculpturedale', 'roadside-oddities', 41.78388, -73.41756, 'Kent', 'CT', 'Sculptor Denis Curtiss has filled his rural studio grounds with more than 100 large steel and bronze animals, people and other figures. The property is an active studio and gallery, so visitors should stick to posted open hours or arrange an appointment.', 'limited', 'https://www.roadsideamerica.com/tip/76115', 'https://kentct.com/shop', 'America/New_York', now()),
  ('Smallpox Mass Grave Monument', 'smallpox-mass-grave-monument', 'weird-history', 41.2258, -73.05226, 'Milford', 'CT', 'A sandstone obelisk in Milford Cemetery marks a mass grave connected to Continental Army prisoners suffering from smallpox after being released from a British prison ship in 1777. Forty-six prisoners died within weeks, leaving one of Connecticut''s grimmer Revolutionary War memorials.', 'limited', 'https://www.roadsideamerica.com/tip/24369', null, 'America/New_York', now()),
  ('Sparky the Firehouse Dog Rock', 'sparky-the-firehouse-dog-rock', 'roadside-oddities', 41.4403, -72.11465, 'Montville', 'CT', 'A boulder outside the Montville fire company has been painted into a spotted firehouse dog named Sparky. It joins eastern Connecticut''s unusual local tradition of turning roadside rocks into oversized canine faces.', 'roadside', 'https://www.roadsideamerica.com/tip/45645', null, 'America/New_York', now()),
  ('Mission Creep Fire Hydrant', 'mission-creep-fire-hydrant', 'roadside-oddities', 41.25887, -72.89824, 'New Haven', 'CT', 'A cast-iron sculpture outside Lighthouse Fire Station began as a tribute to firefighters and gradually accumulated more symbolic details, including an oversized hydrant. The finished piece is part monument and part wonderfully overbuilt firehouse lawn art.', 'roadside', 'https://www.roadsideamerica.com/story/68758', null, 'America/New_York', now()),
  ('18-Foot Fish Made of Dining Utensils', '18-foot-fish-made-of-dining-utensils', 'roadside-oddities', 41.35497, -71.96805, 'Mystic', 'CT', 'Hundreds of forks, knives and spoons were welded into an 18-foot upright striped bass outside S&P Oyster Restaurant. The fish was created in 2022 using utensils supplied by the restaurant itself.', 'open', 'https://www.roadsideamerica.com/tip/81872', 'https://www.sp-oyster.com/', 'America/New_York', now()),
  ('Mystic Pizza', 'mystic-pizza', 'roadside-oddities', 41.35463, -71.97164, 'Mystic', 'CT', 'The real Mystic Pizza inspired the title and setting of the 1988 film that helped launch Julia Roberts'' career. The restaurant was not the movie''s interior filming location, but it embraces the connection with photographs, memorabilia and its now-famous name.', 'open', 'https://www.roadsideamerica.com/tip/6540', 'https://mysticpizzaoriginal.com/', 'America/New_York', now()),
  ('Super Cow — Guida''s Dairy Mascot', 'super-cow-guidas-dairy-mascot', 'roadside-oddities', 41.66552, -72.76964, 'New Britain', 'CT', 'A costumed superhero cow appears to leap across the roof of the Guida''s Dairy building. The airborne bovine is a wonderfully literal dairy mascot and one of New Britain''s easiest drive-by oddities.', 'roadside', 'https://www.roadsideamerica.com/tip/33135', null, 'America/New_York', now()),
  ('The Glass House', 'the-glass-house', 'roadside-oddities', 41.14242, -73.52939, 'New Canaan', 'CT', 'Architect Philip Johnson''s nearly transparent 1949 home reduces a house to a glass rectangle exposed on every side. The property also contains a collection of experimental buildings and landscape structures; entry is available only through scheduled tours.', 'limited', 'https://www.roadsideamerica.com/tip/42971', 'https://theglasshouse.org/', 'America/New_York', now()),
  ('East Rock Soldiers'' and Sailors'' Monument', 'east-rock-soldiers-and-sailors-monument', 'weird-history', 41.32725, -72.90462, 'New Haven', 'CT', 'A tall nineteenth-century war monument crowns East Rock above New Haven, reached by road or trail depending on seasonal access. The summit setting makes the ornate monument feel more like a hilltop shrine than a conventional downtown memorial.', 'open', 'https://www.roadsideamerica.com/story/26977', null, 'America/New_York', now()),
  ('Louis'' Lunch — Home of the Hamburger', 'louis-lunch-home-of-the-hamburger', 'weird-history', 41.30647, -72.93041, 'New Haven', 'CT', 'Louis'' Lunch claims to have served the first hamburger sandwich in 1900 and still cooks its burgers vertically in antique cast-iron broilers. The tiny restaurant also famously resists ketchup, preserving an unusually strict piece of food history.', 'open', 'https://www.roadsideamerica.com/story/15421', 'https://louislunch.com/', 'America/New_York', now()),
  ('Blessed Michael McGivney Pilgrimage Center', 'blessed-michael-mcgivney-pilgrimage-center', 'weird-history', 41.3021, -72.92386, 'New Haven', 'CT', 'The former Knights of Columbus Museum now centers on the life of founder Michael McGivney while retaining exhibits on the Catholic fraternal organization''s history and religious material culture. It is a specialized museum in an unexpectedly monumental downtown building.', 'open', 'https://www.roadsideamerica.com/tip/5688', 'https://www.michaelmcgivneycenter.org/', 'America/New_York', now()),
  ('Iwo Jima Survivors Memorial Park', 'iwo-jima-survivors-memorial-park', 'weird-history', 41.6982, -72.7586, 'Newington', 'CT', 'A dramatic bronze monument recreates the famous flag-raising on Iwo Jima and specifically honors Connecticut servicemen who fought in the battle. The park was developed with the involvement of surviving veterans and includes additional memorial elements.', 'open', 'https://www.roadsideamerica.com/story/7831', null, 'America/New_York', now()),
  ('Wrong Site of Amelia Earhart''s Secret Wedding', 'wrong-site-of-amelia-earharts-secret-wedding', 'weird-history', 41.32596, -71.99136, 'Noank', 'CT', 'A plaque at the Latham/Chester Store identifies the building with Amelia Earhart''s secret 1931 wedding — except local historical research places the actual ceremony at a different house nearby. The confidently incorrect memorial makes the mistake itself the attraction.', 'limited', 'https://www.roadsideamerica.com/tip/49401', 'https://noankhistoricalsociety.org/', 'America/New_York', now()),
  ('Stew Leonard''s — World''s Largest Dairy Store', 'stew-leonards-worlds-largest-dairy-store', 'roadside-oddities', 41.12247, -73.40186, 'Norwalk', 'CT', 'Stew Leonard''s original Norwalk store grew from a small dairy shop into a maze-like food market filled with singing animatronics, costumed characters and theatrical displays. Guinness once recognized it as the world''s largest dairy store.', 'open', 'https://www.roadsideamerica.com/story/2052', 'https://www.stewleonards.com/', 'America/New_York', now()),
  ('Slater Memorial Museum — Mummified Human Arm', 'slater-memorial-museum-mummified-human-arm', 'museums', 41.53629, -72.08152, 'Norwich', 'CT', 'Among the art and historical collections at the Slater Memorial Museum is a preserved human arm brought back from Egypt during the nineteenth century. The unexpected mummy fragment is one of the strangest objects in an otherwise traditional museum.', 'limited', 'https://www.roadsideamerica.com/story/56735', 'https://www.slatermuseum.org/', 'America/New_York', now()),
  ('Woodrow Wilson''s Canoe', 'woodrow-wilsons-canoe', 'weird-history', 41.32574, -72.32694, 'Old Lyme', 'CT', 'The Florence Griswold Museum preserves a canoe used by Woodrow Wilson during visits to the Lyme Art Colony before his presidency. The ordinary-looking boat is an unusually personal artifact tucked into a museum better known for American Impressionism.', 'open', 'https://www.roadsideamerica.com/tip/67054', 'https://florencegriswoldmuseum.org/', 'America/New_York', now()),
  ('Snoopy Rock', 'snoopy-rock', 'roadside-oddities', 41.52676, -72.0526, 'Preston', 'CT', 'A giant glacial boulder has been painted into Snoopy''s smiling profile, with a plywood Charlie Brown standing nearby to complete the scene. The attraction is on private property where visitors have historically been tolerated, so stay in the designated approach area and be respectful.', 'private', 'https://www.roadsideamerica.com/tip/45889', null, 'America/New_York', now()),
  ('Spotty the Rock Dog', 'spotty-the-rock-dog', 'roadside-oddities', 41.52274, -72.01883, 'Preston', 'CT', 'This black-and-white dog-shaped boulder has reportedly been maintained as ''Spotty'' since 1935. A small plaque credits the original painter, making it one of the oldest surviving examples in eastern Connecticut''s peculiar painted-dog-rock tradition.', 'roadside', 'https://www.roadsideamerica.com/tip/22504', null, 'America/New_York', now()),
  ('Gertrude Chandler Warner Boxcar Children Museum', 'gertrude-chandler-warner-boxcar-children-museum', 'museums', 41.90946, -71.90347, 'Putnam', 'CT', 'Putnam honors Boxcar Children author Gertrude Chandler Warner with a museum housed inside a real 1920s railroad boxcar. The tiny seasonal museum contains books, memorabilia and personal objects connected with the author.', 'limited', 'https://www.roadsideamerica.com/tip/10028', null, 'America/New_York', now()),
  ('D''Elia Antique Tool Museum', 'delia-antique-tool-museum', 'museums', 41.69661, -72.08215, 'Scotland', 'CT', 'A small museum connected to the Scotland Public Library preserves an obsessive collection of roughly 1,500 woodworking planes spanning several centuries. Its extremely narrow subject matter is exactly what makes it an OddWay-worthy stop.', 'limited', 'https://www.roadsideamerica.com/tip/62387', null, 'America/New_York', now()),
  ('9/11 Beam Memorial to Local Flight Crew', '9-11-beam-memorial-to-local-flight-crew', 'weird-history', 41.96859, -72.34392, 'Stafford Springs', 'CT', 'A recovered steel beam from the World Trade Center stands outside the West Stafford Fire Department. The memorial particularly honors two local residents who were crew members aboard United Airlines Flight 175.', 'open', 'https://www.roadsideamerica.com/tip/42981', null, 'America/New_York', now()),
  ('Mohegan Sun Walk of Fame', 'mohegan-sun-walk-of-fame', 'roadside-oddities', 41.49185, -72.09084, 'Uncasville', 'CT', 'Blue stars embedded around the Mohegan Sun Arena entrance commemorate performers who have appeared at the casino resort. The casino''s take on a Hollywood-style walk of fame has steadily accumulated names over the years.', 'open', 'https://www.roadsideamerica.com/tip/5169', 'https://mohegansun.com/', 'America/New_York', now()),
  ('Mattatuck Museum Button Gallery', 'mattatuck-museum-button-gallery', 'museums', 41.55741, -73.04315, 'Waterbury', 'CT', 'Thousands of buttons form a permanent collection inside the Mattatuck Museum, ranging from military and fashion pieces to unusually elaborate carved and novelty examples. The collection grew from a much larger archive assembled during Waterbury''s industrial era.', 'open', 'https://www.roadsideamerica.com/tip/6857', 'https://www.mattmuseum.org/', 'America/New_York', now()),
  ('Connecticut Valley Tobacco Museum', 'connecticut-valley-tobacco-museum', 'museums', 41.89909, -72.70355, 'Windsor', 'CT', 'Inside Northwest Park, historic tobacco sheds and exhibits preserve the tools and techniques behind Connecticut River Valley shade tobacco. The highly specialized museum explains an agricultural industry that once shaped the region''s landscape and international trade.', 'limited', 'https://ctvalleytobaccohistorical.org/', 'https://ctvalleytobaccohistorical.org/', 'America/New_York', now()),
  ('Conny the Whale''s Tail', 'conny-the-whales-tail', 'roadside-oddities', 41.76203, -72.73678, 'West Hartford', 'CT', 'Conny was once a walk-through, life-size sperm-whale sculpture outside the Children''s Museum. When the museum moved, the enormous whale was cut apart; its surviving tail was reinstalled beside the Trout Brook Trail as an intentionally strange remnant of the original landmark.', 'open', 'https://www.roadsideamerica.com/tip/1810', null, 'America/New_York', now()),
  ('Travelers Giant Red Umbrella', 'travelers-giant-red-umbrella', 'roadside-oddities', 41.86067, -72.68379, 'Windsor', 'CT', 'A roughly 30-foot version of Travelers Insurance''s red umbrella logo stands outside the company''s Claim University campus. The giant corporate symbol was moved from Hartford to Windsor and is visible from the public approach even when the facility is closed.', 'roadside', 'https://www.roadsideamerica.com/tip/92907', null, 'America/New_York', now()),
  ('Castle Tower Civil War Monument', 'castle-tower-civil-war-monument', 'weird-history', 41.92472, -73.07278, 'Winsted', 'CT', 'Winsted''s 1890 Soldiers'' Monument looks less like a conventional obelisk and more like a small Gothic castle tower, complete with a soldier standing on its parapet. The hilltop structure overlooks town and opens for interior tours only on selected commemorative days.', 'limited', 'https://www.roadsideamerica.com/tip/50878', null, 'America/New_York', now()),
  ('Leslie Murray''s Junk People', 'leslie-murrays-junk-people', 'roadside-oddities', 41.54804, -73.18971, 'Woodbury', 'CT', 'Scrap metal, discarded machinery and automotive parts have been assembled into human figures outside Murray Brothers Garage. The homemade characters turn an ordinary repair-shop lot into a compact roadside sculpture garden.', 'roadside', 'https://www.roadsideamerica.com/story/71908', null, 'America/New_York', now()),
  ('Roseland Cottage — 1846 Bowling Alley', 'roseland-cottage-1846-bowling-alley', 'roadside-oddities', 41.94938, -71.97625, 'Woodstock', 'CT', 'Inside the bright Gothic Revival Roseland Cottage is an indoor bowling alley dating to 1846, often described as the oldest surviving example in the United States. The alley is included on seasonal guided tours of the house.', 'limited', 'https://www.roadsideamerica.com/tip/48563', 'https://www.historicnewengland.org/property/roseland-cottage/', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;

select count(*) as connecticut from public.stops where state = 'CT';
