-- Connecticut, second batch.
--
-- Paul Bunyan Muffler Man goes in as paul-bunyan-muffler-man-cheshire,
-- because Muncie, Indiana holds the plain slug. Muffler men came from a small
-- number of moulds, so many share a name and none share a location.
--
-- Penfield Reef Lighthouse nearly did not make it: its access was written
-- 'view-only', which the parser did not recognise, and the whole stop was
-- dropped in silence. The parser now maps hyphenated access values and asserts
-- on anything it cannot place rather than skipping the row.
--
-- Five more categories added to the shared map. The mapping refused to guess
-- and stopped the run, which is what it is for — 'space' covering a moon rock
-- on a plinth and 'odd-restaurants' covering a diner that gives you books are
-- both roadside oddities, but that is a decision worth making once and writing
-- down rather than inferring under time pressure.
--
-- Four proximity flags, all kept. New Haven Green and the crypt under Center
-- Church are thirty metres apart and tell one story from two sides: the Green
-- has a burial ground beneath it, the crypt is the part you can enter. The
-- Uncle Sam statue is 31 metres from the Danbury Railway Museum because it
-- stands in the museum's yard.
--
-- 50 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Traveler Restaurant — Free Books With Your Meal', 'traveler-restaurant-free-books-with-your-meal', 'roadside-oddities', 42.02533, -72.13991, 'Union', 'CT', 'A roadside restaurant on the Massachusetts line where every diner is invited to leave with free used books. Shelves crowd the dining room and thousands more books are stored throughout the property, turning a highway meal into an unusually literal food-and-books stop.', 'open', 'https://www.atlasobscura.com/places/traveler-restaurant', 'https://travelerrestaurant.com/', 'America/New_York', now()),
  ('Johnsonville Village', 'johnsonville-village', 'weird-history', 41.49496, -72.46652, 'East Haddam', 'CT', 'A nineteenth-century mill village of old houses and industrial buildings survives along the Moodus River after decades of abandonment and repeated attempts at redevelopment. The village is now private property, so OddWay visitors should view only from lawful public roads and never enter buildings or grounds without permission.', 'private', 'https://www.atlasobscura.com/places/johnsonville-village', null, 'America/New_York', now()),
  ('Hearthstone Castle', 'hearthstone-castle', 'weird-history', 41.3781, -73.44849, 'Danbury', 'CT', 'A crumbling stone castle built in the 1890s stands inside Tarrywile Park. The surrounding park is public, but the deteriorated castle itself is fenced and closed to entry, making this a legal exterior-view ruins stop rather than an urban-exploration site.', 'limited', 'https://www.atlasobscura.com/places/hearthstone-castle', 'https://tarrywile.com/', 'America/New_York', now()),
  ('Heublein Tower', 'heublein-tower', 'roadside-oddities', 41.8259, -72.7985, 'Avon', 'CT', 'A 165-foot hilltop tower rises above Talcott Mountain and looks more like a European country estate than a Connecticut observation structure. It can only be reached on foot, and the interior museum operates seasonally, but the tower and its setting make the hike worthwhile.', 'limited', 'https://www.atlasobscura.com/places/heublein-tower', 'https://friendsofheubleintower.org/', 'America/New_York', now()),
  ('Paul Bunyan Muffler Man', 'paul-bunyan-muffler-man-cheshire', 'roadside-oddities', 41.55781, -72.90662, 'Cheshire', 'CT', 'A 26-foot fiberglass Paul Bunyan towers over West Johnson Avenue. When local height rules complicated his oversized axe, it was replaced with an American flag, allowing the classic Muffler Man to remain one of Connecticut''s biggest roadside figures.', 'open', 'https://www.atlasobscura.com/places/paul-bunyan-muffler-man', null, 'America/New_York', now()),
  ('Big Bob — Cowboy Muffler Man', 'big-bob-cowboy-muffler-man', 'roadside-oddities', 41.52194, -72.0918, 'Norwich', 'CT', 'A giant cowboy Muffler Man has been part of Norwich since the 1960s and has watched over the West Main Street shopping area for decades. Big Bob wears a cowboy hat and holds an American flag, preserving a classic piece of fiberglass roadside culture.', 'open', 'https://www.roadsideamerica.com/tip/5908', 'https://surplusunlimitedoffice.com/', 'America/New_York', now()),
  ('The Dinosaur Place', 'the-dinosaur-place', 'roadside-oddities', 41.43198, -72.22254, 'Oakdale', 'CT', 'A wooded trail system is populated by dozens of life-size dinosaur models, including towering sauropods and animatronic creatures. The attraction is seasonal and ticketed, but its huge prehistoric figures make it one of Connecticut''s strongest intentionally weird roadside destinations.', 'limited', 'https://naturesartvillage.com/the-dinosaur-place/', 'https://naturesartvillage.com/', 'America/New_York', now()),
  ('Curioporium', 'curioporium', 'roadside-oddities', 41.60079, -72.88188, 'Southington', 'CT', 'A curiosity shop inside Factory Square filled with taxidermy, natural-history specimens, antiques, strange artwork, unusual collectibles and other objects selected for maximum oddity. It functions as both a shop and a cabinet-of-curiosities-style browsing stop.', 'open', 'https://www.atlasobscura.com/places/curioporium', 'https://www.curioporium.com/', 'America/New_York', now()),
  ('A. Everett Austin Facade House', 'a-everett-austin-facade-house', 'roadside-oddities', 41.78093, -72.70919, 'Hartford', 'CT', 'Museum director A. Everett ''Chick'' Austin designed this 1930s home to resemble a grand European villa, but much of the impressive facade conceals a house only one room deep. The theatrical architecture fits its famously eccentric former owner; interior access is by scheduled museum programming.', 'limited', 'https://www.atlasobscura.com/things-to-do/hartford-connecticut', 'https://www.thewadsworth.org/', 'America/New_York', now()),
  ('The Boat Building', 'the-boat-building', 'roadside-oddities', 41.76526, -72.67053, 'Hartford', 'CT', 'Hartford''s former Phoenix Mutual Life Insurance building curves into a long lens-like shape that resembles a boat or football from above. Its unusual geometry is often described as one of the earliest major two-sided office-building designs.', 'roadside', 'https://www.atlasobscura.com/places/the-boat-building', null, 'America/New_York', now()),
  ('Ingalls Rink — The Yale Whale', 'ingalls-rink-the-yale-whale', 'roadside-oddities', 41.31655, -72.92504, 'New Haven', 'CT', 'Eero Saarinen''s dramatic hockey arena is nicknamed the Yale Whale because its sweeping roof and curved concrete spine resemble a giant marine animal. It remains an active Yale athletic venue, so interior access depends on games and university events.', 'limited', 'https://www.atlasobscura.com/things-to-do/connecticut/architecture', 'https://yalebulldogs.com/facilities/david-s-ingalls-rink/8', 'America/New_York', now()),
  ('Gaylordsville Spite House', 'gaylordsville-spite-house', 'roadside-oddities', 41.6478, -73.4829, 'New Milford', 'CT', 'This extraordinarily narrow house was constructed in a form local history has long connected with a property dispute, earning it the label of a spite house. It is a private residence, so the stop is strictly an exterior view from lawful public space.', 'private', 'https://www.atlasobscura.com/places/gaylordsville-spite-house', null, 'America/New_York', now()),
  ('Talcott Basalt Lava Pillows', 'talcott-basalt-lava-pillows', 'roadside-oddities', 41.5532, -72.81591, 'Meriden', 'CT', 'An exposed rock face behind a shopping area preserves rounded basalt structures formed when ancient lava encountered water. The strange pillow-like shapes are remnants of volcanic activity roughly 200 million years old hiding in an otherwise ordinary commercial landscape.', 'open', 'https://www.atlasobscura.com/places/talcott-basalt-lava-pillows', null, 'America/New_York', now()),
  ('Monument to Miantonomo', 'monument-to-miantonomo', 'weird-history', 41.54892, -72.04978, 'Norwich', 'CT', 'A stone monument marks the area traditionally associated with the 1643 killing of Narragansett sachem Miantonomo after his capture during conflict with the Mohegan. The isolated marker preserves a grim episode from southern New England''s colonial and Indigenous history.', 'open', 'https://www.atlasobscura.com/places/monument-to-miantonomo', null, 'America/New_York', now()),
  ('Lock Museum of America', 'lock-museum-of-america', 'museums', 41.67915, -73.01242, 'Terryville', 'CT', 'Thousands of locks, keys, safes and lock-making tools fill a museum in a town once central to the American lock industry. Displays range from ancient locking concepts to an enormous cannonball safe, and the museum operates on a limited schedule.', 'limited', 'https://www.atlasobscura.com/places/lock-museum-of-america-connecticut', 'https://lockmuseumofamerica.org/', 'America/New_York', now()),
  ('Connecticut Trolley Museum', 'connecticut-trolley-museum', 'museums', 41.9314, -72.59472, 'East Windsor', 'CT', 'Historic streetcars and electric railway equipment are preserved on a working museum line where visitors can ride vintage trolleys. The collection is particularly atmospheric during its seasonal nighttime and Halloween programs.', 'limited', 'https://www.atlasobscura.com/places/connecticut-trolley-museum', 'https://www.ct-trolley.org/', 'America/New_York', now()),
  ('Great Scott Moon Rock', 'great-scott-moon-rock', 'roadside-oddities', 41.76469, -72.66945, 'Hartford', 'CT', 'The Connecticut Science Center displays a genuine lunar sample associated with Apollo astronaut David Scott. It is a small object with an enormous backstory: a physical piece of the Moon sitting in downtown Hartford.', 'open', 'https://www.atlasobscura.com/places/great-scott-moon-rock', 'https://ctsciencecenter.org/', 'America/New_York', now()),
  ('Haddam Shad Museum', 'haddam-shad-museum', 'museums', 41.50003, -72.5657, 'Haddam', 'CT', 'A tiny museum dedicated almost entirely to the Connecticut River''s historic shad-fishing industry preserves nets, tools, boats, photographs and wonderfully specific fish-related artifacts. It traditionally opens only during the spring shad season and by appointment.', 'limited', 'https://www.atlasobscura.com/places/haddam-shad-museum', null, 'America/New_York', now()),
  ('American Clock & Watch Museum', 'american-clock-watch-museum', 'museums', 41.67958, -72.94081, 'Bristol', 'CT', 'Hundreds of American clocks and watches trace Connecticut''s outsized role in mass-produced timekeeping. Rooms filled with ticking mechanisms, novelty clocks and elaborate cases make this specialized museum much stranger than its quiet historic-house exterior suggests.', 'open', 'https://www.atlasobscura.com/places/american-clock-and-watch-museum', 'https://www.clockandwatchmuseum.org/', 'America/New_York', now()),
  ('Vintage Radio and Communications Museum', 'vintage-radio-and-communications-museum', 'museums', 41.86314, -72.64052, 'Windsor', 'CT', 'A hands-on collection follows communications technology from telegraphy and crystal radios through broadcasting, television and early computers. Many displays still function, allowing visitors to operate equipment rather than simply look at it behind glass.', 'limited', 'https://www.atlasobscura.com/places/vintage-radio-and-communications-museum-of-connecticut', 'https://www.vrcmct.org/', 'America/New_York', now()),
  ('Colonial Tavern Sign Collection', 'colonial-tavern-sign-collection', 'museums', 41.77293, -72.70528, 'Hartford', 'CT', 'The Connecticut Museum of Culture and History holds an exceptional collection of early American tavern signs painted with animals, symbols, portraits and sometimes bizarre imagery meant to attract travelers who could not necessarily read. Display availability can rotate with exhibitions.', 'open', 'https://www.atlasobscura.com/places/the-largest-collection-of-colonial-american-tavern-signs', 'https://www.connecticutmuseum.org/', 'America/New_York', now()),
  ('Turtle Submarine Replica', 'turtle-submarine-replica', 'weird-history', 41.35133, -72.38645, 'Essex', 'CT', 'The Connecticut River Museum displays a full-size working reconstruction of the Turtle, the tiny one-man submersible built during the American Revolution for an attempted underwater attack on British warships. Its cramped wooden design looks more like a barrel than a modern submarine.', 'open', 'https://www.atlasobscura.com/places/turtle-submarine-at-connecticut-river-museum', 'https://ctrivermuseum.org/turtle-submarine/', 'America/New_York', now()),
  ('Danbury Railway Museum', 'danbury-railway-museum', 'museums', 41.39784, -73.45046, 'Danbury', 'CT', 'A former railroad station and yard preserve locomotives, rolling stock, a working turntable and other heavy railway equipment. The station also has a film connection: Danbury''s railroad facilities appeared in Alfred Hitchcock''s ''Strangers on a Train.''', 'limited', 'https://www.atlasobscura.com/things-to-do/danbury-connecticut', 'https://www.danburyrail.org/', 'America/New_York', now()),
  ('Pleasure Beach Ghost Town', 'pleasure-beach-ghost-town', 'weird-history', 41.15779, -73.16913, 'Bridgeport', 'CT', 'Once home to an amusement park, cottages and summer crowds, Pleasure Beach was largely abandoned after a bridge fire cut off road access in 1996. Nature has reclaimed much of the former community. The City of Bridgeport operates seasonal water-taxi access, including during the 2026 season.', 'limited', 'https://www.bridgeportct.gov/government/departments/parks-recreation/pleasure-beach', null, 'America/New_York', now()),
  ('Remington Shot Tower', 'remington-shot-tower', 'weird-history', 41.18826, -73.17462, 'Bridgeport', 'CT', 'A tall industrial tower survives within the abandoned Remington Arms complex, where molten lead was once dropped from above so it cooled into round shot while falling. The factory property is not an urban-exploration destination: view the tower only from lawful public areas.', 'roadside', 'https://www.atlasobscura.com/places/remington-shot-tower', null, 'America/New_York', now()),
  ('Grave of Charles Stratton — General Tom Thumb', 'grave-of-charles-stratton-general-tom-thumb', 'weird-history', 41.17658, -73.22089, 'Bridgeport', 'CT', 'Charles Sherwood Stratton, the internationally famous performer promoted by P.T. Barnum as General Tom Thumb, is buried in Mountain Grove Cemetery. A life-size statue of the diminutive entertainer stands atop his monument, making the grave immediately recognizable.', 'open', 'https://www.atlasobscura.com/places/grave-of-charles-stratton', null, 'America/New_York', now()),
  ('CVRATED by Ryan Matthew Cohn', 'cvrated-by-ryan-matthew-cohn', 'roadside-oddities', 41.18185, -73.16495, 'Bridgeport', 'CT', 'A new Bridgeport curiosity shop from oddities collector Ryan Matthew Cohn combines antique medical objects, taxidermy, natural-history pieces and unusual decorative material. It opened in 2026 and currently keeps limited public hours with additional visits available by arrangement.', 'limited', 'https://www.atlasobscura.com/places/cvrated-by-ryan-matthew-cohn', null, 'America/New_York', now()),
  ('Sergeant Stubby Statue', 'sergeant-stubby-statue', 'weird-history', 41.55968, -72.6703, 'Middletown', 'CT', 'A bronze monument honors Sergeant Stubby, the stray dog adopted by Connecticut soldiers who became one of World War I''s most famous military animals. Stubby reportedly warned troops of gas attacks, located wounded soldiers and served with the 102nd Infantry.', 'open', 'https://www.atlasobscura.com/places/sergeant-stubby-statue', null, 'America/New_York', now()),
  ('Hat Maker Statue', 'hat-maker-statue', 'weird-history', 41.39188, -73.45378, 'Danbury', 'CT', 'A bronze hatter commemorates the industry that once made Danbury one of America''s great hat-making centers. The cheerful-looking monument has a darker undertone: mercury used in felt production caused serious neurological illness among hat workers and helped popularize the phrase ''mad as a hatter.''', 'open', 'https://www.atlasobscura.com/places/hat-maker-statue', null, 'America/New_York', now()),
  ('Statue of Jack the Pardoned Turkey', 'statue-of-jack-the-pardoned-turkey', 'roadside-oddities', 41.78282, -72.6599, 'Hartford', 'CT', 'A bronze turkey commemorates Jack, a nineteenth-century bird linked to Abraham Lincoln and the story that helped inspire the presidential turkey-pardoning tradition. The oddly specific monument turns a bit of White House animal lore into a Hartford roadside stop.', 'open', 'https://www.atlasobscura.com/places/statue-of-jack-the-pardoned-turkey', null, 'America/New_York', now()),
  ('Hartford Circus Fire Memorial', 'hartford-circus-fire-memorial', 'weird-history', 41.79497, -72.67445, 'Hartford', 'CT', 'A memorial marks the location of the July 6, 1944 Ringling Bros. and Barnum & Bailey circus fire, one of the deadliest circus disasters in American history. The memorial stands near the former big-top site and preserves the names and memory of the victims.', 'open', 'https://www.atlasobscura.com/places/hartford-circus-fire-memorial', null, 'America/New_York', now()),
  ('Gunntown Cemetery', 'gunntown-cemetery', 'haunted', 41.49088, -73.10427, 'Naugatuck', 'CT', 'This small cemetery dates to around 1790 and is one of Connecticut''s better-known local haunting sites. Stories include a black ghost dog, a lantern-carrying man, a child near the back wall and unexplained music. Treat the reports as folklore and visit respectfully during permitted cemetery hours.', 'limited', 'https://www.hauntedplaces.org/item/gunntown-cemetery/', null, 'America/New_York', now()),
  ('Great Hill Cemetery — Hookman''s Cemetery', 'great-hill-cemetery-hookmans-cemetery', 'folklore', 41.38328, -73.11901, 'Seymour', 'CT', 'Great Hill Cemetery is better known in local ghost lore as Hookman''s Cemetery. The legend tells of a hook-handed caretaker whose spirit supposedly scraped the roofs of cars parked near a particular tree. The tale is folklore; the cemetery remains an active burial place and should be treated accordingly.', 'limited', 'https://www.hauntedplaces.org/item/great-hill-cemetery/', null, 'America/New_York', now()),
  ('Stepney Cemetery', 'stepney-cemetery', 'haunted', 41.32246, -73.2631, 'Monroe', 'CT', 'An old Monroe cemetery appears repeatedly in Connecticut ghost lore, particularly in stories connected with the region''s famous White Lady tradition. Ed and Lorraine Warren are also buried here. Visitors should observe posted hours and avoid nighttime investigation or disturbance.', 'limited', 'https://ctvisit.com/articles/haunted-cemeteries', null, 'America/New_York', now()),
  ('Union Cemetery — White Lady Legend', 'union-cemetery-white-lady-legend', 'haunted', 41.27277, -73.29698, 'Easton', 'CT', 'Union Cemetery is associated with one of Connecticut''s most famous apparitions, the White Lady, along with stories of glowing red eyes and other roadside encounters. The haunting claims remain folklore, and local authorities have long discouraged trespassing and after-hours ghost hunting.', 'limited', 'https://ctvisit.com/articles/haunted-cemeteries', null, 'America/New_York', now()),
  ('Sheffield Island Lighthouse', 'sheffield-island-lighthouse', 'haunted', 41.04882, -73.41912, 'Norwalk', 'CT', 'An 1868 lighthouse on Sheffield Island is reached by seasonal boat excursions from Norwalk. Along with its maritime history, the island carries stories of phantom music, unexplained cries and other keeper-era ghost activity, giving the ferry trip a strong OddWay angle.', 'limited', 'https://ctvisit.com/articles/haunted-lighthouses', 'https://www.seaport.org/', 'America/New_York', now()),
  ('Penfield Reef Lighthouse', 'penfield-reef-lighthouse', 'haunted', 41.1171, -73.2221, 'Fairfield', 'CT', 'This isolated lighthouse stands more than a mile offshore on a dangerous reef. Its best-known legend concerns keeper Frederick Jordan, who drowned in 1916 and was later said to return as a protective ghost. There is no casual public walk-up access; view it from shore or by boat.', 'roadside', 'https://ctvisit.com/articles/haunted-lighthouses', null, 'America/New_York', now()),
  ('New London Ledge Light — Ernie''s Lighthouse', 'new-london-ledge-light-ernies-lighthouse', 'haunted', 41.30589, -72.07743, 'Groton', 'CT', 'The unusual brick lighthouse at the mouth of the Thames River is famous for a resident ghost nicknamed Ernie, traditionally described as a former keeper. The New London Maritime Society owns the light, and public access is available on selected boat tours rather than by road.', 'limited', 'https://ctvisit.com/articles/haunted-lighthouses', 'https://lighthousefoundation.org/lighthouses/new-london-ledge-light/', 'America/New_York', now()),
  ('Captain Grant''s 1754', 'captain-grants-1754', 'haunted', 41.48579, -72.03961, 'Preston', 'CT', 'This operating eighteenth-century inn openly embraces its reputation as one of Connecticut''s haunted lodgings. Guests and investigators have reported apparitions, knocking, moving objects and activity associated with the Adelaide Room, while old cemeteries immediately around the property deepen the atmosphere.', 'limited', 'https://www.hauntedplaces.org/item/captain-grants-inn/', 'https://captaingrants.com/', 'America/New_York', now()),
  ('Captain Daniel Packer Inne', 'captain-daniel-packer-inne', 'haunted', 41.35093, -71.97213, 'Mystic', 'CT', 'A 1756 waterfront building now operates as a restaurant and pub while preserving centuries of Mystic history. Local haunting stories include a young girl on the staircase and other unexplained activity, making it an unusually easy paranormal stop where visitors can simply book a meal.', 'open', 'https://www.hauntedplaces.org/item/captain-daniel-packer-inne/', 'https://danielpacker.com/', 'America/New_York', now()),
  ('Frog Rock Roadside Park', 'frog-rock-roadside-park', 'roadside-oddities', 41.86899, -72.05202, 'Eastford', 'CT', 'A huge glacial boulder has been painted to resemble a frog since the nineteenth century. The surrounding roadside rest area has repeatedly faded, closed and revived over the years, but the green frog itself remains a beloved Route 44 landmark; services around it may be seasonal.', 'limited', 'https://www.roadsideamerica.com/tip/48905', null, 'America/New_York', now()),
  ('Space Shuttle Discovery Tire', 'space-shuttle-discovery-tire', 'roadside-oddities', 41.5257, -73.42602, 'New Milford', 'CT', 'A real tire flown aboard Space Shuttle Discovery is mounted outside the John J. McCarthy Observatory at New Milford High School. The tire touched down after traveling millions of miles in space, turning an otherwise disposable spacecraft component into a hands-on local artifact.', 'limited', 'https://www.roadsideamerica.com/story/72060', 'https://www.mccarthyobservatory.org/', 'America/New_York', now()),
  ('Easter Island Head with Topknot', 'easter-island-head-with-topknot', 'roadside-oddities', 41.55232, -73.03456, 'Waterbury', 'CT', 'A roughly 40-foot moai replica with a red topknot survives beside the former Timexpo Museum. The museum closed in 2015, but the enormous concrete head remains beside the shopping complex as a bizarre leftover from an attempt to connect Timex with explorer Thor Heyerdahl.', 'roadside', 'https://www.roadsideamerica.com/story/83637', null, 'America/New_York', now()),
  ('King Nyani — Giant Bronze Gorilla', 'king-nyani-giant-bronze-gorilla', 'roadside-oddities', 41.01986, -73.62293, 'Greenwich', 'CT', 'An enormous reclining bronze gorilla reaches an open hand toward visitors outside the Bruce Museum. Created by artists Gillie and Marc, King Nyani is intended as a gentle counterpoint to monster-movie gorillas and is currently listed by the museum as an ongoing installation.', 'open', 'https://brucemuseum.org/exhibitions/king-nyani/', 'https://brucemuseum.org/', 'America/New_York', now()),
  ('Shubert Theatre Ghost Stories', 'shubert-theatre-ghost-stories', 'haunted', 41.30653, -72.92906, 'New Haven', 'CT', 'The historic 1914 Shubert has hosted generations of performers and is included in Connecticut''s haunted-theater lore. Reports have included unexplained sounds and apparitions in the old venue. It remains an active theater, so the proper way to experience the building is through a performance, tour or authorized event.', 'limited', 'https://ctvisit.com/articles/connecticuts-haunted-history-trail', 'https://www.shubert.com/', 'America/New_York', now()),
  ('New Haven Green — Bodies Underfoot', 'new-haven-green-bodies-underfoot', 'weird-history', 41.3076, -72.92649, 'New Haven', 'CT', 'New Haven''s central Green looks like an ordinary civic park, but it served as the community burial ground for generations. Most old headstones were moved elsewhere while thousands of human remains were left underground; Hurricane Sandy famously exposed skeletal remains beneath a fallen tree in 2012.', 'open', 'https://thenewhavengreen.org/history/', null, 'America/New_York', now()),
  ('National Helicopter Museum', 'national-helicopter-museum', 'museums', 41.19474, -73.13048, 'Stratford', 'CT', 'A small museum inside Stratford''s railroad station explores the town''s central role in helicopter development, including Igor Sikorsky''s work. Exhibits include aircraft components, models, a Sikorsky cockpit and a helicopter flight simulator. The museum operates seasonally.', 'limited', 'https://nationalhelicoptermuseum.org/', 'https://nationalhelicoptermuseum.org/', 'America/New_York', now()),
  ('Tantaquidgeon Museum', 'tantaquidgeon-museum', 'museums', 41.4742, -72.0997, 'Uncasville', 'CT', 'Founded in 1931 by Mohegan medicine woman Gladys Tantaquidgeon with her father and brother, this is one of the oldest Native American-owned and-operated museums in the United States. Its collections and setting preserve Mohegan material culture from a community-controlled perspective.', 'limited', 'https://www.mohegan.nsn.us/explore/museum', 'https://www.mohegan.nsn.us/explore/museum', 'America/New_York', now()),
  ('Devil''s Hopyard State Park', 'devils-hopyard-state-park', 'folklore', 41.47621, -72.34119, 'East Haddam', 'CT', 'Chapman Falls tumbles over bedrock pocked with near-cylindrical holes. Early folklore claimed the Devil made those holes with his burning hooves after getting his tail wet, while geology explains them as potholes ground out by stones spinning in river eddies. The state park is open daily.', 'open', 'https://ctparks.com/parks/devils-hopyard-state-park', 'https://ctparks.com/parks/devils-hopyard-state-park', 'America/New_York', now()),
  ('1754 House — Former Curtis House Inn', '1754-house-former-curtis-house-inn', 'haunted', 41.53321, -73.20639, 'Woodbury', 'CT', 'Connecticut''s long-running Curtis House Inn now operates as the 1754 House, but its old ghost stories have not disappeared with the name change. Reports attached to the historic property include apparitions, footsteps, voices and unexplained music. It remains an active inn and restaurant rather than an abandoned location.', 'open', 'https://www.hauntedplaces.org/item/curtis-house-restaurant-and-inn/', 'https://1754house.com/', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;

select count(*) as connecticut from public.stops where state = 'CT';
