-- Delaware, both batches. The state had nothing at all before this.
--
-- Two things needed fixing before these could go in.
--
-- Names arrived numbered — "1. The Oddporium" through "80. Clifford Brown
-- Listening Garden". That is a position in a research list rather than part of
-- a name, and left alone it would have appeared on every card and in every URL.
--
-- Ten categories sat outside the enum. All were reasonable descriptions the
-- schema does not have, and each was mapped by looking at the stop rather than
-- the word: 'ruins' is an abandoned amusement park, so weird history;
-- 'transportation' is a heritage railroad, so a museum; 'dark-rides' is
-- Funland's haunted mansion, so haunted.
--
-- The eleven proximity flags between the two batches are all Lewes and Dover,
-- where a dozen listed buildings share three streets. Different buildings.
--
-- 80 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('The Oddporium', 'the-oddporium', 'museums', 39.81296, -75.49281, 'Arden', 'DE', 'Part oddities shop and part cabinet-of-curiosities museum, the Oddporium fills a 1911 building with antique medical equipment, funerary objects, taxidermy, preserved specimens, strange art and other deliberately bizarre finds. The owners also lean into the building''s paranormal lore, making this one of Delaware''s strongest pure OddWay stops.', 'open', 'https://www.roadsideamerica.com/story/62307', 'https://oddporium.com/', 'America/New_York', now()),
  ('Chief Little Owl', 'chief-little-owl', 'roadside-oddities', 38.53823, -75.05896, 'Bethany Beach', 'DE', 'A 24-foot red-cedar head of Nanticoke Chief Little Owl stands in the highway median greeting visitors to Bethany Beach. It is the third version of the town''s Peter "Wolf" Toth Whispering Giant after earlier carvings were lost to a storm and decay.', 'roadside', 'https://www.roadsideamerica.com/tip/50775', null, 'America/New_York', now()),
  ('Bob the Bull', 'bob-the-bull', 'roadside-oddities', 38.54042, -75.22007, 'Dagsboro', 'DE', 'This enormous fiberglass bull spent decades outside an Ocean City steakhouse before being rescued, restored and moved to Parsons Farms in Delaware. Bob still wears his oversized chef hat and sunglasses, preserving one of Delmarva''s classic roadside mascots.', 'open', 'https://www.roadsideamerica.com/story/21619', 'https://parsonsfarmsproduce.com/', 'America/New_York', now()),
  ('Big Crab at Old Mill Crab House', 'big-crab-at-old-mill-crab-house', 'roadside-oddities', 38.45645, -75.58417, 'Delmar', 'DE', 'A giant red crab hangs above the ground outside the Old Mill Crab House, claws dangling over the photo spot below. It sits only about a hundred feet north of the Maryland line and has become a long-running Delmar roadside landmark.', 'roadside', 'https://www.roadsideamerica.com/tip/50755', null, 'America/New_York', now()),
  ('Miles the Monster', 'miles-the-monster', 'roadside-oddities', 39.18839, -75.52692, 'Dover', 'DE', 'Dover Motor Speedway''s enormous concrete mascot erupts from the ground clutching a full-size race car in one hand. The snarling figure is one of Delaware''s largest and most recognizable roadside monsters.', 'open', 'https://www.atlasobscura.com/places/miles-the-monster', 'https://www.dovermotorspeedway.com/', 'America/New_York', now()),
  ('Air Mobility Command Museum', 'air-mobility-command-museum', 'museums', 39.11869, -75.45664, 'Dover', 'DE', 'A free aviation museum housed in a restored World War II hangar that was once used for secret rocket development. More than 35 aircraft and unusual airlift artifacts fill the hangar and outdoor airpark, with some aircraft opened for visitor access on selected days.', 'open', 'https://www.amcmuseum.org/visit/', 'https://www.amcmuseum.org/', 'America/New_York', now()),
  ('Cateraptasaurus', 'cateraptasaurus', 'roadside-oddities', 38.9832, -75.56874, 'Felton', 'DE', 'A mechanical dinosaur assembled from Caterpillar equipment parts has been associated with the Carter Machinery property in Felton. Recent reports indicate the sculpture may travel to events rather than remaining permanently planted, so this pin should be treated as a call-ahead stop.', 'limited', 'https://www.roadsideamerica.com/tip/45297', 'https://www.cartermachinery.com/', 'America/New_York', now()),
  ('DiscoverSea Shipwreck Museum', 'discoversea-shipwreck-museum', 'museums', 38.4573, -75.0526, 'Fenwick Island', 'DE', 'An unusually dense private collection of shipwreck treasure and maritime artifacts, with roughly 10,000 objects displayed at a time. Alongside coins, weapons and recovered cargo are stranger pieces that have included a Fiji-style merman and other natural-history curiosities.', 'limited', 'https://www.discoversea.com/', 'https://www.discoversea.com/', 'America/New_York', now()),
  ('Viking Golf — Trolls and Two-Headed Dragon', 'viking-golf-trolls-and-two-headed-dragon', 'roadside-oddities', 38.45262, -75.05367, 'Fenwick Island', 'DE', 'A Viking-themed miniature-golf course populated by oversized Norse figures, trolls and a large two-headed dragon. It is a commercial attraction rather than folklore history, but the sculptural theming makes it a strong visual OddWay stop during its operating season.', 'limited', 'https://www.roadsideamerica.com/tip/50777', 'https://www.fenwickfun.com/', 'America/New_York', now()),
  ('World''s Largest Frying Pan', 'worlds-largest-frying-pan', 'roadside-oddities', 38.67251, -75.37705, 'Georgetown', 'DE', 'A gigantic frying pan, about ten feet across and roughly eighteen feet long including its handle, is displayed at the Marvel Carriage Museum. It was built for a chicken-frying event and fits neatly with Sussex County''s poultry history.', 'limited', 'https://www.roadsideamerica.com/story/13356', 'https://www.georgetownhistoricalsociety.org/', 'America/New_York', now()),
  ('25-Foot Hanuman Statue', '25-foot-hanuman-statue', 'roadside-oddities', 39.79063, -75.68812, 'Hockessin', 'DE', 'A monumental statue of the Hindu deity Hanuman rises over the grounds of the Hindu Temple of Delaware. The roughly 25-foot figure is an unexpected landmark in northern Delaware and is visible as part of the active temple complex.', 'open', 'https://www.roadsideamerica.com/story/74093', 'https://www.hindutemplede.com/', 'America/New_York', now()),
  ('Lewes Fountain of Youth', 'lewes-fountain-of-youth', 'folklore', 38.7815, -75.15342, 'Lewes', 'DE', 'A small stone well marks a spring that local tradition connected to a 1631 Dutch expedition and later dubbed the Fountain of Youth. The legend is the attraction here, not the water: modern visitors should treat the spring as a historic curiosity rather than a drinking source.', 'open', 'https://www.roadsideamerica.com/location/de', null, 'America/New_York', now()),
  ('Lightship Overfalls', 'lightship-overfalls', 'museums', 38.77801, -75.14114, 'Lewes', 'DE', 'A preserved lightship — essentially a floating lighthouse — sits permanently moored in Lewes. The ship can be toured seasonally, while the surrounding park also includes an enormous fishing-bobber sculpture.', 'limited', 'https://www.roadsideamerica.com/tip/7280', 'https://www.overfalls.org/', 'America/New_York', now()),
  ('Cannonball House', 'cannonball-house', 'weird-history', 38.77593, -75.13939, 'Lewes', 'DE', 'This historic house still carries physical evidence of the British bombardment of Lewes in April 1813. A cannonball associated with the attack is preserved inside, turning a quiet house museum into one of Delaware''s clearest pieces of visible War of 1812 damage.', 'limited', 'https://www.atlasobscura.com/places/the-cannonball-house', 'https://www.historiclewes.org/', 'America/New_York', now()),
  ('Yogi Bear and Jellystone Characters', 'yogi-bear-and-jellystone-characters', 'roadside-oddities', 38.87437, -75.36025, 'Lincoln', 'DE', 'A cluster of restored vintage Yogi Bear/Jellystone character figures survives at the campground on Brick Granary Road. The figures preserve the look of mid-century family roadside attractions, but they sit on active campground property.', 'limited', 'https://www.roadsideamerica.com/tip/71127', null, 'America/New_York', now()),
  ('Big Amish Man Statue', 'big-amish-man-statue', 'roadside-oddities', 38.96054, -75.42883, 'Milford', 'DE', 'A roughly 20-foot fiberglass Amish man stands outside Xtreme Graphix after changing homes more than once over the years. The towering bearded figure is a classic Muffler-Man-era roadside sculpture with distinctly Delmarva styling.', 'roadside', 'https://www.roadsideamerica.com/tip/1613', null, 'America/New_York', now()),
  ('USS Shangri-La Propeller', 'uss-shangri-la-propeller', 'weird-history', 38.9887, -75.44655, 'Milford', 'DE', 'An enormous propeller from the aircraft carrier USS Shangri-La sits beside Bay Road as a piece of naval hardware turned roadside monument. The scale is difficult to appreciate until standing beside it.', 'roadside', 'https://www.roadsideamerica.com/story/19107', null, 'America/New_York', now()),
  ('Tiki Murph — Highway Tikis', 'tiki-murph-highway-tikis', 'roadside-oddities', 38.96761, -75.43227, 'Milford', 'DE', 'A roadside yard filled with large hand-carved tiki figures, including pieces made from logs with exaggerated faces and personalities. The attraction operates seasonally, making it a better planned stop than a year-round guaranteed sight.', 'limited', 'https://www.roadsideamerica.com/tip/70210', 'https://tikimurph.com/', 'America/New_York', now()),
  ('Metal T-Rex and TV Characters', 'metal-t-rex-and-tv-characters', 'roadside-oddities', 38.62122, -75.198, 'Millsboro', 'DE', 'A homemade roadside menagerie led by a large scrap-metal Tyrannosaurus rex, accompanied by pop-culture and television-inspired figures. Recent traveler reports still place the sculptures along DE-24 east of Millsboro.', 'roadside', 'https://www.roadsideamerica.com/location/de', null, 'America/New_York', now()),
  ('Futuro House — Eagle Crest Airport', 'futuro-house-eagle-crest-airport', 'roadside-oddities', 38.7734, -75.22844, 'Milton', 'DE', 'A rare 1960s Futuro House sits at the edge of the small Eagle Crest-Hudson Airport looking like a landed flying saucer. The fiberglass pod is architecture, not a UFO claim, and is on private property, so it should only be viewed from lawful public areas.', 'private', 'https://www.roadsideamerica.com/location/de', null, 'America/New_York', now()),
  ('Vincelette Futuro House', 'vincelette-futuro-house', 'roadside-oddities', 38.92018, -75.51445, 'Houston', 'DE', 'Another surviving Futuro House — one of the distinctive prefabricated flying-saucer homes designed in the late 1960s — stands on Deep Grass Lane. It is a private residence and should be treated strictly as a public-road viewing stop.', 'private', 'https://npgallery.nps.gov/AssetDetail/NRIS/100006880', null, 'America/New_York', now()),
  ('Steampunk Tree House', 'steampunk-tree-house', 'roadside-oddities', 38.77024, -75.31092, 'Milton', 'DE', 'A 40-foot steel tree built from recycled industrial material rises at Dogfish Head''s Milton brewery. Originally created as a Burning Man art installation, the sculpture later became a private employee drinkhaus and can be seen during eligible brewery visits or tours.', 'limited', 'https://www.atlasobscura.com/places/steampunk-tree-house', 'https://www.dogfish.com/', 'America/New_York', now()),
  ('34-Foot Stainless Steel Mary', '34-foot-stainless-steel-mary', 'roadside-oddities', 39.69845, -75.5552, 'New Castle', 'DE', 'A towering stainless-steel statue of Mary rises beside Holy Spirit Catholic Church near the Delaware Memorial Bridge. At roughly 34 feet tall, the polished figure is one of the state''s most conspicuous religious roadside landmarks.', 'open', 'https://www.roadsideamerica.com/location/de', null, 'America/New_York', now()),
  ('Huge Doctor''s Bag with Stethoscope', 'huge-doctors-bag-with-stethoscope', 'roadside-oddities', 39.69843, -75.65197, 'Newark', 'DE', 'An oversized doctor''s bag and stethoscope form the sign/sculpture outside a medical-office property near Christiana. It is exactly the kind of giant-object roadside landmark OddWay is built to surface.', 'roadside', 'https://www.roadsideamerica.com/tip/18430', null, 'America/New_York', now()),
  ('Shark in a Box', 'shark-in-a-box', 'roadside-oddities', 39.45713, -75.657, 'Odessa', 'DE', 'A life-size fiberglass replica of Delaware''s record 840-pound mako shark hangs inside a glass-sided roadside box outside Captain Bones. After a vehicle destroyed the display in 2022, locals repaired it and returned the shark to its longtime spot.', 'open', 'https://www.roadsideamerica.com/story/68689', 'https://www.captainbones.net/', 'America/New_York', now()),
  ('Independence Hall Replica', 'independence-hall-replica', 'roadside-oddities', 39.78078, -75.5441, 'Wilmington', 'DE', 'A scaled replica of Philadelphia''s Independence Hall sits unexpectedly along Concord Pike. The miniature landmark is easy to overlook from the road, which is exactly what makes it useful as a quick OddWay detour.', 'roadside', 'https://www.roadsideamerica.com/location/de', null, 'America/New_York', now()),
  ('Ebright Azimuth — Delaware High Point Marker', 'ebright-azimuth-delaware-high-point-marker', 'weird-history', 39.8358, -75.5192, 'Wilmington', 'DE', 'Delaware''s famously modest high point is commemorated by the Ebright Azimuth benchmark near the Pennsylvania line. The marker is commonly treated as the state''s high-point stop even though the absolute highest ground is slightly offset nearby.', 'roadside', 'https://www.roadsideamerica.com/location/de', null, 'America/New_York', now()),
  ('William McKinley Coffee Break Monument', 'william-mckinley-coffee-break-monument', 'weird-history', 39.75102, -75.54791, 'Wilmington', 'DE', 'A monument in Brandywine Park remembers teenage William McKinley serving coffee to Union soldiers under fire during the Battle of Antietam. It is an unusually specific presidential memorial — less about office and more about a battlefield coffee run.', 'open', 'https://www.roadsideamerica.com/location/de', null, 'America/New_York', now()),
  ('The Crying Giant', 'the-crying-giant', 'roadside-oddities', 39.76537, -75.56518, 'Wilmington', 'DE', 'Tom Otterness''s ten-foot bronze figure sits hunched and weeping in the Delaware Art Museum''s sculpture garden. The strange oversized form was created as a maquette related to a proposed 9/11 memorial.', 'open', 'https://www.atlasobscura.com/places/the-crying-giant', 'https://delart.org/', 'America/New_York', now()),
  ('Marian Coffin Garden', 'marian-coffin-garden', 'weird-history', 39.76083, -75.57424, 'Wilmington', 'DE', 'Formal gardens designed by pioneering landscape architect Marian Cruger Coffin surround the abandoned Gibraltar mansion behind a stone wall in Wilmington. The contrast between carefully restored grounds and the long-neglected mansion gives the site an unusually eerie atmosphere.', 'open', 'https://www.atlasobscura.com/places/marian-coffin-garden', null, 'America/New_York', now()),
  ('Rothschild Patent Model Collection', 'rothschild-patent-model-collection', 'museums', 39.78594, -75.58056, 'Wilmington', 'DE', 'Hagley preserves nearly 5,000 nineteenth-century patent models — tiny working proofs once required with U.S. patent applications. About 100 are displayed in the library, creating a room full of miniature Victorian inventions, mechanisms and forgotten ideas.', 'limited', 'https://www.hagley.org/patentmodels', 'https://www.hagley.org/', 'America/New_York', now()),
  ('Corbit-Sharp House Hidden Cubbyhole', 'corbit-sharp-house-hidden-cubbyhole', 'weird-history', 39.45383, -75.65714, 'Odessa', 'DE', 'The Corbit-Sharp House contains a concealed space associated with Underground Railroad history, hidden within an already unusual eighteenth-century home. Tours provide the context needed to understand the small secret compartment and the house''s role in Odessa''s history.', 'limited', 'https://www.atlasobscura.com/places/corbit-sharp-house', 'https://historicodessa.org/', 'America/New_York', now()),
  ('Packet Alley', 'packet-alley', 'weird-history', 39.65906, -75.5619, 'New Castle', 'DE', 'This narrow passage to the Delaware River recalls the packet boats, stagecoaches and early railroad connections that once converged in New Castle. The small alley marks a surprisingly important transportation link between water and land travel.', 'open', 'https://archives.delaware.gov/delaware-historical-markers/', null, 'America/New_York', now()),
  ('Site of Tilly''s Escape', 'site-of-tillys-escape', 'weird-history', 38.64181, -75.60931, 'Seaford', 'DE', 'A marker and public site commemorate Harriet Tubman''s 1856 effort to guide an enslaved woman known as Tilly through the Seaford area toward freedom. It is a precise physical stop tied to one of Tubman''s documented rescue missions.', 'open', 'https://archives.delaware.gov/delaware-historical-markers/', null, 'America/New_York', now()),
  ('Hardscrabble Historical Marker', 'hardscrabble-historical-marker', 'folklore', 38.61954, -75.48352, 'Seaford', 'DE', 'The marker preserves the local story behind the community name Hardscrabble. The colorful origin tale belongs more to local folklore than fully proven history, which is why it works better as an OddWay story stop than as a conventional historic landmark.', 'roadside', 'https://archives.delaware.gov/delaware-historical-markers/', null, 'America/New_York', now()),
  ('Golden Fleece Tavern Site', 'golden-fleece-tavern-site', 'weird-history', 39.15678, -75.52381, 'Dover', 'DE', 'Delaware delegates gathered at the Golden Fleece Tavern in 1787 around the time the state became the first to ratify the U.S. Constitution. The tavern itself is gone, but a surviving wall and marker preserve the unexpectedly ordinary setting of a major national event.', 'roadside', 'https://www.atlasobscura.com/places/golden-fleece-tavern', null, 'America/New_York', now()),
  ('Transpeninsular Line Marker', 'transpeninsular-line-marker', 'weird-history', 38.45125, -75.05478, 'Fenwick Island', 'DE', 'An eighteenth-century boundary marker records the survey line drawn across the Delmarva Peninsula before the better-known Mason-Dixon survey. It is a small stone remnant of the complicated colonial boundary dispute that shaped Delaware and Maryland.', 'roadside', 'https://archives.delaware.gov/delaware-historical-markers/', null, 'America/New_York', now()),
  ('Ryves Holt House', 'ryves-holt-house', 'weird-history', 38.77584, -75.14108, 'Lewes', 'DE', 'Often promoted as one of Delaware''s oldest surviving houses, the Ryves Holt House has traditionally been dated to 1665. Recent archival work has questioned that exact date, which makes the building an interesting stop not only for its age but for the evolving detective work around its history.', 'limited', 'https://www.historiclewes.org/', 'https://www.historiclewes.org/', 'America/New_York', now()),
  ('Menhaden Fishing Net Reel', 'menhaden-fishing-net-reel', 'weird-history', 38.77631, -75.14331, 'Lewes', 'DE', 'A huge industrial reel once used for the menhaden fishing industry sits on the Lewes Historical Society grounds. The machine-like spool is a tangible remnant of the massive nets and processing operations that once defined part of the town''s waterfront economy.', 'open', 'https://archives.delaware.gov/delaware-historical-markers/', 'https://www.historiclewes.org/', 'America/New_York', now()),
  ('Highball Signal', 'highball-signal', 'weird-history', 38.45648, -75.57796, 'Delmar', 'DE', 'A rare old-style railroad ball signal survives in Delmar''s Railroad Park. The device used a raised or lowered ball to communicate train movement and is an unusual piece of pre-electric railroad signaling technology.', 'open', 'https://www.atlasobscura.com/things-to-do/delaware/places', null, 'America/New_York', now()),
  ('New Castle-Frenchtown Railroad Ticket Office', 'new-castle-frenchtown-railroad-ticket-office', 'weird-history', 39.65781, -75.56219, 'New Castle', 'DE', 'A tiny surviving ticket office recalls the New Castle and Frenchtown Railroad, one of the earliest rail lines in the United States. The miniature building is fenced from entry but can be viewed as an exceptionally small remnant of early American rail travel.', 'open', 'https://www.atlasobscura.com/things-to-do/delaware/places', null, 'America/New_York', now()),
  ('Birthplace of the Commercial Broiler Industry', 'birthplace-of-the-commercial-broiler-industry', 'weird-history', 38.54802, -75.08908, 'Ocean View', 'DE', 'A marker in Ocean View commemorates Cecile Steele''s accidental 1923 order of 500 chicks, an event credited with helping launch the modern commercial broiler-chicken industry. A mundane shipping mistake became an agricultural turning point.', 'open', 'https://archives.delaware.gov/delaware-historical-markers/', null, 'America/New_York', now()),
  ('Steam Locomotive and Old Railway Cars', 'steam-locomotive-and-old-railway-cars', 'roadside-oddities', 38.54372, -75.08595, 'Ocean View', 'DE', 'A vintage steam locomotive and old passenger cars remain beside the former train-themed restaurant property in Ocean View. The equipment is fenced, but the preserved train makes an easy roadside visual stop.', 'roadside', 'https://www.roadsideamerica.com/location/de', null, 'America/New_York', now()),
  ('Zwaanendael Museum Merman', 'zwaanendael-museum-merman', 'museums', 38.77407, -75.13919, 'Lewes', 'DE', 'Inside Delaware''s Dutch-style Zwaanendael Museum is a classic Fiji-style merman — a grotesque composite curiosity made from animal parts — displayed alongside maritime and shipwreck history. It is one of the state''s strongest museum oddities.', 'open', 'https://www.atlasobscura.com/places/zwaanendael-museum', 'https://history.delaware.gov/zwaanendael-museum/', 'America/New_York', now()),
  ('Fort Delaware', 'fort-delaware', 'haunted', 39.58944, -75.56741, 'Delaware City', 'DE', 'The massive Civil War-era fortress on Pea Patch Island served as a prison for Confederate soldiers and is one of Delaware''s best-known haunted locations. State sources and the site''s own programming openly document its ghost lore and paranormal-tour reputation; access requires the seasonal ferry.', 'limited', 'https://dnrec.delaware.gov/outdoor-delaware/unveiling-delawares-dark-secrets-exploring-the-haunted-fort-delaware-and-beyond/', 'https://destateparks.com/FortDelaware', 'America/New_York', now()),
  ('Fort Miles Bunkers — Battery 118', 'fort-miles-bunkers-battery-118', 'weird-history', 38.77057, -75.08614, 'Lewes', 'DE', 'Concrete coastal-defense bunkers hide beneath the dunes of Cape Henlopen, remnants of the wartime Fort Miles complex built to protect Delaware Bay. Battery 118 is one of the most substantial surviving structures and anchors the fort''s museum and tour area.', 'limited', 'https://www.atlasobscura.com/places/bunkers-of-cape-henlopen-state-park', 'https://www.destateparks.com/fortmiles', 'America/New_York', now()),
  ('Woodburn — The Governor''s Haunted House', 'woodburn-the-governors-haunted-house', 'haunted', 39.16097, -75.52378, 'Dover', 'DE', 'Delaware''s governor''s residence carries one of the state''s oldest official ghost stories: the so-called "tippling ghost," said to help itself to guests'' drinks. The Delaware Public Archives preserves the legend but explicitly does not authenticate paranormal claims; public access is limited to scheduled events.', 'limited', 'https://archives.delaware.gov/2010/03/17/haunted-delaware/', 'https://governor.delaware.gov/woodburn/', 'America/New_York', now()),
  ('Cooch''s Bridge Historic Site', 'coochs-bridge-historic-site', 'haunted', 39.64017, -75.7374, 'Newark', 'DE', 'The only Revolutionary War battle fought in Delaware took place around Cooch''s Bridge. State folklore sources also preserve the story of a headless soldier said to haunt the area after being decapitated by a cannonball; the historical site itself has controlled visitor access.', 'limited', 'https://dnrec.delaware.gov/outdoor-delaware/unveiling-delawares-dark-secrets-exploring-the-haunted-fort-delaware-and-beyond/', 'https://history.delaware.gov/coochs-bridge-historic-site/', 'America/New_York', now()),
  ('Rockwood Park & Museum', 'rockwood-park-museum', 'haunted', 39.77311, -75.52077, 'Wilmington', 'DE', 'This Victorian estate is unusual for openly embracing its reported hauntings through county-run Ghost Walks and guided paranormal investigations using investigative equipment. As of September 2026, the mansion galleries are also undergoing accessibility work, so regular indoor access is more limited than usual.', 'limited', 'https://www.newcastlede.gov/431/Rockwood-Park-Museum', 'https://www.newcastlede.gov/431/Rockwood-Park-Museum', 'America/New_York', now()),
  ('Maggie''s Bridge', 'maggies-bridge', 'folklore', 38.59391, -75.66612, 'Seaford', 'DE', 'Woodland Church Road''s small bridge is the center of one of Delaware''s best-known local ghost legends. Versions vary, but the ritual usually involves calling out to "Maggie" and claiming to have her baby; it should be treated strictly as roadside folklore, with no stopping in traffic or trespassing.', 'roadside', 'https://www.onlyinyourstate.com/delaware/maggies-bridge-de', null, 'America/New_York', now()),
  ('Catman’s Grave — Long Cemetery', 'catmans-grave-long-cemetery', 'folklore', 38.50966, -75.24516, 'Frankford', 'DE', 'Long Cemetery is tied to the Delaware legend of Catman, a former cemetery caretaker said to keep watch over the grounds after death. Versions of the ritual involve knocking three times and later having car trouble, but these are local ghost stories rather than verified events, and some older descriptions no longer match what visitors report at the site. Treat it as a cemetery first: visit only when permitted and do not disturb graves or structures.', 'limited', 'https://www.hauntedplaces.org/item/long-cemetery-catmans-grave/', null, 'America/New_York', now()),
  ('Great Cypress Swamp — Selbyville Swamp Monster', 'great-cypress-swamp-selbyville-swamp-monster', 'cryptids', 38.47825, -75.31934, 'Frankford', 'DE', 'Delaware’s huge Great Cypress Swamp accumulated monster stories long before the best-known 1960s sightings. The famous Selbyville Swamp Monster episode was ultimately a hoax involving local man Fred Stevens in a fur-covered costume, but it became a genuine piece of Delaware cryptid folklore. The swamp is conservation land, so interior access should be limited to authorized programs and public areas.', 'limited', 'https://whyy.org/articles/the-spooky-scam-that-haunted-southern-delaware/', 'https://dewildlands.org/our-work/great-cypress-swamp/', 'America/New_York', now()),
  ('Cape Henlopen Corpse Light', 'cape-henlopen-corpse-light', 'folklore', 38.79536, -75.09189, 'Lewes', 'DE', 'Delaware folklore describes a mysterious offshore beam known as the Corpse Light, appearing near Cape Henlopen where no working lighthouse should be seen. State sources preserve the ghost story as part of Delaware’s maritime folklore. This pin uses the public Cape Henlopen Point area as the safest place to connect with the legend.', 'open', 'https://gic.delaware.gov/lighthouse-ghost-stories/', 'https://destateparks.com/CapeHenlopen', 'America/New_York', now()),
  ('Funland Haunted Mansion', 'funland-haunted-mansion', 'haunted', 38.71447, -75.07629, 'Rehoboth Beach', 'DE', 'Funland’s Haunted Mansion is a classic boardwalk dark ride known for its unusual hanging ride vehicles and generations of handmade scares. The original version is in its final operating season in 2026, with the attraction scheduled to close for 2027 while a reimagined Haunted Mansion is developed for a planned 2028 debut. Check current operating dates before routing travelers here.', 'limited', 'https://funlandrehoboth.com/mansion-updates', 'https://funlandrehoboth.com/', 'America/New_York', now()),
  ('Brandywine Springs Amusement Park Ruins', 'brandywine-springs-amusement-park-ruins', 'weird-history', 39.74868, -75.64453, 'Wilmington', 'DE', 'Brandywine Springs was once a major amusement park filled with rides, pavilions and attractions before closing in the 1920s. Archaeological work has uncovered foundations and other remains throughout today’s county park, where interpretive markers reveal traces of the vanished amusement grounds beneath the woods.', 'open', 'https://www.delawarepublic.org/culture-lifestyle-sports/2016-10-28/history-matters-unearthing-brandywine-springs-historic-amusement-park', 'https://www.ecodelaware.com/place.php?id=334', 'America/New_York', now()),
  ('Lums Pond Ghost Legends', 'lums-pond-ghost-legends', 'haunted', 39.57315, -75.70625, 'Bear', 'DE', 'Lums Pond State Park carries several long-running ghost stories, including tales connected to John Lum and another restless spirit said to haunt the area. Delaware’s own environmental agency includes the park among the state’s haunted places, while treating the stories as folklore rather than established fact.', 'open', 'https://dnrec.delaware.gov/outdoor-delaware/unveiling-delawares-dark-secrets-exploring-the-haunted-fort-delaware-and-beyond/', 'https://destateparks.com/LumsPond', 'America/New_York', now()),
  ('Bellevue Hall Ghost Stories', 'bellevue-hall-ghost-stories', 'haunted', 39.77567, -75.495, 'Wilmington', 'DE', 'Bellevue Hall, the mansion at Bellevue State Park, has accumulated stories of unexplained shrieks, moved furniture and electrical disturbances attributed to resident ghosts. Delaware state sources preserve those claims as part of local paranormal lore. The park grounds are public, while mansion access depends on current programming and events.', 'limited', 'https://dnrec.delaware.gov/outdoor-delaware/unveiling-delawares-dark-secrets-exploring-the-haunted-fort-delaware-and-beyond/', 'https://destateparks.com/Bellevue', 'America/New_York', now()),
  ('Addy Sea Inn Ghost Stories', 'addy-sea-inn-ghost-stories', 'haunted', 38.54358, -75.0573, 'Bethany Beach', 'DE', 'The historic Addy Sea appears in Delaware haunted-history material and has accumulated room-specific ghost stories involving a shaking bathtub, phantom organ music and a handyman spirit. Independent evidence for the experiences is thin, so the stories are best presented as inn folklore rather than authenticated paranormal events. It remains an operating lodging property.', 'limited', 'https://www.hauntedplaces.org/item/addy-sea-inn/', 'https://addysea.com/', 'America/New_York', now()),
  ('Airport Road Weeping Bride', 'airport-road-weeping-bride', 'folklore', 38.62485, -75.57055, 'Seaford', 'DE', 'A Seaford-area ghost story tells of a weeping bride and a Confederate soldier appearing along Airport Road, with some versions placing the encounter around Valentine’s Day. The tale is unverified local folklore and the road remains active, so travelers should never stop in traffic or enter private property while looking for the location.', 'roadside', 'https://www.hauntedplaces.org/item/airport-road/', null, 'America/New_York', now()),
  ('Black Diamond Road Ghost Lights', 'black-diamond-road-ghost-lights', 'folklore', 39.34734, -75.62159, 'Smyrna', 'DE', 'Black Diamond Road has a local reputation for unexplained glowing lights and floating orbs after dark. One version of the legend attempts to connect them with a supposed old burial ground, but that explanation is not established fact. This is a public-road folklore pin only; do not enter neighboring private property.', 'roadside', 'https://www.hauntedplaces.org/item/black-diamond-road/', null, 'America/New_York', now()),
  ('Redden State Forest Ranger House', 'redden-state-forest-ranger-house', 'haunted', 38.74111, -75.41056, 'Georgetown', 'DE', 'The historic Redden Forest complex includes an early-1900s lodge and ranger or forester’s house that originated with a Pennsylvania Railroad hunting retreat. Local ghost lore says a woman still haunts the old house. The surrounding state forest has public recreation areas, but access to historic buildings is more restricted.', 'limited', 'https://www.mlski.net/HOLIDAYS/hal3.html', 'https://agriculture.delaware.gov/forest-service/state-forests/', 'America/New_York', now()),
  ('Bonwell House — Fence-Rail Dog Legend', 'bonwell-house-fence-rail-dog-legend', 'folklore', 39.02306, -75.50944, 'Frederica', 'DE', 'The National Register documentation for the Bonwell House records a curious local legend about a huge red-eyed canine apparition called the Fence-Rail Dog because it was supposedly as long as a fence rail. The supernatural story is folklore, but its appearance in the historic documentation makes this an unusually well-preserved Delaware legend. The house is private property and should only be viewed from lawful public areas.', 'private', 'https://npgallery.nps.gov/GetAsset/d7b631ae-a119-4699-9d9e-fa31f1ffdd7e', null, 'America/New_York', now()),
  ('Mordington — Tom’s Daughter Ghost Legend', 'mordington-toms-daughter-ghost-legend', 'folklore', 38.96861, -75.49417, 'Frederica', 'DE', 'Mordington is tied to a grim local story about an enslaved girl remembered in folklore as Tom’s daughter, whose spirit was later said to haunt the property. Delaware archival materials preserve the story as part of the site’s local tradition. The historic house is private, so OddWay routing should keep visitors to public roads only.', 'private', 'https://archivesfiles.delaware.gov/markers/pdfs/kc-114-09.pdf', null, 'America/New_York', now()),
  ('Frightland and Idalia Manor', 'frightland-and-idalia-manor', 'haunted', 39.54021, -75.64695, 'Middletown', 'DE', 'Frightland surrounds the historic Idalia Manor with a large seasonal haunted-attraction complex containing multiple horror experiences. The mid-1800s manor is a genuine historic structure incorporated into the attraction, while the elaborate horror mythology surrounding the event is theatrical entertainment rather than documented history. It normally operates during the Halloween season.', 'limited', 'https://frightland.com/', 'https://frightland.com/', 'America/New_York', now()),
  ('Fiddler’s Bridge — Scott’s Run Legend', 'fiddlers-bridge-scotts-run-legend', 'folklore', 39.53572, -75.64882, 'St. Georges', 'DE', 'A Delaware legend recorded in the twentieth century tells of a local Black fiddler who drowned near Scott’s Run and whose music could supposedly be summoned by tossing a dime from the bridge. The original bridge associated with the story was already gone by the 1950s, so the present crossing is a geographic folklore marker rather than the historic structure itself. Do not stop on active highway lanes.', 'roadside', 'https://www.hauntedplaces.org/item/fiddlers-bridge/', null, 'America/New_York', now()),
  ('Dark Dover Lantern Tours — John Bell House', 'dark-dover-lantern-tours-john-bell-house', 'weird-history', 39.156, -75.52308, 'Dover', 'DE', 'Seasonal Dark Dover tours begin at the historic John Bell House and lead visitors by lantern through the Dover Green area for darker stories, costumed encounters and occasional jump scares. It is a structured way to experience the capital’s stranger history rather than simply visiting another historic house.', 'limited', 'https://visitcentraldelaware.com/events-and-festivals/dark-dover-lantern-tours/', 'https://history.delaware.gov/first-state-heritage-park/', 'America/New_York', now()),
  ('St. Peter’s Cemetery — Captain James Drew Ghost', 'st-peters-cemetery-captain-james-drew-ghost', 'folklore', 38.77539, -75.13982, 'Lewes', 'DE', 'Captain James Drew, commander of HMS DeBraak when the ship sank off Delaware in 1798, is buried in the historic churchyard at St. Peter’s. Local folklore says his ghost leaves the cemetery on moonless nights searching for his lost crew. The shipwreck and Drew’s burial are historical; the wandering captain is the legend.', 'open', 'https://www.visitrehoboth.com/things-to-do/coastal-delaware-ghost-stories', 'https://www.stpeterslewes.org/', 'America/New_York', now()),
  ('Marshall Steam Museum at Auburn Heights', 'marshall-steam-museum-at-auburn-heights', 'museums', 39.80926, -75.67959, 'Yorklyn', 'DE', 'The Marshall Steam Museum preserves what it describes as the world’s largest operating collection of Stanley steam cars along with other antique automobiles. Auburn Valley also operates a miniature live-steam railroad on selected event days, making the site part museum and part functioning mechanical time capsule.', 'limited', 'https://auburnheights.org/', 'https://auburnheights.org/', 'America/New_York', now()),
  ('Rockford Tower', 'rockford-tower', 'roadside-oddities', 39.76731, -75.57489, 'Wilmington', 'DE', 'Rockford Tower looks like a stone observation tower but was built around a massive municipal water tank at the turn of the twentieth century. The roughly 115-foot structure includes an observation level that opens only on scheduled days, turning a piece of water infrastructure into one of Wilmington’s stranger viewpoints.', 'limited', 'https://archives.delaware.gov/delaware-historical-markers/rockford-tower/', 'https://www.visitwilmingtonde.com/listing/rockford-park/940/', 'America/New_York', now()),
  ('Wilmington & Western Railroad', 'wilmington-western-railroad', 'museums', 39.73917, -75.63209, 'Wilmington', 'DE', 'This heritage railroad runs vintage trains through the Red Clay Valley past mills, bridges and a notably tight rock cut where the stone walls crowd close to the cars. The route operates scheduled excursions and seasonal themed trains from its Greenbank station.', 'limited', 'https://www.atlasobscura.com/places/wilmington-western-railroad', 'https://wwrr.com/', 'America/New_York', now()),
  ('One Love Park — Bob Marley’s Delaware Years', 'one-love-park-bob-marleys-delaware-years', 'weird-history', 39.75422, -75.53843, 'Wilmington', 'DE', 'Wilmington renamed this small park One Love Park in recognition of Bob Marley’s time living and working in Delaware. State historical material notes that Marley lived nearby in the 1960s and worked local industrial jobs while raising money for his music career. His former residence is private and should not be approached as part of the stop.', 'open', 'https://archives.delaware.gov/delaware-historical-markers/one-love-park/', 'https://www.wilmingtonde.gov/Home/Components/FacilityDirectory/FacilityDirectory/104/118', 'America/New_York', now()),
  ('Delaware Wedge Plaque', 'delaware-wedge-plaque', 'weird-history', 39.718, -75.7848, 'Newark', 'DE', 'A small marker recalls the Delaware Wedge, a roughly 800-acre geographic anomaly created by conflicting colonial boundary surveys between Delaware, Pennsylvania and Maryland. The oddly shaped tract remained disputed for generations before the boundary was formally settled, turning a tiny roadside plaque into a marker for a surprisingly complicated cartographic problem.', 'roadside', 'https://history.delaware.gov/2023/01/11/delaware-wedge/', null, 'America/New_York', now()),
  ('Rehoboth Beach Temperance Fountain', 'rehoboth-beach-temperance-fountain', 'weird-history', 38.71639, -75.07611, 'Rehoboth Beach', 'DE', 'This granite public drinking fountain was erected in 1929 by the Woman’s Christian Temperance Union to commemorate the Delaware organization’s fiftieth anniversary. Temperance fountains were meant to provide readily available water as an alternative to alcoholic drinks, leaving an unusual piece of Prohibition-era social history directly beside the beach.', 'open', 'https://npgallery.nps.gov/GetAsset/c5ad9348-ef15-4c61-ad87-984e682d28ef', null, 'America/New_York', now()),
  ('The Doors of Fame', 'the-doors-of-fame', 'roadside-oddities', 38.72503, -75.08581, 'Rehoboth Beach', 'DE', 'Three old doors preserved by the Rehoboth Art League carry hundreds of signatures left by artists and local cultural figures over many decades. The doors are fragile and are not guaranteed to be on continuous display, so this is a check-ahead stop rather than a permanent walk-up exhibit.', 'limited', 'https://www.atlasobscura.com/places/the-doors-of-fame-rehoboth-beach-delaware', 'https://www.rehobothartleague.org/', 'America/New_York', now()),
  ('Milton Theatre', 'milton-theatre', 'weird-history', 38.77818, -75.31107, 'Milton', 'DE', 'The historic Milton Theatre has served an unusually long list of purposes, including movie house, basketball hall, fire station, community center and performance venue. It survived major fires, storms, periods of neglect and repeated reinvention before becoming an active theater again.', 'limited', 'https://www.miltontheatre.com/history/', 'https://www.miltontheatre.com/', 'America/New_York', now()),
  ('Lewes Town Clock', 'lewes-town-clock', 'roadside-oddities', 38.77558, -75.13974, 'Lewes', 'DE', 'This freestanding town clock is intentionally designed to look much older than it is. Installed in 2022 and funded by local donors, the roughly ten-foot landmark commemorates Lewes and its 1631 Dutch-settlement history while blending into the town’s centuries-old streetscape.', 'open', 'https://www.atlasobscura.com/places/lewes-town-clock', null, 'America/New_York', now()),
  ('Sussex Tavern — Stockley-Street House', 'sussex-tavern-stockley-street-house', 'museums', 38.77679, -75.14294, 'Lewes', 'DE', 'The Lewes Historical Society operates a recreated colonial tavern inside the circa-1740 Stockley-Street House, drawing inspiration from a real local tavern that operated around the turn of the nineteenth century. Historic drinks, period surroundings and occasional community events turn the preserved house into something much more experiential than a conventional museum room.', 'limited', 'https://www.historiclewes.org/locations/sussex-tavern/', 'https://www.historiclewes.org/locations/sussex-tavern/', 'America/New_York', now()),
  ('Dressed John Milton Statue', 'dressed-john-milton-statue', 'roadside-oddities', 38.77592, -75.31199, 'Milton', 'DE', 'A life-size statue of poet John Milton stands along Governor’s Walk and regularly turns up wearing seasonal costumes and accessories. The anonymous dressing tradition has become a local mystery of its own, with no single person consistently taking credit for the statue’s changing wardrobe.', 'open', 'https://www.atlasobscura.com/places/dressed-john-milton-statue', null, 'America/New_York', now()),
  ('The Gumball Machine Utility Box', 'the-gumball-machine-utility-box', 'roadside-oddities', 39.75605, -75.56047, 'Wilmington', 'DE', 'A utility box in Trolley Square has been transformed into an oversized old-fashioned gumball machine, complete with painted candy, coin slot and dispensing tray. Artist Remi Poindexter created the illusion as part of a larger neighborhood public-art project.', 'open', 'https://www.atlasobscura.com/places/the-gumball-machine-wilmington', null, 'America/New_York', now()),
  ('Clifford Brown Listening Garden', 'clifford-brown-listening-garden', 'roadside-oddities', 39.74807, -75.54085, 'Wilmington', 'DE', 'This compact memorial garden honors Wilmington-born jazz trumpeter Clifford Brown with a towering pair of sculptural obelisks, mosaics, benches and a sound installation. When the interactive system is operating, motion sensors can trigger Brown’s music as visitors move through the garden.', 'open', 'https://www.visitwilmingtonde.com/listing/clifford-brown-listening-garden/8397/', null, 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;

select count(*) as delaware from public.stops where state = 'DE';
