-- Gravity hills, from Wikipedia's sourced List of gravity hills (CC BY-SA).
--
-- Added by hand rather than by the OSM importer, which could never find these:
-- OpenStreetMap records that these are roads, not that cars appear to roll up
-- them. The list is curated and cited, and every entry here carries published
-- coordinates.
--
-- Filed as folklore rather than roadside-oddities: the attraction is the story,
-- and the descriptions say plainly that the slope is an optical illusion. An
-- index that pretended otherwise would not be worth trusting.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone, verified_at)
values
  ('Gravity Hill Lane', 'gravity-hill-lane-oak-grove-al', 'folklore', 33.2036944, -86.30806, 'Oak Grove', 'AL', 'Stop on Gravity Hill Lane, in Talladega County, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Chicago', now()),
  ('Henry''s Hill', 'henry-s-hill-mount-hope-al', 'folklore', 34.4300278, -87.5054444, 'Mount Hope', 'AL', 'Stop on Henry''s Hill, in Lawrence County, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Chicago', now()),
  ('Upper Huffman Gravity Hill', 'upper-huffman-gravity-hill-anchorage-ak', 'folklore', 61.10861, -149.73333, 'Anchorage', 'AK', 'Stop on Upper Huffman Road, on the Hillside, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Anchorage', now()),
  ('Dyer Gravity Hill', 'dyer-gravity-hill-dyer-ar', 'folklore', 35.50139, -94.1476389, 'Dyer', 'AR', 'Stop on just outside Dyer, near Alma, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Chicago', now()),
  ('Sulphur Springs Gravity Hill', 'sulphur-springs-gravity-hill-helena-ar', 'folklore', 34.53583, -90.60583, 'Helena', 'AR', 'Stop on Sulphur Springs Road, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Chicago', now()),
  ('Loma Alta Gravity Hill', 'loma-alta-gravity-hill-altadena-ca', 'folklore', 34.2000278, -118.1218333, 'Altadena', 'CA', 'Stop on East Loma Alta Drive, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Los_Angeles', now()),
  ('Nason Street Gravity Hill', 'nason-street-gravity-hill-moreno-valley-ca', 'folklore', 33.9406944, -117.1916389, 'Moreno Valley', 'CA', 'Stop on Nason Street, heading south just past Elder, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Los_Angeles', now()),
  ('Mountain Springs Gravity Hill', 'mountain-springs-gravity-hill-ocotillo-ca', 'folklore', 32.6789722, -116.0991944, 'Ocotillo', 'CA', 'Stop on the Mountain Springs Road off-ramp from I-8 westbound, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Los_Angeles', now()),
  ('Lichau Road Gravity Hill', 'lichau-road-gravity-hill-rohnert-park-ca', 'folklore', 38.342361, -122.62028, 'Rohnert Park', 'CA', 'Stop on Lichau Road, on the western slope of Sonoma Mountain, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Los_Angeles', now()),
  ('Golden Gate Park Gravity Hill', 'golden-gate-park-gravity-hill-san-francisco-ca', 'folklore', 37.770426, -122.480647, 'San Francisco', 'CA', 'Stop on JFK Drive, where water from Rainbow Falls appears to run towards Lloyd Lake, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Los_Angeles', now()),
  ('Kagel Canyon Gravity Hill', 'kagel-canyon-gravity-hill-sylmar-ca', 'folklore', 34.3045833, -118.3755, 'Sylmar', 'CA', 'Stop on Kagel Canyon Road, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Los_Angeles', now()),
  ('Sterling Gravity Hill', 'sterling-gravity-hill-sterling-ct', 'folklore', 41.7353889, -71.82833, 'Sterling', 'CT', 'Stop on Main Street, just before Snake Meadow Hill Road, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('Spook Hill', 'spook-hill-lake-wales-fl', 'folklore', 27.91194, -81.5823611, 'Lake Wales', 'FL', 'Stop on Spook Hill, off US 27, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('Spook Hill', 'spook-hill-fort-gaines-ga', 'folklore', 31.729083, -85.01056, 'Fort Gaines', 'GA', 'Stop on Spook Hill, north of town, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('Mooresville Gravity Hill', 'mooresville-gravity-hill-mooresville-in', 'folklore', 39.601306, -86.411, 'Mooresville', 'IN', 'Stop on Gravity Hill, outside Mooresville, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Indiana/Indianapolis', now()),
  ('Devou Park Gravity Hill', 'devou-park-gravity-hill-covington-ky', 'folklore', 39.08583, -84.52944, 'Covington', 'KY', 'Stop on Devou Park, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('Princeton Gravity Hill', 'princeton-gravity-hill-princeton-ky', 'folklore', 37.10722, -87.982556, 'Princeton', 'KY', 'Stop on KY 2618, under the Western Kentucky Parkway bridge, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Chicago', now()),
  ('Gapland Road Gravity Hill', 'gapland-road-gravity-hill-burkittsville-md', 'folklore', 39.396861, -77.63444, 'Burkittsville', 'MD', 'Stop on Gapland Road, West Main Street, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('Shelburne Road Gravity Hill', 'shelburne-road-gravity-hill-greenfield-ma', 'folklore', 42.589306, -72.63028, 'Greenfield', 'MA', 'Stop on Shelburne Road, facing east just past the Route 2 overpass, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('Putney Road Gravity Hill', 'putney-road-gravity-hill-blaine-township-mi', 'folklore', 44.53028, -86.16056, 'Blaine Township', 'MI', 'Stop on Putney Road, south of Joyfield Road, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Detroit', now()),
  ('Reasner Road Gravity Hill', 'reasner-road-gravity-hill-rose-city-mi', 'folklore', 44.46333, -84.08722, 'Rose City', 'MI', 'Stop on the end of Reasner Road, past Heath Road, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Detroit', now()),
  ('Freeman Gravity Hill', 'freeman-gravity-hill-freeman-mo', 'folklore', 38.57972, -94.5943889, 'Freeman', 'MO', 'Stop on Route D at East 299th Street, near the Kansas line, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Chicago', now()),
  ('New Prospect Road Gravity Hill', 'new-prospect-road-gravity-hill-jackson-nj', 'folklore', 40.1587778, -74.2676667, 'Jackson', 'NJ', 'Stop on New Prospect Road, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('Pleasant Valley Gravity Hill', 'pleasant-valley-gravity-hill-titusville-nj', 'folklore', 40.3379722, -74.8820556, 'Titusville', 'NJ', 'Stop on Pleasant Valley Road, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('Spook Hill', 'spook-hill-yates-county-ny', 'folklore', 42.7133889, -77.30925, 'Yates County', 'NY', 'Stop on Newell Road, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('Promised Land Gravity Hill', 'promised-land-gravity-hill-portville-ny', 'folklore', 42.0650833, -78.3528611, 'Portville', 'NY', 'Stop on Promised Land Road, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('Spook Rock Road', 'spook-rock-road-rockland-county-ny', 'folklore', 41.1626389, -74.0950278, 'Rockland County', 'NY', 'Stop on Spook Rock Road at US 202, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('Richfield Gravity Hill', 'richfield-gravity-hill-richfield-nc', 'folklore', 35.58333, -80.2450833, 'Richfield', 'NC', 'Stop on Richfield Road, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('King Memorial Gravity Hill', 'king-memorial-gravity-hill-kirtland-hills-oh', 'folklore', 41.64125, -81.2956389, 'Kirtland Hills', 'OH', 'Stop on King Memorial Road, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('Moose Lodge Gravity Hill', 'moose-lodge-gravity-hill-bartlesville-ok', 'folklore', 36.670139, -95.98139, 'Bartlesville', 'OK', 'Stop on Moose Lodge Road, near the railway crossing, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Chicago', now()),
  ('Pitt Road Gravity Hill', 'pitt-road-gravity-hill-springer-ok', 'folklore', 34.345972, -97.1779444, 'Springer', 'OK', 'Stop on Pitt Road, near Ardmore, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Chicago', now()),
  ('Pleasantview Road Gravity Hill', 'pleasantview-road-gravity-hill-lewisberry-pa', 'folklore', 40.153194, -76.8398333, 'Lewisberry', 'PA', 'Stop on Pleasantview Road at PA 177, in York County, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('North Park Gravity Hill', 'north-park-gravity-hill-pittsburgh-pa', 'folklore', 40.6126944, -80.0258056, 'Pittsburgh', 'PA', 'Stop on McKinney Road at Kummer Road, in North Park, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/New_York', now()),
  ('Thunderbird Drive Gravity Hill', 'thunderbird-drive-gravity-hill-el-paso-tx', 'folklore', 31.84361, -106.5175, 'El Paso', 'TX', 'Stop on Thunderbird Drive, facing south, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Denver', now()),
  ('Villamain Road Gravity Hill', 'villamain-road-gravity-hill-san-antonio-tx', 'folklore', 29.31722, -98.44333, 'San Antonio', 'TX', 'Stop on the railway crossing at Villamain and Shane Roads, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Chicago', now()),
  ('Bonneville Boulevard Gravity Hill', 'bonneville-boulevard-gravity-hill-salt-lake-city-ut', 'folklore', 40.78944, -111.87917, 'Salt Lake City', 'UT', 'Stop on Bonneville Boulevard, looping around Memory Grove, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Denver', now()),
  ('Copperton Gravity Hill', 'copperton-gravity-hill-copperton-ut', 'folklore', 40.56611, -112.089028, 'Copperton', 'UT', 'Stop on State Route 48, under the train bridge, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Denver', now()),
  ('North Crosby Road Gravity Hill', 'north-crosby-road-gravity-hill-prosser-wa', 'folklore', 46.36222, -119.7238056, 'Prosser', 'WA', 'Stop on North Crosby Road, northeast of town, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Los_Angeles', now()),
  ('Judgement Street Gravity Hill', 'judgement-street-gravity-hill-shullsburg-wi', 'folklore', 42.5475, -90.23333, 'Shullsburg', 'WI', 'Stop on Judgement Street, just past Rennick Road, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Chicago', now()),
  ('Joe Road Gravity Hill', 'joe-road-gravity-hill-stockbridge-wi', 'folklore', 44.02806, -88.3071389, 'Stockbridge', 'WI', 'Stop on Joe Road, south of Stockbridge off WIS 55, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Chicago', now()),
  ('Garden Creek Gravity Hill', 'garden-creek-gravity-hill-casper-wy', 'folklore', 42.773722, -106.3329722, 'Casper', 'WY', 'Stop on Garden Creek Road, near the Rotary Park entrance, put the car in neutral, and it appears to roll uphill. The slope is an illusion — the surrounding land hides the true horizon, so a gentle descent reads as a climb — which has never once stopped anyone trying it with a bottle of water. A public road, so pull over sensibly and watch for traffic.', 'roadside', 'https://en.wikipedia.org/wiki/List_of_gravity_hills', 'America/Denver', now())
on conflict (slug) do update set
  description = excluded.description,
  latitude    = excluded.latitude,
  longitude   = excluded.longitude,
  source      = excluded.source,
  timezone    = excluded.timezone,
  verified_at = excluded.verified_at;
