-- Hawaii. The last empty state.
--
-- Nothing dropped, because there was nothing here to collide with — the only
-- state in the index that started at zero.
--
-- Excellently sourced: nps.gov, dlnr.hawaii.gov and gohawaii.com are the top
-- three, all first-party.
--
-- Pacific/Honolulu throughout, and Hawaii does not observe daylight saving, so
-- the offset never moves. That is the only state where the timezone is simple.
--
-- Names are stored with the ʻokina and the kahakō intact, because they are
-- part of the spelling rather than decoration — Pele and pele are different
-- words, and Puʻuhonua o Hōnaunau is the name of the place. Only the slug is
-- reduced to ASCII, because a URL cannot carry them.
--
-- One proximity flag kept: the King Kaumualiʻi statue stands 28 metres from
-- Pāʻulaʻula, which is where he ceded the island and the reason the statue is
-- there.
--
-- Worth saying what this is not. A great many of these are heiau, birthstones
-- and burial grounds — active sacred sites rather than attractions, and the
-- descriptions carry that. They are in the index because people go, and the
-- honest thing is to say how to behave rather than leave them out.
--
-- 120 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Bernice Pauahi Bishop Museum', 'bernice-pauahi-bishop-museum', 'museums', 21.33307, -157.87075, 'Honolulu', 'HI', 'Hawaiʻi''s largest museum of natural and cultural history holds extensive Polynesian collections, royal artifacts, a planetarium, and the towering Hawaiian Hall. Its combination of deep-ocean navigation, volcanic science, featherwork, and material culture makes it a foundational OddWay context stop rather than a generic museum.', 'open', 'https://www.bishopmuseum.org/', null, 'Pacific/Honolulu', now()),
  ('ʻIolani Palace', 'iolani-palace', 'weird-history', 21.30682, -157.85877, 'Honolulu', 'HI', 'The only official royal residence in the United States preserves the throne room, private suites, imprisonment room associated with Queen Liliʻuokalani, and artifacts from the Hawaiian Kingdom. Entry is controlled by ticketed tours and museum rules.', 'limited', 'https://www.iolanipalace.org/', null, 'Pacific/Honolulu', now()),
  ('Hānaiakamalama — Queen Emma Summer Palace', 'hanaiakamalama-queen-emma-summer-palace', 'weird-history', 21.33583, -157.83947, 'Honolulu', 'HI', 'This 1848 house became the mountain retreat of Queen Emma, Kamehameha IV, and their son Prince Albert Edward. The Daughters of Hawaiʻi preserve royal furnishings and personal objects inside; tours and access follow the site''s posted schedule.', 'limited', 'https://daughtersofhawaii.org/', null, 'Pacific/Honolulu', now()),
  ('Mauna ʻAla — Royal Mausoleum State Monument', 'mauna-ala-royal-mausoleum-state-monument', 'weird-history', 21.32546, -157.84779, 'Honolulu', 'HI', 'Mauna ʻAla is the burial place of many members of Hawaiʻi''s royal families, including rulers of the Kamehameha and Kalākaua dynasties. It is an active sacred and commemorative landscape, so OddWay visitors should observe posted hours and treat the grounds as a cemetery rather than a sightseeing prop.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/oahu/royal-mausoleum-state-monument/', null, 'Pacific/Honolulu', now()),
  ('Hawaiian Mission Houses Historic Site and Archives', 'hawaiian-mission-houses-historic-site-and-archives', 'weird-history', 21.30379, -157.85679, 'Honolulu', 'HI', 'Three surviving mission-era structures stand beside Kawaiahaʻo Church, including one of Hawaiʻi''s oldest Western-style houses. Exhibits and archives document printing, language, religion, and daily life during a period when written Hawaiian and political life were changing rapidly.', 'limited', 'https://www.missionhouses.org/', null, 'Pacific/Honolulu', now()),
  ('Kawaiahaʻo Church and King Lunalilo Tomb', 'kawaiahao-church-and-king-lunalilo-tomb', 'weird-history', 21.30435, -157.85782, 'Honolulu', 'HI', 'Built from thousands of coral slabs, Kawaiahaʻo became one of the most important churches of the Hawaiian Kingdom. The grounds also hold the tomb of King Lunalilo, who chose burial here rather than at the Royal Mausoleum; remember that this remains an active place of worship.', 'limited', 'https://kawaiahaochurch.com/', null, 'Pacific/Honolulu', now()),
  ('King Kamehameha I Statue at Aliʻiōlani Hale', 'king-kamehameha-i-statue-at-aliiolani-hale', 'roadside-oddities', 21.30571, -157.85967, 'Honolulu', 'HI', 'The gilded bronze Kamehameha statue stands before Aliʻiōlani Hale and has become one of Honolulu''s most recognizable royal monuments. The building behind it once housed the kingdom''s government and now contains the Hawaiʻi Supreme Court and a judiciary history center.', 'open', 'https://www.gohawaii.com/islands/oahu/things-to-do/land-activities/historic-places', null, 'Pacific/Honolulu', now()),
  ('Hawaiʻi State Capitol — Volcano-Crater Architecture', 'hawaii-state-capitol-volcano-crater-architecture', 'roadside-oddities', 21.30724, -157.85738, 'Honolulu', 'HI', 'Hawaiʻi''s capitol rejects the usual domed statehouse design: its open-air atrium evokes a volcanic crater, cone-shaped legislative chambers represent volcanoes, and a surrounding pool symbolizes the Pacific. The building''s symbolic architecture is unusually literal and island-specific.', 'open', 'https://www.capitol.hawaii.gov/', null, 'Pacific/Honolulu', now()),
  ('Kapaemahu — Healing Stones of Waikīkī', 'kapaemahu-healing-stones-of-waikiki', 'folklore', 21.27576, -157.82569, 'Honolulu', 'HI', 'Four large stones near Kūhiō Beach commemorate the tradition of four māhū healers from Tahiti who are said to have transferred their healing powers into the stones before leaving Oʻahu. The site is culturally significant; read the interpretation and do not climb on or treat the stones as props.', 'open', 'https://www.waikikihistorictrail.org/the-healing-stones-of-kapaemahu', null, 'Pacific/Honolulu', now()),
  ('Shangri La Museum of Islamic Art, Culture & Design', 'shangri-la-museum-of-islamic-art-culture-design', 'roadside-oddities', 21.2569, -157.79496, 'Honolulu', 'HI', 'Doris Duke transformed this oceanfront estate into a highly personal architectural environment filled with Islamic art, tilework, carved interiors, and gardens. Visits are controlled through scheduled museum access rather than casual walk-ins to the private residential neighborhood.', 'limited', 'https://www.shangrilahawaii.org/', null, 'Pacific/Honolulu', now()),
  ('U.S. Army Museum of Hawaiʻi — Battery Randolph', 'u-s-army-museum-of-hawaii-battery-randolph', 'weird-history', 21.27903, -157.83384, 'Honolulu', 'HI', 'A former coastal artillery battery at Fort DeRussy now houses an Army museum inside thick concrete defenses built to protect Honolulu. Exhibits range from pre-contact warfare through World War II and later conflicts, while the bunker itself is one of the strongest artifacts.', 'open', 'https://hiarmymuseumsoc.org/', null, 'Pacific/Honolulu', now()),
  ('USS Arizona Memorial', 'uss-arizona-memorial', 'weird-history', 21.36488, -157.95001, 'Honolulu', 'HI', 'The memorial spans the wreck of USS Arizona, where more than 900 crew members remain entombed after the 1941 Pearl Harbor attack. Boat access is controlled through the National Park Service, and the site should be treated as a war grave and memorial.', 'limited', 'https://www.nps.gov/perl/', null, 'Pacific/Honolulu', now()),
  ('Pacific Fleet Submarine Museum and USS Bowfin', 'pacific-fleet-submarine-museum-and-uss-bowfin', 'weird-history', 21.36887, -157.93999, 'Honolulu', 'HI', 'Visitors can descend into USS Bowfin, a World War II submarine launched one year after the Pearl Harbor attack, then explore exhibits on undersea warfare and the Pacific submarine campaign. Tight ladders and confined passages make the preserved vessel substantially more immersive than a conventional museum gallery.', 'open', 'https://www.bowfin.org/', null, 'Pacific/Honolulu', now()),
  ('Battleship Missouri Memorial', 'battleship-missouri-memorial', 'weird-history', 21.36296, -157.95361, 'Honolulu', 'HI', 'USS Missouri is preserved at Ford Island near the site where the Pacific War began; Japan''s formal surrender was signed aboard the ship in Tokyo Bay in 1945. Access requires the authorized Pearl Harbor shuttle and current base-security procedures.', 'limited', 'https://ussmissouri.org/', null, 'Pacific/Honolulu', now()),
  ('Pearl Harbor Aviation Museum', 'pearl-harbor-aviation-museum', 'weird-history', 21.35895, -157.96354, 'Honolulu', 'HI', 'Historic hangars on Ford Island hold aircraft and exhibits connected with the attack on Pearl Harbor and later Pacific aviation. Bullet scars and wartime structures remain part of the setting; visitors reach the museum through controlled shuttle access.', 'limited', 'https://www.pearlharboraviationmuseum.org/', null, 'Pacific/Honolulu', now()),
  ('USS Oklahoma Memorial', 'uss-oklahoma-memorial', 'weird-history', 21.36351, -157.95424, 'Honolulu', 'HI', 'White marble standards commemorate the 429 sailors and Marines killed when USS Oklahoma capsized during the attack on Pearl Harbor. The memorial sits on Ford Island near Battleship Missouri and is reached through the same controlled historic-site access system.', 'limited', 'https://www.nps.gov/perl/', null, 'Pacific/Honolulu', now()),
  ('National Memorial Cemetery of the Pacific — Punchbowl Crater', 'national-memorial-cemetery-of-the-pacific-punchbowl-crater', 'weird-history', 21.31245, -157.84612, 'Honolulu', 'HI', 'A military cemetery occupies the interior of Punchbowl, an extinct volcanic tuff cone above Honolulu. The combination of crater geology, monumental stairways, mosaics, and thousands of military graves makes it visually unusual, but visitors should follow cemetery rules and maintain respectful behavior.', 'limited', 'https://www.cem.va.gov/cems/nchp/nmcp.asp', null, 'Pacific/Honolulu', now()),
  ('Daijingu Temple of Hawaii', 'daijingu-temple-of-hawaii', 'roadside-oddities', 21.3352, -157.83752, 'Honolulu', 'HI', 'Oʻahu''s oldest Shinto shrine developed a distinctly Hawaiian-American pantheon, enshrining figures including Kamehameha I, King Kalākaua, George Washington, and Abraham Lincoln alongside traditional kami. It remains an active religious institution, not a themed attraction.', 'open', 'https://daijingutemple.org/', null, 'Pacific/Honolulu', now()),
  ('Byodo-In Temple', 'byodo-in-temple', 'roadside-oddities', 21.43072, -157.83224, 'Kāneʻohe', 'HI', 'A smaller-scale replica of the nearly thousand-year-old Byōdō-in temple in Uji, Japan, stands against the Koʻolau cliffs inside Valley of the Temples Memorial Park. Visitors can ring the large bon-shō bell and enter the temple during posted visitor hours.', 'limited', 'https://byodo-in.com/', null, 'Pacific/Honolulu', now()),
  ('Hawaii''s Plantation Village', 'hawaiis-plantation-village', 'museums', 21.38543, -158.01186, 'Waipahu', 'HI', 'More than two dozen restored or reconstructed plantation-era buildings recreate the communities where Hawaiian, Japanese, Filipino, Chinese, Korean, Portuguese, Puerto Rican, Okinawan, and other workers lived. Guided tours make the site a walk-through archive of sugar-era everyday life.', 'limited', 'https://www.hawaiiplantationvillage.org/home.html', null, 'Pacific/Honolulu', now()),
  ('Puʻu O Mahuka Heiau State Historic Site', 'puu-o-mahuka-heiau-state-historic-site', 'weird-history', 21.64469, -158.062, 'Pūpūkea', 'HI', 'The largest known heiau on Oʻahu occupies a ridge above Waimea Bay. Massive stone terraces preserve a major Native Hawaiian ceremonial complex; stay on designated paths, never move stones or leave offerings, and approach the site as a protected sacred landscape.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/oahu/puu-o-mahuka-heiau-state-historic-site/', null, 'Pacific/Honolulu', now()),
  ('Ulupō Heiau State Historic Site', 'ulupo-heiau-state-historic-site', 'weird-history', 21.38559, -157.75306, 'Kailua', 'HI', 'A huge stone platform in Kailua preserves one of Oʻahu''s major ancient heiau, with walls built from thousands of stones carried from surrounding areas. The site remains culturally significant to Native Hawaiian practitioners; stay within allowed public access and do not disturb the structure.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/oahu/ulupo-heiau-state-historic-site/', null, 'Pacific/Honolulu', now()),
  ('Keaīwa Heiau State Recreation Area', 'keaiwa-heiau-state-recreation-area', 'weird-history', 21.39972, -157.90806, 'ʻAiea', 'HI', 'The remains of Keaīwa Heiau are traditionally associated with healing and medicinal practice. The site sits within a forested recreation area above Pearl Harbor, but the heiau itself deserves culturally respectful treatment and should not be climbed on or altered.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/oahu/keaiwa-heiau-state-recreation-area/', null, 'Pacific/Honolulu', now()),
  ('Kūkaniloko Birthstones', 'kukaniloko-birthstones', 'weird-history', 21.5047, -158.03625, 'Wahiawā', 'HI', 'Kūkaniloko is one of Hawaiʻi''s most important royal birth sites, where high-ranking aliʻi were traditionally born. The site remains closed to casual public entry in 2026; current stewards provide escorted access only by reservation, so OddWay should never route users through the gate without authorization.', 'limited', 'https://www.kukaniloko.org/', null, 'Pacific/Honolulu', now()),
  ('Nuʻuanu Pali Lookout', 'nuuanu-pali-lookout', 'weird-history', 21.36708, -157.79319, 'Honolulu', 'HI', 'The Pali overlooks the cliffs associated with the 1795 Battle of Nuʻuanu, when Kamehameha I''s forces defeated Oʻahu''s defenders during the campaign to unify the islands. The state wayside is also a classic setting for local supernatural lore. As of September 10, 2026, it remains temporarily closed for Hurricane Lowell repairs.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/oahu/nuuanu-pali-state-wayside/', null, 'Pacific/Honolulu', now()),
  ('Hale o Lono at Waimea Valley', 'hale-o-lono-at-waimea-valley', 'weird-history', 21.63938, -158.05988, 'Haleʻiwa', 'HI', 'Waimea Valley preserves multiple Native Hawaiian cultural sites, including Hale o Lono, a heiau dedicated to Lono and dated by the organization to around the fifteenth century. It remains a living cultural place inside a ticketed botanical and heritage site.', 'limited', 'https://www.waimeavalley.net/cultural-sites', null, 'Pacific/Honolulu', now()),
  ('Koko Crater Railway Trail', 'koko-crater-railway-trail', 'weird-history', 21.27788, -157.69284, 'Honolulu', 'HI', 'More than a thousand steep railroad-tie steps climb the side of Koko Crater along the route of a former military tramway built to service summit installations. The abandoned infrastructure has become one of Oʻahu''s strangest and most physically demanding public stairways.', 'open', 'https://www.gohawaii.com/islands/oahu/things-to-do/land-activities/hiking', null, 'Pacific/Honolulu', now()),
  ('Lēʻahi — Diamond Head State Monument', 'leahi-diamond-head-state-monument', 'roadside-oddities', 21.26348, -157.80502, 'Honolulu', 'HI', 'The trail into and up the rim of this tuff cone passes through tunnels, stairways, and remnants of a former coastal defense complex before reaching the summit. Nonresident entry is reservation-controlled, and the military engineering is as important to the OddWay stop as the crater itself.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/oahu/diamond-head-state-monument/', null, 'Pacific/Honolulu', now()),
  ('Makapuʻu Point Lighthouse Trail', 'makapuu-point-lighthouse-trail', 'weird-history', 21.3099, -157.64976, 'Waimānalo', 'HI', 'A paved ridge trail looks down on the red-roofed 1909 Makapuʻu Lighthouse and its unusually large Fresnel lens. The lighthouse itself is not normally open for public entry, but the route provides a clear view of the isolated coastal installation and volcanic shoreline.', 'open', 'https://dlnr.hawaii.gov/dsp/hiking/oahu/', null, 'Pacific/Honolulu', now()),
  ('Hālona Blowhole', 'halona-blowhole', 'roadside-oddities', 21.28229, -157.67676, 'Honolulu', 'HI', 'Ocean swells force water through a lava tube and blast spray from a hole in the coastal rock beside Kalanianaʻole Highway. Conditions can turn dangerous quickly; use the established overlook and never stand directly over the blowhole or enter rough surf below.', 'roadside', 'https://www.gohawaii.com/islands/oahu', null, 'Pacific/Honolulu', now()),
  ('Kāneana — Mākua Cave', 'kaneana-makua-cave', 'folklore', 21.51964, -158.22753, 'Mākaha', 'HI', 'The large sea cave near Mākua is tied to Native Hawaiian traditions involving the shark-man Nanaue and appears in state interpretation of the Kaʻena coast. OddWay should treat it as a culturally significant roadside cave stop, not an invitation to explore deep or unstable passages.', 'roadside', 'https://dlnr.hawaii.gov/dsp/parks/oahu/kaena-point-state-park/', null, 'Pacific/Honolulu', now()),
  ('Kaʻena Point', 'kaena-point', 'folklore', 21.57442, -158.28058, 'Mokulēʻia', 'HI', 'Oʻahu''s remote western tip combines fossil reef, sea arches, seabird habitat, monk seals, and traditions describing Kaʻena as a leaping-off place for souls. Both road-access sections remain temporarily closed for Hurricane Lowell repairs as of September 10, 2026; verify reopening before routing.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/oahu/kaena-point-state-park/', null, 'Pacific/Honolulu', now()),
  ('Lāʻie Point Sea Arch', 'laie-point-sea-arch', 'folklore', 21.64817, -157.9136, 'Lāʻie', 'HI', 'A wave-cut hole pierces an offshore volcanic islet at this tiny residential wayside. Hawaiian legend connects the scattered offshore rocks with the defeated moʻo Kūiniolo; parking is extremely limited, and visitors must avoid blocking neighboring driveways or entering the adjacent private point.', 'roadside', 'https://dlnr.hawaii.gov/dsp/parks/oahu/laie-point-state-wayside/', null, 'Pacific/Honolulu', now()),
  ('Dole Plantation Pineapple Garden Maze', 'dole-plantation-pineapple-garden-maze', 'roadside-oddities', 21.52605, -158.03765, 'Wahiawā', 'HI', 'A large hedge maze shaped around a pineapple motif spreads across the Dole Plantation grounds. It is unapologetically roadside-tourism spectacle, but its scale and pineapple-industrial setting make it a useful OddWay stop distinct from the plantation''s ordinary retail areas.', 'limited', 'https://www.doleplantation.com/worlds-largest-maze/', null, 'Pacific/Honolulu', now()),
  ('Haleakalā Summit — Puʻu ʻUlaʻula', 'haleakala-summit-puu-ulaula', 'roadside-oddities', 20.70972, -156.25333, 'Kula', 'HI', 'The summit area of Haleakalā rises above 10,000 feet over an enormous erosional crater filled with cinder cones and lava landscapes. Weather, altitude, park rules, and sunrise reservation requirements can all affect access, so conditions should be checked before routing.', 'limited', 'https://www.nps.gov/hale/planyourvisit/index.htm', null, 'Pacific/Honolulu', now()),
  ('Keoneheʻeheʻe — Sliding Sands Trailhead', 'keoneheehee-sliding-sands-trailhead', 'roadside-oddities', 20.71511, -156.24982, 'Kula', 'HI', 'The trail descends from the summit rim into Haleakalā''s stark crater landscape, crossing loose cinder and high-elevation volcanic terrain that can look almost extraterrestrial. This is a serious backcountry environment rather than a casual roadside walk; visitors should match distance to conditions and ability.', 'limited', 'https://www.nps.gov/hale/planyourvisit/index.htm', null, 'Pacific/Honolulu', now()),
  ('Kīpahulu District — ʻOheʻo Gulch', 'kipahulu-district-oheo-gulch', 'roadside-oddities', 20.662, -156.04481, 'Hāna', 'HI', 'A chain of stream pools and waterfalls cuts through volcanic rock near the coast in Haleakalā National Park''s Kīpahulu District. Flash floods and closures can occur without much warning, and the park may prohibit water entry even when trails are open.', 'limited', 'https://www.nps.gov/hale/planyourvisit/index.htm', null, 'Pacific/Honolulu', now()),
  ('Pīpīwai Trail Bamboo Forest', 'pipiwai-trail-bamboo-forest', 'roadside-oddities', 20.66182, -156.04559, 'Hāna', 'HI', 'The Pīpīwai Trail climbs from Kīpahulu through dense bamboo, stream crossings, giant banyan growth, and waterfall country toward Waimoku Falls. The enclosed bamboo section is the distinctive OddWay feature, but weather and flash-flood conditions can change trail safety rapidly.', 'limited', 'https://www.nps.gov/hale/planyourvisit/index.htm', null, 'Pacific/Honolulu', now()),
  ('ʻĪao Valley State Monument — ʻĪao Needle', 'iao-valley-state-monument-iao-needle', 'roadside-oddities', 20.88417, -156.55106, 'Wailuku', 'HI', 'The narrow valley centers on the steep erosional remnant known as Kukaʻemoku or the ʻĪao Needle and was also the setting of the violent 1790 Battle of Kepaniwai. Entry is controlled by state-park rules and nonresident reservation requirements.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/maui/iao-valley-state-monument/', null, 'Pacific/Honolulu', now()),
  ('Halekiʻi-Pihana Heiau State Monument', 'halekii-pihana-heiau-state-monument', 'weird-history', 20.90833, -156.495, 'Wailuku', 'HI', 'Two important heiau survive on ridges above central Maui and were rededicated as war temples by Kahekili, Maui''s last independent ruling chief. The site is open during daylight but remains a protected cultural landscape; visitors should stay off walls and platforms.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/maui/halekii-pihana-heiau-state-monument/', null, 'Pacific/Honolulu', now()),
  ('Waiʻānapanapa Black Sand and Lava Formations', 'waianapanapa-black-sand-and-lava-formations', 'roadside-oddities', 20.78581, -155.99699, 'Hāna', 'HI', 'Black volcanic sand, sea caves, lava arches, blowholes, and sharp coastal formations crowd a small section of shoreline at Waiʻānapanapa. Nonresident reservations are required, and ocean conditions make this a place to follow barriers rather than improvise routes along cliffs or caves.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/maui/waianapanapa-state-park/', null, 'Pacific/Honolulu', now()),
  ('Hāna Lava Tube — Kaʻeleku Caverns', 'hana-lava-tube-kaeleku-caverns', 'roadside-oddities', 20.78517, -156.02792, 'Hāna', 'HI', 'Visitors descend into a privately operated lava tube formed by flowing basalt, where frozen lava textures, chambers, and ceilings preserve the mechanics of an ancient eruption underground. Entry is ticketed and should follow the operator''s lighting and footwear guidance.', 'limited', 'https://mauicave.com/', null, 'Pacific/Honolulu', now()),
  ('Piʻilanihale Heiau at Kahanu Garden', 'piilanihale-heiau-at-kahanu-garden', 'weird-history', 20.80382, -156.03982, 'Hāna', 'HI', 'The enormous Piʻilanihale Heiau is one of the largest surviving traditional Hawaiian temple platforms and sits within the National Tropical Botanical Garden''s Kahanu Garden. It is culturally sacred and archaeologically protected; visitors should use the garden''s designated route and interpretation.', 'limited', 'https://ntbg.org/gardens/kahanu/', null, 'Pacific/Honolulu', now()),
  ('Charles Lindbergh Grave — Palapala Hoʻomau Church', 'charles-lindbergh-grave-palapala-hoomau-church', 'weird-history', 20.6514, -156.05531, 'Kīpahulu', 'HI', 'A small nineteenth-century churchyard on the remote Hāna coast contains the grave of aviator Charles Lindbergh, who spent his final years nearby. The church explicitly welcomes respectful visitors while asking them to honor the congregation, relatives, and people buried in the graveyard.', 'limited', 'https://www.hmdb.org/m.asp?m=71842', null, 'Pacific/Honolulu', now()),
  ('Nakalele Blowhole', 'nakalele-blowhole', 'roadside-oddities', 21.02709, -156.58861, 'Kahakuloa', 'HI', 'Waves funnel into a lava-rock opening and erupt vertically from the coast at Nakalele Point. The blowhole is dramatic precisely because the shoreline is powerful and unpredictable; remain well back from the opening and avoid wet rock near heavy surf.', 'limited', 'https://www.hawaii-guide.com/maui/sights/nakalele-blowhole', null, 'Pacific/Honolulu', now()),
  ('Dragon''s Teeth — Makaluapuna Point', 'dragons-teeth-makaluapuna-point', 'roadside-oddities', 21.0011, -156.65287, 'Kapalua', 'HI', 'A line of jagged lava spires resembles oversized teeth where a past flow met strong wind and surf at Makaluapuna Point. The route crosses exposed coastal terrain beside resort land, and visitors should remain on the established path and respect nearby burial and cultural areas.', 'limited', 'https://www.hawaii-guide.com/maui/sights/dragons-teeth', null, 'Pacific/Honolulu', now()),
  ('Olowalu Petroglyphs — Puʻu Kilea', 'olowalu-petroglyphs-puu-kilea', 'weird-history', 20.81928, -156.61504, 'Olowalu', 'HI', 'Hundreds of carved human and geometric figures are associated with the Olowalu petroglyph field. Access conditions and land stewardship have changed over time, so OddWay should route only when a lawful current path is confirmed and should never encourage touching, tracing, or adding marks.', 'limited', 'https://dlnr.hawaii.gov/shpd/', null, 'Pacific/Honolulu', now()),
  ('Alexander & Baldwin Sugar Museum', 'alexander-baldwin-sugar-museum', 'weird-history', 20.86936, -156.45507, 'Puʻunēnē', 'HI', 'The museum occupies a former plantation superintendent''s house across from the old Puʻunēnē sugar mill and interprets the machinery, labor, irrigation, and immigrant communities behind Maui''s sugar industry. Large outdoor equipment gives the stop an industrial scale beyond a normal local-history museum.', 'open', 'https://sugarmuseum.com/', null, 'Pacific/Honolulu', now()),
  ('Hale Hōʻikeʻike at the Bailey House', 'hale-hoikeike-at-the-bailey-house', 'museums', 20.88578, -156.50711, 'Wailuku', 'HI', 'A nineteenth-century mission-era house contains Maui Historical Society collections ranging from Native Hawaiian artifacts and missionary material to photographs and regional history. The building itself is part of the story, standing near the entrance to ʻĪao Valley.', 'limited', 'https://www.mauimuseum.org/', null, 'Pacific/Honolulu', now()),
  ('Polipoli Redwood Forest', 'polipoli-redwood-forest', 'roadside-oddities', 20.68056, -156.3325, 'Kula', 'HI', 'At roughly 6,200 feet on Haleakalā''s slopes, introduced redwoods and other temperate trees form a cool, foggy forest that feels radically different from coastal Maui. The access road requires a four-wheel-drive vehicle for camping areas, and storm or road damage can change availability quickly.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/maui/polipoli-spring-state-recreation-area/', null, 'Pacific/Honolulu', now()),
  ('Sun Yat-sen Memorial Park', 'sun-yat-sen-memorial-park', 'weird-history', 20.69164, -156.37851, 'Kula', 'HI', 'A small hillside park in upcountry Maui commemorates Chinese revolutionary leader Sun Yat-sen, who had family connections to Hawaiʻi and spent formative years in the islands. The unexpected memorial appears among ranchland and vineyards rather than in an urban Chinatown setting.', 'open', 'https://www.hawaii-guide.com/maui/sights/sun-yat-sen-memorial-park', null, 'Pacific/Honolulu', now()),
  ('Keoneʻōʻio — La Perouse Bay Lava Fields', 'keoneoio-la-perouse-bay-lava-fields', 'roadside-oddities', 20.59723, -156.42273, 'Mākena', 'HI', 'Young ʻaʻā lava from Haleakalā''s most recent eruptive period reaches the sea around Keoneʻōʻio, leaving a stark black landscape threaded with archaeological remains and old coastal trails. Use designated parking and established routes; this is both a geologic and culturally sensitive landscape.', 'limited', 'https://www.hawaii-guide.com/maui/beaches/la-perouse-bay', null, 'Pacific/Honolulu', now()),
  ('Waimea Canyon State Park', 'waimea-canyon-state-park', 'roadside-oddities', 22.05611, -159.66528, 'Waimea', 'HI', 'Deep erosion has cut a multicolored canyon into Kauaʻi''s volcanic interior, exposing red rock, basalt layers, waterfalls, and deeply incised ridges. The park is a legitimate geology stop rather than just a viewpoint. All Kauaʻi state parks remain temporarily closed after Hurricane Lowell as of September 10, 2026.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/kauai/waimea-canyon-state-park/', null, 'Pacific/Honolulu', now()),
  ('Kōkeʻe Natural History Museum', 'kokee-natural-history-museum', 'museums', 22.13035, -159.6576, 'Waimea', 'HI', 'This small high-elevation museum interprets Kauaʻi''s geology, native ecosystems, weather, and cultural history beside Kōkeʻe State Park. Its maps and natural-history material are especially useful context for the island''s canyon and cliff landscapes; verify post-storm operating status before making a special trip.', 'limited', 'https://www.kokee.org/', null, 'Pacific/Honolulu', now()),
  ('Pāʻulaʻula — Russian Fort Elizabeth State Historical Park', 'paulaula-russian-fort-elizabeth-state-historical-park', 'weird-history', 21.95176, -159.66446, 'Waimea', 'HI', 'Earthworks beside the Waimea River preserve the remains of an early nineteenth-century fort associated with the Russian-American Company and Kauaʻi ruler Kaumualiʻi. The history is more complicated than the old ''Russian fort'' label suggests. The state park is temporarily closed after Hurricane Lowell.', 'limited', 'https://www.nps.gov/places/russian-fort-fort-elizabeth.htm', null, 'Pacific/Honolulu', now()),
  ('King Kaumualiʻi Statue', 'king-kaumualii-statue', 'roadside-oddities', 21.95159, -159.66426, 'Waimea', 'HI', 'An eight-foot bronze statue honors Kaumualiʻi, the last independent aliʻi nui of Kauaʻi, beside the Pāʻulaʻula historic landscape. Its placement deliberately recenters the site''s Hawaiian political history alongside the better-known Russian episode; current park access is affected by Hurricane Lowell closures.', 'limited', 'https://kauaikingkaumualii.org/', null, 'Pacific/Honolulu', now()),
  ('Captain James Cook Statue and Landing Area', 'captain-james-cook-statue-and-landing-area', 'roadside-oddities', 21.95477, -159.66701, 'Waimea', 'HI', 'A statue near Waimea commemorates Captain James Cook''s 1778 arrival on Kauaʻi, one of the first documented European contacts with the Hawaiian Islands. The monument is best read alongside nearby Kaumualiʻi and Pāʻulaʻula sites so the stop does not reduce local history to a single explorer narrative.', 'roadside', 'https://www.gohawaii.com/islands/kauai/regions/west-side/waimea', null, 'Pacific/Honolulu', now()),
  ('Hanapēpē Swinging Bridge', 'hanapepe-swinging-bridge', 'roadside-oddities', 21.91227, -159.58687, 'Hanapēpē', 'HI', 'A narrow pedestrian suspension bridge sways above the Hanapēpē River behind the historic town center. It is a compact piece of plantation-era infrastructure turned local landmark; because Kauaʻi is recovering from Hurricane Lowell, verify the bridge and surrounding access before routing.', 'limited', 'https://www.gohawaii.com/islands/kauai/regions/west-side/hanapepe-town', null, 'Pacific/Honolulu', now()),
  ('McBryde Sugar Plantation Cemetery', 'mcbryde-sugar-plantation-cemetery', 'weird-history', 21.8973, -159.58199, 'ʻEleʻele', 'HI', 'A small plantation cemetery above Port Allen contains graves of workers and families from Kauaʻi''s sugar era, including markers with Japanese and English inscriptions. It is reached through an industrial/dirt-road area and remains a burial ground; visit only where lawful and with cemetery-level respect.', 'limited', 'https://portuguesecollections.org/cemeteries/', null, 'Pacific/Honolulu', now()),
  ('Kauaʻi Glass Beach', 'kauai-glass-beach', 'roadside-oddities', 21.89828, -159.58438, 'ʻEleʻele', 'HI', 'Wave-tumbled glass mixed into dark shoreline sediment records an unusual afterlife of discarded material near Port Allen''s industrial coast. Conditions vary with tides and storms, and visitors should not remove remaining glass or wander into adjacent industrial/private areas.', 'limited', 'https://www.kauai.com/glass-beach', null, 'Pacific/Honolulu', now()),
  ('ʻAlekoko — Menehune Fishpond', 'alekoko-menehune-fishpond', 'folklore', 21.94868, -159.37232, 'Līhuʻe', 'HI', 'A large ancient fishpond beside Huleʻia is traditionally linked to stories of the Menehune, who are said to have built its stonework in a single night. The pond is also an important Hawaiian engineering and aquaculture site; use lawful overlooks or authorized tours rather than entering private wetland areas.', 'roadside', 'https://www.gohawaii.com/islands/kauai', null, 'Pacific/Honolulu', now()),
  ('Kauaʻi Museum', 'kauai-museum', 'museums', 21.97504, -159.36828, 'Līhuʻe', 'HI', 'The museum''s volcanic-stone buildings hold artifacts, art, royal history, geology, and material from Kauaʻi and Niʻihau. It is one of the best places to put the island''s heiau, legends, plantation history, and independent Kaumualiʻi kingdom into context before visiting scattered sites.', 'open', 'https://www.kauaimuseum.org/', null, 'Pacific/Honolulu', now()),
  ('Grove Farm Homestead Museum', 'grove-farm-homestead-museum', 'weird-history', 21.96545, -159.36875, 'Līhuʻe', 'HI', 'A preserved sugar-plantation estate contains the Wilcox family home, workers'' structures, gardens, and machinery tied to Kauaʻi''s plantation economy. Public access is through scheduled tours rather than unrestricted wandering across the working property.', 'limited', 'https://grovefarm.org/', null, 'Pacific/Honolulu', now()),
  ('Kilohana Plantation and Kauaʻi Plantation Railway', 'kilohana-plantation-and-kauai-plantation-railway', 'roadside-oddities', 21.97115, -159.39112, 'Līhuʻe', 'HI', 'A restored 1930s plantation estate anchors a narrow-gauge railway that loops through former agricultural land using vintage-style diesel equipment. The ride intentionally turns plantation infrastructure into an interpretive attraction; tickets and schedules apply.', 'limited', 'https://www.kauaiplantationrailway.com/', null, 'Pacific/Honolulu', now()),
  ('Daniel K. Inouye Kīlauea Point Lighthouse', 'daniel-k-inouye-kilauea-point-lighthouse', 'weird-history', 22.23161, -159.402, 'Kīlauea', 'HI', 'The 1913 lighthouse occupies a dramatic volcanic headland inside Kīlauea Point National Wildlife Refuge and once carried a large second-order Fresnel lens. Refuge reservations, wildlife closures, and storm-recovery conditions can affect access, so check the U.S. Fish and Wildlife Service before routing.', 'limited', 'https://www.fws.gov/refuge/kilauea-point', null, 'Pacific/Honolulu', now()),
  ('Waiʻoli Mission House', 'waioli-mission-house', 'weird-history', 22.20094, -159.50192, 'Hanalei', 'HI', 'This restored nineteenth-century mission house preserves furnishings and domestic spaces from Hanalei''s early missionary period beside the distinctive green Waiʻoli Huiʻia Church. Opening days are limited, making it a check-ahead historic-house stop rather than a guaranteed walk-in attraction.', 'limited', 'https://www.gohawaii.com/islands/kauai/regions/north-shore/hanalei-town', null, 'Pacific/Honolulu', now()),
  ('Maniniholo Dry Cave', 'maniniholo-dry-cave', 'roadside-oddities', 22.21927, -159.56532, 'Hāʻena', 'HI', 'A broad, shallow sea cave opens directly beside the north-shore highway near Hāʻena, its ceiling and sandy floor creating an accessible-looking cavern in ancient reef and volcanic terrain. Storm damage, rockfall, and surf conditions should be checked before entry; never climb unstable walls.', 'limited', 'https://www.hawaii-guide.com/kauai/sights/maniniholo-dry-cave', null, 'Pacific/Honolulu', now()),
  ('Spouting Horn Blowhole', 'spouting-horn-blowhole', 'roadside-oddities', 21.8847, -159.4934, 'Kōloa', 'HI', 'Incoming surf compresses air and water through lava-rock openings, producing a plume and a distinctive rushing or groaning sound at this south-shore lookout. Stay behind barriers: blowholes can pull people toward openings as well as shoot water outward.', 'roadside', 'https://www.gohawaii.com/islands/kauai', null, 'Pacific/Honolulu', now()),
  ('Makauwahi Cave Reserve', 'makauwahi-cave-reserve', 'roadside-oddities', 21.88842, -159.41877, 'Kōloa', 'HI', 'A collapsed limestone cave and sinkhole preserves more than 10,000 years of fossil, pollen, seed, shell, bone, and environmental evidence. The reserve pairs paleontology with native-plant restoration and grazing giant tortoises; cave gates and private-property boundaries must be respected.', 'limited', 'https://cavereserve.org/', null, 'Pacific/Honolulu', now()),
  ('Holoholokū Heiau and Royal Birthstones', 'holoholoku-heiau-and-royal-birthstones', 'weird-history', 22.04886, -159.33904, 'Wailua', 'HI', 'The Wailua River complex contains a heiau, royal birthstone traditions, and one of the densest concentrations of high-status Hawaiian cultural sites on Kauaʻi. It is a protected sacred landscape inside the state-park system, currently closed with other Kauaʻi state parks after Hurricane Lowell.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/kauai/wailua-river-state-park/', null, 'Pacific/Honolulu', now()),
  ('Kīlauea Overlook and Kaluapele', 'kilauea-overlook-and-kaluapele', 'roadside-oddities', 19.42342, -155.28562, 'Volcano', 'HI', 'A rim overlook faces Kaluapele, the summit caldera of Kīlauea, one of the world''s most active volcanoes. Eruption status, gas, closures, and visibility can change rapidly; OddWay should link users to current National Park Service and USGS conditions rather than promise lava viewing.', 'limited', 'https://www.nps.gov/havo/planyourvisit/index.htm', null, 'Pacific/Honolulu', now()),
  ('Wahinekapu — Steam Vents', 'wahinekapu-steam-vents', 'roadside-oddities', 19.4314, -155.26734, 'Volcano', 'HI', 'Rainwater sinks into hot volcanic ground and returns as visible steam along the rim of Kaluapele. The vents demonstrate how close residual heat remains to the surface; stay on marked paths because thin crust, hot ground, and volcanic gases are real hazards.', 'limited', 'https://www.nps.gov/havo/learn/nature/steam-vents.htm', null, 'Pacific/Honolulu', now()),
  ('Haʻakulamanu — Sulphur Banks', 'haakulamanu-sulphur-banks', 'roadside-oddities', 19.43349, -155.26136, 'Volcano', 'HI', 'A boardwalk crosses a hydrothermal area stained yellow and white by sulfur minerals while steam and volcanic gases rise from fractures. The landscape can smell strongly of sulfur dioxide and hydrogen sulfide; people with respiratory or heart conditions should follow park health guidance.', 'limited', 'https://www.nps.gov/havo/learn/nature/steam-vents.htm', null, 'Pacific/Honolulu', now()),
  ('Kīlauea Iki Crater', 'kilauea-iki-crater', 'roadside-oddities', 19.41692, -155.24291, 'Volcano', 'HI', 'A trail descends onto the solidified lava lake created by the spectacular 1959 Kīlauea Iki eruption, where hikers cross a crater floor that was once molten. The route is steep and exposed in places, and parking at the overlook is limited.', 'limited', 'https://www.nps.gov/havo/planyourvisit/hike_day_kilaueaiki.htm', null, 'Pacific/Honolulu', now()),
  ('Nāhuku — Thurston Lava Tube', 'nahuku-thurston-lava-tube', 'roadside-oddities', 19.41372, -155.23902, 'Volcano', 'HI', 'A forest trail drops into a large lava tube formed when the surface of a lava flow cooled while molten rock continued moving beneath it. The illuminated main passage is managed for visitors, but rain, lighting, and park closures can affect access.', 'limited', 'https://www.nps.gov/havo/learn/nature/lava-tubes.htm', null, 'Pacific/Honolulu', now()),
  ('Devastation Trail', 'devastation-trail', 'roadside-oddities', 19.40604, -155.25298, 'Volcano', 'HI', 'A short trail crosses the stark cinder and recovering landscape produced by the 1959 Kīlauea Iki eruption. The contrast between blasted volcanic deposits and returning vegetation makes it a compact stop for seeing ecological recovery directly beside an eruptive vent area.', 'limited', 'https://www.nps.gov/havo/planyourvisit/hikes_day.htm', null, 'Pacific/Honolulu', now()),
  ('Mauna Ulu Lava Fields', 'mauna-ulu-lava-fields', 'roadside-oddities', 19.36506, -155.21557, 'Volcano', 'HI', 'The Mauna Ulu eruption of 1969–1974 created broad young lava fields, craters, tree molds, and a shield vent along Chain of Craters Road. Trails cross sharp, exposed lava with little shade, so route users only to established NPS trailheads and marked paths.', 'limited', 'https://www.nps.gov/havo/planyourvisit/hikes_day.htm', null, 'Pacific/Honolulu', now()),
  ('Puʻuloa Petroglyphs', 'puuloa-petroglyphs', 'weird-history', 19.29271, -155.12205, 'Volcano', 'HI', 'More than 20,000 documented petroglyph images and cupules cover lava surfaces at Puʻuloa, making it one of Hawaiʻi''s largest petroglyph concentrations. A boardwalk protects the densest field; never leave the walkway, touch carvings, make rubbings, or add marks.', 'limited', 'https://www.nps.gov/places/stop-4-puuloa-petroglyphs.htm', null, 'Pacific/Honolulu', now()),
  ('Hōlei Sea Arch', 'holei-sea-arch', 'roadside-oddities', 19.29452, -155.09793, 'Volcano', 'HI', 'A large sea arch carved into a lava cliff is visible near the coastal end of Chain of Craters Road. The coastline is actively eroding and the arch will eventually collapse; visitors should remain at the established viewpoint and away from unstable cliff edges.', 'roadside', 'https://www.nps.gov/havo/planyourvisit/index.htm', null, 'Pacific/Honolulu', now()),
  ('1790 Footprints — Kaʻū Desert Trail', '1790-footprints-kau-desert-trail', 'weird-history', 19.36806, -155.36694, 'Volcano', 'HI', 'A trail from Highway 11 leads toward human footprints preserved in ash from an explosive 1790 Kīlauea eruption, traditionally connected with people traveling during conflict involving Keōua Kuahuʻula''s forces. Volcanic activity and gas can close the route, so verify NPS conditions before hiking.', 'limited', 'https://www.nps.gov/havo/planyourvisit/hikes_day.htm', null, 'Pacific/Honolulu', now()),
  ('Puʻuhonua o Hōnaunau National Historical Park', 'puuhonua-o-honaunau-national-historical-park', 'weird-history', 19.42152, -155.9104, 'Hōnaunau-Nāpōʻopoʻo', 'HI', 'Massive stone walls, reconstructed structures, royal grounds, and a traditional place of refuge preserve one of Hawaiʻi''s most important cultural landscapes. The park is a living sacred place as well as an archaeological site; follow NPS rules and avoid climbing or touching structures.', 'limited', 'https://www.nps.gov/puho/', null, 'Pacific/Honolulu', now()),
  ('Kaloko-Honokōhau National Historical Park — Petroglyph and Village Landscape', 'kaloko-honokohau-national-historical-park-petroglyph-and-village-landscape', 'weird-history', 19.68083, -156.03069, 'Kailua-Kona', 'HI', 'Trails connect lava fields, petroglyphs, house sites, fishponds, and coastal wetlands that preserve a traditional Hawaiian settlement landscape inside modern Kona. Heat and rough lava can make short-looking distances difficult, and archaeological features must remain untouched.', 'limited', 'https://www.nps.gov/kaho/planyourvisit/placestogo.htm', null, 'Pacific/Honolulu', now()),
  ('Kaloko Fishpond', 'kaloko-fishpond', 'weird-history', 19.68817, -156.03302, 'Kailua-Kona', 'HI', 'A massive stone seawall encloses this traditional fishpond at Kaloko-Honokōhau, demonstrating sophisticated Native Hawaiian aquaculture on a wave-exposed coast. The structure is cultural property and habitat rather than a swimming enclosure; use designated park trails and viewing areas.', 'limited', 'https://www.nps.gov/kaho/planyourvisit/placestogo.htm', null, 'Pacific/Honolulu', now()),
  ('ʻAimakapā Fishpond', 'aimakapa-fishpond', 'weird-history', 19.67772, -156.02581, 'Kailua-Kona', 'HI', 'This brackish coastal pond is another major surviving component of the Kaloko-Honokōhau settlement system and now supports native and migratory birds. Its archaeological, ecological, and hydrologic functions overlap in one landscape; remain on public park routes and out of sensitive habitat.', 'limited', 'https://www.nps.gov/kaho/planyourvisit/placestogo.htm', null, 'Pacific/Honolulu', now()),
  ('Puʻukoholā Heiau', 'puukohola-heiau', 'weird-history', 20.02729, -155.82154, 'Kawaihae', 'HI', 'Kamehameha I ordered construction of this massive war temple in the late eighteenth century as he pursued control of the Hawaiian Islands. The stone platform dominates Kawaihae Bay and remains sacred; visitors view it from designated paths rather than entering or climbing the heiau.', 'limited', 'https://www.nps.gov/places/puukohola-heiau.htm', null, 'Pacific/Honolulu', now()),
  ('Mailekini Heiau', 'mailekini-heiau', 'weird-history', 20.02785, -155.82236, 'Kawaihae', 'HI', 'Older than nearby Puʻukoholā, Mailekini was later adapted during the period of Western contact and at one point associated with mounted cannon. Its layered use makes the ruins an unusual intersection of traditional Hawaiian sacred architecture and changing military technology.', 'limited', 'https://www.nps.gov/puhe/learn/historyculture/places.htm', null, 'Pacific/Honolulu', now()),
  ('Pelekane Royal Courtyard', 'pelekane-royal-courtyard', 'weird-history', 20.02835, -155.82324, 'Kawaihae', 'HI', 'The shoreline below Puʻukoholā preserves Pelekane, a royal residential and ceremonial area tied to Kamehameha I''s court. It should be understood as part of the larger sacred landscape rather than simply a beach; follow NPS cultural-site guidance.', 'limited', 'https://www.nps.gov/places/pelekane.htm', null, 'Pacific/Honolulu', now()),
  ('John Young Homestead Site', 'john-young-homestead-site', 'weird-history', 20.03019, -155.81878, 'Kawaihae', 'HI', 'The remains of the homestead of John Young, a British sailor who became a trusted adviser to Kamehameha I, sit within Puʻukoholā Heiau National Historic Site. His life embodies the rapid fusion of Hawaiian politics with imported firearms, ships, and military knowledge.', 'limited', 'https://home.nps.gov/places/john-young-homestead.htm', null, 'Pacific/Honolulu', now()),
  ('Lapakahi State Historical Park', 'lapakahi-state-historical-park', 'weird-history', 20.17488, -155.89559, 'Kapaʻau', 'HI', 'Ruins of a coastal Hawaiian fishing settlement stretch across dry lava near North Kohala, with house sites, walls, shrines, and interpretive stations along a trail. The exposed archaeological landscape is fragile; stay on designated paths and do not stack or move stones.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/hawaii/lapakahi-state-historical-park/', null, 'Pacific/Honolulu', now()),
  ('Moʻokini Heiau', 'mookini-heiau', 'weird-history', 20.25765, -155.87705, 'Hāwī', 'HI', 'One of Hawaiʻi''s oldest and most significant heiau stands near the island''s northern tip in a remote, windswept landscape. Access can involve rough roads, gates, and long walking; verify lawful current access and approach the temple with cultural respect rather than as an abandoned ruin.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/hawaii/kohala-historical-sites-state-monument/', null, 'Pacific/Honolulu', now()),
  ('Kamehameha I Birthsite Memorial', 'kamehameha-i-birthsite-memorial', 'weird-history', 20.25889, -155.88583, 'Hāwī', 'HI', 'A remote monument near Upolu Point marks the traditional birthplace of Kamehameha I. The site is part of the Kohala historical landscape near Moʻokini Heiau, and access can be rough-road dependent; use official directions and never cross gates or private land without permission.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/hawaii/kohala-historical-sites-state-monument/', null, 'Pacific/Honolulu', now()),
  ('Captain Cook Monument at Kealakekua Bay', 'captain-cook-monument-at-kealakekua-bay', 'weird-history', 19.48127, -155.93346, 'Captain Cook', 'HI', 'A white obelisk marks the area where British explorer James Cook was killed in 1779 after relations with Hawaiians deteriorated. The monument is not directly reachable by road; visitors arrive by a strenuous trail or lawful water access and should understand the surrounding bay as a significant Hawaiian cultural landscape.', 'limited', 'https://dlnr.hawaii.gov/dsp/parks/hawaii/kealakekua-bay-state-historical-park/', null, 'Pacific/Honolulu', now()),
  ('Huliheʻe Palace', 'hulihee-palace', 'weird-history', 19.63933, -155.99436, 'Kailua-Kona', 'HI', 'This seaside royal residence preserves koa furniture, portraits, featherwork, quilts, and other objects associated with Hawaiʻi''s monarchy. The Daughters of Hawaiʻi operate it as a museum with scheduled hours, making it one of the island''s strongest surviving royal interiors.', 'limited', 'https://daughtersofhawaii.org/', null, 'Pacific/Honolulu', now()),
  ('Ahuʻena Heiau', 'ahuena-heiau', 'weird-history', 19.63889, -155.99738, 'Kailua-Kona', 'HI', 'The reconstructed heiau at Kamakahonu is closely associated with Kamehameha I''s final years and the political center he established at Kailua-Kona. The temple itself is sacred and not a walk-through attraction; view it only from lawful public areas and follow stewardship guidance.', 'roadside', 'https://www.ahuena-heiau.org/', null, 'Pacific/Honolulu', now()),
  ('Mokuʻaikaua Church', 'mokuaikaua-church', 'weird-history', 19.6425, -155.99667, 'Kailua-Kona', 'HI', 'The congregation traces its history to the first company of Protestant missionaries in Hawaiʻi, and the present stone church is one of Kona''s most recognizable nineteenth-century buildings. It remains an active place of worship, so interior access depends on current church hours and services.', 'limited', 'https://www.gohawaii.com/islands/hawaii-big-island/things-to-do/land-activities/historic-places', null, 'Pacific/Honolulu', now()),
  ('Kona Coffee Living History Farm', 'kona-coffee-living-history-farm', 'weird-history', 19.49074, -155.91388, 'Captain Cook', 'HI', 'A working historic coffee farm interprets the lives of Kona''s immigrant farming families through a preserved farmhouse, coffee trees, tools, and demonstrations. The site turns an everyday agricultural landscape into a highly specific living-history experience rather than a simple coffee tasting stop.', 'limited', 'https://konahistorical.org/kona-coffee-living-history-farm', null, 'Pacific/Honolulu', now()),
  ('St. Benedict''s Painted Church', 'st-benedicts-painted-church', 'roadside-oddities', 19.43507, -155.88831, 'Captain Cook', 'HI', 'The small Catholic church is famous for interior murals painted by Belgian missionary Father John Velghe to teach biblical stories visually to parishioners. It remains an active church and cemetery setting, so visitors should enter only when permitted and avoid disrupting worship.', 'limited', 'https://www.gohawaii.com/islands/hawaii-big-island/things-to-do/land-activities/historic-places', null, 'Pacific/Honolulu', now()),
  ('Puakō Petroglyph Archaeological Preserve', 'puako-petroglyph-archaeological-preserve', 'weird-history', 19.95442, -155.85592, 'Puakō', 'HI', 'A trail through dry lava leads to thousands of kiʻi pōhaku, including human figures and repeated geometric forms. The carvings are easily damaged by touching, tracing, chalking, or walking over them; remain on the designated route and treat the field as protected cultural material.', 'limited', 'https://www.gohawaii.com/islands/hawaii-big-island/regions/kohala/puako-petroglyph-archeological-preserve', null, 'Pacific/Honolulu', now()),
  ('Waikōloa Petroglyph Preserve', 'waikoloa-petroglyph-preserve', 'weird-history', 19.91723, -155.87981, 'Waikōloa', 'HI', 'Ancient trails and petroglyph fields survive unexpectedly among the modern Waikōloa resort area, with carvings cut into dark lava just beyond shopping and hotel development. Stay on marked trails and do not add modern scratches to the rock.', 'limited', 'https://www.waikoloabeachresort.com/', null, 'Pacific/Honolulu', now()),
  ('Maunakea Visitor Information Station', 'maunakea-visitor-information-station', 'roadside-oddities', 19.75917, -155.45611, 'Hilo', 'HI', 'At roughly 9,200 feet, the visitor station sits below one of the world''s most important astronomical summit complexes. Altitude, rapidly changing weather, cultural concerns, and summit-road restrictions all matter; the visitor station is the appropriate public orientation point rather than an automatic route to observatories.', 'limited', 'https://hilo.hawaii.edu/maunakea/visitor-information/station', null, 'Pacific/Honolulu', now()),
  ('ʻImiloa Astronomy Center', 'imiloa-astronomy-center', 'roadside-oddities', 19.70082, -155.08889, 'Hilo', 'HI', 'ʻImiloa deliberately connects modern astronomy on Maunakea with Hawaiian wayfinding, language, and traditional knowledge. Planetarium programs and exhibits make it one of the rare science museums where celestial navigation and contemporary telescope research are interpreted together.', 'open', 'https://imiloahawaii.org/', null, 'Pacific/Honolulu', now()),
  ('Pacific Tsunami Museum', 'pacific-tsunami-museum', 'weird-history', 19.72593, -155.08673, 'Hilo', 'HI', 'Hilo''s museum documents destructive Pacific tsunamis, especially the 1946 and 1960 disasters that reshaped the city''s waterfront. Survivor accounts, warning science, maps, and photographs make it a concentrated archive of a hazard that remains central to life across the islands.', 'open', 'https://tsunami.org/', null, 'Pacific/Honolulu', now()),
  ('Mokupāpapa Discovery Center', 'mokupapapa-discovery-center', 'museums', 19.72668, -155.08701, 'Hilo', 'HI', 'NOAA''s discovery center interprets Papahānaumokuākea, the vast protected Northwestern Hawaiian Islands that most visitors can never legally see. Marine specimens, deep-ocean science, Native Hawaiian cultural interpretation, and remote-island imagery turn an inaccessible archipelago into a public museum experience.', 'open', 'https://www.papahanaumokuakea.gov/mdc/', null, 'Pacific/Honolulu', now()),
  ('Lyman Museum and Mission House', 'lyman-museum-and-mission-house', 'museums', 19.72208, -155.09071, 'Hilo', 'HI', 'A 1930s museum and an 1839 mission house share one Hilo site, combining volcanic geology, shells, minerals, Hawaiian artifacts, art, and missionary history. The dense natural-history collections and preserved domestic building make it far stranger than a standard town museum.', 'limited', 'https://www.lymanmuseum.org/', null, 'Pacific/Honolulu', now()),
  ('Naha Stone', 'naha-stone', 'folklore', 19.72445, -155.09055, 'Hilo', 'HI', 'A large sacred stone displayed outside Hilo Public Library is tied to chiefly genealogy and to the tradition that a young Kamehameha moved the stone, fulfilling a prophecy of future power. It should be treated as a cultural object, not climbed on or handled for photographs.', 'open', 'https://www.librarieshawaii.org/branch/hilo-public-library/', null, 'Pacific/Honolulu', now()),
  ('Hilo Tsunami Clock', 'hilo-tsunami-clock', 'weird-history', 19.72257, -155.06762, 'Hilo', 'HI', 'A damaged public clock was preserved because it stopped during the devastating April 1, 1946 tsunami, becoming a compact memorial to the disaster and the destruction of Hilo''s waterfront. Pair the stop with the Pacific Tsunami Museum for the historical context behind the object.', 'roadside', 'https://tsunami.org/', null, 'Pacific/Honolulu', now()),
  ('Kaumana Caves', 'kaumana-caves', 'roadside-oddities', 19.6868, -155.13068, 'Hilo', 'HI', 'A county park stairway descends into a lava tube created by the 1881 Mauna Loa flow. Only the publicly accessible sections should be explored; passages extend beneath mixed ownership, lighting is absent, footing is rough, and flashlights and head protection are sensible.', 'limited', 'https://www.hawaiicounty.gov/departments/parks-recreation', null, 'Pacific/Honolulu', now()),
  ('Rainbow Falls — Waiānuenue', 'rainbow-falls-waianuenue', 'folklore', 19.71947, -155.10962, 'Hilo', 'HI', 'The Wailuku River drops over a broad lava ledge into a large plunge pool and cave traditionally associated with Hina, mother of the demigod Māui. The falls are easily viewed from a county park overlook, but river flow can become dangerous after heavy rain.', 'open', 'https://www.hawaiicounty.gov/departments/parks-recreation', null, 'Pacific/Honolulu', now()),
  ('Boiling Pots — Wailuku River', 'boiling-pots-wailuku-river', 'roadside-oddities', 19.71539, -155.13056, 'Hilo', 'HI', 'A series of lava-carved pools, channels, and submerged tubes makes floodwater churn as if the river were boiling. The same geology that creates the visual effect also makes the site dangerous; admire it from established overlooks and never enter the river during high flow.', 'open', 'https://hilo.hawaii.edu/news/kekalahea/where-to-go-in-hilo-boiling-pots', null, 'Pacific/Honolulu', now()),
  ('Lava Tree State Monument', 'lava-tree-state-monument', 'roadside-oddities', 19.48639, -154.90472, 'Pāhoa', 'HI', 'Tree trunks surrounded by a fast-moving nineteenth-century lava flow left behind hollow lava molds after the wood burned or decayed away. A short loop passes clusters of these strange upright forms, making volcanic processes visible at human scale.', 'open', 'https://dlnr.hawaii.gov/dsp/parks/hawaii/lava-tree-state-monument/', null, 'Pacific/Honolulu', now()),
  ('Kalaupapa Peninsula Overlook at Pālāʻau State Park', 'kalaupapa-peninsula-overlook-at-palaau-state-park', 'weird-history', 21.17695, -157.00513, 'Hoʻolehua', 'HI', 'A cliff-top overlook looks roughly 1,600 feet down onto the isolated Kalaupapa Peninsula and includes interpretation of the settlement created for people with Hansen''s disease. General entry to Kalaupapa itself remains restricted and permit-based; the overlook is the appropriate no-permit perspective for most travelers.', 'open', 'https://www.nps.gov/places/kalapeninsulaoverlook.htm', null, 'Pacific/Honolulu', now()),
  ('Kauleonanahoa — Phallic Rock', 'kauleonanahoa-phallic-rock', 'folklore', 21.17543, -157.00778, 'Hoʻolehua', 'HI', 'A naturally shaped and partly worked stone near the Kalaupapa overlook has long been associated with fertility traditions and the figure Nanahoa. It is a sacred cultural feature within the Pālāʻau landscape, so visitors should observe respectfully and avoid touching, climbing, or leaving objects.', 'limited', 'https://visitmolokai.com/wp/faq-items/what-can-you-tell-me-about-the-phallic-rock/', null, 'Pacific/Honolulu', now()),
  ('Molokaʻi Museum & Cultural Center and R.W. Meyer Sugar Mill', 'molokai-museum-cultural-center-and-r-w-meyer-sugar-mill', 'museums', 21.15622, -157.03996, 'Kualapuʻu', 'HI', 'This small museum pairs island history with a restored nineteenth-century sugar mill, including a mule-driven cane crusher, steam machinery, plantation furnishings, and material related to Kalaupapa. Limited island operating hours make it a check-ahead stop.', 'limited', 'https://www.gohawaii.com/islands/molokai/things-to-do/land-activities/molokai-museum', null, 'Pacific/Honolulu', now()),
  ('Kapuāiwa Coconut Grove', 'kapuaiwa-coconut-grove', 'weird-history', 21.09726, -157.03805, 'Kaunakakai', 'HI', 'Hundreds of coconut palms planted during the reign of Kamehameha V form one of Molokaʻi''s most recognizable royal-era landscapes. The grove is Department of Hawaiian Home Lands property and falling coconuts are hazardous; GoHawaii specifically recommends viewing from the grassy roadside area rather than entering.', 'roadside', 'https://www.gohawaii.com/islands/molokai/regions/central-molokai/kapuaiwa-coconut-grove', null, 'Pacific/Honolulu', now()),
  ('Hālawa Valley', 'halawa-valley', 'weird-history', 21.1571, -156.73791, 'Hālawa', 'HI', 'One of Molokaʻi''s oldest continuously inhabited cultural landscapes contains taro lands, archaeological sites, waterfalls, and family-owned property deep in a dramatic valley. The hiking route crosses private land and should be entered only with an authorized local guide or explicit permission.', 'limited', 'https://www.gohawaii.com/islands/molokai/regions/east-end/halawa-valley', null, 'Pacific/Honolulu', now()),
  ('Keahiakawelo — Garden of the Gods', 'keahiakawelo-garden-of-the-gods', 'roadside-oddities', 20.8819, -156.9978, 'Lānaʻi City', 'HI', 'Wind and erosion have exposed a barren field of red, orange, and purple rock towers and boulders in northwestern Lānaʻi. The remote road is rough and conditions can shift after rain; this is a landscape stop for suitable vehicles, not a place to drive off established routes.', 'limited', 'https://www.gohawaii.com/islands/lanai/things-to-do/land-activities/historic-places', null, 'Pacific/Honolulu', now()),
  ('Kaunolū Village Site', 'kaunolu-village-site', 'weird-history', 20.73472, -156.96444, 'Lānaʻi City', 'HI', 'The ruins of a large traditional Hawaiian fishing village preserve house platforms, Halulu Heiau, walls, and other structures across Lānaʻi''s dry south coast. Remote-road access and the site''s archaeological and sacred importance require conservative routing and no disturbance of stones or features.', 'limited', 'https://www.gohawaii.com/islands/lanai/things-to-do/land-activities/historic-places', null, 'Pacific/Honolulu', now()),
  ('Puʻu Pehe — Sweetheart Rock', 'puu-pehe-sweetheart-rock', 'folklore', 20.73415, -156.89021, 'Lānaʻi City', 'HI', 'A sea stack between Mānele and Hulopoʻe is associated with a well-known tragic Hawaiian legend about Pehe and her lover Makakehau. The view is reached by a short coastal trail, but cliff edges and waves require caution; the offshore archaeological platform itself is not a casual climbing destination.', 'limited', 'https://www.gohawaii.com/islands/lanai/things-to-do/land-activities/historic-places', null, 'Pacific/Honolulu', now()),
  ('Kaiolohia — Shipwreck Beach', 'kaiolohia-shipwreck-beach', 'roadside-oddities', 20.91739, -156.90864, 'Lānaʻi City', 'HI', 'The rusting hulk of a World War II-era concrete-hulled vessel sits offshore from Lānaʻi''s north coast, giving Kaiolohia its modern Shipwreck Beach name. Reaching the area generally requires high-clearance or four-wheel-drive travel, and strong currents make it unsuitable for swimming.', 'limited', 'https://www.gohawaii.com/islands/lanai/regions/north-lanai/kaiolohia', null, 'Pacific/Honolulu', now()),
  ('Lānaʻi Culture & Heritage Center', 'lanai-culture-heritage-center', 'museums', 20.82508, -156.91747, 'Lānaʻi City', 'HI', 'A community-run museum in the old Dole Administration Building preserves archaeology, oral history, plantation-era material, natural history, and Native Hawaiian culture from an island where many historic places are remote or access-sensitive. Posted weekday hours are limited, so verify before visiting.', 'limited', 'https://lanaichc.org/', null, 'Pacific/Honolulu', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;

select count(*) as hawaii from public.stops where state = 'HI';
