-- Idaho. The state had two stops, one of which is in this batch.
--
-- Third state to need two timezones, and the only one split by a river rather
-- than a meridian: the ten northern counties keep Pacific time and everything
-- south of the Salmon River is Mountain. Coeur d'Alene and Moscow on one side,
-- Salmon itself on the other.
--
-- Excellently sourced — nps.gov, parksandrecreation.idaho.gov and
-- visitidaho.org are the top three, with no aggregators near the top.
--
-- Three dropped. The penitentiary was already here. The Shoshone Bird Museum
-- and the Richard Arthur Olsen Museum both sit at exactly zero metres from
-- Idaho's Mammoth Cave, being the cave's own collections rather than separate
-- destinations, and three pins on one point is worse than one.
--
-- Two renamed. Kingfield, Maine holds stanley-museum for the Stanley Steamer
-- family, so Idaho's goes in as stanley-museum-idaho. Balanced Rock is now the
-- third in the index after Baraboo and Big Bend, so it carries its town.
--
-- The parser learned two things here. Compound categories arrive with a slash
-- — "memorial / mining history" — and so does one access value, "open /
-- seasonal"; the first half is taken in both. And one access read "limited —
-- verify reopening", where the caveat belongs in the description rather than
-- the enum.
--
-- 127 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Center of the Universe', 'center-of-the-universe', 'roadside-oddities', 47.4716, -115.92391, 'Wallace', 'ID', 'At the intersection of Bank and Sixth streets, Wallace marks itself as the Center of the Universe, a deliberately tongue-in-cheek civic landmark that fits OddWay almost perfectly. The marker is in the public street intersection; view it from the surrounding sidewalks and crosswalks.', 'open', 'https://www.wallaceid.fun/places/united-states/idaho/wallace/history-heritage/center-of-the-universe-wallace-idaho/', null, 'America/Los_Angeles', now()),
  ('Oasis Bordello Museum', 'oasis-bordello-museum', 'museums', 47.47266, -115.92348, 'Wallace', 'ID', 'A preserved former bordello whose rooms and objects document Wallace''s once-open red-light history. It operates as a guided historic museum rather than as a recreated attraction.', 'limited', 'https://visitnorthidaho.com/activity/oasis-bordello-museum/', null, 'America/Los_Angeles', now()),
  ('Sierra Silver Mine Tour', 'sierra-silver-mine-tour', 'weird-history', 47.47161, -115.9257, 'Wallace', 'ID', 'A guided underground mining experience reached from downtown Wallace, with retired miners interpreting drilling, blasting and Silver Valley mining work. Tours are seasonal and ticketed.', 'limited', 'https://silverminetour.org/take-the-mine-tour/', null, 'America/Los_Angeles', now()),
  ('Wallace District Mining Museum', 'wallace-district-mining-museum', 'museums', 47.47184, -115.92485, 'Wallace', 'ID', 'Downtown museum devoted to the people, machinery, disasters and mineral wealth of the Coeur d''Alene Mining District. It is a useful companion stop before exploring the rest of the Silver Valley.', 'limited', 'https://www.wallaceid.fun/places/united-states/idaho/wallace/arts-culture-entertainment/wallace-district-mining-museum/', null, 'America/Los_Angeles', now()),
  ('Northern Pacific Railroad Depot Museum', 'northern-pacific-railroad-depot-museum', 'museums', 47.47165, -115.92392, 'Wallace', 'ID', 'Wallace''s restored Northern Pacific depot preserves the railroad story of a mining town that famously moved the building to make way for Interstate 90. Interior access follows museum hours.', 'limited', 'https://npdepot.org/about-the-museum/', null, 'America/Los_Angeles', now()),
  ('Mine Heritage Exhibition', 'mine-heritage-exhibition', 'weird-history', 47.47873, -115.9343, 'Wallace', 'ID', 'An outdoor display of large-scale mining equipment and machinery near Wallace''s visitor area. It works well as a quick, visible stop for travelers who do not have time for a full mine tour.', 'open', 'https://www.wallaceid.fun/places/united-states/idaho/wallace/attractions-museums-destinations/mine-heritage-exhibition/', null, 'America/Los_Angeles', now()),
  ('Sunshine Mine Disaster Memorial', 'sunshine-mine-disaster-memorial', 'weird-history', 47.52826, -116.04794, 'Kellogg', 'ID', 'Memorial to the 91 miners killed in the 1972 Sunshine Mine fire, one of the deadliest hard-rock mining disasters in U.S. history. Treat the site as a memorial rather than a paranormal attraction.', 'roadside', 'https://www.lib.uidaho.edu/digital/postcards/items/nwpostcards1585.html', null, 'America/Los_Angeles', now()),
  ('Crystal Gold Mine', 'crystal-gold-mine', 'weird-history', 47.5323, -116.09206, 'Kellogg', 'ID', 'A preserved 1880s gold mine that offers guided underground tours rather than access to an abandoned portal. This is one of Idaho''s safer ways to experience an authentic historic mine environment.', 'limited', 'https://www.goldmine-idaho.com/', null, 'America/Los_Angeles', now()),
  ('Captain John Mullan Museum', 'captain-john-mullan-museum', 'museums', 47.47066, -115.8004, 'Mullan', 'ID', 'Small museum interpreting Captain John Mullan, the Mullan Road and the mining and community history of Idaho''s eastern Silver Valley. Check operating dates before routing around it.', 'limited', 'https://mullanmuseum.org/', null, 'America/Los_Angeles', now()),
  ('Burke Ghost Town', 'burke-ghost-town', 'weird-history', 47.5209, -115.81667, 'Burke', 'ID', 'Remnants of the famously narrow mining settlement of Burke line a public mountain road northeast of Wallace. Observe surviving structures from lawful public areas only; abandoned buildings and nearby parcels are not an invitation to enter.', 'roadside', 'https://visitidaho.org/travel-tips/boom-or-bust-exploring-idaho-ghost-towns/', null, 'America/Los_Angeles', now()),
  ('Elmer''s Fountain', 'elmers-fountain', 'roadside-oddities', 47.46066, -115.82306, 'Mullan', 'ID', 'A homemade assemblage of old mining and logging parts that sprays water into a whimsical roadside fountain. It is one of the Silver Valley''s stranger quick stops.', 'roadside', 'https://www.atlasobscura.com/places/elmers-fountain-mullan', null, 'America/Los_Angeles', now()),
  ('Shoshone County Mining & Smelting Museum', 'shoshone-county-mining-smelting-museum', 'museums', 47.53813, -116.12125, 'Kellogg', 'ID', 'Housed in the historic Bunker Hill Staff House, this museum covers mining, smelting, geology and community life across the Silver Valley. The museum is seasonal and may arrange special tours outside normal dates.', 'limited', 'https://miningandsmeltingmuseum.org/', null, 'America/Los_Angeles', now()),
  ('Coeur d''Alene''s Old Mission State Park', 'coeur-dalenes-old-mission-state-park', 'weird-history', 47.5487, -116.3582, 'Cataldo', 'ID', 'The Cataldo Mission is the oldest standing building in Idaho and anchors a state park interpreting the meeting of Jesuit missionaries and Coeur d''Alene people. Use the designated museum, grounds and park routes.', 'limited', 'https://parksandrecreation.idaho.gov/state-park/coeur-dalenes-old-mission-state-park/', null, 'America/Los_Angeles', now()),
  ('Museum at the Brig', 'museum-at-the-brig', 'museums', 47.95139, -116.60222, 'Athol', 'ID', 'Farragut State Park preserves the brig from the enormous World War II Farragut Naval Training Station. The museum tells the unusual story of a naval base built deep in inland Idaho.', 'limited', 'https://visitidaho.org/things-to-do/museums-exhibits/museum-brig-farragut-state-park/', null, 'America/Los_Angeles', now()),
  ('Fort Sherman Chapel', 'fort-sherman-chapel', 'weird-history', 47.67645, -116.79458, 'Coeur d''Alene', 'ID', 'One of the surviving buildings of Fort Sherman, the U.S. Army post established on the shore of Lake Coeur d''Alene in the late 1800s. Interior availability varies, so treat it primarily as a historic exterior stop unless open.', 'limited', 'https://museumni.org/properties/', null, 'America/Los_Angeles', now()),
  ('Fort Sherman Powder Magazine', 'fort-sherman-powder-magazine', 'weird-history', 47.67727, -116.79761, 'Coeur d''Alene', 'ID', 'A surviving powder magazine from Fort Sherman, preserving a compact piece of the former army post. View only from permitted public access and follow Museum of North Idaho guidance for the historic properties.', 'limited', 'https://museumni.org/properties/', null, 'America/Los_Angeles', now()),
  ('Boundary County Museum', 'boundary-county-museum', 'museums', 48.69757, -116.31195, 'Bonners Ferry', 'ID', 'Museum covering Boundary County railroads, logging, mining, pioneer life and the communities along Idaho''s far northern border. Check hours before making it a primary route stop.', 'limited', 'https://boundarycountymuseum.org/about/our-museum', null, 'America/Los_Angeles', now()),
  ('Bonner County Historical Museum', 'bonner-county-historical-museum', 'museums', 48.31794, -116.51522, 'Sandpoint', 'ID', 'Sandpoint museum with material on logging, railroads, lake travel and settlement around Lake Pend Oreille. The collection gives context to the region''s more unusual industrial and transportation history.', 'limited', 'https://visitnorthidaho.com/activity/bonner-county-historical-museum/', null, 'America/Los_Angeles', now()),
  ('Priest Lake Museum', 'priest-lake-museum', 'museums', 48.54151, -116.92602, 'Priest Lake', 'ID', 'Small seasonal museum devoted to logging, settlement, recreation and life around remote Priest Lake. It is useful for visitors exploring the folklore-rich forests of Idaho''s northern tip without routing to unverified wilderness pins.', 'limited', 'https://visitnorthidaho.com/activity/priest-lake-museum/', null, 'America/Los_Angeles', now()),
  ('Appaloosa Museum & Heritage Center', 'appaloosa-museum-heritage-center', 'museums', 46.73313, -117.0391, 'Moscow', 'ID', 'Museum dedicated to the Appaloosa horse, including its strong historical association with the Nez Perce people and the breed''s modern development. A distinctive regional stop rather than a generic local museum.', 'limited', 'https://www.lib.uidaho.edu/digital/latahsites/items/latahsites0075.html', null, 'America/Los_Angeles', now()),
  ('Historical Museum at St. Gertrude', 'historical-museum-at-st-gertrude', 'weird-history', 46.05374, -116.35338, 'Cottonwood', 'ID', 'A large collection at the Monastery of St. Gertrude covering regional history, religious life, artifacts and settlement of north-central Idaho. Visit only during public museum hours and respect the active monastery setting.', 'limited', 'https://historicalmuseumatstgertrude.org/', null, 'America/Los_Angeles', now()),
  ('J. Howard Bradbury Memorial Logging Museum', 'j-howard-bradbury-memorial-logging-museum', 'museums', 46.491, -115.7999, 'Pierce', 'ID', 'A community museum focused on the machinery, tools and people of Idaho''s logging country. Pierce''s timber and gold-rush history make it a good northern backcountry-history stop.', 'limited', 'https://www.lewisandclark.travel/listing/j-howard-bradbury-memorial-logging-museum/', null, 'America/Los_Angeles', now()),
  ('Pierce Courthouse', 'pierce-courthouse', 'weird-history', 46.49021, -115.79812, 'Pierce', 'ID', 'An 1862 courthouse associated with the early Idaho gold rush and one of the state''s oldest surviving public buildings. Use the designated historic-site access rather than treating nearby private buildings as part of the attraction.', 'limited', 'https://www.nps.gov/places/pierce-courthouse.htm', null, 'America/Los_Angeles', now()),
  ('Pulaski Tunnel Trail', 'pulaski-tunnel-trail', 'weird-history', 47.4592, -115.93512, 'Wallace', 'ID', 'Trail following the escape route of firefighter Ed Pulaski and his crew during the Great Fire of 1910, ending near the mine tunnel where they sheltered. Snow and mountain conditions can make access seasonal.', 'limited', 'https://www.wallaceid.fun/summer/', null, 'America/Los_Angeles', now()),
  ('Nez Perce County Historical Society Museum', 'nez-perce-county-historical-society-museum', 'museums', 46.4228, -117.029, 'Lewiston', 'ID', 'Museum on the Lewiston riverfront interpreting local transportation, settlement and community history. It pairs well with the area''s Lewis and Clark and Nez Perce history without routing visitors to sensitive sites.', 'limited', 'https://www.nezpercecountymuseum.com/', null, 'America/Los_Angeles', now()),
  ('Lewis & Clark Discovery Center', 'lewis-clark-discovery-center', 'weird-history', 46.3683, -117.0577, 'Lewiston', 'ID', 'Interpretive center at Hells Gate State Park focused on the Corps of Discovery and the Snake-Clearwater river corridor. Public park access makes it a reliable route stop.', 'limited', 'https://www.lewisandclark.travel/listing/hells-gate-state-park-lewis-and-clark-discovery-center/', null, 'America/Los_Angeles', now()),
  ('Jack O''Connor Hunting Heritage & Education Center', 'jack-oconnor-hunting-heritage-education-center', 'museums', 46.36917, -117.05444, 'Lewiston', 'ID', 'Center devoted to outdoor writer and hunter Jack O''Connor, with firearms, trophies and conservation-oriented interpretation. It is located within the Hells Gate State Park complex; follow park signs from the mapped campus point.', 'limited', 'https://jack-oconnor.org/center-info/', null, 'America/Los_Angeles', now()),
  ('Dworshak Dam Visitor Center', 'dworshak-dam-visitor-center', 'roadside-oddities', 46.51897, -116.30071, 'Ahsahka', 'ID', 'Visitor center overlooking one of the tallest straight-axis concrete gravity dams in North America. Exhibits explain the huge Clearwater River engineering project and the reservoir behind it.', 'limited', 'https://www.nww.usace.army.mil/Locations/District-Locks-and-Dams/Dworshak-Dam-and-Reservoir/Dworshak-Visitor-Center/', null, 'America/Los_Angeles', now()),
  ('White Bird Battlefield', 'white-bird-battlefield', 'weird-history', 45.77922, -116.27684, 'White Bird', 'ID', 'National Park Service battlefield marking the opening battle of the 1877 Nez Perce War. Remain on designated public routes and interpretive areas; this is a serious historic landscape, not a ghost-hunting location.', 'open', 'https://www.nps.gov/places/white-bird-battlefield.htm', null, 'America/Los_Angeles', now()),
  ('Weippe Prairie', 'weippe-prairie', 'weird-history', 46.35004, -115.92509, 'Weippe', 'ID', 'Prairie landscape associated with the Lewis and Clark expedition''s encounter with the Nez Perce. The NPS notes that much of the prairie is private property, so OddWay should route users to public roads and signed viewpoints only.', 'roadside', 'https://www.nps.gov/nepe/planyourvisit/visit-weippe-prairie.htm', null, 'America/Los_Angeles', now()),
  ('Land of the Yankee Fork Interpretive Center', 'land-of-the-yankee-fork-interpretive-center', 'weird-history', 44.4755, -114.2106, 'Challis', 'ID', 'State park interpretive center that explains the Yankee Fork mining district before visitors head toward Custer, Bonanza and Bayhorse. This is the best orientation point for lawful ghost-town travel in the area.', 'limited', 'https://parksandrecreation.idaho.gov/state-park/land-of-the-yankee-fork-state-park/', null, 'America/Denver', now()),
  ('Bayhorse Ghost Town', 'bayhorse-ghost-town', 'weird-history', 44.39761, -114.31262, 'Bayhorse', 'ID', 'A state-managed mining ghost town with preserved kilns, buildings and mining remains. Use only the designated park roads and trails; seasonal mountain access can change.', 'limited', 'https://parksandrecreation.idaho.gov/state-park/land-of-the-yankee-fork-state-park/', null, 'America/Denver', now()),
  ('Custer Ghost Town', 'custer-ghost-town', 'weird-history', 44.3873, -114.6967, 'Custer', 'ID', 'Preserved Yankee Fork mining town with restored buildings and interpretation, managed as a public historic site. Road conditions and snow make the site strongly seasonal.', 'limited', 'https://parksandrecreation.idaho.gov/state-park/land-of-the-yankee-fork-state-park/', null, 'America/Denver', now()),
  ('Bonanza Ghost Town', 'bonanza-ghost-town', 'weird-history', 44.37128, -114.72835, 'Bonanza', 'ID', 'Historic mining settlement near Custer and the Yankee Fork dredge. Surviving structures sit in a mixed ownership landscape, so remain on signed public routes and do not enter buildings unless explicitly open.', 'limited', 'https://visitidaho.org/things-to-do/ghost-towns-mining-history/', null, 'America/Denver', now()),
  ('Yankee Fork Gold Dredge', 'yankee-fork-gold-dredge', 'weird-history', 44.37765, -114.72268, 'Custer', 'ID', 'Enormous floating bucket-line dredge preserved along the Yankee Fork, where it mechanically tore through river gravels for gold. Guided access is seasonal.', 'limited', 'https://yankeeforkdredge.com/', null, 'America/Denver', now()),
  ('Sunbeam Dam', 'sunbeam-dam', 'weird-history', 44.26797, -114.74035, 'Sunbeam', 'ID', 'Remains of an early hydroelectric dam blasted open to restore salmon passage on the Salmon River. The surviving concrete structure is visible from the highway corridor; use established pull-offs only.', 'roadside', 'https://parksandrecreation.idaho.gov/state-park/land-of-the-yankee-fork-state-park/', null, 'America/Denver', now()),
  ('Challis Hot Springs', 'challis-hot-springs', 'roadside-oddities', 44.52227, -114.17416, 'Challis', 'ID', 'A historic developed hot-springs property now incorporated into Land of the Yankee Fork State Park. Bathing and facility access follow current park rules and operating schedules.', 'limited', 'https://parksandrecreation.idaho.gov/state-park/land-of-the-yankee-fork-state-park/', null, 'America/Denver', now()),
  ('Mackay Mine Hill Tour', 'mackay-mine-hill-tour', 'weird-history', 43.88121, -113.67338, 'Mackay', 'ID', 'A signed backcountry driving and hiking route through old mines, aerial tramway remains, cabins and mining machinery above Mackay. High-clearance conditions and seasonal closures can apply; never enter mine openings.', 'limited', 'https://visitidaho.org/travel-tips/the-mackay-mine-hill-tour/', null, 'America/Denver', now()),
  ('Borah Peak Earthquake Interpretive Site', 'borah-peak-earthquake-interpretive-site', 'weird-history', 44.16394, -113.86843, 'Mackay', 'ID', 'Roadside interpretive area near the visible fault scarp created by the magnitude 6.9 Borah Peak earthquake of 1983. Stay on designated roads and interpretive access rather than crossing private ranch land.', 'limited', 'https://www.usgs.gov/programs/earthquake-hazards', null, 'America/Denver', now()),
  ('Gilmore Ghost Town', 'gilmore-ghost-town', 'weird-history', 44.45881, -113.26975, 'Gilmore', 'ID', 'Remains of a lead-silver mining settlement in the Lemhi Range. Ownership is mixed and many structures are not public attractions, so OddWay should treat Gilmore as a public-road viewing stop only.', 'roadside', 'https://visitidaho.org/things-to-do/ghost-towns-mining-history/', null, 'America/Denver', now()),
  ('Birch Creek Charcoal Kilns', 'birch-creek-charcoal-kilns', 'weird-history', 44.31062, -113.17958, 'Leadore', 'ID', 'Stone charcoal kilns built to supply fuel for regional smelters, standing as unusually intact industrial archaeology in Birch Creek Valley. Remote-road and winter conditions can affect access.', 'limited', 'https://www.loc.gov/pictures/item/id0093/', null, 'America/Denver', now()),
  ('Sacajawea Interpretive, Cultural & Educational Center', 'sacajawea-interpretive-cultural-educational-center', 'weird-history', 45.16568, -113.86571, 'Salmon', 'ID', 'Interpretive center near Sacajawea''s homeland focused on the Agaidika Shoshone-Bannock people and the Lewis and Clark expedition. Use the established center and trails rather than seeking sensitive cultural sites.', 'limited', 'https://www.sacajaweacenter.org/', null, 'America/Denver', now()),
  ('Stanley Museum', 'stanley-museum-idaho', 'museums', 44.22574, -114.92989, 'Stanley', 'ID', 'Historic ranger-station museum interpreting Stanley Basin mining, ranching, recreation and local life. Seasonal operation is typical in this high-elevation area.', 'limited', 'https://discoversawtooth.org/', null, 'America/Denver', now()),
  ('Hemingway Memorial', 'hemingway-memorial', 'weird-history', 43.71182, -114.34056, 'Sun Valley', 'ID', 'A stone memorial to Ernest Hemingway set beside Trail Creek, near the Idaho community where he spent his final years. Use the public memorial rather than routing to the writer''s grave or private former home.', 'open', 'https://www.atlasobscura.com/places/the-hemingway-memorial', null, 'America/Denver', now()),
  ('Experimental Breeder Reactor-I Atomic Museum', 'experimental-breeder-reactor-i-atomic-museum', 'museums', 43.51141, -113.00649, 'Arco', 'ID', 'National Historic Landmark where usable electricity was first generated from nuclear power and where visitors can see early reactor technology. The museum is seasonal and remains within a controlled federal complex.', 'limited', 'https://inl.gov/news-release/experimental-breeder-reactor-i-atomic-museum-opens-for-2026-season-75th-anniversary-approaches/', null, 'America/Denver', now()),
  ('Craters of the Moon Visitor Center', 'craters-of-the-moon-visitor-center', 'roadside-oddities', 43.46185, -113.56318, 'Arco', 'ID', 'Primary public orientation point for Craters of the Moon''s lava fields, cones and caves. Stop here for current road, trail and cave information before entering the monument loop.', 'limited', 'https://www.nps.gov/crmo/index.htm', null, 'America/Denver', now()),
  ('North Crater Flow Trail', 'north-crater-flow-trail', 'roadside-oddities', 43.45752, -113.559, 'Arco', 'ID', 'Short NPS trail across young-looking basalt, pressure ridges and lava textures near the monument entrance. Access can be affected by snow and seasonal loop-road operations.', 'open', 'https://www.nps.gov/crmo/planyourvisit/hiking-trails.htm', null, 'America/Denver', now()),
  ('Inferno Cone', 'inferno-cone', 'roadside-oddities', 43.44494, -113.55535, 'Arco', 'ID', 'A steep black cinder cone with a short climb to panoramic views across the Great Rift volcanic landscape. Follow the maintained trail and current NPS weather guidance.', 'open', 'https://www.nps.gov/crmo/planyourvisit/hiking-trails.htm', null, 'America/Denver', now()),
  ('Spatter Cones', 'spatter-cones', 'roadside-oddities', 43.44169, -113.55779, 'Arco', 'ID', 'Accessible short trails lead to welded lava cones formed around vents. These are named, distinct volcanic features rather than arbitrary extra pins inside the park.', 'open', 'https://www.nps.gov/crmo/planyourvisit/hiking-trails.htm', null, 'America/Denver', now()),
  ('Indian Tunnel', 'indian-tunnel', 'roadside-oddities', 43.44258, -113.52982, 'Arco', 'ID', 'Large collapsed lava tube reached on the Caves Trail. NPS cave entry requires the current cave permit/screening procedure, and conditions can close caves seasonally.', 'limited', 'https://www.nps.gov/crmo/planyourvisit/caves.htm', null, 'America/Denver', now()),
  ('Devil''s Orchard', 'devils-orchard', 'roadside-oddities', 43.4516, -113.53833, 'Arco', 'ID', 'Short loop through lava fragments and displaced blocks that early visitors thought looked like a supernatural ''orchard.'' It is a designated NPS trail with interpretive signs.', 'open', 'https://www.nps.gov/crmo/planyourvisit/hiking-trails.htm', null, 'America/Denver', now()),
  ('Broken Top Loop Trail', 'broken-top-loop-trail', 'roadside-oddities', 43.42771, -113.54863, 'Arco', 'ID', 'Named loop through cinder, lava flows and crater features on the southern portion of the park road. Use only the signed trail and respect seasonal road closures.', 'open', 'https://www.nps.gov/crmo/planyourvisit/hiking-trails.htm', null, 'America/Denver', now()),
  ('Tree Molds Trail', 'tree-molds-trail', 'roadside-oddities', 43.42771, -113.54863, 'Arco', 'ID', 'A signed spur from the Broken Top area reaches molds left where lava flowed around and burned away trees. The mapped point is the shared public trailhead rather than an off-trail feature coordinate.', 'open', 'https://www.nps.gov/crmo/planyourvisit/hiking-trails.htm', null, 'America/Denver', now()),
  ('Big Craters Viewpoint', 'big-craters-viewpoint', 'roadside-oddities', 43.45, -113.53333, 'Arco', 'ID', 'A named crater feature in the North Crater area offering a close look at the monument''s cinder-cone terrain. Stay on signed routes; fragile lava surfaces and steep crater slopes should not be shortcut.', 'open', 'https://www.nps.gov/crmo/index.htm', null, 'America/Denver', now()),
  ('Number Hill', 'number-hill', 'folklore', 43.63607, -113.2996, 'Arco', 'ID', 'Arco High School graduating classes have painted their class numbers on the basalt hill overlooking town for generations. It is best treated as a visible town landmark rather than an invitation to climb across private or unstable slopes.', 'roadside', 'https://cityofarco.municipalimpact.com/about-us', null, 'America/Denver', now()),
  ('USS Hawkbill Sail & Submarine Memorial', 'uss-hawkbill-sail-submarine-memorial', 'weird-history', 43.63417, -113.29665, 'Arco', 'ID', 'The preserved sail of the nuclear submarine USS Hawkbill anchors Arco''s connection to the nearby Naval Reactors Facility and atomic history. It is a public outdoor memorial.', 'open', 'https://visitidaho.org/travel-tips/add-these-stops-to-your-eastern-idaho-road-trip/', null, 'America/Denver', now()),
  ('Lemhi County Historical Museum', 'lemhi-county-historical-museum', 'museums', 45.1763, -113.8957, 'Salmon', 'ID', 'Museum covering Lemhi County mining, ranching, Indigenous history and settlement in the Salmon River country. Check opening hours before making it a destination stop.', 'limited', 'http://www.lemhicountymuseum.org/', null, 'America/Denver', now()),
  ('Lemhi Pass National Historic Landmark', 'lemhi-pass-national-historic-landmark', 'weird-history', 44.97437, -113.44533, 'Leadore', 'ID', 'High mountain pass crossed by Lewis and Clark in 1805, where the expedition confronted the Continental Divide and the scale of the western mountains. Gravel roads, snow and weather make access seasonal.', 'limited', 'https://history.idaho.gov/wp-content/uploads/2018/09/Lemhi_Pass_66000313.pdf', null, 'America/Denver', now()),
  ('Sharkey Hot Springs', 'sharkey-hot-springs', 'roadside-oddities', 45.01058, -113.61204, 'Salmon', 'ID', 'BLM-managed geothermal soaking pools with parking and basic facilities south of Salmon. Use the developed site and follow current BLM rules instead of seeking undeveloped private springs nearby.', 'open', 'https://www.blm.gov/visit/sharkey-hot-springs', null, 'America/Denver', now()),
  ('Challis Bison Kill Interpretive Trail', 'challis-bison-kill-interpretive-trail', 'weird-history', 44.4755, -114.2106, 'Challis', 'ID', 'A paved interpretive trail at the Land of the Yankee Fork visitor center explains the nearby Challis Bison Kill archaeological site. The coordinate intentionally routes to the visitor center, not to sensitive excavation locations.', 'limited', 'https://parksandrecreation.idaho.gov/state-park/land-of-the-yankee-fork-state-park/', null, 'America/Denver', now()),
  ('Big Springs', 'big-springs', 'roadside-oddities', 44.49799, -111.25578, 'Island Park', 'ID', 'A remarkably clear spring complex that forms the headwaters of the Henrys Fork. The developed public viewing area offers a reliable nature stop without sending visitors into sensitive backcountry.', 'open', 'https://visitidaho.org/travel-tips/add-these-stops-to-your-eastern-idaho-road-trip/', null, 'America/Denver', now()),
  ('Johnny Sack Cabin', 'johnny-sack-cabin', 'weird-history', 44.50018, -111.25496, 'Island Park', 'ID', 'Hand-built log cabin known for Johnny Sack''s elaborate bark-covered furnishings and woodworking, beside Big Springs. Interior tours are typically seasonal.', 'limited', 'https://visitidaho.org/travel-tips/add-these-stops-to-your-eastern-idaho-road-trip/', null, 'America/Denver', now()),
  ('Frostop Giant Root Beer Mug', 'frostop-giant-root-beer-mug', 'roadside-oddities', 44.07156, -111.45643, 'Ashton', 'ID', 'Large rotating root-beer mug sign at the historic Frostop drive-in, an easy piece of classic roadside Americana. View from the business/public parking area.', 'roadside', 'https://ashtonidaho.com/membership/dining/frostop-drive', null, 'America/Denver', now()),
  ('Farnsworth TV & Pioneer Museum', 'farnsworth-tv-pioneer-museum', 'museums', 43.67044, -111.91586, 'Rigby', 'ID', 'Rigby museum interpreting Philo T. Farnsworth''s connection to the invention of electronic television alongside local pioneer history. An unusually specific technology-history stop for a small Idaho town.', 'limited', 'https://cityofrigby.gov/museums/', null, 'America/Denver', now()),
  ('Legacy Flight Museum', 'legacy-flight-museum', 'museums', 43.83465, -111.8069, 'Rexburg', 'ID', 'Working aviation museum with historic aircraft, many maintained in flying condition. Hours can be limited, so confirm before routing specifically for the interior collection.', 'limited', 'https://www.rexburg.org/o/legacyflight/', null, 'America/Denver', now()),
  ('Teton Dam Historic Overlook', 'teton-dam-historic-overlook', 'weird-history', 43.9052, -111.54045, 'Newdale', 'ID', 'Designated Bureau of Reclamation overlook interpreting the 1976 Teton Dam failure and the remains of the failed dam. A new historic overlook opened in 2026; follow on-site USBR signage from N 12000 E rather than approaching the ruins directly.', 'open', 'https://www.usbr.gov/pn/snakeriver/dams/uppersnake/teton/', null, 'America/Denver', now()),
  ('Idaho Potato Museum', 'idaho-potato-museum', 'museums', 43.18956, -112.34397, 'Blackfoot', 'ID', 'Potato-focused museum inside Blackfoot''s former railroad depot, complete with agricultural exhibits and oversized potato photo ops. It is one of Idaho''s most on-brand roadside museums.', 'limited', 'https://www.idahopotatomuseum.com/', null, 'America/Denver', now()),
  ('Bingham County Historical Museum', 'bingham-county-historical-museum', 'museums', 43.18884, -112.34123, 'Blackfoot', 'ID', 'County museum with local artifacts and historic collections. The museum has posted building/HVAC closure information, so verify current reopening status before sending travelers specifically for the interior.', 'limited', 'https://binghamcountyhistoricalsociety.org/museum/', null, 'America/Denver', now()),
  ('Museum of Clean', 'museum-of-clean', 'museums', 42.86007, -112.44131, 'Pocatello', 'ID', 'A large, eccentric museum devoted to cleaning, sanitation and the history of cleaning tools. The subject matter and monumental displays make it a strong OddWay museum rather than a routine local-history stop.', 'limited', 'https://museumofclean.com/visit/', null, 'America/Denver', now()),
  ('Idaho Museum of Natural History', 'idaho-museum-of-natural-history', 'museums', 42.85972, -112.4337, 'Pocatello', 'ID', 'Idaho State University''s natural-history museum covers regional fossils, geology, Ice Age animals and anthropology. Use museum exhibits for archaeological context instead of routing to sensitive field sites.', 'limited', 'https://idahohighcountry.org/item/idaho-museum-of-natural-history/', null, 'America/Denver', now()),
  ('Bannock County Historical Museum', 'bannock-county-historical-museum', 'museums', 42.8442, -112.41899, 'Pocatello', 'ID', 'County museum near the Fort Hall Replica with exhibits on railroads, local settlement and southeast Idaho history. Check current museum hours.', 'limited', 'https://idahohighcountry.org/item/bannock-county-historical-museum/', null, 'America/Denver', now()),
  ('Fort Hall Replica', 'fort-hall-replica', 'weird-history', 42.84394, -112.41953, 'Pocatello', 'ID', 'Reconstruction interpreting the 1830s fur-trade Fort Hall and Oregon Trail era. It is a managed visitor site, not the sensitive original fort location.', 'limited', 'https://idahohighcountry.org/item/fort-hall-replica/', null, 'America/Denver', now()),
  ('Shoshone-Bannock Tribal Museum', 'shoshone-bannock-tribal-museum', 'museums', 43.02179, -112.41134, 'Fort Hall', 'ID', 'Museum on the Fort Hall Reservation presenting Shoshone-Bannock culture, history and art from a tribal perspective. Visit only during public hours and follow all reservation/site rules.', 'limited', 'https://idahohighcountry.org/item/shoshone-bannock-tribal-museum/', null, 'America/Denver', now()),
  ('Soda Springs Geyser', 'soda-springs-geyser', 'roadside-oddities', 42.65706, -111.60503, 'Soda Springs', 'ID', 'A carbon-dioxide-driven geyser accidentally created during drilling in 1937 and later fitted with a timer to erupt on a schedule. The city viewing area makes it an easy, legitimate unusual stop.', 'open', 'https://idahohighcountry.org/item/soda-springs-geyser/', null, 'America/Denver', now()),
  ('Hooper Springs Park', 'hooper-springs-park', 'roadside-oddities', 42.67882, -111.60317, 'Soda Springs', 'ID', 'Public park centered on a naturally carbonated mineral spring where visitors have traditionally sampled the water. Use the developed spring and park facilities only.', 'open', 'https://idahohighcountry.org/item/hooper-springs/', null, 'America/Denver', now()),
  ('Formation Springs Preserve', 'formation-springs-preserve', 'roadside-oddities', 42.69589, -111.55233, 'Soda Springs', 'ID', 'Nature preserve with unusual spring-fed pools and travertine formations created by mineral-rich water. Stay on established public routes to protect fragile formations and habitat.', 'open', 'https://idfg.idaho.gov/ibt/southeast', null, 'America/Denver', now()),
  ('Niter Ice Cave', 'niter-ice-cave', 'roadside-oddities', 42.53274, -111.72649, 'Grace', 'ID', 'A publicly known lava tube where cold air can preserve ice into warm months. Conditions are rough and natural; visit only when legal and safe, with appropriate lighting and footwear, and never enter during closures.', 'limited', 'https://idahohighcountry.org/item/niter-ice-cave/', null, 'America/Denver', now()),
  ('Chesterfield Historic Town Site', 'chesterfield-historic-town-site', 'weird-history', 42.86373, -111.90105, 'Chesterfield', 'ID', 'A remarkably intact Mormon agricultural settlement with restored homes, meetinghouse and other structures. Public tours are seasonal; do not enter closed buildings.', 'limited', 'https://visitidaho.org/things-to-do/ghost-mining-towns/chesterfield-historic-town-site/', null, 'America/Denver', now()),
  ('National Oregon/California Trail Center', 'national-oregon-california-trail-center', 'museums', 42.32298, -111.29741, 'Montpelier', 'ID', 'Large interpretive center focused on emigrants traveling the Oregon and California trails through the Bear Lake Valley. It provides a managed alternative to roaming unmarked trail remnants.', 'limited', 'https://www.nps.gov/places/the-national-oregon-california-trail-center.htm', null, 'America/Denver', now()),
  ('Butch Cassidy Museum at the Bank of Montpelier', 'butch-cassidy-museum-at-the-bank-of-montpelier', 'museums', 42.31757, -111.30783, 'Montpelier', 'ID', 'Museum in the historic bank robbed by Butch Cassidy''s gang in 1896, interpreting the robbery and local outlaw history. Check public hours before visiting.', 'limited', 'https://visitidaho.org/things-to-do/museums-exhibits/butch-cassidy-museum-at-the-bank-of-montpelier/', null, 'America/Denver', now()),
  ('Old Ephraim Legends & Lore Marker', 'old-ephraim-legends-lore-marker', 'folklore', 42.31748, -111.30967, 'Montpelier', 'ID', 'Public marker interpreting Old Ephraim, the enormous grizzly bear whose story became a major piece of regional folklore. The Montpelier marker gives travelers the legend without routing them to remote or uncertain backcountry sites.', 'open', 'https://www.wgpfoundation.org/historic-markers/old-ephraim/', null, 'America/Denver', now()),
  ('Minnetonka Cave', 'minnetonka-cave', 'roadside-oddities', 42.08758, -111.51876, 'St. Charles', 'ID', 'Guided Forest Service cave tour through large limestone rooms and formations in the Bear Lake area. Tickets, road conditions and seasonal opening dates should be checked in advance.', 'limited', 'https://www.recreation.gov/ticket/facility/10087702', null, 'America/Denver', now()),
  ('Oneida Stake Academy', 'oneida-stake-academy', 'weird-history', 42.09608, -111.8743, 'Preston', 'ID', 'Restored 1890s academy associated with early education in southeast Idaho. Public tours and events vary, so confirm access before routing for the interior.', 'limited', 'https://www.oneidastakeacademy.org/', null, 'America/Denver', now()),
  ('Oneida County Pioneer Museum', 'oneida-county-pioneer-museum', 'museums', 42.18615, -112.24584, 'Malad City', 'ID', 'County museum preserving pioneer, railroad and community artifacts from the Malad Valley. Check current public hours.', 'limited', 'https://idahohighcountry.org/item/oneida-county-pioneer-museum/', null, 'America/Denver', now()),
  ('Spud Drive-In Giant Potato', 'spud-drive-in-giant-potato', 'roadside-oddities', 43.68944, -111.10917, 'Driggs', 'ID', 'Famous giant potato mounted on an old truck beside the Spud Drive-In, one of Idaho''s signature roadside photo stops. View from the business/public area without blocking traffic.', 'roadside', 'https://visitidaho.org/things-to-do/roadside-attractions/spud-drive-in/', null, 'America/Denver', now()),
  ('Hell''s Half Acre Lava Trail System — I-15 Trailhead', 'hells-half-acre-lava-trail-system-i-15-trailhead', 'roadside-oddities', 43.305, -112.26972, 'Blackfoot', 'ID', 'BLM trail access into a stark basalt field created by relatively young lava flows. The mapped point is an official trailhead, keeping travelers away from unmarked lava-tube entrances and fragile terrain.', 'open', 'https://www.blm.gov/visit/lava-trail-system-hells-half-acre/', null, 'America/Denver', now()),
  ('Hell''s Half Acre Twenty Mile Trail', 'hells-half-acre-twenty-mile-trail', 'roadside-oddities', 43.55694, -112.445, 'Blackfoot', 'ID', 'Longer BLM access point into the Hell''s Half Acre lava landscape for travelers wanting a more substantial volcanic stop. Carry water and follow marked routes; the terrain is sharp and exposed.', 'open', 'https://www.blm.gov/visit/lava-trail-system-hells-half-acre/', null, 'America/Denver', now()),
  ('Bear Lake Monster Lore — North Beach State Park', 'bear-lake-monster-lore-north-beach-state-park', 'cryptids', 42.02771, -111.25131, 'St. Charles', 'ID', 'Bear Lake''s long-running monster legend dates to nineteenth-century reports and remains part of local tourism folklore. OddWay routes to a lawful public lakeshore viewpoint at North Beach State Park and treats the creature strictly as legend, not fact.', 'open', 'https://www.visitbearlake.org/bear-lake-monster', null, 'America/Denver', now()),
  ('Idaho''s Mammoth Cave', 'idahos-mammoth-cave', 'roadside-oddities', 43.07055, -114.41238, 'Shoshone', 'ID', 'A privately operated lava-tube attraction eight miles north of Shoshone with a maintained self-guided route and provided lanterns. It is open for the 2026 season on a reduced weekend schedule after Labor Day and closes for winter after September 28.', 'limited', 'https://idahosmammothcave.com/', null, 'America/Denver', now()),
  ('Minidoka National Historic Site', 'minidoka-national-historic-site', 'weird-history', 42.678, -114.2465, 'Hunt', 'ID', 'National Park Service site preserving the history of more than 13,000 Japanese Americans incarcerated at Minidoka during World War II. Use designated visitor routes and approach the place as a memorial and civil-rights history site.', 'open', 'https://www.nps.gov/miin/index.htm', null, 'America/Denver', now()),
  ('Thousand Springs Visitor Center', 'thousand-springs-visitor-center', 'roadside-oddities', 42.8316, -114.8915, 'Hagerman', 'ID', 'Joint visitor center for Hagerman Fossil Beds National Monument and Thousand Springs State Park, with fossil, geology and regional displays. It is the proper public starting point for understanding the fossil beds.', 'limited', 'https://www.nps.gov/hafo/planyourvisit/visitor-center.htm', null, 'America/Denver', now()),
  ('Hagerman Fossil Beds Oregon Trail Overlook', 'hagerman-fossil-beds-oregon-trail-overlook', 'roadside-oddities', 42.79074, -114.94431, 'Hagerman', 'ID', 'Designated public overlook across the Hagerman fossil landscape and Oregon Trail corridor. Fossil collecting and off-route access are prohibited; OddWay should keep users at signed public viewpoints.', 'open', 'https://www.nps.gov/hafo/index.htm', null, 'America/Denver', now()),
  ('Malad Gorge State Park', 'malad-gorge-state-park', 'roadside-oddities', 42.86546, -114.86061, 'Tuttle', 'ID', 'A dramatic basalt gorge cut by the Malad River within Thousand Springs State Park. Use designated overlooks, trails and park access rather than unofficial cliff approaches.', 'open', 'https://parksandrecreation.idaho.gov/state-park/thousand-springs-state-park/', null, 'America/Denver', now()),
  ('Devil''s Wash Bowl', 'devils-wash-bowl', 'roadside-oddities', 42.86768, -114.85367, 'Tuttle', 'ID', 'A named feature of Malad Gorge where water churns through a deep basalt-cut bowl. View only from established park overlooks and trails.', 'open', 'https://parksandrecreation.idaho.gov/state-park/thousand-springs-state-park/', null, 'America/Denver', now()),
  ('Box Canyon Springs Nature Preserve', 'box-canyon-springs-nature-preserve', 'roadside-oddities', 42.7075, -114.81028, 'Wendell', 'ID', 'One of North America''s largest springs bursts from the canyon wall and feeds an intensely clear stream. Trails are steep in places; remain within the state-park preserve.', 'open', 'https://parksandrecreation.idaho.gov/state-park/thousand-springs-state-park/', null, 'America/Denver', now()),
  ('Ritter Island', 'ritter-island', 'roadside-oddities', 42.74437, -114.84513, 'Hagerman', 'ID', 'State-park unit surrounded by spring-fed water and historic agricultural structures beneath Thousand Springs. Public trails and seasonal facilities make it a reliable stop.', 'open', 'https://parksandrecreation.idaho.gov/state-park/thousand-springs-state-park/', null, 'America/Denver', now()),
  ('Niagara Springs', 'niagara-springs', 'roadside-oddities', 42.66574, -114.67421, 'Wendell', 'ID', 'Large spring pours from the Snake River Canyon wall in another unit of Thousand Springs State Park. The canyon road is steep; follow park access and vehicle guidance.', 'open', 'https://parksandrecreation.idaho.gov/state-park/thousand-springs-state-park/', null, 'America/Denver', now()),
  ('Shoshone Falls', 'shoshone-falls', 'roadside-oddities', 42.59519, -114.40087, 'Twin Falls', 'ID', 'Massive waterfall on the Snake River often called the ''Niagara of the West.'' Water volume varies dramatically with season and irrigation, but the city park and overlooks are established public access.', 'open', 'https://visitsouthidaho.com/adventure/shoshone-falls/', null, 'America/Denver', now()),
  ('Perrine Memorial Bridge', 'perrine-memorial-bridge', 'roadside-oddities', 42.60102, -114.45448, 'Twin Falls', 'ID', 'High bridge over the Snake River Canyon internationally known as a legal BASE-jumping location. Visitors should use the official visitor-center overlooks and sidewalks; OddWay does not encourage jumping or climbing.', 'open', 'https://visitsouthidaho.com/adventure/snake-river-canyon/', null, 'America/Denver', now()),
  ('Evel Knievel Monument at Twin Falls Visitor Center', 'evel-knievel-monument-at-twin-falls-visitor-center', 'roadside-oddities', 42.59845, -114.4548, 'Twin Falls', 'ID', 'Public monument interpreting Evel Knievel''s 1974 attempt to jump the Snake River Canyon in a rocket-powered Skycycle. This pin intentionally uses the visitor center rather than the privately owned jump-ramp site.', 'open', 'https://visitsouthidaho.com/adventure/evel-knievel-jump-site/', null, 'America/Denver', now()),
  ('Perrine Coulee Falls', 'perrine-coulee-falls', 'roadside-oddities', 42.59686, -114.47017, 'Twin Falls', 'ID', 'A tall waterfall dropping into the Snake River Canyon with a short trail that can pass behind the falling water. Parking near the trail is extremely limited; use only legal spaces and choose alternate canyon parking when full.', 'limited', 'https://visitsouthidaho.com/adventure/perrine-coulee-falls/', null, 'America/Denver', now()),
  ('Balanced Rock', 'balanced-rock-castleford', 'roadside-oddities', 42.57449, -115.08963, 'Castleford', 'ID', 'A huge rhyolite boulder balanced on a narrow pedestal in the Salmon Falls Creek canyon country. Use the established county recreation area and trail rather than scrambling on the formation.', 'open', 'https://www.recreation.gov/activitypass/balanced-rock-park', null, 'America/Denver', now()),
  ('City of Rocks Visitor Center', 'city-of-rocks-visitor-center', 'roadside-oddities', 42.09136, -113.63252, 'Almo', 'ID', 'Visitor center for City of Rocks National Reserve and Castle Rocks State Park, providing maps and current access information for the granite formations and emigrant inscriptions.', 'limited', 'https://www.nps.gov/ciro/planyourvisit/basicinfo.htm', null, 'America/Denver', now()),
  ('Camp Rock', 'camp-rock', 'weird-history', 42.0738, -113.69084, 'Almo', 'ID', 'Prominent granite outcrop where nineteenth-century emigrants left names and dates along the California Trail. Do not add marks, chalk or rub historic inscriptions.', 'open', 'https://www.nps.gov/ciro/index.htm', null, 'America/Denver', now()),
  ('Register Rock — City of Rocks', 'register-rock-city-of-rocks', 'weird-history', 42.06714, -113.69751, 'Almo', 'ID', 'Named rock formation carrying historic emigrant signatures and dates from the California Trail period. View from designated public access and leave all inscriptions untouched.', 'open', 'https://www.nps.gov/ciro/index.htm', null, 'America/Denver', now()),
  ('Bath Rock', 'bath-rock', 'roadside-oddities', 42.07547, -113.72223, 'Almo', 'ID', 'Massive rounded granite monolith named for a weathered basin near its summit. It is a distinct named City of Rocks landmark with established nearby parking and trails.', 'open', 'https://www.nps.gov/ciro/index.htm', null, 'America/Denver', now()),
  ('Bread Loaves', 'bread-loaves', 'roadside-oddities', 42.088, -113.729, 'Almo', 'ID', 'Long rounded granite formation whose shape inspired the ''Bread Loaves'' name, standing among the reserve''s most recognizable rock forms. Stay on public reserve routes.', 'open', 'https://www.nps.gov/ciro/index.htm', null, 'America/Denver', now()),
  ('Massacre Rocks State Park', 'massacre-rocks-state-park', 'weird-history', 42.6808, -112.9836, 'American Falls', 'ID', 'State park along the Snake River where emigrant-trail history, basalt boulders and later legends converge. Interpretive facilities place the stories in context; the ominous name should not be treated as proof of a single massacre at the park site.', 'open', 'https://parksandrecreation.idaho.gov/state-park/massacre-rocks-state-park/', null, 'America/Denver', now()),
  ('Register Rock State Historic Site', 'register-rock-state-historic-site', 'weird-history', 42.65269, -113.01692, 'American Falls', 'ID', 'Protected Oregon Trail campsite where emigrants carved names into a large basalt outcrop. A shelter helps preserve the historic inscriptions; no new carving or touching is appropriate.', 'open', 'https://parksandrecreation.idaho.gov/state-park/massacre-rocks-state-park/', null, 'America/Denver', now()),
  ('Oakley Valley Historical Museum', 'oakley-valley-historical-museum', 'museums', 42.24282, -113.88261, 'Oakley', 'ID', 'Small museum interpreting Oakley Valley settlement, ranching and community history in one of southern Idaho''s unusually intact historic towns. Check hours before visiting.', 'limited', 'https://visitsouthidaho.com/adventure/oakley-valley-historical-museum/', null, 'America/Denver', now()),
  ('Haunted Mansions of Albion', 'haunted-mansions-of-albion', 'haunted', 42.41333, -113.58389, 'Albion', 'ID', 'A ticketed Halloween haunt staged inside the century-old former Albion State Normal School campus, a property also associated with decades of local ghost stories and paranormal investigations. The attraction is seasonal and access is only during authorized events or lodging bookings.', 'limited', 'https://www.hauntedalbion.com/', null, 'America/Denver', now()),
  ('Herrett Center for Arts & Science', 'herrett-center-for-arts-science', 'museums', 42.58028, -114.46667, 'Twin Falls', 'ID', 'College of Southern Idaho museum and planetarium with natural-history, anthropology and astronomy exhibits. It adds an astronomy and science angle to the Twin Falls cluster.', 'limited', 'https://herrett.csi.edu/', null, 'America/Denver', now()),
  ('Minidoka County Historical Society Museum', 'minidoka-county-historical-society-museum', 'museums', 42.61915, -113.64894, 'Rupert', 'ID', 'County museum preserving agricultural, pioneer and community artifacts from the Rupert and Minidoka area. Check current operating hours before routing specifically for the museum.', 'limited', 'https://www.museum-mchs.org/', null, 'America/Denver', now()),
  ('Bruneau Dunes State Park', 'bruneau-dunes-state-park', 'roadside-oddities', 42.91, -115.70972, 'Bruneau', 'ID', 'Home to North America''s tallest single-structured sand dune, rising above a pair of small lakes. The stark dune field is a major natural oddity and also a well-known dark-sky destination.', 'open', 'https://parksandrecreation.idaho.gov/state-park/bruneau-dunes-state-park/', null, 'America/Denver', now()),
  ('Bruneau Dunes Observatory', 'bruneau-dunes-observatory', 'roadside-oddities', 42.9024, -115.69021, 'Bruneau', 'ID', 'Public observatory inside Bruneau Dunes State Park offering scheduled telescope programs under dark skies. Programs are seasonal and weather dependent.', 'limited', 'https://parksandrecreation.idaho.gov/state-park/bruneau-dunes-state-park/', null, 'America/Denver', now()),
  ('Swan Falls Dam', 'swan-falls-dam', 'weird-history', 43.24245, -116.37631, 'Murphy', 'ID', 'Historic dam on the Snake River inside the Morley Nelson Snake River Birds of Prey National Conservation Area. Use developed recreation areas and signed roads; the surrounding canyon is rugged.', 'open', 'https://www.blm.gov/visit/swan-falls', null, 'America/Denver', now()),
  ('Dedication Point Overlook', 'dedication-point-overlook', 'roadside-oddities', 43.27667, -116.39389, 'Kuna', 'ID', 'BLM overlook above the Snake River Canyon within the Birds of Prey conservation area, with a short interpretive trail and dramatic basalt cliffs. Stay behind barriers and on signed paths.', 'open', 'https://www.blm.gov/visit/dedication-point-overlook', null, 'America/Denver', now()),
  ('Idaho Museum of Mining and Geology', 'idaho-museum-of-mining-and-geology', 'roadside-oddities', 43.60278, -116.16147, 'Boise', 'ID', 'Museum next to the Old Pen complex with Idaho minerals, fossils and mining exhibits. It is an efficient way to add genuine geological context to the state''s mine and lava-field stops.', 'limited', 'https://www.idahomuseum.org/', null, 'America/Denver', now()),
  ('Freak Alley Gallery', 'freak-alley-gallery', 'roadside-oddities', 43.61708, -116.203, 'Boise', 'ID', 'Large open-air mural gallery filling an alley in downtown Boise, continually changing as artists add new work. Public pedestrian access makes it a strong low-friction OddWay stop.', 'open', 'https://visitidaho.org/things-to-do/roadside-attractions/freak-alley-gallery/', null, 'America/Denver', now()),
  ('Warhawk Air Museum', 'warhawk-air-museum', 'museums', 43.5856, -116.5236, 'Nampa', 'ID', 'Large museum of military aircraft, vehicles, uniforms and personal stories from twentieth-century conflicts. Check admission hours before visiting.', 'limited', 'https://warhawkairmuseum.org/visit/', null, 'America/Denver', now()),
  ('Nampa Train Depot Museum', 'nampa-train-depot-museum', 'museums', 43.5796, -116.55869, 'Nampa', 'ID', 'Restored 1903 Oregon Short Line depot preserving Nampa railroad and community history. Museum hours are limited, so verify before making it a dedicated stop.', 'limited', 'https://canyoncountyhistory.org/', null, 'America/Denver', now()),
  ('Silver City Historic District', 'silver-city-historic-district', 'weird-history', 43.01652, -116.73261, 'Silver City', 'ID', 'Remote nineteenth-century mining town with an unusually large collection of surviving historic buildings and a small modern seasonal population. Roads can be rough and snowbound; respect private homes and enter only businesses or buildings explicitly open to visitors.', 'limited', 'https://visitidaho.org/things-to-do/ghost-towns-mining-history/silver-city-historical-area/', null, 'America/Denver', now()),
  ('Idaho Hotel', 'idaho-hotel', 'weird-history', 43.0166, -116.73311, 'Silver City', 'ID', 'Landmark 1860s hotel in the Silver City historic district, long surrounded by local stories and old-west atmosphere. Unless current public hotel access is clearly posted, treat it as an exterior/view-only landmark and do not enter private portions.', 'roadside', 'https://www.lib.uidaho.edu/digital/postcards/items/nwpostcards989.html', null, 'America/Denver', now()),
  ('Boise Basin Museum', 'boise-basin-museum', 'museums', 43.82861, -115.83278, 'Idaho City', 'ID', 'Museum interpreting the explosive Boise Basin gold rush, mining tools and Idaho City''s frontier history. Operating dates can be seasonal.', 'limited', 'https://www.loc.gov/pictures/item/id0024/', null, 'America/Denver', now()),
  ('Three Island Crossing State Park', 'three-island-crossing-state-park', 'weird-history', 42.9447, -115.3181, 'Glenns Ferry', 'ID', 'State park interpreting one of the Snake River crossings used by Oregon Trail emigrants. Museum exhibits and designated viewpoints explain the hazardous crossing without routing visitors onto unmarked trail or archaeological areas.', 'limited', 'https://parksandrecreation.idaho.gov/state-park/three-island-crossing-state-park/', null, 'America/Denver', now()),
  ('Bonneville Point', 'bonneville-point', 'weird-history', 43.49167, -116.04, 'Boise', 'ID', 'BLM-managed overlook where travelers can see the Boise Valley much as Oregon Trail emigrants did after crossing the desert. Use the marked road and interpretive area.', 'open', 'https://www.blm.gov/visit/bonneville-point', null, 'America/Denver', now()),
  ('Lawson''s Legacy / Emu-Z-Um', 'lawsons-legacy-emu-z-um', 'museums', 43.04126, -116.19013, 'Grand View', 'ID', 'An eccentric private museum complex created by the Lawson family, known for wide-ranging collections and unusual displays in the Grand View area. Because access and hours can change, confirm directly before routing visitors onto the property.', 'limited', 'https://emuzum.com/HowToGetThere/default.html', null, 'America/Denver', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  timezone      = excluded.timezone,
  verified_at   = excluded.verified_at;

select count(*) as idaho from public.stops where state = 'ID';
