-- weird-history: 47 places from the OpenStreetMap scan.
--
-- Reviewed as a CSV before generation, so anything unwanted was deleted there
-- rather than pruned out of live data afterwards.
--
-- Descriptions are null and verified_at is unset: these pages will say the
-- entry is unverified until somebody writes one, which is honest and is the
-- same discipline the rest of the index follows.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone)
values
('J Lorraine, Texas Ghost Town', 'j-lorraine-texas-ghost-town', 'weird-history', 30.332325, -97.509487, 'Manor', 'TX', 'A piece of weird history in Manor, TX, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/way/962329436', 'America/Chicago'),
('Martin Augustine Mining Camp', 'martin-augustine-mining-camp', 'weird-history', 33.484085, -115.236058, 'Niland', 'CA', 'A piece of weird history in Niland, CA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/10794140239', 'America/Los_Angeles'),
('Castle Dome Mine Museum', 'castle-dome-mine-museum', 'weird-history', 33.045874, -114.178023, 'Yuma', 'AZ', 'A piece of weird history in Yuma, AZ, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/way/1137995652', 'America/Phoenix'),
('Goldfield Ghost Town', 'goldfield-ghost-town', 'weird-history', 33.45733, -111.491847, 'Apache Junction', 'AZ', 'A piece of weird history in Apache Junction, AZ, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/way/46411488', 'America/Phoenix'),
('Shakespeare Ghost Town Tours', 'shakespeare-ghost-town-tours', 'weird-history', 32.32479, -108.738557, 'Lordsburg', 'NM', 'A piece of weird history in Lordsburg, NM, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/9775681844', 'America/Denver'),
('Belcamp (Ghost Town)', 'belcamp-ghost-town', 'weird-history', 33.443616, -98.685788, 'Olney', 'TX', 'A piece of weird history in Olney, TX, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/1731158405', 'America/Chicago'),
('Ghost Town of Cotton Gin', 'ghost-town-of-cotton-gin', 'weird-history', 31.68067, -96.35993, 'Teague', 'TX', 'A piece of weird history in Teague, TX, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/12403614321', 'America/Chicago'),
('Calico Ghost Town', 'calico-ghost-town', 'weird-history', 34.948373, -116.864611, 'Barstow', 'CA', 'A piece of weird history in Barstow, CA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/670761', 'America/Los_Angeles'),
('Ballarat', 'ballarat', 'weird-history', 36.047917, -117.225675, 'Searles Valley', 'CA', 'A piece of weird history in Searles Valley, CA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/150935444', 'America/Los_Angeles'),
('Silver City Ghost Town', 'silver-city-ghost-town', 'weird-history', 35.597694, -118.4916, 'Bodfish', 'CA', 'A piece of weird history in Bodfish, CA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/way/1285388412', 'America/Los_Angeles'),
('Ghost Town of White Hills', 'ghost-town-of-white-hills', 'weird-history', 35.700322, -114.474416, 'Dolan Springs', 'AZ', 'A piece of weird history in Dolan Springs, AZ, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/959119853', 'America/Phoenix'),
('Lost Arch Historic Mining Camp', 'lost-arch-historic-mining-camp', 'weird-history', 34.436412, -114.824378, 'Desert Hills', 'AZ', 'A piece of weird history in Desert Hills, AZ, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/12125673149', 'America/Los_Angeles'),
('Venezia', 'venezia', 'weird-history', 34.393082, -112.416834, 'Mayer', 'AZ', 'A piece of weird history in Mayer, AZ, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/150939519', 'America/Phoenix'),
('Goodwin', 'goodwin', 'weird-history', 34.355719, -112.380399, 'Mayer', 'AZ', 'A piece of weird history in Mayer, AZ, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/150954256', 'America/Phoenix'),
('Hooper', 'hooper', 'weird-history', 34.26614, -112.382945, 'Mayer', 'AZ', 'A piece of weird history in Mayer, AZ, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/150963127', 'America/Phoenix'),
('Vulture Mine Tours / Vulture City Ghost Town', 'vulture-mine-tours-vulture-city-ghost-town', 'weird-history', 33.816527, -112.828828, 'Wickenburg', 'AZ', 'A piece of weird history in Wickenburg, AZ, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/3274100436', 'America/Phoenix'),
('Ghost Town Tours', 'ghost-town-tours', 'weird-history', 34.750699, -112.116606, 'Clarkdale', 'AZ', 'A piece of weird history in Clarkdale, AZ, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/9953774076', 'America/Phoenix'),
('Gold King Mine Ghost Town', 'gold-king-mine-ghost-town', 'weird-history', 34.75655, -112.130827, 'Clarkdale', 'AZ', 'A piece of weird history in Clarkdale, AZ, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/14145400120', 'America/Phoenix'),
('abandoned mine marker', 'abandoned-mine-marker', 'weird-history', 35.464799, -106.12779, 'La Cienega', 'NM', 'A piece of weird history in La Cienega, NM, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/5489916823', 'America/Denver'),
('Ghost Town of Clara', 'ghost-town-of-clara', 'weird-history', 34.09176, -98.69693, 'Burkburnett', 'TX', 'A piece of weird history in Burkburnett, TX, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/12453787783', 'America/Chicago'),
('Ghost Town Village', 'ghost-town-village', 'weird-history', 35.526815, -83.103619, 'Maggie Valley', 'NC', 'A piece of weird history in Maggie Valley, NC, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/way/1092172492', 'America/New_York'),
('Palmyra Mining Camp', 'palmyra-mining-camp', 'weird-history', 39.165714, -119.500106, 'Dayton', 'NV', 'A piece of weird history in Dayton, NV, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/9869705017', 'America/Los_Angeles'),
('Leadfield', 'leadfield', 'weird-history', 36.848316, -117.060807, 'Beatty', 'NV', 'A piece of weird history in Beatty, NV, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/150955198', 'America/Los_Angeles'),
('Rhyolite Ghost Town', 'rhyolite-ghost-town', 'weird-history', 36.900897, -116.829335, 'Beatty', 'NV', 'A piece of weird history in Beatty, NV, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/2628616795', 'America/Los_Angeles'),
('Cerro Gordo Ghost Town', 'cerro-gordo-ghost-town', 'weird-history', 36.537743, -117.79506, 'Lone Pine', 'CA', 'A piece of weird history in Lone Pine, CA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/3472284346', 'America/Los_Angeles'),
('Logan City', 'logan-city', 'weird-history', 37.609462, -115.393523, 'Alamo', 'NV', 'A piece of weird history in Alamo, NV, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/3814805134', 'America/Los_Angeles'),
('Ghost Town Pahreah Old Cellar', 'ghost-town-pahreah-old-cellar', 'weird-history', 37.24808, -111.952794, 'Kanab', 'UT', 'A piece of weird history in Kanab, UT, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/1800705764', 'America/Denver'),
('Ghost Town Pahreah Old Chimney', 'ghost-town-pahreah-old-chimney', 'weird-history', 37.247594, -111.952313, 'Kanab', 'UT', 'A piece of weird history in Kanab, UT, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/1800705771', 'America/Denver'),
('Spencer´s Mining Camp', 'spencer-s-mining-camp', 'weird-history', 37.246992, -111.952239, 'Kanab', 'UT', 'A piece of weird history in Kanab, UT, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/1800705800', 'America/Denver'),
('Leefe', 'leefe', 'weird-history', 41.811762, -111.024733, 'Randolph', 'UT', 'A piece of weird history in Randolph, UT, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/150957842', 'America/Denver'),
('Murray Hall', 'murray-hall', 'weird-history', 41.809501, -96.024678, 'Tekamah', 'NE', 'A piece of weird history in Tekamah, NE, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/8487259027', 'America/Chicago'),
('Jean Baptiste Charbonneau Grave', 'jean-baptiste-charbonneau-grave', 'weird-history', 42.951943, -117.339185, 'Murphy', 'ID', 'A piece of weird history in Murphy, ID, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/way/460000136', 'America/Los_Angeles'),
('Buffalo Ridge Ghost Town', 'buffalo-ridge-ghost-town', 'weird-history', 43.607993, -96.885893, 'Hartford', 'SD', 'A piece of weird history in Hartford, SD, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/way/1063293375', 'America/Chicago'),
('Forts Ferry', 'forts-ferry', 'weird-history', 42.787988, -73.793012, 'Niskayuna', 'NY', 'A piece of weird history in Niskayuna, NY, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/7576529641', 'America/New_York'),
('Gilbert Ghost Town', 'gilbert-ghost-town', 'weird-history', 48.457381, -120.562214, 'Granite Falls', 'WA', 'A piece of weird history in Granite Falls, WA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/150969778', 'America/Los_Angeles'),
('Franklin Ghost Town', 'franklin-ghost-town', 'weird-history', 47.297998, -121.95874, 'Black Diamond', 'WA', 'A piece of weird history in Black Diamond, WA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/6172525155', 'America/Los_Angeles'),
('Garnet Ghost Town', 'garnet-ghost-town', 'weird-history', 46.825141, -113.339388, 'Clinton', 'MT', 'A piece of weird history in Clinton, MT, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/way/1149749049', 'America/Denver'),
('Old Molson Ghost Town Museum', 'old-molson-ghost-town-museum', 'weird-history', 48.976171, -119.19968, 'Oroville', 'WA', 'A piece of weird history in Oroville, WA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/way/428128256', 'America/Los_Angeles')
on conflict (slug) do update set
  latitude  = excluded.latitude,
  longitude = excluded.longitude,
  city      = excluded.city,
  state     = excluded.state,
  timezone  = excluded.timezone;
-- Note: description is deliberately not updated here. Re-running this must
-- never overwrite a description somebody has written with the placeholder.
