-- cryptids: 29 places from the OpenStreetMap scan.
--
-- Reviewed as a CSV before generation, so anything unwanted was deleted there
-- rather than pruned out of live data afterwards.
--
-- Descriptions are null and verified_at is unset: these pages will say the
-- entry is unverified until somebody writes one, which is honest and is the
-- same discipline the rest of the index follows.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone)
values
  ('Skunk Ape Center and Museum', 'skunk-ape-center-and-museum', 'cryptids', 25.893918, -81.278523, 'Marco Island', 'FL', 'A cryptid site in Marco Island, FL, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/10210835917', 'America/New_York'),
  ('Bigfoot Lookout', 'bigfoot-lookout', 'cryptids', 33.815056, -117.918628, 'Anaheim', 'CA', 'A cryptid site in Anaheim, CA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/10962908264', 'America/Los_Angeles'),
  ('Expedition: Bigfoot - The Sasquatch Museum', 'expedition-bigfoot-the-sasquatch-museum', 'cryptids', 34.802273, -84.376175, 'Cherry Log', 'GA', 'A cryptid site in Cherry Log, GA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/way/380684000', 'America/New_York'),
  ('Bigfoot Museum', 'bigfoot-museum', 'cryptids', 37.041437, -122.072526, 'Felton', 'CA', 'A cryptid site in Felton, CA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/797799539', 'America/Los_Angeles'),
  ('Sasquatch - Photo Opp', 'sasquatch-photo-opp', 'cryptids', 37.036099, -88.271112, 'Calvert City', 'KY', 'A cryptid site in Calvert City, KY, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/12893412684', 'America/Chicago'),
  ('Mothman Statue', 'mothman-statue', 'cryptids', 38.842573, -82.13852, 'Point Pleasant', 'WV', 'A cryptid site in Point Pleasant, WV, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/5328446004', 'America/New_York'),
  ('Mothman Museum', 'mothman-museum', 'cryptids', 38.842731, -82.138529, 'Point Pleasant', 'WV', 'A cryptid site in Point Pleasant, WV, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/way/904768521', 'America/New_York'),
  ('Bigfoot Trap', 'bigfoot-trap', 'cryptids', 42.056587, -123.137225, 'Williams', 'OR', 'A cryptid site in Williams, OR, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/10817099005', 'America/Los_Angeles'),
  ('Southern Oregon Bigfoot Experience', 'southern-oregon-bigfoot-experience', 'cryptids', 42.167613, -123.646048, 'Cave Junction', 'OR', 'A cryptid site in Cave Junction, OR, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/11343789706', 'America/Los_Angeles'),
  ('Bigfoot Statue', 'bigfoot-statue', 'cryptids', 40.93882, -123.628581, 'Willow Creek', 'CA', 'A cryptid site in Willow Creek, CA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/13526912734', 'America/Los_Angeles'),
  ('Museum Bigfoot Statue', 'museum-bigfoot-statue', 'cryptids', 40.940121, -123.632084, 'Willow Creek', 'CA', 'A cryptid site in Willow Creek, CA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/13527671968', 'America/Los_Angeles'),
  ('Gonzalez Bigfoot Statue', 'gonzalez-bigfoot-statue', 'cryptids', 40.939748, -123.631694, 'Willow Creek', 'CA', 'A cryptid site in Willow Creek, CA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/13531160722', 'America/Los_Angeles'),
  ('Willow Creek-China Flat Museum & Bigfoot Collection', 'willow-creek-china-flat-museum-bigfoot-collection', 'cryptids', 40.940229, -123.63207, 'Willow Creek', 'CA', 'A cryptid site in Willow Creek, CA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/way/776346735', 'America/Los_Angeles'),
  ('Big Boot', 'big-boot', 'cryptids', 41.133566, -104.82535, 'Cheyenne', 'WY', 'A cryptid site in Cheyenne, WY, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/14090479377', 'America/Denver'),
  ('Jersey Devil', 'jersey-devil', 'cryptids', 40.13439, -74.443789, 'Shrewsbury', 'NJ', 'A cryptid site in Shrewsbury, NJ, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/12859899266', 'America/New_York'),
  ('Bigfoot Cabin (ruins)', 'bigfoot-cabin-ruins', 'cryptids', 39.695892, -76.249272, 'Susquehanna Trails', 'PA', 'A cryptid site in Susquehanna Trails, PA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/way/383618052', 'America/New_York'),
  ('North American Bigfoot Center', 'north-american-bigfoot-center', 'cryptids', 45.431789, -122.340251, 'Sandy', 'OR', 'A cryptid site in Sandy, OR, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/8868908017', 'America/Los_Angeles'),
  ('Surfing Sasquatch', 'surfing-sasquatch', 'cryptids', 44.979731, -124.013634, 'Lincoln City', 'OR', 'A cryptid site in Lincoln City, OR, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/13021851179', 'America/Los_Angeles'),
  ('Bigfoot', 'bigfoot', 'cryptids', 45.36042, -122.856409, 'Sherwood', 'OR', 'A cryptid site in Sherwood, OR, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/13670202967', 'America/Los_Angeles'),
  ('Bigfoot Pass Overlook', 'bigfoot-pass-overlook', 'cryptids', 43.795913, -102.046085, 'Philip', 'SD', 'A cryptid site in Philip, SD, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/422386081', 'America/Denver'),
  ('Pixel Yeti', 'pixel-yeti', 'cryptids', 44.886268, -93.401937, 'Edina', 'MN', 'A cryptid site in Edina, MN, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/6802602198', 'America/Chicago'),
  ('Sasquatch', 'sasquatch', 'cryptids', 42.531314, -83.315132, 'Franklin', 'MI', 'A cryptid site in Franklin, MI, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/12664732006', 'America/Detroit'),
  ('Sasquatch Pushing Over a House', 'sasquatch-pushing-over-a-house', 'cryptids', 47.664314, -122.319674, 'Seattle', 'WA', 'A cryptid site in Seattle, WA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/3211770268', 'America/Los_Angeles'),
  ('Sasquatch Steps', 'sasquatch-steps', 'cryptids', 46.226284, -122.185263, 'Morton', 'WA', 'A cryptid site in Morton, WA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/5535204373', 'America/Los_Angeles'),
  ('Ferry Fever', 'ferry-fever', 'cryptids', 47.566984, -122.630788, 'Bremerton', 'WA', 'A cryptid site in Bremerton, WA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/12672661145', 'America/Los_Angeles'),
  ('The Yeti', 'the-yeti', 'cryptids', 47.275547, -120.428416, 'South Wenatchee', 'WA', 'A cryptid site in South Wenatchee, WA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/9634773055', 'America/Los_Angeles'),
  ('Chamber of Commerce Hodag', 'chamber-of-commerce-hodag', 'cryptids', 45.632178, -89.423039, 'Rhinelander', 'WI', 'A cryptid site in Rhinelander, WI, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/2876677463', 'America/Chicago'),
  ('Hodag', 'hodag', 'cryptids', 45.655123, -89.400556, 'Rhinelander', 'WI', 'A cryptid site in Rhinelander, WI, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/7815427682', 'America/Chicago'),
  ('Sasquatch Statue', 'sasquatch-statue', 'cryptids', 48.995582, -122.75162, 'Blaine', 'WA', 'A cryptid site in Blaine, WA, found in OpenStreetMap. Nobody has written this one up yet, so check the source link and the access details before making a special trip.', 'open', 'https://www.openstreetmap.org/node/10065644288', 'America/Vancouver')
on conflict (slug) do update set
  latitude  = excluded.latitude,
  longitude = excluded.longitude,
  city      = excluded.city,
  state     = excluded.state,
  timezone  = excluded.timezone;
-- Note: description is deliberately not updated here. Re-running this must
-- never overwrite a description somebody has written with the placeholder.
