-- Indiana, first batch.
--
-- Two things the checks caught, and they are different kinds of problem.
--
-- World's Largest Ball of Paint is a genuine duplicate — 12 metres from the
-- existing record, flagged by both checks.
--
-- World's Largest Egg is not. Indiana's is at Mentone; the slug already
-- belongs to the egg at Winlock, Washington, two thousand miles away. The
-- coordinate check stayed correctly silent, and the upsert would have moved a
-- Washington egg to Indiana. It goes in as world-s-largest-egg-mentone.
--
-- Five rows arrived with category 'paranormal', which is not in the enum;
-- remapped to 'haunted'. They would have failed on insert.
--
-- Timezone is America/Indiana/Indianapolis rather than America/New_York.
-- Indiana observes Eastern time but has its own zone identifier, and several
-- counties in the northwest and southwest are on Central — worth revisiting if
-- stops are added around Gary or Evansville.
--
-- 49 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Beast of Busco', 'beast-of-busco', 'cryptids', 41.23583, -85.32519, 'Churubusco', 'IN', 'Churubusco''s signature legend began with reports of an enormous snapping turtle called Oscar in Fulk Lake, culminating in a highly publicized attempt to capture it in 1949. The town still embraces the "Beast of Busco" through Turtle Days and a large turtle statue in the community park, giving the cryptid story a clear public stop.', 'open', 'https://visitindiana.in.gov/listing/beast-of-busco/16069/', null, 'America/Indiana/Indianapolis', now()),
  ('Avon Haunted Bridge', 'avon-haunted-bridge', 'folklore', 39.7579, -86.41402, 'Avon', 'IN', 'The railroad bridge west of Indianapolis has accumulated several local ghost stories, most famously involving a mother and child and another tale about a worker supposedly entombed in the structure. The bridge remains an active railroad structure, so OddWay visitors should view it only from legal public areas around Washington Township Park and never walk on the tracks.', 'roadside', 'https://visitindiana.in.gov/blog/post/5-weird-wonderful-must-see-places-near-indy/', null, 'America/Indiana/Indianapolis', now()),
  ('Who North America', 'who-north-america', 'museums', 39.63295, -86.34522, 'Camby', 'IN', 'Who North America began as a Doctor Who merchandise business in 1998 and later opened a dedicated physical location in Camby. Along with the store, visitors can see a museum of Doctor Who merchandise and memorabilia spanning the program''s history, making it one of the country''s most unusually specific pop-culture museums.', 'limited', 'https://www.visitindy.com/directory/who-north-america/', 'https://www.whona.com/', 'America/Indiana/Indianapolis', now()),
  ('Rotary Jail Museum', 'rotary-jail-museum', 'museums', 40.04385, -86.90174, 'Crawfordsville', 'IN', 'Built around a rotating circular cell block, Crawfordsville''s 1882 jail used a hand-cranked mechanism to bring individual cells to the only opening. The preserved structure is now a museum and is notable as the only surviving rotary jail whose cell block can still be operated.', 'limited', 'https://www.rotaryjailmuseum.org/', 'https://www.rotaryjailmuseum.org/', 'America/Indiana/Indianapolis', now()),
  ('Indiana Medical History Museum', 'indiana-medical-history-museum', 'museums', 39.7699, -86.21336, 'Indianapolis', 'IN', 'The museum occupies the 1896 Old Pathology Building of the former Central State Hospital, the oldest surviving pathology facility in the United States. Guided tours retain original laboratories, an autopsy room and an anatomical museum containing preserved specimens, while the remaining former hospital buildings and tunnels elsewhere on the property are posted no-trespassing.', 'limited', 'https://www.imhm.org/about/', 'https://imhm.org/', 'America/Indiana/Indianapolis', now()),
  ('Historic Hannah House', 'historic-hannah-house', 'haunted', 39.71167, -86.14305, 'Indianapolis', 'IN', 'Alexander Moore Hannah built this large brick house in the nineteenth century, and it later became one of Indianapolis''s best-known paranormal locations. The organization preserving the property offers historical access and scheduled paranormal investigations, allowing visitors to experience the site legally instead of relying on abandoned-building lore.', 'limited', 'https://www.historichannahhouse.net/', 'https://www.historichannahhouse.net/', 'America/Indiana/Indianapolis', now()),
  ('Twisted House', 'twisted-house', 'roadside-oddities', 39.87778, -86.14379, 'Indianapolis', 'IN', 'Artist John McNaughton created this warped cedar sculpture to look like a small house twisting upward as though caught in a vortex. It stands on the grounds of the Indianapolis Art Center and can be viewed as part of the center''s outdoor sculpture environment.', 'open', 'https://www.atlasobscura.com/places/twisted-house-sculpture', null, 'America/Indiana/Indianapolis', now()),
  ('Mr. Bendo Muffler Man', 'mr-bendo-muffler-man', 'roadside-oddities', 39.78887, -86.18398, 'Indianapolis', 'IN', 'Mr. Bendo is a towering fiberglass Muffler Man that has served as an Indianapolis auto-shop landmark for decades. The giant figure has survived moves, repairs and changing businesses and remains a recognizable piece of classic American roadside advertising on West 16th Street.', 'roadside', 'https://fotospot.com/attractions/indiana/mr-bendo-muffler-man', null, 'America/Indiana/Indianapolis', now()),
  ('World''s Largest Candle', 'worlds-largest-candle', 'roadside-oddities', 39.8589, -84.9924, 'Centerville', 'IN', 'Warm Glow Candle Company turned its headquarters into a roadside landmark with an enormous candle-shaped structure visible from Interstate 70. The oversized candle rises from the shop complex and gives travelers a straightforward stop built around one of Indiana''s most conspicuous giant-object attractions.', 'open', 'https://visitindiana.in.gov/listing/giant-candle/19529/', null, 'America/Indiana/Indianapolis', now()),
  ('Nancy Kerlin Barnett Grave', 'nancy-kerlin-barnett-grave', 'weird-history', 39.41989, -85.97592, 'Amity', 'IN', 'Nancy Kerlin Barnett was buried here in 1831, and when officials later wanted to build a road through the burial ground, her descendants resisted moving her grave. The compromise left the burial site protected in the middle of County Road 400 South, where traffic still splits around the fenced grave and the additional remains discovered there in 2016.', 'roadside', 'https://www.atlasobscura.com/places/nancy-kerlin-barnett-grave', null, 'America/Indiana/Indianapolis', now()),
  ('Lova''s Dollhouse Grave', 'lovas-dollhouse-grave', 'folklore', 39.63843, -85.56499, 'Arlington', 'IN', 'The grave of young Lova Cline is marked by an elaborate miniature house built by her family rather than a conventional headstone. Local stories later attached eerie details to the little structure, including claims that objects inside change position, making it one of Indiana''s better-known unusual cemetery monuments.', 'open', 'https://www.roadsideamerica.com/story/59389', null, 'America/Indiana/Indianapolis', now()),
  ('Double Parking Meter Tombstone', 'double-parking-meter-tombstone', 'weird-history', 41.24949, -84.83918, 'Harlan', 'IN', 'Archillous "Archie" Arnold''s grave in Scipio Cemetery is flanked by two old parking meters, both permanently reading "Expired." The intentionally comic memorial turns an ordinary rural cemetery visit into one of Indiana''s stranger examples of personalized grave art.', 'open', 'https://www.roadsideamerica.com/story/75086', null, 'America/Indiana/Indianapolis', now()),
  ('Pocket Watch Grave', 'pocket-watch-grave', 'weird-history', 40.48559, -85.98776, 'Greentown', 'IN', 'A grave in Greenlawn Cemetery is marked with an oversized stone pocket watch rather than a standard rectangular monument. The carved watch face and chain make the memorial immediately recognizable and give travelers a specific, respectful cemetery oddity to locate.', 'open', 'https://www.roadsideamerica.com/tip/76259', null, 'America/Indiana/Indianapolis', now()),
  ('Stiffy Green Mausoleum', 'stiffy-green-mausoleum', 'folklore', 39.476, -87.3489, 'Terre Haute', 'IN', 'Terre Haute legend says a bulldog nicknamed Stiffy Green remained devoted to his owner, florist John Heinl, and later became associated with Heinl''s mausoleum in Highland Lawn Cemetery. Stories claim the dog''s green eyes could be seen glowing near the tomb; the original dog figure is now preserved at the Vigo County History Center, while the mausoleum remains the physical location tied to the legend.', 'open', 'https://www.terrehaute.com/things-to-do/experiences/legend-of-stiffy-green/', null, 'America/Indiana/Indianapolis', now()),
  ('Willard Library Grey Lady', 'willard-library-grey-lady', 'haunted', 37.97836, -87.57404, 'Evansville', 'IN', 'Willard Library''s best-known legend concerns the "Grey Lady," an apparition reportedly seen inside the Victorian Gothic library for decades. The library openly embraces the story with its long-running Ghost Cams and paranormal programming, making this an unusually accessible haunted-location stop rather than an abandoned site.', 'open', 'https://www.willardlib.org/ghost-cams', 'https://www.willardlib.org/', 'America/Indiana/Indianapolis', now()),
  ('Story Inn Blue Lady', 'story-inn-blue-lady', 'haunted', 39.09898, -86.21411, 'Story', 'IN', 'Guests at the historic Story Inn have long reported a female apparition known as the Blue Lady, particularly around one of the inn''s rooms. Accounts collected by the property describe details such as the scent of peaches and sightings near a dressing table, while the active inn allows visitors to experience the location through normal lodging and dining access.', 'limited', 'https://storyinn.com/', 'https://storyinn.com/', 'America/Indiana/Indianapolis', now()),
  ('Whispers Estate', 'whispers-estate', 'haunted', 38.73332, -86.47452, 'Mitchell', 'IN', 'Built in the 1890s, this house has been operated specifically as a paranormal attraction rather than simply marketed through outside ghost stories. Whispers Estate offers scheduled investigations and events centered on reported voices, apparitions, movement and other unexplained activity inside the property.', 'limited', 'https://whispersestate.com/', 'https://whispersestate.com/', 'America/Indiana/Indianapolis', now()),
  ('Edna Collins Covered Bridge', 'edna-collins-covered-bridge', 'folklore', 39.7275, -86.97633, 'Clinton Falls', 'IN', 'The 1922 Edna Collins Covered Bridge crosses Little Walnut Creek and carries one of Putnam County''s persistent ghost stories. Local legend tells of a girl named Edna who would wait for her parents to honk three times at the bridge and is now supposedly connected to unexplained sounds and sightings around the structure.', 'roadside', 'https://ourhistoricalindiana.blogspot.com/2020/11/edna-collings-bridge.html', null, 'America/Indiana/Indianapolis', now()),
  ('Footprints of the Archangel Gabriel', 'footprints-of-the-archangel-gabriel', 'folklore', 38.12996, -87.93482, 'New Harmony', 'IN', 'New Harmony tradition once claimed that the Archangel Gabriel visited communal leader George Rapp in 1819 and left footprints impressed into a limestone slab. The weathered slab still survives behind a brick wall near Church and Main Streets, but it is on private property and should only be viewed from the public sidewalk through or over the wall.', 'private', 'https://www.roadsideamerica.com/story/19391', null, 'America/Indiana/Indianapolis', now()),
  ('Rose Island Ruins', 'rose-island-ruins', 'weird-history', 38.44975, -85.64556, 'Charlestown', 'IN', 'Rose Island was once a popular amusement park with rides, a swimming pool, zoo attractions and river access before the catastrophic Ohio River flood of 1937 left it beyond repair. Charlestown State Park now maintains a trail to the former park area, where visitors can see surviving foundations, the old pool and other ruins in the woods.', 'open', 'https://www.in.gov/dnr/state-parks/parks-lakes/charlestown-state-park/', null, 'America/Indiana/Indianapolis', now()),
  ('Old Ben and the Giant Sycamore Stump', 'old-ben-and-the-giant-sycamore-stump', 'roadside-oddities', 40.46917, -86.14389, 'Kokomo', 'IN', 'Highland Park preserves two major Kokomo oddities under neighboring shelters: Old Ben, a famously enormous steer born in 1902 and preserved by taxidermy after his death, and the huge stump of an ancient sycamore. Combining them into one stop avoids sending travelers to duplicate coordinates while preserving both pieces of Kokomo roadside history.', 'open', 'https://www.atlasobscura.com/places/old-ben-pavilion-worlds-largest-steer', null, 'America/Indiana/Indianapolis', now()),
  ('KokoMantis', 'kokomantis', 'roadside-oddities', 40.48658, -86.13351, 'Kokomo', 'IN', 'KokoMantis is a giant praying mantis assembled from salvaged industrial material, including World War II-era fuel pontoons and recycled traffic-light poles. The roughly 17-foot-high sculpture stands downtown at Washington and Sycamore Streets and is one of Kokomo''s most recognizable modern roadside oddities.', 'open', 'https://www.atlasobscura.com/places/kokomantis-scrap-art-sculpture', null, 'America/Indiana/Indianapolis', now()),
  ('Hall of Heroes Superhero Museum', 'hall-of-heroes-superhero-museum', 'museums', 41.71065, -85.97253, 'Elkhart', 'IN', 'The Hall of Heroes is a museum devoted specifically to the history of superheroes across comics, film, animation, toys and related memorabilia. Its large collection includes rare comics, original art and screen-related artifacts, giving OddWay a strong niche museum stop rather than a general history museum.', 'limited', 'https://hallofheroesmuseum.com/', 'https://hallofheroesmuseum.com/', 'America/Indiana/Indianapolis', now()),
  ('Studebaker National Museum', 'studebaker-national-museum', 'museums', 41.67471, -86.26193, 'South Bend', 'IN', 'South Bend''s Studebaker museum preserves vehicles and artifacts from the company that evolved from nineteenth-century wagon building into a major automobile manufacturer. Among its most unusual historic vehicles are presidential carriages, including the carriage associated with Abraham Lincoln''s final trip to Ford''s Theatre.', 'limited', 'https://www.studebakermuseum.org/', 'https://www.studebakermuseum.org/', 'America/Indiana/Indianapolis', now()),
  ('Indiana Dinosaur Museum', 'indiana-dinosaur-museum', 'museums', 41.70768, -86.34659, 'South Bend', 'IN', 'This newer South Bend museum is devoted to dinosaurs and paleontology, with large fossil displays, mounted skeletons and working scientific material rather than only fiberglass roadside models. Its unusual pairing with the adjacent South Bend Chocolate Company destination makes it a strong family-friendly OddWay stop.', 'limited', 'https://www.indianadinosaurmuseum.org/', 'https://www.indianadinosaurmuseum.org/', 'America/Indiana/Indianapolis', now()),
  ('International Circus Hall of Fame', 'international-circus-hall-of-fame', 'museums', 40.75444, -86.01972, 'Peru', 'IN', 'The museum occupies part of the former Wallace Circus winter quarters, a site that helped make Peru one of America''s most important circus towns. Historic wagons, circus buildings, memorabilia and performers'' history survive on the property, which is designated a National Historic Landmark.', 'limited', 'https://circushalloffame.com/', 'https://circushalloffame.com/', 'America/Indiana/Indianapolis', now()),
  ('Grissom Air Museum', 'grissom-air-museum', 'museums', 40.66952, -86.13061, 'Peru', 'IN', 'Located just outside the former Grissom Air Force Base, the museum preserves a large outdoor air park of military aircraft along with indoor Cold War and aviation exhibits. The collection includes fighters, bombers, transports and other aircraft that make the site visually distinct from a conventional local museum.', 'limited', 'https://www.grissomairmuseum.com/', 'https://www.grissomairmuseum.com/', 'America/Indiana/Indianapolis', now()),
  ('Dr. Ted''s Musical Marvels', 'dr-teds-musical-marvels', 'museums', 38.20816, -86.97477, 'Dale', 'IN', 'Dr. Ted Waflart assembled a collection of self-playing musical machines ranging from small music boxes to enormous orchestrions and dance organs. The unusual part is that many of the instruments are demonstrated rather than left silent, but access is generally arranged for pre-scheduled groups, so travelers should call before routing here.', 'limited', 'https://www.atlasobscura.com/places/dr-teds-musical-marvels', null, 'America/Indiana/Indianapolis', now()),
  ('Historic Santa Claus Statue', 'historic-santa-claus-statue', 'roadside-oddities', 38.11567, -86.91013, 'Santa Claus', 'IN', 'This large Santa statue was dedicated in 1935 and became an early physical symbol of the town that had already turned its unusual name into a Christmas identity. Restored and now standing at the Santa Claus Museum & Village, it gives visitors a historic roadside Santa rather than a modern seasonal decoration.', 'open', 'https://www.hmdb.org/m.asp?m=286726', 'https://santaclausmuseum.org/', 'America/Indiana/Indianapolis', now()),
  ('Squire Boone Caverns', 'squire-boone-caverns', 'weird-history', 38.065, -86.13355, 'Mauckport', 'IN', 'Squire Boone, younger brother of Daniel Boone, settled in this area and developed a gristmill near the cave system in the early nineteenth century. His remains are associated with the cavern property, where guided tours descend through underground rooms, streams and formations around a site carrying both natural and frontier history.', 'limited', 'https://squireboonecaverns.com/', 'https://squireboonecaverns.com/', 'America/Indiana/Indianapolis', now()),
  ('Marengo Cave', 'marengo-cave', 'roadside-oddities', 38.37552, -86.3395, 'Marengo', 'IN', 'Discovered by children in 1883, Marengo Cave grew into one of Indiana''s best-known commercial cave systems and is designated a U.S. National Natural Landmark. Guided routes take visitors through large underground rooms and extensive formations while preserving a very old-school roadside cave-attraction feel.', 'limited', 'https://www.marengocave.com/', 'https://www.marengocave.com/', 'America/Indiana/Indianapolis', now()),
  ('Indiana Caverns', 'indiana-caverns', 'roadside-oddities', 38.1825, -86.15017, 'Corydon', 'IN', 'Indiana Caverns provides public access to part of the Binkley Cave system, one of the state''s major underground networks. Cave exploration in the system has revealed Ice Age animal remains and other paleontological material, while the commercial tour combines walking and underground boat travel.', 'limited', 'https://indianacaverns.com/', 'https://indianacaverns.com/', 'America/Indiana/Indianapolis', now()),
  ('Constitution Elm', 'constitution-elm', 'weird-history', 38.21348, -86.12734, 'Corydon', 'IN', 'Delegates drafting Indiana''s first state constitution met beneath a huge elm in Corydon in 1816 because the territorial capitol building was too hot. The tree died in 1925, but its enormous preserved trunk remains under a protective sandstone shelter at the historic site.', 'open', 'https://www.atlasobscura.com/places/constitution-elm', null, 'America/Indiana/Indianapolis', now()),
  ('Jug Rock', 'jug-rock', 'roadside-oddities', 38.67593, -86.79715, 'Shoals', 'IN', 'Jug Rock is an isolated sandstone formation shaped like a giant stone vessel and is one of the largest free-standing table-rock formations east of the Mississippi River. It sits beside a short public access trail near Shoals, giving OddWay a natural oddity that can be visited without a major hike.', 'open', 'https://www.atlasobscura.com/places/jug-rock', null, 'America/Indiana/Indianapolis', now()),
  ('Providence Home Geode Grotto', 'providence-home-geode-grotto', 'roadside-oddities', 38.3943, -86.93718, 'Jasper', 'IN', 'Beginning in the 1960s, Father Phillip Ottavi directed the creation of an enormous religious art environment using geodes, concrete, stone and imported statuary. The resulting shrines, grottoes, planters and garden structures spread across several blocks and remain free and open to the public.', 'open', 'https://spacesarchives.org/explore/search-the-online-collection/o1182449609/', null, 'America/Indiana/Indianapolis', now()),
  ('World''s Largest In-Situ Celtic Cross', 'worlds-largest-in-situ-celtic-cross', 'roadside-oddities', 37.91714, -86.66565, 'Cannelton', 'IN', 'Sculptor Greg Harris spent 23 months carving a High Celtic Cross directly through a massive natural sandstone slab on the Blue Heron Vineyard property. The owners describe it as the largest known in-situ Celtic Cross, meaning it was carved from stone still naturally embedded in the hillside; access follows the winery''s property hours.', 'limited', 'https://www.blueheronvines.com/celtic-cross.html', 'https://www.blueheronvines.com/', 'America/Indiana/Indianapolis', now()),
  ('Buried in Her Cadillac', 'buried-in-her-cadillac', 'weird-history', 39.02583, -84.88778, 'Aurora', 'IN', 'Aurora Schuck was buried at River View Cemetery in 1989 inside her red 1976 Cadillac Eldorado, reportedly requiring a burial area spanning multiple normal grave plots. Nothing dramatic rises above the burial today, but the cemetery itself is public and the bizarre interment story gives the site an unusually literal connection between car culture and burial custom.', 'open', 'https://www.roadsideamerica.com/tip/76516', 'https://aurorariverviewcemetery.com/', 'America/Indiana/Indianapolis', now()),
  ('Colgate Clock', 'colgate-clock', 'roadside-oddities', 38.27463, -85.75287, 'Clarksville', 'IN', 'The enormous Colgate Clock was originally installed at the company''s Jersey City plant before being moved to the Clarksville factory complex in the 1920s. Its roughly 40-foot face survives as a giant industrial landmark along the Ohio River even though toothpaste production at the old plant has ended.', 'roadside', 'https://www.atlasobscura.com/places/colgate-clock', null, 'America/Indiana/Indianapolis', now()),
  ('World''s Largest Egg', 'world-s-largest-egg-mentone', 'roadside-oddities', 41.1734, -86.0349, 'Mentone', 'IN', 'Mentone''s approximately ten-to-twelve-foot concrete egg was built in 1946 to advertise the community''s egg industry and festival. It still stands downtown emblazoned with "The Egg Basket of the Midwest," preserving a wonderfully literal piece of small-town promotional history.', 'open', 'https://www.roadsideamerica.com/tip/471', null, 'America/Indiana/Indianapolis', now()),
  ('Paul Bunyan Muffler Man', 'paul-bunyan-muffler-man', 'roadside-oddities', 40.18319, -85.4207, 'Muncie', 'IN', 'A roughly 25-foot Paul Bunyan-style fiberglass giant has stood in Muncie since the mid-twentieth-century roadside-advertising era. Originally connected to a lumber business, the figure later moved to the property near Kilgore Avenue and remains one of Indiana''s classic Muffler Man survivors.', 'roadside', 'https://visitindiana.in.gov/blog/post/roadside-attractions/', null, 'America/Indiana/Indianapolis', now()),
  ('Berne Clock Tower', 'berne-clock-tower', 'roadside-oddities', 40.65815, -84.95537, 'Berne', 'IN', 'Berne built its 160-foot clock tower in 2010 as an elaborate tribute to the Zytglogge in Bern, Switzerland and the town''s Swiss heritage. The public Muensterberg Plaza also stages a mechanical glockenspiel presentation several times a day, complete with large moving figures.', 'open', 'https://www.berneclocktower.org/', 'https://www.berneclocktower.org/', 'America/Indiana/Indianapolis', now()),
  ('The Big Peach', 'the-big-peach', 'roadside-oddities', 38.78835, -87.47035, 'Bruceville', 'IN', 'A giant peach rises beside this seasonal farm market in southern Indiana, a deliberately oversized symbol for a business promoting locally grown fruit. The market traditionally operates during the warmer growing season, so the sculpture is best treated as a seasonal business stop rather than guaranteed year-round access.', 'limited', 'https://visitindiana.in.gov/blog/post/roadside-attractions/', null, 'America/Indiana/Indianapolis', now()),
  ('Future Birthplace of Captain Kathryn Janeway', 'future-birthplace-of-captain-kathryn-janeway', 'roadside-oddities', 39.16589, -86.53617, 'Bloomington', 'IN', 'Star Trek: Voyager establishes Captain Kathryn Janeway as being born in Bloomington in the twenty-fourth century, giving the real city the unusual opportunity to commemorate a person who has not technically been born yet. A dedicated monument marks her "future birthplace" downtown and has become a pilgrimage stop for Star Trek fans.', 'open', 'https://janewaystatue.com/', 'https://janewaystatue.com/', 'America/Indiana/Indianapolis', now()),
  ('Prophet''s Rock', 'prophets-rock', 'weird-history', 40.50458, -86.85153, 'Battle Ground', 'IN', 'Tradition identifies this rocky overlook as the place where Tenskwatawa, known as the Prophet, watched or encouraged Native forces during the Battle of Tippecanoe in November 1811. A marker and public pull-off identify the location today, though interpretations of the battle should be understood within the larger history of Indigenous resistance to U.S. expansion.', 'open', 'https://www.hmdb.org/m.asp?m=6434', null, 'America/Indiana/Indianapolis', now()),
  ('Culbertson Mansion', 'culbertson-mansion', 'haunted', 38.2864, -85.8128, 'New Albany', 'IN', 'Industrialist William Culbertson began building this elaborate Second Empire mansion in 1867, filling it with ornate woodwork, painted ceilings and other high Victorian details. The state historic site is also widely associated with local haunting stories and seasonal paranormal programming, giving visitors a legitimate way to experience the building rather than approaching a private haunted house.', 'limited', 'https://www.in.gov/history/state-historical-markers/find-a-marker/culbertson-mansion/', 'https://www.indianamuseum.org/historic-sites/culbertson-mansion/', 'America/Indiana/Indianapolis', now()),
  ('Giant Santa', 'giant-santa', 'roadside-oddities', 38.08585, -87.55695, 'Evansville', 'IN', 'Built in 1974, this approximately 35-foot Santa spent years moving between displays, a truck stop and even a junkyard before supporters restored it in 2016. It now stands upright again beside US 41, with a walkway and parking specifically allowing travelers to stop for photos.', 'open', 'https://www.roadsideamerica.com/story/11853', null, 'America/Indiana/Indianapolis', now()),
  ('Martini-Drinking Pink Elephant', 'martini-drinking-pink-elephant', 'roadside-oddities', 39.92987, -85.85252, 'Fortville', 'IN', 'A huge pink elephant holding a martini glass sits on a trailer outside a Fortville beverage business, turning the old "seeing pink elephants" expression into literal advertising. The statue is occasionally moved for parades but normally serves as one of central Indiana''s most unmistakable roadside photo stops.', 'roadside', 'https://visitindiana.in.gov/blog/post/roadside-attractions/', null, 'America/Indiana/Indianapolis', now()),
  ('Smiley Face Water Tower', 'smiley-face-water-tower', 'roadside-oddities', 41.52581, -85.06694, 'Ashley', 'IN', 'Ashley''s municipal water tower has a giant smiling face painted across it and has become so recognizable that the town itself promotes the "Smiley Face" identity. The tower stands by Ashley Memorial Park, providing a public place to stop rather than forcing visitors to photograph it from a highway shoulder.', 'open', 'https://ashley.in.gov/', null, 'America/Indiana/Indianapolis', now()),
  ('Uranus Fudge Factory & General Store', 'uranus-fudge-factory-general-store', 'roadside-oddities', 40.06145, -85.70098, 'Anderson', 'IN', 'Indiana''s first Uranus Fudge Factory opened in Anderson in 2022 and commits completely to its deliberately ridiculous name through signs, jokes, photo opportunities and a general store built around fudge. The active business also includes ice cream and seasonal mini golf, making it a modern roadside attraction rather than merely a novelty sign.', 'open', 'https://uranusindiana.com/anderson/', 'https://uranusindiana.com/', 'America/Indiana/Indianapolis', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;
