-- Indiana, second batch, plus a timezone correction to the first.
--
-- Mooresville Gravity Hill dropped: already in the index from the
-- OpenStreetMap scan, 215 metres away.
--
-- World's Largest Rocking Chair goes in as
-- world-s-largest-rocking-chair-franklin, because Casey, Illinois holds the
-- plain slug. Two different giant chairs.
--
-- Timezones are looked up per coordinate. Indiana is mostly Eastern but a
-- dozen counties in the northwest and southwest keep Central time, and the
-- opening-hours logic reads this field to decide whether somewhere is open
-- now. I assumed Eastern for the whole state in the first batch, which was
-- wrong for 10 of those stops; the updates at the end fix them.
--
-- Points near the Michigan and Kentucky borders resolve to America/Detroit or
-- America/Kentucky/Louisville, which keep identical Eastern rules but are the
-- wrong label for an Indiana stop. Those are normalised.
--
-- The four New Harmony entries sit within 850 metres of each other. Not
-- duplication: New Harmony was a nineteenth-century utopian settlement and the
-- whole village is the attraction.
--
-- 49 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Auburn Cord Duesenberg Automobile Museum', 'auburn-cord-duesenberg-automobile-museum', 'museums', 41.35579, -85.0573, 'Auburn', 'IN', 'This museum occupies the restored 1930 Art Deco headquarters of the Auburn Automobile Company and preserves more than a century of Indiana automotive history. The building itself is part of the attraction, with period offices and showrooms surrounding rare Auburn, Cord and Duesenberg automobiles.', 'open', 'https://automobilemuseum.org/', 'https://automobilemuseum.org/', 'America/Indiana/Indianapolis', now()),
  ('National Auto & Truck Museum', 'national-auto-truck-museum', 'museums', 41.35558, -85.05868, 'Auburn', 'IN', 'NATMUS occupies surviving Auburn Automobile Company factory buildings next door to the Auburn Cord Duesenberg Museum. Its collection includes unusual cars, trucks, prototypes, automotive signs and GM Futurliner No. 10, one of the enormous vehicles built for General Motors'' Parade of Progress.', 'open', 'https://natmus.org/', 'https://natmus.org/', 'America/Indiana/Indianapolis', now()),
  ('Clayshire Castle', 'clayshire-castle', 'roadside-oddities', 39.39782, -86.94701, 'Bowling Green', 'IN', 'This modern medieval-style castle was built in the Indiana countryside as a private residence and bed-and-breakfast, complete with towers, stonework and themed rooms. It is not an abandoned castle or public park, so interior access should be limited to booked guests or scheduled events.', 'limited', 'https://www.roadsideamerica.com/tip/43906', 'https://clayshirecastle.com/', 'America/Indiana/Indianapolis', now()),
  ('Champ the Giant Great Dane', 'champ-the-giant-great-dane', 'roadside-oddities', 39.5395, -87.0577, 'Brazil', 'IN', 'A towering fiberglass Great Dane named Champ has watched over this US 40 property for decades. The dog dates to the classic era of oversized roadside advertising and has been restored and repainted several times while remaining a recognizable Brazil-area landmark.', 'roadside', 'https://www.roadsideamerica.com/tip/16289', null, 'America/Indiana/Indianapolis', now()),
  ('Market Street Catacombs', 'market-street-catacombs', 'weird-history', 39.76858, -86.15344, 'Indianapolis', 'IN', 'Beneath Indianapolis'' historic City Market lies roughly 20,000 square feet of brick and limestone passages once used for cool storage beneath the market halls. The catacombs have historically opened only for scheduled tours and were closed during City Market redevelopment, so access should be verified before OddWay routes a traveler inside.', 'limited', 'https://www.atlasobscura.com/places/market-street-catacombs', 'https://www.indianalandmarks.org/', 'America/Indiana/Indianapolis', now()),
  ('Johnny Appleseed Grave', 'johnny-appleseed-grave', 'folklore', 41.11223, -85.12244, 'Fort Wayne', 'IN', 'John Chapman, better known as Johnny Appleseed, died near Fort Wayne in 1845 after decades of planting and tending orchards across the frontier. A prominent memorial in Johnny Appleseed Park marks the burial place traditionally accepted as his grave, giving the American folk figure a real public destination.', 'open', 'https://www.atlasobscura.com/places/grave-of-johnny-appleseed', null, 'America/Indiana/Indianapolis', now()),
  ('Schimpff''s Confectionery and Candy Museum', 'schimpffs-confectionery-and-candy-museum', 'museums', 38.27258, -85.74136, 'Jeffersonville', 'IN', 'The Schimpff family has operated this downtown candy business at its present site since 1891. Its museum preserves antique candy equipment, packaging and memorabilia, and visitors can often watch candy being made on machinery that looks almost as unusual as the collection itself.', 'open', 'https://www.atlasobscura.com/places/schimpffs-confectionery', 'https://www.schimpffs.com/', 'America/Indiana/Indianapolis', now()),
  ('Dunn''s Bridge', 'dunns-bridge', 'folklore', 41.22015, -86.96897, 'Wheatfield', 'IN', 'This unusual steel bridge over the Kankakee River carries a persistent local story that some of its metal came from the original 1893 Chicago World''s Fair Ferris wheel. The bridge itself is real and historically significant, while the Ferris-wheel connection is best treated as legend rather than settled fact.', 'open', 'https://www.hmdb.org/m.asp?m=269431', null, 'America/Chicago', now()),
  ('Indianapolis Moon Tree', 'indianapolis-moon-tree', 'weird-history', 39.7683, -86.162, 'Indianapolis', 'IN', 'This sycamore grew from a seed carried around the Moon aboard Apollo 14 in 1971 as part of astronaut Stuart Roosa''s famous seed experiment. Planted in Indianapolis during the U.S. Bicentennial era, it is one of the surviving "Moon Trees" scattered across the country.', 'open', 'https://www.atlasobscura.com/places/indianapolis-moon-tree', null, 'America/Indiana/Indianapolis', now()),
  ('The Ruins at Holliday Park', 'the-ruins-at-holliday-park', 'roadside-oddities', 39.87082, -86.16339, 'Indianapolis', 'IN', 'Three massive stone figures from the demolished St. Paul Building in New York City were rescued and incorporated into a strange architectural installation in Holliday Park. The sculptures now rise from a deliberately ruined-looking structure that combines public art with pieces of a vanished skyscraper.', 'open', 'https://www.atlasobscura.com/places/the-ruins-indianapolis-indiana', 'https://www.hollidaypark.org/', 'America/Indiana/Indianapolis', now()),
  ('New Harmony Labyrinth', 'new-harmony-labyrinth', 'folklore', 38.12244, -87.93591, 'New Harmony', 'IN', 'The Harmonists who founded New Harmony in the early nineteenth century used a labyrinth as a spiritual symbol of the difficult path toward enlightenment. Today''s hedge labyrinth recreates that tradition around a small temple and is open to visitors year-round without admission.', 'open', 'https://www.atlasobscura.com/places/new-harmony-labyrinth', null, 'America/Chicago', now()),
  ('City West Ghost Town', 'city-west-ghost-town', 'weird-history', 41.6632, -87.06315, 'Chesterton', 'IN', 'City West was platted on the Lake Michigan shore in the 1830s with ambitions of becoming a major city and port. The Panic of 1837 helped kill the development, and shifting dunes eventually swallowed nearly every trace; the former townsite is now within Indiana Dunes State Park.', 'open', 'https://www.atlasobscura.com/places/city-west-ghost-town', null, 'America/Chicago', now()),
  ('West Baden Springs Hotel', 'west-baden-springs-hotel', 'weird-history', 38.56722, -86.61806, 'West Baden Springs', 'IN', 'When the present hotel opened in 1902, its enormous free-spanning atrium dome was considered an engineering marvel and was promoted as the "Eighth Wonder of the World." The restored building is again an operating hotel, but public areas and scheduled tours allow travelers to see the surreal circular interior legally.', 'limited', 'https://www.asce.org/about-civil-engineering/history-and-heritage/historic-landmarks/west-baden-springs-hotel/', 'https://www.frenchlick.com/', 'America/Indiana/Indianapolis', now()),
  ('Bluespring Caverns', 'bluespring-caverns', 'roadside-oddities', 38.79618, -86.54603, 'Bedford', 'IN', 'Bluespring Caverns contains one of the longest known cave systems in Indiana and an extensive navigable underground river. Commercial tours take visitors by boat through the dark cave system rather than along a standard walking path.', 'limited', 'https://www.atlasobscura.com/places/bluespring-caverns', 'https://www.bluespringcaverns.com/', 'America/Indiana/Indianapolis', now()),
  ('Maconaquah''s Grave — Slocum Cemetery', 'maconaquahs-grave-slocum-cemetery', 'weird-history', 40.69852, -85.90759, 'Wabash', 'IN', 'This family cemetery contains the grave of Maconaquah, the Miami woman long known in American histories as Frances Slocum after she was taken from her Pennsylvania family as a child and raised among the Miami. She later chose to remain with her Miami family rather than return east, making the cemetery an important physical site for a complicated story often flattened into frontier folklore.', 'open', 'https://www.atlasobscura.com/places/the-slocum-cemetery', null, 'America/Indiana/Indianapolis', now()),
  ('A Healing Palindrome', 'a-healing-palindrome', 'roadside-oddities', 38.13186, -87.93856, 'New Harmony', 'IN', 'Behind New Harmony''s Atheneum stands a marker for the Kcymaerxthaere project, a worldwide network of plaques and installations describing an invented parallel geography. This piece, titled "A Healing Palindrome," deliberately blurs public art, fictional history and real-world place.', 'open', 'https://kcymaerxthaere.com/historicalsite/a-healing-palindrome/', null, 'America/Chicago', now()),
  ('Working Men''s Institute', 'working-mens-institute', 'museums', 38.12867, -87.93636, 'New Harmony', 'IN', 'Founded in 1838 with help from scientist and philanthropist William Maclure, the Working Men''s Institute is Indiana''s oldest continuously operating public library. Its upstairs museum contains natural-history specimens, artifacts and collections that preserve New Harmony''s unusually dense legacy of utopian communities and scientific experimentation.', 'open', 'https://www.atlasobscura.com/places/working-mens-institute', 'https://workingmensinstitute.org/', 'America/Chicago', now()),
  ('Roofless Church', 'roofless-church', 'roadside-oddities', 38.13138, -87.93501, 'New Harmony', 'IN', 'Architect Philip Johnson designed this open-air sacred space in 1960 around a central sculptural canopy rather than enclosing the congregation beneath a conventional roof. Its stark walls, gates and dome make it one of New Harmony''s most visually unusual structures.', 'open', 'https://www.atlasobscura.com/places/the-roofless-church-new-harmony-indiana', null, 'America/Chicago', now()),
  ('Kerr Lock Ruins', 'kerr-lock-ruins', 'weird-history', 40.83718, -85.72538, 'Lagro', 'IN', 'Stone remains beside the Wabash River preserve part of a lock from the Wabash and Erie Canal, once one of the longest canal systems in North America. A public trail now passes the nineteenth-century masonry, allowing travelers to inspect infrastructure from a transportation network that almost completely disappeared.', 'open', 'https://www.atlasobscura.com/places/kerr-lock', null, 'America/Indiana/Indianapolis', now()),
  ('Hanging Rock National Natural Landmark', 'hanging-rock-national-natural-landmark', 'roadside-oddities', 40.83, -85.70733, 'Lagro', 'IN', 'Hanging Rock is the exposed remnant of an ancient coral reef formed hundreds of millions of years before Indiana existed as dry land. The limestone bluff rises abruptly over the Wabash River and is protected as a National Natural Landmark.', 'open', 'https://www.atlasobscura.com/places/hanging-rock-national-natural-landmark', null, 'America/Indiana/Indianapolis', now()),
  ('Modoc''s Market', 'modocs-market', 'weird-history', 40.79663, -85.82198, 'Wabash', 'IN', 'The shop''s name recalls Modoc, a circus elephant that escaped in Wabash in 1942 and famously crashed through a downtown drugstore during the commotion. A business now operating at the historic location keeps the story alive with elephant imagery and local memorabilia.', 'open', 'https://www.atlasobscura.com/places/modocs-market', null, 'America/Indiana/Indianapolis', now()),
  ('Bilby Tower', 'bilby-tower', 'weird-history', 39.11805, -85.29394, 'Osgood', 'IN', 'U.S. Coast and Geodetic Surveyor Jasper Bilby designed a distinctive steel surveying tower in the 1920s that could be erected quickly above trees and terrain. One surviving tower stands near Osgood as a rare monument to the pre-satellite era of precision mapping.', 'roadside', 'https://www.atlasobscura.com/places/bilby-tower', 'https://www.in.gov/history/markers/4326.htm', 'America/Indiana/Indianapolis', now()),
  ('Century of Progress Homes', 'century-of-progress-homes', 'weird-history', 41.68476, -86.99881, 'Beverly Shores', 'IN', 'Five experimental houses from Chicago''s 1933–34 Century of Progress World''s Fair were moved across Lake Michigan to Indiana after the exposition. Their futuristic materials and designs survive along the lakeshore in Indiana Dunes National Park; exteriors can be viewed year-round, while interior tours are normally limited to special events.', 'open', 'https://www.atlasobscura.com/places/century-of-progress-architectural-district', null, 'America/Chicago', now()),
  ('Bob Ross Experience', 'bob-ross-experience', 'museums', 40.20269, -85.39274, 'Muncie', 'IN', 'Many episodes of The Joy of Painting were recorded in an unassuming studio inside Muncie''s historic Lucius L. Ball home. The room has been recreated as part of the Bob Ross Experience, with original paintings, artifacts and the actual setting associated with one of television''s most recognizable painters.', 'limited', 'https://visitindiana.in.gov/listing/bob-ross-experience/11963/', 'https://www.minnetrista.net/bobrossexperience', 'America/Indiana/Indianapolis', now()),
  ('Saint Anne Shell Chapel', 'saint-anne-shell-chapel', 'roadside-oddities', 39.5093, -87.4579, 'Saint Mary-of-the-Woods', 'IN', 'Sisters of Providence constructed this tiny nineteenth-century chapel and covered its interior with shells, creating an unexpectedly ornate space in the Indiana woods. The historic structure has undergone preservation work, so interior access can vary and tours should be checked before visiting.', 'limited', 'https://spsmw.org/visit/must-sees/saint-anne-shell-chapel/', null, 'America/Indiana/Indianapolis', now()),
  ('Stepp Cemetery', 'stepp-cemetery', 'folklore', 39.31428, -86.43024, 'Martinsville', 'IN', 'This small cemetery inside Morgan-Monroe State Forest has become the center of a long-running "Lady in Black" legend involving a grieving woman said to linger near an old tree and grave. The haunting is folklore, not established fact, and visitors should treat the active cemetery respectfully and use normal daylight forest access.', 'open', 'https://www.hauntedplaces.org/item/stepp-cemetery/', null, 'America/Indiana/Indianapolis', now()),
  ('Hindostan Falls Ghost Town', 'hindostan-falls-ghost-town', 'weird-history', 38.6245, -86.85083, 'Shoals', 'IN', 'Hindostan was once a promising early Indiana settlement on the White River before disease and economic decline emptied the community in the 1820s. Little of the town survives today, but the public recreation area at Hindostan Falls preserves the landscape and remnants associated with one of the state''s earliest ghost towns.', 'open', 'https://www.in.gov/dnr/fish-and-wildlife/properties/hindostan-falls-public-fishing-area/', null, 'America/Indiana/Vincennes', now()),
  ('Angel Mounds State Historic Site', 'angel-mounds-state-historic-site', 'weird-history', 37.93886, -87.46023, 'Evansville', 'IN', 'Between roughly A.D. 1000 and 1450, Mississippian people built a major town here containing large earthen platform mounds, plazas and houses. The preserved archaeological site and museum allow visitors to encounter the landscape without treating the Indigenous city as a mysterious or vanished-civilization legend.', 'limited', 'https://www.indianamuseum.org/historic-sites/angel-mounds/', null, 'America/Chicago', now()),
  ('Mounds State Park Earthworks', 'mounds-state-park-earthworks', 'weird-history', 40.09576, -85.62007, 'Anderson', 'IN', 'Mounds State Park protects a group of prehistoric earthworks constructed by Indigenous peoples beginning more than two thousand years ago. The largest, the Great Mound, is an impressive circular earthwork that can be reached from maintained park trails.', 'open', 'https://www.in.gov/dnr/state-parks/parks-lakes/mounds-state-park/', null, 'America/Indiana/Indianapolis', now()),
  ('Falls of the Ohio Fossil Beds', 'falls-of-the-ohio-fossil-beds', 'roadside-oddities', 38.2725, -85.7609, 'Clarksville', 'IN', 'When river conditions are low, enormous exposed limestone beds reveal fossils from a Devonian sea that covered the region roughly 390 million years ago. The state park protects one of the world''s largest exposed Devonian fossil beds and provides a visitor center overlooking the site.', 'open', 'https://www.in.gov/dnr/state-parks/parks-lakes/falls-of-the-ohio-state-park/', null, 'America/Indiana/Indianapolis', now()),
  ('Pigeon Roost State Historic Site', 'pigeon-roost-state-historic-site', 'weird-history', 38.617, -85.77644, 'Scottsburg', 'IN', 'This rural memorial marks the location of the Pigeon Roost settlement and a deadly 1812 attack during the violent frontier conflict surrounding the War of 1812. The state historic site preserves the location and memorial while modern interpretation places the event within the larger conflict between Indigenous nations, settlers and U.S. expansion.', 'open', 'https://secure.in.gov/history/state-historical-markers/find-a-marker/pigeon-roost/', null, 'America/Indiana/Indianapolis', now()),
  ('Chief Menominee Monument and Trail of Death Site', 'chief-menominee-monument-and-trail-of-death-site', 'weird-history', 41.29565, -86.36177, 'Plymouth', 'IN', 'A 17-foot granite memorial marks the homeland of Potawatomi leader Menominee and the starting area associated with the forced 1838 removal remembered as the Potawatomi Trail of Death. The monument was dedicated in 1909 and is significant as an early government-funded memorial to a Native American leader.', 'open', 'https://www.visitmarshallcounty.in/history-culture', null, 'America/Indiana/Indianapolis', now()),
  ('Camp Atterbury POW Chapel', 'camp-atterbury-pow-chapel', 'weird-history', 39.37572, -86.06832, 'Edinburgh', 'IN', 'Italian prisoners of war held at Camp Atterbury built this tiny Catholic chapel in 1943 using limited and salvaged materials. Restored after later vandalism and fire damage, the Chapel in the Meadow survives as a rare physical remnant of the camp''s World War II prisoner compound.', 'limited', 'https://www.atlasobscura.com/places/camp-atterbury-prisoner-of-war-chapel', 'https://www.in.gov/indiana-national-guard/about/history-and-museums/', 'America/Indiana/Indianapolis', now()),
  ('Gus Grissom Boyhood Home', 'gus-grissom-boyhood-home', 'museums', 38.72994, -86.47267, 'Mitchell', 'IN', 'Virgil "Gus" Grissom grew up in this modest Mitchell house before becoming one of the original Mercury Seven astronauts and later commanding Gemini 3. The preserved home is operated as a small museum devoted to his childhood and early life, providing a more personal counterpoint to large space museums.', 'limited', 'https://www.hmdb.org/m.asp?m=195330', null, 'America/Indiana/Indianapolis', now()),
  ('Shrine of Christ''s Passion', 'shrine-of-christs-passion', 'roadside-oddities', 41.42581, -87.47078, 'St. John', 'IN', 'This large outdoor devotional attraction uses dozens of life-size bronze sculptures to create an immersive walking route through scenes from the Passion of Christ. Regardless of religious interest, its scale and elaborate staged environments make it an unusually ambitious roadside art installation.', 'open', 'https://shrineofchristspassion.org/', 'https://shrineofchristspassion.org/', 'America/Chicago', now()),
  ('John Dillinger''s Grave', 'john-dillingers-grave', 'weird-history', 39.82212, -86.16484, 'Indianapolis', 'IN', 'Bank robber John Dillinger was killed by federal agents in Chicago in 1934 and returned to Indianapolis for burial in Crown Hill Cemetery. His granite grave has long attracted visitors interested in Depression-era outlaw history and has reportedly been replaced or repaired after decades of souvenir damage.', 'open', 'https://thetombstonetourist.com/graves/john-dillinger/', null, 'America/Indiana/Indianapolis', now()),
  ('Old Lake County Sheriff''s House and Jail', 'old-lake-county-sheriffs-house-and-jail', 'weird-history', 41.41563, -87.36373, 'Crown Point', 'IN', 'This historic jail became nationally famous after John Dillinger escaped from it in March 1934, reportedly using a fake gun to bluff his way past guards. The preserved complex has also developed a reputation among paranormal groups, but visitors should use official tours and events rather than attempting unscheduled access.', 'limited', 'https://www.hauntedplaces.org/item/crown-point-sheriffs-house-and-jail/', null, 'America/Chicago', now()),
  ('Tree on the Decatur County Courthouse Tower', 'tree-on-the-decatur-county-courthouse-tower', 'roadside-oddities', 39.33703, -85.48312, 'Greensburg', 'IN', 'Trees have mysteriously managed to grow from the courthouse tower high above Greensburg since the nineteenth century, with successive trees replacing earlier ones over time. The living courthouse-top tree became such a local symbol that Greensburg adopted the nickname "Tree City."', 'roadside', 'https://www.roadsideamerica.com/location/in/all', null, 'America/Indiana/Indianapolis', now()),
  ('USS LST-325', 'uss-lst-325', 'museums', 37.9525, -87.5768, 'Evansville', 'IN', 'USS LST-325 is a surviving World War II landing ship of the type used to carry tanks, vehicles and troops directly onto beaches. The restored vessel is now permanently based on the Ohio River in Evansville and offers guided tours through a working piece of wartime naval engineering.', 'limited', 'https://lstmemorial.org/', 'https://lstmemorial.org/', 'America/Chicago', now()),
  ('Ernie Pyle World War II Museum', 'ernie-pyle-world-war-ii-museum', 'museums', 39.80438, -87.49514, 'Dana', 'IN', 'Pulitzer Prize-winning war correspondent Ernie Pyle was born outside the tiny town of Dana, and his birthplace farmhouse has been preserved beside museum galleries housed in Quonset-style buildings. The exhibits focus on Pyle''s reporting and the ordinary soldiers whose experiences made his wartime columns famous.', 'limited', 'https://erniepyle.org/visit-the-ernie-pyle-wwii-museum/', 'https://erniepyle.org/', 'America/Indiana/Indianapolis', now()),
  ('Belle Gunness Exhibit — La Porte County Historical Society Museum', 'belle-gunness-exhibit-la-porte-county-historical-society-museum', 'museums', 41.58711, -86.70125, 'La Porte', 'IN', 'La Porte''s museum maintains an exhibit on Belle Gunness, the Norwegian-born woman linked to a series of killings discovered after her farm burned in 1908. The case remains unusually murky because the headless woman''s body recovered from the house was never conclusively established to be Gunness, and her ultimate fate is still debated.', 'open', 'https://laportecountyhistory.org/exhibits/belle-gunness/', 'https://laportecountyhistory.org/', 'America/Chicago', now()),
  ('Touchdown Jesus — Word of Life Mural', 'touchdown-jesus-word-of-life-mural', 'roadside-oddities', 41.70211, -86.23448, 'Notre Dame', 'IN', 'Millard Sheets'' enormous 1964 "Word of Life" mosaic on the Hesburgh Library depicts Christ with raised arms directly beyond Notre Dame Stadium. Students quickly nicknamed it "Touchdown Jesus" because the pose resembles a referee signaling a touchdown and the mural is visible from inside the stadium.', 'open', 'https://www.atlasobscura.com/places/the-word-of-life-mural-at-the-university-of-notre-dame', null, 'America/Indiana/Indianapolis', now()),
  ('James Dean Museum and Garfield Museum', 'james-dean-museum-and-garfield-museum', 'museums', 40.41582, -85.65035, 'Fairmount', 'IN', 'Fairmount manages to combine two very different pieces of pop culture in one small museum: hometown actor James Dean and Garfield creator Jim Davis, who grew up nearby. The collection contains Dean memorabilia alongside Garfield material, including a Garfield Trail statue dressed as Dean.', 'limited', 'https://www.atlasobscura.com/places/james-dean-museum-and-garfield-museum', null, 'America/Indiana/Indianapolis', now()),
  ('World''s Largest Rocking Chair', 'world-s-largest-rocking-chair-franklin', 'roadside-oddities', 39.41789, -85.99979, 'Franklin', 'IN', 'A gigantic wooden rocking chair survives outside a furniture business along US 31. An equally oversized chest of drawers once accompanied it but was destroyed in a fire, leaving the giant chair as the property''s solitary oversized landmark.', 'roadside', 'https://fotospot.com/attractions/indiana/worlds-largest-rocking-chair', null, 'America/Indiana/Indianapolis', now()),
  ('James Dean''s Grave', 'james-deans-grave', 'weird-history', 40.43309, -85.64503, 'Fairmount', 'IN', 'James Dean was returned to his hometown after his fatal 1955 automobile crash and buried in Park Cemetery north of Fairmount. Fans still visit the simple headstone, often leaving small memorial items or lipstick marks, making the cemetery one of the most enduring pilgrimage sites connected to the actor.', 'open', 'https://www.roadsideamerica.com/tip/460', 'https://showmegrantcounty.com/park-cemetery/', 'America/Indiana/Indianapolis', now()),
  ('Santa Claus Post Office', 'santa-claus-post-office', 'roadside-oddities', 38.12065, -86.92477, 'Santa Claus', 'IN', 'The real U.S. Post Office in a town genuinely named Santa Claus receives huge volumes of holiday mail from people seeking the town''s distinctive postmark. Local volunteers have answered children''s Santa letters for generations, turning an otherwise ordinary federal post office into a functioning piece of Christmas folklore.', 'open', 'https://tools.usps.com/locations/details/1380746', null, 'America/Chicago', now()),
  ('The Only Swayzee in the World', 'the-only-swayzee-in-the-world', 'roadside-oddities', 40.5071, -85.8254, 'Swayzee', 'IN', 'Swayzee proudly advertises itself as the "Only Swayzee in the World," a slogan tied to a local story that a wartime postcard addressed only to "Swayzee" still reached its destination. The claim appears on town signage and has become the tiny community''s defining roadside identity.', 'roadside', 'https://www.in.gov/towns/swayzee/about/', null, 'America/Indiana/Indianapolis', now()),
  ('The Lady and the Winds of Change', 'the-lady-and-the-winds-of-change', 'roadside-oddities', 38.2862, -85.7413, 'Jeffersonville', 'IN', 'In an industrial corner of Jeffersonville, a large welded-metal female figure is paired with poetry and environmental elements designed to make the piece more than a conventional statue. The unexpected placement and scale turn the installation into a particularly strange public-art stop.', 'open', 'https://www.atlasobscura.com/places/the-lady-and-the-winds-of-change', null, 'America/Indiana/Indianapolis', now()),
  ('Harlan — World''s Largest Anatomically Accurate Brain Sculpture', 'harlan-worlds-largest-anatomically-accurate-brain-sculpture', 'roadside-oddities', 39.17207, -86.52017, 'Bloomington', 'IN', 'Indiana University''s Psychological and Brain Sciences building has a seven-foot-tall, roughly 10,000-pound human brain carved from Indiana limestone outside its entrance. Artist Amy Brier and carver Mike Donham created the anatomically detailed sculpture, nicknamed Harlan, for the department''s 125th anniversary.', 'open', 'https://www.atlasobscura.com/places/the-world-s-largest-anatomically-accurate-limestone-brain-sculpture-bloomington-indiana', 'https://psych.indiana.edu/about/harlan-brain/index.html', 'America/Indiana/Indianapolis', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  timezone      = excluded.timezone,
  verified_at   = excluded.verified_at;

-- Corrections to the first Indiana batch.
update public.stops set timezone = 'America/Chicago' where slug = 'willard-library-grey-lady';
update public.stops set timezone = 'America/Chicago' where slug = 'footprints-of-the-archangel-gabriel';
update public.stops set timezone = 'America/Indiana/Vincennes' where slug = 'dr-teds-musical-marvels';
update public.stops set timezone = 'America/Chicago' where slug = 'historic-santa-claus-statue';
update public.stops set timezone = 'America/Indiana/Marengo' where slug = 'marengo-cave';
update public.stops set timezone = 'America/Indiana/Vincennes' where slug = 'jug-rock';
update public.stops set timezone = 'America/Indiana/Vincennes' where slug = 'providence-home-geode-grotto';
update public.stops set timezone = 'America/Chicago' where slug = 'worlds-largest-in-situ-celtic-cross';
update public.stops set timezone = 'America/Indiana/Vincennes' where slug = 'the-big-peach';
update public.stops set timezone = 'America/Chicago' where slug = 'giant-santa';

select timezone, count(*) from public.stops where state = 'IN' group by timezone order by 2 desc;
