-- Indiana, third batch.
--
-- No duplicates. Six coordinate flags, all genuinely separate: the Tippecanoe
-- monument and Prophet's Rock are two sites at the same battlefield, and the
-- Old Lake County courthouse and jail are adjacent buildings in Crown Point.
--
-- Checked against all 1,013 rows rather than the first thousand. The Supabase
-- REST API caps a request at 1,000 rows and says nothing about it, so earlier
-- checks in this session were quietly comparing against a partial index. Any
-- collision with a slug sorting after the cut-off would have been missed.
--
-- Timezones looked up per coordinate, as with the second batch.
--
-- 50 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Veal''s Ice Tree', 'veals-ice-tree', 'roadside-oddities', 39.67528, -85.96343, 'Acton', 'IN', 'Since 1961, the Veal family has used pond water and winter weather to build an enormous naturally frozen sculpture beside their home. Pipes and sprinklers add layer after layer until the "tree" becomes a towering mass of icicles, but it only appears when sustained cold makes construction possible.', 'limited', 'https://vealsicetree.wixsite.com/vealsicetree', 'https://vealsicetree.wixsite.com/vealsicetree', 'America/Indiana/Indianapolis', now()),
  ('Albany Shoe Tree', 'albany-shoe-tree', 'roadside-oddities', 40.29242, -85.25238, 'Albany', 'IN', 'A roadside tree on Edgewater Road became covered with shoes tossed and tied into its branches, turning an otherwise ordinary rural tree into a local landmark. The display has changed over the years as shoes disappear and new ones are added, so it is best treated as an evolving roadside oddity rather than a formal attraction.', 'roadside', 'https://www.atlasobscura.com/places/albany-shoe-tree', null, 'America/Indiana/Indianapolis', now()),
  ('Diehl''s Jalopy Junction', 'diehls-jalopy-junction', 'roadside-oddities', 41.3917, -85.382, 'Albion', 'IN', 'This rural property is packed with vintage gas-station signs, old cars, petroleum memorabilia and other roadside relics arranged into a sprawling personal collection. The owners have historically welcomed respectful visitors, but it remains private property and should only be entered when permission or visitor access is clearly offered.', 'private', 'https://www.roadsideamerica.com/tip/61661', null, 'America/Indiana/Indianapolis', now()),
  ('Half-Buried Cars and Dinosaurs', 'half-buried-cars-and-dinosaurs', 'roadside-oddities', 40.08764, -85.69818, 'Anderson', 'IN', 'Outside an Anderson collision shop, automobiles appear to dive nose-first into the ground alongside large dinosaur figures and other automotive art. The display sits at an active business at 1400 W. 29th Street, so it is best visited during normal business access rather than after the gates are closed.', 'limited', 'https://www.roadsideamerica.com/location/in/all', null, 'America/Indiana/Indianapolis', now()),
  ('Plane Crash in a Cemetery Marker', 'plane-crash-in-a-cemetery-marker', 'weird-history', 39.60532, -85.43274, 'Arlington', 'IN', 'East Hill Cemetery contains a marker tied to a bizarre 1978 accident in which a small airplane crashed into the cemetery while carrying figures from the auto-racing world. The cemetery itself is active and public, so visitors should approach the memorial respectfully and remain on normal cemetery drives and paths.', 'open', 'https://www.roadsideamerica.com/location/in/all', 'https://www.arlingtoneasthillcemetery.com/', 'America/Indiana/Indianapolis', now()),
  ('Early Ford V-8 Foundation Museum', 'early-ford-v-8-foundation-museum', 'museums', 41.335, -85.08964, 'Auburn', 'IN', 'This museum is devoted to Ford vehicles and history from the flathead V-8 era, especially 1932 through 1953. Its collection includes dozens of restored automobiles, period displays and a recreation of an early Ford dealership, making it a much more specific stop than a general car museum.', 'open', 'https://fordv8foundation.org/', 'https://fordv8foundation.org/', 'America/Indiana/Indianapolis', now()),
  ('Windows of Aurora — Abandoned Building Murals', 'windows-of-aurora-abandoned-building-murals', 'roadside-oddities', 39.05718, -84.90144, 'Aurora', 'IN', 'Artist Cindy Crofoot transformed boarded windows on a deteriorating downtown building into a series of painted faces and characters rather than leaving the facade blank. The installation became part of Aurora''s broader public-art effort and can be viewed from the public sidewalk without entering the building.', 'roadside', 'https://www.roadsideamerica.com/tip/61267', null, 'America/Indiana/Indianapolis', now()),
  ('Soccer Ball Rock', 'soccer-ball-rock', 'roadside-oddities', 39.5465, -86.19394, 'Bargersville', 'IN', 'A large, naturally lumpy boulder outside the South Central Soccer Academy has been painted again and again to resemble a giant soccer ball. The simple gag has survived for more than a decade and is visible from the soccer-complex grounds along Whiteland Road.', 'roadside', 'https://www.roadsideamerica.com/tip/73328', null, 'America/Indiana/Indianapolis', now()),
  ('German Cuckoo Clock Tower', 'german-cuckoo-clock-tower', 'roadside-oddities', 39.30055, -85.22232, 'Batesville', 'IN', 'Completed in 2021, this downtown clock tower plays with Batesville''s German heritage through two carved, lederhosen-clad woodsmen who mechanically saw a log every hour. Despite the cuckoo-clock appearance, the moving woodsmen rather than a bird are the centerpiece.', 'open', 'https://www.roadsideamerica.com/tip/75247', null, 'America/Indiana/Indianapolis', now()),
  ('Tippecanoe Battlefield Monument and Museum', 'tippecanoe-battlefield-monument-and-museum', 'weird-history', 40.5069, -86.8438, 'Battle Ground', 'IN', 'An 85-foot marble monument marks the landscape of the November 1811 Battle of Tippecanoe, fought between William Henry Harrison''s forces and warriors associated with Tecumseh''s Native confederacy. The adjacent museum provides context for the battle and the broader Indigenous resistance to U.S. expansion rather than reducing the location to battlefield folklore.', 'open', 'https://tippecanoehistory.org/our-places/tippecanoe-battlefield-museum/', 'https://tippecanoehistory.org/our-places/tippecanoe-battlefield-museum/', 'America/Indiana/Indianapolis', now()),
  ('Giant Chicken', 'giant-chicken', 'roadside-oddities', 39.28054, -86.75718, 'Spencer', 'IN', 'This oversized white chicken once advertised a local drive-in restaurant and became familiar enough that residents objected when redevelopment threatened it. The community rescued the fiberglass bird and moved it to the entrance of the Owen County Fairgrounds, where it still stands at East and Cooper streets.', 'open', 'https://www.roadsideamerica.com/tip/476', null, 'America/Indiana/Indianapolis', now()),
  ('1910 U.S. Population Center Marker', '1910-us-population-center-marker', 'weird-history', 39.16683, -86.5342, 'Bloomington', 'IN', 'A stone marker on the Monroe County Courthouse grounds commemorates the point calculated as the geographic center of the United States population after the 1910 Census. The actual statistical point reflected the country''s westward population shift, turning an abstract census calculation into a physical downtown landmark.', 'open', 'https://www.nps.gov/nr/feature/places/pdfs/76000013.pdf', null, 'America/Indiana/Indianapolis', now()),
  ('Pieces of the Battleship Indiana', 'pieces-of-the-battleship-indiana', 'weird-history', 39.1809, -86.5261, 'Bloomington', 'IN', 'Large surviving pieces of USS Indiana, including guns and part of the ship''s mast, stand outside Indiana University''s Memorial Stadium. The display has been assembled over decades from remnants of the battleship, creating a strange naval monument hundreds of miles from the sea.', 'open', 'https://www.roadsideamerica.com/tip/84479', null, 'America/Indiana/Indianapolis', now()),
  ('Gift from Brazil to Brazil', 'gift-from-brazil-to-brazil', 'roadside-oddities', 39.50105, -87.12428, 'Brazil', 'IN', 'In the 1950s, the nation of Brazil gave its Indiana namesake a massive granite reproduction of the Chafariz de São José fountain as a gesture of friendship. The roughly 40-foot-wide monument still stands near Nabuca Drive, although the fountain itself is generally dry.', 'open', 'https://www.roadsideamerica.com/tip/69438', null, 'America/Indiana/Indianapolis', now()),
  ('Giant Coke Bottle', 'giant-coke-bottle', 'roadside-oddities', 38.76525, -87.42074, 'Bruceville', 'IN', 'Built in 1949 for an Indianapolis Coca-Cola plant, this huge bottle eventually ended up on a trailer outside a private home in Bruceville. It has occasionally appeared in parades, but travelers should photograph the bottle only from the public road unless the property owner explicitly invites closer access.', 'private', 'https://www.roadsideamerica.com/tip/15522', null, 'America/Indiana/Vincennes', now()),
  ('Henager''s Memories and Nostalgia Museum', 'henagers-memories-and-nostalgia-museum', 'museums', 38.23142, -87.42672, 'Buckskin', 'IN', 'James Henager assembled a sprawling rural collection of tens of thousands of nostalgic objects, including toys, military items, advertising pieces, radios and pop-culture memorabilia. Because this is a small independently operated museum at 8837 S. State Road 57, travelers should verify current hours before making it a major detour.', 'limited', 'https://www.roadsideamerica.com/tip/15491', null, 'America/Chicago', now()),
  ('International Monster Truck Museum & Hall of Fame', 'international-monster-truck-museum-hall-of-fame', 'museums', 41.42985, -84.88196, 'Butler', 'IN', 'This museum preserves the history of monster trucks through full-size historic trucks, photographs, memorabilia and a hall of fame devoted to the sport''s major builders and drivers. The rotating vehicle lineup makes it a particularly strong automotive OddWay stop.', 'open', 'https://monstermuseum.org/', 'https://monstermuseum.org/', 'America/Indiana/Indianapolis', now()),
  ('Pirate Cat Memorial', 'pirate-cat-memorial', 'weird-history', 39.92696, -86.13658, 'Carmel', 'IN', 'Pirate Cat was a wandering orange-and-white cat who became a familiar sight to people using the Monon Trail and earned the unofficial title "Mayor of the Monon." After his death in 2020, admirers installed a black granite memorial topped with a life-size cat statue; some of his ashes are sealed inside.', 'open', 'https://www.roadsideamerica.com/story/75578', null, 'America/Indiana/Indianapolis', now()),
  ('Concrete Kingdom', 'concrete-kingdom', 'roadside-oddities', 38.32315, -85.76723, 'Clarksville', 'IN', 'The main yard of Concrete Kingdom contains thousands of concrete figures, fountains and lawn ornaments ranging from animals and religious pieces to oversized characters. Because it is an active statuary business rather than a museum, inventory changes constantly and the grounds can look different from one visit to the next.', 'open', 'https://concretekingdom65.com/', 'https://concretekingdom65.com/', 'America/Indiana/Indianapolis', now()),
  ('Upended Cadillac', 'upended-cadillac', 'roadside-oddities', 38.32072, -85.74691, 'Clarksville', 'IN', 'A vintage Cadillac is buried nose-first into the pavement outside the former Couch''s Body Shop location on Blackiston Mill Road. A mannequin once sat dramatically on the exposed rear of the car and later reports described it being replaced by other props, but the half-buried automobile itself remains the core attraction.', 'roadside', 'https://www.roadsideamerica.com/tip/454', null, 'America/Indiana/Indianapolis', now()),
  ('House of Bells', 'house-of-bells', 'roadside-oddities', 39.43855, -86.7455, 'Cloverdale', 'IN', 'Dozens of bells share this rural yard with oversized chains, huge buckets, traps jokingly sized for gigantic animals and other industrial curiosities. The unusual collection surrounds an unoccupied private house, so it should be viewed from the road unless access is clearly permitted.', 'private', 'https://www.roadsideamerica.com/tip/455', null, 'America/Indiana/Indianapolis', now()),
  ('World''s Largest Toilet — kidscommons', 'worlds-largest-toilet-kidscommons', 'museums', 39.19921, -85.92143, 'Columbus', 'IN', 'Inside the kidscommons children''s museum, visitors can climb into a comically oversized toilet that doubles as part of the building''s interactive plumbing-themed exhibit. The attraction is intentionally playful rather than a world-record engineering claim, but its giant scale makes it one of downtown Columbus''s stranger indoor stops.', 'limited', 'https://www.roadsideamerica.com/tip/22492', 'https://www.kidscommons.org/', 'America/Indiana/Indianapolis', now()),
  ('Zaharakos Soda Fountain and Museum', 'zaharakos-soda-fountain-and-museum', 'museums', 39.20018, -85.92143, 'Columbus', 'IN', 'Zaharakos opened in 1900 and preserves an elaborate turn-of-the-century soda-fountain interior filled with marble, stained glass and mechanical music machines. The business functions as both an operating restaurant and a small museum, allowing visitors to eat among restored pieces of early American soda-fountain culture.', 'open', 'https://www.zaharakos.com/', 'https://www.zaharakos.com/', 'America/Indiana/Indianapolis', now()),
  ('Vivian''s Dollhouse Grave', 'vivians-dollhouse-grave', 'weird-history', 39.65025, -85.1383, 'Connersville', 'IN', 'Vivian May Allison died as a young child in 1899, and her family placed a fully furnished miniature house over her grave rather than a conventional monument. Community members have maintained the unusual memorial for generations; it was temporarily removed for restoration in 2025 before being scheduled to return to City Cemetery.', 'open', 'https://historicconnersville.org/cemeteteries', null, 'America/Indiana/Indianapolis', now()),
  ('Pencil Collection and Odd Dummies — Old Lake County Courthouse', 'pencil-collection-and-odd-dummies-old-lake-county-courthouse', 'museums', 41.41722, -87.36583, 'Crown Point', 'IN', 'Inside the historic Old Lake County Courthouse is an eccentric collection that has included thousands of pencils alongside mannequins, local memorabilia and displays tied to courthouse history. The strange assortment makes the building more than a conventional courthouse museum, but exhibit access follows the historical society''s seasonal hours.', 'limited', 'https://www.roadsideamerica.com/tip/6135', null, 'America/Chicago', now()),
  ('Metal Dinosaur and Big Chicken', 'metal-dinosaur-and-big-chicken', 'roadside-oddities', 40.58535, -86.6751, 'Delphi', 'IN', 'A homemade metal dinosaur stands outside a rural Delphi property alongside an oversized fiberglass rooster. The mismatched pair gives travelers two classic forms of roadside folk art—scrap-metal sculpture and reused commercial fiberglass—in one stop.', 'roadside', 'https://www.roadsideamerica.com/tip/75392', null, 'America/Indiana/Indianapolis', now()),
  ('Micrometer Grave Marker', 'micrometer-grave-marker', 'weird-history', 38.88995, -85.5153, 'Dupont', 'IN', 'Robert D. and Carol L. Hughes are commemorated in Dupont Cemetery with a large stone monument shaped like a precision micrometer, reflecting Robert''s work in the tool-and-die trade. The unusual marker is visible from State Road 7 but should be approached with normal cemetery etiquette.', 'open', 'https://www.roadsideamerica.com/tip/17415', null, 'America/Indiana/Indianapolis', now()),
  ('Lincoln Highway Ideal Section Marker', 'lincoln-highway-ideal-section-marker', 'weird-history', 41.4928, -87.5095, 'Dyer', 'IN', 'In 1923, highway planners completed an experimental "Ideal Section" of the Lincoln Highway near Dyer to demonstrate what a modern road could be. The model section used unusually thick reinforced concrete along with drainage, lighting and pedestrian features, and a marker now identifies this influential piece of early highway engineering.', 'roadside', 'https://highways.fhwa.dot.gov/highway-history/general-highway-history/lincoln-highway', null, 'America/Chicago', now()),
  ('RV/MH Hall of Fame and Museum', 'rv-mh-hall-of-fame-and-museum', 'museums', 41.72924, -85.87985, 'Elkhart', 'IN', 'Elkhart''s RV/MH Hall of Fame preserves historic recreational vehicles ranging from primitive camping trailers to elaborate motorhomes. Walking through decades of changing interiors and technology makes the collection feel like a timeline of increasingly strange mobile living spaces.', 'open', 'https://www.rvmhhalloffame.org/', 'https://www.rvmhhalloffame.org/', 'America/Indiana/Indianapolis', now()),
  ('Giant Hood Ornament', 'giant-hood-ornament', 'roadside-oddities', 39.92798, -86.0909, 'Carmel', 'IN', 'Unveiled in 2024, this giant Art Deco winged hood ornament rises from the roundabout at 96th Street and Gray Road as a tribute to Indiana''s historic Stutz automobile company. It is one of several automotive-themed roundabout sculptures in the area, but its enormous transparent form makes it the standout.', 'roadside', 'https://www.roadsideamerica.com/tip/85807', null, 'America/Indiana/Indianapolis', now()),
  ('Bosse Field — A League of Their Own Ballpark', 'bosse-field-a-league-of-their-own-ballpark', 'weird-history', 37.99284, -87.56279, 'Evansville', 'IN', 'Opened in 1915, Bosse Field is one of the oldest professional baseball parks still in regular use in the United States. It became even more recognizable after appearing as Racine''s ballpark in the 1992 film A League of Their Own, and visitors can see it during games and scheduled events.', 'limited', 'https://www.atlasobscura.com/places/bosse-field', 'https://www.evansvilleotters.com/', 'America/Chicago', now()),
  ('Elizabeth Harrison Memorial — Oak Hill Cemetery', 'elizabeth-harrison-memorial-oak-hill-cemetery', 'weird-history', 37.99045, -87.53525, 'Evansville', 'IN', 'Elizabeth Harrison, a recognized leader within a nineteenth-century Romani traveling community, died in 1895 and was buried at Oak Hill Cemetery after a funeral that drew widespread public attention. Her family monument remains in Section 23; historical sources often use the period title "Queen of the Gypsies," but OddWay should describe the site with the more respectful Romani terminology.', 'open', 'https://www.roadsideamerica.com/story/23179', null, 'America/Chicago', now()),
  ('Tree With Car and Bicycles', 'tree-with-car-and-bicycles', 'roadside-oddities', 40.42375, -85.6504, 'Fairmount', 'IN', 'A dead tree outside a Fairmount residence has been turned into a vertical junk-art display with a Volkswagen Beetle and bicycles lodged high among its branches. The installation is on private property at 819 N. Morton Street and should be viewed only from the public road.', 'private', 'https://www.roadsideamerica.com/tip/79265', null, 'America/Indiana/Indianapolis', now()),
  ('Taylor Prayer Chapel', 'taylor-prayer-chapel', 'roadside-oddities', 39.34318, -87.38212, 'Farmersburg', 'IN', 'This tiny roadside chapel sits beside US 41 near the Vigo-Sullivan county line and was built as a quiet place where travelers could stop to pray or rest. Its miniature scale has also earned it a place in roadside-attraction guides, and visitor reports describe it as open to the public.', 'open', 'https://www.roadsideamerica.com/tip/12639', null, 'America/Indiana/Indianapolis', now()),
  ('27-Foot Blue Deity — Omkaar Temple', '27-foot-blue-deity-omkaar-temple', 'roadside-oddities', 41.123, -85.3435, 'Fort Wayne', 'IN', 'A 27-foot seated blue Hindu deity statue rises from the rural grounds of Omkaar Temple west of Fort Wayne, creating an unexpectedly monumental sight among surrounding farm fields. The scale and setting—not the religion itself—make this an OddWay stop; visitors should respect the temple as an active place of worship and follow posted access rules.', 'limited', 'https://www.roadsideamerica.com/story/74029', 'https://www.omkaartemple.org/', 'America/Indiana/Indianapolis', now()),
  ('Monument to Birdboy Arthur Smith', 'monument-to-birdboy-arthur-smith', 'weird-history', 41.0779, -85.11295, 'Fort Wayne', 'IN', 'A 40-foot limestone shaft in Memorial Park supports an eight-foot winged figure honoring early aviation daredevil Arthur "Art" Smith. Nicknamed Birdboy, Smith built and flew his own airplane as a teenager, became a nationally known stunt pilot and died in a 1926 air-mail crash.', 'open', 'https://www.roadsideamerica.com/story/68684', null, 'America/Indiana/Indianapolis', now()),
  ('Scrap Metal Mariachi Band', 'scrap-metal-mariachi-band', 'roadside-oddities', 41.11188, -85.14118, 'Fort Wayne', 'IN', 'A group of mariachi musicians fabricated from scrap metal performs permanently outside Cebolla''s Mexican Grill. The welded figures transform automotive and industrial pieces into instruments, sombreros and human forms, creating an effective roadside-art stop at an active restaurant.', 'roadside', 'https://www.roadsideamerica.com/tip/58221', null, 'America/Indiana/Indianapolis', now()),
  ('Stand on Three States Marker', 'stand-on-three-states-marker', 'weird-history', 41.69612, -84.80596, 'Fremont', 'IN', 'Near Indiana''s northeastern corner, a small benchmark marks the point where Indiana, Michigan and Ohio meet. A larger nearby monument makes the tri-state junction easier to find, but the actual survey point is much more modest and sits close to the road, so visitors should watch for traffic.', 'roadside', 'https://www.roadsideamerica.com/tip/50657', null, 'America/Indiana/Indianapolis', now()),
  ('Emperor Larry Bird', 'emperor-larry-bird', 'roadside-oddities', 38.5578, -86.62085, 'French Lick', 'IN', 'An outdoor bust of French Lick native Larry Bird depicts the basketball legend with the severe styling of an ancient Roman emperor. The sculpture stands outside the Springs Valley recreation-center area on Larry Bird Boulevard, making it an easy public tribute with a deliberately unusual visual twist.', 'open', 'https://www.roadsideamerica.com/tip/85109', null, 'America/Indiana/Indianapolis', now()),
  ('Hagenbeck-Wallace Circus Diorama', 'hagenbeck-wallace-circus-diorama', 'museums', 38.54896, -86.6204, 'French Lick', 'IN', 'The French Lick West Baden Museum houses an enormous miniature circus display devoted to the Hagenbeck-Wallace Circus, which once wintered in nearby Peru. The museum describes the sprawling model as containing well over 150,000 individual pieces, creating a dense miniature world of tents, wagons, performers and animals.', 'open', 'https://www.flwbmuseum.com/', 'https://www.flwbmuseum.com/', 'America/Indiana/Indianapolis', now()),
  ('Otis the Fishing Sasquatch', 'otis-the-fishing-sasquatch', 'cryptids', 38.41535, -86.7601, 'French Lick', 'IN', 'Otis is a 25-foot wooden Sasquatch built by Bear Hollow Wood Carvers in 2023 and posed on a broken dock with an enormous fishing pole. He stands on the French Lick Cabins at Patoka Lake property and has become a destination in his own right, but visitors should remember that the surrounding cabins are an operating lodging property.', 'limited', 'https://www.roadsideamerica.com/tip/84642', 'https://frenchlickcabins.net/', 'America/Indiana/Vincennes', now()),
  ('Fusion — Steel Workers and Fairies', 'fusion-steel-workers-and-fairies', 'roadside-oddities', 41.6025, -87.33743, 'Gary', 'IN', 'Artist Omri Amrany''s 2006 sculpture combines muscular steelworkers gathered around molten metal with winged dancers appearing to burst upward from the pour. The intentionally surreal mix of heavy industry and fantasy stands downtown beside the former convention-center area.', 'open', 'https://www.roadsideamerica.com/tip/42823', null, 'America/Chicago', now()),
  ('Goshen Police Booth', 'goshen-police-booth', 'weird-history', 41.58655, -85.83472, 'Goshen', 'IN', 'Built in 1939, this small fortified police booth was designed as a bullet-resistant downtown lookout during an era when Midwestern communities were still conscious of automobile-era gangsters. The tiny structure survives as a public reminder of how seriously towns once planned for armed criminals traveling the Lincoln Highway.', 'open', 'https://www.roadsideamerica.com/tip/3819', null, 'America/Indiana/Indianapolis', now()),
  ('Periodic Display of the Elements', 'periodic-display-of-the-elements', 'museums', 39.6364, -86.86195, 'Greencastle', 'IN', 'Inside DePauw University''s Julian Science and Mathematics Center is a large periodic table containing actual element samples or representative objects whenever safety allows. Instead of treating the periodic table as a flat chart, the installation turns chemistry into a cabinet of physical curiosities.', 'limited', 'https://www.roadsideamerica.com/tip/53091', null, 'America/Indiana/Indianapolis', now()),
  ('World War II V-1 Buzz Bomb', 'world-war-ii-v-1-buzz-bomb', 'weird-history', 39.64402, -86.86519, 'Greencastle', 'IN', 'A captured German V-1 flying bomb is mounted outdoors on a distinctive V-shaped memorial near the Putnam County Courthouse. The weapon, infamous for its use against European cities during World War II, now forms part of a memorial to local servicemembers who died in the war.', 'open', 'https://www.coveredbridgecountry.com/attractions/wwii-buzzbomb', null, 'America/Indiana/Indianapolis', now()),
  ('Giant Popcorn Box', 'giant-popcorn-box', 'roadside-oddities', 38.4006, -86.93185, 'Jasper', 'IN', 'A roughly 17-foot popcorn carton rises outside the business at 1522 Newton Street, complete with oversized kernels spilling from the top. Built to advertise a popcorn shop known for dozens of flavors, the sculpture remains an unmistakable roadside landmark on US 231.', 'roadside', 'https://www.roadsideamerica.com/tip/46315', null, 'America/Indiana/Vincennes', now()),
  ('Giant Fishing Lure', 'giant-fishing-lure', 'roadside-oddities', 38.26812, -85.74804, 'Jeffersonville', 'IN', 'An enormous fishing lure hangs over the Ohio River outside Upland Brewing''s Jeffersonville location. Installed as public art in 2021, the shiny oversized tackle turns the riverfront setting into a literal visual joke about fishing.', 'open', 'https://www.roadsideamerica.com/tip/84706', null, 'America/Indiana/Indianapolis', now()),
  ('Fiberglass Freaks'' Batman Museum', 'fiberglass-freaks-batman-museum', 'museums', 40.75303, -86.36319, 'Logansport', 'IN', 'Fiberglass Freaks opened its expanded downtown museum in 2024 as a tribute to the 1966 Batman television series and related superhero history. Displays include thousands of items, recreated environments and Batmobile-related material assembled by a builder known for licensed replicas of the show''s famous car.', 'open', 'https://fiberglassfreaksmuseum.com/', 'https://fiberglassfreaksmuseum.com/', 'America/Indiana/Indianapolis', now()),
  ('Pole Licker Statue — A Christmas Story', 'pole-licker-statue-a-christmas-story', 'roadside-oddities', 41.57405, -87.47055, 'Hammond', 'IN', 'A bronze boy has his tongue permanently frozen to a real flagpole outside the Indiana Welcome Center, recreating one of the best-known scenes from A Christmas Story. The tribute belongs in Hammond because author Jean Shepherd based the fictional hometown in his stories on his own northwest Indiana upbringing, even though the movie itself was filmed elsewhere.', 'open', 'https://visitindiana.in.gov/listing/pole-licker-statue%3A-a-christmas-story/16187/', null, 'America/Chicago', now()),
  ('Grave of the Wienermobile''s Little Oscar', 'grave-of-the-wienermobiles-little-oscar', 'weird-history', 41.48603, -87.36562, 'Merrillville', 'IN', 'George Molchan spent decades portraying Little Oscar for Oscar Mayer and traveling with the Wienermobile before retiring in 1987. His grave in Calumet Park Cemetery includes a bronze image of his costumed alter ego and the Wienermobile; it is in Section 19, Marker 901.', 'open', 'https://www.roadsideamerica.com/tip/51527', null, 'America/Chicago', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  timezone      = excluded.timezone,
  verified_at   = excluded.verified_at;

select count(*) as indiana from public.stops where state = 'IN';
