-- Kentucky, second batch.
--
-- Kentucky Bend is filed under Kentucky with a Tiptonville, Tennessee address,
-- which looks like an error and is not. The Mississippi loops around and
-- strands a piece of Kentucky that can only be reached by road through
-- Tennessee. It is Kentucky, so somebody browsing the state should find it,
-- and the postal address is the honest one to print.
--
-- My parser skipped it for exactly that reason: it was looking for a Kentucky
-- address rather than a Kentucky place.
--
-- Two more rows outside the enum, mapped as before.
--
-- Ten coordinate flags, none of them duplicates. They are small towns: the
-- Jailer's Inn is 39 metres from the Old Talbott Tavern because they face each
-- other across a street in Bardstown, and Frankfort's museums share a few
-- blocks.
--
-- 50 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Big Mike''s Rock Shop and Mystery House', 'big-mikes-rock-shop-and-mystery-house', 'roadside-oddities', 37.14429, -86.03745, 'Cave City', 'KY', 'Big Mike''s has been a Cave City roadside fixture for decades, combining a rock and fossil shop with a deliberately old-school Mystery House full of tilted rooms and gravity-defying visual tricks. Outside, an enormous mosasaur advertises the attraction while the shop displays "Big Mo," a massive real mosasaur skull.', 'open', 'https://www.roadsideamerica.com/story/12182', 'https://www.bigmikesrocks.com/', 'America/Chicago', now()),
  ('Floyd Collins Grave', 'floyd-collins-grave', 'weird-history', 37.19778, -86.07306, 'Mammoth Cave', 'KY', 'Cave explorer Floyd Collins became the center of a national media spectacle after becoming trapped in Sand Cave in 1925 and dying before rescuers could reach him. His remains had an equally strange afterlife, including years displayed in a glass-topped coffin and the theft of his body, before his eventual reburial at Mammoth Cave Baptist Church Cemetery.', 'open', 'https://www.roadsideamerica.com/story/11536', null, 'America/Chicago', now()),
  ('Sand Cave — Floyd Collins Rescue Site Trail', 'sand-cave-floyd-collins-rescue-site-trail', 'weird-history', 37.15255, -86.04767, 'Cave City', 'KY', 'A short National Park Service trail leads to an overlook near Sand Cave, where Floyd Collins became trapped during a 1925 exploration attempt and died after a rescue effort followed across the country. The cave itself is dangerous and not open for entry; OddWay should route visitors only to the established boardwalk and overlook.', 'open', 'https://myhikes.org/trails/sand-cave-trail', null, 'America/Chicago', now()),
  ('Crystal Onyx Cave', 'crystal-onyx-cave', 'roadside-oddities', 37.11073, -85.97347, 'Cave City', 'KY', 'Discovered in 1960, Crystal Onyx is a privately operated show cave packed with calcite formations beneath Prewitts Knob. Guided tours descend into the cave through a developed route, giving travelers another underground stop that feels very different from the huge passages of nearby Mammoth Cave.', 'limited', 'https://cavecountrytrails.com/trails/crystal-onyx-cave/', 'https://crystalonyxcaveky.com/', 'America/Chicago', now()),
  ('National Cave Museum and Library', 'national-cave-museum-and-library', 'museums', 37.11677, -86.06247, 'Park City', 'KY', 'The National Cave Museum and Library preserves material on cave exploration, geology and the long history of commercial and scientific caving around Mammoth Cave. Its specialized collection makes it a natural OddWay stop for travelers interested in what lies beneath Kentucky rather than another general local-history museum.', 'limited', 'https://mapcarta.com/N10757547905', null, 'America/Chicago', now()),
  ('Bell''s Tavern Ruins', 'bells-tavern-ruins', 'weird-history', 37.0918, -86.0499, 'Park City', 'KY', 'Bell''s Tavern became a major nineteenth-century stop for travelers heading toward Mammoth Cave, but a fire gutted the inn shortly before the Civil War. Plans to rebuild in stone were abandoned when the war began, leaving massive limestone walls and arched openings standing as picturesque public ruins.', 'open', 'https://www.atlasobscura.com/places/bells-tavern-ruins', null, 'America/Chicago', now()),
  ('National Corvette Museum Sinkhole', 'national-corvette-museum-sinkhole', 'weird-history', 37.0037, -86.3729, 'Bowling Green', 'KY', 'In February 2014, a sinkhole suddenly opened beneath the National Corvette Museum''s Skydome and swallowed eight rare Corvettes. The museum recovered the cars and incorporated the disaster into its exhibits, preserving damaged vehicles and the story of one of the strangest museum accidents in automotive history.', 'limited', 'https://www.corvettemuseum.org/sinkhole/', 'https://www.corvettemuseum.org/', 'America/Chicago', now()),
  ('Aviation Heritage Park', 'aviation-heritage-park', 'museums', 36.91951, -86.43594, 'Bowling Green', 'KY', 'This free aviation park displays restored military aircraft connected to aviators from south-central Kentucky, including fighters and other Cold War-era machines mounted outdoors. An indoor museum adds personal stories and artifacts tied to the people who flew them.', 'open', 'https://www.aviationheritagepark.com/about/location/', 'https://www.aviationheritagepark.com/', 'America/Chicago', now()),
  ('Historic RailPark and Train Museum', 'historic-railpark-and-train-museum', 'museums', 37.00018, -86.43826, 'Bowling Green', 'KY', 'Bowling Green''s restored Louisville & Nashville depot now anchors a museum where visitors can tour historic railroad cars rather than simply view them behind barriers. The collection includes passenger and service cars that preserve the strange, self-contained world of long-distance rail travel.', 'limited', 'https://www.historicrailpark.com/museum/', 'https://www.historicrailpark.com/', 'America/Chicago', now()),
  ('Cocaine Bear', 'cocaine-bear', 'weird-history', 38.04367, -84.45719, 'Lexington', 'KY', 'The Kentucky Fun Mall displays a taxidermied black bear presented as the animal that died after ingesting cocaine dropped by drug smuggler Andrew Thornton in Georgia in 1985. The bear''s later provenance has accumulated its own mythology, so the shop''s claim is best treated as part history and part modern roadside legend.', 'open', 'https://kyforky.com/pages/lexington-ky-s-kentucky-fun-mall-home-of-the-bear-who-ate-cocaine', 'https://kyforky.com/', 'America/New_York', now()),
  ('Monroe Moosnick Medical and Science Museum', 'monroe-moosnick-medical-and-science-museum', 'museums', 38.05272, -84.49403, 'Lexington', 'KY', 'Transylvania University''s medical collection contains nineteenth-century scientific instruments and anatomical curiosities, including a huge buffalo hairball and an anatomical figure associated with early medical teaching. Public access is limited and may require advance arrangements, so travelers should confirm availability before routing here.', 'limited', 'https://www.atlasobscura.com/places/the-monroe-moosnick-medical-and-science-museum-lexington-kentucky', null, 'America/New_York', now()),
  ('Dixie Cup Water Tower', 'dixie-cup-water-tower', 'roadside-oddities', 38.08004, -84.52675, 'Lexington', 'KY', 'A giant Dixie cup still sits high above the former Dixie Cup plant even though the property changed corporate ownership long ago. The tower became such a recognizable navigation landmark that it survived the brand''s departure and remains visible from surrounding public roads.', 'roadside', 'https://www.atlasobscura.com/places/dixie-cup-water-tower', null, 'America/New_York', now()),
  ('Bondurant''s Giant Mortar and Pestle', 'bondurants-giant-mortar-and-pestle', 'roadside-oddities', 38.04775, -84.54955, 'Lexington', 'KY', 'Joe Bondurant designed his 1970s pharmacy as an enormous mortar and pestle, complete with a tall pestle projecting from the roof. The pharmacy eventually closed, but the bizarre building survived under new commercial uses and remains one of Lexington''s most literal pieces of novelty architecture.', 'roadside', 'https://www.atlasobscura.com/places/bondurants-pharmacy', null, 'America/New_York', now()),
  ('Chained Rock', 'chained-rock', 'folklore', 36.75384, -83.70176, 'Pineville', 'KY', 'Pineville folklore says residents chained an enormous boulder to Pine Mountain to keep it from rolling down and crushing the town. The chain was actually installed in the 1930s as a publicity stunt inspired by the legend, and visitors can hike to the rock from Pine Mountain State Resort Park.', 'open', 'https://www.atlasobscura.com/places/chained-rock', null, 'America/New_York', now()),
  ('Kentucky Bend', 'kentucky-bend', 'weird-history', 36.53957, -89.47605, 'Tiptonville', 'KY', 'Kentucky Bend is a geographical oddity where a looping Mississippi River left a small piece of Kentucky surrounded by Tennessee and the river. Road access comes only through Tennessee, creating an isolated Kentucky pocket that feels disconnected from the rest of the state; travelers should remain on public roads and respect the surrounding farmland.', 'roadside', 'https://www.atlasobscura.com/places/kentucky-bend', null, 'America/Chicago', now()),
  ('Mantle Rock', 'mantle-rock', 'weird-history', 37.35183, -88.42883, 'Smithland', 'KY', 'This enormous natural sandstone bridge spans roughly 150 feet and sheltered Cherokee people during the forced-removal journey remembered as the Trail of Tears. About 1,800 Cherokee were stranded in the area during the bitter winter of 1838–39 while waiting for ice conditions on the Ohio River to improve.', 'open', 'https://www.fraziermuseum.org/weekly/7-29-2024', null, 'America/Chicago', now()),
  ('Tri-State Peak', 'tri-state-peak', 'roadside-oddities', 36.60136, -83.67525, 'Middlesboro', 'KY', 'A marker atop Tri-State Peak identifies the meeting point of Kentucky, Tennessee and Virginia. Visitors reach it by trail from Cumberland Gap National Historical Park, allowing them to stand at the junction of three states on the same hike.', 'open', 'https://www.nps.gov/cuga/planyourvisit/hiking-trails.htm', null, 'America/New_York', now()),
  ('Nada Tunnel', 'nada-tunnel', 'roadside-oddities', 37.81703, -83.68102, 'Stanton', 'KY', 'This narrow, unlit tunnel was blasted through solid rock in the early twentieth century for a logging railroad before being converted into a one-lane automobile road. Now known as the Gateway to Red River Gorge, it is just wide enough for a single vehicle and still carries normal traffic through the mountain.', 'open', 'https://www.atlasobscura.com/places/nada-tunnel', null, 'America/New_York', now()),
  ('Futuro House', 'futuro-house', 'roadside-oddities', 39.08817, -84.52642, 'Covington', 'KY', 'One of architect Matti Suuronen''s rare surviving Futuro Houses sits in Covington looking like a small fiberglass flying saucer that has just landed among ordinary homes. The structure is privately owned, so OddWay visitors should view it only from the public street and sidewalk.', 'private', 'https://thefuturohouse.com/Futuro-Covington-Kentucky-USA.html', null, 'America/New_York', now()),
  ('Clive the Alien', 'clive-the-alien', 'roadside-oddities', 39.08678, -84.50903, 'Covington', 'KY', 'A huge green alien named Clive peers through a magnifying glass from Covington''s Midtown Parking Garage. The playful public sculpture turns a utilitarian garage into an unexpected UFO-themed downtown photo stop.', 'open', 'https://www.atlasobscura.com/places/clive-covington-kentucky', null, 'America/New_York', now()),
  ('Jailer''s Inn', 'jailers-inn', 'haunted', 37.80892, -85.46789, 'Bardstown', 'KY', 'Bardstown''s old jail operated from the eighteenth century until 1987 before portions of the complex became a bed-and-breakfast. Guests can sleep in rooms surrounded by original jail architecture and decades of stories involving executions, prisoners and reported paranormal activity.', 'limited', 'https://www.atlasobscura.com/places/jailers-inn-bed-and-breakfast', 'https://www.jailersinn.com/', 'America/New_York', now()),
  ('Oscar Getz Museum of Whiskey History', 'oscar-getz-museum-of-whiskey-history', 'museums', 37.81008, -85.47022, 'Bardstown', 'KY', 'Rather than functioning as another bourbon tasting room, this museum follows American whiskey history through old bottles, advertising, distilling equipment and Prohibition-era artifacts. Its collection has included objects associated with figures ranging from George Washington to early Kentucky whiskey producers.', 'open', 'https://www.atlasobscura.com/places/oscar-getz-museum-of-whiskey-history', 'https://www.oscargetzwhiskeymuseum.com/', 'America/New_York', now()),
  ('Soldier Creek B-29 Crash Memorial', 'soldier-creek-b-29-crash-memorial', 'weird-history', 36.7896, -88.42902, 'Benton', 'KY', 'A black stone memorial near Soldier Creek remembers a B-29 Superfortress that crashed in this area on July 1, 1945. Nine men were killed and one survived, turning an otherwise quiet rural roadside into the marker for a largely forgotten wartime aviation disaster.', 'roadside', 'https://www.waymarking.com/waymarks/WMB0M5_Soldier_Creek_B_29_Crash_Memorial_Marshall_Co_Kentucky', null, 'America/Chicago', now()),
  ('Kentucky Military History Museum', 'kentucky-military-history-museum', 'museums', 38.1976, -84.87262, 'Frankfort', 'KY', 'Kentucky''s military museum occupies the fortress-like nineteenth-century State Arsenal, a building that looks unusually defensive even before entering. Exhibits cover weapons, military technology and Kentuckians at war, including material from the large George M. Chinn collection.', 'limited', 'https://history.ky.gov/visit/kentucky-military-history-museum/', null, 'America/New_York', now()),
  ('William Goebel Assassination Site', 'william-goebel-assassination-site', 'weird-history', 38.19853, -84.87788, 'Frankfort', 'KY', 'William Goebel was shot outside Kentucky''s Old State Capitol on January 30, 1900 during a bitterly disputed gubernatorial election. He was sworn in as governor while dying and died days later, becoming the only U.S. state governor assassinated while in office; a marker identifies the attack site.', 'open', 'https://www.atlasobscura.com/places/site-william-goebel-assassination', null, 'America/New_York', now()),
  ('Pete the Talking Crow — Georgetown & Scott County Museum', 'pete-the-talking-crow-georgetown-scott-county-museum', 'folklore', 38.21858, -84.55624, 'Georgetown', 'KY', 'Local legend remembers Pete as a real talking crow that supposedly shouted "Go!" during early horse races and helped inspire the use of organized race starts. The Georgetown & Scott County Museum keeps the story alive with a mechanical Pete display among its local-history collections.', 'limited', 'https://www.roadsideamerica.com/story/16999', 'https://www.georgetownscottcountymuseum.com/', 'America/New_York', now()),
  ('Dils Cemetery — Hatfield-McCoy Graves', 'dils-cemetery-hatfield-mccoy-graves', 'weird-history', 37.47785, -82.51477, 'Pikeville', 'KY', 'Dils Cemetery contains the graves of Randolph McCoy, his wife Sarah and several other people tied directly to the Hatfield-McCoy feud. The cemetery also has broader Civil War and local significance and can be reached from a designated parking area and stairway off Chloe Road.', 'open', 'https://www.hmdb.org/m.asp?m=146195', null, 'America/New_York', now()),
  ('McCoy Cemetery Historical Marker', 'mccoy-cemetery-historical-marker', 'weird-history', 37.58028, -82.17988, 'Hardy', 'KY', 'A roadside historical marker identifies the McCoy family cemetery associated with victims of the Hatfield-McCoy feud. Because access to the cemetery itself can be restricted, OddWay should route travelers to the public marker rather than encouraging entry onto private or controlled land.', 'roadside', 'https://www.hmdb.org/m.asp?m=50661', null, 'America/New_York', now()),
  ('Randolph McCoy Well and Homeplace', 'randolph-mccoy-well-and-homeplace', 'weird-history', 37.60278, -82.215, 'Hardy', 'KY', 'The original well survives at the site of Randolph McCoy''s home, where the Hatfields attacked the family on New Year''s night in 1888 and burned the cabin. Archaeological work recovered bullets, nails and household fragments, and the site now includes interpretation and a chainsaw-carved Randolph McCoy.', 'open', 'https://mccoywelltour.com/about-the-mccoy-well', 'https://mccoywelltour.com/', 'America/New_York', now()),
  ('Kentucky Folk Art Center', 'kentucky-folk-art-center', 'museums', 38.18167, -83.43306, 'Morehead', 'KY', 'Morehead State University''s Kentucky Folk Art Center preserves a large collection of work by self-taught and Appalachian artists. The collection''s carved figures, visionary art and unconventional materials make it much stranger and more personal than a conventional fine-art gallery.', 'open', 'https://www.moreheadstate.edu/kfac/', null, 'America/New_York', now()),
  ('Camp Breckinridge Museum and Art Center', 'camp-breckinridge-museum-and-art-center', 'museums', 37.6776, -87.8887, 'Morganfield', 'KY', 'This museum occupies one of the few surviving buildings from Camp Breckinridge, a World War II training installation that once contained roughly 1,800 structures. Among its most distinctive remnants are murals of European scenes painted by German prisoners of war held at the camp.', 'open', 'https://www.unioncountyky.org/our-county/camp-breckinridge-museum-and-arts-center/camp-breckinridge-museum', null, 'America/Chicago', now()),
  ('World Peace Bell', 'world-peace-bell', 'roadside-oddities', 39.09227, -84.49574, 'Newport', 'KY', 'Cast in 1998 and installed for the arrival of the year 2000, Newport''s enormous World Peace Bell weighs roughly 66,000 pounds and is about 12 feet across. It was the world''s largest functioning free-swinging bell when dedicated and remains an outsized downtown monument.', 'open', 'https://www.towerbells.org/data/NAOtherGreatBells.html', null, 'America/New_York', now()),
  ('Museum of Physical Security', 'museum-of-physical-security', 'museums', 37.8626, -84.5793, 'Nicholasville', 'KY', 'Lockmasters Security Institute maintains an unusual museum devoted to locks, safes and physical security technology stretching across centuries. Its collection has included historic locks, safecracking equipment and specialized security devices rarely displayed together elsewhere; visitors should call ahead before planning a tour.', 'limited', 'https://www.roadsideamerica.com/story/24045', null, 'America/New_York', now()),
  ('Ben E. Clement Mineral Museum', 'ben-e-clement-mineral-museum', 'museums', 37.33368, -88.07821, 'Marion', 'KY', 'Ben E. Clement spent decades assembling an extraordinary collection of fluorite from the Kentucky-Illinois mining district. The museum now houses thousands of vivid mineral specimens along with fossils, mining tools and geological curiosities.', 'open', 'https://clementmineralmuseum.org/about-the-mineral-museum/', 'https://clementmineralmuseum.org/', 'America/Chicago', now()),
  ('Pikeville Cut-Through Overlook', 'pikeville-cut-through-overlook', 'weird-history', 37.47246, -82.53852, 'Pikeville', 'KY', 'The Pikeville Cut-Through rerouted a river, railroad and highway through Peach Orchard Mountain in one enormous engineering project. A public overlook gives travelers a clear view of the artificial gap and the reshaped landscape below.', 'open', 'https://www.hmdb.org/m.asp?m=212047', null, 'America/New_York', now()),
  ('Rabbit Hash General Store and Dog Mayor Town', 'rabbit-hash-general-store-and-dog-mayor-town', 'roadside-oddities', 38.94219, -84.84598, 'Rabbit Hash', 'KY', 'Tiny Rabbit Hash is famous for ceremonially electing dogs as mayors, turning a historic Ohio River community into one of Kentucky''s strangest civic traditions. Its nineteenth-century general store remains the center of town after being rebuilt following a devastating 2016 fire.', 'open', 'https://www.rabbithash.com/about-us/directions.html', 'https://www.rabbithash.com/', 'America/Indiana/Indianapolis', now()),
  ('Cathedral Basilica of the Assumption Reliquaries', 'cathedral-basilica-of-the-assumption-reliquaries', 'weird-history', 39.0787, -84.50907, 'Covington', 'KY', 'Covington''s immense Gothic Revival cathedral contains elaborate stained glass and a reliquary chapel holding relics associated with Catholic saints. The combination of bones, ornate containers and cathedral architecture gives the active place of worship a distinctly unusual museum-like element; visitors should observe service schedules and church etiquette.', 'limited', 'https://www.atlasobscura.com/places/cathedral-basilica-of-the-assumption', null, 'America/New_York', now()),
  ('Belle of Louisville', 'belle-of-louisville', 'weird-history', 38.25924, -85.75555, 'Louisville', 'KY', 'Built in 1914, the Belle of Louisville is a surviving Mississippi River-style sternwheel steamboat that still operates passenger cruises on the Ohio River. Its working steam machinery and extraordinary longevity make it a piece of living transportation history rather than a static museum ship.', 'limited', 'https://www.atlasobscura.com/places/belle-of-louisville', 'https://www.belleoflouisville.org/', 'America/Kentucky/Louisville', now()),
  ('The Kentucky Castle', 'the-kentucky-castle', 'roadside-oddities', 38.04676, -84.65311, 'Versailles', 'KY', 'A full-scale modern castle rises unexpectedly above the horse farms along US 60 outside Lexington. Construction began decades ago, the property sat unfinished for years and later suffered a major fire before being transformed into an operating hotel, restaurant and event destination.', 'limited', 'https://www.thekentuckycastle.com/', 'https://www.thekentuckycastle.com/', 'America/New_York', now()),
  ('Heigold House Facade', 'heigold-house-facade', 'weird-history', 38.26394, -85.72503, 'Louisville', 'KY', 'Only the intricately carved stone facade remains from German immigrant Christian Heigold''s nineteenth-century Louisville home. Covered in patriotic inscriptions and sculpted imagery created during a period of intense anti-immigrant sentiment, the facade was saved from demolition and relocated as a freestanding public monument.', 'open', 'https://www.atlasobscura.com/places/heigold-house', null, 'America/Kentucky/Louisville', now()),
  ('Louisville Water Tower', 'louisville-water-tower', 'weird-history', 38.28056, -85.70139, 'Louisville', 'KY', 'Completed around 1860, this ornate column disguised a functioning water-system standpipe behind the appearance of a classical monument. Often described as the world''s oldest ornamental water tower, it stands beside the equally elaborate pumping station and WaterWorks Museum.', 'limited', 'https://commons.wikimedia.org/wiki/File:Louisville_water_tower.jpg', 'https://louisvillewater.com/', 'America/Kentucky/Louisville', now()),
  ('Louisville Mega Cavern', 'louisville-mega-cavern', 'roadside-oddities', 38.20138, -85.7041, 'Louisville', 'KY', 'A former limestone mine beneath Louisville was expanded into an enormous man-made underground space stretching beneath part of the city. The cavern has been used for storage and civil-defense planning and now hosts commercial underground attractions and tours.', 'limited', 'https://mapcarta.com/W332447080', 'https://louisvillemegacavern.com/', 'America/Kentucky/Louisville', now()),
  ('Captain Thomas Mantell Jr. UFO Death Marker', 'captain-thomas-mantell-jr-ufo-death-marker', 'ufos', 36.66772, -86.55768, 'Franklin', 'KY', 'On January 7, 1948, Kentucky Air National Guard pilot Thomas Mantell died after climbing while pursuing an unidentified object reported over Kentucky. The incident became an early landmark of the modern UFO era; later investigations have commonly connected the object to a high-altitude balloon and Mantell''s crash to hypoxia, while a Kentucky marker preserves the mystery.', 'roadside', 'https://www.hmdb.org/m.asp?m=239316', null, 'America/Chicago', now()),
  ('Red Bird Petroglyph', 'red-bird-petroglyph', 'weird-history', 37.15856, -83.76175, 'Manchester', 'KY', 'A large sandstone block known as the Red Bird Petroglyph bears a confusing mixture of carved markings and inscriptions and was moved for preservation after falling from its original cliff in 1994. Some writers have claimed the markings represent ancient Old World scripts, but those interpretations are controversial and are not accepted as established archaeological evidence.', 'open', 'https://www.fraziermuseum.org/weekly/3-25-2024', null, 'America/New_York', now()),
  ('Forest Giants in a Giant Forest', 'forest-giants-in-a-giant-forest', 'roadside-oddities', 37.91765, -85.65708, 'Clermont', 'KY', 'Danish artist Thomas Dambo built three enormous troll-like figures from recycled wood inside Bernheim Forest in 2019. The giants are hidden along trails rather than clustered beside a parking lot, turning the search for the sculptures into part of the attraction.', 'open', 'https://bernheim.org/must-sees/forest-giants/', 'https://bernheim.org/', 'America/New_York', now()),
  ('Grave of Speedy the Mortuary Mummy', 'grave-of-speedy-the-mortuary-mummy', 'weird-history', 37.08909, -88.62469, 'Paducah', 'KY', 'Charles "Speedy" Atkins drowned in 1928, was embalmed and then remained unclaimed at a Paducah funeral home for an astonishing 66 years. The preserved body became a local celebrity before finally being buried in Maplelawn Park Cemetery in 1994; his modest marker records the bizarre delay between death and burial.', 'open', 'https://www.roadsideamerica.com/story/34518', null, 'America/Chicago', now()),
  ('John T. Scopes Grave', 'john-t-scopes-grave', 'weird-history', 37.08454, -88.60321, 'Paducah', 'KY', 'John T. Scopes, the teacher prosecuted in the famous 1925 "Monkey Trial" for teaching evolution in Tennessee, was a Paducah native and is buried in Oak Grove Cemetery. A historical marker near the cemetery entrance explains the trial and its role in the continuing American conflict over science, religion and education.', 'open', 'https://map-gis.paducahky.gov/node/2861', null, 'America/Chicago', now()),
  ('World''s Largest Pocketknife', 'worlds-largest-pocketknife', 'roadside-oddities', 37.79756, -85.91228, 'Radcliff', 'KY', 'Outside Red Hill Cutlery stands an enormous folding pocketknife with a roughly 20-foot handle and a 17-foot-plus blade. Built in 2019, the several-thousand-pound knife is theoretically functional but requires heavy equipment to open or close.', 'open', 'https://www.atlasobscura.com/places/worlds-largest-pocketknife', 'https://redhillcutlery.com/', 'America/New_York', now()),
  ('World''s Largest Pin', 'worlds-largest-pin', 'roadside-oddities', 37.71856, -85.87687, 'Elizabethtown', 'KY', 'The Transit Authority of Central Kentucky turned its acronym—TACK—into a literal landmark by building an enormous pushpin outside its headquarters. Guinness World Records certified the approximately 21-foot-7-inch structure as the world''s largest pin in 2024.', 'open', 'https://www.atlasobscura.com/places/transit-authority-of-central-kentucky-tack-headquarters', null, 'America/New_York', now()),
  ('Feudists on Trial Hanging Site Marker', 'feudists-on-trial-hanging-site-marker', 'weird-history', 37.47948, -82.52172, 'Pikeville', 'KY', 'A Kentucky historical marker on the University of Pikeville campus identifies the site where Ellison "Cottontop" Mounts was hanged on February 18, 1890 for his role in the murder of Alifair McCoy. His execution is often treated as one of the final official acts of violence connected to the Hatfield-McCoy feud.', 'roadside', 'https://history.ky.gov/markers/feudists-on-trial', null, 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  timezone      = excluded.timezone,
  verified_at   = excluded.verified_at;

select count(*) as kentucky from public.stops where state = 'KY';
