-- Kentucky, third batch.
--
-- Seven rows outside the enum, mapped as before.
--
-- No duplicates. Nine coordinate flags, all of them small towns. The tightest
-- is The Walking Dead mural, 18 metres from the Rohs Opera House: Cynthiana is
-- Robert Kirkman's home town and the mural is painted on a wall beside the
-- theatre. A mural and a theatre are two stops.
--
-- Colonel Sanders appears three times across this state now — his grave in
-- Louisville, the original cafe at Corbin, and a mural of him as a shogun in
-- Covington. That is not a mistake either.
--
-- 50 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Giant Statues of Vulcan and Venus', 'giant-statues-of-vulcan-and-venus', 'roadside-oddities', 38.4819, -82.6395, 'Ashland', 'KY', 'Two roughly 30-foot bronze figures of the Roman deities Vulcan and Venus stand along the Ohio River beside an even taller abstract sculpture called Genesis. Installed at Riverfront Park in 2019, the enormous figures turn Ashland''s public riverfront into a surprisingly monumental art stop.', 'open', 'https://www.roadsideamerica.com/tip/67669', null, 'America/New_York', now()),
  ('World''s Tallest Crucifix', 'worlds-tallest-crucifix', 'roadside-oddities', 37.76694, -85.48333, 'Bardstown', 'KY', 'A roughly 60-foot stainless-steel crucifix rises above St. Thomas Cemetery south of Bardstown. Built in 1986, the unusually skeletal wire-frame figure of Jesus is visible above the cemetery and has long been promoted as one of the tallest crucifixes of its type.', 'open', 'https://www.roadsideamerica.com/story/11447', null, 'America/New_York', now()),
  ('Tiny Church — Bardwell City Park', 'tiny-church-bardwell-city-park', 'roadside-oddities', 36.87094, -89.01056, 'Bardwell', 'KY', 'A miniature white church stands in Bardwell City Park between downtown and the railroad tracks, accompanied by an equally tiny lighthouse. The little structure is one of Kentucky''s classic miniature roadside churches and can be visited from the public park.', 'open', 'https://www.roadsideamerica.com/tip/10263', null, 'America/Chicago', now()),
  ('Last Supper in Concrete', 'last-supper-in-concrete', 'roadside-oddities', 37.38973, -86.88989, 'Beaver Dam', 'KY', 'Folk artist Donald Bray created a full Last Supper scene from concrete along with additional homemade sculpture and mural work on his rural property. The installation is visible beside Rochester Road, but there is little parking and the art is on private land, so OddWay visitors should remain roadside unless invited closer.', 'private', 'https://www.roadsideamerica.com/tip/74119', null, 'America/Chicago', now()),
  ('Krispy Kreme Founder''s Birthplace Marker', 'krispy-kreme-founders-birthplace-marker', 'weird-history', 36.81862, -88.19791, 'Benton', 'KY', 'A modest roadside sign identifies the birthplace area of Vernon Rudolph, who went on to found Krispy Kreme. The original home is gone and the site is now an open field beside US 68, making the understated marker a strange contrast to the enormous brand Rudolph later created.', 'roadside', 'https://www.roadsideamerica.com/tip/82081', null, 'America/Chicago', now()),
  ('Big Black Bull', 'big-black-bull', 'roadside-oddities', 37.58171, -84.28918, 'Berea', 'KY', 'A large fiberglass black bull has stood outside the used-car property at 200 Richmond Road North for decades. The figure predates the current business and survives as an old-school example of oversized commercial roadside advertising.', 'roadside', 'https://www.roadsideamerica.com/tip/57398', null, 'America/New_York', now()),
  ('Unsettling Hand Sculptures', 'unsettling-hand-sculptures', 'roadside-oddities', 37.56872, -84.29613, 'Berea', 'KY', 'Berea''s 2003 Show of Hands public-art project scattered a dozen roughly six-foot fiberglass hands around town, each decorated differently by an artist. Several still survive in the Old Town area, and the visitor center at 3 Artist Circle is the best starting point for finding them.', 'open', 'https://www.roadsideamerica.com/tip/51090', 'https://visitberea.com/', 'America/New_York', now()),
  ('Deere John Project', 'deere-john-project', 'roadside-oddities', 37.9317, -85.31892, 'Bloomfield', 'KY', 'Inspired by Cadillac Ranch, Linda Bruckheimer planted ten John Deere tractors nose-first in a field north of Bloomfield in 2020. The machines progress from older to newer models and are intended as a tribute to the area''s farming history; a roadside pull-off allows legal viewing without entering the private field.', 'roadside', 'https://www.roadsideamerica.com/tip/72508', null, 'America/New_York', now()),
  ('1921 Standard Oil Gas Station', '1921-standard-oil-gas-station', 'weird-history', 36.9955, -86.43878, 'Bowling Green', 'KY', 'Built in 1921, this domestic-style filling station was Bowling Green''s first dedicated gas station and operated until the 1950s. The city restored it in 2008 with replica glass-topped pumps, and the little station now serves as part of public Circus Square Park.', 'open', 'https://www.roadsideamerica.com/tip/69146', null, 'America/Chicago', now()),
  ('Big Man, Little Car', 'big-man-little-car', 'roadside-oddities', 36.97875, -86.42968, 'Bowling Green', 'KY', 'A cartoonish metal strongman outside Walt''s Allstate Transmission holds a real vintage Renault Dauphine high over his head. The car once had neon trim and is now outlined with newer lighting, preserving the strange roadside sign well into the twenty-first century.', 'roadside', 'https://www.roadsideamerica.com/tip/86463', null, 'America/Chicago', now()),
  ('Big Red — Bronze Monster Mascot', 'big-red-bronze-monster-mascot', 'roadside-oddities', 36.98714, -86.45561, 'Bowling Green', 'KY', 'Western Kentucky University''s famously undefined red mascot became permanent public art in 2014 when alumnus Russ Faxon sculpted Big Red in bronze. The statue stands near the Alumni Center and captures the creature in its familiar wide-mouthed, sideline-cheering pose.', 'open', 'https://www.roadsideamerica.com/tip/42367', null, 'America/Chicago', now()),
  ('Car Parts Pumping Iron', 'car-parts-pumping-iron', 'roadside-oddities', 36.9588, -86.48737, 'Bowling Green', 'KY', 'Several weightlifters assembled from automobile and machine parts stand outside the business on Dishman Lane. The welded figures use wheels, springs and scrap components as bodies and barbells, turning discarded automotive material into an unexpected roadside gym.', 'roadside', 'https://www.roadsideamerica.com/location/ky/all', null, 'America/Chicago', now()),
  ('Duncan Hines Home and Office Marker', 'duncan-hines-home-and-office-marker', 'weird-history', 37.01035, -86.3965, 'Bowling Green', 'KY', 'Before his name became synonymous with boxed cake mix, Bowling Green native Duncan Hines was a traveling salesman and restaurant critic whose guidebooks helped motorists find dependable places to eat. A historical marker identifies his former home and office and explains the real man behind the supermarket brand.', 'roadside', 'https://www.hmdb.org/', null, 'America/Chicago', now()),
  ('Civil War Grave in a Parking Lot', 'civil-war-grave-in-a-parking-lot', 'weird-history', 36.7918, -85.3729, 'Burkesville', 'KY', 'Civil War veteran Captain Jack McClain''s grave sits by itself on a small island in the parking lot of the Alpine resort. The burial predates the motel property and was preserved when the hilltop was developed, leaving a solitary nineteenth-century grave surrounded by asphalt and parked cars.', 'limited', 'https://www.roadsideamerica.com/tip/40304', null, 'America/Chicago', now()),
  ('Hatfield-McCoy Love Baby Grave', 'hatfield-mccoy-love-baby-grave', 'weird-history', 37.56786, -82.23755, 'Burnwell', 'KY', 'Roseanna McCoy and Johnse Hatfield''s relationship produced a daughter, Sarah Elizabeth "Sally" McCoy, during the bitter Hatfield-McCoy feud. The infant died after only a few months, and a staircase from a small public parking area now climbs to the hillside cemetery containing her grave and interpretive markers.', 'open', 'https://www.roadsideamerica.com/story/48376', null, 'America/New_York', now()),
  ('Cadi the Pig', 'cadi-the-pig', 'roadside-oddities', 36.8795, -87.73679, 'Cadiz', 'KY', 'A large pink fiberglass pig named Cadi stands beside Hopkinsville Road as a local roadside mascot. The cheerful pig has been repainted and maintained over time and remains an easy drive-up example of Kentucky''s oversized fiberglass advertising tradition.', 'roadside', 'https://www.roadsideamerica.com/location/ky/all', null, 'America/Chicago', now()),
  ('Daniel Boone''s Last Kentucky Home Marker', 'daniel-boones-last-kentucky-home-marker', 'weird-history', 38.33213, -84.06632, 'Carlisle', 'KY', 'A Kentucky historical marker identifies the area where Daniel and Rebecca Boone lived from 1795 until the family left Kentucky for Spanish Louisiana territory in 1799. The original cabin is not the attraction here; OddWay should route travelers to the official US 68 roadside marker.', 'roadside', 'https://www.hmdb.org/m.asp?m=136919', null, 'America/New_York', now()),
  ('Carlisle Old Jail Dungeon', 'carlisle-old-jail-dungeon', 'weird-history', 38.31255, -84.0287, 'Carlisle', 'KY', 'The restored old Nicholas County jail retains a basement dungeon with stone foundations, earthen flooring and graffiti left by prisoners. Local tourism groups have also used the exceptionally grim cells as a seasonal haunted attraction, and visits outside events should be arranged rather than assumed.', 'limited', 'https://www.roadsideamerica.com/tip/7607', null, 'America/New_York', now()),
  ('Heart of the Forest — 27-Foot Tin Man', 'heart-of-the-forest-27-foot-tin-man', 'roadside-oddities', 37.91859, -85.66183, 'Clermont', 'KY', 'Artist Bill Secunda unveiled this 27-foot metal reinterpretation of the Tin Woodsman at Bernheim Forest in 2025. Rather than carrying his ax as a weapon, the giant figure embraces the forest, turning the familiar Wizard of Oz character into a towering environmental sculpture at the Jackson-Yoe trailhead.', 'open', 'https://www.roadsideamerica.com/tip/89361', 'https://bernheim.org/', 'America/New_York', now()),
  ('Harland Sanders Cafe and Museum', 'harland-sanders-cafe-and-museum', 'museums', 36.95993, -84.09375, 'Corbin', 'KY', 'Colonel Harland Sanders developed the recipe and restaurant operation that became Kentucky Fried Chicken at this roadside cafe. The restored site combines an operating KFC with museum displays and a reconstruction of Sanders'' original kitchen, motel room and early restaurant equipment.', 'open', 'https://www.roadsideamerica.com/location/ky/all', 'https://www.kfc.com/harrland-sanders-cafe-and-museum', 'America/New_York', now()),
  ('Shogun Sanders Mural', 'shogun-sanders-mural', 'roadside-oddities', 39.07664, -84.5178, 'Covington', 'KY', 'Artist Jonathan Queen reimagined Colonel Sanders as a roughly 20-foot futuristic Japanese-style warrior on the exterior of Earth To Kentucky. The mural is based on a physical Shogun Sanders figure displayed inside the collectible shop, giving Kentucky''s most famous colonel a deliberately bizarre pop-culture makeover.', 'open', 'https://www.roadsideamerica.com/tip/85476', null, 'America/New_York', now()),
  ('Monte Casino Chapel', 'monte-casino-chapel', 'roadside-oddities', 39.02157, -84.56867, 'Crestview Hills', 'KY', 'Two Benedictine monks built this tiny fieldstone chapel in the late nineteenth century, and Ripley''s Believe It or Not later promoted it as an exceptionally small church. The entire building was moved to what is now Thomas More University, where it sits beside a pond near the campus entrance.', 'open', 'https://www.crestviewhills.gov/Archive.aspx?ADID=139', null, 'America/New_York', now()),
  ('The Walking Dead Mural', 'the-walking-dead-mural', 'roadside-oddities', 38.38853, -84.29633, 'Cynthiana', 'KY', 'Cynthiana native Tony Moore co-created The Walking Dead comic, giving the small Kentucky town a direct connection to the franchise. Portuguese artist Sergio Odeith painted an enormous 3D-style undead mural beside Rohs Opera House in 2016, turning downtown into a destination for comic and horror fans.', 'open', 'https://www.roadsideamerica.com/location/ky/all', null, 'America/New_York', now()),
  ('Merle Travis Monument', 'merle-travis-monument', 'weird-history', 37.22388, -87.0063, 'Drakesboro', 'KY', 'Country musician Merle Travis, known for his influential fingerpicking style and for writing "Sixteen Tons," was cremated after his death in 1983. His ashes were scattered around this freestanding memorial near Ebenezer Missionary Baptist Church rather than placed beneath a conventional cemetery headstone.', 'open', 'https://www.roadsideamerica.com/tip/35082', null, 'America/Chicago', now()),
  ('Cannonball in the Building', 'cannonball-in-the-building', 'weird-history', 37.69316, -85.85922, 'Elizabethtown', 'KY', 'A Confederate artillery shell struck a downtown building during the Civil War fighting at Elizabethtown in 1862. When the original structure burned in 1887, the cannonball was recovered and deliberately placed into the replacement building near its approximate original impact point, where it remains visible from the square.', 'open', 'https://www.roadsideamerica.com/tip/3905', null, 'America/New_York', now()),
  ('Punkyville', 'punkyville', 'roadside-oddities', 38.6452, -84.32179, 'Falmouth', 'KY', 'Beginning in 2003, Charles "Punky" Beckett built a miniature nostalgic town beside his home using vintage signs, tools and salvaged material. The personal folk-art environment includes a gas station, jail, church, bank and water tower; because it shares private residential property, visitors should arrange access or remain respectful from the roadside.', 'private', 'https://fotospot.com/attractions/kentucky/punkyville', null, 'America/New_York', now()),
  ('Wildwood Inn Tropical Dome and Theme Suites', 'wildwood-inn-tropical-dome-and-theme-suites', 'roadside-oddities', 38.98558, -84.64825, 'Florence', 'KY', 'This operating motel has spent decades leaning into elaborate fantasy lodging, with rooms themed around caves, pirate ships, the 1950s, Venice, jungles and other over-the-top environments. A tropical indoor dome and novelty architecture make the property feel like a surviving piece of old roadside honeymoon-motel culture.', 'limited', 'https://www.wildwoodinnky.com/hotel-rooms-theme-based-wildwood-inn-florence-ky.html', 'https://www.wildwoodinnky.com/', 'America/New_York', now()),
  ('Capital City Museum', 'capital-city-museum', 'museums', 38.19852, -84.87569, 'Frankfort', 'KY', 'Frankfort''s city museum mixes state-capital history with odd local stories, political artifacts and material connected to events such as the assassination of Governor William Goebel. The museum is also a stop on Kentucky''s paranormal-tourism program, adding reported ghost activity to an already unusual local collection.', 'open', 'https://frankforthistory.org/capital-city-museum/', null, 'America/New_York', now()),
  ('Kentucky Floral Clock', 'kentucky-floral-clock', 'roadside-oddities', 38.18604, -84.87641, 'Frankfort', 'KY', 'Dedicated in 1961 behind the Kentucky State Capitol, this functioning clock uses a massive planted face that changes with seasonal flowers. The mechanism moves oversized hands across the living display while coins tossed into the pool below help support horticultural scholarships.', 'open', 'https://www.atlasobscura.com/places/kentucky-floral-clock', null, 'America/New_York', now()),
  ('Anderson Hotel', 'anderson-hotel', 'haunted', 38.03639, -84.89636, 'Lawrenceburg', 'KY', 'The nineteenth-century Anderson Hotel stopped operating as normal lodging decades ago but remains one of Lawrenceburg''s best-known paranormal locations. Investigators and local storytellers have reported apparitions, voices and violent unexplained activity inside; because the hotel is not a normal walk-in attraction, OddWay should route visitors only to public downtown viewing or explicitly scheduled events. Address: 116 S. Main St., Lawrenceburg, KY', 'roadside', 'https://www.kentuckyafterdark.com/', null, 'America/New_York', now()),
  ('Haunted Elm Building', 'haunted-elm-building', 'haunted', 37.83937, -87.59032, 'Henderson', 'KY', 'The three-story building at 120 N. Elm Street has been featured by Kentucky After Dark for stories involving shadow figures, voices, a mysterious bell and other reported activity. The retail business formerly known as The Elm moved away from this address in 2025, so OddWay should treat the historic haunted building itself as an exterior stop unless a current tenant advertises public access.', 'roadside', 'https://www.kentuckyafterdark.com/', null, 'America/Chicago', now()),
  ('Congleton Building', 'congleton-building', 'haunted', 37.57121, -83.70601, 'Beattyville', 'KY', 'The Congleton Building began as a hardware business but also provided undertaking services, with bodies reportedly moved upstairs by a hand-cranked elevator for embalming. Kentucky After Dark features the building for its funeral history and reported paranormal activity; it now contains offices, so access should be limited to advertised tours or events. Address: 203 Main St., Beattyville, KY', 'limited', 'https://www.kentuckyafterdark.com/locations/beattyville-lee-county-ky', null, 'America/New_York', now()),
  ('Chesnut House', 'chesnut-house', 'haunted', 37.28889, -83.79631, 'Manchester', 'KY', 'The Chesnut House is an early twentieth-century residence that has become one of southeastern Kentucky''s dedicated paranormal-tourism stops. Investigators report voices, footsteps and apparitions, and the property has hosted scheduled tours and investigations rather than functioning as an abandoned legend-tripping site. Address: 32 Ells Branch Rd., Manchester, KY', 'limited', 'https://www.kentuckyafterdark.com/', null, 'America/New_York', now()),
  ('Lexington Opera House', 'lexington-opera-house', 'haunted', 38.05001, -84.49921, 'Lexington', 'KY', 'Opened in 1887 after an earlier theater burned, the Lexington Opera House remains an active performance venue with ornate nineteenth-century architecture. Staff and performers have also passed down ghost stories involving unexplained sounds and figures, earning the theater a place on Kentucky''s paranormal tourism trail.', 'limited', 'https://www.kentuckyafterdark.com/', 'https://www.lexingtonoperahouse.com/', 'America/New_York', now()),
  ('White Hall State Historic Site', 'white-hall-state-historic-site', 'haunted', 37.83292, -84.35241, 'Richmond', 'KY', 'A major nineteenth-century expansion transformed the Clay family home into the sprawling mansion now known as White Hall. The restored house is open for tours and is also associated with long-running reports of moving lights, footsteps, phantom music and apparitions attributed to members of the Clay family.', 'limited', 'https://visitrichmondky.com/listing/white-hall-state-historic-house/', null, 'America/New_York', now()),
  ('Sassy Trash', 'sassy-trash', 'haunted', 36.84725, -83.3226, 'Harlan', 'KY', 'This downtown artisan shop occupies a three-story early twentieth-century building with stories of ringing bells, unexplained music and other reported activity. Harlan County tourism actively includes Sassy Trash on its Haunted Harlan County material, making it a rare paranormal stop that visitors can enter during normal retail hours. Address: 108 N. Main St., Harlan, KY', 'open', 'https://www.harlancountytrails.com/haunted-harlan-county-tour/sassy-trash/', null, 'America/New_York', now()),
  ('World''s Largest Butter Knife and Sculpture Park', 'worlds-largest-butter-knife-and-sculpture-park', 'roadside-oddities', 36.75864, -86.52423, 'Franklin', 'KY', 'Franklin-Simpson High School welding students built the 24-foot "Cutting Edge of Simpson County" in 2021 after previously creating the town''s giant fork. The rural sculpture park also contains other oversized student projects, including a space capsule and additional metal creations. Address: 4433 Blackjack Rd., Franklin, KY', 'open', 'https://www.roadsideamerica.com/tip/74601', null, 'America/Chicago', now()),
  ('Big Metal Abacus', 'big-metal-abacus', 'roadside-oddities', 38.40588, -85.58139, 'Goshen', 'KY', 'A giant steel-and-chrome abacus stands at the entrance to St. Francis School along US 42. The ancient calculating device has been enlarged to architectural scale, giving an elementary-school entrance the appearance of a piece of oversized mathematical machinery. Address: 10728 US Hwy 42, Goshen, KY', 'roadside', 'https://www.roadsideamerica.com/tip/46360', null, 'America/New_York', now()),
  ('Pink Elephant', 'pink-elephant', 'roadside-oddities', 36.64645, -87.19675, 'Guthrie', 'KY', 'A bright pink fiberglass elephant stands with its trunk raised outside a roadside gas-station property on Dixie Beeline Highway. The statue has been repainted several shades of pink over the years and was still being photographed in 2026.', 'roadside', 'https://fotospot.com/attractions/kentucky/pink-elephant', null, 'America/Chicago', now()),
  ('House of Many Crosses — Harrison Mayes', 'house-of-many-crosses-harrison-mayes', 'folklore', 36.60508, -83.71966, 'Middlesboro', 'KY', 'Coal miner and self-taught folk artist Henry Harrison Mayes spent decades creating concrete crosses, hearts and religious messages that he distributed across America and envisioned sending around the world. He also constructed his Middlesboro home itself in the shape of a cross; it remains a private residence, with surviving original crosses visible from the public street.', 'private', 'https://folk-visions.com/marker/middlesboro-ky-house-of-many-crosses/', null, 'America/New_York', now()),
  ('Coal House', 'coal-house', 'roadside-oddities', 36.6086, -83.71435, 'Middlesboro', 'KY', 'Built in 1926 as a tourism gimmick, this Arts and Crafts-style building is faced with blocks of locally mined coal rather than ordinary stone or brick. The unusual structure later served civic and tourism functions and survives downtown as a literal house made from the material that shaped the region.', 'open', 'https://commons.wikimedia.org/wiki/File:Coal_House,_20th_Street_and_Lothbury_Avenue,_Middlesboro,_KY.jpg', null, 'America/New_York', now()),
  ('Nostalgia Station Toy Museum', 'nostalgia-station-toy-museum', 'museums', 38.05569, -84.72602, 'Versailles', 'KY', 'A former railroad depot houses a collection of antique and vintage toys, model trains and related memorabilia. The combination of railroad architecture and decades of childhood objects gives the small museum the feeling of a carefully preserved time capsule.', 'limited', 'https://museumsdatabase.com/museums/view/11796', null, 'America/New_York', now()),
  ('Kentucky Music Hall of Fame and Museum', 'kentucky-music-hall-of-fame-and-museum', 'museums', 37.38979, -84.33175, 'Mount Vernon', 'KY', 'The museum preserves artifacts connected to Kentucky musicians across country, bluegrass, gospel, folk and other genres. Its Renfro Valley location ties the collection to one of the state''s oldest country-music entertainment traditions while providing a physical hall of fame for performers with Kentucky roots.', 'open', 'https://kentuckymusichalloffame.com/', null, 'America/New_York', now()),
  ('Old Joe Clark Statue', 'old-joe-clark-statue', 'roadside-oddities', 37.38714, -84.33087, 'Mount Vernon', 'KY', 'A bronze banjo player at Renfro Valley honors Manuel Dewey Clark Jr., who performed the comic old-time character "Old Joe Clark" for decades. The statue freezes the entertainer in mid-performance beside the historic Barn Dance complex.', 'open', 'https://www.roadsideamerica.com/tip/52377', null, 'America/New_York', now()),
  ('Nathan Stubblefield''s Grave', 'nathan-stubblefields-grave', 'weird-history', 36.62748, -88.29273, 'Murray', 'KY', 'Self-taught inventor Nathan Stubblefield publicly demonstrated wireless voice transmission in 1902 but died poor and largely forgotten in 1928. His later headstone in Bowman Cemetery boldly identifies him as the inventor of wireless telephony or radio, reflecting the continuing debate over how his experiments fit into radio history.', 'open', 'https://www.roadsideamerica.com/tip/55690', null, 'America/Chicago', now()),
  ('Fabulous Paradise Point', 'fabulous-paradise-point', 'roadside-oddities', 36.84268, -86.07395, 'Scottsville', 'KY', 'Paradise Point is a deliberately eclectic roadside marketplace packed with brightly painted vehicles, handmade signs, unusual decor and an anything-goes mixture of food, art and local merchandise. Its constantly changing collection makes the stop feel more like a living folk-art environment than a conventional country store.', 'open', 'https://www.paradisepointky.com/', null, 'America/Chicago', now()),
  ('World''s Largest Sassafras Tree', 'worlds-largest-sassafras-tree', 'roadside-oddities', 37.76147, -87.11158, 'Owensboro', 'KY', 'This enormous sassafras at Frederica Street and Maple Avenue has a trunk circumference of roughly 21 feet and is believed to be several centuries old. Local lore says homeowner Grace Rash once confronted road crews with a shotgun to prevent the tree from being cut down during a highway-widening project.', 'open', 'https://www.roadsideamerica.com/tip/7879', null, 'America/Chicago', now()),
  ('World''s Second Largest Seated Lincoln', 'worlds-second-largest-seated-lincoln', 'roadside-oddities', 37.66528, -82.78144, 'Prestonsburg', 'KY', 'A gigantic seated Abraham Lincoln originally commissioned by disgraced attorney Eric C. Conn now overlooks Middle Creek National Battlefield. The statue was deliberately built slightly smaller than the Lincoln Memorial figure in Washington and was relocated to the battlefield in 2021 after Conn''s fraud conviction. Address: 2968 KY-114, Prestonsburg, KY', 'open', 'https://www.roadsideamerica.com/story/27035', null, 'America/New_York', now()),
  ('Giant Needle and Thread', 'giant-needle-and-thread', 'roadside-oddities', 37.08617, -88.60372, 'Paducah', 'KY', 'Artist Michael Terra created a 22-foot chrome-plated needle with a bright red thread extending dozens of feet through the ground. Formally titled E Pluribus Unum, the sculpture celebrates Paducah''s internationally known quilting culture with an appropriately enormous sewing tool. Address: 533 N. 5th St., Paducah, KY', 'open', 'https://www.roadsideamerica.com/tip/82097', null, 'America/Chicago', now()),
  ('Greenup County War Memorial', 'greenup-county-war-memorial', 'weird-history', 38.55188, -82.85577, 'Greenup', 'KY', 'This unusually equipment-heavy veterans memorial surrounds its monuments with a full-size tank, fighter jet, helicopter and military boat. One of the Huey helicopter displays has held dog tags honoring veterans, turning the roadside park into a much more visually dramatic memorial than a conventional stone monument.', 'open', 'https://www.roadsideamerica.com/tip/30875', null, 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  timezone      = excluded.timezone,
  verified_at   = excluded.verified_at;

select count(*) as kentucky from public.stops where state = 'KY';
