-- Kentucky, first batch.
--
-- Ten rows arrived with categories outside the enum — nine 'paranormal' and
-- one 'ufo' — and are mapped to 'haunted' and 'ufos'. Left alone they would
-- have failed the insert.
--
-- Timezones looked up per coordinate. Kentucky is split between Eastern and
-- Central roughly down the middle, so assuming either one would be wrong for
-- about half the state.
--
-- No duplicates. One coordinate flag: the Behringer-Crawford Museum sits
-- inside Devou Park, 952 metres from the gravity hill already in the index.
-- Same park, different things.
--
-- 50 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Waverly Hills Sanatorium', 'waverly-hills-sanatorium', 'haunted', 38.13031, -85.84151, 'Louisville', 'KY', 'Opened as a tuberculosis hospital and expanded into its famous five-story form in the 1920s, Waverly Hills later became one of America''s best-known paranormal destinations. The preserved building now offers historical tours, nighttime paranormal tours and longer investigations, including access to the notorious body chute area through authorized programs.', 'limited', 'https://thewaverlyhillssanatorium.com/', 'https://thewaverlyhillssanatorium.com/', 'America/Kentucky/Louisville', now()),
  ('Pope Lick Monster — Pope Lick Park', 'pope-lick-monster-pope-lick-park', 'cryptids', 38.18781, -85.48466, 'Louisville', 'KY', 'Louisville folklore tells of a goat-man creature said to inhabit the area around the Pope Lick railroad trestle. The trestle is active railroad property and has been the site of fatal accidents, so OddWay should route travelers to public Pope Lick Park for the legend and never onto the tracks or bridge.', 'open', 'https://www.atlasobscura.com/places/the-pope-lick-monster', 'https://louisvilleky.gov/government/parks/park-list/pope-lick-park', 'America/Kentucky/Louisville', now()),
  ('The Witches'' Tree', 'the-witches-tree', 'folklore', 38.23602, -85.73177, 'Louisville', 'KY', 'Local legend says a tree once used as a gathering place by witches was cut down before the 1890 tornado that devastated Louisville, and that the witches cursed the city in revenge. The gnarled replacement tree at Park Avenue and Sixth Street has become a neighborhood landmark where visitors still leave small offerings.', 'open', 'https://www.atlasobscura.com/places/the-witches-tree', null, 'America/Kentucky/Louisville', now()),
  ('Vent Haven Museum', 'vent-haven-museum', 'museums', 39.05298, -84.55198, 'Fort Mitchell', 'KY', 'Vent Haven is the world''s only museum devoted entirely to ventriloquism, with nearly a thousand figures and puppets plus photographs, posters and recordings. Rows of staring dummies make it visually perfect for OddWay, but all visits require an advance guided-tour reservation during the museum''s May-through-September season.', 'limited', 'https://www.venthaven.org/', 'https://www.venthaven.org/', 'America/New_York', now()),
  ('Two-Headed Calf — Behringer-Crawford Museum', 'two-headed-calf-behringer-crawford-museum', 'museums', 39.0812, -84.53872, 'Covington', 'KY', 'Among the eclectic regional-history displays inside the Behringer-Crawford Museum is a preserved two-headed calf, one of the museum''s signature curiosities. The museum also contains fossils, historic vehicles and an elaborate model railroad inside a former mansion in Devou Park.', 'open', 'https://www.bcmuseum.org/', 'https://www.bcmuseum.org/', 'America/New_York', now()),
  ('Florence Y''all Water Tower', 'florence-yall-water-tower', 'roadside-oddities', 38.99773, -84.64785, 'Florence', 'KY', 'The famous tower originally advertised "Florence Mall," but highway regulations objected to using the structure as an advertisement before the mall had opened. Rather than repaint the entire tower, workers changed the M into a Y and added an apostrophe, creating the now-iconic "Florence Y''all."', 'roadside', 'https://www.atlasobscura.com/places/florence-y-all-water-tower', null, 'America/New_York', now()),
  ('Mammoth Cave', 'mammoth-cave', 'roadside-oddities', 37.18699, -86.10049, 'Mammoth Cave', 'KY', 'Mammoth Cave National Park protects the longest known cave system on Earth, with hundreds of miles of surveyed passages beneath central Kentucky. Ranger-led tours range from enormous historic corridors to tight stair-filled cave routes, while the park above ground remains open without an entrance fee.', 'limited', 'https://www.nps.gov/maca/', 'https://www.nps.gov/maca/', 'America/Chicago', now()),
  ('Diamond Caverns', 'diamond-caverns', 'roadside-oddities', 37.17438, -86.12624, 'Park City', 'KY', 'Discovered in 1859, Diamond Caverns became one of Kentucky''s earliest commercial cave attractions. Guided tours descend through passages densely packed with stalactites, flowstone and other formations just outside Mammoth Cave National Park.', 'limited', 'https://diamondcaverns.com/', 'https://diamondcaverns.com/', 'America/Chicago', now()),
  ('Lost River Cave', 'lost-river-cave', 'roadside-oddities', 36.95192, -86.47225, 'Bowling Green', 'KY', 'Lost River Cave carries visitors by boat into an underground river system beneath Bowling Green. The site also has a strange human history involving mills, Civil War activity and an underground nightclub that once operated inside the cave entrance.', 'limited', 'https://www.lostrivercave.org/', 'https://www.lostrivercave.org/', 'America/Chicago', now()),
  ('Hidden River Cave', 'hidden-river-cave', 'roadside-oddities', 37.17916, -85.90671, 'Horse Cave', 'KY', 'Hidden River Cave opens directly beneath downtown Horse Cave and was once badly polluted before becoming a major cave-restoration success story. Visitors can descend beneath Main Street for guided cave tours and visit the American Cave Museum above the entrance.', 'limited', 'https://hiddenrivercave.com/', 'https://hiddenrivercave.com/', 'America/Chicago', now()),
  ('Carter Caves State Resort Park', 'carter-caves-state-resort-park', 'roadside-oddities', 38.37412, -83.1216, 'Olive Hill', 'KY', 'Carter Caves protects a concentration of caves, natural bridges and unusual limestone formations in northeastern Kentucky. Several caves are accessible by scheduled guided tours, while surface trails reach arches and rock formations without requiring underground travel.', 'limited', 'https://parks.ky.gov/explore/carter-caves-state-resort-park-7780', 'https://parks.ky.gov/explore/carter-caves-state-resort-park-7780', 'America/New_York', now()),
  ('Big Bone Lick State Historic Site', 'big-bone-lick-state-historic-site', 'weird-history', 38.88479, -84.75059, 'Union', 'KY', 'For thousands of years, mineral-rich salt licks drew enormous Ice Age animals to this area, where many became trapped and left fossil remains behind. The park now interprets mammoths, mastodons and other prehistoric animals and maintains a modern bison herd near the visitor center.', 'open', 'https://parks.ky.gov/explore/big-bone-lick-state-historic-site-7810', 'https://parks.ky.gov/explore/big-bone-lick-state-historic-site-7810', 'America/New_York', now()),
  ('Dinosaur World', 'dinosaur-world', 'roadside-oddities', 37.13667, -85.97156, 'Cave City', 'KY', 'More than a hundred life-size dinosaur models populate the wooded trails at this classic Cave City roadside attraction. The giant prehistoric figures, fossil activities and oversized entrance make it a strong family-friendly OddWay stop near Mammoth Cave.', 'limited', 'https://www.atlasobscura.com/places/dinosaur-world', 'https://www.dinosaurworld.com/kentucky/', 'America/Chicago', now()),
  ('Wigwam Village No. 2', 'wigwam-village-no-2', 'roadside-oddities', 37.14528, -85.9455, 'Cave City', 'KY', 'Built in 1937, Wigwam Village No. 2 is one of the few surviving examples of America''s once-widespread concrete tipi motel chain. Fifteen individual cone-shaped motel rooms surround a larger central structure, and travelers can still book an overnight stay.', 'limited', 'https://www.atlasobscura.com/places/wigwam-village-2', 'https://www.historicwigwamvillage.com/', 'America/Chicago', now()),
  ('Kentucky Stonehenge', 'kentucky-stonehenge', 'roadside-oddities', 37.27186, -85.89144, 'Munfordville', 'KY', 'Chester Fryer hauled huge rocks from the surrounding area to create his own interpretation of Stonehenge beside his Munfordville home. The property also includes other rock installations such as Earth Mysteries and the Garden of Gethsemane, with designated visitor parking.', 'open', 'https://www.visitmunfordville.com/kentucky-stone-henge', null, 'America/Chicago', now()),
  ('Apple Valley Hillbilly Garden and Toyland', 'apple-valley-hillbilly-garden-and-toyland', 'roadside-oddities', 37.02731, -88.33261, 'Calvert City', 'KY', 'This former roadside store has evolved into a sprawling collection of pun-heavy junk sculptures, folk art, vintage toys and old gas-station memorabilia. The outdoor Hillbilly Garden and indoor Toyland collection contain thousands of objects arranged with intentionally eccentric humor.', 'open', 'https://applevalleyhillbillygardenandtoyland.com/', 'https://applevalleyhillbillygardenandtoyland.com/', 'America/Chicago', now()),
  ('Great American Dollhouse Museum', 'great-american-dollhouse-museum', 'museums', 37.65005, -84.77803, 'Danville', 'KY', 'More than 200 dollhouses and miniature room boxes form a densely detailed fictional American town and surrounding countryside. Tiny businesses, homes and historical scenes are filled with hidden jokes and objects, making this one of Kentucky''s most distinctive miniature museums.', 'open', 'https://thedollhousemuseum.com/', 'https://thedollhousemuseum.com/', 'America/New_York', now()),
  ('International Paranormal Museum and Research Center', 'international-paranormal-museum-and-research-center', 'museums', 37.09226, -84.60419, 'Somerset', 'KY', 'This small downtown museum is dedicated to paranormal claims, cryptids, UFOs and unexplained phenomena. Displays include investigation equipment, unusual artifacts, research material and rotating pieces tied to ghost stories and other unexplained events.', 'open', 'https://www.kentuckytourism.com/events/hauntedkentucky', null, 'America/New_York', now()),
  ('Portal 31 Underground Mine', 'portal-31-underground-mine', 'haunted', 36.96592, -82.9177, 'Lynch', 'KY', 'Portal 31 takes visitors by rail into a former U.S. Steel coal mine in the historic company town of Lynch. Beyond its mining history, the site is included on Kentucky''s paranormal tourism trail because visitors and staff have reported unexplained lights and sounds underground.', 'limited', 'https://portal31.org/', 'https://portal31.org/', 'America/New_York', now()),
  ('Blue Heron Mining Community', 'blue-heron-mining-community', 'weird-history', 36.67141, -84.54775, 'Stearns', 'KY', 'Blue Heron was a remote coal camp operated by the Stearns Coal and Lumber Company before being abandoned in the early 1960s. The National Park Service reconstructed building outlines with open steel structures and audio exhibits, creating an eerie walk through the footprint of a vanished mining town.', 'open', 'https://www.nps.gov/biso/learn/historyculture/blueheron.htm', 'https://www.nps.gov/biso/', 'America/New_York', now()),
  ('Kentucky Coal Museum', 'kentucky-coal-museum', 'museums', 36.96425, -82.95131, 'Benham', 'KY', 'Housed in the former company store of a coal town, this museum preserves mining equipment, company scrip, household artifacts and a recreated underground mine environment. The building''s solar-panel installation also became nationally notable because a museum devoted to coal partially powers itself with solar energy.', 'open', 'https://kycoalmuseum.southeast.kctcs.edu/', 'https://kycoalmuseum.southeast.kctcs.edu/', 'America/New_York', now()),
  ('Van Lear Historical Society Coal Miners'' Museum', 'van-lear-historical-society-coal-miners-museum', 'haunted', 37.77113, -82.75775, 'Van Lear', 'KY', 'The museum occupies the former Consolidation Coal Company office in the historic Van Lear coal camp and preserves artifacts from the surrounding mining community. Kentucky tourism also includes the building among locations with reported paranormal activity and occasional investigation events.', 'limited', 'https://www.kentuckytourism.com/events/hauntedkentucky', null, 'America/New_York', now()),
  ('Octagon Hall', 'octagon-hall', 'haunted', 36.80725, -86.55754, 'Franklin', 'KY', 'This unusual eight-sided antebellum house became entangled with Civil War history when soldiers occupied and camped around the property. Today it operates as a museum and has become one of Kentucky''s best-known paranormal investigation sites, with numerous television ghost-hunting appearances.', 'limited', 'https://www.atlasobscura.com/places/octagon-hall-civil-war-museum', 'https://www.octagonhallmuseum.com/', 'America/Chicago', now()),
  ('Liberty Hall Gray Lady', 'liberty-hall-gray-lady', 'haunted', 38.20052, -84.87622, 'Frankfort', 'KY', 'Liberty Hall dates to the late eighteenth century and carries one of Kentucky''s oldest ghost traditions. The most famous apparition is the "Gray Lady," said to be connected to a visiting relative who died in the house, with additional stories involving other unexplained figures and sounds.', 'limited', 'https://www.kentuckytourism.com/events/hauntedkentucky', 'https://libertyhall.org/', 'America/New_York', now()),
  ('Rohs Opera House', 'rohs-opera-house', 'haunted', 38.38869, -84.29636, 'Cynthiana', 'KY', 'Opened in 1871, Rohs Opera House is Kentucky''s oldest continuously operating theater and one of the state''s most openly paranormal-friendly venues. Staff and investigators have reported footsteps, voices, shadows and apparitions, and the theater hosts ghost walks and investigations.', 'limited', 'https://www.kentuckytourism.com/trip-planning/travel-inspiration/articles/2026/07/17/autumn-adventures-in-kentucky--spirits--scenery---spooky-stories', 'https://rohsoperahouse.com/', 'America/New_York', now()),
  ('Paramount Joe — Paramount Arts Center', 'paramount-joe-paramount-arts-center', 'haunted', 38.47823, -82.63736, 'Ashland', 'KY', 'The restored Paramount theater is associated with a resident ghost known as "Paramount Joe," traditionally described as a worker who died while the building was being constructed. Employees and performers have reported missing objects, cold spots and unexplained appearances around the theater.', 'limited', 'https://www.kentuckytourism.com/events/hauntedkentucky', 'https://paramountartscenter.com/', 'America/New_York', now()),
  ('Whitehaven Welcome Center', 'whitehaven-welcome-center', 'haunted', 37.05087, -88.65298, 'Paducah', 'KY', 'This elaborate 1860s mansion was restored and repurposed as one of America''s most unusual interstate welcome centers. Visitors and employees have also reported apparitions, strange smells and unexplained activity attributed to former residents of the property.', 'open', 'https://www.kentuckytourism.com/events/hauntedkentucky', null, 'America/Chicago', now()),
  ('Old Talbott Tavern', 'old-talbott-tavern', 'haunted', 37.809, -85.46746, 'Bardstown', 'KY', 'Operating from an eighteenth-century stone building, the Old Talbott Tavern has accumulated ghost stories involving former guests, unexplained apparitions and figures associated with Kentucky frontier history. Visitors can eat, drink or stay overnight rather than merely viewing the supposedly haunted building from outside.', 'open', 'https://www.hauntedplaces.org/item/old-talbott-tavern/', 'https://www.talbotttavern.com/', 'America/New_York', now()),
  ('Cumberland Falls Moonbow and Lover''s Leap', 'cumberland-falls-moonbow-and-lovers-leap', 'folklore', 36.83973, -84.34452, 'Corbin', 'KY', 'Cumberland Falls is one of the few places where visitors can regularly see a lunar rainbow, or moonbow, under the right full-moon conditions. The surrounding gorge also carries the Lover''s Leap ghost story of a bride said to have fallen to her death and later appeared in a white dress near the falls.', 'open', 'https://www.kentuckytourism.com/events/hauntedkentucky', 'https://parks.ky.gov/explore/cumberland-falls-state-resort-park-7786', 'America/New_York', now()),
  ('The Big Twigs', 'the-big-twigs', 'roadside-oddities', 37.05867, -87.03109, 'Dunmor', 'KY', 'Lake Malone State Park is home to a growing family of enormous wooden characters known as the Big Twigs. The 10-to-17-foot sculptures are scattered around park trails and recreation areas in scenes involving fishing, camping, reading and wildlife.', 'open', 'https://visitmuhlenberg.com/big-twigs/', 'https://visitmuhlenberg.com/big-twigs/', 'America/Chicago', now()),
  ('Fork in the Road', 'fork-in-the-road', 'roadside-oddities', 36.7898, -86.58908, 'Franklin', 'KY', 'A roughly 21-foot stainless-steel dinner fork rises from a literal fork in a rural Simpson County road. The deliberately obvious visual pun has become one of the county''s signature roadside-photo stops.', 'roadside', 'https://www.roadsideamerica.com/tip/64026', null, 'America/Chicago', now()),
  ('World''s Largest Baseball Bat', 'worlds-largest-baseball-bat', 'roadside-oddities', 38.2571, -85.76471, 'Louisville', 'KY', 'A 120-foot steel baseball bat leans against the Louisville Slugger Museum & Factory, modeled after a bat used by Babe Ruth. The enormous object weighs tens of thousands of pounds and functions as one of downtown Louisville''s easiest-to-spot landmarks.', 'open', 'https://www.sluggermuseum.com/', 'https://www.sluggermuseum.com/', 'America/Kentucky/Louisville', now()),
  ('30-Foot Gold Statue of David', '30-foot-gold-statue-of-david', 'roadside-oddities', 38.25657, -85.76144, 'Louisville', 'KY', 'A towering gold-painted reproduction inspired by Michelangelo''s David stands outside the 21c Museum Hotel on Main Street. The roughly 30-foot sculpture is intentionally oversized and impossible to miss among Louisville''s downtown buildings.', 'open', 'https://www.roadsideamerica.com/tip/33453', null, 'America/Kentucky/Louisville', now()),
  ('Colonel Sanders'' Grave', 'colonel-sanders-grave', 'weird-history', 38.24564, -85.71443, 'Louisville', 'KY', 'KFC founder Harland Sanders is buried in Cave Hill Cemetery beneath a monument featuring a sculpted bust with his unmistakable glasses, goatee and string tie. The cemetery marks the route to the grave with a colored road line for visitors.', 'open', 'https://www.roadsideamerica.com/tip/11451', null, 'America/Kentucky/Louisville', now()),
  ('The Peaslee Sphinx', 'the-peaslee-sphinx', 'weird-history', 38.24493, -85.71648, 'Louisville', 'KY', 'Installed in 1907, this 14-foot granite sphinx guards the Peaslee family plot in Cave Hill Cemetery. Its Egyptian styling was unusually exotic for Kentucky cemetery art at the time and remains one of the cemetery''s most conspicuous monuments.', 'open', 'https://www.roadsideamerica.com/story/63563', null, 'America/Kentucky/Louisville', now()),
  ('Sami Swings', 'sami-swings', 'weird-history', 38.24537, -85.71713, 'Louisville', 'KY', 'The grave of three-year-old Samantha "Sami" McDonald is marked by a life-size bronze sculpture depicting the child happily swinging while Jesus holds the ropes. The unusual and deeply personal memorial stands in Cave Hill Cemetery and is officially titled "Sami Swings."', 'open', 'https://www.atlasobscura.com/places/jesus-is-my-swingset', null, 'America/Kentucky/Louisville', now()),
  ('Hand Out Grave', 'hand-out-grave', 'weird-history', 38.24608, -85.7162, 'Louisville', 'KY', 'George Anne Sotsky''s Cave Hill Cemetery monument takes the form of an enormous open stone hand with its palm facing upward. The gesture symbolizes generosity and creates one of the cemetery''s strangest pieces of funerary sculpture.', 'open', 'https://www.roadsideamerica.com/tip/79097', null, 'America/Kentucky/Louisville', now()),
  ('Wooldridge Monuments', 'wooldridge-monuments', 'weird-history', 36.74948, -88.63653, 'Mayfield', 'KY', 'Colonel Henry Wooldridge commissioned a crowded cemetery tableau of 18 life-size statues depicting himself, relatives, dogs, a horse, a deer and a fox. Often called "the strange procession which never moves," the restored group fills his plot in Maplewood Cemetery.', 'open', 'https://www.roadsideamerica.com/story/2504', null, 'America/Chicago', now()),
  ('Octavia Hatcher Buried-Alive Grave', 'octavia-hatcher-buried-alive-grave', 'folklore', 37.47963, -82.5193, 'Pikeville', 'KY', 'Local tradition says Octavia Hatcher was mistakenly declared dead in 1891 during an illness that left several Pikeville residents in coma-like states. Her husband later reportedly exhumed her and found evidence she had awakened in the coffin; a fenced statue now marks her grave in Pikeville Cemetery.', 'open', 'https://www.roadsideamerica.com/story/23884', null, 'America/New_York', now()),
  ('Jim Varney''s Grave', 'jim-varneys-grave', 'weird-history', 38.06074, -84.51042, 'Lexington', 'KY', 'Actor Jim Varney, best remembered as Ernest P. Worrell and the original voice of Slinky Dog, is buried in Lexington Cemetery. Fans frequently leave Mello Yello cans, photos and other Ernest-related objects at his grave.', 'open', 'https://www.atlasobscura.com/places/jim-varney-grave', null, 'America/New_York', now()),
  ('Man o'' War''s Grave', 'man-o-wars-grave', 'weird-history', 38.15087, -84.5202, 'Lexington', 'KY', 'Legendary racehorse Man o'' War was embalmed and buried in an oversized casket before his remains and monumental bronze statue were later moved to the Kentucky Horse Park. The memorial now stands prominently near the park entrance among the graves of other famous horses.', 'limited', 'https://www.roadsideamerica.com/story/3613', 'https://kyhorsepark.com/', 'America/New_York', now()),
  ('Mother Goose House', 'mother-goose-house', 'roadside-oddities', 37.27275, -83.19301, 'Hazard', 'KY', 'George Stacy built this circular stone home beneath the enormous body of a goose beginning in the 1930s. The bird''s eyes were made from automobile headlights and still illuminate, but the structure remains a private residence and should only be admired from the public roadside.', 'private', 'https://www.atlasobscura.com/places/mother-goose-house', null, 'America/New_York', now()),
  ('Jefferson Davis Monument', 'jefferson-davis-monument', 'weird-history', 36.84194, -87.30056, 'Fairview', 'KY', 'A 351-foot concrete obelisk marks the Kentucky birthplace of Jefferson Davis, president of the Confederate States of America. The enormous monument was constructed between 1917 and 1924; interpretation of the site should place Davis and the Confederacy within the history of slavery, secession and the Civil War rather than treating the monument as neutral commemoration.', 'open', 'https://parks.ky.gov/explore/jefferson-davis-state-historic-site-7794', null, 'America/Chicago', now()),
  ('Kentucky Reptile Zoo', 'kentucky-reptile-zoo', 'museums', 37.79311, -83.70394, 'Slade', 'KY', 'This small zoo maintains one of the largest collections of venomous snakes in the United States and supplies venom for scientific and medical research. Visitors can see cobras, rattlesnakes, vipers and other reptiles at close range during seasonal operating hours.', 'limited', 'https://www.kyreptilezoo.com/', 'https://www.kyreptilezoo.com/', 'America/New_York', now()),
  ('Kelly Little Green Men Encounter', 'kelly-little-green-men-encounter', 'ufos', 36.95922, -87.47757, 'Kelly', 'KY', 'In August 1955, residents of a farmhouse near Kelly reported a nighttime encounter with small strange beings after seeing a bright object in the sky. The Kelly-Hopkinsville incident became one of America''s best-known UFO-era creature encounters, and the community still commemorates it through Little Green Men imagery and events; visitors should stay on public roads and avoid attempting to locate the original private farmhouse.', 'roadside', 'https://www.kellyky.com/', null, 'America/Chicago', now()),
  ('Creation Museum', 'creation-museum', 'museums', 39.08629, -84.78301, 'Petersburg', 'KY', 'This large museum presents a young-Earth creationist interpretation of natural history through elaborate displays, animatronics and recreated environments. OddWay can treat it as an unusual themed museum rather than endorsing its scientific claims, which differ from the mainstream scientific consensus on Earth''s age and evolution.', 'limited', 'https://creationmuseum.org/', 'https://creationmuseum.org/', 'America/New_York', now()),
  ('Ark Encounter', 'ark-encounter', 'roadside-oddities', 38.6222, -84.59451, 'Williamstown', 'KY', 'The centerpiece of this religious theme park is an enormous timber-frame interpretation of Noah''s Ark measuring more than 500 feet long. The scale of the structure makes it a legitimate roadside architectural oddity, while its exhibits present a young-Earth creationist interpretation rather than mainstream scientific geology and biology.', 'limited', 'https://arkencounter.com/', 'https://arkencounter.com/', 'America/New_York', now()),
  ('KSB Miniatures Collection', 'ksb-miniatures-collection', 'museums', 38.64816, -83.76701, 'Maysville', 'KY', 'Inside the Kentucky Gateway Museum Center is an extensive collection of intricately detailed miniature rooms, buildings and objects. Displays range from domestic interiors to tiny specialty pieces such as an exceptionally small Swiss Army knife, all presented at miniature scale.', 'open', 'https://www.atlasobscura.com/places/kentucky-gateway-museum-center', 'https://www.kygmc.org/', 'America/New_York', now()),
  ('Daniel Boone''s Disputed Grave', 'daniel-boones-disputed-grave', 'weird-history', 38.19758, -84.86646, 'Frankfort', 'KY', 'Kentucky says Daniel Boone was reinterred here in Frankfort Cemetery in 1845, but Missouri has long disputed whether all of his remains were actually moved from his original grave. The resulting two-state burial controversy makes Boone''s elaborate Kentucky monument more unusual than a typical famous-person grave.', 'open', 'https://www.roadsideamerica.com/story/2507', null, 'America/New_York', now()),
  ('Abraham Lincoln Birthplace Symbolic Cabin', 'abraham-lincoln-birthplace-symbolic-cabin', 'weird-history', 37.53167, -85.73736, 'Hodgenville', 'KY', 'Inside a large neoclassical memorial building sits a small nineteenth-century log cabin once promoted as the actual birthplace cabin of Abraham Lincoln. Historians later determined the cabin was not the original, so the National Park Service now presents it as a symbolic reconstruction associated with the birthplace site.', 'open', 'https://www.nps.gov/abli/', 'https://www.nps.gov/abli/', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  timezone      = excluded.timezone,
  verified_at   = excluded.verified_at;

select count(*) as kentucky from public.stops where state = 'KY';
