-- Maryland, first batch.
--
-- Maryland held exactly one stop before this. It was among the worst gaps in
-- the index and one of the least deserved: this is a state with the Goatman,
-- Moll Dyer's rock, Poe's grave, the man who patented the Ouija board buried
-- under a board of his own design, and a bay full of scuttled wooden steamships.
--
-- Completely clean: no slug collisions, nothing within 600 metres of an
-- existing stop.
--
-- Worth noting how much of this is the Lincoln assassination — the Mudd house,
-- the Surratt house, Booth's grave. Southern Maryland was the escape route, and
-- the sites are still standing and still open.
--
-- 50 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone, verified_at)
values
  ('Maryland Goatman at Governor''s Bridge', 'maryland-goatman-at-governors-bridge', 'cryptids', 38.95143, -76.69346, 'Bowie', 'MD', 'Governor''s Bridge is one of the locations most closely tied to Maryland''s Goatman legend, the half-man, half-goat creature said to stalk the woods and roads around Prince George''s County. The 1912 bridge itself is closed to vehicle traffic, so use the nearby public natural-area access and do not enter neighboring private property or wander the area after posted hours.', 'limited', 'https://historicbridges.org/bridges/browser/?bridgebrowser=maryland/governorsbridge/', 'America/New_York', now()),
  ('Moll Dyer Rock', 'moll-dyer-rock', 'folklore', 38.28947, -76.63594, 'Leonardtown', 'MD', 'Local legend says Moll Dyer was driven from her home on a freezing night in the late 1600s after townspeople accused her of witchcraft, and that her frozen body was later found against a large rock. The stone associated with the story was moved in 2021 to Tudor Hall, where it is displayed outside the St. Mary''s County Historical Society.', 'open', 'https://www.stmaryshistory.org/content.aspx?club_id=706426&module_id=487754&page_id=22', 'America/New_York', now()),
  ('Point Lookout Civil War Prison Camp', 'point-lookout-civil-war-prison-camp', 'haunted', 38.05965, -76.33698, 'Scotland', 'MD', 'Point Lookout held tens of thousands of Confederate prisoners during the Civil War, with thousands dying from disease and harsh conditions before the camp closed in 1865. The state park preserves the landscape and interpretation today, while generations of visitors and staff have reported apparitions, voices and other ghost stories around the former prison grounds and lighthouse area.', 'open', 'https://dnr.maryland.gov/publiclands/Pages/southern/pointlookout.aspx', 'America/New_York', now()),
  ('Edgar Allan Poe House & Museum', 'edgar-allan-poe-house-museum', 'museums', 39.2913, -76.63313, 'Baltimore', 'MD', 'Edgar Allan Poe lived in this tiny Baltimore rowhouse with members of his family from roughly 1833 to 1835. The preserved house now operates as a museum devoted to Poe''s life and writing, with period rooms, exhibits and artifacts connected to one of America''s most enduring masters of the macabre.', 'open', 'https://www.poeinbaltimore.org/', 'America/New_York', now()),
  ('Edgar Allan Poe Grave', 'edgar-allan-poe-grave', 'weird-history', 39.29027, -76.62333, 'Baltimore', 'MD', 'Edgar Allan Poe was buried at Westminster Burying Ground after his mysterious death in Baltimore in 1849, then moved to the prominent monument near the cemetery entrance in 1875. Visitors can see both the monument and his original burial place inside the historic graveyard.', 'open', 'https://www.westminsterhall.org/', 'America/New_York', now()),
  ('Elijah Bond''s Ouija Board Grave', 'elijah-bonds-ouija-board-grave', 'folklore', 39.31036, -76.60674, 'Baltimore', 'MD', 'Elijah Bond patented the talking board that would become the Ouija board in 1891. His grave in Green Mount Cemetery was unmarked for decades until researchers installed a new headstone in 2008 with a full Ouija board carved into its reverse side; visit only during cemetery hours.', 'open', 'https://elijahbond.com/', 'America/New_York', now()),
  ('John Wilkes Booth Grave', 'john-wilkes-booth-grave', 'weird-history', 39.30711, -76.606, 'Baltimore', 'MD', 'Lincoln assassin John Wilkes Booth is buried in the Booth family plot at Green Mount Cemetery beneath a small, deliberately unremarkable marker. Visitors often leave pennies on the stone, but the cemetery is an active burial ground and should only be visited during its posted daytime hours.', 'open', 'https://www.atlasobscura.com/places/grave-of-john-wilkes-booth', 'America/New_York', now()),
  ('The Horse You Came In On Saloon', 'the-horse-you-came-in-on-saloon', 'haunted', 39.28154, -76.5941, 'Baltimore', 'MD', 'A tavern has operated at this Fell''s Point location since the 18th century, and the modern saloon has long embraced stories linking the building to Edgar Allan Poe and a resident ghost known as Edgar. It remains an operating bar and live-music venue rather than a formal paranormal attraction.', 'open', 'https://www.atlasobscura.com/places/the-horse-you-came-in-on-saloon-baltimore-maryland', 'America/New_York', now()),
  ('Lord Baltimore Hotel', 'lord-baltimore-hotel', 'haunted', 39.2897, -76.61612, 'Baltimore', 'MD', 'Opened in 1928, the Lord Baltimore is a surviving grand downtown hotel with decades of stories involving a girl in white, unexplained elevator stops and other reported activity. The hotel actively embraces the reputation today with ghost tours, paranormal events and haunted-stay packages.', 'open', 'https://www.lordbaltimorehotel.com/', 'America/New_York', now()),
  ('Admiral Fell Inn', 'admiral-fell-inn', 'haunted', 39.2818, -76.5933, 'Baltimore', 'MD', 'The Admiral Fell Inn occupies a collection of historic Fell''s Point buildings associated with the neighborhood''s long maritime history. Guests and tour guides have attached numerous ghost stories to its rooms and corridors, while the property continues to operate as a hotel.', 'open', 'https://www.visitmaryland.org/listing/hotels-motels/admiral-fell-inn', 'America/New_York', now()),
  ('Historic Savage Mill Ghost Tour', 'historic-savage-mill-ghost-tour', 'haunted', 39.1354, -76.82521, 'Savage', 'MD', 'Historic Savage Mill dates to the 19th-century textile industry, and its organized ghost tour mixes mill history with reports of footsteps, apparitions and a mischievous child spirit. Tours require tickets and run on scheduled dates, so the haunting experience is limited even though the commercial mill complex is otherwise open.', 'limited', 'https://www.savagemill.com/ghost-tours/', 'America/New_York', now()),
  ('Ghost Tours of Historic Frederick', 'ghost-tours-of-historic-frederick', 'haunted', 39.4162, -77.4104, 'Frederick', 'MD', 'This long-running walking tour uses downtown Frederick''s wars, executions and local tragedies as the background for documented paranormal stories. Tours depart on scheduled evenings from the Market Street area and require a ticket or reservation.', 'limited', 'https://www.visitfrederick.org/event/ghost-tours-of-historic-frederick/24999/', 'America/New_York', now()),
  ('Ghosts of Annapolis Tour', 'ghosts-of-annapolis-tour', 'haunted', 38.97756, -76.48768, 'Annapolis', 'MD', 'Annapolis ghost walks take visitors through the old waterfront and colonial core for stories involving historic taverns, pirates, former residents and reported hauntings. The current tour meets around Market Space on scheduled evenings, so this is a ticketed tour rather than an always-open attraction.', 'limited', 'https://www.visitmaryland.org/events/ashes-and-apparitions-annapolis-ghost-tour', 'America/New_York', now()),
  ('Catoctin Furnace', 'catoctin-furnace', 'weird-history', 39.58116, -77.43445, 'Thurmont', 'MD', 'Iron production began at Catoctin Furnace in 1776 and relied in part on enslaved labor before the industrial village expanded through the 19th century. The surviving furnace stack, historic village, trails and Museum of the Ironworker now interpret both the industry''s technology and the lives of the people who worked there.', 'open', 'https://dnr.maryland.gov/publiclands/Pages/western/CunninghamFalls/Catoctin-Furnace.aspx', 'America/New_York', now()),
  ('Dr. Samuel A. Mudd House Museum', 'dr-samuel-a-mudd-house-museum', 'weird-history', 38.60958, -76.8262, 'Waldorf', 'MD', 'Dr. Samuel Mudd treated John Wilkes Booth''s broken leg here after Lincoln''s assassination, helping make the farmhouse one of the most notorious stops on Booth''s escape route. The privately owned historic property operates as a seasonal museum on selected days rather than daily.', 'limited', 'https://drmudd.org/', 'America/New_York', now()),
  ('Surratt House Museum', 'surratt-house-museum', 'weird-history', 38.76417, -76.89729, 'Clinton', 'MD', 'Mary Surratt''s country home and tavern became a meeting point and supply stop connected to the Lincoln assassination conspiracy. Restored as a museum, it focuses on the Surratt family, the Confederate underground and Booth''s escape; current public access is limited to scheduled tour and walk-in hours.', 'limited', 'https://www.surrattmuseum.org/visitor-information', 'America/New_York', now()),
  ('National Museum of Civil War Medicine', 'national-museum-of-civil-war-medicine', 'museums', 39.41379, -77.40932, 'Frederick', 'MD', 'This museum examines the grim realities and surprising advances of medicine during the Civil War through surgical instruments, field-hospital material and stories of doctors, nurses and patients. Its displays include subjects such as battlefield surgery, embalming and wartime disease that fit OddWay''s darker-history side particularly well.', 'open', 'https://www.civilwarmed.org/', 'America/New_York', now()),
  ('National Museum of Dentistry', 'national-museum-of-dentistry', 'museums', 39.2896, -76.62548, 'Baltimore', 'MD', 'The University of Maryland''s dental collection preserves thousands of objects tracing the strange, painful and occasionally ingenious history of dentistry. Holdings include early instruments, dentures, dental advertising and other material from the national collection of the American dental profession; confirm public visiting access before routing because it is housed within the dental school.', 'limited', 'https://www.dental.umaryland.edu/museum/', 'America/New_York', now()),
  ('National Museum of Health and Medicine', 'national-museum-of-health-and-medicine', 'museums', 39.00889, -77.05389, 'Silver Spring', 'MD', 'Founded during the Civil War as the Army Medical Museum, this institution holds one of America''s most unusual medical collections. Visitors encounter anatomical specimens, pathological material, military medicine exhibits and artifacts tied to major events including the assassination of Abraham Lincoln.', 'open', 'https://medicalmuseum.health.mil/', 'America/New_York', now()),
  ('National Cryptologic Museum', 'national-cryptologic-museum', 'museums', 39.11487, -76.77473, 'Annapolis Junction', 'MD', 'The National Security Agency''s public museum explores codebreaking, espionage and communications intelligence from early ciphers through modern computing. Displays include historic cryptographic machines, Cold War equipment and artifacts from some of the most secretive parts of American history.', 'open', 'https://www.nsa.gov/museum/', 'America/New_York', now()),
  ('National Capital Radio & Television Museum', 'national-capital-radio-television-museum', 'museums', 38.92631, -76.73332, 'Bowie', 'MD', 'A 1906 storekeeper''s house is packed with early radios, televisions, crystal sets, vacuum tubes and broadcasting equipment. The museum traces the rapid transformation from wireless telegraphy to household television and operates on limited weekly public hours.', 'open', 'https://www.cityofbowie.org/292/National-Capital-Radio-Television-Museum', 'America/New_York', now()),
  ('Spring Grove Hospital Center Alumni Museum', 'spring-grove-hospital-center-alumni-museum', 'museums', 39.26692, -76.72195, 'Catonsville', 'MD', 'Spring Grove traces its institutional history to 1797, making it one of the oldest continuously operating psychiatric hospitals in the United States. Its small alumni museum preserves early medical equipment, photographs, furniture and records from the hospital''s past, but visits are guided and by appointment.', 'limited', 'https://health.maryland.gov/springgrove/phototours/Pages/museum.aspx', 'America/New_York', now()),
  ('American Visionary Art Museum', 'american-visionary-art-museum', 'museums', 39.2804, -76.60689, 'Baltimore', 'MD', 'Rather than concentrating on conventionally trained artists, this Baltimore museum is devoted to self-taught and visionary creators. The campus is packed with giant sculptures, mosaics, kinetic pieces and objects made from unexpected materials, making the exterior alone an OddWay-worthy stop.', 'open', 'https://www.avam.org/', 'America/New_York', now()),
  ('National Great Blacks In Wax Museum', 'national-great-blacks-in-wax-museum', 'museums', 39.31182, -76.59685, 'Baltimore', 'MD', 'Founded in 1983, this museum uses more than 100 life-size wax figures and immersive scenes to interpret Black history. Some exhibits intentionally confront slavery, lynching and racial violence in unusually direct and graphic ways, making it very different from a conventional wax museum.', 'open', 'https://www.greatblacksinwax.org/', 'America/New_York', now()),
  ('The Mermaid Museum', 'the-mermaid-museum', 'museums', 38.32432, -75.21907, 'Berlin', 'MD', 'This small upstairs museum in downtown Berlin treats mermaids as a mixture of folklore, art, popular culture and imagined natural history. Displays include mermaid artifacts, stories and curiosities assembled into an intentionally unusual cabinet-of-wonders experience.', 'open', 'https://www.berlinmermaidmuseum.com/', 'America/New_York', now()),
  ('Trimper''s Haunted House', 'trimpers-haunted-house', 'haunted', 38.32653, -75.08808, 'Ocean City', 'MD', 'Built in 1964 and designed by legendary dark-ride creator Bill Tracy, Trimper''s Haunted House is one of the few surviving Tracy attractions still operating in its original location. The two-story boardwalk ride retains vintage stunts alongside newer effects and operates seasonally with Trimper Rides.', 'limited', 'https://trimpershauntedhouse.com/', 'America/New_York', now()),
  ('Ocean Gallery World Center', 'ocean-gallery-world-center', 'roadside-oddities', 38.33335, -75.08409, 'Ocean City', 'MD', 'Ocean Gallery''s boardwalk building looks like a chaotic collision of scrap metal, signs, art and old vehicles rather than a normal gallery storefront. The family-run business has evolved into one of Ocean City''s most recognizable visual oddities, and the exterior is worth seeing even without shopping.', 'open', 'https://www.roadsideamerica.com/location/md/all', 'America/New_York', now()),
  ('The Awakening', 'the-awakening', 'roadside-oddities', 38.78512, -77.01723, 'National Harbor', 'MD', 'J. Seward Johnson Jr.''s enormous sculpture depicts a giant apparently clawing his way out of the earth, with separate head, hand, arm, knee and foot emerging from the sand. The work was moved from Washington, D.C. to National Harbor in 2008 and is freely accessible on the waterfront.', 'open', 'https://www.atlasobscura.com/places/the-awakening-dc', 'America/New_York', now()),
  ('Bromo-Seltzer Arts Tower', 'bromo-seltzer-arts-tower', 'roadside-oddities', 39.28768, -76.62065, 'Baltimore', 'MD', 'Built between 1907 and 1911 for the company behind Bromo-Seltzer headache remedy, this clock tower was originally crowned by a giant glowing blue medicine bottle. The bottle is gone, but the tower now contains artist studios and a Bromo-Seltzer museum, with scheduled access to the clock room.', 'limited', 'https://www.bromoseltzertower.com/', 'America/New_York', now()),
  ('Bollman Truss Bridge', 'bollman-truss-bridge', 'weird-history', 39.13486, -76.82538, 'Savage', 'MD', 'This bright iron bridge is the last surviving example of Wendel Bollman''s once-influential railroad truss design. Built in the 19th century and later moved to Savage, it now carries a pedestrian trail across the Little Patuxent River and can be walked through freely.', 'open', 'https://www.loc.gov/item/md0583/', 'America/New_York', now()),
  ('Crystal Grottoes Caverns', 'crystal-grottoes-caverns', 'roadside-oddities', 39.49806, -77.67694, 'Boonsboro', 'MD', 'Discovered during quarry work in 1920, Crystal Grottoes developed into Maryland''s only commercial show cave. Guided tours descend into chambers filled with stalactites, flowstone and other formations, so visitors must enter during the attraction''s operating season and tour hours.', 'limited', 'https://www.mgs.md.gov/geology/caves/crystal_grottoes.html', 'America/New_York', now()),
  ('Enchanted Forest at Clark''s Elioak Farm', 'enchanted-forest-at-clarks-elioak-farm', 'roadside-oddities', 39.23701, -76.87535, 'Ellicott City', 'MD', 'Maryland''s original Enchanted Forest storybook park opened in 1955 and eventually closed, but many of its giant fairy-tale structures were rescued and restored at Clark''s Elioak Farm. Visitors can now wander among pieces such as Cinderella''s pumpkin coach and the Old Woman''s Shoe during the farm''s seasonal operating dates.', 'limited', 'https://clarklandfarm.com/enchanted_forest.html', 'America/New_York', now()),
  ('Vanadu Art House', 'vanadu-art-house', 'roadside-oddities', 38.96074, -76.95407, 'Hyattsville', 'MD', 'Artist and conservator Clarke Bedford transformed his home and vehicles into dense assemblages of metal, found objects, antlers, machine parts and architectural fragments. It is a private residence: admire it from the public street unless the owner is present and explicitly welcomes visitors onto the grounds.', 'private', 'https://www.atlasobscura.com/places/vanadu-art-house', 'America/New_York', now()),
  ('Paw Paw Tunnel', 'paw-paw-tunnel', 'weird-history', 39.55556, -78.46278, 'Oldtown', 'MD', 'Construction of this 3,118-foot C&O Canal tunnel began in 1836 and took 14 years amid unstable rock, funding problems and violent labor disputes. The towpath still passes through the completely dark tunnel, which is reached on foot or bicycle; bring a flashlight and follow any temporary NPS closure notices.', 'limited', 'https://www.nps.gov/places/paw-paw-tunnel.htm', 'America/New_York', now()),
  ('Mallows Bay Ghost Fleet', 'mallows-bay-ghost-fleet', 'weird-history', 38.47195, -77.26863, 'Nanjemoy', 'MD', 'More than 100 wrecks from a fleet of World War I-era wooden steamships remain in and around Mallows Bay, forming one of the largest concentrations of shipwrecks in the Western Hemisphere. The best views come by kayak or other small craft from the public launch, though some remains can also be seen from shore and trails.', 'limited', 'https://dnr.maryland.gov/ccs/Pages/mallowsbay.aspx', 'America/New_York', now()),
  ('John Paul Jones Crypt', 'john-paul-jones-crypt', 'weird-history', 38.98069, -76.48184, 'Annapolis', 'MD', 'Revolutionary War naval hero John Paul Jones died in Paris in 1792, disappeared beneath a later development, and was rediscovered more than a century afterward before being returned to the United States. His ornate black-and-white marble sarcophagus now sits beneath the U.S. Naval Academy Chapel; visitors must follow Naval Academy identification and security rules.', 'limited', 'https://www.atlasobscura.com/places/john-paul-jones-crypt', 'America/New_York', now()),
  ('Phoenix Shot Tower', 'phoenix-shot-tower', 'weird-history', 39.29073, -76.60547, 'Baltimore', 'MD', 'Completed in 1828, the 234-foot brick tower was briefly the tallest structure in the United States and manufactured lead shot by dropping molten metal from its upper levels. The landmark remains standing downtown, with interior access available only during limited tour hours and events.', 'limited', 'https://baltimore.org/listings/phoenix-shot-tower/', 'America/New_York', now()),
  ('F. Scott and Zelda Fitzgerald Graves', 'f-scott-and-zelda-fitzgerald-graves', 'weird-history', 39.082, -77.14536, 'Rockville', 'MD', 'F. Scott Fitzgerald and Zelda Fitzgerald are buried together in the small cemetery at St. Mary''s Catholic Church, beneath a stone engraved with the final line of The Great Gatsby. The graves are easy to visit from the church property but should be treated as an active cemetery rather than a roadside photo prop.', 'open', 'https://www.roadsideamerica.com/location/md/all', 'America/New_York', now()),
  ('Boonsborough Museum of History', 'boonsborough-museum-of-history', 'museums', 39.50829, -77.65283, 'Boonsboro', 'MD', 'This eccentric small-town collection ranges far beyond local history, with Civil War weapons sitting alongside Egyptian material, carved bullets, unusual medical and military objects, and a bouquet made from human hair. Tours operate on selected weekends from May through December or by appointment.', 'limited', 'https://boonsboroughmoh.org/', 'America/New_York', now()),
  ('Spocott Windmill Village', 'spocott-windmill-village', 'weird-history', 38.58958, -76.18149, 'Cambridge', 'MD', 'The current post windmill is a reconstruction of a 19th-century mill destroyed by a blizzard, surrounded by a collection of relocated and restored historic buildings. The grounds are generally accessible from dawn to dusk, while buildings and milling demonstrations have more limited schedules.', 'open', 'https://visitdorchester.org/spocott-windmill/', 'America/New_York', now()),
  ('College Park Aviation Museum', 'college-park-aviation-museum', 'museums', 38.97883, -76.92231, 'College Park', 'MD', 'The museum stands beside the world''s oldest continuously operating airport, where the Wright brothers trained military pilots beginning in 1909. Exhibits cover early flight, unusual aircraft and the airport''s long experimental history, with active aircraft often visible just outside.', 'open', 'https://www.pgparks.com/facilities/college-park-aviation-museum', 'America/New_York', now()),
  ('National Capital Trolley Museum', 'national-capital-trolley-museum', 'museums', 39.09581, -77.03139, 'Colesville', 'MD', 'This volunteer museum preserves historic streetcars and the technology of electric urban transportation. On operating days visitors can inspect restored cars and ride along the museum''s demonstration railway, so access depends on the published schedule.', 'limited', 'https://www.dctrolley.org/', 'America/New_York', now()),
  ('National Park Seminary', 'national-park-seminary', 'roadside-oddities', 39.0121, -77.05641, 'Silver Spring', 'MD', 'This former women''s school developed an extraordinary campus of architectural fantasies including a Japanese pagoda, Dutch windmill, Swiss chalet and English-style buildings before becoming part of an Army medical complex. Much of the property has since been redeveloped as residences, so visitors should stick to public roads, sidewalks and designated public areas rather than entering private buildings.', 'limited', 'https://www.loc.gov/pictures/item/md1503/', 'America/New_York', now()),
  ('Earthoid Water Tower', 'earthoid-water-tower', 'roadside-oddities', 39.18472, -77.24961, 'Germantown', 'MD', 'A huge spherical water tank has been painted as a remarkably detailed globe of the Earth, turning a piece of utility infrastructure into a giant roadside planet. It is best viewed from nearby public roads and areas around the Montgomery College Germantown campus rather than approached as an attraction with its own visitor entrance.', 'roadside', 'https://www.roadsideamerica.com/location/md/all', 'America/New_York', now()),
  ('The Cider Barrel', 'the-cider-barrel', 'roadside-oddities', 39.19008, -77.24192, 'Germantown', 'MD', 'This barrel-shaped building is a surviving example of novelty roadside architecture from the era when businesses were designed to look like the products they sold. The former cider stand is no longer a normal walk-in attraction, but the oversized barrel remains visible from public roadside areas.', 'roadside', 'https://www.roadsideamerica.com/location/md/all', 'America/New_York', now()),
  ('Mercury Cougar Statue', 'mercury-cougar-statue', 'roadside-oddities', 38.8266, -76.9261, 'Temple Hills', 'MD', 'This enormous fiberglass cougar survives from the days when the property operated as a Lincoln-Mercury dealership. Once mounted on the roof, the 1960s advertising cat now sits at ground level near the dealership and is easily visible from the public-facing commercial area.', 'roadside', 'https://www.roadsideamerica.com/tip/46420', 'America/New_York', now()),
  ('Giant Crash Test Dummy', 'giant-crash-test-dummy', 'roadside-oddities', 39.19661, -76.60995, 'Glen Burnie', 'MD', 'A 34-foot-tall yellow crash-test dummy stands outside Maryland Motor Vehicle Administration headquarters as an oversized traffic-safety mascot. Installed in 2012, it is a permanent outdoor photo stop visible from the public MVA complex.', 'roadside', 'https://www.roadsideamerica.com/tip/36232', 'America/New_York', now()),
  ('Jim Henson and Kermit the Frog Statue', 'jim-henson-and-kermit-the-frog-statue', 'roadside-oddities', 38.98763, -76.94505, 'College Park', 'MD', 'A life-size bronze Jim Henson sits on a bench beside Kermit the Frog on the University of Maryland campus, where Henson studied before creating the Muppets. The memorial garden is outdoors and publicly viewable while campus access is open.', 'open', 'https://arboretum.umd.edu/', 'America/New_York', now()),
  ('Patterson Park Pagoda', 'patterson-park-pagoda', 'roadside-oddities', 39.28995, -76.58349, 'Baltimore', 'MD', 'Built in 1891 as an observation tower, this brightly painted four-story structure is popularly called a pagoda despite being designed in a fanciful Victorian interpretation of Asian architecture. The exterior can be visited in Patterson Park year-round, while interior stair access is limited to scheduled open hours and events.', 'open', 'https://www.atlasobscura.com/places/patterson-park-observatory', 'America/New_York', now()),
  ('Hoodoo Marker', 'hoodoo-marker', 'folklore', 39.45928, -76.41388, 'Kingsville', 'MD', 'This rough boundary stone has stood beside Bel Air Road since the early 1800s and carries a biblical warning cursing anyone who moves a neighbor''s landmark. It sits beside private commercial property near the roadside, so view it without blocking traffic or treating the surrounding land as public.', 'roadside', 'https://www.roadsideamerica.com/tip/3345', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  verified_at   = excluded.verified_at;
