-- Maryland, second batch.
--
-- No duplicates. Six coordinate flags, all of them Baltimore being dense: the
-- Fell Family Cemetery is 63 metres from the Horse You Came In On, because
-- Fell's Point is named after the family buried in it.
--
-- Heavy on ruins and cemeteries, which is a fair description of the Maryland
-- piedmont: four mill and quarry ruins along the Potomac and Patapsco, a
-- drowned mill town, a pet cemetery, and a set of faux-bois grave markers made
-- of concrete cast to look like wood.
--
-- 35 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone, verified_at)
values
  ('Witch Board Museum Baltimore', 'witch-board-museum-baltimore', 'museums', 39.33086, -76.62962, 'Baltimore', 'MD', 'This Hampden museum is devoted to the history, mythology and pop-culture legacy of the Ouija board, which has deep roots in Baltimore. Opened as the Baltimore branch of the Salem Witch Board Museum, it sits inside Bazaar and covers figures such as Elijah Bond and Helen Peters alongside the board''s stranger cultural history.', 'open', 'https://www.salemwitchboardmuseum.com/copy-of-home-2', 'America/New_York', now()),
  ('Papermoon Diner', 'papermoon-diner', 'roadside-oddities', 39.32244, -76.62123, 'Baltimore', 'MD', 'Papermoon is less a normal diner than a giant assemblage artwork with mannequins, toys, Pez dispensers, dolls, brightly painted objects and bizarre decorations covering nearly every available surface. The restaurant is still operating, so travelers can actually go inside rather than merely photographing the exterior.', 'open', 'https://www.roadsideamerica.com/tip/37475', 'America/New_York', now()),
  ('Site of Edgar Allan Poe''s Death', 'site-of-edgar-allan-poes-death', 'weird-history', 39.29293, -76.59421, 'Baltimore', 'MD', 'Edgar Allan Poe died on October 7, 1849 at what was then Washington College Hospital after being found delirious several days earlier, and the circumstances of his final days remain disputed. The original hospital is gone, but a plaque on the later hospital complex marks the location traditionally associated with the room where Poe died.', 'roadside', 'https://www.atlasobscura.com/places/edgar-allen-poes-site-of-death', 'America/New_York', now()),
  ('George Peabody Library', 'george-peabody-library', 'museums', 39.2972, -76.61502, 'Baltimore', 'MD', 'Completed in the 19th century, the Peabody Library''s soaring atrium is lined with multiple tiers of cast-iron balconies and hundreds of thousands of books. Often described as a cathedral of books, the historic research library is open to visitors during posted public hours when not closed for events.', 'open', 'https://www.atlasobscura.com/places/george-peabody-library', 'America/New_York', now()),
  ('Graffiti Alley', 'graffiti-alley', 'roadside-oddities', 39.31153, -76.61881, 'Baltimore', 'MD', 'This alley behind Baltimore''s Motor House is one of the city''s best-known legal graffiti spaces, with nearly every wall and surface repeatedly covered by new layers of paint. Because the artwork constantly changes, repeat travelers may find an almost entirely different alley from one visit to the next.', 'open', 'https://www.atlasobscura.com/places/graffiti-alley', 'America/New_York', now()),
  ('Fort Armistead', 'fort-armistead', 'weird-history', 39.20929, -76.53368, 'Baltimore', 'MD', 'Built around the turn of the 20th century as part of Baltimore''s coastal-defense system, Fort Armistead later became an abandoned military battery inside a public park. The concrete emplacements are heavily weathered and graffitied; stay in legitimate public areas and do not enter unsafe tunnels, sealed spaces or restricted sections.', 'limited', 'https://www.atlasobscura.com/places/fort-armistead', 'America/New_York', now()),
  ('Babe Ruth Birthplace Museum', 'babe-ruth-birthplace-museum', 'museums', 39.28558, -76.6248, 'Baltimore', 'MD', 'George Herman “Babe” Ruth was born in this Baltimore rowhouse in 1895, just a few blocks from what is now Camden Yards. The restored house operates as a museum containing Ruth memorabilia, photographs and exhibits covering his life and baseball career.', 'open', 'https://baberuthmuseum.org/', 'America/New_York', now()),
  ('National Electronics Museum', 'national-electronics-museum', 'museums', 39.48578, -76.66327, 'Cockeysville', 'MD', 'The National Electronics Museum preserves more than 10,000 objects related to radar, radio, sonar, satellites, communications and electronic warfare. The collection has moved to the Hunt Valley/Cockeysville area, so travelers should use the museum''s current address and check its posted schedule before visiting.', 'limited', 'https://www.nationalelectronicsmuseum.org/', 'America/New_York', now()),
  ('William P. Didusch Center for Urologic History', 'william-p-didusch-center-for-urologic-history', 'museums', 39.20978, -76.67239, 'Linthicum Heights', 'MD', 'Housed at the American Urological Association, this highly specialized museum preserves the history of urology through antique cystoscopes, surgical instruments, microscopes, medical illustrations and other unusual artifacts. Public visits are generally arranged in advance, so contact the museum rather than treating it as a drop-in attraction.', 'limited', 'https://urologichistory.museum/', 'America/New_York', now()),
  ('National Road Museum', 'national-road-museum', 'museums', 39.50926, -77.65397, 'Boonsboro', 'MD', 'The museum tells the story of the National Road, America''s first federally funded highway and one of the routes that transformed early road travel westward. Exhibits recreate pieces of the road''s tavern, transportation and roadside history, and the museum also serves as Boonsboro''s visitor center during its limited open hours.', 'limited', 'https://nationalrdfoundation.org/boonsboro-visitor-center/', 'America/New_York', now()),
  ('NASA Goddard Rocket Garden and Moon Tree', 'nasa-goddard-rocket-garden-and-moon-tree', 'roadside-oddities', 38.9928, -76.84699, 'Greenbelt', 'MD', 'Outside NASA''s Goddard Visitor Center is a collection of rockets and space hardware that gives travelers an up-close look at the scale of sounding rockets and launch technology. The grounds also include a Moon Tree descended from seeds carried around the Moon during Apollo 14, while the visitor center contains additional free exhibits.', 'open', 'https://www.nasa.gov/goddard/visitor-center/', 'America/New_York', now()),
  ('Dinosaur Park Fossil Site', 'dinosaur-park-fossil-site', 'weird-history', 39.0708, -76.86861, 'Laurel', 'MD', 'This protected Early Cretaceous fossil site preserves one of the most important dinosaur deposits in the eastern United States, including material from Maryland''s state dinosaur, Astrodon. The fenced fossil area is only opened during scheduled public programs and dig experiences, although the surrounding playground and garden have broader access.', 'limited', 'https://www.pgparks.com/parks_trails/dinosaur-park', 'America/New_York', now()),
  ('Havre de Grace Decoy Museum', 'havre-de-grace-decoy-museum', 'museums', 39.53966, -76.08693, 'Havre de Grace', 'MD', 'The Decoy Museum preserves the Chesapeake Bay tradition of carved waterfowl decoys, working boats, hunting gear and folk art. Its large collection includes historic and contemporary carvings that turn an otherwise ordinary hunting tool into a distinctly regional art form.', 'open', 'https://www.decoymuseum.com/', 'America/New_York', now()),
  ('God''s Ark of Safety', 'gods-ark-of-safety', 'roadside-oddities', 39.63428, -78.92898, 'Frostburg', 'MD', 'A church congregation began planning a full-scale Noah''s Ark beside Interstate 68 after its pastor said he received a divine command to build it in 1976. The enormous steel skeleton remains an unfinished landmark decades later; view it from legitimate public roadside areas and do not enter the construction property without permission.', 'roadside', 'https://www.atlasobscura.com/places/gods-ark-of-safety', 'America/New_York', now()),
  ('First Washington Monument', 'first-washington-monument', 'weird-history', 39.50047, -77.62315, 'Middletown', 'MD', 'Boonsboro residents climbed South Mountain on July 4, 1827 and built a rough stone tower honoring George Washington, making it the first completed monument to Washington in the country. The rebuilt tower stands inside Washington Monument State Park and requires a short uphill walk from the parking area.', 'limited', 'https://www.atlasobscura.com/places/first-washington-monument', 'America/New_York', now()),
  ('War Correspondents Memorial Arch', 'war-correspondents-memorial-arch', 'weird-history', 39.40571, -77.63931, 'Jefferson', 'MD', 'Journalist George Alfred Townsend erected this unusual stone arch in 1896 as a memorial to journalists and artists who covered wars. The roughly 50-foot monument now stands in Gathland State Park beside the Appalachian Trail and can be visited from the park''s public grounds.', 'open', 'https://www.atlasobscura.com/places/war-correspondents-memorial', 'America/New_York', now()),
  ('Killiansburg Cave', 'killiansburg-cave', 'weird-history', 39.45879, -77.79609, 'Sharpsburg', 'MD', 'During the Battle of Antietam, local civilians reportedly sheltered beneath this large rock overhang along the Potomac while fighting raged nearby. The site is reached from the C&O Canal towpath near mile 75.7 and requires walking plus a short climb away from the canal, so it is not a drive-up stop.', 'limited', 'https://www.atlasobscura.com/places/killiansburg-cave', 'America/New_York', now()),
  ('Daniels Ghost Town', 'daniels-ghost-town', 'weird-history', 39.31677, -76.81741, 'Ellicott City', 'MD', 'Daniels grew around a textile mill on the Patapsco River before the mill closed in the 1960s and Tropical Storm Agnes devastated the remaining community in 1972. Today hikers can find foundations, cemetery remnants and other traces of the vanished mill town inside the Patapsco Valley area.', 'limited', 'https://www.atlasobscura.com/places/daniels', 'America/New_York', now()),
  ('Clopper Mill Ruins', 'clopper-mill-ruins', 'weird-history', 39.15313, -77.25369, 'Germantown', 'MD', 'A mill operated at this Seneca Creek location from the 18th century until the surviving structure burned in 1947, leaving picturesque stone walls beside the water. The area also has a Lincoln-assassination connection through conspirator George Atzerodt, who was familiar with and sought refuge around the region; reaching the ruins involves park trails and uneven ground.', 'limited', 'https://www.atlasobscura.com/places/ruins-of-clopper-mill', 'America/New_York', now()),
  ('Waters Mill Ruins', 'waters-mill-ruins', 'weird-history', 39.19995, -77.28416, 'Germantown', 'MD', 'The remains of an early-19th-century saw and grist mill sit near Little Seneca Creek along the Black Hill trail system. The site is made darker by the 1920 dynamiting of the nearby miller''s house, an attack that killed three people and eventually led to the execution of Guy Thompson.', 'limited', 'https://www.atlasobscura.com/places/waters-mill-ruins', 'America/New_York', now()),
  ('Seneca Quarry', 'seneca-quarry', 'weird-history', 39.06988, -77.34408, 'Poolesville', 'MD', 'This abandoned quarry supplied the distinctive reddish Seneca sandstone used in major Washington-area buildings, most famously the Smithsonian Castle. Quarry cuts, ruins and related historic features remain within the C&O Canal National Historical Park landscape and are reached on foot.', 'limited', 'https://www.atlasobscura.com/places/seneca-quarry', 'America/New_York', now()),
  ('Marshall Hall Ruins', 'marshall-hall-ruins', 'weird-history', 38.68496, -77.09883, 'Accokeek', 'MD', 'The Marshall family built its Potomac River estate here in the 18th century, and the property later became a popular amusement park complete with rides and a roller coaster. The amusement park closed in 1979, but remnants of the old mansion and later recreational history survive within today''s Piscataway Park.', 'open', 'https://www.nps.gov/pisc/learn/historyculture/about-marshall-hall.htm', 'America/New_York', now()),
  ('Remains of the Truxton Circle Fountain', 'remains-of-the-truxton-circle-fountain', 'weird-history', 38.71027, -77.02762, 'Fort Washington', 'MD', 'A fountain once stood in Washington, D.C.''s Truxton Circle before the traffic circle was removed in the 1940s and the monument seemingly disappeared. Pieces were later identified among discarded stone at Fort Washington Park, where the surviving fragments can be seen in the park rather than at their original D.C. location.', 'open', 'https://www.atlasobscura.com/places/remains-of-truxton-circle-fountain', 'America/New_York', now()),
  ('Glenn Dale Hospital', 'glenn-dale-hospital', 'haunted', 38.96286, -76.80991, 'Glenn Dale', 'MD', 'Opened in 1934 as a tuberculosis sanatorium for Washington, D.C., Glenn Dale later served other patients before closing in 1982. Its abandoned hospital buildings have become a major source of local ghost stories, but entering the structures is prohibited; view them only from legal public roads and trails.', 'roadside', 'https://www.atlasobscura.com/places/glenn-dale-hospital', 'America/New_York', now()),
  ('Jericho Covered Bridge', 'jericho-covered-bridge', 'haunted', 39.45911, -76.39022, 'Kingsville', 'MD', 'This one-lane covered bridge dates to the 1860s and still carries traffic across Little Gunpowder Falls. Local legends attach hanging apparitions, stalled vehicles and stranger creature stories to the bridge, but it remains an active narrow roadway, so do not stop a vehicle inside it or block traffic.', 'roadside', 'https://www.atlasobscura.com/places/jericho-covered-bridge-maryland', 'America/New_York', now()),
  ('Bladensburg Dueling Grounds', 'bladensburg-dueling-grounds', 'weird-history', 38.93356, -76.95199, 'Colmar Manor', 'MD', 'The fields near old Bladensburg became a notorious place for settling political and personal disputes with pistols during the 19th century, earning the nearby stream the nickname “Blood Run.” More than 50 duels are associated with the area, and a marker now interprets the history from the public grounds.', 'open', 'https://www.atlasobscura.com/places/bladensburg-dueling-grounds', 'America/New_York', now()),
  ('Church of the Atonement Cemetery', 'church-of-the-atonement-cemetery', 'folklore', 38.73475, -76.82288, 'Brandywine', 'MD', 'A small cemetery and surviving steps are all that remain of the Church of the Atonement, built in the 19th century and demolished decades after services ended. The isolated burial ground has accumulated witch and ghost folklore over the years; access is awkward near the railroad, so use only legitimate approaches and never cross active tracks unsafely.', 'limited', 'https://www.atlasobscura.com/places/church-of-the-atonement-cemetery', 'America/New_York', now()),
  ('Fort Lincoln Cemetery', 'fort-lincoln-cemetery', 'weird-history', 38.93048, -76.95672, 'Brentwood', 'MD', 'This large active cemetery occupies land with layers of history that include Civil War-era Fort Lincoln earthworks, an old spring house, monuments and a sprawling mausoleum complex. Visitors can see the historic features during cemetery hours but should stay on cemetery roads and treat active burial areas respectfully.', 'open', 'https://www.atlasobscura.com/places/fort-lincoln-cemetery', 'America/New_York', now()),
  ('Cedar Hill Cemetery Faux-Bois Sculptures', 'cedar-hill-cemetery-faux-bois-sculptures', 'weird-history', 38.86023, -76.94105, 'Suitland-Silver Hill', 'MD', 'Cedar Hill Cemetery contains a surprising group of 1930s faux-bois concrete sculptures by Dionicio Rodriguez, made to resemble gnarled trees, logs and rustic wooden structures. The cemetery also contains a mass grave connected to the deadly 1906 Terra Cotta railroad wreck, giving the grounds an unusually layered history.', 'open', 'https://spacesarchives.org/explore/search-the-online-collection/cedar-hill-cemetery/', 'America/New_York', now()),
  ('Aspin Hill Pet Cemetery', 'aspin-hill-pet-cemetery', 'weird-history', 39.0799, -77.07629, 'Aspen Hill', 'MD', 'Established in the early 20th century, Aspin Hill is one of the country''s oldest pet cemeteries and contains tens of thousands of animal burials alongside a smaller number of human graves. Elaborate markers memorialize dogs, cats, birds and other pets, and the cemetery is open for respectful daytime visits.', 'open', 'https://www.atlasobscura.com/places/aspin-hill-pet-cemetery', 'America/New_York', now()),
  ('Fell Family Cemetery', 'fell-family-cemetery', 'folklore', 39.282, -76.59452, 'Baltimore', 'MD', 'The family that gave Fell''s Point its name once had a burial ground here, now reduced to a tiny graveyard squeezed between later Baltimore buildings. Very little remains above ground, and uncertainty over what happened to some of the burials has helped make the small plot a recurring stop in neighborhood ghost lore.', 'open', 'https://www.atlasobscura.com/places/fells-family-cemetery', 'America/New_York', now()),
  ('Roscoe the Rooster Statue', 'roscoe-the-rooster-statue', 'roadside-oddities', 38.97433, -77.01216, 'Takoma Park', 'MD', 'Roscoe was a free-roaming rooster that wandered Takoma Park for roughly a decade and became so beloved that residents memorialized him after he was killed by a vehicle in 1999. A life-size bronze statue now stands along Laurel Avenue and is occasionally dressed or decorated by locals.', 'roadside', 'https://www.atlasobscura.com/places/roscoe-the-rooster', 'America/New_York', now()),
  ('Madonna of the Trail', 'madonna-of-the-trail', 'roadside-oddities', 38.98392, -77.09425, 'Bethesda', 'MD', 'Maryland''s Madonna of the Trail is one of 12 nearly identical pioneer-woman monuments installed across the country along the National Old Trails Road in 1928 and 1929. Dedicated in Bethesda in 1929, the massive stone figure has been moved several times as the surrounding downtown developed but remains publicly viewable beside Wisconsin Avenue.', 'open', 'https://highways.dot.gov/highway-history/general-highway-history/part-4-named-trails-us-numbered-highways/part-j', 'America/New_York', now()),
  ('World''s Largest Engagement Ring', 'worlds-largest-engagement-ring', 'roadside-oddities', 39.43733, -76.62572, 'Timonium', 'MD', 'Smyth Jewelers unveiled this enormous stainless-steel-and-acrylic engagement ring outside its Timonium showroom in 2015. The sculpture stands 17 feet tall and 14 feet wide, was designed as a permanent landmark, and is meant to be approached for photos from the store''s public frontage.', 'open', 'https://www.prnewswire.com/news-releases/smyth-jewelers-and-uneek-fine-jewelry-create-worlds-largest-engagement-ring-300161337.html', 'America/New_York', now()),
  ('Biddison Family Cemetery', 'biddison-family-cemetery', 'weird-history', 39.34005, -76.5552, 'Baltimore', 'MD', 'A tiny 19th-century family cemetery survives improbably in the middle of a modern Baltimore neighborhood, a remnant of the much larger property once owned by the Biddison family. Most graves date to the 1800s, and neighborhood volunteers have periodically cleared vegetation from the otherwise easily overlooked burial ground.', 'open', 'https://www.atlasobscura.com/places/biddison-family-cemetery', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  verified_at   = excluded.verified_at;
