-- Michigan, second batch.
--
-- Eighteen dropped as duplicates of the first batch, and six of those were
-- caught only by position rather than by name: Pickle Barrel House Museum
-- against Pickle Barrel House, Cherry Pie Tin against Cherry Pie - Pan, Seul
-- Choix Point against Seul Choix Pointe, Brown Trout Sculpture against Brown
-- Trout, Cross in the Woods Shrine against Cross in the Woods, and Gravity Hill
-- — Putney Road against Putney Road Gravity Hill.
--
-- A slug check alone would have let all six through and produced visible
-- duplicates on the site. This is the clearest case yet for running both.
--
-- Kept despite flagging: the Wacky Taxidermy and Miniatures Museum, 520 metres
-- from Mystery Town USA. Same tourist strip in Mackinaw City, different places.
--
-- 32 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Allegan County Old Jail Museum', 'allegan-county-old-jail-museum', 'museums', 42.52857, -85.85297, 'Allegan', 'MI', 'Built in 1906, this former county jail and sheriff''s residence remained in use until 1963 and now houses the Allegan County Historical Society''s museum collection. Visitors can see original jail spaces alongside thousands of local artifacts, photographs and historical displays.', 'limited', 'https://alleganchamber.org/members/allegan-county-historical-society/', null, 'America/Detroit', now()),
  ('Fantasy Forest', 'fantasy-forest', 'roadside-oddities', 42.3359, -85.21406, 'Battle Creek', 'MI', 'After emerald ash borers killed many of the trees at Leila Arboretum, artists transformed the dead trunks into a strange outdoor forest of large carved creatures and figures. The project began in 2015 and now contains more than two dozen sculptures that can be explored on foot for free.', 'open', 'https://lasgarden.org/fantasy-forest/', 'https://lasgarden.org/fantasy-forest/', 'America/Detroit', now()),
  ('Historic Bridge Park', 'historic-bridge-park', 'weird-history', 42.29212, -85.1148, 'Battle Creek', 'MI', 'This county park functions as an open-air museum of rescued historic bridges, including several restored metal truss spans moved here from elsewhere in Michigan. Visitors can walk across the bridges, follow riverside trails and also see an unusual stone-and-concrete railroad overpass.', 'open', 'https://historicbridges.org/info/bridgepark/index.php', null, 'America/Detroit', now()),
  ('Dr. J.H. Kellogg Discovery Center', 'dr-jh-kellogg-discovery-center', 'museums', 42.32781, -85.19686, 'Battle Creek', 'MI', 'Part of Historic Adventist Village, this museum explores Dr. John Harvey Kellogg''s unusual ideas about exercise, nutrition and preventive health. Displays include reproductions and examples of the mechanical exercise devices, light treatments and other inventions associated with Battle Creek''s sanitarium era.', 'limited', 'https://www.michigan.org/property/historic-adventist-village', 'https://adventistheritage.org/', 'America/Detroit', now()),
  ('Food Gatherers'' Giant Carrots', 'food-gatherers-giant-carrots', 'roadside-oddities', 42.3178, -83.72719, 'Ann Arbor', 'MI', 'Six oversized concrete carrots stand outside the Food Gatherers warehouse at the appropriately named 1 Carrot Way. The sculptures turn the nonprofit food bank''s carrot logo into a large roadside landmark; visitors should keep the active warehouse driveway clear.', 'roadside', 'https://www.atlasobscura.com/places/food-gatherers-giant-carrots', 'https://www.foodgatherers.org/', 'America/Detroit', now()),
  ('Wave Field', 'wave-field', 'roadside-oddities', 42.29318, -83.71162, 'Ann Arbor', 'MI', 'Artist and architect Maya Lin created this 90-by-90-foot field of sculpted earth for the University of Michigan in 1995. The repeating grassy ridges mimic the mathematics and rhythm of water waves, turning an ordinary lawn into a walk-through landscape artwork.', 'open', 'https://umma.umich.edu/objects/wave-field-aps1995-1/', null, 'America/Detroit', now()),
  ('Face in the Rock', 'face-in-the-rock', 'folklore', 46.4374, -86.81683, 'Au Train', 'MI', 'A weathered human face carved into the sandstone along Lake Superior has become one of the Upper Peninsula''s stranger shoreline landmarks. Local interpretation connects the carving with a nineteenth-century story involving a French voyageur and an Ojibwe leader, although the exact origin of the carving is not firmly documented; reaching it requires a shoreline walk.', 'limited', 'https://www.michigan.org/article/road-trip/one-tank-road-trip-central-upper-peninsula', null, 'America/Detroit', now()),
  ('Cadillac''s KISS Monument', 'cadillacs-kiss-monument', 'weird-history', 44.24968, -85.41393, 'Cadillac', 'MI', 'In October 1975, KISS visited Cadillac after the local high-school football team credited the band''s music with helping inspire a championship season. A granite-and-metal monument near the football field now commemorates the famously elaborate homecoming visit; travelers should visit outside school activities and respect campus rules.', 'limited', 'https://www.atlasobscura.com/places/cadillacs-kiss-monument', null, 'America/Detroit', now()),
  ('Italian Hall Memorial Park', 'italian-hall-memorial-park', 'weird-history', 47.24834, -88.45522, 'Calumet', 'MI', 'On Christmas Eve 1913, a false cry of fire caused a deadly panic during a striking miners'' holiday party at Italian Hall, killing more than 70 people, most of them children. The building was later demolished, but its original stone arch was preserved in this memorial park alongside the names of the victims.', 'open', 'https://www.nps.gov/places/italian-hall-memorial-park.htm', null, 'America/Detroit', now()),
  ('The Man-Killing Clam at Sea Shell City', 'the-man-killing-clam-at-sea-shell-city', 'roadside-oddities', 45.63439, -84.63352, 'Cheboygan', 'MI', 'Sea Shell City has displayed an enormous giant-clam shell weighing hundreds of pounds as its famous "Man-Killing Clam" for decades. The label is classic roadside-showmanship rather than biology, but the shell remains a memorable centerpiece inside this seasonal northern Michigan tourist stop.', 'limited', 'https://www.atlasobscura.com/places/the-man-killing-clam', 'https://www.seashellcitymi.com/', 'America/Detroit', now()),
  ('Detroit Eight Mile-Wyoming Wall', 'detroit-eight-mile-wyoming-wall', 'weird-history', 42.44222, -83.16611, 'Detroit', 'MI', 'This concrete wall was built in 1941 to physically separate a Black neighborhood from a planned white subdivision so developers could obtain federal housing financing under discriminatory lending practices. A section beside Alfonso Wells Memorial Playground now carries murals interpreting Black history, turning the surviving segregation barrier into an important public history site.', 'open', 'https://timeshiftamerica.com/birwood-wall/', null, 'America/Detroit', now()),
  ('Lakenenland Sculpture Park', 'lakenenland-sculpture-park', 'roadside-oddities', 46.4923, -87.15205, 'Chocolay Township', 'MI', 'Artist Tom Lakenen has filled a large wooded property east of Marquette with more than 100 sculptures made largely from scrap iron and industrial leftovers. Visitors can walk or drive through the free outdoor art park at any hour, encountering everything from humorous figures to political and environmental pieces.', 'open', 'https://lakenenland.com/', 'https://lakenenland.com/', 'America/Detroit', now()),
  ('Midwest Miniatures Museum', 'midwest-miniatures-museum', 'museums', 43.06221, -86.22617, 'Grand Haven', 'MI', 'This museum displays highly detailed miniature rooms, buildings and scenes created by artists working at tiny scales. Its current home in downtown Grand Haven contains multiple floors of miniature collections, including architectural interiors and unusually meticulous handmade environments.', 'limited', 'https://www.midwestminiaturesmuseum.org/', 'https://www.midwestminiaturesmuseum.org/', 'America/Detroit', now()),
  ('Moist Towelette Museum', 'moist-towelette-museum', 'museums', 42.72562, -84.47603, 'East Lansing', 'MI', 'Hidden inside an office at Michigan State University''s Abrams Planetarium is an actual collection devoted to packaged moist towelettes. The tiny museum contains examples from businesses and countries around the world, but because it is inside a working office, visitors should call ahead rather than assume drop-in access.', 'limited', 'https://abramsplanetarium.natsci.msu.edu/about/moist-towelette.aspx', null, 'America/Detroit', now()),
  ('Keweenaw Rocket Range', 'keweenaw-rocket-range', 'weird-history', 47.4303, -87.71481, 'Copper Harbor', 'MI', 'At the remote tip of the Keweenaw Peninsula, this former launch site was used during the 1960s for small sounding rockets that collected meteorological data over Lake Superior. A marker and surviving traces commemorate Michigan''s little-known role in early rocket research, but reaching the site involves remote roads and conditions can be highly seasonal.', 'limited', 'https://www.atlasobscura.com/places/keweenaw-rocket-range', null, 'America/Detroit', now()),
  ('Ypsilanti Water Tower', 'ypsilanti-water-tower', 'roadside-oddities', 42.24555, -83.62469, 'Ypsilanti', 'MI', 'Built in 1890 from local stone, Ypsilanti''s tall cylindrical water tower has become famous far beyond its engineering history because of its unmistakably suggestive shape. The National Register-listed structure remains an exterior roadside landmark; the tower itself is not a normal walk-in attraction.', 'roadside', 'https://www.us12heritagetrail.com/asset.asp?aid=135&ait=av', null, 'America/Detroit', now()),
  ('Witch''s Hat Depot Museum', 'witchs-hat-depot-museum', 'museums', 42.45479, -83.65352, 'South Lyon', 'MI', 'South Lyon''s former railroad depot earned the nickname "Witch''s Hat" from its steep conical roof. Saved from demolition and moved to McHattie Park in 1976, the unusual building now anchors the local historical museum complex and opens on a limited schedule.', 'limited', 'https://www.downtownsouthlyon.com/visit/', null, 'America/Detroit', now()),
  ('Calumet Theatre', 'calumet-theatre', 'haunted', 47.24776, -88.45363, 'Calumet', 'MI', 'Opened in 1900 during the Copper Country boom, the ornate Calumet Theatre still hosts performances and scheduled historical tours. Local ghost lore centers on actress Helena Modjeska, whose apparition was reportedly seen by another performer in 1958; the story remains folklore rather than verified history.', 'limited', 'https://www.michigan.org/article/trip-idea/incredibly-haunted-places-upper-peninsula', 'https://calumettheatre.com/', 'America/Detroit', now()),
  ('Fayette Historic Townsite', 'fayette-historic-townsite', 'weird-history', 45.7182, -86.66911, 'Garden', 'MI', 'Fayette preserves the remains of a nineteenth-century iron-smelting company town on the Garden Peninsula. More than 20 historic buildings and ruins survive around the old harbor and industrial area, giving travelers a walkable, state-managed version of a genuine Upper Peninsula ghost town.', 'limited', 'https://www.michigan.gov/recsearch/parks/fayette', null, 'America/Detroit', now()),
  ('The Wacky Taxidermy and Miniatures Museum', 'the-wacky-taxidermy-and-miniatures-museum', 'museums', 45.78052, -84.72625, 'Mackinaw City', 'MI', 'This small museum combines taxidermy animals with more than 60 elaborate miniature dioramas, creating deliberately absurd scenes at tiny scale. It is a legitimate walk-in attraction rather than simply a roadside display, with self-guided viewing through two buildings.', 'limited', 'https://www.michigan.org/property/wacky-taxidermy-and-miniatures-museum', null, 'America/Detroit', now()),
  ('Mourning Museum at Borrowed Time Oddities', 'mourning-museum-at-borrowed-time-oddities', 'museums', 41.83013, -86.25585, 'Niles', 'MI', 'Inside Borrowed Time Oddities is a small museum focused on mourning customs, funerary objects and material culture surrounding death. The collection turns a modern oddities shop into a more structured historical stop, with displays interpreting how people have remembered and cared for the dead.', 'limited', 'https://www.atlasobscura.com/places/the-mourning-museum-at-borrowed-time-oddities', null, 'America/Detroit', now()),
  ('Croswell Swinging Bridge', 'croswell-swinging-bridge', 'roadside-oddities', 43.27522, -82.6237, 'Croswell', 'MI', 'Built in 1905, this narrow pedestrian suspension bridge sways above the Black River and carries the famously odd instruction "Be Good to Your Mother-in-Law." The bridge remains a free public landmark and gives travelers a quick, slightly unnerving walk across the river.', 'open', 'https://www.michigan.org/property/croswell-swinging-bridge', null, 'America/Detroit', now()),
  ('Dinosaur Gardens', 'dinosaur-gardens', 'roadside-oddities', 44.91536, -83.43996, 'Ossineke', 'MI', 'Artist Paul Domke began building this wooded prehistoric attraction in the 1930s, filling the property with hand-built concrete dinosaurs and other oversized creatures. The old-school sculptures and forest trail preserve the look of an early American roadside dinosaur park rather than a modern theme-park interpretation.', 'limited', 'https://www.dinosaurgardensllc.com/', 'https://www.dinosaurgardensllc.com/', 'America/Detroit', now()),
  ('Bottle House Museum', 'bottle-house-museum', 'museums', 44.37337, -86.00935, 'Kaleva', 'MI', 'John Makinen built this unusual house in 1941 using about 60,000 chipped or flawed glass bottles from his local bottling business. The Kaleva Historical Society now operates it as a museum of Finnish-American community history, with the colored bottle walls remaining the building''s main curiosity.', 'limited', 'https://www.kalevamichigan.com/bottle-house-museum', 'https://www.kalevamichigan.com/bottle-house-museum', 'America/Detroit', now()),
  ('Bishop Baraga Shrine', 'bishop-baraga-shrine', 'roadside-oddities', 46.74941, -88.47446, 'L''Anse', 'MI', 'A towering metal statue of nineteenth-century Catholic missionary Bishop Frederic Baraga stands above the wooded hillside near L''Anse. The roughly 35-foot monument shows Baraga holding a cross and snowshoes, referencing the long winter journeys that earned him the nickname "Snowshoe Priest."', 'open', 'https://www.atlasobscura.com/places/bishop-baraga-shrine', null, 'America/Detroit', now()),
  ('Doherty Hotel', 'doherty-hotel', 'haunted', 43.81998, -84.7681, 'Clare', 'MI', 'The Doherty Hotel has operated since the 1920s and has a documented Prohibition-era history that includes the 1938 killing of Isaiah Leebove, a lawyer and businessman associated with Detroit underworld figures. The active hotel also carries longstanding ghost stories involving Leebove and members of the Doherty family, though those paranormal claims remain anecdotal.', 'open', 'https://www.michigan.org/article/trip-idea/look-haunted-places-michigan', null, 'America/Detroit', now()),
  ('American Museum of Magic', 'american-museum-of-magic', 'museums', 42.27229, -84.95832, 'Marshall', 'MI', 'Founded in 1978, this downtown museum preserves an enormous collection of stage-magic history, including posters, props, costumes, illusions and material connected with famous performers. It is one of the strongest OddWay museum stops in southern Michigan because the collection focuses on the mechanics, showmanship and history of supposedly impossible acts.', 'limited', 'https://americanmuseumofmagic.com/', 'https://americanmuseumofmagic.com/', 'America/Detroit', now()),
  ('World''s Largest Weathervane', 'worlds-largest-weathervane', 'roadside-oddities', 43.41608, -86.35457, 'Montague', 'MI', 'Montague''s enormous working weathervane rises roughly 48 feet above Ellenwood Park and is topped by a detailed schooner. The ship represents the Ella Ellenwood, a lumber schooner associated with the area''s nineteenth-century maritime trade.', 'open', 'https://www.whitelake.org/business/worlds-largest-weathervane-and-ellenwood-park/', null, 'America/Detroit', now()),
  ('Fish Ladder Park', 'fish-ladder-park', 'roadside-oddities', 42.97391, -85.67635, 'Grand Rapids', 'MI', 'Artist Joseph Kinnebrew designed this concrete structure as both public sculpture and a functioning fish ladder around a man-made obstacle in the Grand River. During migration periods, visitors can watch fish work their way through the brutalist-looking channels, making the site an unusual mix of infrastructure, ecology and art.', 'open', 'https://www.michigan.org/property/fish-ladder-park', null, 'America/Detroit', now()),
  ('Old Presque Isle Lighthouse', 'old-presque-isle-lighthouse', 'haunted', 45.34197, -83.47825, 'Presque Isle', 'MI', 'Built in 1840 and retired as the area''s primary light in 1871, this small Lake Huron lighthouse now operates as a township park and museum. Persistent local ghost stories claim unusual activity and a mysteriously illuminated lantern, although the museum itself explicitly treats the haunting stories with skepticism.', 'limited', 'https://www.presqueislelighthouses.org/lighthouses/old-presque-isle-lighthouse-1840/', 'https://www.presqueislelighthouses.org/', 'America/Detroit', now()),
  ('Bruce Mansion', 'bruce-mansion', 'haunted', 43.21022, -83.07791, 'Burnside Township', 'MI', 'Built in 1876, the Bruce Mansion is a Victorian landmark with decades of local ghost stories and reported paranormal experiences. The current operators lean directly into that reputation with scheduled mystery tours, events and paranormal visits, giving travelers legitimate access without trespassing on the property.', 'limited', 'https://www.thebrucemansion.com/', 'https://www.thebrucemansion.com/', 'America/Detroit', now()),
  ('Landmark Inn', 'landmark-inn', 'haunted', 46.54474, -87.39202, 'Marquette', 'MI', 'The Landmark Inn is a restored historic hotel in downtown Marquette that has accumulated several long-running ghost stories. The best-known is the legend of the "Lilac Lady," while other accounts involve unexplained calls and activity in upper-floor spaces; the inn remains a normal year-round hotel, restaurant and lounge rather than a dedicated ghost attraction.', 'open', 'https://www.michigan.org/article/trip-idea/incredibly-haunted-places-upper-peninsula', 'https://thelandmarkinn.com/', 'America/Detroit', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  timezone      = excluded.timezone,
  verified_at   = excluded.verified_at;

select count(*) as michigan from public.stops where state = 'MI';
