-- Michigan, third batch.
--
-- Eight dropped as duplicates. Two are worth naming: the Castle Museum's
-- postal inspector peep holes are a feature inside a museum already in the
-- index rather than a separate stop, and The Turning Point is the Snurfer
-- monument under its proper title.
--
-- Pink Elephant goes in as pink-elephant-mio, because Guthrie,
-- Kentucky holds the plain slug.
--
-- One thing the check surfaced that is not about this batch: the Buster Keaton
-- Statue and the Snurfer Monument were inserted with identical coordinates in
-- the first Michigan batch. They are two different objects in Muskegon and one
-- of those pins is wrong. Left alone here because fixing it needs a real
-- location rather than a guess, but it should not be forgotten.
--
-- 42 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('USS Edson — Saginaw Valley Naval Ship Museum', 'uss-edson-saginaw-valley-naval-ship-museum', 'museums', 43.61389, -83.86889, 'Bay City', 'MI', 'The retired destroyer USS Edson now serves as a floating naval museum on the Saginaw River. Visitors can tour the ship''s decks, weapons systems, living quarters and machinery spaces, and the museum also schedules special overnight and paranormal-themed programs.', 'limited', 'https://svnsm.com/', 'https://svnsm.com/', 'America/Detroit', now()),
  ('Singing Sands of Bete Grise', 'singing-sands-of-bete-grise', 'folklore', 47.38679, -87.95703, 'Bete Grise', 'MI', 'The pale sand along Bete Grise Bay can produce a squeaking or humming sound when rubbed or disturbed under the right dry conditions. Local legend gives the phenomenon a more romantic explanation, saying the beach sings back to a woman who once called across the water for her lost lover.', 'open', 'https://www.visitkeweenaw.com/outdoors/water-activities/beaches/', null, 'America/Detroit', now()),
  ('Winegar Cemetery''s Mysterious Glowing Grave', 'winegar-cemeterys-mysterious-glowing-grave', 'haunted', 42.79347, -85.75046, 'Byron Center', 'MI', 'For decades, local legend has claimed that a faint greenish light can sometimes be seen around one grave in Winegar Cemetery after dark. Explanations range from ghost stories to reflected light and atmospheric effects, and the phenomenon is best treated as folklore rather than a verified paranormal event; visitors should obey cemetery hours and remain respectful.', 'limited', 'https://www.roadsideamerica.com/tip/2863', null, 'America/Detroit', now()),
  ('Lakeside Cemetery — Michigan''s Magic Graveyard', 'lakeside-cemetery-michigans-magic-graveyard', 'weird-history', 41.96699, -85.33624, 'Colon', 'MI', 'Colon calls itself the Magic Capital of the World, and Lakeside Cemetery contains the graves of numerous professional magicians connected with the town. Among the best known is Harry Blackstone Sr., making the cemetery an unusual pilgrimage site for the history of American stage magic.', 'open', 'https://www.atlasobscura.com/places/lakeside-cemetery', null, 'America/Detroit', now()),
  ('RoboCop Statue', 'robocop-statue', 'roadside-oddities', 42.35116, -83.04349, 'Detroit', 'MI', 'After years of fundraising and fabrication, Detroit''s long-planned RoboCop statue was installed at Eastern Market in December 2025. The roughly 10-foot bronze figure recreates the armored police cyborg from the 1987 film, which is set in a dystopian version of Detroit.', 'open', 'https://easternmarket.org/robo-cop-statue/', 'https://easternmarket.org/robo-cop-statue/', 'America/Detroit', now()),
  ('USS Kearsarge Stone Ship Memorial', 'uss-kearsarge-stone-ship-memorial', 'roadside-oddities', 47.26935, -88.42012, 'Kearsarge', 'MI', 'Workers built this ship-shaped stone veterans memorial during the 1930s, naming it for the Civil War-era USS Kearsarge. A mining drill stands in for a naval gun on the unusual landlocked vessel, tying Copper Country industry to naval and military remembrance.', 'open', 'https://www.waymarking.com/waymarks/WMCEKY_USS_Kearsarge_Ship_of_Stones_Kearsarge_MI', null, 'America/Detroit', now()),
  ('Keweenaw County Snow Stick', 'keweenaw-county-snow-stick', 'roadside-oddities', 47.35898, -88.30343, 'Mohawk', 'MI', 'This towering measuring-stick display visualizes just how much snow can fall in Michigan''s Keweenaw Peninsula. Markers climb far above a person''s head to represent record seasonal snowfall totals, turning local weather statistics into a memorable roadside landmark.', 'roadside', 'https://www.waymarking.com/waymarks/WMCEM2_The_Snow_Stick_Mohawk_MI', null, 'America/Detroit', now()),
  ('Lake Michigan Underwater Crucifix', 'lake-michigan-underwater-crucifix', 'weird-history', 45.37706, -84.96269, 'Petoskey', 'MI', 'An 11-foot white-marble crucifix lies beneath the waters of Little Traverse Bay after being placed there in 1962 as a memorial to divers who had died. During rare winters with safe, clear ice, organized viewing events have allowed visitors to walk offshore and look down through a cut in the ice; access depends completely on conditions and authorization.', 'limited', 'https://petoskeyarea.com/places/underwater-crucifix/', null, 'America/Detroit', now()),
  ('Meridian-Baseline State Park', 'meridian-baseline-state-park', 'weird-history', 42.42302, -84.35616, 'Leslie', 'MI', 'Michigan''s principal meridian and baseline should have met cleanly here, but early nineteenth-century survey crews working independently created a mismatch of more than 900 feet. The small state park preserves survey monuments marking both lines, turning an old mapping error into a walkable geographic curiosity.', 'open', 'https://www.michigan.gov/recsearch/parks/meridian', null, 'America/Detroit', now()),
  ('Traverse Colantha Walker''s Grave', 'traverse-colantha-walkers-grave', 'weird-history', 44.7482, -85.6476, 'Traverse City', 'MI', 'Traverse Colantha Walker was a prize Holstein associated with the former Northern Michigan Asylum farm and became famous for extraordinary milk production. Her stone grave marker survives on the grounds of Historic Barns Park, preserving one of Traverse City''s stranger pieces of agricultural history.', 'open', 'https://www.roadsideamerica.com/tip/2850', null, 'America/Detroit', now()),
  ('Grave of Felix Schlag — Jefferson Nickel Designer', 'grave-of-felix-schlag-jefferson-nickel-designer', 'weird-history', 42.98638, -84.16977, 'Owosso', 'MI', 'Felix Schlag won the 1938 competition to design the Jefferson nickel, creating the basic portrait and Monticello design used for decades. His grave in Oak Hill Cemetery is marked with a large representation of the coin, and visitors sometimes leave nickels on the stone.', 'limited', 'https://www.atlasobscura.com/places/grave-of-felix-schlag', null, 'America/Detroit', now()),
  ('Frank L. White''s Cream of Wheat Gravestone', 'frank-l-whites-cream-of-wheat-gravestone', 'weird-history', 42.45777, -84.42944, 'Leslie', 'MI', 'Frank L. White is widely associated with the smiling chef image once used for decades on Cream of Wheat packaging. His grave in Woodlawn Cemetery was unmarked until a later memorial was installed featuring the familiar chef image, creating an unusual connection between advertising history and a quiet Michigan cemetery.', 'limited', 'https://www.roadsideamerica.com/tip/9567', null, 'America/Detroit', now()),
  ('Polar Bear Memorial', 'polar-bear-memorial', 'weird-history', 42.5845, -83.16509, 'Troy', 'MI', 'A white marble polar bear marks the burial and memorial area for American soldiers who served in northern Russia during the Allied intervention following World War I. The men became known as the Polar Bears, and the monument preserves a little-known episode in which Michigan troops fought Bolshevik forces thousands of miles from home.', 'limited', 'https://www.roadsideamerica.com/story/19832', null, 'America/Detroit', now()),
  ('Michigan War Dog Memorial', 'michigan-war-dog-memorial', 'weird-history', 42.47586, -83.61374, 'South Lyon', 'MI', 'This memorial park grew from a neglected pet cemetery into a dedicated burial and remembrance site for military, police and service dogs. Rows of markers, memorial walls and ceremonies recognize working animals whose service ranged from combat deployments to law enforcement and assistance work.', 'open', 'https://www.roadsideamerica.com/tip/63288', 'https://mwdm.org/', 'America/Detroit', now()),
  ('An Gorta Mor — Michigan''s Great Hunger Memorial', 'an-gorta-mor-michigans-great-hunger-memorial', 'weird-history', 42.05698, -84.16708, 'Brooklyn', 'MI', 'A stone memorial at the Irish Hills'' St. Joseph Shrine commemorates the victims of Ireland''s Great Famine and the immigrants forced from the country during the nineteenth century. Dedicated in 2004, the monument adds an unexpectedly specific piece of Irish history to a rural Michigan religious complex.', 'open', 'https://www.hmdb.org/m.asp?m=165618', null, 'America/Detroit', now()),
  ('Mormon Print Shop Museum', 'mormon-print-shop-museum', 'museums', 45.74609, -85.52084, 'St. James', 'MI', 'Built in 1850, this small Beaver Island building was used by followers of James Jesse Strang, the self-proclaimed Mormon king whose island community became one of Michigan''s strangest religious experiments. The restored print shop now interprets Strang''s kingdom along with broader Beaver Island history.', 'limited', 'https://www.beaverislandhistory.org/print-shop/', 'https://www.beaverislandhistory.org/print-shop/', 'America/Detroit', now()),
  ('Beaver Island Toy Museum', 'beaver-island-toy-museum', 'museums', 45.74601, -85.50797, 'St. James', 'MI', 'This tiny seasonal museum mixes vintage toys, dolls, miniature objects, handmade art and an eclectic collection assembled over many years on remote Beaver Island. Its informal, densely packed displays make it feel closer to a personal cabinet of curiosities than a conventional museum.', 'limited', 'https://www.atlasobscura.com/places/toy-museum-beaver-island-michigan', null, 'America/Detroit', now()),
  ('Glen Haven Cannery Boat Museum', 'glen-haven-cannery-boat-museum', 'museums', 44.90154, -86.02815, 'Glen Arbor', 'MI', 'A former fruit cannery in the historic village of Glen Haven now houses a collection of traditional Great Lakes and inland-water boats. Dugout canoes, fishing craft and lifesaving vessels fill the bright red building, combining unusual maritime artifacts with the preserved remains of a once-busy Lake Michigan port.', 'limited', 'https://www.atlasobscura.com/places/cannery-boat-museum', null, 'America/Detroit', now()),
  ('Longest Known Mastodon Trackway', 'longest-known-mastodon-trackway', 'museums', 42.27887, -83.73375, 'Ann Arbor', 'MI', 'Inside the University of Michigan Museum of Natural History is a roughly 40-foot cast of more than 20 mastodon footprints discovered near Saline in 1992. Individual mastodon tracks are rare, and this sequence is considered the longest known trackway made by one mastodon.', 'open', 'https://www.atlasobscura.com/places/longest-known-mastodon-trackway', 'https://lsa.umich.edu/ummnh', 'America/Detroit', now()),
  ('Tahquamenon Logging Museum', 'tahquamenon-logging-museum', 'museums', 46.37083, -85.50917, 'Newberry', 'MI', 'This seasonal museum preserves the machinery, buildings and daily-life artifacts of Michigan''s Upper Peninsula logging era. Its grounds include reconstructed camp spaces and equipment that show how crews lived and worked when timber drives shaped much of the region.', 'limited', 'https://www.loggingmuseum.com/', 'https://www.loggingmuseum.com/', 'America/Detroit', now()),
  ('Michigan Flywheelers Museum', 'michigan-flywheelers-museum', 'museums', 42.39531, -86.20227, 'South Haven', 'MI', 'The Michigan Flywheelers preserve antique tractors, steam engines, farm machinery and other pieces of mechanical agricultural history across a large rural site. Demonstrations and major annual events bring many of the machines back to life rather than displaying everything as static museum pieces.', 'limited', 'https://michiganflywheelers.org/', 'https://michiganflywheelers.org/', 'America/Detroit', now()),
  ('Music House Museum', 'music-house-museum', 'museums', 44.77922, -85.49524, 'Williamsburg', 'MI', 'The Music House Museum is filled with mechanical musical instruments that play without conventional live performers, including music boxes, player pianos, organs and large automated machines. Demonstrations turn the collection into a noisy tour through the engineering history of self-playing music.', 'limited', 'https://musichouse.org/hours-location-directions-music-house-museum-michigan/', 'https://musichouse.org/', 'America/Detroit', now()),
  ('Stahls Automotive Foundation Museum', 'stahls-automotive-foundation-museum', 'museums', 42.71783, -82.80683, 'Chesterfield Township', 'MI', 'Stahls combines rare and unusual automobiles with a large collection of automated musical instruments, organs and mechanical music machines. The mixture of transportation and giant self-playing instruments makes the museum substantially stranger than a standard classic-car collection.', 'limited', 'https://www.stahlsauto.com/', 'https://www.stahlsauto.com/', 'America/Detroit', now()),
  ('Call of the Wild Museum', 'call-of-the-wild-museum', 'museums', 45.01892, -84.68254, 'Gaylord', 'MI', 'This old-school wildlife museum uses dozens of taxidermy animals in large dioramas to recreate North American habitats. The dense arrangement of bears, wolves, deer and other mounted animals gives it the distinctive feel of a classic northern Michigan roadside attraction.', 'open', 'https://www.michigan.org/property/call-wild', 'https://callofthewildgaylord.com/', 'America/Detroit', now()),
  ('Michigan Whitetail Hall of Fame Museum', 'michigan-whitetail-hall-of-fame-museum', 'museums', 42.29385, -84.22937, 'Grass Lake', 'MI', 'This museum is devoted almost entirely to exceptionally large whitetail deer and antler records. Displays include dozens of notable racks and hunting-history exhibits, while live deer on the property make the stop part museum and part highly specialized wildlife attraction.', 'open', 'https://www.michigan.org/property/michigan-whitetail-hall-fame-museum', null, 'America/Detroit', now()),
  ('Original Old Rugged Cross Church & Museum', 'original-old-rugged-cross-church-museum', 'weird-history', 41.91208, -86.17393, 'Pokagon Township', 'MI', 'This restored nineteenth-century church is where the final version of George Bennard''s hymn "The Old Rugged Cross" was first sung publicly in 1913. The building now operates as a historical site and small museum, preserving the unexpectedly specific Michigan origin story of one of America''s best-known Christian hymns.', 'limited', 'https://the-oldruggedcross.org/', 'https://the-oldruggedcross.org/', 'America/Detroit', now()),
  ('U.S. National Ski and Snowboard Hall of Fame', 'us-national-ski-and-snowboard-hall-of-fame', 'museums', 46.50292, -87.66554, 'Ishpeming', 'MI', 'Ishpeming played a major role in organized American skiing, and this hall of fame preserves equipment, photographs, trophies and stories connected with the sport''s development. Hundreds of inductees are represented inside a museum that also traces the strange evolution from early wooden skis to modern competition equipment.', 'limited', 'https://skihall.com/', 'https://skihall.com/', 'America/Detroit', now()),
  ('Montrose Historical and Telephone Pioneer Museum', 'montrose-historical-and-telephone-pioneer-museum', 'museums', 43.17778, -83.89056, 'Montrose', 'MI', 'This small local museum preserves switchboards, telephones and other equipment from the era when operators manually connected calls. The collection turns an everyday technology that largely vanished from modern life into a hands-on look at how complicated making a simple phone call once was.', 'limited', 'https://montrosemuseum.com/historical/', 'https://montrosemuseum.com/historical/', 'America/Detroit', now()),
  ('Adventure Mine', 'adventure-mine', 'weird-history', 46.77272, -89.08181, 'Greenland', 'MI', 'Adventure Mine preserves an authentic nineteenth-century copper mine where visitors can descend underground through old workings cut into the rock. Different tours range from conventional walking routes to more demanding excursions deeper into the mine, making access ticketed and seasonal rather than a casual open stop.', 'limited', 'https://adventureminetours.com/', 'https://adventureminetours.com/', 'America/Detroit', now()),
  ('Mythos Museum of Oddities & Curiosities', 'mythos-museum-of-oddities-curiosities', 'museums', 42.63671, -83.291, 'Pontiac', 'MI', 'Mythos is a compact museum devoted to the macabre and unusual, with displays involving funerary objects, bones, medical material, vintage Halloween pieces and other curiosities. Its collection intentionally sits somewhere between oddities shop, sideshow history and modern cabinet of curiosities.', 'limited', 'https://mythosmuseum.com/', 'https://mythosmuseum.com/', 'America/Detroit', now()),
  ('Chief Pontiac Muffler Man — Pontiac Transportation Museum', 'chief-pontiac-muffler-man-pontiac-transportation-museum', 'roadside-oddities', 42.63575, -83.30079, 'Pontiac', 'MI', 'A roughly 25-foot fiberglass figure depicting Chief Pontiac now stands indoors at the Pontiac Transportation Museum after decades as a piece of commercial roadside advertising. The restored figure belongs to the same broad family of giant fiberglass "Muffler Man" statues that once towered over businesses across America.', 'limited', 'https://www.roadsideamerica.com/tip/802', 'https://www.pontiactransportationmuseum.org/visit/', 'America/Detroit', now()),
  ('President McKinley Statue', 'president-mckinley-statue', 'weird-history', 43.23299, -86.25273, 'Muskegon', 'MI', 'Muskegon''s William McKinley statue was dedicated in May 1902, only months after the president''s assassination, making it one of the earliest public monuments erected to him. Its unusually naturalistic pose has also earned it a reputation as one of the less flattering presidential statues in the country.', 'open', 'https://www.roadsideamerica.com/story/32295', null, 'America/Detroit', now()),
  ('St. Joseph Shrine''s Faux-Wood Stations of the Cross', 'st-joseph-shrines-faux-wood-stations-of-the-cross', 'roadside-oddities', 42.0571, -84.16477, 'Brooklyn', 'MI', 'The outdoor Stations of the Cross at this Irish Hills shrine were built from concrete sculpted and painted to imitate logs, roots and rough-hewn wood. Created during the 1930s, the convincing faux-bois work makes the devotional landscape look as if it were constructed from enormous twisted trees rather than cement.', 'open', 'https://www.waymarking.com/waymarks/wm1B2JM_St_Josephs_Shrine_Fake_Wood_Sculptures_Brooklyn_MI', null, 'America/Detroit', now()),
  ('Kaiser Paul — Bunyan Made of Car Parts', 'kaiser-paul-bunyan-made-of-car-parts', 'roadside-oddities', 45.08181, -83.44635, 'Alpena', 'MI', 'This giant Paul Bunyan figure was assembled from pieces of old Kaiser automobiles, turning car fenders and body panels into a northern Michigan folk hero. The roughly 30-foot sculpture now stands at Alpena Community College as a particularly literal combination of auto history and roadside giant.', 'roadside', 'https://www.roadsideamerica.com/story/2421', null, 'America/Detroit', now()),
  ('Wayside Chapel', 'wayside-chapel', 'roadside-oddities', 45.18966, -85.34499, 'Atwood', 'MI', 'This tiny roadside chapel measures only about 12 by 8 feet and contains just a few miniature pews. Built in 1968, it remains an unexpectedly small place of worship along US-31 and is easy to miss despite being only a few steps from the highway.', 'open', 'https://www.roadsideamerica.com/tip/10506', null, 'America/Detroit', now()),
  ('Bangor Viking Muffler Man', 'bangor-viking-muffler-man', 'roadside-oddities', 42.30778, -86.12167, 'Bangor', 'MI', 'A vintage giant fiberglass Viking serves as a mascot at Bangor High School, adapting the classic roadside Muffler Man form into school spirit. Because the figure is on school property near athletic facilities, travelers should view it only from publicly accessible areas and avoid entering restricted grounds.', 'limited', 'https://www.roadsideamerica.com/tip/18457', null, 'America/Detroit', now()),
  ('Talula the Elk Rapids Swan', 'talula-the-elk-rapids-swan', 'roadside-oddities', 44.89617, -85.40957, 'Elk Rapids', 'MI', 'This roughly 15-foot swan began life as a parade float built in 1966 to carry Miss Elk Rapids before eventually becoming a permanent landmark outside the local Chamber of Commerce. Students have helped maintain and repaint Talula over the years, and the oversized bird remains an easy roadside photo stop.', 'roadside', 'https://www.atlasobscura.com/places/talula-the-elk-rapids-swan', 'https://www.elkrapidschamber.org/', 'America/Detroit', now()),
  ('Coleman Veterans Memorial', 'coleman-veterans-memorial', 'weird-history', 43.75451, -84.5773, 'Coleman', 'MI', 'This memorial uses life-size soldier figures to represent veterans from multiple American conflicts. One of its most striking visual devices is the contrast between darker, solid figures representing those who returned and pale "ghost" soldiers representing those who did not.', 'open', 'https://www.michigan.org/property/coleman-veterans-memorial', null, 'America/Detroit', now()),
  ('The River Guardian', 'the-river-guardian', 'roadside-oddities', 44.765, -85.62064, 'Traverse City', 'MI', 'Artist Dewey Blocksma built this approximately 12-foot figure beside the Boardman River from old canoes and other found materials. The towering assemblage appears to guard the riverbank, turning discarded watercraft into one of downtown Traverse City''s strangest pieces of public art.', 'open', 'https://www.atlasobscura.com/places/the-river-guardian', null, 'America/Detroit', now()),
  ('Moxie — Manhole Mastodon', 'moxie-manhole-mastodon', 'roadside-oddities', 43.23408, -86.25215, 'Muskegon', 'MI', 'A life-size bronze mastodon with bright blue tusks appears to climb out of an enormous manhole outside the Muskegon Museum of History and Science. Unveiled in 2019, the sculpture gives Michigan''s official state fossil a deliberately impossible return to the streets of downtown Muskegon.', 'open', 'https://www.roadsideamerica.com/tip/83011', null, 'America/Detroit', now()),
  ('Geographical Center of Michigan''s Lower Peninsula', 'geographical-center-of-michigans-lower-peninsula', 'roadside-oddities', 43.40822, -84.6053, 'Saint Louis', 'MI', 'A roadside monument near Saint Louis marks the calculated geographic center of Michigan''s mitten-shaped Lower Peninsula. The marker turns an otherwise anonymous rural point into a destination for travelers who want to stand, at least by one commonly used calculation, in the literal middle of the Mitten.', 'open', 'https://www.roadsideamerica.com/tip/77961', null, 'America/Detroit', now()),
  ('Pink Elephant', 'pink-elephant-mio', 'roadside-oddities', 44.64778, -84.12976, 'Mio', 'MI', 'A large bright-pink elephant has stood along M-33 in Mio for decades, surviving changing businesses and becoming a local roadside landmark in its own right. The oversized animal now remains outside a commercial property as a quick, unmistakable photo stop.', 'roadside', 'https://www.roadsideamerica.com/tip/54657', null, 'America/Detroit', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  timezone      = excluded.timezone,
  verified_at   = excluded.verified_at;

select count(*) as michigan from public.stops where state = 'MI';
