-- Michigan, final batch, and the Muskegon coordinate fix.
--
-- Six dropped as duplicates. Graffiti Alley goes in as
-- graffiti-alley-ann-arbor, because Baltimore holds the plain slug — two
-- different painted alleys.
--
-- Kept despite flagging: the Banded Iron Formation Stone, 192 metres from the
-- mastodon trackway. Both are outdoor exhibits on the same Ann Arbor campus.
--
-- The Muskegon fix at the end is not what it first looked like. The Buster
-- Keaton statue and the Snurfer monument were sharing one pin, and the
-- coordinate offered as a correction for Keaton was the one already stored —
-- applying it would have changed nothing and left them both on the same spot.
--
-- The addresses settled it instead: Keaton is at the Frauenthal Theater, 415 W
-- Western, which is where the existing pin is. The Snurfer is at 477 W
-- Western, a block away. So Keaton stays and the Snurfer moves, to the
-- coordinate that arrived with the third batch as "The Turning Point" and was
-- dropped as a duplicate — which it was, of the wrongly placed record.
--
-- 44 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Pere Cheney Cemetery', 'pere-cheney-cemetery', 'haunted', 44.57349, -84.63521, 'Beaver Creek Township', 'MI', 'This isolated cemetery is the most visible remnant of Pere Cheney, a nineteenth-century lumber town abandoned after disease and economic decline. Stories about a witch''s curse, ghostly lights and unexplained voices have accumulated around the site, but visitors should treat it primarily as a historic cemetery and remain respectful of the graves.', 'open', 'https://www.atlasobscura.com/places/pere-cheney-cemetery', null, 'America/Detroit', now()),
  ('Superior Dome', 'superior-dome', 'roadside-oddities', 46.56042, -87.39379, 'Marquette', 'MI', 'Northern Michigan University''s enormous geodesic stadium has a 536-foot span and is recognized for the remarkable size of its wooden dome. The structure uses hundreds of massive Douglas-fir beams and can hold thousands of spectators, but interior access depends on university schedules and events.', 'limited', 'https://www.atlasobscura.com/places/superior-dome', null, 'America/Detroit', now()),
  ('Turnip Rock', 'turnip-rock', 'roadside-oddities', 44.06847, -82.91931, 'Port Austin', 'MI', 'Wave erosion carved this Lake Huron sea stack into a top-heavy shape resembling a giant turnip, with trees growing from its narrow summit. The surrounding shoreline is private, so legitimate access is by water—most commonly kayak or boat—and visitors should never attempt to cross private land to reach it.', 'limited', 'https://www.atlasobscura.com/places/turnip-rock', null, 'America/Detroit', now()),
  ('The Tridge', 'the-tridge', 'roadside-oddities', 43.61116, -84.24902, 'Midland', 'MI', 'Built in 1981, the Tridge is a three-way pedestrian bridge centered at the meeting of the Chippewa and Tittabawassee rivers. Three wooden spans radiate from one central support, allowing travelers to cross between three separate riverbanks from a single junction.', 'open', 'https://www.atlasobscura.com/places/tridge-michigan', null, 'America/Detroit', now()),
  ('Ruth Ann Miller Shrine', 'ruth-ann-miller-shrine', 'weird-history', 47.26112, -88.46025, 'Calumet Township', 'MI', 'This remote memorial marks the abandoned mine shaft where six-year-old Ruth Ann Miller fell in 1966 during a tragedy that drew a major rescue effort. The incident helped focus attention on dangerous unsealed shafts across Copper Country; the shrine is reached by an unmarked dirt road and should be treated as a memorial rather than a curiosity to disturb.', 'limited', 'https://www.atlasobscura.com/places/ruth-ann-miller-memorial-shrine', null, 'America/Detroit', now()),
  ('Wahbememe Burial Site and Monument', 'wahbememe-burial-site-and-monument', 'weird-history', 41.79782, -85.66268, 'White Pigeon', 'MI', 'A roadside monument and burial site honors Potawatomi leader Wahbememe, or White Pigeon, for whom the community is named. A dramatic local story claims he ran roughly 150 miles to warn settlers of an attack, although later historical research casts doubt on that version of events.', 'open', 'https://www.atlasobscura.com/places/chief-wahbememe-white-pigeon-memorial', null, 'America/Detroit', now()),
  ('Archduke Stefan of Austria''s Grave', 'archduke-stefan-of-austrias-grave', 'weird-history', 45.06225, -85.67276, 'Suttons Bay', 'MI', 'St. Wenceslaus Cemetery contains the grave of Archduke Stefan of Austria, a member of the Habsburg family who eventually settled in the United States and worked for General Motors. His quiet burial in rural Leelanau County creates an unexpected link between northern Michigan and European royalty.', 'open', 'https://www.atlasobscura.com/places/archduke-austria-grave-st-wenceslaus-michigan', null, 'America/Detroit', now()),
  ('Mission Creek Cemetery', 'mission-creek-cemetery', 'weird-history', 43.61921, -84.79731, 'Mount Pleasant', 'MI', 'This small Native American cemetery beside Mission Creek contains the grave of Ojibwe leader Shaw-Shaw-Waw-Nay-Beece and memorials connected with local Indigenous history. The site is historically significant rather than a conventional attraction, so visitors should keep to public access areas and treat the burial ground with care.', 'open', 'https://www.atlasobscura.com/places/mission-creek-indian-cemetery', null, 'America/Detroit', now()),
  ('Beth Olem Cemetery', 'beth-olem-cemetery', 'weird-history', 42.38235, -83.05161, 'Detroit', 'MI', 'Beth Olem is a nineteenth-century Jewish cemetery completely enclosed by an active automotive manufacturing complex after later industrial development grew around it. Public access is extremely limited to specific scheduled days, making this one of Detroit''s strangest surviving pieces of urban history.', 'limited', 'https://www.atlasobscura.com/places/beth-olem', null, 'America/Detroit', now()),
  ('Gwen Frostic Prints', 'gwen-frostic-prints', 'museums', 44.61911, -86.13728, 'Benzonia', 'MI', 'Artist Gwen Frostic created her nature-inspired block prints inside a remarkable boulder-and-timber studio built into the northern Michigan landscape. Vintage Heidelberg presses still produce work from her original designs, and the studio can be visited during its seasonal operating period.', 'limited', 'https://www.atlasobscura.com/places/gwen-frostic-prints-2', null, 'America/Detroit', now()),
  ('The Hippie Tree', 'the-hippie-tree', 'folklore', 44.75258, -85.65039, 'Traverse City', 'MI', 'A sprawling fallen willow on the former Traverse City State Hospital grounds has been covered in layers of colorful paint by generations of visitors. Local folklore claims the tree is connected with spirits from the old hospital and even calls it a portal to hell, while today it remains a strange trailside folk-art landmark.', 'open', 'https://www.atlasobscura.com/places/the-hippie-tree', null, 'America/Detroit', now()),
  ('Kitch-iti-kipi', 'kitch-iti-kipi', 'roadside-oddities', 46.00417, -86.38195, 'Manistique', 'MI', 'Michigan''s largest freshwater spring is a brilliant emerald pool about 40 feet deep, constantly replenished by thousands of gallons of clear groundwater. Visitors cross the spring on a hand-operated observation raft that provides views of trout, submerged trees and the bubbling bottom.', 'open', 'https://www.atlasobscura.com/places/kitch-iti-kipi', null, 'America/Detroit', now()),
  ('Quincy Dredge No. 2', 'quincy-dredge-no-2', 'weird-history', 47.14558, -88.45681, 'Hancock', 'MI', 'The rusting remains of a massive copper-reclamation dredge sit partly submerged in Torch Lake as a relic of Keweenaw mining. The dredge operated until the 1960s and is now best viewed from public roadside or trail vantage points rather than approached directly.', 'roadside', 'https://www.atlasobscura.com/places/quincy-dredge-2', null, 'America/Detroit', now()),
  ('Jasper Knob', 'jasper-knob', 'roadside-oddities', 46.48559, -87.65659, 'Ishpeming', 'MI', 'This small rocky hill overlooking Ishpeming is composed largely of ancient banded iron formation, preserving geology tied directly to the region''s mining history. A short trail and stair access let visitors climb onto some of the oldest exposed rock found in Michigan.', 'open', 'https://www.atlasobscura.com/places/jasper-knob', null, 'America/Detroit', now()),
  ('Haven Hill', 'haven-hill', 'weird-history', 42.64092, -83.56342, 'White Lake Township', 'MI', 'Henry and Clara Ford''s former country estate once included a large mansion, pool, gardens and recreational facilities high above the surrounding landscape. The mansion burned in 1999, but foundations, a chimney and other ruins remain along public trails within Highland Recreation Area.', 'open', 'https://www.atlasobscura.com/places/haven-hill', null, 'America/Detroit', now()),
  ('Seurat at Saugatuck', 'seurat-at-saugatuck', 'roadside-oddities', 42.65797, -86.20548, 'Saugatuck', 'MI', 'A public restroom building in Wicks Park carries a large community-painted adaptation of Georges Seurat''s famous Sunday-afternoon scene. First painted in 1977, the mural was saved from demolition and has been refreshed by local artists over the years.', 'open', 'https://www.atlasobscura.com/places/seurat-at-saugatuck-s-restroom', null, 'America/Detroit', now()),
  ('Manning Memorial Lighthouse', 'manning-memorial-lighthouse', 'roadside-oddities', 44.8143, -86.06725, 'Empire', 'MI', 'This small working lighthouse was completed in 1991 as a memorial to local fisherman Robert H. Manning, who had long wanted a light in Empire. It stands in a public lakeside park and operates seasonally as a private aid to navigation rather than as a traditional staffed lighthouse.', 'open', 'https://www.atlasobscura.com/places/manning-memorial-lighthouse', null, 'America/Detroit', now()),
  ('Michigan Transportation Employees Memorial', 'michigan-transportation-employees-memorial', 'weird-history', 43.85061, -84.77671, 'Clare', 'MI', 'A series of metal figures at the Clare Welcome Center honors Michigan transportation workers killed while performing their jobs. Dedicated in 1994, the memorial turns an interstate rest stop into an unexpectedly somber piece of roadside public art.', 'open', 'https://www.atlasobscura.com/places/michigan-transportation-employees-memorial', null, 'America/Detroit', now()),
  ('Banded Iron Formation Stone', 'banded-iron-formation-stone', 'roadside-oddities', 42.27765, -83.73541, 'Ann Arbor', 'MI', 'A massive specimen of banded iron formation sits outdoors on the University of Michigan campus as a physical remnant of Earth''s ancient oxygenation history. The alternating iron-rich layers formed billions of years ago and create an unusually deep-time roadside geology stop in the middle of campus.', 'open', 'https://www.atlasobscura.com/places/banded-iron-formation-stone', null, 'America/Detroit', now()),
  ('Ann Arbor Fairy Doors', 'ann-arbor-fairy-doors', 'folklore', 42.27856, -83.75019, 'Ann Arbor', 'MI', 'Tiny decorative doors began appearing around Ann Arbor after artist Jonathan B. Wright created miniature ''fairy'' entrances in the 1990s and early 2000s. Several public examples survive around downtown buildings and shops, creating a walkable scavenger hunt for miniature architecture.', 'open', 'https://www.atlasobscura.com/places/ann-arbor-s-fairy-doors', null, 'America/Detroit', now()),
  ('Detroit Geodesic Dome House', 'detroit-geodesic-dome-house', 'roadside-oddities', 42.32652, -83.07973, 'Detroit', 'MI', 'This pair of steel-reinforced concrete domes forms one of Detroit''s most recognizable unconventional private homes. Built around 2000, the structure can be seen from public streets, but it remains a residence and OddWay visitors should not enter the property.', 'private', 'https://www.atlasobscura.com/places/geodesic-dome-house', null, 'America/Detroit', now()),
  ('The Fist — Joe Louis Monument', 'the-fist-joe-louis-monument', 'roadside-oddities', 42.32874, -83.04455, 'Detroit', 'MI', 'Robert Graham''s 24-foot bronze arm and clenched fist was installed in 1987 as a monument to heavyweight champion Joe Louis. Suspended beneath a pyramidal frame near Woodward and Jefferson, the sculpture has become one of Detroit''s most unmistakable pieces of public art.', 'open', 'https://www.atlasobscura.com/places/giant-boxing-arm-of-joe-louis', null, 'America/Detroit', now()),
  ('The Emergency Ark', 'the-emergency-ark', 'roadside-oddities', 43.97864, -83.12342, 'Port Austin', 'MI', 'Artist Scott Hocking transformed a collapsing nineteenth-century barn into a huge ship-like sculpture in 2015. The resulting ''barnboat'' appears stranded in a field near Port Austin and is best treated as a roadside art stop rather than an invitation to enter the surrounding property.', 'roadside', 'https://www.atlasobscura.com/places/emergency-ark-port-austin-michigan', null, 'America/Detroit', now()),
  ('Camp Grayling Military Cemetery', 'camp-grayling-military-cemetery', 'weird-history', 44.64557, -84.75347, 'Grayling', 'MI', 'At the top of Mount Franklin in Hanson Hills is an exceptionally small military cemetery containing only two marked servicemen''s graves. The fenced plot is maintained in connection with Camp Grayling and can be reached on foot through the public recreation area.', 'open', 'https://www.atlasobscura.com/places/camp-grayling-military-cemetery', null, 'America/Detroit', now()),
  ('Bay Mills Old Indian Burial Ground', 'bay-mills-old-indian-burial-ground', 'weird-history', 46.4533, -84.60461, 'Brimley', 'MI', 'This historic Ojibwe burial ground contains weathered wooden spirit houses and a large white pine connected with Bay Mills community history. The cemetery is closed to general public entry, so travelers should view it only from permitted public areas along the perimeter and never enter the grounds.', 'private', 'https://www.atlasobscura.com/places/bay-mills-old-indian-burial-ground', null, 'America/Detroit', now()),
  ('Graffiti Alley', 'graffiti-alley-ann-arbor', 'roadside-oddities', 42.27945, -83.74442, 'Ann Arbor', 'MI', 'A narrow downtown passage off East Liberty Street has evolved into an ever-changing public graffiti environment. Layers of tags, murals, stickers and new paintings regularly cover earlier work, making the alley look different from one visit to the next.', 'open', 'https://www.atlasobscura.com/places/graffiti-alley-ann-arbor', null, 'America/Detroit', now()),
  ('Giant Cow Head', 'giant-cow-head', 'roadside-oddities', 42.38504, -82.96106, 'Detroit', 'MI', 'An enormous cow head still watches over Mack Avenue from the roof of a former dairy and ice-cream building. The oversized relic of roadside advertising survived long after the original business disappeared and can be viewed from surrounding public streets.', 'roadside', 'https://www.atlasobscura.com/places/giant-cow-head', null, 'America/Detroit', now()),
  ('Mount Arvon', 'mount-arvon', 'weird-history', 46.75549, -88.15596, 'Skanee', 'MI', 'Michigan''s highest point was not officially recognized as the state high point until improved measurements showed it exceeded nearby Mount Curwood by roughly 11 inches. Reaching the summit involves remote logging roads and a short hike, so road conditions can make access difficult during wet or snowy weather.', 'limited', 'https://www.atlasobscura.com/places/mount-arvon', null, 'America/Detroit', now()),
  ('Handfuls of Small Stones', 'handfuls-of-small-stones', 'roadside-oddities', 42.97985, -85.67293, 'Grand Rapids', 'MI', 'A small plaque beside the Grand River commemorates an event that never happened in this universe. It belongs to Eames Demetrios''s worldwide Kcymaerxthaere project, which installs physical markers describing people, places and events from an elaborate fictional parallel world.', 'open', 'https://www.atlasobscura.com/places/handfuls-of-small-stones', null, 'America/Detroit', now()),
  ('Detroit Industrial Gallery', 'detroit-industrial-gallery', 'roadside-oddities', 42.38736, -82.9513, 'Detroit', 'MI', 'Artist Tim Burke created an outdoor sculpture environment using architectural fragments salvaged from demolished Detroit landmarks. Stone, metal and building pieces from lost factories, institutions and department stores have been repurposed into a physical collage of the city''s disappearing industrial landscape.', 'roadside', 'https://www.atlasobscura.com/places/detroit-industrial-gallery', null, 'America/Detroit', now()),
  ('Woolsey Memorial Airport', 'woolsey-memorial-airport', 'weird-history', 45.16435, -85.57548, 'Northport', 'MI', 'This public grass-strip airport commemorates Army aviator Clinton F. Woolsey, who died during the 1927 Pan-American Goodwill Flight. Its rustic stone terminal and open field make the site look more like an early aviation outpost than a modern airport; winter operations are restricted and visitors should stay clear of active runways.', 'limited', 'https://www.atlasobscura.com/places/woolsey-memorial-airport', null, 'America/Detroit', now()),
  ('Michigan Theatre Parking Garage', 'michigan-theatre-parking-garage', 'weird-history', 42.3345, -83.0531, 'Detroit', 'MI', 'Detroit''s once-opulent 1920s Michigan Theatre was partially gutted and converted into a parking garage rather than completely demolished. Cars now park beneath surviving plasterwork, balconies and fragments of the old auditorium, creating one of the strangest adaptive-reuse spaces in the city.', 'limited', 'https://www.atlasobscura.com/places/michigan-theatre', null, 'America/Detroit', now()),
  ('Caryatids of Book Tower', 'caryatids-of-book-tower', 'roadside-oddities', 42.3335, -83.05145, 'Detroit', 'MI', 'Twelve sculpted female figures line the exterior of Detroit''s restored Book Tower, appearing to support part of the building high above Washington Boulevard. The unusual caryatids survive from the tower''s elaborate early twentieth-century design and can be viewed from public downtown streets.', 'open', 'https://www.atlasobscura.com/places/the-book-tower-detroit-michigan', null, 'America/Detroit', now()),
  ('Fierce Encounter — Giant Bronze Bears', 'fierce-encounter-giant-bronze-bears', 'roadside-oddities', 41.9646, -83.6743, 'Dundee', 'MI', 'Two enormous bronze grizzly bears battle over an animal carcass outside the Dundee Cabela''s in a sculpture commonly promoted as one of the world''s largest bronze wildlife monuments. The roughly 24-foot composition is directly accessible around the store entrance as a free exterior photo stop.', 'open', 'https://www.waymarking.com/waymarks/wmEHRN_Dundee_Michigan_Worlds_Largest_Bronze_Wildlife_Sculpture', null, 'America/Detroit', now()),
  ('Grand Haven Musical Fountain', 'grand-haven-musical-fountain', 'roadside-oddities', 43.06603, -86.23782, 'Grand Haven', 'MI', 'Operating since 1962, this enormous synchronized fountain sends water more than 100 feet into the air while lights and music are choreographed to the jets. Free shows run on seasonal evenings, so the installation is a legitimate stop only when the fountain''s current show calendar is active.', 'limited', 'https://www.ghfountain.org/', null, 'America/Detroit', now()),
  ('Pine Mountain Ski Jump', 'pine-mountain-ski-jump', 'roadside-oddities', 45.8375, -88.09111, 'Iron Mountain', 'MI', 'The towering Pine Mountain ski jump rises above Iron Mountain as one of the Upper Peninsula''s most dramatic pieces of sports infrastructure. It hosts major ski-jumping competition and can be seen year-round, but access to the jump structure and event areas depends on current schedules and restrictions.', 'limited', 'https://www.roadsideamerica.com/location/mi/all', null, 'America/Menominee', now()),
  ('Michigan Heroes Museum', 'michigan-heroes-museum', 'museums', 43.31841, -83.73537, 'Frankenmuth', 'MI', 'This small museum focuses specifically on Michigan men and women connected with military service and the U.S. space program. Uniforms, photographs and personal artifacts create an unusually local approach to wars, veterans and astronauts rather than a generic military collection.', 'open', 'https://www.frankenmuth.org/directory/michigan-heroes-museum/', null, 'America/Detroit', now()),
  ('Sparty the Spartan', 'sparty-the-spartan', 'roadside-oddities', 42.73108, -84.48753, 'East Lansing', 'MI', 'Michigan State University''s massive Spartan figure is one of the school''s defining landmarks and was originally created from glazed terra-cotta sections. A bronze replica now stands outdoors at the prominent campus site while the fragile original is preserved indoors.', 'open', 'https://www.waymarking.com/waymarks/WM1B98J_Sparty_the_Spartan_Worlds_Largest_Free_Standing_Ceramic_Figure_East_Lansing_MI', null, 'America/Detroit', now()),
  ('Walk of the Planets', 'walk-of-the-planets', 'roadside-oddities', 45.74583, -87.05293, 'Escanaba', 'MI', 'Escanaba''s downtown contains a 1.3-mile scale model of the solar system beginning with the Sun and continuing past markers for the planets. The distances between the markers are scaled to emphasize just how much empty space separates the worlds in the real solar system.', 'open', 'https://www.roadsideamerica.com/tip/82478', null, 'America/Detroit', now()),
  ('Michigan Central Station', 'michigan-central-station', 'weird-history', 42.3287, -83.0775, 'Detroit', 'MI', 'Opened in 1913, Michigan Central Station became one of America''s most famous abandoned buildings after passenger service ended in 1988. Ford restored and reopened the monumental station in 2024 as part of an innovation campus, turning a long-standing ruin into one of Detroit''s most dramatic preservation reversals.', 'limited', 'https://www.atlasobscura.com/things-to-do/detroit-michigan', null, 'America/Detroit', now()),
  ('Belle Isle Aquarium', 'belle-isle-aquarium', 'museums', 42.3379, -82.9856, 'Detroit', 'MI', 'Opened in 1904, Belle Isle Aquarium is one of America''s oldest surviving public aquarium buildings and is known for its long, green-tiled gallery. The restored aquarium now displays freshwater and saltwater species during limited weekly public hours.', 'limited', 'https://www.atlasobscura.com/things-to-do/detroit-michigan', null, 'America/Detroit', now()),
  ('Detroit Industry Murals', 'detroit-industry-murals', 'weird-history', 42.3594, -83.0645, 'Detroit', 'MI', 'Diego Rivera''s monumental Detroit Industry fresco cycle covers the walls of the Detroit Institute of Arts'' Rivera Court with workers, machinery and industrial processes inspired by Ford factories. Painted in the early 1930s, the murals remain an unusually intense artistic record of Detroit''s manufacturing era.', 'limited', 'https://www.atlasobscura.com/things-to-do/detroit-michigan', null, 'America/Detroit', now()),
  ('Dequindre Cut Greenway', 'dequindre-cut-greenway', 'roadside-oddities', 42.3439, -83.0336, 'Detroit', 'MI', 'A former below-grade railroad corridor has been converted into a public greenway lined with large murals and layers of Detroit street art. The unusual sunken route lets walkers and cyclists move through the city inside what feels like a long outdoor graffiti gallery.', 'open', 'https://www.atlasobscura.com/things-to-do/detroit-michigan', null, 'America/Detroit', now()),
  ('Skull Cave', 'skull-cave', 'weird-history', 45.859, -84.6221, 'Mackinac Island', 'MI', 'This shallow limestone cave earned its name after human bones were reportedly found inside during the eighteenth century. The cave is tied to Mackinac Island''s wartime and burial history and can be reached from the island''s public road-and-trail network without motor vehicles.', 'open', 'https://www.atlasobscura.com/things-to-do/michigan', null, 'America/Detroit', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  timezone      = excluded.timezone,
  verified_at   = excluded.verified_at;

update public.stops set
  latitude = 43.23386,
  longitude = -86.25308
where slug = 'snurfer-monument-birthplace-of-snowboarding';

select count(*) as michigan from public.stops where state = 'MI';
