-- Michigan, first batch.
--
-- Three dropped as duplicates: the Uniroyal tire at 7 metres, the Hiawatha
-- statue at 2, and Arcadia Gravity Hill, which we already hold as Putney Road
-- Gravity Hill 4 metres away.
--
-- Mystery Spot goes in as mystery-spot-st-ignace, because Santa Cruz,
-- California holds the plain slug. Two different tilted rooms — and the piece
-- in this index about mystery spots argues that they are all the same room.
--
-- One stop near Sault Ste Marie resolved to America/Toronto, which keeps
-- identical Eastern rules but is the wrong country for a Michigan label.
-- Normalised. America/Menominee is left alone: that is a genuine Michigan zone
-- for the Central-time counties in the western Upper Peninsula.
--
-- The Paulding Light is the first ghost light to reach the index, and it is
-- filed as folklore rather than something invented whole. The lights are real;
-- Michigan Tech students traced them to headlights on US-45 about four and a
-- half miles away.
--
-- 47 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Michigan Dogman — Mystery Town USA', 'michigan-dogman-mystery-town-usa', 'cryptids', 45.77956, -84.73281, 'Mackinaw City', 'MI', 'Michigan''s Dogman is a long-running canine-humanoid legend that became especially famous through northern Michigan storytelling and radio culture. Mystery Town USA gives the creature a real, legal destination through a dedicated Dogman exhibit inside its walkthrough of cryptids, UFOs and other mysteries.', 'open', 'https://mysterytownusa.com/portfolio-items/michigan-dogman/', 'https://mysterytownusa.com/', 'America/Detroit', now()),
  ('Da Yoopers Tourist Trap', 'da-yoopers-tourist-trap', 'roadside-oddities', 46.49228, -87.69794, 'Ishpeming', 'MI', 'This proudly ridiculous Upper Peninsula attraction mixes Yooper humor with homemade machines, mining jokes and enormous outdoor sculptures. Its best-known pieces include Big Gus, an oversized working chainsaw, and Big Ernie, a gigantic rifle, giving travelers multiple oddities at one easy roadside stop.', 'open', 'https://www.michigan.org/property/da-yoopers-tourist-trap', null, 'America/Detroit', now()),
  ('Mystery Spot', 'mystery-spot-st-ignace', 'roadside-oddities', 45.8758, -84.80803, 'St. Ignace', 'MI', 'Opened in the 1950s, this classic roadside "mystery spot" uses tilted construction and visual cues to make visitors feel as though gravity is behaving incorrectly. The seasonal attraction has grown to include the original gravity experience plus other family attractions, but the old mystery-house presentation remains the reason it belongs on OddWay.', 'limited', 'https://www.atlasobscura.com/places/mystery-spot', 'https://www.mysteryspotstignace.com/', 'America/Detroit', now()),
  ('Mystery Hill', 'mystery-hill', 'roadside-oddities', 42.05594, -84.1399, 'Onsted', 'MI', 'Mystery Hill has been confusing Irish Hills travelers since 1952 with rooms and demonstrations where water, balls and people appear to defy gravity. The revived attraction also includes Ward Hall''s Strange Oddities, with sideshow-style curiosities and unusual animal specimens.', 'limited', 'https://visitmysteryhill.com/', 'https://visitmysteryhill.com/', 'America/Detroit', now()),
  ('Paulding Light Viewing Area', 'paulding-light-viewing-area', 'folklore', 46.40129, -89.17907, 'Watersmeet', 'MI', 'For generations, people have gathered at the end of an old roadway to watch a mysterious light appear in the distance, inspiring stories about a ghostly railroad worker and other supernatural explanations. Experiments have strongly connected the phenomenon to distant vehicle headlights, but the established public viewing area keeps the Paulding Light one of Michigan''s most enduring legend-tripping stops.', 'roadside', 'https://www.atlasobscura.com/places/the-paulding-light', null, 'America/Detroit', now()),
  ('Anatomy of Death Museum', 'anatomy-of-death-museum', 'museums', 42.59822, -82.89161, 'Mount Clemens', 'MI', 'This small museum focuses directly on death, medicine, mourning and mortuary history rather than conventional local history. Displays include embalming and funeral equipment, anatomical material and other macabre artifacts, making it one of Michigan''s strongest indoor OddWay stops.', 'open', 'https://www.atlasobscura.com/places/the-anatomy-of-death-museum', 'https://www.anatomyofdeathmuseum.com/', 'America/Detroit', now()),
  ('Sanilac Petroglyphs Historic State Park', 'sanilac-petroglyphs-historic-state-park', 'weird-history', 43.65778, -83.01861, 'Cass City', 'MI', 'A sandstone outcrop here contains Michigan''s largest known collection of Indigenous rock carvings, including figures and teachings associated with Anishinaabe history. The site is jointly interpreted with the Saginaw Chippewa Indian Tribe, and the protected petroglyph viewing area is accessed through scheduled seasonal tours rather than unrestricted handling of the carvings.', 'limited', 'https://www.michigan.gov/recsearch/parks/sanilac', null, 'America/Detroit', now()),
  ('The Heidelberg Project', 'the-heidelberg-project', 'roadside-oddities', 42.35892, -83.0215, 'Detroit', 'MI', 'Artist Tyree Guyton began transforming vacant lots and abandoned houses on Heidelberg Street in 1986 using painted dots, discarded objects, shoes, clocks and other found material. The result became an internationally known outdoor art environment spread through a real Detroit neighborhood.', 'open', 'https://www.heidelberg.org/', 'https://www.heidelberg.org/', 'America/Detroit', now()),
  ('Hamtramck Disneyland', 'hamtramck-disneyland', 'roadside-oddities', 42.40722, -83.05862, 'Hamtramck', 'MI', 'Ukrainian immigrant Dmytro Szylak spent decades filling the space above and behind his garages with whirligigs, wooden figures, airplanes, lights and handmade moving sculptures. Hatch Art now preserves the folk-art environment, which can be viewed from the alley and has scheduled volunteer restoration days. Address: 12087 Klinger St., Hamtramck, MI', 'open', 'https://www.hatchart.org/hamtramck-disneyland', null, 'America/Detroit', now()),
  ('Dymaxion House — The Henry Ford', 'dymaxion-house-the-henry-ford', 'museums', 42.30369, -83.23422, 'Dearborn', 'MI', 'Buckminster Fuller''s experimental Dymaxion House was designed as a lightweight, mass-producible aluminum home suspended around a central mast. A surviving prototype has been reconstructed inside The Henry Ford, allowing visitors to walk through one of the twentieth century''s strangest attempts to reinvent ordinary housing.', 'limited', 'https://www.atlasobscura.com/places/dymaxion-house', 'https://www.thehenryford.org/', 'America/Detroit', now()),
  ('Gilmore Car Museum', 'gilmore-car-museum', 'museums', 42.43978, -85.42007, 'Hickory Corners', 'MI', 'More than 400 vehicles fill a sprawling 90-acre campus of historic barns, recreated dealerships and automotive displays. The scale, unusual prototypes and preserved pieces of roadside motoring culture make Gilmore much more than a conventional rows-of-cars museum.', 'open', 'https://gilmorecarmuseum.org/', 'https://gilmorecarmuseum.org/', 'America/Detroit', now()),
  ('Air Zoo Aerospace & Science Museum', 'air-zoo-aerospace-science-museum', 'museums', 42.22867, -85.55563, 'Portage', 'MI', 'The Air Zoo mixes more than a hundred aircraft and space artifacts with flight simulators and indoor amusement-style rides. Highlights include rare military aircraft and an SR-71B Blackbird, creating an unusually theatrical aviation museum rather than a quiet hangar display.', 'open', 'https://www.airzoo.org/', 'https://www.airzoo.org/', 'America/Detroit', now()),
  ('USS Silversides Submarine Museum', 'uss-silversides-submarine-museum', 'museums', 43.22958, -86.33264, 'Muskegon', 'MI', 'USS Silversides is a highly decorated World War II submarine preserved as a museum ship beside Lake Michigan. As of September 2026 the submarine itself is temporarily away for scheduled dry-dock work through roughly mid-October, while the shore museum remains open, so OddWay should flag the current limited access.', 'limited', 'https://silversidesmuseum.org/', 'https://silversidesmuseum.org/', 'America/Detroit', now()),
  ('Snurfer Monument — Birthplace of Snowboarding', 'snurfer-monument-birthplace-of-snowboarding', 'weird-history', 43.23507, -86.25337, 'Muskegon', 'MI', 'Sherm Poppen invented the Snurfer in Muskegon in 1965 by fastening skis together as a toy for his daughters, helping launch what became modern snowboarding. The downtown sculpture called The Turning Point shows a child riding a Snurfer above a modern snowboarder.', 'open', 'https://www.roadsideamerica.com/tip/33885', null, 'America/Detroit', now()),
  ('Jonathan Walker''s Branded Hand Grave', 'jonathan-walkers-branded-hand-grave', 'weird-history', 43.226, -86.23446, 'Muskegon', 'MI', 'Abolitionist sea captain Jonathan Walker was branded on his right hand with the letters "SS" for "slave stealer" after attempting to help seven enslaved people escape from Florida in 1844. His monument stands just inside Evergreen Cemetery and prominently reproduces the branded hand that became a symbol of the antislavery movement.', 'open', 'https://www.nps.gov/people/jonathan-walker.htm', 'https://muskegon-mi.gov/city-services/public-works/cemetery/evergreen-cemetery-and-potters-field/', 'America/Detroit', now()),
  ('Buster Keaton Statue', 'buster-keaton-statue', 'roadside-oddities', 43.23507, -86.25337, 'Muskegon', 'MI', 'Silent-film legend Buster Keaton spent important childhood summers performing with his family in the Muskegon Actors'' Colony. A bronze statue installed downtown shows Keaton beside an old motion-picture camera, connecting the city to one of early cinema''s strangest physical comedians.', 'open', 'https://www.hmdb.org/m.asp?m=119651', null, 'America/Detroit', now()),
  ('Great Lakes Shipwreck Museum', 'great-lakes-shipwreck-museum', 'museums', 46.77056, -84.95667, 'Paradise', 'MI', 'Whitefish Point has witnessed some of Lake Superior''s most notorious maritime disasters, and its museum preserves artifacts recovered from Great Lakes wrecks. The collection''s centerpiece is the bell recovered from the Edmund Fitzgerald, displayed as a memorial to the ship''s 29 crew members.', 'limited', 'https://shipwreckmuseum.com/', 'https://shipwreckmuseum.com/', 'America/Detroit', now()),
  ('Great Lakes Maritime Heritage Center', 'great-lakes-maritime-heritage-center', 'museums', 45.06698, -83.43282, 'Alpena', 'MI', 'NOAA''s free visitor center interprets the extraordinary concentration of shipwrecks protected in Thunder Bay National Marine Sanctuary. Visitors can walk through a life-size schooner recreation, experience a simulated Great Lakes storm and examine enormous timbers from wrecked vessels without going underwater.', 'open', 'https://thunderbay.noaa.gov/visit/great-lakes-maritime-heritage-center.html', null, 'America/Detroit', now()),
  ('Quincy Mine', 'quincy-mine', 'weird-history', 47.13702, -88.57477, 'Hancock', 'MI', 'The Quincy Mining Company became one of the Keweenaw Peninsula''s most successful copper operations and left behind an enormous industrial landscape. Guided tours descend underground and visit the massive No. 2 hoist house, home to one of the world''s largest steam-powered mine hoists.', 'limited', 'https://www.quincymine.com/', 'https://www.quincymine.com/', 'America/Detroit', now()),
  ('Delaware Copper Mine', 'delaware-copper-mine', 'weird-history', 47.42417, -88.09861, 'Mohawk', 'MI', 'The Delaware Mine preserves an unsuccessful nineteenth-century copper operation whose underground levels can now be explored on a self-guided tour. Visitors descend into the mine at their own pace while the abandoned surface landscape preserves another chapter of the Keweenaw copper boom.', 'limited', 'https://www.delawareminetours.com/', 'https://www.delawareminetours.com/', 'America/Detroit', now()),
  ('Fayette Historic State Park', 'fayette-historic-state-park', 'weird-history', 45.71669, -86.66111, 'Garden', 'MI', 'Fayette was built around an iron-smelting operation in the 1860s and largely emptied after the company shut down in 1891. More than 20 restored buildings and industrial ruins now form an unusually intact ghost town on the Lake Michigan shoreline.', 'open', 'https://www.michigan.gov/recsearch/parks/fayette', null, 'America/Detroit', now()),
  ('Iron Mountain Iron Mine', 'iron-mountain-iron-mine', 'weird-history', 45.78242, -87.86402, 'Vulcan', 'MI', 'Visitors ride a small underground train into a former iron mine and walk through cool, dark workings beneath the Upper Peninsula. The combination of mining machinery, underground passages and old-fashioned tour presentation makes it a classic regional roadside attraction.', 'limited', 'https://www.michigan.org/property/iron-mountain-iron-mine', null, 'America/Menominee', now()),
  ('Top of the Lake Snowmobile Museum', 'top-of-the-lake-snowmobile-museum', 'museums', 46.09463, -85.45048, 'Naubinway', 'MI', 'More than 150 antique and unusual snow machines trace the evolution of snow travel in a region where winter transportation became a way of life. The collection includes prototypes, rare rear-engine sleds and machines that look far stranger than modern snowmobiles.', 'open', 'https://www.michigan.org/property/top-lake-snowmobile-museum', 'https://www.snowmobilemuseum.com/', 'America/Detroit', now()),
  ('U.S. Ski & Snowboard Hall of Fame', 'us-ski-snowboard-hall-of-fame', 'museums', 46.48823, -87.66626, 'Ishpeming', 'MI', 'Ishpeming helped organize competitive skiing in the United States, making it a fitting home for the national hall of fame devoted to skiing and snowboarding. The museum preserves equipment, photographs and stories from generations of athletes, though current hours are limited and an appointment is recommended.', 'limited', 'https://www.skihall.com/', 'https://www.skihall.com/', 'America/Detroit', now()),
  ('Giant Stormy Kromer Cap', 'giant-stormy-kromer-cap', 'roadside-oddities', 46.4616, -90.14394, 'Ironwood', 'MI', 'Stormy Kromer''s famous wool cap is manufactured in Ironwood, and an enormous version of it sits outside the factory on Wall Street. The giant cap can be viewed anytime, while the factory store and scheduled tours provide a closer look at the century-old Michigan clothing brand.', 'open', 'https://www.atlasobscura.com/places/stormy-kromer-cap-factory', 'https://www.stormykromer.com/', 'America/Menominee', now()),
  ('Onaway Steers the World', 'onaway-steers-the-world', 'roadside-oddities', 45.35556, -84.23459, 'Onaway', 'MI', 'A roughly 30-foot steering wheel towers beside the road in Onaway as a tribute to the city''s history manufacturing wooden automobile steering wheels. Built by local metal artist Tom Moran, the sculpture turns a forgotten piece of Michigan automotive history into an oversized visual pun.', 'open', 'https://www.atlasobscura.com/places/onaway-steers-the-world', null, 'America/Detroit', now()),
  ('Cross in the Woods and Nun Doll Museum', 'cross-in-the-woods-and-nun-doll-museum', 'museums', 45.39783, -84.63091, 'Indian River', 'MI', 'This Catholic shrine is dominated by an enormous outdoor crucifix and also contains an unexpectedly specific museum of more than 500 dolls dressed to represent hundreds of religious orders. The grounds are open year-round during daylight hours, while the doll museum follows posted daily hours.', 'open', 'https://crossinthewoods.com/doll-museum/', 'https://crossinthewoods.com/', 'America/Detroit', now()),
  ('Castle Rock and Paul Bunyan', 'castle-rock-and-paul-bunyan', 'roadside-oddities', 45.91013, -84.74319, 'St. Ignace', 'MI', 'Castle Rock has operated as an old-school Upper Peninsula tourist stop since 1929, sending visitors up a steep staircase to the top of a nearly 200-foot limestone stack. Large Paul Bunyan and Babe the Blue Ox figures wait outside the gift shop, adding classic roadside kitsch to the natural formation.', 'limited', 'https://www.atlasobscura.com/places/castle-rock-st-ignace', null, 'America/Detroit', now()),
  ('Shrine of the Pines', 'shrine-of-the-pines', 'museums', 43.85983, -85.8483, 'Baldwin', 'MI', 'Raymond Overholzer spent years turning naturally fallen pine roots, stumps and branches into highly polished furniture without conventional metal fasteners. The hunting-lodge museum now contains more than 200 of his handmade pieces, including enormous tables, beds and chandeliers.', 'limited', 'https://www.michigan.org/property/shrine-pines', null, 'America/Detroit', now()),
  ('World''s Largest Brown Trout', 'worlds-largest-brown-trout', 'roadside-oddities', 43.89733, -85.85157, 'Baldwin', 'MI', 'Artist Ivan Iler built this roughly 25-foot metal trout to commemorate Baldwin''s connection to the first recorded stocking of brown trout in American waters. Installed downtown in 2018, the fish was intentionally made large enough to surpass another giant brown trout sculpture in New Zealand.', 'open', 'https://www.atlasobscura.com/places/world-s-largest-brown-trout-sculpture', null, 'America/Detroit', now()),
  ('Pickle Barrel House', 'pickle-barrel-house', 'museums', 46.67092, -85.98469, 'Grand Marais', 'MI', 'Cartoonist William Donahey received this barrel-shaped cottage in the 1920s, inspired by the tiny barrel homes in his Teenie Weenies comic strip. The restored structure now operates seasonally as a museum and looks exactly like two giant wooden pickle barrels joined together.', 'limited', 'https://www.atlasobscura.com/places/pickle-barrel-house', null, 'America/Detroit', now()),
  ('Two-Story Outhouse', 'two-story-outhouse', 'roadside-oddities', 43.40332, -84.9746, 'Cedar Lake', 'MI', 'Cedar Lake''s famous double-decker privy traces back to an 1875 home and store whose upper floor was once connected to the outhouse by a walkway. The surviving structure is a reconstructed/restored version of the historic oddity and sits on private property, so visitors should view it from the roadside rather than attempting to use or enter it.', 'roadside', 'https://www.atlasobscura.com/places/two-story-outhouse-cedar-lake', null, 'America/Detroit', now()),
  ('McCourtie Park Concrete Bridges', 'mccourtie-park-concrete-bridges', 'roadside-oddities', 42.0528, -84.4094, 'Somerset Center', 'MI', 'In the 1930s, Mexican artisans built a series of bridges and structures from sculpted concrete carefully shaped and painted to resemble logs, ropes and rustic woodwork. The surreal faux-timber bridges now form the centerpiece of a public park on the former McCourtie estate.', 'open', 'https://www.atlasobscura.com/places/mccourtie-park', null, 'America/Detroit', now()),
  ('Hell, Michigan', 'hell-michigan', 'roadside-oddities', 42.4331, -83.9842, 'Hell', 'MI', 'The tiny community of Hell has fully embraced its name with the Gates of Hell, a tiny post office that singes mail, Damnation University diplomas, novelty mayor-for-a-day appointments and appropriately infernal souvenirs. Screams Souvenirs serves as the easiest routable center of the attraction.', 'open', 'https://www.gotohellmi.com/', 'https://www.gotohellmi.com/', 'America/Detroit', now()),
  ('Bath School Disaster Memorial', 'bath-school-disaster-memorial', 'weird-history', 42.8164, -84.44929, 'Bath', 'MI', 'On May 18, 1927, school-board member Andrew Kehoe used explosives to destroy part of Bath Consolidated School before detonating his truck outside, in an attack that killed 45 people including Kehoe. James Couzens Memorial Park preserves the school''s cupola, a historical marker and the Girl with a Cat memorial dedicated after the disaster.', 'open', 'https://www2.dnr.state.mi.us/publications/pdfs/ArcGISOnline/StoryMaps/mhc_historical_markers/pdfs/MHC191991013.pdf', null, 'America/Detroit', now()),
  ('Great Wallace Shows Circus Train-Wreck Memorial', 'great-wallace-shows-circus-train-wreck-memorial', 'weird-history', 42.88123, -83.99195, 'Durand', 'MI', 'A 1903 collision involving the Great Wallace Shows circus train killed performers, workers and animals near Durand. Several unidentified victims were buried together in Lovejoy Cemetery, where a memorial preserves the story of one of America''s deadliest circus-train disasters.', 'open', 'https://www.atlasobscura.com/places/great-wallace-shows-circus-train-wreck-memorial', null, 'America/Detroit', now()),
  ('S.S. City of Milwaukee', 'ss-city-of-milwaukee', 'museums', 44.2594, -86.31496, 'Manistee', 'MI', 'Built in 1930, the City of Milwaukee carried railroad cars across Lake Michigan before being preserved as a museum ship. Guided tours pass through the working spaces and steep stairways of the old car ferry; the 2026 regular tour season ended August 30, so fall access should be checked before routing here.', 'limited', 'https://www.carferry.com/tours', 'https://www.carferry.com/', 'America/Detroit', now()),
  ('Seul Choix Pointe Lighthouse', 'seul-choix-pointe-lighthouse', 'haunted', 45.92135, -85.91226, 'Gulliver', 'MI', 'This isolated Lake Michigan light station has become one of the Upper Peninsula''s better-known haunted lighthouse destinations, with stories of apparitions, voices and unexplained movement inside the keeper''s buildings. The Gulliver Historical Society operates the restored museum and tower, while special haunted tours lean directly into the site''s paranormal reputation.', 'limited', 'https://www.greatlakelighthouse.com/', 'https://www.greatlakelighthouse.com/', 'America/Detroit', now()),
  ('Museum Ship Valley Camp', 'museum-ship-valley-camp', 'museums', 46.49944, -84.335, 'Sault Ste. Marie', 'MI', 'A 550-foot Great Lakes freighter launched in 1917 now serves as a floating museum beside the St. Marys River. Among its many maritime exhibits are two lifeboats recovered from the wreckage of the Edmund Fitzgerald, making the ship especially significant to Great Lakes disaster history.', 'limited', 'https://www.saulthistoricsites.com/museum-ship-valley-camp/', null, 'America/Detroit', now()),
  ('Tower of History', 'tower-of-history', 'roadside-oddities', 46.49857, -84.34068, 'Sault Ste. Marie', 'MI', 'This stark 210-foot tower was built by the Catholic Church in 1968 as part of a proposed religious complex before becoming a public museum and observation tower. Its high viewing decks overlook the Soo Locks and passing freighters, while the unusual concrete structure dominates the city''s otherwise low skyline.', 'limited', 'https://www.atlasobscura.com/places/tower-of-history-2', null, 'America/Detroit', now()),
  ('The Antlers Restaurant', 'the-antlers-restaurant', 'roadside-oddities', 46.49446, -84.32919, 'Sault Ste. Marie', 'MI', 'More than 200 animal mounts crowd the walls and ceiling of this long-running restaurant near the Soo Locks. The overwhelming collection of antlers, taxidermy and North Woods memorabilia makes eating here feel closer to dining inside an eccentric hunting museum.', 'open', 'https://www.michigan.org/property/antlers-restaurant', 'https://sooantlers.com/', 'America/Detroit', now()),
  ('Legs Inn', 'legs-inn', 'roadside-oddities', 45.64262, -85.03721, 'Cross Village', 'MI', 'Polish immigrant Stanley Smolak built this eccentric stone-and-timber restaurant with driftwood, local rock and handmade decorations, then lined the roof with upside-down cast-iron stove legs that gave the inn its name. The heavily decorated interior adds taxidermy, carved wood and folk-art details to the already unusual building.', 'limited', 'https://www.atlasobscura.com/places/legs-inn', 'https://www.legsinn.com/', 'America/Detroit', now()),
  ('Earl Young Mushroom Houses', 'earl-young-mushroom-houses', 'roadside-oddities', 45.31806, -85.2584, 'Charlevoix', 'MI', 'Self-taught builder Earl Young created a group of stone cottages with curved roofs, massive boulders and storybook proportions that have become known as Charlevoix''s Mushroom Houses. Most are private residences, so travelers should view them respectfully from public streets or use an authorized walking tour rather than entering yards.', 'private', 'https://www.atlasobscura.com/places/earl-young-gnome-homes', 'https://visitcharlevoix.com/earl-young-mushroom-houses/', 'America/Detroit', now()),
  ('Castle Farms', 'castle-farms', 'roadside-oddities', 45.28052, -85.2302, 'Charlevoix', 'MI', 'Sears executive Albert Loeb built this sprawling Norman-style complex in 1918 as a model farm, creating an improbable stone castle amid northern Michigan farmland. After decades of changing uses, the restored property now offers tours and events that let visitors legally explore the towers, courtyards and collections.', 'limited', 'https://castlefarms.com/', 'https://castlefarms.com/', 'America/Detroit', now()),
  ('Packard Proving Grounds', 'packard-proving-grounds', 'weird-history', 42.66139, -83.03422, 'Shelby Township', 'MI', 'Packard opened this engineering complex in 1928 to test cars at high speeds on its track and through specialized durability courses. Surviving garages, gatehouses and portions of the test facility are now preserved by a nonprofit and can be explored during scheduled tours and public events.', 'limited', 'https://packardprovinggrounds.org/', 'https://packardprovinggrounds.org/', 'America/Detroit', now()),
  ('Curwood Castle', 'curwood-castle', 'museums', 42.99944, -84.17528, 'Owosso', 'MI', 'Adventure novelist James Oliver Curwood built this miniature French-style castle in 1922 as his private writing studio beside the Shiawassee River. The fanciful stone building is now a museum containing Curwood artifacts and feels far more like a storybook fortress than an author''s office.', 'limited', 'https://www.atlasobscura.com/places/curwood-castle', null, 'America/Detroit', now()),
  ('Castle Museum of Saginaw County History', 'castle-museum-of-saginaw-county-history', 'museums', 43.43095, -83.93552, 'Saginaw', 'MI', 'Saginaw''s history museum occupies a spectacular 1898 federal building deliberately designed to resemble a French château. Behind the turrets and stone walls are local-history exhibits and remnants of its former postal role, making the architecture alone worth the OddWay stop.', 'open', 'https://www.castlemuseum.org/', 'https://www.castlemuseum.org/', 'America/Detroit', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  timezone      = excluded.timezone,
  verified_at   = excluded.verified_at;

select count(*) as michigan from public.stops where state = 'MI';
