-- MO: 125 researched stops.
--
-- 121 new, 4 updating a row already in the index.
-- After running this and scripts/refresh-site.mts, /explore should read
-- 6788.
--
-- Coordinates are deliberately NOT updated on conflict: a checked position
-- must never be replaced by an unchecked one. Where the existing row came
-- from the OpenStreetMap scan and is wrong by a kilometre, delete that slug
-- first and let this insert instead.
--
-- state is deliberately NOT updated either. That is how an overwritten stop
-- in another state keeps its old state and hides — so the collision check
-- above refuses rather than relying on anyone noticing afterwards.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone)
values
  ('Missouri State Penitentiary Tours', 'missouri-state-penitentiary-tours', 'weird-history', 38.5735, -92.1607, 'Jefferson City', 'MO', 'Opened in 1836 and closed in 2004, the Missouri State Penitentiary preserves cell blocks, yards and the former gas chamber from one of the country''s oldest major prisons west of the Mississippi. Scheduled history tours and paranormal investigations make the enormous complex a particularly strong OddWay stop.', 'limited', 'https://missouripentours.com/', 'America/Chicago'),
  ('Missouri State Penitentiary Museum', 'missouri-state-penitentiary-museum', 'weird-history', 38.57204, -92.16358, 'Jefferson City', 'MO', 'This museum complements the nearby prison complex with photographs, artifacts, inmate-made objects and displays interpreting daily life inside the Missouri State Penitentiary. It gives travelers a lower-intensity way to explore the prison''s history before or after a scheduled tour.', 'limited', 'https://missouripentours.com/museum/', 'America/Chicago'),
  ('Lemp Mansion', 'lemp-mansion', 'haunted', 38.59317, -90.21581, 'St. Louis', 'MO', 'The mansion of St. Louis''s once-powerful Lemp brewing family is tied to a series of deaths and suicides that helped create one of the city''s best-known haunted-house legends. The restored property operates as an inn and event venue and periodically offers ghost-focused experiences.', 'limited', 'https://www.lempmansion.com/', 'America/Chicago'),
  ('Pythian Castle', 'pythian-castle', 'haunted', 37.22143, -93.26868, 'Springfield', 'MO', 'Built in the early twentieth century for the Knights of Pythias and later used by the U.S. military, this fortress-like building has accumulated prison, military and paranormal lore. Public access is through scheduled tours, events and selected paranormal programs rather than unrestricted walk-in exploration.', 'limited', 'https://www.pythiancastle.com/', 'America/Chicago'),
  ('The Elms Hotel & Spa Paranormal Tour', 'the-elms-hotel-spa-paranormal-tour', 'haunted', 39.33686, -94.226, 'Excelsior Springs', 'MO', 'The historic Elms has survived fires, Prohibition-era intrigue and decades as a mineral-water resort, giving the hotel a deep supply of stories about unusual activity. The property has offered scheduled paranormal tours that explore its darker legends and hidden spaces.', 'limited', 'https://www.hyatt.com/destination-by-hyatt/en-US/mkcdc-the-elms-hotel-and-spa', 'America/Chicago'),
  ('Beattie Mansion', 'beattie-mansion', 'haunted', 39.775, -94.8598, 'St. Joseph', 'MO', 'This 1850s mansion is one of St. Joseph''s best-known paranormal investigation locations. The privately operated property offers scheduled tours and extended investigations, so OddWay travelers should reserve rather than simply arriving and entering.', 'limited', 'https://www.thebeattiemansion.com/', 'America/Chicago'),
  ('Vaile Victorian Mansion', 'vaile-victorian-mansion', 'weird-history', 39.10758, -94.41713, 'Independence', 'MO', 'Built in 1881, the ornate Second Empire mansion contains elaborate interiors, unusual architectural details and stories surrounding the Vaile family. Seasonal tours make it a strong combination of Gilded Age excess, local tragedy and Victorian atmosphere.', 'limited', 'https://vailemansion.org/', 'America/Chicago'),
  ('Glore Psychiatric Museum', 'glore-psychiatric-museum', 'weird-history', 39.77639, -94.80839, 'St. Joseph', 'MO', 'Housed in a former state hospital building, the Glore traces the history of psychiatric treatment through reconstructed devices, patient art, medical equipment and institutional artifacts. Its displays range from early treatment methods to more modern mental-health history and are unusually specific rather than generic museum material.', 'limited', 'https://www.stjosephmuseum.org/glore-psychiatric-museum', 'America/Chicago'),
  ('Haunted Castle House', 'haunted-castle-house', 'haunted', 38.09046, -92.48272, 'Brumley', 'MO', 'The turreted Castle House has been used as a residence and medical property and is promoted around its long-running paranormal reputation. Tours and investigations are reservation-based, so it should be treated as a scheduled private attraction rather than a walk-up abandoned site.', 'limited', 'https://hauntedcastlehouse.com/', 'America/Chicago'),
  ('Emmaus Asylum', 'emmaus-asylum', 'haunted', 38.6438, -90.99267, 'Marthasville', 'MO', 'This historic property is operated as a dedicated paranormal investigation venue with overnight and scheduled access. The site gives OddWay a legitimate routeable haunted-location stop without encouraging entry into an abandoned or unauthorized structure.', 'limited', 'https://www.emmausasylum.com/', 'America/Chicago'),
  ('Ozark Spooklight', 'ozark-spooklight', 'folklore', 37.08445, -94.51345, 'Joplin', 'MO', 'The Ozark or Hornet Spooklight is a long-running borderland legend involving a mysterious light reported along rural roads southwest of Joplin. Modern explanations point toward distant vehicle headlights, but the story remains one of Missouri''s classic supernatural roadside traditions; stay on public roads and never enter adjacent private fields.', 'roadside', 'https://www.atlasobscura.com/places/ozark-spooklight', 'America/Chicago'),
  ('Jim the Wonder Dog Memorial Garden', 'jim-the-wonder-dog-memorial-garden', 'folklore', 39.12157, -93.19733, 'Marshall', 'MO', 'Jim was a Llewellin setter celebrated in the 1930s for apparently understanding complex spoken commands, predicting events and identifying objects he had not been trained to recognize. A public memorial garden in downtown Marshall preserves the story of the dog whose abilities became local legend.', 'open', 'http://www.jimthewonderdog.org/', 'America/Chicago'),
  ('Jesse James Home Museum', 'jesse-james-home-museum', 'weird-history', 39.7558, -94.8451, 'St. Joseph', 'MO', 'Jesse James was shot and killed in this St. Joseph house in 1882 by Robert Ford. The preserved home contains artifacts and interpretation focused on James''s final days, making it one of Missouri''s most concrete locations tied to the outlaw''s life and death.', 'limited', 'https://stjosephmuseum.org/jesse-james-home/', 'America/Chicago'),
  ('Jesse James Birthplace & Farm Museum', 'jesse-james-birthplace-farm-museum', 'weird-history', 39.39222, -94.32052, 'Kearney', 'MO', 'The James family farm preserves the birthplace and childhood setting of outlaw Jesse James. Museum exhibits and the historic house place the famous robbery stories within the larger history of the James family, slavery, guerrilla warfare and post-Civil War Missouri.', 'limited', 'https://jessejamesmuseum.org/', 'America/Chicago'),
  ('Jesse James Bank Museum', 'jesse-james-bank-museum', 'weird-history', 39.24697, -94.41926, 'Liberty', 'MO', 'The former Clay County Savings Association building was the target of an 1866 daylight robbery often associated with the James-Younger gang, although the exact identities of the robbers remain debated. The museum preserves the bank interior and the story of one of the earliest major postwar outlaw raids.', 'limited', 'https://jessejamesmuseum.org/jesse-james-bank-museum/', 'America/Chicago'),
  ('Jesse James Grave', 'jesse-james-grave', 'weird-history', 39.36747, -94.36426, 'Kearney', 'MO', 'Jesse James''s remains were ultimately reinterred in Mount Olivet Cemetery beneath a family marker after first being buried at the James farm. The grave is a routeable endpoint to the outlaw''s story and should be visited respectfully during lawful cemetery hours.', 'limited', 'https://www.atlasobscura.com/places/jesse-james-grave', 'America/Chicago'),
  ('Odd Fellows Home / Belvoir Winery', 'odd-fellows-home-belvoir-winery', 'haunted', 39.22581, -94.40661, 'Liberty', 'MO', 'The former Odd Fellows complex included an orphanage, hospital, nursing home and cemetery, creating a large institutional landscape with a substantial paranormal reputation. The property is privately operated; public access is limited to business hours, events and authorized ghost tours rather than entry into closed buildings.', 'limited', 'https://www.atlasobscura.com/places/odd-fellows-home', 'America/Chicago'),
  ('Lemp Family Tomb', 'lemp-family-tomb', 'weird-history', 38.68973, -90.22461, 'St. Louis', 'MO', 'The Lemp family mausoleum in Bellefontaine Cemetery holds members of the brewing dynasty whose tragedies helped fuel the haunted reputation of the Lemp Mansion. It is a useful companion stop to the mansion and can be visited respectfully under cemetery rules.', 'limited', 'https://www.atlasobscura.com/places/the-lemp-family-tomb', 'America/Chicago'),
  ('Old St. Ferdinand Shrine', 'old-st-ferdinand-shrine', 'weird-history', 38.79639, -90.33389, 'Florissant', 'MO', 'This historic Catholic complex preserves an 1819 convent, 1821 church and other early buildings connected with St. Rose Philippine Duchesne. Religious artifacts, frontier history and the unusually old surviving structures make it a distinctive stop in suburban St. Louis.', 'limited', 'http://www.oldstferdinandshrine.com/', 'America/Chicago'),
  ('Queen Tombstone', 'queen-tombstone', 'weird-history', 36.94011, -89.35138, 'Charleston', 'MO', 'A striking grave marker in the Charleston area depicts a crowned woman and has generated local curiosity far beyond an ordinary headstone. The stop is valuable as cemetery folk art, but visitors should stay on established paths and treat the burial ground respectfully.', 'limited', 'https://www.atlasobscura.com/places/grave-of-the-queen', 'America/Chicago'),
  ('Grave of David Rice Atchison', 'grave-of-david-rice-atchison', 'weird-history', 39.55818, -94.44455, 'Plattsburg', 'MO', 'Senator David Rice Atchison is buried beneath a monument that repeats the long-running claim that he was ''president for one day'' during the 1849 presidential transition. Historians do not regard him as an actual U.S. president, but the story remains one of Missouri''s most durable political-history oddities.', 'limited', 'https://www.atlasobscura.com/places/david-rice-atchison-grave', 'America/Chicago'),
  ('Far West Temple Site', 'far-west-temple-site', 'weird-history', 39.6716, -94.1307, 'Kingston', 'MO', 'Far West was an important Latter-day Saint settlement in the 1830s before conflict forced its residents from the area. Cornerstones from the planned temple remain on the preserved site, creating a quiet but highly specific religious-history stop.', 'open', 'https://history.churchofjesuschrist.org/subsection/historic-sites/missouri/far-west?lang=eng', 'America/Chicago'),
  ('Burial Place of Chief Pontiac', 'burial-place-of-chief-pontiac', 'weird-history', 38.62456, -90.19037, 'St. Louis', 'MO', 'A plaque near the former colonial village area marks the traditional St. Louis burial place of Odawa leader Pontiac, who was killed in 1769. The exact burial history is not perfectly documented, but the marker anchors an important and often-overlooked part of regional Native and colonial history.', 'roadside', 'https://www.atlasobscura.com/places/burial-place-of-chief-pontiac', 'America/Chicago'),
  ('Marconnott Mausoleum / Mount Olive Mummy', 'marconnott-mausoleum-mount-olive-mummy', 'weird-history', 38.53439, -90.29188, 'St. Louis', 'MO', 'The Marconnott mausoleum became locally famous because a naturally mummified body was once visible through a glass panel. The coffin is no longer displayed for public viewing, but the mausoleum and story remain part of Mount Olive Cemetery''s unusual history; visit respectfully.', 'limited', 'https://www.atlasobscura.com/places/mount-olive-mummy', 'America/Chicago'),
  ('Meramec Caverns', 'meramec-caverns', 'roadside-oddities', 38.24155, -91.09224, 'Stanton', 'MO', 'Meramec Caverns is a large commercial cave system beneath the Ozark hills that has drawn Route 66 travelers for generations. Guided tours pass through extensive limestone rooms and formations, with the attraction also trading heavily on regional Jesse James lore.', 'limited', 'https://www.americascave.com/', 'America/Chicago'),
  ('Fantastic Caverns', 'fantastic-caverns', 'roadside-oddities', 37.288, -93.35962, 'Springfield', 'MO', 'Fantastic Caverns is toured in passenger vehicles rather than on foot, making it one of the few ride-through show caves in the United States. Visitors travel through large passages filled with flowstone, columns and other formations on scheduled guided tours.', 'limited', 'https://fantasticcaverns.com/', 'America/Chicago'),
  ('Mark Twain Cave', 'mark-twain-cave', 'roadside-oddities', 39.68875, -91.33166, 'Hannibal', 'MO', 'Known to Samuel Clemens as a boy and later woven into The Adventures of Tom Sawyer, Mark Twain Cave is Missouri''s oldest continuously operating show cave. Guided tours explore its maze-like passages while connecting the geology directly to Hannibal''s literary history.', 'limited', 'https://www.marktwaincave.com/', 'America/Chicago'),
  ('Cameron Cave', 'cameron-cave', 'roadside-oddities', 39.68851, -91.33175, 'Hannibal', 'MO', 'Cameron Cave is the less-developed companion to Mark Twain Cave and is toured by lantern rather than permanent electric lighting. Its narrow maze-like passages provide a noticeably different experience from the neighboring commercial tour route.', 'limited', 'https://www.marktwaincave.com/', 'America/Chicago'),
  ('Onondaga Cave', 'onondaga-cave', 'roadside-oddities', 38.0612, -91.22718, 'Leasburg', 'MO', 'Onondaga Cave contains a dense concentration of stalactites, stalagmites, flowstone and large rooms beneath its namesake state park. Missouri State Parks offers scheduled guided tours during the 2026 cave season.', 'limited', 'https://mostateparks.com/key-location/onondaga-cave', 'America/Chicago'),
  ('Cathedral Cave', 'cathedral-cave', 'roadside-oddities', 38.05644, -91.24099, 'Leasburg', 'MO', 'Cathedral Cave is a separate cave system inside Onondaga Cave State Park, reached on a more limited guided-tour schedule. The route includes undeveloped passages and the large formation known as the Cathedral Bell.', 'limited', 'https://mostateparks.com/page/onondaga-cave-state-park/cathedral-cave', 'America/Chicago'),
  ('Fisher Cave', 'fisher-cave', 'roadside-oddities', 38.22731, -91.0843, 'Sullivan', 'MO', 'Fisher Cave lies beneath Meramec State Park and is opened for naturalist-led tours during the park''s cave season. The tour follows an active cave environment with streams, wildlife and varied limestone formations rather than a heavily commercialized interior.', 'limited', 'https://mostateparks.com/page/meramec-state-park/fisher-cave', 'America/Chicago'),
  ('Ozark Caverns', 'ozark-caverns', 'roadside-oddities', 38.05459, -92.58354, 'Kaiser', 'MO', 'Ozark Caverns is an undeveloped cave at Lake of the Ozarks State Park where tours rely on hand-held lanterns instead of installed electric lighting. Angel Showers, a formation created by water falling from the cave ceiling, is one of its signature features.', 'limited', 'https://mostateparks.com/page/lake-ozarks-state-park/ozark-caverns', 'America/Chicago'),
  ('Bridal Cave', 'bridal-cave', 'roadside-oddities', 38.02353, -92.79193, 'Camdenton', 'MO', 'Bridal Cave is a long-running Lake of the Ozarks show cave known for dramatic formations and an underground chapel where weddings are performed. Guided tours make it an easy routeable cave stop rather than an adventure-caving location.', 'limited', 'https://bridalcave.com/', 'America/Chicago'),
  ('Jacob''s Cave', 'jacobs-cave', 'roadside-oddities', 38.33529, -92.83582, 'Versailles', 'MO', 'Jacob''s Cave offers guided walking tours through a large Ozark cavern filled with reflective pools, columns and other formations. The cave has operated as a tourist attraction for decades and remains a dependable central-Missouri subterranean stop.', 'limited', 'http://www.jacobscave.com/', 'America/Chicago'),
  ('Talking Rocks Cavern', 'talking-rocks-cavern', 'roadside-oddities', 36.67727, -93.37743, 'Branson West', 'MO', 'Talking Rocks Cavern descends through a tightly packed collection of cave formations near Branson West. Guided tours use stairs and walkways to reach richly decorated rooms that feel very different from Missouri''s larger horizontal cave systems.', 'limited', 'https://talkingrockscavern.com/', 'America/Chicago'),
  ('Smallin Civil War Cave', 'smallin-civil-war-cave', 'roadside-oddities', 37.05123, -93.18681, 'Ozark', 'MO', 'Smallin Cave has a massive entrance and a human history tied to Native use, settlement and Civil War-era stories. Guided tours combine geology with regional history, and seasonal lantern programs go deeper into the cave''s folklore.', 'limited', 'https://smallincave.com/', 'America/Chicago'),
  ('Bluff Dwellers Cave', 'bluff-dwellers-cave', 'roadside-oddities', 36.51883, -94.48699, 'Noel', 'MO', 'Discovered in the 1920s and opened as a show cave soon afterward, Bluff Dwellers Cave preserves extensive speleothems and archaeological context from the Ozarks. Guided tours operate from the privately run cave complex outside Noel.', 'limited', 'https://bluffdwellerscave.com/', 'America/Chicago'),
  ('Lost Canyon Cave & Nature Trail', 'lost-canyon-cave-nature-trail', 'roadside-oddities', 36.53713, -93.24746, 'Ridgedale', 'MO', 'Lost Canyon is explored by self-driven golf cart along a constructed nature trail that passes waterfalls, rock formations and a cave containing an underground bar. It is highly developed, but the unusual cave-drive format earns it a place in the OddWay database.', 'limited', 'https://topoftherock.com/top-of-the-rock/', 'America/Chicago'),
  ('Marvel Cave', 'marvel-cave', 'roadside-oddities', 36.66708, -93.33842, 'Branson', 'MO', 'Marvel Cave was the original attraction around which Silver Dollar City developed and contains one of the largest cave entrance rooms in North America. Theme-park admission includes scheduled cave tours that descend hundreds of feet below the surface before returning visitors by cable train.', 'limited', 'https://www.silverdollarcity.com/theme-park/attractions/rides/marvel-cave/', 'America/Chicago'),
  ('Devil''s Icebox Entrance', 'devils-icebox-entrance', 'roadside-oddities', 38.87089, -92.32663, 'Columbia', 'MO', 'A boardwalk in Rock Bridge Memorial State Park leads to the dramatic sinkhole and cave entrance known as the Devil''s Icebox. Wild-cave tours are suspended, so OddWay should route visitors only to the lawful surface trail and entrance-viewing area.', 'open', 'https://mostateparks.com/key-location/devils-icebox-entrance', 'America/Chicago'),
  ('Ha Ha Tonka Castle Ruins', 'ha-ha-tonka-castle-ruins', 'weird-history', 37.97608, -92.76985, 'Camdenton', 'MO', 'The stone ruins of an early twentieth-century mansion crown a bluff above the Lake of the Ozarks after the building was destroyed by fire in 1942. Public trails and overlooks let travelers explore the stabilized exterior ruins without trespassing.', 'open', 'https://mostateparks.com/key-location/castle-ruins', 'America/Chicago'),
  ('Ha Ha Tonka Natural Bridge', 'ha-ha-tonka-natural-bridge', 'roadside-oddities', 37.97446, -92.76325, 'Camdenton', 'MO', 'This massive natural limestone bridge is one of several karst features concentrated inside Ha Ha Tonka State Park. A maintained trail reaches the arch and makes it an easy addition to the nearby castle ruins and spring.', 'open', 'https://mostateparks.com/park/ha-ha-tonka-state-park', 'America/Chicago'),
  ('Ha Ha Tonka Colosseum', 'ha-ha-tonka-colosseum', 'roadside-oddities', 37.97482, -92.76312, 'Camdenton', 'MO', 'The Colosseum is a huge collapsed sinkhole, roughly 150 feet deep, created by the same karst processes that shaped Ha Ha Tonka''s caves and natural bridge. The feature is reached from a signed state-park trail rather than by entering the collapse itself.', 'open', 'https://mostateparks.com/park/ha-ha-tonka-state-park', 'America/Chicago'),
  ('Ha Ha Tonka Spring', 'ha-ha-tonka-spring', 'roadside-oddities', 37.97388, -92.7672, 'Camdenton', 'MO', 'A large blue spring emerges at the base of the Ha Ha Tonka bluffs and feeds a clear stream toward the lake. Boardwalks and trails connect the spring with the park''s other geological features and historic ruins.', 'open', 'https://mostateparks.com/park/ha-ha-tonka-state-park', 'America/Chicago'),
  ('Elephant Rocks State Park', 'elephant-rocks-state-park', 'roadside-oddities', 37.65179, -90.6898, 'Belleview', 'MO', 'Enormous rounded granite boulders stand in rows and clusters that resemble a train of circus elephants. A paved loop trail threads among the 1.5-billion-year-old rocks and past traces of the area''s quarrying history.', 'open', 'https://mostateparks.com/park/elephant-rocks-state-park', 'America/Chicago'),
  ('Engine House Ruin', 'engine-house-ruin', 'weird-history', 37.65586, -90.68472, 'Graniteville', 'MO', 'Stone walls from a nineteenth-century railroad engine house survive among the granite landscape near Elephant Rocks. The ruin is a compact industrial-history counterpart to the park''s better-known natural formations.', 'open', 'https://mostateparks.com/key-location/engine-house-ruins', 'America/Chicago'),
  ('Johnson''s Shut-Ins', 'johnsons-shut-ins', 'roadside-oddities', 37.53913, -90.83806, 'Middle Brook', 'MO', 'The East Fork of the Black River is squeezed through resistant volcanic rock here, creating chutes, potholes and cascades known as shut-ins. Designated public access makes this one of Missouri''s most dramatic routeable geological stops.', 'open', 'https://mostateparks.com/park/johnsons-shut-ins-state-park', 'America/Chicago'),
  ('Taum Sauk Mountain High Point', 'taum-sauk-mountain-high-point', 'roadside-oddities', 37.57119, -90.72932, 'Ironton', 'MO', 'A short trail leads to the highest natural point in Missouri at Taum Sauk Mountain. The high point itself is subtle, but the surrounding St. Francois Mountains are among the oldest exposed mountain rocks in North America.', 'open', 'https://mostateparks.com/key-location/high-point', 'America/Chicago'),
  ('Mina Sauk Falls', 'mina-sauk-falls', 'roadside-oddities', 37.5625, -90.74086, 'Ironton', 'MO', 'Mina Sauk Falls drops in a series of cascades down Taum Sauk Mountain and is generally considered Missouri''s tallest waterfall. Its flow is seasonal, so the rugged trail is most rewarding after wet weather.', 'open', 'https://mostateparks.com/park/taum-sauk-mountain-state-park', 'America/Chicago'),
  ('The Pinnacles', 'the-pinnacles', 'roadside-oddities', 39.13476, -92.32347, 'Sturgeon', 'MO', 'A narrow limestone ridge rises sharply between two creeks at this Boone County park, creating fins, cracks and elevated scrambling routes unusual for central Missouri. Visitors should stay on established public access and use caution on exposed rock.', 'open', 'https://www.atlasobscura.com/places/the-pinnacles', 'America/Chicago'),
  ('Bennett Spring Natural Tunnel', 'bennett-spring-natural-tunnel', 'roadside-oddities', 37.70383, -92.84013, 'Lebanon', 'MO', 'A natural rock tunnel along a Bennett Spring State Park trail creates a compact cave-like passage through the Ozark limestone. It is a good surface-geology stop for travelers who do not want a scheduled commercial cave tour.', 'open', 'https://www.atlasobscura.com/places/bennett-spring-natural-tunnel', 'America/Chicago'),
  ('Devil''s Honeycomb', 'devils-honeycomb', 'roadside-oddities', 37.81069, -90.71542, 'Ste. Genevieve', 'MO', 'Wind, water and erosion have carved a sandstone wall into a honeycomb of cavities along a trail in the Hawn State Park area. The texture is striking at close range and fits OddWay''s preference for routeable natural features with a clear physical object to find.', 'open', 'https://www.atlasobscura.com/places/devils-honeycomb', 'America/Chicago'),
  ('Portuguese Point', 'portuguese-point', 'roadside-oddities', 37.90726, -92.09794, 'Montreal', 'MO', 'Portuguese Point is an exposed Ozark overlook with dramatic rock shelves above the surrounding river-and-lake country. Its unusual name and rugged stone viewpoint make it a worthwhile short geological detour when conditions are safe.', 'open', 'https://www.atlasobscura.com/places/portuguese-point', 'America/Chicago'),
  ('Greer Spring', 'greer-spring', 'roadside-oddities', 36.78661, -91.34753, 'Alton', 'MO', 'Greer Spring is one of the largest springs in the Ozarks, releasing an enormous volume of clear water that quickly forms a substantial stream. A roughly one-mile trail descends from the public parking area to the spring branch.', 'open', 'https://mdc.mo.gov/discover-nature/places/greer-spring', 'America/Chicago'),
  ('Roaring River Spring', 'roaring-river-spring', 'roadside-oddities', 36.59131, -93.83241, 'Cassville', 'MO', 'A deep blue spring emerges from a cavernous opening beneath a cliff and forms the headwaters of Roaring River. The spring is immediately accessible inside the state park and pairs natural geology with the park''s historic trout-hatchery landscape.', 'open', 'https://mostateparks.com/park/roaring-river-state-park', 'America/Chicago'),
  ('Montauk Springs', 'montauk-springs', 'roadside-oddities', 37.46032, -91.6832, 'Salem', 'MO', 'Multiple large springs rise inside Montauk State Park and combine to form the headwaters of the Current River. Trails and historic mill features make the spring area a strong natural-history stop rather than simply a fishing destination.', 'open', 'https://mostateparks.com/park/montauk-state-park', 'America/Chicago'),
  ('Alley Spring & Mill', 'alley-spring-mill', 'roadside-oddities', 37.15394, -91.4443, 'Eminence', 'MO', 'A vivid blue spring flows beside the red Alley Mill, one of the most recognizable historic structures in the Ozark National Scenic Riverways. The combination of karst hydrology and preserved milling machinery makes this a high-value OddWay stop.', 'open', 'https://www.nps.gov/ozar/learn/historyculture/alley-mill.htm', 'America/Chicago'),
  ('Big Spring', 'big-spring', 'roadside-oddities', 36.95304, -90.9931, 'Van Buren', 'MO', 'Big Spring pours hundreds of millions of gallons of water into the Current River system and is among the largest springs in the United States. Public trails and overlooks allow travelers to see the immense blue-green discharge safely from the riverways park.', 'open', 'https://www.nps.gov/ozar/learn/nature/big-spring.htm', 'America/Chicago'),
  ('Blue Spring', 'blue-spring', 'roadside-oddities', 37.16687, -91.16437, 'Eminence', 'MO', 'Blue Spring is famous for its intense sapphire color and exceptional depth. A foot trail from the conservation-area access leads to the spring, which is protected from swimming and other disturbance.', 'open', 'https://mdc.mo.gov/discover-nature/places/blue-spring-natural-area', 'America/Chicago'),
  ('Welch Spring Hospital Ruins', 'welch-spring-hospital-ruins', 'weird-history', 37.39459, -91.57628, 'Akers', 'MO', 'Ruins of a stone hospital stand beside Welch Spring, where an early twentieth-century doctor promoted cave air as a treatment for respiratory illness. The failed medical venture left an unusually photogenic wall directly beside a major Ozark spring.', 'open', 'https://www.nps.gov/places/welch-spring.htm', 'America/Chicago'),
  ('Rocky Falls', 'rocky-falls', 'roadside-oddities', 37.0949, -91.21018, 'Eminence', 'MO', 'Rocky Falls spills over billion-year-old rhyolite in a broad stair-step cascade. The National Scenic Riverways site is reached by road and short foot access, making the unusual volcanic geology especially easy to visit.', 'open', 'https://www.nps.gov/places/rocky-falls.htm', 'America/Chicago'),
  ('Grand Gulf State Park', 'grand-gulf-state-park', 'roadside-oddities', 36.54415, -91.64499, 'Thayer', 'MO', 'Grand Gulf is a collapsed cave system often described as Missouri''s ''Little Grand Canyon.'' Visitors can view the deep chasm from rim trails and, when conditions allow, descend designated routes into portions of the natural feature.', 'open', 'https://mostateparks.com/park/grand-gulf-state-park', 'America/Chicago'),
  ('Graham Cave', 'graham-cave', 'weird-history', 38.90556, -91.57528, 'Danville', 'MO', 'Excavations at Graham Cave revealed evidence of human occupation stretching back thousands of years. A public trail leads to the broad sandstone shelter, while interpretation explains the archaeological importance of the site without encouraging disturbance.', 'open', 'https://mostateparks.com/park/graham-cave-state-park', 'America/Chicago'),
  ('Pickle Springs Natural Area', 'pickle-springs-natural-area', 'roadside-oddities', 37.8017, -90.3015, 'Ste. Genevieve', 'MO', 'Pickle Springs protects an extraordinary concentration of sandstone arches, slot-like passages, hoodoos and weathered rock forms. The Trail Through Time loops through the natural area and gives OddWay several strange formations within one routeable stop.', 'open', 'https://mdc.mo.gov/discover-nature/places/pickle-springs-natural-area', 'America/Chicago'),
  ('Castor River Shut-Ins', 'castor-river-shut-ins', 'roadside-oddities', 37.56882, -90.15506, 'Fredericktown', 'MO', 'The Castor River squeezes through Missouri''s only known pink-granite shut-ins, creating cascades over exposed 1.5-billion-year-old rock. Missouri Department of Conservation provides a public trailhead and a one-mile loop to the formation.', 'open', 'https://mdc.mo.gov/discover-nature/places/natural-areas/castor-river-shut-ins', 'America/Chicago'),
  ('Edward ''Ted'' and Pat Jones-Confluence Point', 'edward-ted-and-pat-jones-confluence-point', 'roadside-oddities', 38.81607, -90.11953, 'West Alton', 'MO', 'A short trail reaches the point where the Missouri River meets the Mississippi, allowing visitors to stand at one of the most consequential river junctions in North America. Seasonal flooding can affect access, so current state-park conditions should be checked before routing.', 'open', 'https://mostateparks.com/park/edward-ted-and-pat-jones-confluence-point-state-park', 'America/Chicago'),
  ('Wild Horses of Shannon County', 'wild-horses-of-shannon-county', 'folklore', 37.17214, -91.30052, 'Eminence', 'MO', 'Several small herds of free-roaming horses live on public lands around the Current and Jacks Fork rivers and have become a distinctive part of Shannon County folklore. Sightings are not guaranteed; travelers should observe from a distance and never feed, chase or block the horses.', 'open', 'https://www.nps.gov/ozar/learn/nature/wild-horses.htm', 'America/Chicago'),
  ('Round Spring', 'round-spring', 'roadside-oddities', 37.28255, -91.40764, 'Eminence', 'MO', 'Round Spring rises in a nearly circular blue basin and flows directly toward the Current River. The spring itself remains a valid public stop even though Round Spring Cave is closed for the 2026 season, so OddWay should route only to the spring area.', 'open', 'https://www.nps.gov/places/round-spring.htm', 'America/Chicago'),
  ('Klepzig Mill', 'klepzig-mill', 'roadside-oddities', 37.1265, -91.19852, 'Eminence', 'MO', 'Klepzig Mill is a small historic turbine mill beside Rocky Creek in the Ozark National Scenic Riverways. The remote structure, shut-ins and creek setting create a strong backroad OddWay stop, but access roads can be rough after bad weather.', 'open', 'https://www.nps.gov/places/klepzig-mill.htm', 'America/Chicago'),
  ('Hodgson Water Mill', 'hodgson-water-mill', 'roadside-oddities', 36.70971, -92.26641, 'Sycamore', 'MO', 'Hodgson Mill stands dramatically at the base of a bluff beside a powerful spring that once drove milling machinery. The privately owned building is best treated as a roadside exterior/photo stop unless current access information specifically permits more.', 'roadside', 'https://www.explorewestplains.com/hodgson-mill/', 'America/Chicago'),
  ('Jolly Mill', 'jolly-mill', 'roadside-oddities', 36.89596, -94.07028, 'Pierce City', 'MO', 'Jolly Mill survives from the vanished community of Jollification and has served at different times as a mill and distillery. The restored mill stands inside a public park with seasonal grinding demonstrations and an unusual local history tied to Civil War-era violence and Ozark folklore.', 'limited', 'https://www.atlasobscura.com/places/jolly-mill', 'America/Chicago'),
  ('Dillard Mill State Historic Site', 'dillard-mill-state-historic-site', 'roadside-oddities', 37.71774, -91.20683, 'Davisville', 'MO', 'The red Dillard Mill preserves early twentieth-century milling machinery beside Huzzah Creek in a remarkably intact rural setting. Guided access to the building is scheduled, while the surrounding historic-site grounds provide a scenic public stop.', 'limited', 'https://mostateparks.com/park/dillard-mill-state-historic-site', 'America/Chicago'),
  ('Bollinger Mill & Burfordville Covered Bridge', 'bollinger-mill-burfordville-covered-bridge', 'roadside-oddities', 37.3683, -89.80272, 'Burfordville', 'MO', 'A four-story brick gristmill stands directly beside Missouri''s oldest surviving covered bridge, creating one of the state''s best preserved transportation-and-industry pairings. The bridge is pedestrian-only and the mill interior is available through scheduled tours.', 'limited', 'https://mostateparks.com/park/bollinger-mill-state-historic-site', 'America/Chicago'),
  ('Locust Creek Covered Bridge', 'locust-creek-covered-bridge', 'weird-history', 39.79194, -93.23444, 'Laclede', 'MO', 'Built in 1868, Locust Creek Covered Bridge is one of only a handful of surviving covered bridges in Missouri. The preserved wooden structure no longer carries vehicles but remains open to pedestrians within the state historic site.', 'open', 'https://mostateparks.com/key-location/locust-creek-covered-bridge', 'America/Chicago'),
  ('Mastodon State Historic Site', 'mastodon-state-historic-site', 'weird-history', 38.37905, -90.38467, 'Imperial', 'MO', 'Archaeological work here linked Clovis stone tools with mastodon remains, providing important evidence that humans and mastodons overlapped in North America. The museum and trail system interpret both the Ice Age animals and the archaeological discoveries made at the site.', 'open', 'https://mostateparks.com/park/mastodon-state-historic-site', 'America/Chicago'),
  ('Thousand Hills State Park Petroglyphs', 'thousand-hills-state-park-petroglyphs', 'weird-history', 40.18866, -92.64074, 'Kirksville', 'MO', 'A protected shelter displays Native American petroglyphs carved into exposed rock as many as roughly 1,500 years ago. The site is open for self-guided viewing during park hours, and visitors must remain on the observation walkway.', 'open', 'https://mostateparks.com/key-location/petroglyph-siteshelter', 'America/Chicago'),
  ('Washington State Park Petroglyphs', 'washington-state-park-petroglyphs', 'weird-history', 38.08365, -90.6739, 'De Soto', 'MO', 'Washington State Park preserves the largest known concentration of petroglyphs in Missouri, associated with Mississippian-era ceremonial activity. Two protected viewing areas near the north entrance allow public access without walking on or touching the carvings.', 'open', 'https://mostateparks.com/page/washington-state-park/petroglyphs', 'America/Chicago'),
  ('Iliniwek Village State Historic Site', 'iliniwek-village-state-historic-site', 'weird-history', 40.42967, -91.55861, 'Wayland', 'MO', 'This state historic site preserves the location of a large Illinois Indian village recorded by French explorers in the seventeenth century. Trails and interpretation overlook the Mississippi floodplain while protecting the archaeological resources below ground.', 'open', 'https://mostateparks.com/park/iliniwek-village-state-historic-site', 'America/Chicago'),
  ('Osage Village State Historic Site', 'osage-village-state-historic-site', 'weird-history', 37.98128, -94.20664, 'Harwood', 'MO', 'The site preserves archaeological remains of a major Osage village occupied in the late eighteenth and early nineteenth centuries. A public trail and interpretive signs provide access while the village remains themselves stay protected beneath the ground.', 'open', 'https://mostateparks.com/park/osage-village-state-historic-site', 'America/Chicago'),
  ('Towosahgy State Historic Site', 'towosahgy-state-historic-site', 'weird-history', 36.69333, -89.23556, 'East Prairie', 'MO', 'Towosahgy preserves the earthworks and village area of a Mississippian mound-building community in Missouri''s Bootheel. The surviving mounds and plaza can be viewed from the public historic-site grounds without disturbing archaeological deposits.', 'open', 'https://mostateparks.com/park/towosahgy-state-historic-site', 'America/Chicago'),
  ('Battle of Island Mound State Historic Site', 'battle-of-island-mound-state-historic-site', 'weird-history', 38.23654, -94.43955, 'Butler', 'MO', 'This site commemorates an 1862 Civil War fight in which the 1st Kansas Colored Volunteer Infantry engaged Confederate guerrillas before Black soldiers were formally accepted into federal service nationwide. The landscape is preserved with trails, interpretation and memorial elements.', 'open', 'https://mostateparks.com/park/battle-island-mound-state-historic-site', 'America/Chicago'),
  ('Fort Davidson Ruins', 'fort-davidson-ruins', 'weird-history', 37.61982, -90.64003, 'Pilot Knob', 'MO', 'The earthen remains of Fort Davidson mark the center of the 1864 Battle of Pilot Knob, where Union defenders fought a much larger Confederate force before evacuating and destroying their powder magazine. The fort outline and crater remain visible on the public historic-site grounds.', 'open', 'https://mostateparks.com/key-location/fort-davidson-ruins', 'America/Chicago'),
  ('Missouri Mines State Historic Site', 'missouri-mines-state-historic-site', 'weird-history', 37.83778, -90.50861, 'Park Hills', 'MO', 'The former St. Joe Minerals mill complex preserves massive industrial buildings and machinery from Missouri''s lead-mining region. A museum inside the old powerhouse displays minerals, mining equipment and the history of an industry that reshaped the St. Francois Mountains.', 'limited', 'https://mostateparks.com/park/missouri-mines-state-historic-site', 'America/Chicago'),
  ('City Museum', 'city-museum', 'roadside-oddities', 38.633, -90.2001, 'St. Louis', 'MO', 'City Museum turns a former shoe factory into a maze of tunnels, salvaged architecture, giant slides, rooftop structures and outsider-art environments. It functions less like a conventional museum than a building-sized interactive sculpture assembled from pieces of the city itself.', 'limited', 'https://citymuseum.org/', 'America/Chicago'),
  ('Laclede''s Landing Wax Museum', 'lacledes-landing-wax-museum', 'museums', 38.63079, -90.18425, 'St. Louis', 'MO', 'This old-school wax museum packs historical figures, celebrities, horror characters and intentionally uncanny tableaux into a downtown St. Louis building. Its dated theatrical atmosphere is part of the appeal for travelers seeking something stranger than a polished modern attraction.', 'limited', 'https://stlwaxmuseum.com/', 'America/Chicago'),
  ('World Chess Hall of Fame & World''s Largest Chess Piece', 'world-chess-hall-of-fame-worlds-largest-chess-piece', 'museums', 38.6443, -90.26115, 'St. Louis', 'MO', 'The World Chess Hall of Fame combines rotating art and history exhibitions with a monumental Staunton king standing outside the building. The giant chess piece is Guinness-recognized and can be seen independently of the free museum galleries.', 'open', 'https://worldchesshof.org/plan-your-visit/', 'America/Chicago'),
  ('Miniature Museum of Greater St. Louis', 'miniature-museum-of-greater-st-louis', 'museums', 38.5815, -90.2665, 'St. Louis', 'MO', 'Room boxes, dollhouses and intricate miniature environments fill this specialized museum devoted entirely to tiny-scale craftsmanship. The obsessive level of detail makes it a strong OddWay collection stop rather than a general local-history museum.', 'limited', 'https://www.atlasobscura.com/places/miniature-museum-of-greater-st-louis', 'America/Chicago'),
  ('Kansas City Library Community Bookshelf', 'kansas-city-library-community-bookshelf', 'roadside-oddities', 39.1023, -94.5839, 'Kansas City', 'MO', 'The parking garage of the Kansas City Public Library is disguised behind a row of enormous book spines selected with community input. The oversized titles turn an otherwise utilitarian downtown structure into one of Missouri''s most recognizable pieces of literary street architecture.', 'roadside', 'https://kclibrary.org/community-bookshelf', 'America/Chicago'),
  ('National Museum of Toys and Miniatures', 'national-museum-of-toys-and-miniatures', 'museums', 39.0312, -94.5819, 'Kansas City', 'MO', 'This museum holds an enormous collection of historic toys alongside exceptionally detailed fine-scale miniatures. Mechanical toys, dollhouses and tiny decorative arts make the collection especially well suited to OddWay''s niche-museum category.', 'limited', 'https://toyandminiaturemuseum.org/', 'America/Chicago'),
  ('Arabia Steamboat Museum', 'arabia-steamboat-museum', 'weird-history', 39.1094, -94.5815, 'Kansas City', 'MO', 'The museum displays thousands of remarkably preserved objects recovered from the steamboat Arabia, which sank in the Missouri River in 1856 and was excavated from a field more than a century later. Everyday cargo survives in such quantity that the collection feels like a sealed nineteenth-century store brought back to life.', 'limited', 'https://www.1856.com/', 'America/Chicago'),
  ('Museum of Osteopathic Medicine', 'museum-of-osteopathic-medicine', 'weird-history', 40.19266, -92.58748, 'Kirksville', 'MO', 'Located at A.T. Still University, this museum documents the origins of osteopathic medicine in Kirksville through instruments, papers and unusual anatomical and medical displays. The collection also preserves buildings and artifacts associated with founder Andrew Taylor Still.', 'limited', 'https://www.atsu.edu/museum-of-osteopathic-medicine', 'America/Chicago'),
  ('National Cookie Cutter Historical Museum', 'national-cookie-cutter-historical-museum', 'museums', 37.08727, -94.54965, 'Joplin', 'MO', 'Thousands of cookie cutters document changing holidays, advertising, manufacturing and domestic life inside the Joplin History & Mineral Museum complex. It is one of those hyper-specific collections that fits OddWay better than a broad regional museum.', 'limited', 'https://www.joplinmo.org/550/Joplin-History-Mineral-Museum', 'America/Chicago'),
  ('Pigs Aloft Museum', 'pigs-aloft-museum', 'museums', 38.46639, -91.77147, 'Linn', 'MO', 'Where Pigs Fly Farm contains a huge collection of pig-related objects alongside a working rescue farm. The organization describes it as America''s only pig museum, making the property a deliberately eccentric collection stop with current weekend public hours.', 'limited', 'https://wherepigsflyfarm.com/', 'America/Chicago'),
  ('Missouri Meerschaum Corn Cob Pipe Museum', 'missouri-meerschaum-corn-cob-pipe-museum', 'roadside-oddities', 38.56174, -91.01377, 'Washington', 'MO', 'Missouri Meerschaum has manufactured corn-cob pipes in Washington since the nineteenth century. Its small museum and shop interpret the unusual local industry beside the still-active factory, while factory production areas themselves are not a public tour.', 'limited', 'https://corncobpipe.com/', 'America/Chicago'),
  ('Veterinary Museum of Missouri', 'veterinary-museum-of-missouri', 'weird-history', 38.58409, -92.21694, 'Jefferson City', 'MO', 'The Missouri Veterinary Medical Foundation preserves thousands of veterinary artifacts, including historic surgical tools, animal dentistry equipment, medicines and unusual specimens. It is the first U.S. museum dedicated solely to veterinary medicine and currently operates by posted weekday hours with appointments recommended.', 'limited', 'https://www.visitmo.com/things-to-do/missouri-veterinary-medical-foundation-museum', 'America/Chicago'),
  ('Ralph Foster Museum', 'ralph-foster-museum', 'museums', 36.61874, -93.24151, 'Point Lookout', 'MO', 'The College of the Ozarks museum contains a sprawling collection of Ozarks material, but its most unexpected object is the original modified automobile used by the Clampett family on The Beverly Hillbillies. Firearms, antiques, natural history and regional collections surround the pop-culture centerpiece.', 'limited', 'https://www.rfostermuseum.com/', 'America/Chicago'),
  ('Bonniebrook Home & Museum / Kewpie Museum', 'bonniebrook-home-museum-kewpie-museum', 'weird-history', 36.772, -93.22013, 'Walnut Shade', 'MO', 'Bonniebrook preserves the home landscape of illustrator Rose O''Neill, creator of the Kewpie characters. A reconstructed house, museum, grave site and artwork collection make the property a strange intersection of cartoon history, Ozark landscape and early twentieth-century art.', 'limited', 'https://roseoneill.org/', 'America/Chicago'),
  ('Walt Disney Hometown Museum', 'walt-disney-hometown-museum', 'museums', 39.71585, -92.94779, 'Marceline', 'MO', 'Housed in Marceline''s restored Santa Fe depot, the museum focuses on Walt Disney''s childhood connection to the town through family letters, photographs and personal artifacts. It also preserves material from the Midget Autopia attraction that Disney later donated to Marceline.', 'limited', 'https://www.waltdisneymuseum.org/', 'America/Chicago'),
  ('Nicholas-Beazley Aviation Museum', 'nicholas-beazley-aviation-museum', 'weird-history', 39.09823, -93.19692, 'Marshall', 'MO', 'This museum at the Marshall airport documents the locally based Nicholas-Beazley Airplane Company and its surprisingly ambitious early aircraft designs. Original aircraft, engines and cockpit displays make it a focused aviation-history stop with a strong Missouri connection.', 'limited', 'https://www.nicholasbeazley.org/', 'America/Chicago'),
  ('66 Drive-In Theatre', '66-drive-in-theatre', 'roadside-oddities', 37.17436, -94.36889, 'Carthage', 'MO', 'Opened in 1949 and restored in the 1990s, the 66 Drive-In preserves its original neon sign, screen and classic Route 66 setting. The theater operates seasonally, so travelers should check the current movie schedule rather than assuming a screening is available every night.', 'limited', 'https://www.nps.gov/places/66-drive-in.htm', 'America/Chicago'),
  ('Sliced Bread Innovation Center', 'sliced-bread-innovation-center', 'weird-history', 39.78795, -93.55152, 'Chillicothe', 'MO', 'The restored former Chillicothe Baking Company building celebrates the town where commercially machine-sliced bread was first sold in 1928. Exhibits turn an everyday supermarket item into a surprisingly specific piece of technological and advertising history.', 'limited', 'https://www.thehomeofslicedbread.com/', 'America/Chicago'),
  ('World''s Largest Spool of Thread', 'worlds-largest-spool-of-thread', 'roadside-oddities', 39.74491, -93.99494, 'Hamilton', 'MO', 'A 22-foot spool outside the Missouri Quilt Museum is wrapped with more than one million yards of thread. Visitors can photograph the oversized sewing landmark and, when museum programs permit, contribute additional thread to the ever-growing display.', 'roadside', 'https://www.missouriquiltmuseum.com/about-5', 'America/Chicago'),
  ('Precious Moments Chapel & Gardens', 'precious-moments-chapel-gardens', 'roadside-oddities', 37.11181, -94.3452, 'Carthage', 'MO', 'Artist Samuel J. Butcher transformed his famous teardrop-eyed Precious Moments characters into an elaborate chapel covered with murals, stained glass and monumental devotional scenes. The surrounding gardens and statues create a uniquely immersive branded religious-art environment.', 'limited', 'https://preciousmomentschapel.org/', 'America/Chicago'),
  ('Laumeier Sculpture Park', 'laumeier-sculpture-park', 'roadside-oddities', 38.55093, -90.4151, 'St. Louis', 'MO', 'More than 100 acres of woods and lawns hold large-scale contemporary sculptures, including monumental works that can be walked around and through. The free outdoor collection makes an easy OddWay cluster of strange objects rather than a single conventional gallery visit.', 'open', 'https://www.laumeiersculpturepark.org/', 'America/Chicago'),
  ('Eros Bendato', 'eros-bendato', 'roadside-oddities', 38.6265, -90.1933, 'St. Louis', 'MO', 'Igor Mitoraj''s enormous bandaged bronze head lies on its side in Citygarden, turning a fragment of classical-looking anatomy into a surreal downtown landmark. The sculpture is outdoors and can be viewed freely during public garden access.', 'open', 'https://www.citygardenstl.org/', 'America/Chicago'),
  ('Turtle Playground', 'turtle-playground', 'roadside-oddities', 38.6315, -90.2924, 'St. Louis', 'MO', 'A family of gigantic concrete turtles forms an outdoor playground near Forest Park, with shells large enough for visitors to climb and sit on. The sculptures were designed as both public art and functional play structures, making the site stranger than a standard city playground.', 'open', 'https://www.atlasobscura.com/places/turtle-playground', 'America/Chicago'),
  ('The Awakening II', 'the-awakening-ii', 'roadside-oddities', 38.64594, -90.59967, 'Chesterfield', 'MO', 'A 70-foot aluminum giant appears to claw his way out of the earth in Chesterfield Central Park, with separate hands, head, knee and foot emerging from the ground. The installation is a second casting of Seward Johnson''s famous The Awakening and is freely viewable in the park.', 'open', 'https://www.chesterfield.mo.us/the-awakening.html', 'America/Chicago'),
  ('Thomas Jefferson''s Original Tombstone', 'thomas-jeffersons-original-tombstone', 'weird-history', 38.94615, -92.3283, 'Columbia', 'MO', 'Thomas Jefferson''s original gravestone was given to the University of Missouri by his descendants in the nineteenth century and now stands on Francis Quadrangle. The odd relocation puts a major presidential funerary artifact hundreds of miles from Jefferson''s actual grave at Monticello.', 'open', 'https://www.atlasobscura.com/places/thomas-jeffersons-original-tombstone', 'America/Chicago'),
  ('1904 World''s Fair Flight Cage', '1904-worlds-fair-flight-cage', 'weird-history', 38.63667, -90.2922, 'St. Louis', 'MO', 'Built for the 1904 Louisiana Purchase Exposition, the enormous free-flight cage survived the fair and became a foundational exhibit of the St. Louis Zoo. The restored structure remains in active use, giving travelers a rare surviving piece of World''s Fair architecture that still serves its original purpose.', 'open', 'https://stlzoo.org/about/history', 'America/Chicago'),
  ('St. Louis Water Intake Towers', 'st-louis-water-intake-towers', 'roadside-oddities', 38.75849, -90.17684, 'St. Louis', 'MO', 'Two castle-like stone intake towers rise directly from the Mississippi River near the Old Chain of Rocks Bridge. They are no longer used for water collection and are not open for public entry, but they can be safely viewed from the pedestrian bridge.', 'roadside', 'https://www.stlouis-mo.gov/government/departments/planning/cultural-resources/preservation-plan/The-Victorian-City-Utilities-Structures.cfm', 'America/Chicago'),
  ('Whispering Arch at Union Station', 'whispering-arch-at-union-station', 'roadside-oddities', 38.62813, -90.20804, 'St. Louis', 'MO', 'A curved arch inside historic Union Station carries whispers from one side to the other, allowing two people standing far apart to hear each other clearly. The simple acoustic trick is hidden within one of the city''s grandest railroad-era interiors.', 'open', 'https://www.atlasobscura.com/places/whispering-arch-st-louis-union-station', 'America/Chicago'),
  ('Hall of Waters', 'hall-of-waters', 'weird-history', 39.34189, -94.22236, 'Excelsior Springs', 'MO', 'This monumental Art Deco building once collected multiple types of mineral water under one roof and contained baths, treatment rooms, pools and a famously long water bar. Some areas remain closed or restricted, but museum and visitor spaces preserve the strange history of Excelsior Springs as a medical-water resort.', 'limited', 'https://www.lewisandclark.travel/listing/hall-of-waters/', 'America/Chicago'),
  ('Bothwell Lodge State Historic Site', 'bothwell-lodge-state-historic-site', 'roadside-oddities', 38.79444, -93.2225, 'Sedalia', 'MO', 'This sprawling Arts-and-Crafts lodge was built over natural caves, which were incorporated into the house as an early form of passive cooling. Guided tours climb through the unusually layered interior while the surrounding grounds remain open on a broader schedule.', 'limited', 'https://mostateparks.com/key-location/bothwell-lodge', 'America/Chicago'),
  ('Red Oak II', 'red-oak-ii', 'roadside-oddities', 37.21296, -94.27792, 'Carthage', 'MO', 'Artist Lowell Davis rebuilt a version of his vanished hometown by relocating and restoring old rural buildings on his property outside Carthage. The result is a deliberately recreated ghost town filled with vintage structures, roadside art and a surreal sense of displaced history.', 'limited', 'https://www.atlasobscura.com/places/red-oak-ii', 'America/Chicago'),
  ('BoatHenge', 'boathenge', 'roadside-oddities', 38.8186, -92.3858, 'Columbia', 'MO', 'Six fiberglass boats stand vertically in the Missouri River bottoms in a tongue-in-cheek imitation of Stonehenge. The folk-art installation appeared in 1993 and has repeatedly survived floods, making it one of central Missouri''s best roadside oddities.', 'roadside', 'https://www.lewisandclark.travel/listing/boathenge/', 'America/Chicago'),
  ('Canoehenge', 'canoehenge', 'roadside-oddities', 38.0553, -91.2196, 'Leasburg', 'MO', 'More than 100 retired canoes are stacked into a Stonehenge-inspired structure at an Ozark river resort near Onondaga Cave State Park. Because it sits on resort property, travelers should follow current visitor rules rather than treating it as unrestricted public land.', 'limited', 'https://www.atlasobscura.com/places/canoehenge', 'America/Chicago'),
  ('Hubble Space Telescope Replica', 'hubble-space-telescope-replica', 'roadside-oddities', 37.33855, -92.9071, 'Marshfield', 'MO', 'A one-quarter-scale, roughly 1,200-pound replica of the Hubble Space Telescope stands near the Webster County Courthouse in astronomer Edwin Hubble''s hometown. The outdoor monument turns a complex spacecraft into an easy roadside science-history stop.', 'roadside', 'https://www.visitmo.com/in-the-spotlight/route-66', 'America/Chicago'),
  ('Route 66 Neon Park', 'route-66-neon-park', 'roadside-oddities', 37.82119, -92.14786, 'St. Robert', 'MO', 'A collection of restored and recreated neon signs preserves the look of businesses that once lined Missouri''s stretch of Route 66. The outdoor display is especially effective after dark and gives travelers a concentrated dose of Mother Road visual history.', 'open', 'https://www.atlasobscura.com/places/route-66-neon-park', 'America/Chicago'),
  ('Maxie, the World''s Largest Goose', 'maxie-the-world-s-largest-goose', 'roadside-oddities', 39.65339, -93.24603, 'Sumner', 'MO', 'Maxie is a roughly 40-foot-tall Canada goose sculpture with a wingspan of more than 60 feet, built as a monument to Sumner''s identity as a goose-hunting and migration town. The giant bird stands in a public park and is an easy northern-Missouri photo stop.', 'roadside', 'https://goosefestival.com/', 'America/Chicago'),
  ('World''s Largest Amoco Sign', 'worlds-largest-amoco-sign', 'roadside-oddities', 38.63296, -90.30447, 'St. Louis', 'MO', 'A towering Amoco sign near Forest Park rises far above the surrounding streets, a survivor of an era when oversized petroleum advertising dominated American roadsides. The sign remains visible from public areas and works best as a quick exterior stop.', 'roadside', 'https://www.atlasobscura.com/places/worlds-largest-amoco-sign', 'America/Chicago'),
  ('Uranus Sideshow Museum & Fudge Factory', 'uranus-sideshow-museum-fudge-factory', 'roadside-oddities', 37.82873, -92.10544, 'St. Robert', 'MO', 'The intentionally absurd Uranus complex combines Route 66 humor with a real sideshow museum containing two-headed animals, circus artifacts, oddities and live performers. The attraction is operating year-round and is one of Missouri''s clearest modern examples of deliberately weird roadside tourism.', 'open', 'https://www.uranusmissouri.com/attractions/uranus-sideshow-museum/', 'America/Chicago'),
  ('Gary''s Gay Parita', 'garys-gay-parita', 'roadside-oddities', 37.19435, -93.67932, 'Paris Springs', 'MO', 'This lovingly recreated 1930s Sinclair station became internationally known through the hospitality of the late Gary Turner and remains a major Route 66 pilgrimage stop. Vintage pumps, signs, vehicles and roadside memorabilia recreate the atmosphere of the Mother Road''s service-station era.', 'limited', 'https://garysgayparita.com/', 'America/Chicago'),
  ('Boots Court Motel', 'boots-court-motel', 'roadside-oddities', 37.1783, -94.3144, 'Carthage', 'MO', 'Built in 1939, Boots Court is a streamlined Route 66 motor court known for its neon, architecture and association with travelers including Clark Gable. The restored property functions as a motel, so exterior viewing is easy while rooms are for registered guests unless tours or events say otherwise.', 'limited', 'https://bootscourt66.com/', 'America/Chicago'),
  ('Wagon Wheel Motel', 'wagon-wheel-motel', 'roadside-oddities', 38.0645, -91.3954, 'Cuba', 'MO', 'The Wagon Wheel has served Route 66 travelers since the 1930s and preserves stone cottages, vintage neon and a classic motor-court layout. It remains an operating motel, making it a rare roadside landmark where travelers can actually stay in the historic property.', 'limited', 'https://wagonwheel66.com/', 'America/Chicago'),
  ('Route 66 State Park / Times Beach', 'route-66-state-park-times-beach', 'roadside-oddities', 38.50575, -90.59092, 'Eureka', 'MO', 'The park occupies land once belonging to Times Beach, a Route 66 community evacuated after dioxin contamination and later demolished. Its visitor center interprets both the Mother Road and the extraordinary environmental history of the vanished town, while park trails cross portions of the former street grid.', 'open', 'https://mostateparks.com/park/route-66-state-park', 'America/Chicago')
on conflict (slug) do update set
  name          = excluded.name,
  category      = excluded.category,
  city          = excluded.city,
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  timezone      = excluded.timezone;

-- The Red Rocker was dropped from the batch as a duplicate, but it brought two
-- things the existing row lacks: a first-party visitmo.com page in place of
-- nothing better, and the correct town. The chair stands at Fanning, not Cuba.
--
-- Its slug stays world-s-largest-rocker. The name has not been the world's
-- largest for years — bigger chairs have been built — but renaming a live page
-- breaks every link to it, and a stale slug is the cheaper of the two.
update public.stops
set source = 'https://www.visitmo.com/things-to-do/route-66-red-rocker',
    city   = 'Fanning'
where slug = 'world-s-largest-rocker';
