-- Nebraska. The state had one stop, and it was Carhenge.
--
-- This is the last piece of Chicago to Denver, which has been the emptiest
-- long route in the index from the beginning. Iowa filled the eastern half a
-- few hours ago; this fills the rest.
--
-- Carhenge is dropped as a duplicate, which means the state's entire previous
-- coverage was one stop that is also in this file.
--
-- Very well sourced: visitnebraska.com, history.nebraska.gov and
-- outdoornebraska.gov are the top three, with the Park Service fourth.
--
-- The panhandle is Mountain time, the rest Central, split at roughly the 101st
-- meridian — Scottsbluff and Chadron on one side, North Platte on the other.
-- Only the second state to need both, after Texas.
--
-- Two proximity flags kept. The Kool-Aid Man statue stands 35 metres from the
-- Hastings Museum's Kool-Aid exhibit because Hastings invented the stuff and
-- has built a small district around saying so.
--
-- 109 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Burlington Locomotive 719', 'burlington-locomotive-719', 'weird-history', 42.11108, -102.87103, 'Alliance', 'NE', 'This preserved steam locomotive commemorates Alliance’s long relationship with the Burlington railroad. The large engine sits outdoors as a straightforward roadside photo stop and gives travelers an industrial counterpart to the city’s better-known Carhenge.', 'roadside', 'https://walk2unlock.ne.gov/markers/burlington-locomotive-719/', null, 'America/Denver', now()),
  ('Dobby’s Frontier Town', 'dobbys-frontier-town', 'museums', 42.1234, -102.8689, 'Alliance', 'NE', 'Kenneth “Dobby” Lee began collecting endangered historic buildings and artifacts to create this volunteer-run frontier village. The property includes a funeral parlor, schoolhouse, church, general store, gas station and other structures that recreate life from the frontier era into the early twentieth century. Main public access is seasonal.', 'limited', 'https://dobbysfrontiertown.com/index', null, 'America/Denver', now()),
  ('Museum of the Fur Trade', 'museum-of-the-fur-trade', 'museums', 42.82377, -102.92818, 'Chadron', 'NE', 'This specialized museum documents the North American fur trade through firearms, trade goods, textiles, tools and other material culture. Its location beside the reconstructed Bordeaux Trading Post gives the collection a direct connection to a historic trading site rather than presenting the subject only in cases.', 'limited', 'https://www.furtrade.org/', null, 'America/Denver', now()),
  ('Bordeaux Trading Post', 'bordeaux-trading-post', 'weird-history', 42.82361, -102.92417, 'Chadron', 'NE', 'A reconstruction of James Bordeaux’s 1830s trading post stands near the site of the original post and is interpreted as part of the Museum of the Fur Trade complex. The structure helps make the region’s fur-trade history physically routeable for OddWay travelers.', 'limited', 'https://www.nps.gov/places/bordeaux-trading-post.htm', null, 'America/Denver', now()),
  ('Mari Sandoz High Plains Heritage Center', 'mari-sandoz-high-plains-heritage-center', 'weird-history', 42.81999, -103.00275, 'Chadron', 'NE', 'The center interprets writer Mari Sandoz and the culture, environment and history of the High Plains that shaped her work. Exhibits connect regional stories of settlement, Indigenous peoples and ranch life to one of Nebraska’s distinctive literary voices.', 'limited', 'https://www.csc.edu/sandoz/', null, 'America/Denver', now()),
  ('Toadstool Geologic Park', 'toadstool-geologic-park', 'roadside-oddities', 42.68302, -103.40548, 'Harrison', 'NE', 'Erosion has carved the badlands here into mushroom-like hoodoos, cliffs and channels that look dramatically unlike the surrounding plains. Fossil trackways preserve evidence of ancient animals, including a rare pursuit sequence involving entelodonts and rhinoceroses. Roads can become difficult after rain or snow.', 'open', 'https://www.nps.gov/thingstodo/hike-toadstool-geo-park.htm', null, 'America/Denver', now()),
  ('Hudson-Meng Bison Kill Site', 'hudson-meng-bison-kill-site', 'weird-history', 42.82833, -103.59972, 'Crawford', 'NE', 'Thousands of bison bones were preserved in a concentrated prehistoric bonebed at this Oglala National Grassland site. The exact cause of the mass accumulation has been debated by archaeologists, making the excavation both visually unusual and scientifically interesting. Visitor access and interpretation are seasonal or scheduled.', 'limited', 'https://www.fs.usda.gov/recarea/nebraska/recarea/?recid=10620', null, 'America/Denver', now()),
  ('Agate Fossil Beds National Monument', 'agate-fossil-beds-national-monument', 'roadside-oddities', 42.42517, -103.79037, 'Harrison', 'NE', 'Agate preserves some of the world’s important Miocene mammal fossil deposits as well as collections connected to the Cook family and Lakota people. Trails cross the fossil landscape while the visitor center interprets animals such as beardogs, ancient rhinoceroses and the strange burrowing paleocast known as Daemonelix.', 'open', 'https://www.nps.gov/agfo/', null, 'America/Denver', now()),
  ('Daemonelix Trail', 'daemonelix-trail', 'roadside-oddities', 42.423, -103.8278, 'Harrison', 'NE', 'This trail leads through terrain containing the corkscrew-shaped fossil burrows once nicknamed “Devil’s Corkscrews.” Scientists eventually linked these spiraling structures to prehistoric beaver relatives, turning what first looked like a bizarre fossil plant into a classic paleontology mystery.', 'open', 'https://www.nps.gov/thingstodo/daemonelix-trail.htm', null, 'America/Denver', now()),
  ('Harold J. Cook Homestead / Bone Cabin', 'harold-j-cook-homestead-bone-cabin', 'weird-history', 42.41815, -103.73918, 'Harrison', 'NE', 'The former Cook ranch is tied directly to the fossil discoveries that led to protection of Agate Fossil Beds. Harold Cook’s family also developed close relationships with Lakota leaders, and the historic homestead helps connect the monument’s paleontology with its human history.', 'limited', 'https://www.nps.gov/agfo/learn/historyculture/cook-homestead.htm', null, 'America/Denver', now()),
  ('Fort Robinson State Park', 'fort-robinson-state-park', 'weird-history', 42.66719, -103.46548, 'Crawford', 'NE', 'Fort Robinson began as a military post and became connected with major events in Plains history, including the final days of Crazy Horse and the 1879 Northern Cheyenne outbreak. The immense preserved post now contains historic buildings, museums and public grounds rather than functioning as an abandoned military site.', 'open', 'https://outdoornebraska.gov/location/fort-robinson/', null, 'America/Denver', now()),
  ('Fort Robinson History Center', 'fort-robinson-history-center', 'museums', 42.66913, -103.4652, 'Crawford', 'NE', 'Housed in the fort’s 1905 post headquarters, this History Nebraska museum interprets the military post, Indigenous history, the Red Cloud Agency period and later uses of Fort Robinson. It is the best controlled-access stop for travelers who want the deeper story behind the surrounding historic landscape.', 'limited', 'https://history.nebraska.gov/fortrobinson/', null, 'America/Denver', now()),
  ('Crazy Horse Death Site Memorial at Fort Robinson', 'crazy-horse-death-site-memorial-at-fort-robinson', 'weird-history', 42.6664, -103.46623, 'Crawford', 'NE', 'A memorial near the old guardhouse area marks Fort Robinson’s connection to the death of Oglala Lakota leader Crazy Horse in 1877. The location is historically significant and sensitive; OddWay should present it as a memorial and historical site, not as a sensationalized attraction.', 'open', 'https://history.nebraska.gov/marker-monday-crazy-horse/', null, 'America/Denver', now()),
  ('Trailside Museum of Natural History', 'trailside-museum-of-natural-history', 'roadside-oddities', 42.6658, -103.46687, 'Crawford', 'NE', 'The museum’s signature display is the fossilized remains of two Columbian mammoths found with their tusks locked together, apparently killed during combat. The dramatic specimen makes this small museum inside Fort Robinson one of Nebraska’s most visually distinctive fossil stops.', 'limited', 'https://museum.unl.edu/trailside-museum/', null, 'America/Denver', now()),
  ('Horse Creek Treaty Historical Marker', 'horse-creek-treaty-historical-marker', 'weird-history', 41.65524, -102.98961, 'Morrill', 'NE', 'This marker interprets the 1851 Fort Laramie Treaty gathering near Horse Creek, where thousands of Native people and U.S. representatives negotiated territorial agreements. The roadside stop provides geographic context for an event whose scale is difficult to understand from the modern landscape alone.', 'roadside', 'https://walk2unlock.ne.gov/markers/horse-creek-treaty/', null, 'America/Denver', now()),
  ('Courthouse and Jail Rocks', 'courthouse-and-jail-rocks', 'roadside-oddities', 41.59682, -103.11582, 'Bridgeport', 'NE', 'These massive Brule clay and sandstone formations were major landmarks for emigrants on the Oregon, California and Mormon trails. Their castle-like shapes inspired names such as Court House, Jail House and Solitary Tower. Public access allows travelers to see the same skyline repeatedly described in nineteenth-century journals.', 'open', 'https://walk2unlock.ne.gov/markers/courthouse-jail-rocks/', null, 'America/Denver', now()),
  ('Pioneer Trails Museum', 'pioneer-trails-museum', 'weird-history', 41.66525, -103.0991, 'Bridgeport', 'NE', 'Located near the historic overland routes through western Nebraska, this local museum preserves objects and stories tied to emigrants, early settlers and transportation through the North Platte Valley. It is a useful interpretive companion to nearby Courthouse and Jail Rocks.', 'limited', 'https://visitnebraska.com/bridgeport/pioneer-trails-museum', null, 'America/Denver', now()),
  ('Chimney Rock National Historic Site', 'chimney-rock-national-historic-site', 'roadside-oddities', 41.71399, -103.3492, 'Bayard', 'NE', 'Chimney Rock’s narrow spire became one of the most famous visual milestones on the Oregon, California and Mormon trails. Emigrants wrote repeatedly about seeing it from miles away, making the formation both a geologic oddity and a surviving landmark from the overland migration era.', 'open', 'https://history.nebraska.gov/rock/', null, 'America/Denver', now()),
  ('Scotts Bluff National Monument', 'scotts-bluff-national-monument', 'roadside-oddities', 41.83464, -103.70714, 'Gering', 'NE', 'Towering bluffs forced emigrant trails through a narrow passage along the North Platte River and later became a defining landmark of western Nebraska. Roads and trails allow visitors onto and around the formations while the NPS visitor center interprets geology and overland-trail history.', 'open', 'https://www.nps.gov/scbl/', null, 'America/Denver', now()),
  ('Scotts Bluff North Overlook', 'scotts-bluff-north-overlook', 'roadside-oddities', 41.83972, -103.69806, 'Gering', 'NE', 'The North Overlook trail reaches the edge of Scotts Bluff with expansive views over the North Platte Valley and the modern communities below. The elevated perspective makes the scale of the monument and the emigrant corridor much easier to understand than from the visitor center alone.', 'open', 'https://www.nps.gov/scbl/planyourvisit/hiking-trails.htm', null, 'America/Denver', now()),
  ('Mitchell Pass', 'mitchell-pass', 'weird-history', 41.8308, -103.71424, 'Gering', 'NE', 'Beginning in the early 1850s, emigrant traffic shifted through this narrow gap between the bluffs, followed later by the Pony Express. Wagon-trail remnants and the constricted landscape make it a strong physical-history stop rather than merely another scenic viewpoint.', 'open', 'https://www.nps.gov/scbl/learn/historyculture/mitchell-pass.htm', null, 'America/Denver', now()),
  ('Legacy of the Plains Museum', 'legacy-of-the-plains-museum', 'museums', 41.82299, -103.68825, 'Gering', 'NE', 'This museum covers High Plains agriculture, Indigenous history, westward migration, irrigation and the many communities that developed in the North Platte Valley. Large equipment and hands-on exhibits make the region’s settlement and farming history unusually tangible.', 'open', 'https://legacyoftheplains.org/', null, 'America/Denver', now()),
  ('Ash Hollow State Historical Park', 'ash-hollow-state-historical-park', 'weird-history', 41.29804, -102.11991, 'Lewellen', 'NE', 'Ash Hollow was a major descent and camping area for emigrants moving west along the Platte. The park combines trail history, archaeology, geology and natural springs, with preserved features spread across the valley rather than concentrated in a single museum building.', 'open', 'https://outdoornebraska.gov/location/ash-hollow/', null, 'America/Denver', now()),
  ('Ash Hollow Cave', 'ash-hollow-cave', 'weird-history', 41.3032, -102.1135, 'Lewellen', 'NE', 'This rock shelter preserves evidence of repeated human use stretching back thousands of years. Archaeological excavations revealed layers of occupation that long predate the Oregon Trail, giving the Ash Hollow area a much deeper human history than the nineteenth-century wagon route alone suggests.', 'limited', 'https://outdoornebraska.gov/location/ash-hollow/', null, 'America/Denver', now()),
  ('Windlass Hill', 'windlass-hill', 'weird-history', 41.2609, -102.11519, 'Lewellen', 'NE', 'Deep wagon ruts descend the steep slope where emigrants struggled down from the tablelands into Ash Hollow. The grade was so difficult that travelers sometimes used ropes or other methods to control wagons, creating one of Nebraska’s clearest surviving pieces of overland-trail terrain.', 'open', 'https://www.nps.gov/places/000/windlass-hill.htm', null, 'America/Denver', now()),
  ('California Hill', 'california-hill', 'weird-history', 41.10056, -101.98167, 'Brule', 'NE', 'Thousands of wagons climbed this steep ridge after crossing the South Platte River, wearing parallel swales into the hillside. The surviving ruts make the scale of nineteenth-century migration visible in the ground itself and are accessible from a maintained historic-trail site.', 'open', 'https://www.nps.gov/places/000/california-hill.htm', null, 'America/Denver', now()),
  ('O’Fallon’s Bluff', 'ofallons-bluff', 'weird-history', 41.13639, -101.09472, 'Sutherland', 'NE', 'Rocky terrain forced Oregon and California Trail travelers into a narrow corridor around this bluff, creating congestion and repeated wagon traffic. A nearby interstate rest area provides a legal, practical place to interpret the landmark without directing visitors onto private land.', 'roadside', 'https://www.nps.gov/places/000/ofallons-bluff-at-sutherland-rest-area.htm', null, 'America/Denver', now()),
  ('Front Street and Crystal Palace Revue', 'front-street-and-crystal-palace-revue', 'weird-history', 41.1254, -101.714, 'Ogallala', 'NE', 'Front Street recreates Ogallala’s cattle-drive era with a saloon-style complex, western displays and seasonal entertainment. The attraction leans into the town’s historical reputation as the rough “Cowboy Capital,” making it deliberately theatrical but still rooted in local trail and cattle history.', 'limited', 'https://visitnebraska.com/ogallala/front-street', null, 'America/Denver', now()),
  ('Boot Hill Cemetery', 'boot-hill-cemetery', 'weird-history', 41.13268, -101.72541, 'Ogallala', 'NE', 'Ogallala’s Boot Hill recalls the violent cattle-town years when some dead were reportedly buried with their boots still on. The hilltop cemetery and monuments preserve the town’s frontier mythology and documented history while remaining a respectful public burial site.', 'open', 'https://visitnebraska.com/ogallala/boot-hill', null, 'America/Denver', now()),
  ('Petrified Wood Gallery', 'petrified-wood-gallery', 'museums', 41.12521, -101.7146, 'Ogallala', 'NE', 'This unusual gallery centers on petrified wood, fossils, minerals and detailed artwork created from stone and fossilized material. The collection turns natural specimens into elaborate landscapes and objects, giving OddWay a strong indoor geology-and-outsider-art stop.', 'limited', 'https://petrifiedwoodgallery.com/', null, 'America/Denver', now()),
  ('The Little Church at Keystone', 'the-little-church-at-keystone', 'roadside-oddities', 41.21627, -101.58333, 'Keystone', 'NE', 'Keystone’s tiny church was built to serve both Catholic and Protestant residents of a small ranching community. Separate religious symbols and an unusual shared-use history make the little building a distinctive piece of rural architecture. Interior access is generally by arrangement rather than guaranteed walk-in hours.', 'limited', 'https://visitnebraska.com/keystone/little-church-keystone', null, 'America/Denver', now()),
  ('First Arthur County Courthouse and Jail', 'first-arthur-county-courthouse-and-jail', 'roadside-oddities', 41.57, -101.6903, 'Arthur', 'NE', 'Arthur County’s first courthouse was an exceptionally small government building, and the nearby jail was built with unusual local materials. Together they reflect the tiny population and improvised civic infrastructure of one of Nebraska’s sparsest counties.', 'limited', 'https://visitnebraska.com/arthur/first-arthur-county-courthouse-and-jail', null, 'America/Denver', now()),
  ('Ole’s Big Game Steakhouse & Lounge', 'oles-big-game-steakhouse-lounge', 'roadside-oddities', 41.12376, -101.35597, 'Paxton', 'NE', 'This longtime roadside restaurant is filled with mounted animals collected during decades of hunting trips, turning a meal into a walk through an old-school trophy room. The dense taxidermy makes it visually unlike a typical Nebraska steakhouse.', 'open', 'https://www.olesbiggame.com/', null, 'America/Denver', now()),
  ('Golden Spike Tower and Bailey Yard', 'golden-spike-tower-and-bailey-yard', 'weird-history', 41.14439, -100.82939, 'North Platte', 'NE', 'The tower overlooks Union Pacific’s enormous Bailey Yard, where freight cars are sorted across a vast web of tracks. Elevated observation decks reveal the scale of railroad operations that cannot be appreciated from ground level, making this one of the state’s strongest industrial OddWay stops.', 'open', 'https://goldenspiketower.com/', null, 'America/Chicago', now()),
  ('Fort Cody Trading Post', 'fort-cody-trading-post', 'roadside-oddities', 41.11361, -100.76294, 'North Platte', 'NE', 'This classic roadside stop combines a gift shop with Old West displays and a large hand-carved miniature recreation of Buffalo Bill’s Wild West show. Its deliberately oversized and nostalgic presentation fits OddWay better than a conventional souvenir store.', 'open', 'https://www.fortcody.com/', null, 'America/Chicago', now()),
  ('Buffalo Bill Ranch State Historical Park', 'buffalo-bill-ranch-state-historical-park', 'weird-history', 41.1622, -100.79529, 'North Platte', 'NE', 'William F. “Buffalo Bill” Cody’s North Platte ranch preserves his Second Empire mansion, barn and grounds. The property ties the famous Wild West showman to an actual Nebraska residence and provides context for the mythology he helped build around the American West.', 'limited', 'https://outdoornebraska.gov/location/buffalo-bill-ranch/', null, 'America/Chicago', now()),
  ('Lincoln County Historical Museum and North Platte Canteen Exhibit', 'lincoln-county-historical-museum-and-north-platte-canteen-exhibit', 'weird-history', 41.16031, -100.79078, 'North Platte', 'NE', 'The museum preserves the story of the North Platte Canteen, where volunteers served millions of military personnel passing through by train during World War II. An outdoor heritage village adds relocated historic buildings, making this more than a standard county display.', 'limited', 'https://lincolncountymuseum.org/', null, 'America/Chicago', now()),
  ('Cody Park Railroad Museum', 'cody-park-railroad-museum', 'weird-history', 41.1479, -100.7609, 'North Platte', 'NE', 'Large Union Pacific locomotives and railroad equipment are displayed in Cody Park, including preserved machines that reflect North Platte’s enormous rail identity. The outdoor setting makes the stop easy to combine with other city landmarks while still offering true industrial scale.', 'limited', 'https://visitnorthplatte.com/cody-park/', null, 'America/Chicago', now()),
  ('100th Meridian Historical Marker', '100th-meridian-historical-marker', 'roadside-oddities', 40.85695, -99.98501, 'Cozad', 'NE', 'This marker commemorates the line of 100 degrees west longitude, a geographic division that became culturally associated with the transition toward the drier Great Plains. Cozad itself was named for the meridian, turning an invisible coordinate into a routeable roadside history stop.', 'roadside', 'https://history.nebraska.gov/marker-monday-the-100th-meridian/', null, 'America/Chicago', now()),
  ('Pony Express Station Museum', 'pony-express-station-museum', 'weird-history', 40.93324, -100.15949, 'Gothenburg', 'NE', 'A preserved nineteenth-century log station associated with the Pony Express was relocated to a public park in Gothenburg. The compact building gives travelers a tangible piece of the short-lived mail service that became far more famous than its actual operating lifespan.', 'limited', 'https://www.ponyexpressstation.org/', null, 'America/Chicago', now()),
  ('Grand Duke Alexis Historical Marker', 'grand-duke-alexis-historical-marker', 'weird-history', 40.55726, -100.9102, 'Hayes Center', 'NE', 'This marker recalls the huge 1872 buffalo hunt staged for visiting Russian Grand Duke Alexis, involving prominent western figures and an elaborate camp. The event is a strange intersection of diplomacy, celebrity, Plains history and spectacle.', 'roadside', 'https://walk2unlock.ne.gov/markers/grand-duke-alexis/', null, 'America/Chicago', now()),
  ('General Custer in Nebraska Historical Marker', 'general-custer-in-nebraska-historical-marker', 'weird-history', 40.03801, -101.543, 'Trenton', 'NE', 'This marker interprets George Armstrong Custer’s movements through southwestern Nebraska during military campaigns on the Plains. It gives a geographic anchor to a figure usually associated with events farther north and west.', 'roadside', 'https://walk2unlock.ne.gov/markers/general-custer-in-nebraska/', null, 'America/Denver', now()),
  ('Massacre Canyon Monument', 'massacre-canyon-monument', 'weird-history', 40.2064, -100.96457, 'Trenton', 'NE', 'The monument commemorates the 1873 battle between Pawnee and Lakota people known as the Massacre Canyon conflict. The site is historically significant and somber, and OddWay should frame it as Indigenous and regional history rather than a spectacle.', 'open', 'https://history.nebraska.gov/marker-monday-massacre-canyon/', null, 'America/Chicago', now()),
  ('Pioneer Village', 'pioneer-village', 'museums', 40.5077, -98.95113, 'Minden', 'NE', 'Founded by Harold Warp, this sprawling museum assembles tens of thousands of objects across buildings devoted to transportation, household technology, agriculture and everyday American life. Its sheer scale and time-capsule quality make it far stranger than a typical local history museum.', 'open', 'https://pioneervillage.com/', null, 'America/Chicago', now()),
  ('Harvard Jail House', 'harvard-jail-house', 'weird-history', 40.61805, -98.09788, 'Harvard', 'NE', 'This small historic jail preserves the sort of stark local lockup that once served rural Nebraska communities. Its compact cells and utilitarian construction make it an appropriately offbeat stop when the building is open or available for viewing.', 'limited', 'https://visitnebraska.com/harvard/harvard-jail-house', null, 'America/Chicago', now()),
  ('Fort Kearny State Historical Park', 'fort-kearny-state-historical-park', 'weird-history', 40.64278, -99.00583, 'Kearney', 'NE', 'Reconstructed structures and archaeological interpretation mark the site of Fort Kearny, an important military and emigrant-trail post along the Platte. The fort served travelers, mail routes and military operations moving through the central overland corridor.', 'open', 'https://outdoornebraska.gov/location/fort-kearny-shp/', null, 'America/Chicago', now()),
  ('The Archway', 'the-archway', 'roadside-oddities', 40.67042, -99.0385, 'Kearney', 'NE', 'A museum literally spans Interstate 80 in a giant bridge-like structure, interpreting centuries of travel through the Platte River corridor. Its unusual architecture makes the building itself a roadside oddity before visitors even enter the exhibits.', 'open', 'https://archway.org/', null, 'America/Chicago', now()),
  ('Stuhr Museum of the Prairie Pioneer', 'stuhr-museum-of-the-prairie-pioneer', 'museums', 40.88397, -98.3733, 'Grand Island', 'NE', 'Stuhr combines a striking modern museum building with a recreated 1890s railroad town and historic structures. The juxtaposition of formal architecture, working demonstrations and reconstructed streets gives it more route value than a conventional regional museum.', 'open', 'https://stuhrmuseum.org/', null, 'America/Chicago', now()),
  ('Fred’s Flying Circus', 'freds-flying-circus', 'roadside-oddities', 40.93058, -98.33732, 'Grand Island', 'NE', 'A collection of homemade mechanical figures, vehicles and whimsical metal creations fills this roadside property north of Grand Island. The folk-art installation is designed to be seen from the road; visitors should remain in lawful public viewing areas and respect the property.', 'roadside', 'https://visitnebraska.com/grand-island/freds-flying-circus', null, 'America/Chicago', now()),
  ('Iain Nicolson Audubon Center at Rowe Sanctuary', 'iain-nicolson-audubon-center-at-rowe-sanctuary', 'roadside-oddities', 40.66969, -98.88477, 'Gibbon', 'NE', 'Each spring, enormous numbers of sandhill cranes converge on the Platte River, producing one of Nebraska’s most dramatic recurring natural spectacles. Rowe Sanctuary operates controlled viewing experiences and blinds during migration, so advance reservations are important during peak crane season.', 'limited', 'https://rowe.audubon.org/', null, 'America/Chicago', now()),
  ('Hastings Museum — Kool-Aid: Discover the Dream', 'hastings-museum-kool-aid-discover-the-dream', 'weird-history', 40.60009, -98.39151, 'Hastings', 'NE', 'Kool-Aid was invented in Hastings, and the museum maintains a dedicated exhibit tracing Edwin Perkins and the powdered drink’s development. The bright commercial history gives the city an unexpectedly strong pop-culture connection.', 'open', 'https://hastingsmuseum.org/exhibits/kool-aid/', null, 'America/Chicago', now()),
  ('Kool-Aid Man Statue', 'kool-aid-man-statue', 'roadside-oddities', 40.59985, -98.39177, 'Hastings', 'NE', 'A large Kool-Aid Man figure outside the Hastings Museum turns the city’s claim as the drink’s birthplace into an easy public photo stop. It works well as a quick OddWay pin paired with the museum’s deeper Kool-Aid exhibit.', 'open', 'https://visitnebraska.com/hastings/hastings-museum', null, 'America/Chicago', now()),
  ('Bigfoot Crossroads of America Museum', 'bigfoot-crossroads-of-america-museum', 'cryptids', 40.62665, -98.36586, 'Hastings', 'NE', 'This dedicated Bigfoot museum grew from Nebraska researcher Harriet McFeely’s interest in Sasquatch reports and evidence. Exhibits focus on casts, research material, witness stories and the broader Bigfoot phenomenon, giving Nebraska a legitimate routeable cryptid stop.', 'limited', 'https://nebraskabigfootmuseum.com/', null, 'America/Chicago', now()),
  ('Original Kool-Aid Factory Site', 'original-kool-aid-factory-site', 'weird-history', 40.58437, -98.38798, 'Hastings', 'NE', 'A historical marker at the former Perkins Products factory location identifies the place where Kool-Aid production became a Hastings industry. The building/site gives travelers a second, more geographic connection to the drink beyond the museum displays.', 'roadside', 'https://www.hmdb.org/m.asp?m=251833', null, 'America/Chicago', now()),
  ('Edgerton Explorit Center', 'edgerton-explorit-center', 'weird-history', 40.85867, -97.99606, 'Aurora', 'NE', 'This hands-on science center honors Harold “Doc” Edgerton, the Aurora-born MIT engineer whose stroboscopic photography froze bullets, milk drops and other split-second events in iconic images. Interactive exhibits connect his unusual high-speed experiments with broader science demonstrations.', 'open', 'https://edgerton.org/', null, 'America/Chicago', now()),
  ('Lee’s Legendary Marbles & Collectibles', 'lees-legendary-marbles-collectibles', 'museums', 40.8327, -97.59814, 'York', 'NE', 'Thousands of marbles, vintage toys and unusual collectibles fill this highly specialized museum and shop. The concentration of antique and contemporary marbles makes it the kind of niche collection OddWay is built to surface along an otherwise ordinary highway route.', 'open', 'https://leeslegendarymarbles.com/', null, 'America/Chicago', now()),
  ('Clayton Museum of Ancient History', 'clayton-museum-of-ancient-history', 'weird-history', 40.869, -97.57908, 'York', 'NE', 'This unusually focused museum on a Nebraska college campus displays replicas and artifacts relating to the ancient Mediterranean and Near East. Exhibits on Roman military life, archaeology and early civilizations create an unexpected ancient-history stop in the Great Plains.', 'open', 'https://www.claytonmuseumofancienthistory.org/', null, 'America/Chicago', now()),
  ('World’s Largest Time Capsule Site', 'worlds-largest-time-capsule-site', 'roadside-oddities', 40.91636, -97.09615, 'Seward', 'NE', 'Harold Davisson built an enormous time capsule in Seward and later added a pyramid and even a car to maintain its record-setting scale. The capsule was opened in June 2025 after roughly fifty years, so OddWay should describe this as the historic time-capsule site rather than incorrectly claiming it remains sealed.', 'roadside', 'https://www.klkntv.com/hundreds-gather-to-see-what-was-inside-worlds-largest-time-capsule-in-seward/', null, 'America/Chicago', now()),
  ('Nebraska National Guard Museum', 'nebraska-national-guard-museum', 'weird-history', 40.90879, -97.10222, 'Seward', 'NE', 'This museum interprets Nebraska National Guard service through uniforms, vehicles, equipment and stories extending across multiple conflicts. Its collection gives a military-history counterpart to Seward’s more eccentric time-capsule stop.', 'open', 'https://www.nationalguardmuseumne.org/', null, 'America/Chicago', now()),
  ('World’s Largest Covered Porch Swing', 'worlds-largest-covered-porch-swing', 'roadside-oddities', 40.16558, -97.59168, 'Hebron', 'NE', 'Hebron built an enormous covered porch swing large enough to seat many people at once, turning an ordinary piece of backyard furniture into a civic landmark. It remains an easy public photo stop in Roosevelt Park.', 'open', 'https://visitnebraska.com/hebron/worlds-largest-covered-porch-swing', null, 'America/Chicago', now()),
  ('National Willa Cather Center', 'national-willa-cather-center', 'weird-history', 40.08908, -98.51938, 'Red Cloud', 'NE', 'The center anchors a collection of Red Cloud sites tied to author Willa Cather and the people and places that influenced her fiction. Exhibits help travelers connect the surrounding town and prairie landscape with literary settings inspired by south-central Nebraska.', 'open', 'https://www.willacather.org/', null, 'America/Chicago', now()),
  ('Willa Cather Memorial Prairie', 'willa-cather-memorial-prairie', 'weird-history', 40.00398, -98.52316, 'Red Cloud', 'NE', 'This preserved native prairie south of Red Cloud protects the type of landscape that shaped Cather’s writing about the Great Plains. Trails allow visitors to experience the setting itself rather than only reading about it inside the town’s historic buildings.', 'open', 'https://www.willacather.org/willa-cather-memorial-prairie', null, 'America/Chicago', now()),
  ('Rock Creek Station State Historical Park', 'rock-creek-station-state-historical-park', 'weird-history', 40.11054, -97.05583, 'Fairbury', 'NE', 'Rock Creek was an Oregon-California Trail and Pony Express station, but it is best known for the 1861 confrontation in which James Butler “Wild Bill” Hickok killed David McCanles and others. Reconstructed buildings and trail ruts give the famous gunfight a physical setting.', 'open', 'https://outdoornebraska.gov/location/rock-creek-station/', null, 'America/Chicago', now()),
  ('Spring Ranche Historical Marker', 'spring-ranche-historical-marker', 'haunted', 40.43741, -98.24033, 'Fairfield', 'NE', 'The public historical marker interprets the vanished Spring Ranche settlement, which later accumulated local stories involving violence and a reportedly haunted bridge. OddWay should route users only to the lawful public marker and road corridor, not onto private property or unverified bridge access.', 'roadside', 'https://history.nebraska.gov/nebraska-historical-marker-program/', null, 'America/Chicago', now()),
  ('Great Plains Welsh Heritage Centre', 'great-plains-welsh-heritage-centre', 'weird-history', 40.12012, -96.66212, 'Wymore', 'NE', 'This specialized center preserves the history of Welsh immigrants who settled on the Great Plains, including language, music, religion and community life. Its narrow cultural focus makes it a worthwhile niche-history stop rather than a generic local museum.', 'limited', 'https://www.welshheritageproject.org/', null, 'America/Chicago', now()),
  ('Jerry’s Dream Museum', 'jerrys-dream-museum', 'museums', 40.10966, -96.15809, 'Odell', 'NE', 'This small private collection is centered on unusual memorabilia and objects assembled by its creator, giving travelers the feeling of entering someone’s long-running personal obsession rather than a formal institutional museum. Verify current hours or appointment requirements before routing.', 'limited', 'https://visitnebraska.com/odell/jerrys-dream-museum', null, 'America/Chicago', now()),
  ('Happy Jack Peak and Chalk Mine', 'happy-jack-peak-and-chalk-mine', 'weird-history', 41.44251, -98.70897, 'Scotia', 'NE', 'A former chalk mine cuts horizontally into Happy Jack Peak, creating a rare public underground room-and-pillar mine in Nebraska. Guided or seasonal access reveals the pale chalk walls and industrial excavation while the surrounding peak provides trails and views.', 'limited', 'https://happyjackpeakandchalkmine.org/', null, 'America/Chicago', now()),
  ('The Villagers of Taylor', 'the-villagers-of-taylor', 'roadside-oddities', 41.77028, -99.37872, 'Taylor', 'NE', 'Life-size painted figures are positioned around Taylor in scenes depicting residents, workers and everyday town life. The growing outdoor art project turns streets, lots and buildings into an eerie open-air population of wooden or metal “villagers.”', 'open', 'https://visitnebraska.com/taylor/villagers-taylor', null, 'America/Chicago', now()),
  ('Fort Hartsuff State Historical Park', 'fort-hartsuff-state-historical-park', 'weird-history', 41.7235, -99.02361, 'Elyria', 'NE', 'Fort Hartsuff preserves a collection of 1870s military buildings constructed from local concrete-like material rather than the stereotypical wooden frontier fort. The surviving post interprets Army life and conflicts surrounding settlement of the North Loup Valley.', 'open', 'https://outdoornebraska.gov/location/fort-hartsuff/', null, 'America/Chicago', now()),
  ('Loup City Riot Historical Marker', 'loup-city-riot-historical-marker', 'weird-history', 41.27529, -98.96675, 'Loup City', 'NE', 'This marker recalls the 1934 Loup City disturbance in which tensions surrounding relief work and local politics erupted into violence. The roadside marker gives an otherwise obscure Depression-era conflict a precise geographic anchor.', 'roadside', 'https://history.nebraska.gov/nebraska-historical-marker-program/', null, 'America/Chicago', now()),
  ('Ashfall Fossil Beds State Historical Park', 'ashfall-fossil-beds-state-historical-park', 'roadside-oddities', 42.42186, -98.15769, 'Royal', 'NE', 'A prehistoric volcanic ashfall buried and preserved entire herds of rhinoceroses, horses and other animals here. Visitors can look directly into an active excavation inside the Hubbard Rhino Barn, making the site one of Nebraska’s most exceptional fossil experiences.', 'limited', 'https://outdoornebraska.gov/location/ashfall-fossil-beds/', null, 'America/Chicago', now()),
  ('Klown Doll Museum', 'klown-doll-museum', 'museums', 42.35059, -97.79186, 'Plainview', 'NE', 'Thousands of clown dolls and clown-related objects fill this deliberately specialized museum. For travelers who find clowns charming or unsettling, the sheer density of figures makes it an unusually memorable small-town collection.', 'limited', 'https://visitnebraska.com/plainview/klown-doll-museum', null, 'America/Chicago', now()),
  ('Neligh Mill State Historic Site', 'neligh-mill-state-historic-site', 'weird-history', 42.1264, -98.03115, 'Neligh', 'NE', 'This preserved nineteenth-century flour mill retains machinery and structures connected to water-powered grain processing on the Elkhorn River. The surviving industrial equipment makes it a strong example of an obsolete technology preserved in place.', 'limited', 'https://history.nebraska.gov/nelighmill/', null, 'America/Chicago', now()),
  ('World’s Largest Shamrock', 'worlds-largest-shamrock', 'roadside-oddities', 42.45767, -98.64788, 'O’Neill', 'NE', 'A giant shamrock painted into the pavement marks O’Neill’s identity as Nebraska’s self-proclaimed Irish Capital. The oversized symbol occupies a downtown intersection and works as a fast roadside photo stop.', 'open', 'https://walk2unlock.ne.gov/markers/worlds-largest-shamrock/', null, 'America/Chicago', now()),
  ('Monowi — Nebraska’s One-Resident Village', 'monowi-nebraskas-one-resident-village', 'weird-history', 42.82811, -98.32507, 'Monowi', 'NE', 'Monowi became famous for having only one resident, Elsie Eiler, who has served multiple civic roles while operating the Monowi Tavern. It is not an abandoned ghost town, but its extreme population decline makes it one of America’s strangest functioning incorporated villages. Respect residents and private property.', 'open', 'https://visitnebraska.com/monowi', null, 'America/Chicago', now()),
  ('Ionia “Volcano” Historical Marker', 'ionia-volcano-historical-marker', 'weird-history', 42.65241, -96.87186, 'Newcastle', 'NE', 'Early travelers saw smoke, heat and burning material in the Missouri River bluffs and believed a volcano existed near the vanished town of Ionia. Later investigation attributed the phenomenon to chemical processes and burning deposits, but the “volcano” legend persisted for decades.', 'roadside', 'https://history.nebraska.gov/marker-monday-the-ionia-volcano/', null, 'America/Chicago', now()),
  ('Ainsworth Army Air Field Historical Marker', 'ainsworth-army-air-field-historical-marker', 'weird-history', 42.5604, -100.0034, 'Johnstown', 'NE', 'This marker interprets a World War II training base whose long concrete runways hosted fighter and bomber crews. The airfield also participated in aircraft-camouflage experiments before closing after the war, leaving an unusual military layer in the Sandhills landscape.', 'roadside', 'https://history.nebraska.gov/marker-monday-ainsworth-army-air-field/', null, 'America/Chicago', now()),
  ('DeWitty / Audacious Historical Marker', 'dewitty-audacious-historical-marker', 'weird-history', 42.2846, -100.53627, 'Brownlee', 'NE', 'The marker identifies the region of DeWitty, later called Audacious, the largest and longest-lasting African American settlement in rural Nebraska. Black homesteaders established farms, schools, a church, businesses and community events in the Sandhills before environmental and economic pressures led most families away.', 'roadside', 'https://history.nebraska.gov/marker-monday-dewitty-an-african-american-settlement-in-the-sandhills/', null, 'America/Chicago', now()),
  ('Merritt Reservoir International Dark Sky Park', 'merritt-reservoir-international-dark-sky-park', 'roadside-oddities', 42.596, -100.892, 'Valentine', 'NE', 'Remote Sandhills geography and extremely low light pollution give Merritt Reservoir some of Nebraska’s darkest night skies. Its International Dark Sky designation makes the reservoir a routeable stargazing stop rather than simply another recreation lake.', 'open', 'https://outdoornebraska.gov/location/merritt-reservoir/', null, 'America/Chicago', now()),
  ('Niobrara National Scenic River Visitor Center', 'niobrara-national-scenic-river-visitor-center', 'museums', 42.8683, -100.5554, 'Valentine', 'NE', 'The Niobrara cuts through an unusual biological crossroads where eastern, western and northern plant communities overlap. The NPS visitor center provides context for the river’s geology, waterfalls, wildlife and cultural history before travelers enter the broader scenic corridor.', 'open', 'https://www.nps.gov/niob/', null, 'America/Chicago', now()),
  ('Smith Falls State Park', 'smith-falls-state-park', 'roadside-oddities', 42.88825, -100.31502, 'Valentine', 'NE', 'Nebraska’s tallest waterfall drops through a cool, spring-fed side canyon into the Niobrara corridor. A footbridge and trail provide controlled public access to a natural feature that feels unexpectedly secluded for the Great Plains.', 'open', 'https://outdoornebraska.gov/location/smith-falls/', null, 'America/Chicago', now()),
  ('Walgren Lake State Recreation Area — Lake Monster Lore', 'walgren-lake-state-recreation-area-lake-monster-lore', 'cryptids', 42.63765, -102.62868, 'Hay Springs', 'NE', 'Walgren Lake is associated with a long-running Nebraska monster story, sometimes called the Alkali Lake Monster, describing an enormous creature in or around the water. The recreation area is a legitimate public destination, allowing OddWay to attach the folklore to a safe, routeable lake rather than an invented pin.', 'open', 'https://outdoornebraska.gov/location/walgren-lake/', null, 'America/Denver', now()),
  ('Dr. Susan La Flesche Picotte Center', 'dr-susan-la-flesche-picotte-center', 'weird-history', 42.15186, -96.49575, 'Walthill', 'NE', 'Built as a hospital by Dr. Susan La Flesche Picotte, widely recognized as the first Native American physician in the United States, this restored building carries major Omaha Tribe and medical-history significance. Current programming and interior access should be checked before arrival.', 'limited', 'https://www.susanlafleschepicottecenter.org/', null, 'America/Chicago', now()),
  ('John G. Neihardt State Historic Site', 'john-g-neihardt-state-historic-site', 'weird-history', 42.01138, -96.57698, 'Bancroft', 'NE', 'The site preserves the study of poet and writer John G. Neihardt, whose work includes the influential and controversial Black Elk Speaks. Exhibits examine his life, writing and relationships with Native people, giving travelers useful historical context beyond the book’s mythology.', 'open', 'https://neihardtcenter.org/', null, 'America/Chicago', now()),
  ('Siouxland Freedom Park', 'siouxland-freedom-park', 'weird-history', 42.47113, -96.39246, 'South Sioux City', 'NE', 'This riverfront memorial complex includes military monuments, large artifacts and a replica Vietnam Veterans Memorial wall. Its concentration of military remembrance and machinery makes it a substantial public stop along Nebraska’s northeastern edge.', 'open', 'https://siouxlandfreedompark.org/', null, 'America/Chicago', now()),
  ('Fort Atkinson State Historical Park', 'fort-atkinson-state-historical-park', 'weird-history', 41.45473, -96.0168, 'Fort Calhoun', 'NE', 'Built near the site of the 1804 Lewis and Clark council at Council Bluff, Fort Atkinson became the first major U.S. military post west of the Missouri River in this region. Reconstructed buildings and living-history events recreate an unusually early frontier military community.', 'open', 'https://outdoornebraska.gov/location/fort-atkinson/', null, 'America/Chicago', now()),
  ('Museum of Shadows', 'museum-of-shadows', 'haunted', 41.25893, -95.93107, 'Omaha', 'NE', 'This paranormal museum displays objects presented by its operators as haunted or connected with unusual activity. Whatever visitors conclude about the claims, it is a purpose-built, lawful paranormal attraction rather than an abandoned building or trespass-dependent legend.', 'open', 'https://www.museumofshadows.com/', null, 'America/Chicago', now()),
  ('Japanese Balloon Bomb Explosion Historical Marker', 'japanese-balloon-bomb-explosion-historical-marker', 'roadside-oddities', 41.26487, -95.99047, 'Omaha', 'NE', 'A marker documents a Japanese Fu-Go balloon bomb that exploded in Omaha during World War II. Japan launched thousands of these high-altitude weapons toward North America, making the Nebraska incident an unusual local trace of a little-known wartime campaign.', 'roadside', 'https://history.nebraska.gov/nebraska-historical-marker-photo-submission/', null, 'America/Chicago', now()),
  ('Old Lincoln Highway at Elkhorn', 'old-lincoln-highway-at-elkhorn', 'weird-history', 41.27394, -96.19617, 'Omaha', 'NE', 'A surviving section and marker recall the Lincoln Highway, one of the first transcontinental automobile routes in the United States. The stop connects modern Omaha traffic with the era when cross-country driving depended on named roads, local markers and frequently primitive conditions.', 'roadside', 'https://history.nebraska.gov/nebraska-historical-marker-photo-submission/', null, 'America/Chicago', now()),
  ('The Infield at Omaha’s Henry Doorly Zoo', 'the-infield-at-omahas-henry-doorly-zoo', 'weird-history', 41.22548, -95.93156, 'Omaha', 'NE', 'The zoo occupies land that once held Rosenblatt Stadium, and the former baseball infield has been preserved as a recognizable patch within the grounds. It creates the odd experience of finding a vanished College World Series ballpark embedded inside a major zoo.', 'open', 'https://www.omahazoo.com/', null, 'America/Chicago', now()),
  ('World’s Largest Ball of Stamps', 'worlds-largest-ball-of-stamps', 'roadside-oddities', 41.26257, -96.12698, 'Boys Town', 'NE', 'Millions of canceled postage stamps were assembled into a giant spherical mass at Boys Town. The object turns an ordinary collectible into a deliberately absurd oversized artifact and remains one of the Omaha area’s classic niche curiosities.', 'limited', 'https://visitnebraska.com/boys-town/worlds-largest-ball-stamps', null, 'America/Chicago', now()),
  ('Chef Boyardee Statue', 'chef-boyardee-statue', 'roadside-oddities', 41.25386, -95.9253, 'Omaha', 'NE', 'A statue honors Ettore “Hector” Boiardi, better known through the Chef Boyardee brand, and his connection to Omaha’s food industry. The larger-than-life branded figure is an easy downtown curiosity with an unexpected connection to American grocery-store history.', 'open', 'https://visitnebraska.com/omaha/chef-boyardee-statue', null, 'America/Chicago', now()),
  ('Joslyn Castle', 'joslyn-castle', 'roadside-oddities', 41.2617, -95.97181, 'Omaha', 'NE', 'This massive Scottish Baronial-style mansion was built for George and Sarah Joslyn and is filled with elaborate woodwork, stone, stained glass and unusual rooms. Guided access lets visitors explore a piece of Gilded Age architecture that looks strikingly out of place on the Plains.', 'limited', 'https://joslyncastle.com/', null, 'America/Chicago', now()),
  ('Great Plains Black History Museum', 'great-plains-black-history-museum', 'weird-history', 41.25959, -95.9437, 'Omaha', 'NE', 'The museum preserves and interprets African American history in Omaha and across the Great Plains, including civil rights, migration, businesses and community life. Its regional focus fills an important historical gap often missed by broader Nebraska museums.', 'limited', 'https://gpblackhistorymuseum.org/', null, 'America/Chicago', now()),
  ('Nebraska State Capitol Mosaic Floor', 'nebraska-state-capitol-mosaic-floor', 'roadside-oddities', 40.80805, -96.69971, 'Lincoln', 'NE', 'The Nebraska Capitol’s interior floors contain elaborate mosaics depicting natural history, cosmic symbolism and the evolution of life. Combined with the building’s unusual tower and integrated art program, the floor turns a functioning government building into a dense symbolic artwork.', 'limited', 'https://capitol.nebraska.gov/', null, 'America/Chicago', now()),
  ('Morrill Hall — Archie the Mammoth', 'morrill-hall-archie-the-mammoth', 'roadside-oddities', 40.81991, -96.70185, 'Lincoln', 'NE', 'The University of Nebraska State Museum is home to “Archie,” an enormous Columbian mammoth reconstruction that has become a Lincoln landmark. Fossil elephants and other prehistoric animals give the museum one of the strongest paleontology collections in the region.', 'open', 'https://museum.unl.edu/', null, 'America/Chicago', now()),
  ('Pioneers Park Pillars', 'pioneers-park-pillars', 'roadside-oddities', 40.7791, -96.75714, 'Lincoln', 'NE', 'Four massive columns from the old U.S. Treasury Building in Washington, D.C., were relocated to Lincoln and now stand unexpectedly in Pioneers Park. The transplanted classical architecture creates the appearance of monumental ruins in a Nebraska landscape.', 'open', 'https://www.lincoln.ne.gov/City/Departments/Parks-and-Recreation/Parks-Facilities/Pioneers-Park', null, 'America/Chicago', now()),
  ('Robber’s Cave', 'robbers-cave', 'weird-history', 40.78, -96.7078, 'Lincoln', 'NE', 'A network of sandstone chambers beneath Lincoln accumulated stories involving outlaws, breweries, secret meetings and other underground activity. Today access is controlled through scheduled tours, allowing visitors into the historic cave system without trespassing.', 'limited', 'https://www.robberscavetours.com/', null, 'America/Chicago', now()),
  ('National Museum of Roller Skating', 'national-museum-of-roller-skating', 'museums', 40.79189, -96.65418, 'Lincoln', 'NE', 'This nationally focused museum preserves roller skates, costumes, trophies, photographs and equipment tracing the evolution of skating. Its highly specific collection covers everything from recreation and rink culture to competitive roller sports.', 'open', 'https://www.rollerskatingmuseum.org/', null, 'America/Chicago', now()),
  ('International Quilt Museum', 'international-quilt-museum', 'museums', 40.82833, -96.67357, 'Lincoln', 'NE', 'One of the world’s major quilt collections is housed in a purpose-built Lincoln museum with textiles spanning countries, centuries and artistic traditions. The scale and specialization turn a familiar household object into a surprisingly global material-culture archive.', 'open', 'https://www.internationalquiltmuseum.org/', null, 'America/Chicago', now()),
  ('Museum of American Speed', 'museum-of-american-speed', 'weird-history', 40.82212, -96.77792, 'Lincoln', 'NE', 'This enormous collection covers racing engines, hot rods, land-speed vehicles, pedal cars, automobilia and mechanical innovation. Its dense assortment of machines and speed-related artifacts makes it much more eccentric than a standard automobile museum.', 'open', 'https://www.museumofamericanspeed.org/', null, 'America/Chicago', now()),
  ('Kregel Windmill Factory Museum', 'kregel-windmill-factory-museum', 'weird-history', 40.67699, -95.86362, 'Nebraska City', 'NE', 'The Kregel factory was preserved with its machinery, tools, patterns and workspaces largely intact, creating the feeling that workers simply left the shop. Rather than reconstructing an industry elsewhere, the museum interprets windmill manufacturing inside the original factory.', 'open', 'https://www.kregelwindmillfactorymuseum.org/', null, 'America/Chicago', now()),
  ('Mayhew Cabin and John Brown’s Cave', 'mayhew-cabin-and-john-browns-cave', 'weird-history', 40.67323, -95.8699, 'Nebraska City', 'NE', 'This historic site interprets Nebraska’s Underground Railroad connections through the Mayhew family story and a reconstructed underground passage traditionally associated with freedom seekers. The “cave” element and abolitionist history make it one of the state’s most unusual historic-house stops.', 'limited', 'https://mayhewcabin.org/', null, 'America/Chicago', now()),
  ('Seven Sisters Road', 'seven-sisters-road', 'haunted', 40.62468, -96.08013, 'Nebraska City', 'NE', 'A rural road west of Nebraska City has long been linked to a legend about seven sisters and reports of eerie nighttime experiences. The story varies widely and is folklore rather than established history. Travelers should remain on public roads, avoid stopping dangerously, and never enter surrounding private property.', 'roadside', 'https://visitnebraska.com/trip-idea/haunted-spooky-attractions-nebraska', null, 'America/Chicago', now()),
  ('Indian Cave State Park — Petroglyph Cave', 'indian-cave-state-park-petroglyph-cave', 'weird-history', 40.26539, -95.57998, 'Shubert', 'NE', 'The park takes its name from a sandstone shelter containing petroglyphs whose age and precise origins remain uncertain. A boardwalk provides public viewing while protecting the fragile carvings. The surrounding park also preserves archaeological and historic resources along the Missouri River.', 'open', 'https://outdoornebraska.gov/location/indian-cave/', null, 'America/Chicago', now()),
  ('St. Deroin Ghost Town', 'st-deroin-ghost-town', 'weird-history', 40.25531, -95.5675, 'Shubert', 'NE', 'St. Deroin was once a Missouri River community but declined after transportation patterns changed and repeated flooding damaged the town. Reconstructed and preserved features within Indian Cave State Park allow visitors to explore the remains of a real vanished settlement without entering abandoned private property.', 'open', 'https://outdoornebraska.gov/location/indian-cave/', null, 'America/Chicago', now()),
  ('Arbor Lodge State Historical Park', 'arbor-lodge-state-historical-park', 'weird-history', 40.68051, -95.88149, 'Nebraska City', 'NE', 'The estate of J. Sterling Morton is tied directly to the creation of Arbor Day, turning Nebraska City into the origin point of a holiday now observed around the world. The mansion, collections and tree-filled grounds preserve the place where that unusually influential civic idea developed.', 'open', 'https://outdoornebraska.gov/location/arbor-lodge/', null, 'America/Chicago', now()),
  ('Dorrington Underground Railroad Historical Marker', 'dorrington-underground-railroad-historical-marker', 'weird-history', 40.06085, -95.60327, 'Falls City', 'NE', 'This marker interprets the role of the Dorrington family and Falls City area in antislavery activity and Underground Railroad history before the Civil War. It provides a public, routeable location for a history that often depended on private homes and secret movement.', 'roadside', 'https://history.nebraska.gov/nebraska-historical-marker-program/', null, 'America/Chicago', now()),
  ('Strategic Air Command & Aerospace Museum', 'strategic-air-command-aerospace-museum', 'weird-history', 41.0155, -96.31813, 'Ashland', 'NE', 'Two immense hangars contain Cold War bombers, reconnaissance aircraft, missiles and other aerospace artifacts tied to Strategic Air Command. The scale of the aircraft and nuclear-era technology makes this one of Nebraska’s strongest military and technological OddWay stops.', 'open', 'https://www.sacmuseum.org/', null, 'America/Chicago', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  timezone      = excluded.timezone,
  verified_at   = excluded.verified_at;

select count(*) as nebraska from public.stops where state = 'NE';
