-- New Jersey, third batch.
--
-- Smiley Face Water Tower goes in as smiley-face-water-tower-longport,
-- because Ashley, Indiana holds the plain slug. Two different water towers
-- painted with the same face, which is apparently a genre.
--
-- Six proximity flags, none of them duplicates — the Jersey Shore is simply
-- dense. Tillie is 36 metres from the SS Morro Castle memorial because both
-- are on the same stretch of Asbury Park boardwalk, and the Zinc Miner statue
-- stands 54 metres outside the Franklin Mineral Museum. Separate things in
-- both cases.
--
-- 50 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Tillie at The Wonder Bar', 'tillie-at-the-wonder-bar', 'roadside-oddities', 40.22329, -73.99929, 'Asbury Park', 'NJ', 'A large grinning Tillie face overlooks the exterior of The Wonder Bar, preserving Asbury Park''s long-running connection with the strange smiling mascot once associated with Palace Amusements. The present face is a tribute rather than the original mural, but it remains an easy public-roadside stop.', 'roadside', 'https://www.roadsideamerica.com/story/13017', null, 'America/New_York', now()),
  ('Bert Parks Crowns You Miss America', 'bert-parks-crowns-you-miss-america', 'roadside-oddities', 39.36231, -74.43961, 'Atlantic City', 'NJ', 'A bronze Bert Parks holds a Miss America crown overhead beside the convention-center complex, inviting visitors to stand beneath it for a mock crowning. The interactive sculpture commemorates the longtime pageant host and Atlantic City''s deep Miss America history.', 'open', 'https://www.roadsideamerica.com/location/map?mode=detail&id=21611', null, 'America/New_York', now()),
  ('Chicken Bone Beach Marker', 'chicken-bone-beach-marker', 'weird-history', 39.35417, -74.43611, 'Atlantic City', 'NJ', 'A historical marker identifies the stretch of Atlantic City beach that Black visitors were informally restricted to during segregation. The nickname came from the picnic food reportedly left behind by beachgoers; today the location is interpreted as an important piece of Jersey Shore civil-rights history.', 'open', 'https://www.atlasobscura.com/places/chicken-bone-beach', null, 'America/New_York', now()),
  ('Mount Mitchill 9/11 Memorial', 'mount-mitchill-9-11-memorial', 'weird-history', 40.40722, -74.00442, 'Atlantic Highlands', 'NJ', 'At New Jersey''s highest natural point on the Atlantic seaboard, a memorial overlooks the New York skyline and honors Monmouth County residents killed on September 11, 2001. Its centerpiece incorporates an eagle clutching a twisted steel beam recovered from the World Trade Center.', 'open', 'https://www.monmouthcountyparks.com/page.aspx?ID=2530', null, 'America/New_York', now()),
  ('The Bayville Dinosaur', 'the-bayville-dinosaur', 'roadside-oddities', 39.90932, -74.15487, 'Berkeley Township', 'NJ', 'A large old-school dinosaur statue stands beside Route 9 in Bayville, surviving decades of changing businesses around it. Its hand-built roadside-attraction look makes it feel like a leftover from an earlier era of highway tourism.', 'roadside', 'https://www.roadsideamerica.com/tip/11872', null, 'America/New_York', now()),
  ('Nitro Girl — Uniroyal SuperGal', 'nitro-girl-uniroyal-supergal', 'roadside-oddities', 39.82345, -75.06788, 'Blackwood', 'NJ', 'A towering fiberglass woman stands outside Werbany Tire Town, adapted from the classic Uniroyal Gal advertising figures once placed outside tire stores around the country. This surviving example has been repainted as ''Nitro Girl'' and remains visible from the Black Horse Pike.', 'roadside', 'https://www.roadsideamerica.com/tip/18893', null, 'America/New_York', now()),
  ('Angel in Anguish 9/11 Memorial', 'angel-in-anguish-9-11-memorial', 'weird-history', 40.05748, -74.11116, 'Brick Township', 'NJ', 'A bronze angel bends forward in grief as the central figure of Brick Township''s September 11 memorial. The emotionally direct sculpture is surrounded by names and memorial elements honoring township residents lost in the attacks.', 'open', 'https://www.roadsideamerica.com/tip/29739', null, 'America/New_York', now()),
  ('Big Golden Propeller — Merchant Marine Memorial', 'big-golden-propeller-merchant-marine-memorial', 'roadside-oddities', 39.9424, -75.13217, 'Camden', 'NJ', 'A huge polished ship propeller forms the centerpiece of Camden''s World War II American Merchant Marine Memorial. The unidentified propeller sits on the waterfront within sight of Battleship New Jersey and honors merchant mariners and Navy Armed Guard sailors who died at sea.', 'open', 'https://www.roadsideamerica.com/story/33801', null, 'America/New_York', now()),
  ('Cannonball in the Crosswicks Meeting House', 'cannonball-in-the-crosswicks-meeting-house', 'weird-history', 40.15185, -74.64712, 'Crosswicks', 'NJ', 'A Revolutionary War cannonball remains mortared into the second-story brick wall of the 1773 Crosswicks Friends Meeting House. Both British and American forces were exchanging fire in the area in June 1778, so exactly which side fired the embedded shot is uncertain.', 'roadside', 'https://www.roadsideamerica.com/story/33804', null, 'America/New_York', now()),
  ('Palisades Amusement Park Site', 'palisades-amusement-park-site', 'weird-history', 40.8281, -73.9778, 'Cliffside Park', 'NJ', 'Palisades Amusement Park operated above the Hudson River for generations before closing in 1971 and being replaced by high-rise development. A public memorial and historical marker preserve the location of the once-famous park, remembered for rides, music and its enormous saltwater pool.', 'open', 'https://www.roadsideamerica.com/tip/18383', null, 'America/New_York', now()),
  ('Lakota Wolf Preserve', 'lakota-wolf-preserve', 'roadside-oddities', 40.97093, -75.07223, 'Knowlton Township', 'NJ', 'Guided visits lead to observation areas overlooking packs of wolves, foxes, bobcats and other animals at this privately operated preserve near the Delaware Water Gap. Access is controlled by tour schedule and reservation rather than casual roaming through the property.', 'limited', 'https://www.lakotawolf.com/', null, 'America/New_York', now()),
  ('Camp Merritt Memorial Monument', 'camp-merritt-memorial-monument', 'weird-history', 40.94121, -73.97653, 'Cresskill', 'NJ', 'A 66-foot granite obelisk stands in a traffic circle near the center of the former Camp Merritt, the enormous World War I embarkation camp through which more than a million people passed. The monument especially remembers hundreds who died during the 1918 influenza epidemic.', 'open', 'https://www.cresskillboro.com/resident/history', null, 'America/New_York', now()),
  ('First Flight in America Marker', 'first-flight-in-america-marker', 'weird-history', 39.8411, -75.0913, 'Deptford Township', 'NJ', 'A public marker at Deptford Landing commemorates Jean-Pierre Blanchard''s 1793 balloon flight from Philadelphia to New Jersey, generally recognized as America''s first successful manned balloon flight. The original landing-site memorial behind the shopping center has become fenced and neglected, making the public marker the practical OddWay stop.', 'open', 'https://www.roadsideamerica.com/tip/39010', null, 'America/New_York', now()),
  ('20-Foot California Raisin', '20-foot-california-raisin', 'roadside-oddities', 39.36549, -74.59592, 'Egg Harbor Township', 'NJ', 'A giant purple California Raisin figure towers outside a roadside property on Zion Road, preserving one of the strangest physical remnants of the once-ubiquitous advertising characters. The oversized fiberglass figure is best viewed from the public roadside.', 'roadside', 'https://www.roadsideamerica.com/tip/22811', null, 'America/New_York', now()),
  ('Storybook Land', 'storybook-land', 'roadside-oddities', 39.42325, -74.59139, 'Egg Harbor Township', 'NJ', 'Opened in 1955, this family amusement park fills wooded grounds with three-dimensional scenes based on nursery rhymes and children''s stories. Its vintage fiberglass characters and storybook structures preserve the atmosphere of a classic mid-century roadside fairy-tale park.', 'limited', 'https://storybookland.com/', null, 'America/New_York', now()),
  ('Big Cow of Middlebush', 'big-cow-of-middlebush', 'roadside-oddities', 40.48465, -74.53236, 'Franklin Township', 'NJ', 'A large fiberglass dairy cow stands as a roadside reminder of the farmland that once dominated this part of Somerset County. The oversized bovine has survived development around it and remains a quick public-roadside photo stop.', 'roadside', 'https://www.roadsideamerica.com/tip/23718', null, 'America/New_York', now()),
  ('Zinc Miner Statue', 'zinc-miner-statue', 'roadside-oddities', 41.11331, -74.58838, 'Franklin', 'NJ', 'A bronze miner holding a pick stands near the Franklin Mineral Museum entrance, representing generations who worked the area''s exceptionally mineral-rich zinc deposits. The figure wears a carbide lamp and stands on a pile of rock as a memorial to Franklin''s mining workforce.', 'open', 'https://www.roadsideamerica.com/story/40021', null, 'America/New_York', now()),
  ('Greenwich Tea Burning Monument', 'greenwich-tea-burning-monument', 'weird-history', 39.38833, -75.33833, 'Greenwich Township', 'NJ', 'A monument commemorates the December 1774 Greenwich Tea Party, when local patriots destroyed a shipment of tea in protest against British taxation. The New Jersey action occurred after the more famous Boston Tea Party but remains an important regional Revolutionary-era protest.', 'open', 'https://www.hmdb.org/m.asp?m=22044', null, 'America/New_York', now()),
  ('Haddy the Hadrosaurus', 'haddy-the-hadrosaurus', 'roadside-oddities', 39.89706, -75.03437, 'Haddonfield', 'NJ', 'A life-size bronze Hadrosaurus foulkii stands downtown in honor of the dinosaur discovered nearby in 1858. Nicknamed Haddy, the sculpture gives Haddonfield a visible prehistoric mascot linked to one of the most important early dinosaur discoveries in North America.', 'open', 'https://www.atlasobscura.com/places/haddy-the-hadrosaurus', null, 'America/New_York', now()),
  ('Gingerbread Castle', 'gingerbread-castle', 'roadside-oddities', 41.14939, -74.57478, 'Hamburg', 'NJ', 'This elaborate fairy-tale castle was built in the 1920s as part of a children''s attraction associated with a local flour mill. Its towers, figures and storybook details survive, but public access has changed repeatedly; travelers should treat it as an exterior roadside landmark unless an official opening is advertised.', 'roadside', 'https://www.atlasobscura.com/places/gingerbread-castle', null, 'America/New_York', now()),
  ('Hancock House — Bayonet Massacre Site', 'hancock-house-bayonet-massacre-site', 'weird-history', 39.50807, -75.46029, 'Hancocks Bridge', 'NJ', 'British and Loyalist troops stormed this house in March 1778 and killed roughly two dozen people inside during the Hancock''s Bridge massacre. The preserved eighteenth-century building operates as a state historic site with limited tour hours.', 'limited', 'https://www.roadsideamerica.com/story/33807', null, 'America/New_York', now()),
  ('U.S. Army Parachute Test Platoon Monument', 'us-army-parachute-test-platoon-monument', 'weird-history', 40.25879, -74.54065, 'East Windsor Township', 'NJ', 'A small monument along Route 130 marks the former site of tall wooden parachute-training towers used by the Army''s experimental parachute test platoon in 1940. The towers disappeared long ago, but the marker preserves an obscure location from the birth of American airborne forces.', 'roadside', 'https://www.roadsideamerica.com/tip/41908', null, 'America/New_York', now()),
  ('Elaborate Grave of Singin'' Sam Stevens', 'elaborate-grave-of-singin-sam-stevens', 'weird-history', 40.68953, -74.21353, 'Hillside', 'NJ', 'Romani musician Singin'' Sam Stevens is memorialized with an extravagant black-granite monument featuring gold musical notes, a carved amplifier, electric guitar and oversized record. The grave sits inside Evergreen Cemetery, which has posted daily visiting hours.', 'limited', 'https://www.roadsideamerica.com/story/33809', null, 'America/New_York', now()),
  ('Frank Sinatra Birthplace Star', 'frank-sinatra-birthplace-star', 'weird-history', 40.74344, -74.0386, 'Hoboken', 'NJ', 'A sidewalk star marks 415 Monroe Street, where Frank Sinatra was born in 1915. The original house no longer survives, so the marker serves as the physical stop connecting Hoboken with the singer''s birthplace.', 'open', 'https://mapcarta.com/N5468067617', null, 'America/New_York', now()),
  ('Karl Jansky Radio Astronomy Monument', 'karl-jansky-radio-astronomy-monument', 'weird-history', 40.36514, -74.16357, 'Holmdel Township', 'NJ', 'A monument on the former Bell Labs property honors Karl Jansky, whose 1930s experiments detected radio waves from the Milky Way and helped create the field of radio astronomy. The stop connects an otherwise quiet corporate campus with a major scientific discovery.', 'open', 'https://www.atlasobscura.com/places/karl-jansky-monument', null, 'America/New_York', now()),
  ('Holmdel Horn Antenna', 'holmdel-horn-antenna', 'weird-history', 40.39072, -74.18484, 'Holmdel Township', 'NJ', 'This enormous horn-shaped radio antenna was used by Arno Penzias and Robert Wilson when they accidentally detected the cosmic microwave background, a key piece of evidence for the Big Bang. The National Historic Landmark survives on private property with access dependent on current site arrangements.', 'limited', 'https://www.atlasobscura.com/places/holmdel-horn-antenna', null, 'America/New_York', now()),
  ('United States War Dogs Memorial', 'united-states-war-dogs-memorial', 'weird-history', 40.38928, -74.17565, 'Holmdel Township', 'NJ', 'A bronze soldier and military dog stand together in a memorial dedicated to American war dogs and their handlers. The sculpture sits near the New Jersey Vietnam Veterans'' Memorial and honors animal teams used across multiple conflicts.', 'open', 'https://www.hmdb.org/m.asp?m=209032', null, 'America/New_York', now()),
  ('World''s Largest Transistor Monument', 'worlds-largest-transistor-monument', 'roadside-oddities', 40.372, -74.1597, 'Holmdel Township', 'NJ', 'The giant three-legged water tower at Bell Works was deliberately shaped like an early transistor, the revolutionary device invented at Bell Laboratories. Its saucer-like form makes the scientific tribute look more like a machine from a vintage alien-invasion film.', 'roadside', 'https://www.roadsideamerica.com/tip/8180', null, 'America/New_York', now()),
  ('Lakehurst Historical Society Museum', 'lakehurst-historical-society-museum', 'museums', 40.01306, -74.32028, 'Lakehurst', 'NJ', 'Inside a former Catholic church, this local museum packs together Hindenburg wreckage, airship artifacts, railroad history, a hand-carved Jersey Devil and ''Stuffy,'' a taxidermied dachshund whose damaged feet were fitted with little shoes. Public hours are limited.', 'limited', 'https://www.roadsideamerica.com/story/74973', null, 'America/New_York', now()),
  ('George Coryell''s Grave — Washington''s Pallbearer', 'george-coryells-grave-washingtons-pallbearer', 'weird-history', 40.36665, -74.94515, 'Lambertville', 'NJ', 'Revolutionary War officer George Coryell, later one of George Washington''s pallbearers, is buried beside the First Presbyterian Church in Lambertville. A historical marker identifies the small graveyard, which also contains Samuel Holcombe, remembered locally as one of Washington''s spies.', 'open', 'https://www.hmdb.org/m.asp?m=16861', null, 'America/New_York', now()),
  ('Quick Stop — Clerks Filming Location', 'quick-stop-clerks-filming-location', 'weird-history', 40.4152, -74.05712, 'Leonardo', 'NJ', 'The operating Quick Stop convenience store became a cult-film landmark after Kevin Smith shot much of the 1994 movie Clerks here. The familiar storefront remains recognizable to fans and continues to function as a normal neighborhood store.', 'open', 'https://www.atlasobscura.com/places/quick-stop-groceries', null, 'America/New_York', now()),
  ('Mercedes-Benz Tombstone', 'mercedes-benz-tombstone', 'weird-history', 40.63813, -74.23869, 'Linden', 'NJ', 'A black granite gravestone is carved into the unmistakable front end of a Mercedes-Benz, complete with grille and three-pointed star. The monument stands inside Rosedale and Rosehill Cemetery and turns an enthusiasm for luxury cars into unusually literal funerary art.', 'limited', 'https://www.roadsideamerica.com/tip/7740', null, 'America/New_York', now()),
  ('Yogi Berra Museum & Learning Center', 'yogi-berra-museum-learning-center', 'museums', 40.8684, -74.19456, 'Little Falls', 'NJ', 'This museum at Montclair State University preserves memorabilia from Yankees catcher Yogi Berra, including championship material, photographs and artifacts from his baseball career. Exhibits also examine Berra''s military service and the famous sayings associated with him.', 'limited', 'https://yogiberramuseum.org/', null, 'America/New_York', now()),
  ('Ultimate Frisbee Monument', 'ultimate-frisbee-monument', 'weird-history', 40.73151, -74.2769, 'Maplewood', 'NJ', 'A disc-shaped plaque mounted on a rock marks the parking lot where Columbia High School students developed the game that became Ultimate Frisbee in 1968. The small monument sits beside West Parker Avenue near the original playing area.', 'roadside', 'https://www.roadsideamerica.com/story/62666', null, 'America/New_York', now()),
  ('Hachi and Professor Ueno Statue', 'hachi-and-professor-ueno-statue', 'roadside-oddities', 41.09115, -74.7106, 'Lafayette Township', 'NJ', 'A life-size bronze replica shows the famously loyal Japanese Akita Hachiko joyfully reunited with Professor Hidesaburo Ueno. Installed at Abbey Glen Pet Memorial Park in 2016, it reproduces the paired statue created for the University of Tokyo.', 'open', 'https://www.roadsideamerica.com/story/55089', null, 'America/New_York', now()),
  ('Hubcap Pyramid', 'hubcap-pyramid', 'roadside-oddities', 39.45024, -74.70419, 'Mays Landing', 'NJ', 'Hundreds of shiny hubcaps are stacked into a large pyramid outside a long-running hubcap business on the Black Horse Pike. The reflective roadside structure turns an ordinary pile of automotive parts into a deliberately oversized advertising landmark.', 'roadside', 'https://www.roadsideamerica.com/tip/13914', null, 'America/New_York', now()),
  ('Three Stooges Tombstone', 'three-stooges-tombstone', 'weird-history', 40.53669, -74.36175, 'Metuchen', 'NJ', 'Firefighter James Bechtold''s gravestone features Moe, Larry and Curly looking down from the stone above the message ''Laugh, Don''t Weep — It Feels Better!'' The personalized memorial stands in Hillside Cemetery and should be visited respectfully during cemetery hours.', 'limited', 'https://www.roadsideamerica.com/tip/33275', null, 'America/New_York', now()),
  ('Colossal Head of Franklin D. Roosevelt', 'colossal-head-of-franklin-d-roosevelt', 'roadside-oddities', 40.22062, -74.47366, 'Roosevelt', 'NJ', 'A monumental sculpted head of Franklin D. Roosevelt sits in a wooded amphitheater in the town renamed for him. Roosevelt began as a New Deal resettlement community, making the enormous presidential head both civic monument and unusual roadside art.', 'open', 'https://www.roadsideamerica.com/tip/7845', null, 'America/New_York', now()),
  ('Radium Girls Memorial Park', 'radium-girls-memorial-park', 'weird-history', 40.78172, -74.22713, 'Orange', 'NJ', 'A public park and memorial stand near the former U.S. Radium Corporation site where women painted luminous watch dials with radioactive radium paint. Their illnesses and legal battle became a major turning point in occupational-safety history.', 'open', 'https://www.atlasobscura.com/places/us-radium-corporation-site', null, 'America/New_York', now()),
  ('Light Bulb Grave of the World''s Greatest Electrician', 'light-bulb-grave-of-the-worlds-greatest-electrician', 'weird-history', 40.89855, -74.20772, 'Totowa', 'NJ', 'Electrician Sal Giardino''s four-foot black granite tombstone is shaped like an incandescent bulb and includes lightning bolts, an electrical outlet and the words ''World''s Greatest Electrician.'' It stands inside Laurel Grove Cemetery, which maintains posted visiting hours.', 'limited', 'https://www.roadsideamerica.com/story/28572', null, 'America/New_York', now()),
  ('Weehawken Dueling Grounds', 'weehawken-dueling-grounds', 'weird-history', 40.7708, -74.0168, 'Weehawken', 'NJ', 'A monument and stone mark the Palisades area associated with the 1804 duel in which Aaron Burr mortally wounded Alexander Hamilton. The exact historical firing spot is debated, but the public memorial preserves the location traditionally connected with the famous encounter.', 'open', 'https://www.atlasobscura.com/places/weehawken-dueling-grounds', null, 'America/New_York', now()),
  ('Kip''s Castle', 'kips-castle', 'roadside-oddities', 40.82866, -74.22446, 'Verona', 'NJ', 'A turreted early twentieth-century mansion modeled loosely on a medieval Norman castle rises above the surrounding suburbs. Essex County now operates the estate as a public cultural site, with interior access tied to tours and scheduled programs.', 'limited', 'https://www.essexcountyparks.org/parks/kips-castle', null, 'America/New_York', now()),
  ('Willingboro Futuro House', 'willingboro-futuro-house', 'roadside-oddities', 40.0269, -74.90915, 'Willingboro', 'NJ', 'A rare Futuro House—Matti Suuronen''s 1960s prefabricated flying-saucer-shaped building—survives beside Beverly Rancocas Road. The fiberglass pod is one of only a limited number of Futuros still known to exist and should be viewed from public areas.', 'roadside', 'https://thefuturohouse.com/Futuro-Willingboro-New-Jersey-USA.html', null, 'America/New_York', now()),
  ('Union Watersphere', 'union-watersphere', 'roadside-oddities', 40.69327, -74.26205, 'Union Township', 'NJ', 'A spherical water tank perched on an exceptionally tall narrow column rises more than 200 feet beside major highways in Union. Long promoted as the world''s tallest watersphere, the peculiar tower looks like a giant white ball balanced on a stick.', 'roadside', 'https://www.roadsideamerica.com/tip/896', null, 'America/New_York', now()),
  ('Pizzaland — The Sopranos Opening-Credits Pizzeria', 'pizzaland-the-sopranos-opening-credits-pizzeria', 'weird-history', 40.78165, -74.138, 'North Arlington', 'NJ', 'This small pizzeria appears in the opening credits of The Sopranos as Tony Soprano drives through North Jersey. Pizzaland remains an operating restaurant at the same location, making it a straightforward stop for fans of the series.', 'open', 'https://sirstoria.com/locations/new-jersey/north-arlington/sopranos-pizza-land', null, 'America/New_York', now()),
  ('Smiley Face Water Tower', 'smiley-face-water-tower-longport', 'roadside-oddities', 39.31637, -74.52206, 'Longport', 'NJ', 'Longport''s blue municipal water tower wears an enormous smiling face visible above the barrier-island houses. The town restored the cheerful design after tower repairs, preserving one of the Jersey Shore''s friendliest pieces of infrastructure.', 'roadside', 'https://fotospot.com/attractions/new-jersey/smiley-face-water-tower', null, 'America/New_York', now()),
  ('Frank Sinatra in Bronze', 'frank-sinatra-in-bronze', 'roadside-oddities', 40.73718, -74.02641, 'Hoboken', 'NJ', 'A life-size bronze Frank Sinatra leans casually against a lamppost on the Hoboken waterfront, microphone in hand and overlooking Manhattan. The sculpture provides a second, visually distinct Sinatra stop separate from the marker at his birthplace.', 'open', 'https://www.roadsideamerica.com/location/map?mode=detail&id=83543', null, 'America/New_York', now()),
  ('Springsteen ''Born to Run'' House', 'springsteen-born-to-run-house', 'weird-history', 40.29931, -73.99323, 'Long Branch', 'NJ', 'The modest house at 7½ West End Court is closely associated with Bruce Springsteen''s mid-1970s period and the creation of Born to Run. It remains a private residence rather than a museum, so OddWay travelers should only view it from the public street without disturbing occupants.', 'private', 'https://www.roadsideamerica.com/location/map?mode=detail&id=28887', null, 'America/New_York', now()),
  ('The Garfield Tea House', 'the-garfield-tea-house', 'weird-history', 40.26643, -73.99708, 'Long Branch', 'NJ', 'A small structure in Church of the Presidents park was built using railroad ties from the emergency rail spur constructed to carry wounded President James A. Garfield to the shore in 1881. Garfield died nearby after the assassination attempt, leaving this unusual reuse of the temporary railroad as a memorial.', 'open', 'https://www.roadsideamerica.com/location/map?mode=detail&id=22598', null, 'America/New_York', now()),
  ('Frank and Buddy — Seeing Eye Dog Statue', 'frank-and-buddy-seeing-eye-dog-statue', 'roadside-oddities', 40.79762, -74.4815, 'Morristown', 'NJ', 'A bronze man and German shepherd commemorate Morris Frank and Buddy, whose partnership helped establish The Seeing Eye in Morristown and popularize guide dogs in the United States. The public sculpture captures Frank walking confidently with Buddy at his side.', 'open', 'https://www.roadsideamerica.com/location/map?mode=detail&id=48333', null, 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;

select count(*) as new_jersey from public.stops where state = 'NJ';
