-- New York, second batch.
--
-- Two collections of markers, and it is worth knowing which is which.
--
-- The Legends and Lore markers come from the William G. Pomeroy Foundation,
-- which pays for cast-metal signs at folklore sites. That is why a hoop snake,
-- a giant turtle and a séance that located a mineral spring all have precise
-- coordinates: somebody already decided where each story happens and bolted a
-- sign to the ground there.
--
-- The rest come from the Haunted History Trail of New York State, a tourism
-- programme, so those are working museums and historic houses with scheduled
-- paranormal programming rather than roadside curiosities.
--
-- Checked against the whole index: no slug collisions, and the only nearby
-- existing stop is Doctor Morbid's Haunted House, 109 metres from the Lake
-- George Mystery Spot and an entirely different thing.
--
-- 32 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone, verified_at)
values
  ('Hairy Women of Klipnocky Marker', 'hairy-women-of-klipnocky-marker', 'cryptids', 42.4277, -77.80109, 'Canaseraga', 'NY', 'Local legend says two girls disappeared into the Klipnocky forest after being told to hide there for safety and were later reported as large, hairy women living in the woods. The story was in circulation by the 1920s, and today a Legends & Lore marker on County Route 13C gives travelers a specific public-road stop tied to the tale.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/a-hairy-legend/', 'America/New_York', now()),
  ('Gorton Turtle Marker', 'gorton-turtle-marker', 'folklore', 42.86158, -75.352, 'West Edmeston', 'NY', 'A Brookfield-area tall tale tells of a turtle larger than a cottage emerging from Gorton Lake and dragging an impossibly heavy wagon of rocks into the water. A Legends & Lore marker on Gorton Lake Road preserves the story at a specific roadside location.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/gorton-turtle/', 'America/New_York', now()),
  ('Hoop Snake Hill Marker', 'hoop-snake-hill-marker', 'cryptids', 41.27935, -74.29825, 'Chester', 'NY', 'Generations of Warwick-area folklore describe an enormous snake that grabs its own tail, forms a hoop and rolls downhill toward its victims before striking with a spiked tail. The legend now has a dedicated marker overlooking the area associated with the creature.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/hoop-snake-hill/', 'America/New_York', now()),
  ('Franklin Spring Marker', 'franklin-spring-marker', 'folklore', 43.00845, -73.8436, 'Ballston Spa', 'NY', 'In 1869, Spiritualist Samuel Hides said a séance message from the spirit of Benjamin Franklin told him exactly where to drill for a healing mineral spring. A spring was struck at the predicted depth, and the story became part of Ballston Spa folklore; a Legends & Lore marker now identifies the site.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/franklin-spring/', 'America/New_York', now()),
  ('Pink Hill Ghost Marker', 'pink-hill-ghost-marker', 'haunted', 42.58108, -75.86414, 'Pitcher', 'NY', 'Local legend says Zella Droff was murdered after secretly attending dances at the former Pitcher Hotel, then returned years later as a ghost who accepted a ride from an unsuspecting salesman. A Legends & Lore marker on Pitcher Hill Road marks the area associated with the story.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/pink-hill-legend/', 'America/New_York', now()),
  ('Dave Push Ghost at Haviland-Davison Mill', 'dave-push-ghost-at-haviland-davison-mill', 'haunted', 40.63976, -73.65954, 'East Rockaway', 'NY', 'Local boatman David "Dave Push" Terrell was found dead in the water in 1910, and folklore says his spirit later haunted the Haviland-Davison Mill. The historic mill was moved to Memorial Park in 1963 and is now a museum, with a Legends & Lore marker preserving the ghost story.', 'open', 'https://www.wgpfoundation.org/historic-markers/dave-push/', 'America/New_York', now()),
  ('The Leatherman Grave and Marker', 'the-leatherman-grave-and-marker', 'weird-history', 41.1369, -73.86219, 'Ossining', 'NY', 'The mysterious wanderer known as the Leatherman repeatedly walked a roughly 365-mile circuit through New York and Connecticut in the 1880s while wearing a handmade suit of heavy leather. He died in 1889 and is buried in Ossining, where a Legends & Lore marker records one of New York''s strangest real-life folk figures.', 'open', 'https://www.wgpfoundation.org/historic-markers/the-leatherman/', 'America/New_York', now()),
  ('The Lewis Giant Marker', 'the-lewis-giant-marker', 'folklore', 44.2772, -73.56462, 'Lewis', 'NY', 'Joseph Call was a real nineteenth-century wrestler, logger and millwright whose unusual size and strength inspired stories of superhuman feats. Known as the Lewis Giant or the Paul Bunyan of the East, he is commemorated by a Legends & Lore marker along U.S. Route 9.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/the-lewis-giant/', 'America/New_York', now()),
  ('Haeger''s Vision Marker', 'haegers-vision-marker', 'folklore', 42.14329, -73.88886, 'Germantown', 'NY', 'According to local tradition, Rev. Johann Frederick Haeger was visited on Christmas Eve 1720 by a spirit calling itself the "Master of Time and Space." The spirit supposedly showed him visions of Germantown''s future, and a Legends & Lore marker now identifies the location tied to the story.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/haegers-vision/', 'America/New_York', now()),
  ('Cat Rocks Treasure Marker', 'cat-rocks-treasure-marker', 'folklore', 41.2454, -74.28533, 'Southfields', 'NY', 'Local legend says Revolutionary War loyalist and outlaw Claudius Smith hid stolen valuables inside caves at nearby Cat Rocks before his capture and execution. Treasure hunters have searched for the supposed cache for generations, and a Legends & Lore marker along Route 17 records the story; do not leave public access areas to hunt for it.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/cat-rocks-treasure/', 'America/New_York', now()),
  ('Nathaniel Knapp Bear Fight Marker', 'nathaniel-knapp-bear-fight-marker', 'folklore', 41.32864, -74.27994, 'Chester', 'NY', 'Local legend says Nathaniel Knapp killed a bear here around 1750 using only a knife and later asked to be buried at the site. The marker stands at Knapp''s View, a public passive park with walking and picnic access, though no confirmed grave marker for Knapp survives.', 'open', 'https://www.wgpfoundation.org/historic-markers/nathaniel-knapp/', 'America/New_York', now()),
  ('New Hope''s Sodom Renaming Marker', 'new-hopes-sodom-renaming-marker', 'weird-history', 42.7979, -76.34678, 'Moravia', 'NY', 'This hamlet was once known as Sodom until, according to local lore, a man climbed the ridgepole of a new gristmill in 1823 with a jug of whiskey and proclaimed that the struggling village had "new hope." The story of the unusual christening is now preserved on a Legends & Lore marker along NY-41A.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/new-hope-named/', 'America/New_York', now()),
  ('Jacob Conklin Pirate Legend Marker', 'jacob-conklin-pirate-legend-marker', 'folklore', 40.75868, -73.38299, 'Wheatley Heights', 'NY', 'Long Island legend says Jacob Conklin sailed with Captain William Kidd before building a home in this area around 1710. The house burned in 1918, but a Legends & Lore marker on Colonial Springs Road preserves the local pirate connection.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/jacob-conklin/', 'America/New_York', now()),
  ('Smith''s Bull Ride Marker', 'smiths-bull-ride-marker', 'folklore', 40.8585, -73.2124, 'Smithtown', 'NY', 'Smithtown folklore claims founder Richard Smith received as much land as he could circle in a single day while riding a bull after helping return a kidnapped daughter to a Montauk leader. Historical deeds make the tale doubtful, but it remains central to the town''s identity and is commemorated by both a marker and the famous Whisper the Bull statue nearby.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/smiths-bull-ride/', 'America/New_York', now()),
  ('Lake George Mystery Spot', 'lake-george-mystery-spot', 'roadside-oddities', 43.42263, -73.713, 'Lake George', 'NY', 'Stand on the marked X behind the Lake George Visitor Center and speak toward the lake; your voice returns as a strange focused echo that people standing only a few feet away may not hear the same way. The free public spot has accumulated both acoustic explanations and supernatural folklore and remains physically marked in Blais Park.', 'open', 'https://www.lakegeorge.com/guides/things-to-do/mystery-spot/', 'America/New_York', now()),
  ('The Haunted Hinsdale House', 'the-haunted-hinsdale-house', 'haunted', 42.16731, -78.34226, 'Hinsdale', 'NY', 'The Dandy family reported lights switching on by themselves, chanting from the woods and apparitions after moving into this McMahon Road house in the early 1970s, eventually seeking an exorcism. The property is now a paranormal research site offering scheduled day tours, ghost tours and overnight investigations rather than ordinary walk-in access.', 'limited', 'https://hauntedhistorytrail.com/explore/the-haunted-hinsdale-house', 'America/New_York', now()),
  ('Wildwood Sanitarium', 'wildwood-sanitarium', 'haunted', 42.15829, -78.6924, 'Salamanca', 'NY', 'Wildwood opened in 1906 as a sanitarium and bath house and later served as a tuberculosis clinic and apartments. Visitors and investigators report shadow figures, voices and unexplained physical contact, and the restored property now offers history tours, ghost tours and investigations by reservation.', 'limited', 'https://hauntedhistorytrail.com/explore/wildwood-sanitarium', 'America/New_York', now()),
  ('Fox Sisters Property / Hydesville Memorial Park', 'fox-sisters-property-hydesville-memorial-park', 'haunted', 43.0705, -77.10768, 'Newark', 'NY', 'Maggie and Kate Fox reported mysterious rapping sounds here in 1848 and became central figures in the rise of modern Spiritualism. The original cottage is gone but its foundation remains inside Hydesville Memorial Park; the park itself is open to visitors while access to the enclosure and guided interpretation may require the caretaker.', 'limited', 'https://hauntedhistorytrail.com/explore/the-fox-sisters-propertyhydesville-memorial-park', 'America/New_York', now()),
  ('Hyde Hall', 'hyde-hall', 'haunted', 42.79231, -74.87513, 'Cooperstown', 'NY', 'This large early-nineteenth-century mansion overlooking Otsego Lake has more than a century of stories involving footsteps, whispers, phantom knocking and apparitions. Hyde Hall operates seasonal historic tours and scheduled haunted programming, including candlelit ghost tours in the fall.', 'limited', 'https://hauntedhistorytrail.com/explore/hyde-hall', 'America/New_York', now()),
  ('Phelps Mansion Museum', 'phelps-mansion-museum', 'haunted', 42.10068, -75.90556, 'Binghamton', 'NY', 'Built beginning in 1870 for businessman and former Binghamton mayor Sherman D. Phelps, the mansion is associated with reports of period-dressed apparitions, unexplained footsteps, moving objects and a clock chiming without being wound. It is now a public museum with regular tours, while dedicated haunted tours and paranormal investigations are offered on scheduled dates or by reservation.', 'open', 'https://hauntedhistorytrail.com/explore/phelps-mansion-museum', 'America/New_York', now()),
  ('Casey''s Cottage at Mexico Point', 'caseys-cottage-at-mexico-point', 'haunted', 43.51968, -76.25514, 'Mexico', 'NY', 'Dr. William Casey transformed this former carriage house into an elaborate medieval-style cottage before his death in 1978. Later visitors reported organ music, cries for help, moving furniture and the apparition of a young girl; tours, ghost hunts and investigations are arranged by reservation at Mexico Point State Park.', 'limited', 'https://hauntedhistorytrail.com/explore/caseys-cottage-at-mexico-point-state-park', 'America/New_York', now()),
  ('Dunkirk Lighthouse', 'dunkirk-lighthouse', 'haunted', 42.4936, -79.3537, 'Dunkirk', 'NY', 'The Dunkirk light station dates to 1827, with the present Victorian keeper''s house and tower preserving maritime and military history along Lake Erie. Reports include footsteps, voices, humming and unexplained touches inside the keeper''s house and tower; the site operates as a museum and also schedules paranormal investigations.', 'open', 'https://hauntedhistorytrail.com/explore/dunkirk-historical-lighthouse-veterans-park-museum', 'America/New_York', now()),
  ('Historic Bundy House', 'historic-bundy-house', 'haunted', 42.10164, -75.92793, 'Binghamton', 'NY', 'Built in the 1890s for clock manufacturer Harlow Bundy, this Victorian house is now a museum and a recurring stop for paranormal investigators. Visitors have reported footsteps, voices and other unexplained activity, and the museum hosts scheduled ghost tours and investigations in addition to regular public hours.', 'open', 'https://hauntedhistorytrail.com/explore/the-historic-bundy-house', 'America/New_York', now()),
  ('Roberson Mansion', 'roberson-mansion', 'haunted', 42.094, -75.91866, 'Binghamton', 'NY', 'This Italian Renaissance-style mansion was completed in 1907 for Alonzo and Margaret Roberson and is now part of the Roberson Museum and Science Center. Staff and visitors have reported unexplained footsteps, voices and the sensation of unseen people in the house, while the mansion remains accessible through the museum and occasional ghost programs.', 'open', 'https://hauntedhistorytrail.com/explore/roberson-mansion', 'America/New_York', now()),
  ('Erie Canal Museum', 'erie-canal-museum', 'haunted', 43.05065, -76.14872, 'Syracuse', 'NY', 'The museum occupies Syracuse''s 1850 Weighlock Building, the only surviving canal weighlock structure of its kind. Stories associated with the building include apparitions, footsteps and voices, while visitors can normally explore the canal exhibits during regular museum hours.', 'open', 'https://hauntedhistorytrail.com/explore/erie-canal-museum', 'America/New_York', now()),
  ('Landmark Theatre', 'landmark-theatre', 'haunted', 43.04731, -76.15261, 'Syracuse', 'NY', 'The ornate theater opened in 1928 and has developed a long-running ghost story involving a woman named Clarissa, said to have fallen to her death and later appeared inside the building wearing white. It remains an active performance venue, with behind-the-scenes tours and paranormal investigations offered on selected dates or by arrangement.', 'open', 'https://hauntedhistorytrail.com/explore/the-landmark-theatre', 'America/New_York', now()),
  ('The 1890 House Museum', 'the-1890-house-museum', 'haunted', 42.59614, -76.18222, 'Cortland', 'NY', 'This elaborate stone mansion was built for industrialist Chester Wickwire and his family in 1890. Reports of footsteps, shadows, knocking and figures in the windows have made it a local paranormal destination; the museum operates seasonally and also offers scheduled ghost-hunting events and private investigations.', 'limited', 'https://hauntedhistorytrail.com/explore/the-1890-house-museum', 'America/New_York', now()),
  ('Old Stone Fort Museum', 'old-stone-fort-museum', 'haunted', 42.67773, -74.30214, 'Schoharie', 'NY', 'Originally built as a church in 1772, the stone structure was fortified during the Revolutionary War and attacked in 1780. Visitors and investigators have reported apparitions, footsteps, screams and other unexplained activity; the museum is seasonal, with special paranormal programs and ghost hunts offered on selected dates.', 'limited', 'https://hauntedhistorytrail.com/explore/old-stone-fort-museum', 'America/New_York', now()),
  ('Montgomery County Old Courthouse', 'montgomery-county-old-courthouse', 'haunted', 42.95294, -74.37553, 'Fonda', 'NY', 'Built in 1836, this courthouse witnessed generations of criminal trials and executions and now houses county historical records on its first floor. Paranormal reports include unexplained footsteps, voices, falling books and an apparition described as a woman in blue, while the public can visit during normal county history and archives hours.', 'open', 'https://hauntedhistorytrail.com/explore/montgomery-county-old-courthouse', 'America/New_York', now()),
  ('Kilmer Mansion', 'kilmer-mansion', 'haunted', 42.09264, -75.92122, 'Binghamton', 'NY', 'Built in 1898 for the family behind the patent-medicine company that produced Swamp Root, Kilmer Mansion has accumulated reports of voices, footsteps, lights switching on and unexplained touches. The restored mansion opens for scheduled tours, events and paranormal programs rather than unrestricted daily access.', 'limited', 'https://hauntedhistorytrail.com/explore/kilmer-mansion', 'America/New_York', now()),
  ('Mile Marker No. 30', 'mile-marker-no-30', 'folklore', 41.155, -72.24116, 'Cutchogue', 'NY', 'Long Island tradition claimed Benjamin Franklin personally placed this stone mileage marker while serving as colonial postmaster in the 1750s. Later research indicates the marker was probably installed in the early nineteenth century, but the Franklin story endured for generations and is now explained by a Legends & Lore marker beside Route 25.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/mile-marker-30/', 'America/New_York', now()),
  ('John Quincy Adams Summer Home Legend Marker', 'john-quincy-adams-summer-home-legend-marker', 'folklore', 40.76154, -73.33565, 'Deer Park', 'NY', 'For decades, local stories claimed President John Quincy Adams once owned a summer home in Deer Park. Research instead traced the property to a different John Quincy Adams, a clergyman who owned land here in the nineteenth century, and a Legends & Lore marker now explains how the presidential connection became local folklore.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/john-quincy-adams/', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  verified_at   = excluded.verified_at;
