-- New York, third batch.
--
-- World's Largest Kaleidoscope is excluded: it is the Kaatskill Kaleidoscope
-- we already hold, 600 metres from the stored position. That is just outside
-- the coordinate check's radius, so only the slug check caught it — the exact
-- reverse of the horseshoe crab, which only the coordinate check would have
-- caught. Neither check alone is sufficient, which is the reason to run both.
--
-- The two House of Frankenstein flags are the Lake George tourist strip: three
-- unrelated attractions within 200 metres of each other.
--
-- Several here are genuinely restricted rather than merely ticketed. Hart
-- Island is the city's public burial ground and visits are arranged through
-- the Parks Department; North Brother Island is closed to the public entirely.
-- Both are 'limited' or 'closed' for real reasons rather than opening hours.
--
-- 49 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone, verified_at)
values
  ('Eternal Flame Falls', 'eternal-flame-falls', 'roadside-oddities', 42.70158, -78.75113, 'Orchard Park', 'NY', 'A natural gas seep burns inside a small grotto behind this waterfall in Chestnut Ridge Park, creating the strange sight of fire flickering through falling water. Reaching the flame requires a wooded hike and a walk along Shale Creek, and muddy or wet conditions are common.', 'limited', 'https://www3.erie.gov/parks/chestnut-ridge', 'America/New_York', now()),
  ('Panama Rocks', 'panama-rocks', 'roadside-oddities', 42.07322, -79.48881, 'Panama', 'NY', 'Towering conglomerate formations create narrow passageways, caves and crevices through an old-growth forest at this privately operated park. The one-mile rock trail is open seasonally with paid admission, and visitors can walk directly among the formations rather than viewing them from a distance.', 'limited', 'https://www.panamarocks.com/visitforday.html', 'America/New_York', now()),
  ('Griffis Sculpture Park', 'griffis-sculpture-park', 'roadside-oddities', 42.36938, -78.69151, 'East Otto', 'NY', 'More than 250 large-scale sculptures are scattered through fields, forests and ponds across one of the oldest outdoor sculpture parks in the country. The main Mill Valley Road section is generally open from May through October and involves walking trails over varied terrain.', 'limited', 'https://griffissculpturepark.org/', 'America/New_York', now()),
  ('Original American Kazoo Company Museum', 'original-american-kazoo-company-museum', 'museums', 42.64911, -78.89839, 'Eden', 'NY', 'The Original American Kazoo Company began producing metal kazoos here in 1916, and the surviving factory now includes a small museum packed with historic kazoos and production equipment. Visitors can see how the instruments are made and, on operating days, make a kazoo of their own.', 'open', 'https://www.edenkazoo.com/museum.php', 'America/New_York', now()),
  ('Jell-O Gallery Museum', 'jell-o-gallery-museum', 'museums', 42.97885, -77.98569, 'Le Roy', 'NY', 'Jell-O was developed in Le Roy in 1897, and this museum preserves advertising, packaging, recipes and artifacts from the dessert''s unusually successful history. The gallery operates seasonally from spring until shortly before Christmas, so check its current schedule before routing here.', 'limited', 'https://leroyhistoricalsociety.org/visit-us/', 'America/New_York', now()),
  ('Lily Dale Museum', 'lily-dale-museum', 'museums', 42.35302, -79.3231, 'Lily Dale', 'NY', 'Lily Dale has operated as a Spiritualist community since the nineteenth century, and its museum occupies a former schoolhouse filled with photographs, documents and artifacts from generations of mediums and séances. Access is tied to the Lily Dale grounds and its seasonal programming, with a gate fee required during the summer season.', 'limited', 'https://www.lilydaleassembly.org/pointsofinterest', 'America/New_York', now()),
  ('Mmuseumm', 'mmuseumm', 'museums', 40.71736, -74.00282, 'New York', 'NY', 'Mmuseumm is a tiny cabinet-of-curiosities museum built inside a former freight elevator in a Tribeca alley. Its displays focus on overlooked everyday objects and contemporary artifacts, and the interior has very limited seasonal hours even though the exhibits can often be viewed through the windows from the alley.', 'limited', 'https://mmuseumm.com/', 'America/New_York', now()),
  ('Buffalo Central Terminal', 'buffalo-central-terminal', 'weird-history', 42.88965, -78.83024, 'Buffalo', 'NY', 'This enormous Art Deco railway terminal opened in 1929 and was abandoned by passenger trains in 1979, leaving its tower and concourse as one of Buffalo''s most imposing industrial-era landmarks. Interior historic tours are currently suspended during restoration work, but an official self-guided outdoor audio tour follows designated exterior paths.', 'limited', 'https://buffalocentralterminal.org/tours/', 'America/New_York', now()),
  ('Richardson Olmsted Campus', 'richardson-olmsted-campus', 'weird-history', 42.93001, -78.88258, 'Buffalo', 'NY', 'H.H. Richardson designed this monumental complex as the Buffalo State Asylum for the Insane, with Frederick Law Olmsted and Calvert Vaux shaping the grounds around it. The grounds remain accessible and scheduled seasonal tours enter portions of the restored complex, while other former hospital buildings are not open for exploration.', 'limited', 'https://richardson-olmsted.com/', 'America/New_York', now()),
  ('The Bone Museum', 'the-bone-museum', 'museums', 40.70589, -73.93718, 'Brooklyn', 'NY', 'This Brooklyn museum displays a large educational collection of real human skeletal material, including unusual pathologies, traumatic injuries and what it describes as the world''s largest public collection of human spines. It operates as a ticketed museum inside the McKibbin Lofts during posted Wednesday-through-Sunday hours.', 'open', 'https://www.thebonemuseum.org/', 'America/New_York', now()),
  ('Goodleburg Cemetery', 'goodleburg-cemetery', 'haunted', 42.71406, -78.53754, 'Wales', 'NY', 'This inactive town-owned cemetery dates to 1811 and became notorious in the late twentieth century for stories of apparitions and other paranormal activity. Ghost hunters also caused serious vandalism here, so visit only during lawful cemetery access, remain within the grounds and treat the surviving graves with particular care.', 'open', 'https://en.wikipedia.org/wiki/Goodleburg_Cemetery', 'America/New_York', now()),
  ('Barcelona Lighthouse', 'barcelona-lighthouse', 'weird-history', 42.3411, -79.59483, 'Westfield', 'NY', 'Completed in 1829, Barcelona Lighthouse is recognized as the world''s first lighthouse powered by natural gas. The grounds are open year-round and the restored tower can be climbed during staffed seasonal hours when weather and staffing permit.', 'open', 'https://staffportal.parks.ny.gov/parks/196/details.aspx', 'America/New_York', now()),
  ('Schoellkopf Power Station Ruins', 'schoellkopf-power-station-ruins', 'weird-history', 43.0928, -79.06283, 'Niagara Falls', 'NY', 'The Schoellkopf complex was once the world''s largest hydroelectric power station before a catastrophic rockslide and collapse destroyed most of it in 1956. A seasonal elevator at Niagara Falls State Park now carries visitors into the gorge, where surviving walls and industrial remnants can be seen along the official ruins trail.', 'limited', 'https://www.niagarafallsstatepark.com/attractions/schoellkopf-power-station-ruins-site/', 'America/New_York', now()),
  ('Seneca White Deer at Deer Haven Park', 'seneca-white-deer-at-deer-haven-park', 'roadside-oddities', 42.74418, -76.86922, 'Romulus', 'NY', 'The fenced former Seneca Army Depot became home to the world''s largest known herd of all-white white-tailed deer, descended from animals protected inside the military property for decades. Deer Haven Park now runs seasonal driving and bus tours through the old depot, combining the unusual herd with abandoned ammunition igloos and Cold War history.', 'limited', 'https://deerhavenpark.org/', 'America/New_York', now()),
  ('Oneida Community Mansion House', 'oneida-community-mansion-house', 'weird-history', 43.06034, -75.60462, 'Oneida', 'NY', 'Nearly 300 members of the radical Oneida Community once lived communally in this enormous mansion while practicing group marriage, communal child rearing and religious Perfectionism. The 93,000-square-foot building survives as a museum, inn and residence with daily self-guided museum access and scheduled deeper tours.', 'open', 'https://www.oneidacommunity.org/our-history', 'America/New_York', now()),
  ('Salt Museum', 'salt-museum', 'museums', 43.10002, -76.20705, 'Liverpool', 'NY', 'Built beside Onondaga Lake in 1933, this small museum preserves the story of the salt industry that gave nearby Syracuse its nickname, the Salt City. Exhibits explain brine wells, boiling blocks and salt production, with free public hours running seasonally from May into October.', 'limited', 'https://onondagacountyparks.com/parks/onondaga-lake-park/salt-museum/', 'America/New_York', now()),
  ('National Bottle Museum', 'national-bottle-museum', 'museums', 43.00312, -73.84872, 'Ballston Spa', 'NY', 'The National Bottle Museum treats bottle making as America''s first major industry and fills its galleries with historic bottles, molds, tools and glassmaking equipment. It is open year-round on posted Wednesday-through-Saturday hours and also maintains a research collection devoted to historic glass.', 'open', 'https://nationalbottlemuseum.org/', 'America/New_York', now()),
  ('Howe Caverns', 'howe-caverns', 'roadside-oddities', 42.69624, -74.39852, 'Howes Cave', 'NY', 'Howe Caverns takes visitors deep underground through limestone passages, enormous chambers and an underground lake first explored commercially in the nineteenth century. The cave operates as a guided attraction with scheduled tours from its Discovery Drive visitor complex.', 'open', 'https://howecaverns.com/', 'America/New_York', now()),
  ('Secret Caverns', 'secret-caverns', 'roadside-oddities', 42.70934, -74.39185, 'Howes Cave', 'NY', 'Secret Caverns is a deliberately old-school show cave reached by descending 103 steps into a winding underground passage. The guided route ends at a roughly 100-foot underground waterfall, and the attraction is open daily during its 2026 season.', 'open', 'https://secretcaverns.com/', 'America/New_York', now()),
  ('Herkimer Diamond Mines', 'herkimer-diamond-mines', 'roadside-oddities', 43.12871, -74.97665, 'Newport', 'NY', 'Visitors break apart exposed dolostone to search for naturally double-terminated quartz crystals known as Herkimer diamonds, which formed roughly 500 million years ago. The fee-dig surface mine operates seasonally and provides basic tools and instruction, with anything found by visitors theirs to keep.', 'limited', 'https://herkimerdiamond.com/mine/', 'America/New_York', now()),
  ('Cross Island Chapel', 'cross-island-chapel', 'roadside-oddities', 43.0995, -75.6374, 'Oneida', 'NY', 'Built in 1989 on a tiny platform in the middle of Mason''s Pond, Cross Island Chapel measures only about 28 square feet and has been promoted as the world''s smallest church. The chapel is reached by boat for private ceremonies, but ordinary travelers should view it from the public roadside rather than attempting to cross the pond.', 'roadside', 'https://www.oneidacityny.gov/sites/default/files/fileattachments/community/page/3217/may_newsletter.pdf', 'America/New_York', now()),
  ('The Tepee', 'the-tepee', 'roadside-oddities', 42.80784, -74.68453, 'Cherry Valley', 'NY', 'This giant concrete-and-steel tepee has stood beside U.S. Route 20 since the 1950s as a surviving piece of classic American roadside architecture. It still operates as a gift shop and overlook, so visitors can stop rather than simply photograph it while driving past.', 'open', 'https://www.atlasobscura.com/places/the-tepee', 'America/New_York', now()),
  ('Gilboa Fossil Forest', 'gilboa-fossil-forest', 'museums', 42.40046, -74.45014, 'Gilboa', 'NY', 'Gilboa became famous after quarrying exposed fossilized tree stumps from one of the oldest known forests on Earth, dating back roughly 380 million years. The local museum and outdoor fossil displays preserve examples from the site, with regular public hours concentrated on summer and early-fall weekends.', 'limited', 'https://www.atlasobscura.com/places/gilboa-fossil-forest', 'America/New_York', now()),
  ('Pratt Rock', 'pratt-rock', 'roadside-oddities', 42.30982, -74.42314, 'Prattsville', 'NY', 'Nineteenth-century businessman and congressman Zadock Pratt commissioned enormous carvings of himself, his family and symbols of his life directly into a Catskills cliff face. The free public park requires a steep climb from the road to reach the carvings, including an unfinished chamber originally intended as Pratt''s tomb.', 'limited', 'https://townofprattsville.com/historic-prattsville', 'America/New_York', now()),
  ('Stone Quarry Hill Art Park', 'stone-quarry-hill-art-park', 'roadside-oddities', 42.91344, -75.83343, 'Cazenovia', 'NY', 'Large contemporary sculptures are scattered across more than 100 acres of fields, woods and trails at this outdoor art park founded in 1991. Visitors can wander the grounds from dawn to dusk and encounter the work as part of the landscape rather than inside a conventional gallery.', 'open', 'https://sqhap.org/visit', 'America/New_York', now()),
  ('House of Frankenstein Wax Museum', 'house-of-frankenstein-wax-museum', 'museums', 43.42436, -73.71361, 'Lake George', 'NY', 'This old-fashioned horror wax museum fills a Canada Street building with moving monsters, gruesome tableaux and classic horror characters. It operates seasonally in Lake George, so current opening dates should be checked before treating it as a guaranteed walk-in stop.', 'limited', 'https://frankensteinwaxmuseum.com/', 'America/New_York', now()),
  ('Natural Stone Bridge and Caves', 'natural-stone-bridge-and-caves', 'roadside-oddities', 43.74739, -73.85192, 'Pottersville', 'NY', 'A massive marble arch spans Trout Brook here, forming what is promoted as the largest marble cave entrance in the eastern United States. Seasonal trails lead through caves, potholes and unusual rock formations, with access dependent on the attraction''s operating schedule and weather.', 'limited', 'https://stonebridgeandcaves.com/', 'America/New_York', now()),
  ('Santa''s Workshop at North Pole', 'santas-workshop-at-north-pole', 'roadside-oddities', 44.40088, -73.84889, 'Wilmington', 'NY', 'This vintage Christmas theme park opened in 1949 and helped pioneer the modern American theme-park concept with a year-round North Pole village built around Santa Claus. The park is closed for much of 2026 for improvements but has announced limited winter-season reopening dates, so verify the calendar before routing visitors here.', 'limited', 'https://www.northpoleny.com/', 'America/New_York', now()),
  ('Tahawus Ghost Town', 'tahawus-ghost-town', 'weird-history', 44.05061, -74.05098, 'Newcomb', 'NY', 'The abandoned mining settlement of Tahawus sits deep in the Adirondacks near the old iron and titanium works where Theodore Roosevelt began his famous 1901 ride to the presidency. Furnace ruins and surviving structures remain around the remote historic district, reached by a long drive into public forest lands and short walks from established access areas.', 'limited', 'https://www.adirondackhub.com/history/tahawus', 'America/New_York', now()),
  ('Singer Castle', 'singer-castle', 'roadside-oddities', 44.45223, -75.81216, 'Hammond', 'NY', 'This stone castle on Dark Island was built beginning in 1902 for Frederick Gilbert Bourne, president of the Singer Sewing Machine Company. Guided seasonal tours reveal hidden passageways, concealed doors and secret observation spaces, but reaching the island requires a boat.', 'limited', 'https://www.singercastle.com/', 'America/New_York', now()),
  ('Opus 40', 'opus-40', 'roadside-oddities', 42.05067, -74.03169, 'Saugerties', 'NY', 'Sculptor Harvey Fite spent nearly four decades assembling this sprawling bluestone earthwork by hand from millions of pieces of local stone. The six-acre labyrinth of ramps, terraces, walls and platforms is open seasonally as an outdoor arts site.', 'limited', 'https://opus40.org/', 'America/New_York', now()),
  ('Widow Jane Mine', 'widow-jane-mine', 'weird-history', 41.84284, -74.09827, 'Rosendale', 'NY', 'This enormous former cement mine is part of the Snyder Estate, where Rosendale cement was once quarried for major American construction projects. The cavernous mine now hosts concerts and special events, so interior access is limited to scheduled programs rather than unrestricted exploration.', 'limited', 'https://www.centuryhouse.org/', 'America/New_York', now()),
  ('Overlook Mountain House Ruins', 'overlook-mountain-house-ruins', 'weird-history', 42.08439, -74.09972, 'Woodstock', 'NY', 'Concrete walls and staircases from the abandoned Overlook Mountain House still stand high above Woodstock after repeated fires and unfinished rebuilding attempts ended the resort''s history. The ruins are reached by a steep multi-mile hike, and the state warns visitors not to enter or climb the unstable structures.', 'limited', 'https://dec.ny.gov/places/overlook-mountain-wild-forest', 'America/New_York', now()),
  ('Doodletown Ghost Town', 'doodletown-ghost-town', 'weird-history', 41.29596, -73.9916, 'Stony Point', 'NY', 'Doodletown was a small Hudson Highlands settlement whose remaining residents left in the 1960s after the Palisades Interstate Park Commission acquired the property. House foundations, roads, cemeteries and interpretive signs remain in the woods, reached only by hiking trails inside Bear Mountain State Park.', 'limited', 'https://parks.ny.gov/sites/default/files/BearMountainSuggestedHikes.pdf', 'America/New_York', now()),
  ('Bannerman Castle', 'bannerman-castle', 'weird-history', 41.45531, -73.98887, 'Fishkill', 'NY', 'Military-surplus dealer Francis Bannerman built this eccentric castle-like arsenal on Pollepel Island between 1900 and 1918, later leaving a romantic ruin after explosions, fire and abandonment. The island is controlled by New York State Parks and can be visited only through authorized seasonal boat or kayak tours.', 'limited', 'https://bannermancastle.org/faq/', 'America/New_York', now()),
  ('Chuang Yen Monastery Giant Buddha', 'chuang-yen-monastery-giant-buddha', 'roadside-oddities', 41.48333, -73.79444, 'Kent', 'NY', 'Chuang Yen Monastery occupies more than 200 wooded acres and houses an enormous indoor Buddha surrounded by thousands of smaller Buddha images. The Buddhist Association of the United States welcomes visitors to the monastery at designated times, but religious services and current visitor schedules should be respected.', 'limited', 'https://www.baus.org/en/visit-us/chuang-yen-monastery/introducing-cym/', 'America/New_York', now()),
  ('Armour-Stiner Octagon House', 'armour-stiner-octagon-house', 'roadside-oddities', 41.03085, -73.87047, 'Irvington', 'NY', 'This exuberant pink Victorian residence was transformed in the 1870s into an eight-sided domed house inspired by nineteenth-century octagon-house theories. It remains a private residence, and both the house and grounds are accessible only through advance ticketed guided tours.', 'limited', 'https://armourstiner.com/visit/', 'America/New_York', now()),
  ('Old Catskill Game Farm', 'old-catskill-game-farm', 'weird-history', 42.23924, -74.00823, 'Catskill', 'NY', 'The Catskill Game Farm operated from 1933 to 2006 and was once promoted as America''s largest privately owned zoo. Many empty cages, paths and zoo buildings still survive, but the property is now an inn and campground and only overnight guests currently have permission to explore the abandoned zoo grounds.', 'limited', 'https://www.theoldgamefarm.com/faqs', 'America/New_York', now()),
  ('North Brother Island', 'north-brother-island', 'weird-history', 40.80066, -73.89875, 'Bronx', 'NY', 'North Brother Island held Riverside Hospital, where New York isolated patients with contagious diseases and where Mary Mallon, better known as Typhoid Mary, spent years in quarantine. Hospital ruins remain overgrown across the island, but it is a protected wildlife area with no ordinary public access, so travelers should not attempt to land there.', 'closed', 'https://en.wikipedia.org/wiki/North_and_South_Brother_Islands_(New_York_City)', 'America/New_York', now()),
  ('Hart Island', 'hart-island', 'weird-history', 40.85326, -73.77044, 'Bronx', 'NY', 'New York City has used Hart Island as its public cemetery for more than a century, burying more than a million people there in mass and individual graves. The island is not freely accessible, but NYC Parks now offers limited public ranger visits and scheduled gravesite visits using the city ferry.', 'limited', 'https://www.nyc.gov/site/hartisland/hart-island/visitation.page', 'America/New_York', now()),
  ('Renwick Smallpox Hospital Ruin', 'renwick-smallpox-hospital-ruin', 'weird-history', 40.75159, -73.95956, 'New York', 'NY', 'This Gothic Revival ruin on Roosevelt Island opened as a smallpox hospital in the nineteenth century and later became a nurses'' residence before abandonment. The shell remains fenced and cannot be entered, but it is clearly visible from the public paths in Southpoint Park while preservation groups work toward eventual safe access.', 'closed', 'https://www.theruin.org/', 'America/New_York', now()),
  ('Old City Hall Subway Station', 'old-city-hall-subway-station', 'weird-history', 40.71264, -74.00668, 'New York', 'NY', 'The ornate original City Hall subway station opened with New York''s first subway line in 1904 and closed to passengers in 1945, leaving its Guastavino tile vaults and chandeliers intact underground. Entry is restricted to rare New York Transit Museum member tours that require advance tickets and a security background check.', 'limited', 'https://www.nytransitmuseum.org/old-city-hall/', 'America/New_York', now()),
  ('The New York Earth Room', 'the-new-york-earth-room', 'roadside-oddities', 40.72598, -73.99975, 'New York', 'NY', 'Walter De Maria filled a second-floor SoHo loft with roughly 250 cubic yards of earth in 1977, turning an ordinary interior into a permanent room of dark soil. Dia Art Foundation maintains the installation and allows visitors to see it for free during posted weekly hours.', 'open', 'https://www.diaart.org/visit/visit-our-locations-sites/walter-de-maria-the-new-york-earth-room-new-york-united-states', 'America/New_York', now()),
  ('The Broken Kilometer', 'the-broken-kilometer', 'roadside-oddities', 40.72408, -74.00211, 'New York', 'NY', 'Walter De Maria arranged 500 polished brass rods in five precisely spaced rows inside this SoHo storefront, creating a total combined length of one kilometer. The 1979 installation remains permanently maintained by Dia Art Foundation and is free to visit during posted hours.', 'open', 'https://www.diaart.org/visit/visit-our-locations-sites/walter-de-maria-the-broken-kilometer-new-york-united-states', 'America/New_York', now()),
  ('The City Reliquary', 'the-city-reliquary', 'museums', 40.71395, -73.95574, 'Brooklyn', 'NY', 'The City Reliquary is a tiny community museum devoted to ordinary and eccentric pieces of New York life, from subway tokens and fragments of landmarks to collections assembled by neighborhood residents. It began as a window display and now occupies a small Williamsburg storefront with limited weekend public hours.', 'limited', 'https://www.cityreliquary.org/plan-your-visit/', 'America/New_York', now()),
  ('Harry Houdini''s Grave', 'harry-houdinis-grave', 'weird-history', 40.69344, -73.8848, 'Queens', 'NY', 'Escape artist Harry Houdini is buried beneath a distinctive monument in Machpelah Cemetery, where magicians and fans have gathered for decades around the anniversary of his Halloween 1926 death. The grave can be visited during cemetery hours, but this is an active burial ground and should be treated respectfully.', 'open', 'https://houdinimuseum.wordpress.com/2013/02/05/houdini-grave-aerial-map/', 'America/New_York', now()),
  ('Coney Island Circus Sideshow', 'coney-island-circus-sideshow', 'roadside-oddities', 40.5753, -73.9798, 'Brooklyn', 'NY', 'Coney Island USA''s Sideshows by the Seashore continues the neighborhood''s freak-show and circus-sideshow tradition with sword swallowers, fire performers and other live acts. The organization describes it as the last permanently housed circus sideshow in the United States, but performances follow a seasonal schedule rather than running every day of the year.', 'limited', 'https://www.coneyisland.com/coneyislandcircussideshow', 'America/New_York', now()),
  ('Kings Park Psychiatric Center at Nissequogue River State Park', 'kings-park-psychiatric-center-at-nissequogue-river-state-park', 'weird-history', 40.89593, -73.23956, 'Kings Park', 'NY', 'The former Kings Park Psychiatric Center grew into a sprawling institutional campus that held more than 9,000 patients at its peak before closing in 1996. Much of the property is now Nissequogue River State Park, where public roads and trails pass surviving hospital buildings; the abandoned structures themselves are unsafe and off-limits, so do not enter them.', 'open', 'https://apps.cio.ny.gov/apps/mediacontact/public/view.cfm?backButton=&parm=DBCB9EAF-BB2B-D983-D05568DCB12EB50B', 'America/New_York', now()),
  ('Edgar Allan Poe Cottage', 'edgar-allan-poe-cottage', 'museums', 40.86551, -73.89424, 'Bronx', 'NY', 'Edgar Allan Poe lived in this small Fordham cottage from 1846 until shortly before his death, and his wife Virginia died here in 1847. The preserved house is now a museum containing exhibits and period furnishings connected to Poe''s final years, with regular weekend hours and additional private tours by arrangement.', 'open', 'https://bronxhistoricalsociety.org/poe-cottage', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  verified_at   = excluded.verified_at;
