-- New York, added by hand.
--
-- Dropped as already present: Rolling Hills Asylum (36 metres from the
-- existing record) and the Pine Bush UFO Museum (the same building).
--
-- Note the Spook Hill here is in Wappingers Falls and is a different place
-- from the Spook Hill already in the index, which is in Yates County. Slugs
-- were checked against the whole database rather than just this batch,
-- because an accidental collision would have quietly overwritten one with
-- the other.
--
-- A third of these are William G. Pomeroy Foundation Legends and Lore
-- markers: a programme that puts cast-metal signs at folklore sites, which
-- is why so many otherwise unmarked legends here have a precise location.
--
-- 27 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Origin of Champ Marker', 'origin-of-champ-marker', 'cryptids', 44.03611, -73.45666, 'Port Henry', 'NY', 'Bulwagga Bay is one of the locations most closely associated with Champ, the legendary creature of Lake Champlain. The marker here preserves a local origin story in which a scorned suitor becomes the lake monster, while Port Henry has built a much broader identity around decades of alleged Champ sightings.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/origin-of-champ/', null, 'America/New_York', now()),
  ('Champy Lake Monster Marker', 'champy-lake-monster-marker', 'cryptids', 44.70553, -73.40323, 'Plattsburgh', 'NY', 'This Legends & Lore marker on Cumberland Head commemorates Champ, the serpent-like creature allegedly seen in Lake Champlain for generations. More than 300 reported sightings have become part of regional folklore, and New York even symbolically protects the creature.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/10700-2/', null, 'America/New_York', now()),
  ('Lyonesse River Monster Marker', 'lyonesse-river-monster-marker', 'cryptids', 43.61615, -75.35691, 'Lyons Falls', 'NY', 'Lyonesse is a supposed 15-foot river creature first famously reported in the Black River in 1951, described as dark brown with unusual fins and silver-colored eyes. The town installed a Legends & Lore marker beside the river, making this unusually obscure New York cryptid easy to visit.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/lyonesse/', null, 'America/New_York', now()),
  ('Silver Lake Sea Serpent Marker', 'silver-lake-sea-serpent-marker', 'cryptids', 42.70068, -78.02302, 'Silver Lake', 'NY', 'Stories of a monster in Silver Lake became so popular that a local hotel owner built a mechanical sea serpent in 1855 and secretly launched it into the water to attract tourists. The hoax was eventually exposed, but the Silver Lake serpent survived as local folklore and now has its own Legends & Lore marker.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/sea-serpent-legend/', null, 'America/New_York', now()),
  ('The White Lady of Durand Eastman Park', 'the-white-lady-of-durand-eastman-park', 'haunted', 43.23597, -77.55674, 'Irondequoit', 'NY', 'For generations, people around Durand Eastman Park have told stories of a white-clad woman wandering near Lake Ontario with ghostly hounds while searching for her missing daughter. A Legends & Lore marker now stands on Lakeshore Boulevard near the park and the stone ruins popularly called the White Lady''s Castle.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/the-white-lady/', null, 'America/New_York', now()),
  ('Iron Island Museum', 'iron-island-museum', 'haunted', 42.88992, -78.81142, 'Buffalo', 'NY', 'This former church and funeral home is now both a neighborhood history museum and one of Buffalo''s established paranormal destinations. Visitors can take scheduled guided museum tours, while longer overnight investigations are available separately by reservation.', 'open', 'https://ironislandmuseum.com/', null, 'America/New_York', now()),
  ('Kau-Qua-Tau Witch Legend Marker', 'kau-qua-tau-witch-legend-marker', 'folklore', 42.83366, -78.74749, 'West Seneca', 'NY', 'A Legends & Lore marker at Ebenezer Cemetery preserves the story of Kau-Qua-Tau, a Seneca woman accused of witchcraft in 1821 and killed after fleeing the accusation. Later folklore blamed her spirit for disturbances in a cabin that once stood at the site.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/kau-qua-tau/', null, 'America/New_York', now()),
  ('Thirteen Curves', 'thirteen-curves', 'haunted', 42.98883, -76.25056, 'Onondaga', 'NY', 'Cedarvale Road''s twisting section known as Thirteen Curves is associated with the legend of a newlywed bride who died with her husband and still wanders the road looking for him. A Legends & Lore marker stands near Cedarvale Road and West Seneca Turnpike, so visitors do not need to stop on the narrow curves themselves.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/thirteen-curves/', null, 'America/New_York', now()),
  ('Split Rock Quarry and the Crusher', 'split-rock-quarry-and-the-crusher', 'haunted', 43.02454, -76.24219, 'Onondaga', 'NY', 'A massive explosion at the Split Rock munitions plant killed more than 50 workers in 1918, and the abandoned quarry later developed stories of phantom footsteps, voices and machinery. The surviving stone Crusher can still be reached on foot within the wooded former factory site, but it is an undeveloped hike and visitors should stay on the permitted public route.', 'limited', 'https://hauntedhistorytrail.com/explore/split-rock-quarry', null, 'America/New_York', now()),
  ('Fort Ontario''s Post Ghost', 'fort-ontarios-post-ghost', 'haunted', 43.46454, -76.50697, 'Oswego', 'NY', 'Fort Ontario''s best-known ghost is George Fikes, a British soldier who died there in 1782 and is said to continue guarding the fort with a red lantern. The state historic site preserves the fort and its underground passages, while a Legends & Lore marker specifically records the Post Ghost story.', 'open', 'https://www.wgpfoundation.org/historic-markers/the-post-ghost/', null, 'America/New_York', now()),
  ('Thompson Park Vortex', 'thompson-park-vortex', 'folklore', 43.96209, -75.89192, 'Watertown', 'NY', 'Local lore claims there is a strange area within Thompson Park where people become disoriented, lose several minutes of time, or briefly experience another time period. There is no proven supernatural vortex, but the story has become one of Watertown''s best-known modern legends and the public park can be visited normally.', 'open', 'https://hauntedhistorytrail.com/explore?category=creepy-locations\&utm_source=chatgpt.com', null, 'America/New_York', now()),
  ('Widow Susan Road', 'widow-susan-road', 'haunted', 42.92811, -74.16155, 'Amsterdam', 'NY', 'The road is named for Susan DeGraff, whose ghost is said to appear wearing white and crying while searching for her husband''s grave. A Legends & Lore marker at 179 Widow Susan Road gives travelers a safe physical point for the story rather than encouraging anyone to wander the road at night.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/widow-susan-road/', null, 'America/New_York', now()),
  ('Esperance Witch Marker', 'esperance-witch-marker', 'folklore', 42.76087, -74.26119, 'Esperance', 'NY', 'Local legend tells of a widowed French woman accused of witchcraft by neighboring settlers during the nineteenth century. The story claims she was eventually shot through her window with a silver bullet and buried beneath a pine tree so she could not return, and a Legends & Lore marker now preserves the tale along Route 20.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/esperance-witch/', null, 'America/New_York', now()),
  ('Hazel Drew Ghost Marker', 'hazel-drew-ghost-marker', 'haunted', 42.64404, -73.52709, 'Sand Lake', 'NY', 'Twenty-year-old Hazel Drew was found murdered near Teal''s Pond in 1908, and the case was never solved. Stories of her ghost walking the nearby woods survived for generations and later helped inspire the mystery behind Twin Peaks; a Legends & Lore marker now marks the local story without requiring visitors to enter the woods.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/hazel-drew/', null, 'America/New_York', now()),
  ('Spook Hill', 'spook-hill', 'folklore', 41.58642, -73.89194, 'Wappingers Falls', 'NY', 'Spook Hill Road supposedly earned its name when moonlight reflecting from a rocky hillside created a strange glow that terrified horses traveling the old dirt road. The original landscape has changed considerably, but a 2023 Legends & Lore marker in Spook Hill Park preserves the story.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/spook-hill/', null, 'America/New_York', now()),
  ('Lincoln''s Ghost Train Marker', 'lincolns-ghost-train-marker', 'haunted', 41.78727, -73.94629, 'Hyde Park', 'NY', 'Abraham Lincoln''s funeral train passed through Hyde Park on April 25, 1865. Folklore later developed that a spectral version of the black-draped train returns along the Hudson River tracks on the anniversary of its passage, and a Legends & Lore marker now identifies the location associated with the story.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/ghost-train/', null, 'America/New_York', now()),
  ('Fiddler''s Ghost', 'fiddlers-ghost', 'haunted', 41.87079, -73.8365, 'Staatsburg', 'NY', 'A local fiddler was reportedly robbed and murdered on a bridge here in September 1808. The bridge is gone, but folklore says his music can still be heard on moonlit nights, and a roadside Legends & Lore marker identifies the site.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/fiddlers-ghost/', null, 'America/New_York', now()),
  ('Headless Horseman Marker', 'headless-horseman-marker', 'folklore', 41.09097, -73.86119, 'Sleepy Hollow', 'NY', 'Sleepy Hollow Cemetery and the adjoining Old Dutch Church landscape are inseparable from Washington Irving''s The Legend of Sleepy Hollow. A Legends & Lore marker inside the cemetery specifically commemorates the story that the Headless Horseman tethers his horse among the graves.', 'open', 'https://www.wgpfoundation.org/historic-markers/headless-horseman/', null, 'America/New_York', now()),
  ('Mountain Witch of Sugar Loaf', 'mountain-witch-of-sugar-loaf', 'folklore', 41.3155, -74.28789, 'Sugar Loaf', 'NY', 'Local folklore remembers Elizabeth Dobbin, a widow who supposedly lived alone near Sugar Loaf Mountain in the late 1700s and was accused by nearby villagers of practicing witchcraft. A Legends & Lore marker now marks the area associated with the Mountain Witch story.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/mountain-witch/', null, 'America/New_York', now()),
  ('Calamity Corners', 'calamity-corners', 'weird-history', 41.31803, -74.29696, 'Sugar Loaf', 'NY', 'The intersection of Hambletonian Road and Pine Hill Road became known locally as Calamity Corners because of a succession of deaths, accidents and violent events associated with the area. Its reputation begins with the 1818 murder of Richard Jennings, a case often cited as an early American murder-for-hire, and a Legends & Lore marker was added in 2026.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/calamity-corners/', null, 'America/New_York', now()),
  ('Merchant''s House Museum', 'merchants-house-museum', 'haunted', 40.72766, -73.99234, 'New York', 'NY', 'The preserved 1832 Tredwell family home calls itself Manhattan''s most haunted house and has collected reports of footsteps, voices, odors and apparitions since becoming a museum. It remains open for normal daytime tours and also runs scheduled candlelight ghost tours and paranormal programming.', 'open', 'https://merchantshouse.org/ghosts/', null, 'America/New_York', now()),
  ('Morris-Jumel Mansion', 'morris-jumel-mansion', 'haunted', 40.83447, -73.93858, 'New York', 'NY', 'Manhattan''s oldest surviving house has accumulated stories of apparitions and unexplained activity connected with its long history, including former owner Eliza Jumel. The museum has offered dedicated paranormal investigations, although the mansion is temporarily undergoing roof work in 2026 and access should be checked before visiting.', 'limited', 'https://morrisjumel.org/programs/paranormal/', null, 'America/New_York', now()),
  ('Ghostly Friendship at Historic Richmond Town', 'ghostly-friendship-at-historic-richmond-town', 'haunted', 40.57138, -74.14743, 'Staten Island', 'NY', 'A Staten Island legend tells of a Hessian drummer named Ernest and a young Van Pelt girl called Pretty who became friends in 1776 and died the same year. Stories claim drumbeats, footsteps and the girl''s apparition can still be encountered around the historic house, and a Legends & Lore marker records the tale at Historic Richmond Town.', 'open', 'https://www.wgpfoundation.org/historic-markers/ghostly-friendship/', null, 'America/New_York', now()),
  ('Amityville Horror House', 'amityville-horror-house', 'haunted', 40.66661, -73.41481, 'Amityville', 'NY', 'The house associated with the 1974 DeFeo murders later became internationally famous through claims made by the Lutz family and The Amityville Horror books and films. It remains a private residence, so OddWay visitors should view only from public streets, should not enter the property, and should avoid disturbing the occupants.', 'private', 'https://www.wikidata.org/wiki/Q3597031', null, 'America/New_York', now()),
  ('The Big Duck', 'the-big-duck', 'roadside-oddities', 40.90694, -72.62306, 'Flanders', 'NY', 'Built in 1931 to sell ducks and eggs, this roughly 20-foot-tall duck-shaped building became such a famous example of novelty architecture that similar buildings are sometimes called "ducks." It is now owned by Suffolk County and operates as a visitor center and gift shop, generally open seven days a week.', 'open', 'https://www.suffolkcountyny.gov/Departments/Parks/Historic-Sites/The-Big-Duck', null, 'America/New_York', now()),
  ('Money Diggers Marker', 'money-diggers-marker', 'folklore', 43.18124, -76.83584, 'North Rose', 'NY', 'During the 1830s, spirit mediums supposedly led groups into this area to dig for buried gold and jewels revealed by supernatural guidance. The legend held that everyone had to remain completely silent while digging or evil spirits would appear and the treasure would vanish; a marker now stands near Galen and Lasher roads.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/money-diggers/', null, 'America/New_York', now()),
  ('Cardiff Giant', 'cardiff-giant', 'weird-history', 42.70598, -74.92973, 'Cooperstown', 'NY', 'The Cardiff Giant was a ten-foot stone figure secretly manufactured and buried before being "discovered" in 1869 and promoted as a petrified prehistoric man. One of America''s most famous nineteenth-century hoaxes survives today inside The Farmers'' Museum in Cooperstown.', 'open', 'https://www.atlasobscura.com/places/cardiff-giant', null, 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;
