-- North Dakota. The state had two stops, and both are duplicated in this file
-- under different names.
--
-- Neither showed up in the slug check. The buffalo is held as World's Largest
-- Buffalo and arrived as "World's Largest Buffalo — Dakota Thunder"; the crane
-- is held as World's Largest Sandhill Crane and arrived as "Sandy the Sandhill
-- Crane". Six metres and fourteen metres away. Nothing but a position check
-- would ever have found either, which is the clearest case yet for running
-- both.
--
-- Fourth state to need two timezones, and the fiddliest. The line follows
-- county borders rather than a meridian, so a coordinate rule gets it wrong
-- both ways: Regent sits at -102.54 in Hettinger County and keeps Mountain
-- time, while Lefor is fractionally further west in Stark County and keeps
-- Central. The Mountain towns are listed rather than calculated.
--
-- The Enchanted Highway crosses the line. It starts at Gladstone on Central
-- and ends at Regent on Mountain — twenty-nine miles of road with an hour in
-- the middle of it, and seven enormous scrap-metal sculptures along the way.
--
-- Sourcing is unusually concentrated: a hundred of the hundred and twenty come
-- from ndtourism.com. That is first-party rather than an aggregator, but it is
-- one domain carrying most of a state.
--
-- 118 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Geese in Flight', 'geese-in-flight', 'roadside-oddities', 46.87858, -102.56447, 'Gladstone', 'ND', 'Gary Greff''s enormous scrap-metal geese rise beside I-94 as the northern gateway to the Enchanted Highway. Unlike the later sculptures, this first installation is primarily viewed from the interstate/exit area, so use a safe lawful pull-off.', 'roadside', 'https://enchantedhighwaynd.com/geese-in-flight/', null, 'America/Chicago', now()),
  ('Deer Crossing', 'deer-crossing', 'roadside-oddities', 46.84617, -102.57465, 'Gladstone', 'ND', 'A herd of towering metal deer appears to leap over a fence along the Enchanted Highway. The sculpture is one of Gary Greff''s oversized prairie scenes built to turn the road to Regent into a destination of its own.', 'roadside', 'https://enchantedhighwaynd.com/deer-crossing/', null, 'America/Chicago', now()),
  ('Grasshoppers in the Field', 'grasshoppers-in-the-field', 'roadside-oddities', 46.68396, -102.55587, 'Lefor', 'ND', 'Giant metal grasshoppers loom over a roadside field, transforming a familiar Plains insect into a monumental roadside scene. A designated pull-off makes it one of the easier Enchanted Highway sculptures to inspect up close.', 'roadside', 'https://enchantedhighwaynd.com/grasshoppers/', null, 'America/Chicago', now()),
  ('Fisherman''s Dream', 'fishermans-dream', 'roadside-oddities', 46.60268, -102.48727, 'Regent', 'ND', 'A huge metal fish, fisherman and underwater scene fill this Enchanted Highway stop. Its scale and dense collection of welded aquatic forms make it one of the route''s most elaborate installations.', 'roadside', 'https://enchantedhighwaynd.com/fishermans-dream/', null, 'America/Denver', now()),
  ('Pheasants on the Prairie', 'pheasants-on-the-prairie', 'roadside-oddities', 46.54261, -102.52974, 'Regent', 'ND', 'A colossal pheasant family stands above the prairie beside the Enchanted Highway. The birds are built from welded metal and are deliberately exaggerated into a classic North Dakota photo stop.', 'roadside', 'https://enchantedhighwaynd.com/pheasants-on-the-prairie/', null, 'America/Denver', now()),
  ('Teddy Roosevelt Rides Again', 'teddy-roosevelt-rides-again', 'roadside-oddities', 46.5075, -102.50064, 'Regent', 'ND', 'This large metal tableau depicts Theodore Roosevelt on horseback with a stagecoach and other Western figures. It brings the state''s Roosevelt mythology into the same outsized scrap-metal language as the rest of the Enchanted Highway.', 'roadside', 'https://enchantedhighwaynd.com/teddy-roosevelt-rides-again/', null, 'America/Denver', now()),
  ('World''s Largest Tin Family', 'worlds-largest-tin-family', 'roadside-oddities', 46.45239, -102.5137, 'Regent', 'ND', 'Three gigantic farm-family figures made from metal tanks and pipe stand beside the road south of Regent. The deliberately homemade-looking giants are among the most recognizable pieces on the Enchanted Highway.', 'roadside', 'https://enchantedhighwaynd.com/tin-family/', null, 'America/Denver', now()),
  ('Enchanted Highway Gift Shop & Whirly Gigs', 'enchanted-highway-gift-shop-whirly-gigs', 'roadside-oddities', 46.43904, -102.54402, 'Regent', 'ND', 'The Regent terminus collects miniature sculpture souvenirs and a group of moving metal whirly-gigs tied to the Enchanted Highway project. Check posted hours before making the drive specifically for indoor access.', 'limited', 'https://enchantedhighwaynd.com/gift-shop-and-wirly-gigs/', null, 'America/Denver', now()),
  ('Salem Sue', 'salem-sue', 'roadside-oddities', 46.85274, -101.42631, 'New Salem', 'ND', 'A 38-foot-high fiberglass Holstein stands on a hill above New Salem as a monument to the area''s dairy industry. Its hilltop position makes the enormous cow visible from miles away along I-94.', 'open', 'https://www.ndtourism.com/new-salem/attractions-entertainment/family-fun/salem-sue', null, 'America/Chicago', now()),
  ('Tommy Turtle', 'tommy-turtle', 'roadside-oddities', 48.82325, -100.43105, 'Bottineau', 'ND', 'Tommy is a giant turtle riding an equally oversized snowmobile, a deliberately strange tribute to Bottineau''s winter recreation. North Dakota Tourism describes him as the world''s largest snowmobile-riding turtle.', 'open', 'https://www.ndtourism.com/articles/north-dakotas-larger-life-sculptures', null, 'America/Chicago', now()),
  ('W''eel Turtle', 'weel-turtle', 'roadside-oddities', 48.81076, -100.06187, 'Dunseith', 'ND', 'More than 2,000 painted wheel rims were assembled into this enormous turtle at the edge of Dunseith. The recycled construction gives the roadside giant an unmistakable skeletal, mechanical look.', 'open', 'https://www.ndtourism.com/dunseith/attractions-entertainment/family-fun/weel-turtle', null, 'America/Chicago', now()),
  ('Rusty the Two-Ton Turtle', 'rusty-the-two-ton-turtle', 'roadside-oddities', 47.51583, -100.89147, 'Turtle Lake', 'ND', 'Turtle Lake''s namesake roadside mascot is a two-ton turtle positioned on the south side of town. It is part of North Dakota''s unusual concentration of giant turtle monuments.', 'open', 'https://www.ndtourism.com/articles/north-dakotas-larger-life-sculptures', null, 'America/Chicago', now()),
  ('Wally the Walleye', 'wally-the-walleye', 'roadside-oddities', 47.65241, -101.41741, 'Garrison', 'ND', 'A 26-foot fiberglass walleye marks Garrison''s claim as a major Lake Sakakawea fishing town. The giant fish is a straightforward piece of oversized roadside Americana.', 'open', 'https://www.ndtourism.com/garrison/attractions-entertainment/family-fun/wally-walleye', null, 'America/Chicago', now()),
  ('Wahpper — World''s Largest Catfish', 'wahpper-worlds-largest-catfish', 'roadside-oddities', 46.28892, -96.59704, 'Wahpeton', 'ND', 'This 40-foot-long catfish pays tribute to the giant channel catfish associated with the Red River of the North. Its exaggerated scale makes it one of southeastern North Dakota''s strongest roadside-photo stops.', 'open', 'https://www.ndtourism.com/wahpeton/attractions-entertainment/arts-attractions/worlds-largest-catfish', null, 'America/Chicago', now()),
  ('Big Bruce — World''s Largest Wood Baseball Bat', 'big-bruce-worlds-largest-wood-baseball-bat', 'roadside-oddities', 46.89873, -96.80373, 'Fargo', 'ND', 'A record-setting wooden baseball bat stands at Newman Outdoor Field in Fargo. The oversized bat turns a conventional ballpark entrance into one of the state''s more literal roadside superlatives.', 'open', 'https://www.ndtourism.com/best-places/12-pack-classic-americana-north-dakota', null, 'America/Chicago', now()),
  ('Wheat Monument', 'wheat-monument', 'roadside-oddities', 48.15607, -103.64064, 'Williston', 'ND', 'A 35-foot wheat-themed monument uses black granite panels to commemorate the farmers and settlers of the region. It is an unusually monumental treatment of the crop that reshaped much of North Dakota''s prairie economy.', 'open', 'https://www.ndtourism.com/williston/attractions-entertainment/educational-attractions/wheat-monument', null, 'America/Chicago', now()),
  ('Wheat Sculpture', 'wheat-sculpture', 'roadside-oddities', 48.8629, -99.60787, 'Rolla', 'ND', 'A large roadside wheat sculpture celebrates the grain agriculture surrounding Rolla. Its scale and stylized metal form give an everyday crop the treatment normally reserved for civic monuments.', 'open', 'https://www.ndtourism.com/rolla/attractions-entertainment/arts-attractions/wheat-sculpture', null, 'America/Chicago', now()),
  ('Geographical Center of North America Monument', 'geographical-center-of-north-america-monument', 'roadside-oddities', 48.35441, -99.99807, 'Rugby', 'ND', 'Rugby has long promoted this stone monument as marking the geographical center of North America, based on an older calculation. Modern center-point claims are disputed, which makes the monument as interesting for its cartographic argument as for the photo stop itself.', 'open', 'https://www.ndtourism.com/rugby/attractions-entertainment/educational-attractions/geographical-center-north-america-monument', null, 'America/Chicago', now()),
  ('Northern Lights Tower and Interpretive Center', 'northern-lights-tower-and-interpretive-center', 'roadside-oddities', 48.35429, -99.99695, 'Rugby', 'ND', 'An 88.5-foot illuminated steel tower is painted in metallic colors as a tribute to the aurora borealis. At night the structure becomes an intentionally artificial echo of one of the northern Plains'' most dramatic natural phenomena.', 'open', 'https://www.ndtourism.com/rugby/attractions-entertainment/family-fun/northern-lights-tower-and-interpretive-center', null, 'America/Chicago', now()),
  ('Niewoehner Bell Tower', 'niewoehner-bell-tower', 'roadside-oddities', 48.36826, -99.99739, 'Rugby', 'ND', 'This freestanding tower holds a collection of bells gathered from schools, churches and other local institutions. The stacked bells turn community history into a vertical outdoor sound-and-metal monument.', 'open', 'https://www.ndtourism.com/rugby/nature-outdoor-activities/wildlife-viewing/niewoehner-bell-tower', null, 'America/Chicago', now()),
  ('Mystical Horizons', 'mystical-horizons', 'roadside-oddities', 48.94862, -100.52324, 'Bottineau', 'ND', 'Often described as a ''Stonehenge of the Prairie,'' Mystical Horizons uses stone and concrete alignments to frame the solstices, equinoxes and the north star. Its remote Turtle Mountain setting gives the intentionally astronomical monument a distinctly uncanny feel.', 'open', 'https://www.ndtourism.com/highway-5-tour', null, 'America/Chicago', now()),
  ('Union Silos', 'union-silos', 'roadside-oddities', 48.2374, -101.28728, 'Minot', 'ND', 'Working grain silos became an enormous mural complex in Minot, turning utilitarian agricultural infrastructure into public art. The scale is best understood from the surrounding public areas where the full painted cylinders can be seen together.', 'open', 'https://www.ndtourism.com/minot/attractions-entertainment/arts-attractions/union-silos', null, 'America/Chicago', now()),
  ('Big Gene Zombie Golf Giant', 'big-gene-zombie-golf-giant', 'roadside-oddities', 47.64326, -101.39334, 'Garrison', 'ND', 'A roughly 15-foot metal figure known as Big Gene guards the Garrison Golf Course. The oversized, zombie-like golfer is one of the stranger members of North Dakota''s roadside-giant collection; respect golf-course access and operations.', 'limited', 'https://www.ndtourism.com/articles/north-dakotas-larger-life-sculptures', null, 'America/Chicago', now()),
  ('Scandinavian Heritage Park Dala Horse', 'scandinavian-heritage-park-dala-horse', 'roadside-oddities', 48.22623, -101.2983, 'Minot', 'ND', 'A towering painted Dala horse stands inside Scandinavian Heritage Park as a monument to Swedish folk tradition. North Dakota Tourism identifies it as the largest Dala horse in the United States.', 'open', 'https://scandinavianheritage.org/map/', null, 'America/Chicago', now()),
  ('Fargo Woodchipper', 'fargo-woodchipper', 'weird-history', 46.8491, -96.85968, 'Fargo', 'ND', 'A replica woodchipper commemorates the infamous prop and scene from the film Fargo, despite much of the movie having been filmed outside North Dakota. It has become a deliberately macabre pop-culture photo stop at the Fargo-Moorhead Visitors Center.', 'open', 'https://www.ndtourism.com/fargo/attractions-entertainment/family-fun/fargo-woodchipper', null, 'America/Chicago', now()),
  ('Celebrity Walk of Fame', 'celebrity-walk-of-fame', 'roadside-oddities', 46.84897, -96.85974, 'Fargo', 'ND', 'Concrete handprints, footprints and signatures from visiting celebrities line this unusual Fargo attraction. The collection ranges across entertainers, athletes and public figures, creating a small-town answer to Hollywood''s celebrity pavement.', 'open', 'https://www.ndtourism.com/fargo/attractions-entertainment/family-fun/celebrity-walk-fame', null, 'America/Chicago', now()),
  ('Coghlan Castle', 'coghlan-castle', 'roadside-oddities', 48.93107, -99.65512, 'Rolla', 'ND', 'This eccentric stone residence was built by Maurice Coghlan and resembles a small prairie castle more than a conventional farmhouse. It is private property with controlled/check-ahead access, so do not enter without explicit permission.', 'limited', 'https://www.ndtourism.com/rolla/attractions-entertainment/free-attractions/coghlan-castle', null, 'America/Chicago', now()),
  ('Fort Sauerkraut', 'fort-sauerkraut', 'weird-history', 46.9027, -102.05543, 'Hebron', 'ND', 'Local settlers built this improvised defensive position during an 1892 scare, and the nickname ''Fort Sauerkraut'' outlived the crisis. The surviving memorial preserves a peculiar episode of frontier fear rather than a conventional military fort.', 'open', 'https://www.ndtourism.com/hebron/historic-sites-forts/forts/fort-sauerkraut', null, 'America/Chicago', now()),
  ('Minuteman Missile and Red Wing Boat', 'minuteman-missile-and-red-wing-boat', 'weird-history', 46.35549, -98.29881, 'LaMoure', 'ND', 'A preserved Minuteman missile display shares space with an unusual Red Wing boat, creating an abrupt pairing of Cold War weaponry and local transportation history. The outdoor display provides a visible introduction to North Dakota''s long nuclear-missile legacy.', 'open', 'https://www.ndtourism.com/lamoure/attractions-entertainment/educational-attractions/minuteman-missile-and-red-wing-boat', null, 'America/Chicago', now()),
  ('Oscar-Zero Missile Alert Facility', 'oscar-zero-missile-alert-facility', 'weird-history', 47.49764, -98.12726, 'Cooperstown', 'ND', 'The Ronald Reagan Minuteman Missile State Historic Site preserves an underground launch-control center where Air Force crews once waited for nuclear-war orders. Tours descend into the hardened command capsule and interpret daily life inside the missile field.', 'limited', 'https://www.history.nd.gov/historicsites/minutemanmissile/', null, 'America/Chicago', now()),
  ('November-33 Launch Facility', 'november-33-launch-facility', 'weird-history', 47.4404, -98.06615, 'Cooperstown', 'ND', 'This former Minuteman launch facility preserves the topside security structures and sealed silo position associated with a single nuclear missile. It is interpreted as part of the Ronald Reagan Minuteman Missile State Historic Site; remain within designated public areas.', 'limited', 'https://www.history.nd.gov/historicsites/minutemanmissile/', null, 'America/Chicago', now()),
  ('RSL3 Missile Site and Tours', 'rsl3-missile-site-and-tours', 'weird-history', 48.76307, -97.98563, 'Cavalier', 'ND', 'A preserved remote launch site from the Safeguard anti-ballistic-missile system contains underground corridors and the remains of Sprint missile silos. Scheduled tours reveal one of the shortest-lived and strangest chapters of America''s Cold War defense network.', 'limited', 'https://www.ndtourism.com/cavalier/attractions-entertainment/educational-attractions/rsl3-missile-site-and-tours', null, 'America/Chicago', now()),
  ('Fort Buford State Historic Site', 'fort-buford-state-historic-site', 'weird-history', 47.98767, -104.00062, 'Williston', 'ND', 'Fort Buford preserves several buildings and the grounds of an 1866 military post near the Missouri-Yellowstone confluence. The site is closely tied to Plains military conflict and Sitting Bull''s 1881 surrender; interpret the landscape as a historic site rather than an abandoned fort.', 'limited', 'https://www.ndtourism.com/williston/attractions-entertainment/hidden-gem-attractions/fort-buford-state-historic-site', null, 'America/Chicago', now()),
  ('Fort Abraham Lincoln Custer House', 'fort-abraham-lincoln-custer-house', 'haunted', 46.76606, -100.84784, 'Mandan', 'ND', 'The reconstructed commanding officer''s quarters interprets George and Libbie Custer''s life at Fort Abraham Lincoln before the 1876 Little Bighorn campaign. North Dakota Tourism also records local ghost lore involving unexplained touches and moved objects; those stories are presented as reports, not verified events.', 'limited', 'https://www.ndtourism.com/mandan/attractions-entertainment/educational-attractions/fort-abraham-lincoln-custer-house-commissary-bookstore', null, 'America/Chicago', now()),
  ('James Memorial Art Center', 'james-memorial-art-center', 'haunted', 48.15014, -103.62448, 'Williston', 'ND', 'This historic former library now operates as an arts center with galleries and classes. It also appears in North Dakota Tourism''s ghost-story collection, where investigators and visitors have reported unexplained activity; treat those accounts as local lore rather than fact.', 'limited', 'https://www.ndtourism.com/williston/attractions-entertainment/arts-attractions/james-memorial-art-center', null, 'America/Chicago', now()),
  ('Taube Museum of Art', 'taube-museum-of-art', 'haunted', 48.23657, -101.29277, 'Minot', 'ND', 'The museum occupies Minot''s historic 1906 Union National Bank building, giving its galleries an architectural story of their own. North Dakota Tourism includes the site in its state ghost-story collection under ''Unexpected Visitors,'' but the paranormal element remains folklore.', 'limited', 'https://www.ndtourism.com/minot/attractions-entertainment/arts-attractions/taube-museum-art', null, 'America/Chicago', now()),
  ('Historic 1883 Stutsman County Courthouse', 'historic-1883-stutsman-county-courthouse', 'weird-history', 46.90386, -98.7059, 'Jamestown', 'ND', 'North Dakota''s oldest surviving courthouse is a Gothic Revival landmark with an unusually intact pressed-metal interior. The building also played a role in the political struggle over Dakota statehood, making it far more than a preserved courtroom.', 'limited', 'https://www.history.nd.gov/historicsites/stutsmancc/', null, 'America/Chicago', now()),
  ('Writing Rock State Historic Site', 'writing-rock-state-historic-site', 'weird-history', 48.29311, -103.77505, 'Grenora', 'ND', 'Two granite boulders carry carved images traditionally associated with Indigenous spiritual meaning and later historical interpretation. The carvings and surrounding landscape should be treated as protected cultural material—do not touch, chalk, trace or alter the rock art.', 'limited', 'https://www.ndtourism.com/grenora/historic-sites-forts/historic-sites/writing-rock-state-historic-site', null, 'America/Chicago', now()),
  ('Huff Indian Village State Historic Site', 'huff-indian-village-state-historic-site', 'weird-history', 46.6187, -100.64449, 'Huff', 'ND', 'Depressions and earthworks mark a large fortified Mandan village occupied in the fifteenth century. More than a hundred earthlodge locations and the village''s defensive ditch remain legible in the prairie, turning archaeology into a visible landscape rather than a reconstructed attraction.', 'open', 'https://www.history.nd.gov/historicsites/huff/', null, 'America/Chicago', now()),
  ('Standing Rock State Historic Site', 'standing-rock-state-historic-site', 'weird-history', 46.6234, -97.9084, 'Nome', 'ND', 'Prehistoric burial mounds and the landmark known as Standing Rock occupy this high point above the Sheyenne Valley. North Dakota classifies the mounds as protected unmarked burial sites; visit respectfully and never disturb the earth or objects.', 'limited', 'https://www.ndtourism.com/nome/attractions-entertainment/free-attractions/standing-rock-state-historic-site', null, 'America/Chicago', now()),
  ('Fort Union Trading Post National Historic Site', 'fort-union-trading-post-national-historic-site', 'weird-history', 48.00016, -104.04148, 'Williston', 'ND', 'A reconstructed Upper Missouri fur-trade post marks the place where Native nations and Euro-American traders met from 1828 to 1867. The imposing white palisades and bourgeois house create one of the region''s most visually distinctive historical reconstructions.', 'open', 'https://www.nps.gov/fous/', null, 'America/Chicago', now()),
  ('Knife River Indian Villages National Historic Site', 'knife-river-indian-villages-national-historic-site', 'weird-history', 47.40031, -101.48609, 'Stanton', 'ND', 'Earthlodge depressions, village sites and museum exhibits preserve the homeland of Hidatsa and Mandan communities along the Knife River. The landscape includes the village associated with Sakakawea before the Lewis and Clark expedition.', 'open', 'https://www.nps.gov/knri/', null, 'America/Chicago', now()),
  ('Fort Mandan State Historic Site', 'fort-mandan-state-historic-site', 'weird-history', 47.29808, -101.08755, 'Washburn', 'ND', 'A reconstructed version of Lewis and Clark''s 1804-05 winter fort stands near the Missouri River. The site interprets the expedition''s crucial winter among nearby Mandan and Hidatsa communities rather than pretending the reconstruction is the surviving original structure.', 'limited', 'https://www.ndtourism.com/washburn/attractions-entertainment/educational-attractions/fort-mandan-state-historic-site', null, 'America/Chicago', now()),
  ('On-A-Slant Indian Village', 'on-a-slant-indian-village', 'weird-history', 46.76753, -100.84727, 'Mandan', 'ND', 'Reconstructed earthlodges stand amid the archaeological remains of a Mandan village occupied for centuries near the Heart and Missouri rivers. The site is within Fort Abraham Lincoln State Park and interprets Indigenous life that predates the military fort by generations.', 'limited', 'https://www.ndtourism.com/mandan/history/historic-sites/slant-indian-village', null, 'America/Chicago', now()),
  ('Menoken Indian Village State Historic Site', 'menoken-indian-village-state-historic-site', 'weird-history', 46.84095, -100.51853, 'Menoken', 'ND', 'Low earthworks preserve a fortified village occupied roughly eight centuries ago. An interpretive trail helps make the otherwise subtle ditch, bastion and lodge pattern visible without reconstructing the settlement.', 'open', 'https://www.ndtourism.com/menoken/attractions-entertainment/free-attractions/menoken-indian-village-state-historic-site', null, 'America/Chicago', now()),
  ('Double Ditch Indian Village State Historic Site', 'double-ditch-indian-village-state-historic-site', 'weird-history', 46.93409, -100.89707, 'Bismarck', 'ND', 'Large depressions, defensive ditches and refuse mounds mark a major Mandan village above the Missouri River. The abandoned village remains are unusually readable from the ground and reveal centuries of changing settlement size and fortification.', 'open', 'https://www.ndtourism.com/bismarck/historic-sites-forts/archaeology-paleontology/double-ditch-indian-village-state-historic-site', null, 'America/Chicago', now()),
  ('Wadeson Park State Historic Site', 'wadeson-park-state-historic-site', 'weird-history', 46.68009, -97.97454, 'Kathryn', 'ND', 'This Sheyenne Valley site protects prehistoric cultural remains and later historic features within a small public park. Its importance is archaeological rather than spectacular, so stay on established access and leave all material in place.', 'open', 'https://www.ndtourism.com/kathryn/history/historic-sites/wadeson-park-state-historic-site', null, 'America/Chicago', now()),
  ('Killdeer Mountain Battlefield State Historic Site', 'killdeer-mountain-battlefield-state-historic-site', 'weird-history', 47.42189, -102.91693, 'Killdeer', 'ND', 'This one-acre historic site marks the 1864 Battle of Killdeer Mountain, part of a U.S. military campaign against Native peoples of the northern Plains. The surrounding land is private and road conditions/access can change, so verify current access and remain on the state parcel.', 'limited', 'https://www.ndtourism.com/killdeer/history/historic-sites/killdeer-mountain-battlefield-state-historic-site', null, 'America/Chicago', now()),
  ('Fort Ransom State Historic Site', 'fort-ransom-state-historic-site', 'weird-history', 46.5208, -97.92561, 'Fort Ransom', 'ND', 'Little remains above ground of the 1867 military post, but cellar depressions, a dry moat, embankments and a flagpole still outline the fort. The ghostly absence of buildings makes the site read more like an archaeological footprint than a restored frontier attraction.', 'open', 'https://www.ndtourism.com/fort-ransom/attractions-entertainment/landmark-attractions/fort-ransom-state-historic-site', null, 'America/Chicago', now()),
  ('Fort Rice State Historic Site', 'fort-rice-state-historic-site', 'weird-history', 46.51428, -100.58402, 'Fort Rice', 'ND', 'Markers, depressions and surviving archaeological traces identify a Missouri River military post established in 1864. The site connects U.S. military expansion, steamboat travel and conflict with Indigenous nations in a landscape where most original structures are gone.', 'limited', 'https://www.ndtourism.com/fort-rice/attractions-entertainment/landmark-attractions/fort-rice-state-historic-site', null, 'America/Chicago', now()),
  ('Whitestone Hill State Historic Site', 'whitestone-hill-state-historic-site', 'weird-history', 46.16888, -98.85664, 'Kulm', 'ND', 'The site commemorates the deadly 1863 attack at Whitestone Hill and is now interpreted as a place of remembrance for its victims. Exhibits draw on documents, oral histories and research; visit with the seriousness appropriate to a massacre and burial landscape.', 'limited', 'https://www.ndtourism.com/kulm/history/historic-sites/whitestone-hill-state-historic-site', null, 'America/Chicago', now()),
  ('Fort Clark State Historic Site', 'fort-clark-state-historic-site', 'weird-history', 47.32554, -101.38027, 'Stanton', 'ND', 'Earthlodge depressions, cemetery areas and fort traces preserve a place where a Mandan village and a major American Fur Company post once stood side by side. A devastating smallpox epidemic in 1837 is central to the site''s history.', 'open', 'https://www.ndtourism.com/stanton/attractions-entertainment/landmark-attractions/fort-clark-state-historic-site', null, 'America/Chicago', now()),
  ('Gingras Trading Post State Historic Site', 'gingras-trading-post-state-historic-site', 'weird-history', 48.93701, -97.89106, 'Walhalla', 'ND', 'Two restored nineteenth-century buildings preserve the trading world of Métis businessman Antoine Blanc Gingras. The site is a rare architectural link to the Red River Métis community and the cross-border fur and buffalo-robe economy.', 'limited', 'https://www.ndtourism.com/walhalla/attractions-entertainment/free-attractions/gingras-trading-post-state-historic-site', null, 'America/Chicago', now()),
  ('Fort Totten State Historic Site', 'fort-totten-state-historic-site', 'weird-history', 47.97736, -98.99389, 'Fort Totten', 'ND', 'A remarkably intact cluster of brick buildings served first as a military post, then as a federal Indian boarding school and later as a tuberculosis preventorium. That layered institutional history makes the site important but also calls for careful, non-sensational interpretation.', 'limited', 'https://www.ndtourism.com/fort-totten/attractions-entertainment/educational-attractions/fort-totten-state-historic-site', null, 'America/Chicago', now()),
  ('Welk Homestead State Historic Site', 'welk-homestead-state-historic-site', 'weird-history', 46.15033, -100.20743, 'Strasburg', 'ND', 'The restored farmstead preserves the German-Russian immigrant world in which bandleader Lawrence Welk was raised. Outbuildings, agricultural setting and family history make it a surprisingly specific time capsule of early twentieth-century prairie life.', 'limited', 'https://www.ndtourism.com/strasburg/attractions-entertainment/hidden-gem-attractions/welk-homestead-state-historic-site', null, 'America/Chicago', now()),
  ('Camp Hancock State Historic Site', 'camp-hancock-state-historic-site', 'roadside-oddities', 46.80502, -100.7903, 'Bismarck', 'ND', 'Bismarck''s oldest surviving building began as part of a military supply post and weather station before becoming a church and museum site. Its changing uses compress several early city histories into one small Gothic-looking structure.', 'limited', 'https://www.ndtourism.com/bismarck/attractions-entertainment/family-fun/camp-hancock-state-historic-site', null, 'America/Chicago', now()),
  ('Former Governors'' Mansion State Historic Site', 'former-governors-mansion-state-historic-site', 'roadside-oddities', 46.81087, -100.78646, 'Bismarck', 'ND', 'This late nineteenth-century house served as the official home of North Dakota governors for decades. Period rooms and later additions show the oddly domestic side of state political history before the modern executive residence.', 'limited', 'https://www.ndtourism.com/bismarck/attractions-entertainment/educational-attractions/former-governors-mansion-state-historic-site', null, 'America/Chicago', now()),
  ('Chief Looking''s Village', 'chief-lookings-village', 'weird-history', 46.82978, -100.82808, 'Bismarck', 'ND', 'Archaeological remains on a high Missouri River bluff mark a Mandan village with a commanding view over the valley. The location connects a modern city park with a much older Indigenous settlement landscape.', 'open', 'https://www.ndtourism.com/bismarck/attractions-entertainment/free-attractions/chief-lookings-village', null, 'America/Chicago', now()),
  ('Chateau de Mores State Historic Site', 'chateau-de-mores-state-historic-site', 'roadside-oddities', 46.91662, -103.54252, 'Medora', 'ND', 'The 26-room hunting lodge of French aristocrat and entrepreneur Marquis de Mores sits above Medora like a transplanted piece of European ambition. Furnishings and exhibits interpret his unusual cattle-packing experiment in the Dakota Badlands.', 'limited', 'https://www.ndtourism.com/medora/attractions-entertainment/educational-attractions/chateau-de-mores-state-historic-site', null, 'America/Denver', now()),
  ('Fort Abercrombie State Historic Site', 'fort-abercrombie-state-historic-site', 'weird-history', 46.44803, -96.72708, 'Abercrombie', 'ND', 'Reconstructed blockhouses and interpretive grounds mark a frontier post known as the ''Gateway to the Dakotas.'' The fort was besieged in 1862, giving the quiet site a history of violence that contrasts with its pastoral setting today.', 'limited', 'https://www.ndtourism.com/abercrombie/attractions-entertainment/educational-attractions/fort-abercrombie-state-historic-site', null, 'America/Chicago', now()),
  ('Bagg Bonanza Farm', 'bagg-bonanza-farm', 'weird-history', 46.2527, -96.86549, 'Mooreton', 'ND', 'A huge preserved bonanza-farm complex documents the era when eastern investors operated wheat farms on an almost industrial scale. The mansion-like main house, barns and machinery show how dramatically agriculture reshaped the Red River Valley.', 'limited', 'https://www.ndtourism.com/mooreton/history/historic-sites/bagg-bonanza-farm', null, 'America/Chicago', now()),
  ('Buckstop Junction', 'buckstop-junction', 'weird-history', 46.80794, -100.72651, 'Bismarck', 'ND', 'Historic buildings relocated from around the region have been assembled into what the organization calls the ''little old town that never was, but is today.'' The result is an intentionally constructed ghost of a prairie main street rather than a preserved original town.', 'limited', 'https://www.ndtourism.com/bismarck/attractions-entertainment/family-fun/buckstop-junction', null, 'America/Chicago', now()),
  ('Fort Stevenson Guardhouse', 'fort-stevenson-guardhouse', 'weird-history', 47.59609, -101.42031, 'Garrison', 'ND', 'A reconstructed guardhouse interprets the vanished nineteenth-century Fort Stevenson, whose original site was affected by the creation of Lake Sakakawea. The small building serves as a physical stand-in for a much larger military landscape that no longer survives intact.', 'limited', 'https://www.ndtourism.com/garrison/attractions-entertainment/educational-attractions/fort-stevenson-guardhouse', null, 'America/Chicago', now()),
  ('Ellendale Opera House', 'ellendale-opera-house', 'roadside-oddities', 46.00175, -98.52824, 'Ellendale', 'ND', 'This restored 1909 opera house preserves a surprisingly elaborate performance space in a small prairie city. Seasonal events and tours provide access to its stage, balcony and period architecture.', 'limited', 'https://www.ndtourism.com/ellendale/attractions-entertainment/arts-attractions/ellendale-opera-house', null, 'America/Chicago', now()),
  ('North Dakota Heritage Center & State Museum', 'north-dakota-heritage-center-state-museum', 'museums', 46.81898, -100.78068, 'Bismarck', 'ND', 'The state museum spans North Dakota from deep geologic time through Indigenous history and statehood, including major fossil and archaeology collections. Its scale makes it one of the best places to understand why so many OddWay stops elsewhere in the state exist.', 'open', 'https://www.ndtourism.com/bismarck/attractions-entertainment/educational-attractions/north-dakota-heritage-center-state-museum', null, 'America/Chicago', now()),
  ('Dickinson Museum Center & Badlands Dinosaur Museum', 'dickinson-museum-center-badlands-dinosaur-museum', 'museums', 46.89529, -102.78415, 'Dickinson', 'ND', 'The complex combines a dinosaur museum, regional history museum, machinery hall and outdoor pioneer buildings. Eleven full-scale dinosaur skeletons, local fossils and a major Triceratops skull give it an especially strong prehistoric OddWay fit.', 'open', 'https://www.ndtourism.com/dickinson/attractions-entertainment/educational-attractions/dickinson-museum-center', null, 'America/Chicago', now()),
  ('Pioneer Trails Regional Museum', 'pioneer-trails-regional-museum', 'museums', 46.18244, -103.39334, 'Bowman', 'ND', 'This regional museum is unusually strong in paleontology as well as local history, with fossils gathered from southwestern North Dakota and an active research tradition. It connects ranch-country history with the much older animals buried beneath it.', 'limited', 'https://www.ndtourism.com/bowman/attractions-entertainment/educational-attractions/pioneer-trails-regional-museum', null, 'America/Denver', now()),
  ('Ukrainian Cultural Institute', 'ukrainian-cultural-institute', 'roadside-oddities', 46.87887, -102.80373, 'Dickinson', 'ND', 'Traditional embroidery, decorated eggs, textiles and folk art document the Ukrainian immigrant communities of western North Dakota. The collection gives a concentrated look at cultural practices that remain visually distinct from the surrounding Plains landscape.', 'limited', 'https://www.ndtourism.com/dickinson/attractions-entertainment/educational-attractions/ukrainian-cultural-institute', null, 'America/Chicago', now()),
  ('Pembina State Museum', 'pembina-state-museum', 'museums', 48.97327, -97.25463, 'Pembina', 'ND', 'A museum near the Canadian border interprets thousands of years of human history in one of the state''s oldest settlement regions. Its observation tower also makes the borderland geography itself part of the exhibit.', 'limited', 'https://www.ndtourism.com/pembina/attractions-entertainment/family-fun/pembina-state-museum', null, 'America/Chicago', now()),
  ('Long X Trading Post Visitor Center', 'long-x-trading-post-visitor-center', 'museums', 47.79962, -103.28345, 'Watford City', 'ND', 'The visitor center combines regional history, Theodore Roosevelt material and displays tied to western North Dakota''s ranching and badlands culture. It works as a gateway to the North Unit while retaining the atmosphere of an old trading-post name and frontier crossroads.', 'open', 'https://www.ndtourism.com/watford-city/attractions-entertainment/family-fun/long-x-trading-post-visitor-center', null, 'America/Chicago', now()),
  ('MHA Interpretive Center', 'mha-interpretive-center', 'weird-history', 47.97447, -102.59473, 'New Town', 'ND', 'The Mandan, Hidatsa and Arikara Nation''s interpretive center presents tribal history and culture from the perspective of the Three Affiliated Tribes. It is an essential counterweight to military forts and expedition sites elsewhere on the OddWay route.', 'open', 'https://www.ndtourism.com/new-town/attractions-entertainment/educational-attractions/mha-interpretive-center', null, 'America/Chicago', now()),
  ('Fargo Air Museum', 'fargo-air-museum', 'museums', 46.90542, -96.80417, 'Fargo', 'ND', 'Aircraft ranging from historic warbirds to more modern machines fill two hangars near Fargo''s airport. Several examples are maintained in flying condition, making the collection more than a static lineup of shells.', 'open', 'https://www.ndtourism.com/fargo/attractions-entertainment/aviation-flight/fargo-air-museum', null, 'America/Chicago', now()),
  ('Dakota Territory Air Museum', 'dakota-territory-air-museum', 'museums', 48.27164, -101.28964, 'Minot', 'ND', 'A large aircraft collection near Minot''s airport preserves military and civilian aviation history, including rare restored planes and wartime material. The museum''s proximity to a city shaped by an Air Force base adds another layer to the machinery on display.', 'limited', 'https://www.ndtourism.com/minot/attractions-entertainment/aviation-flight/dakota-territory-air-museum', null, 'America/Chicago', now()),
  ('North Dakota State Railroad Museum', 'north-dakota-state-railroad-museum', 'weird-history', 46.85922, -100.93248, 'Mandan', 'ND', 'Locomotives, rolling stock and railroad artifacts interpret the transportation system that created and connected many North Dakota towns. Outdoor equipment gives the museum the feel of a compact rail yard frozen in time.', 'limited', 'https://www.ndtourism.com/mandan/attractions-entertainment/educational-attractions/north-dakota-state-railroad-museum', null, 'America/Chicago', now()),
  ('Railroad Museum of Minot', 'railroad-museum-of-minot', 'weird-history', 48.23708, -101.29185, 'Minot', 'ND', 'This downtown museum collects tools, photographs, uniforms and equipment from the railroads that made Minot the ''Magic City.'' Its focus on working railroad culture distinguishes it from more general local-history collections.', 'limited', 'https://www.ndtourism.com/minot/attractions-entertainment/educational-attractions/railroad-museum-minot', null, 'America/Chicago', now()),
  ('Medicine Wheel Park', 'medicine-wheel-park', 'roadside-oddities', 46.91688, -98.00256, 'Valley City', 'ND', 'A large modern medicine-wheel-inspired installation anchors a walking-scale solar system, calendar features and other astronomy displays. The park deliberately mixes monumental earthwork geometry with science interpretation.', 'open', 'https://www.ndtourism.com/valley-city/attractions-entertainment/family-fun/medicine-wheel-park', null, 'America/Chicago', now()),
  ('Midland Continental Depot Transportation Museum Featuring Peggy Lee', 'midland-continental-depot-transportation-museum-featuring-peggy-lee', 'museums', 47.16899, -98.45967, 'Wimbledon', 'ND', 'A restored railroad depot interprets both local transportation history and singer Peggy Lee, who lived and worked here as a teenager. The unusual pairing of a tiny prairie depot and major pop-music biography gives the museum its OddWay value.', 'limited', 'https://www.ndtourism.com/wimbledon/attractions-entertainment/educational-attractions/midland-continental-depot-transportation-museum-featuring-peggy-lee', null, 'America/Chicago', now()),
  ('Valley City Rosebud Visitor Center', 'valley-city-rosebud-visitor-center', 'weird-history', 46.92368, -98.00529, 'Valley City', 'ND', 'The restored Northern Pacific Rosebud railcar sits beside the visitor center as a polished survivor of luxury railroad travel. Its ornate interior contrasts sharply with the utilitarian freight history usually associated with prairie rail towns.', 'open', 'https://www.ndtourism.com/valley-city/attractions-entertainment/educational-attractions/valley-city-rosebud-visitor-center', null, 'America/Chicago', now()),
  ('Barnes County Historical Society and Museum', 'barnes-county-historical-society-and-museum', 'museums', 46.92542, -98.00325, 'Valley City', 'ND', 'This county museum layers pioneer artifacts, military material, machinery and eccentric local objects into a dense small-town collection. It is a useful stop for stories too specific to fit into a statewide museum.', 'limited', 'https://www.ndtourism.com/valley-city/attractions-entertainment/family-fun/barnes-county-historical-society-and-museum', null, 'America/Chicago', now()),
  ('Paul Broste Rock Museum', 'paul-broste-rock-museum', 'museums', 47.96103, -102.13159, 'Parshall', 'ND', 'Artist and collector Paul Broste assembled rocks, minerals and geological specimens from around the world inside a distinctive stone museum. The building and collection together feel like a personal cabinet of geological obsessions enlarged to museum scale.', 'limited', 'https://www.ndtourism.com/parshall/attractions-entertainment/family-fun/paul-broste-rock-museum', null, 'America/Chicago', now()),
  ('Stump Lake Village Pioneer Museum', 'stump-lake-village-pioneer-museum', 'museums', 47.8755, -98.34552, 'Pekin', 'ND', 'Historic buildings gathered into a village preserve churches, homes, a school and other pieces of rural North Dakota life. The clustered structures make the site resemble an intentionally assembled ghost town on the prairie.', 'limited', 'https://www.ndtourism.com/pekin/history/museums/stump-lake-village-pioneer-museum', null, 'America/Chicago', now()),
  ('Lake County Pioneer Village Museum', 'lake-county-pioneer-village-museum', 'museums', 48.66502, -102.0556, 'Kenmare', 'ND', 'A collection of relocated buildings and artifacts recreates a small pioneer settlement near Kenmare. The site is seasonal and works best as an architectural time capsule rather than a conventional indoor museum.', 'limited', 'https://www.ndtourism.com/kenmare/attractions-entertainment/free-attractions/lake-county-pioneer-village-museum', null, 'America/Chicago', now()),
  ('Bonanzaville USA', 'bonanzaville-usa', 'museums', 46.87622, -96.92893, 'West Fargo', 'ND', 'Dozens of historic buildings and specialized collections have been assembled into a sprawling pioneer village in West Fargo. Cars, tractors, airplanes, railroad material and period structures make it closer to a preserved miniature region than a single museum.', 'limited', 'https://www.ndtourism.com/articles/visit-ranches-farms-and-gardens-throughout-north-dakota', null, 'America/Chicago', now()),
  ('Divide County Pioneer Village & Museum', 'divide-county-pioneer-village-museum', 'museums', 48.90889, -103.30163, 'Crosby', 'ND', 'Relocated historic buildings create a small pioneer village on the edge of Crosby. The collection preserves rural architecture and objects from one of North Dakota''s most remote northwestern counties.', 'limited', 'https://www.ndtourism.com/crosby/history/museums/divide-county-pioneer-village-museum', null, 'America/Chicago', now()),
  ('Prairie Village and Museum', 'prairie-village-and-museum', 'museums', 48.35311, -99.99471, 'Rugby', 'ND', 'A collection of historic buildings and artifacts recreates everyday life from the surrounding prairie communities. It complements Rugby''s giant monuments with a denser, more local version of roadside history.', 'limited', 'https://www.ndtourism.com/rugby/attractions-entertainment/educational-attractions/prairie-village-and-museum', null, 'America/Chicago', now()),
  ('Victorian Dress Museum', 'victorian-dress-museum', 'museums', 48.36707, -99.99799, 'Rugby', 'ND', 'Historic clothing and accessories are displayed in a museum devoted specifically to Victorian-era dress. The narrow focus makes it one of the state''s more unusual specialty collections.', 'limited', 'https://www.ndtourism.com/rugby/history/museums/victorian-dress-museum', null, 'America/Chicago', now()),
  ('Cavalier County Museum', 'cavalier-county-museum', 'museums', 48.82574, -98.48139, 'Dresden', 'ND', 'A native-rock church anchors a museum complex that also includes a log cabin, schoolhouse, caboose and reconstructed historic streetscape. The site is seasonal/check-ahead and feels like a collection of rescued fragments from vanished rural communities.', 'limited', 'https://www.ndtourism.com/dresden/history/museums/cavalier-county-museum', null, 'America/Chicago', now()),
  ('Pembina County Historical Museum and Pioneer Machinery Museum', 'pembina-county-historical-museum-and-pioneer-machinery-museum', 'weird-history', 48.77117, -97.73833, 'Cavalier', 'ND', 'Eleven buildings and large machinery displays preserve agricultural history, including a homestead, barn, blacksmith shop, depot and multiple buildings of restored farm equipment. The site is seasonal and may also operate by appointment.', 'limited', 'https://www.ndtourism.com/cavalier/historic-sites-forts/museums/pembina-county-historical-museum-and-pioneer-machinery-museum', null, 'America/Chicago', now()),
  ('Icelandic State Park Pioneer Heritage Center', 'icelandic-state-park-pioneer-heritage-center', 'roadside-oddities', 48.77373, -97.74009, 'Cavalier', 'ND', 'Historic buildings and exhibits interpret Icelandic settlement in northeastern North Dakota inside a state park near Lake Renwick. The preserved homestead culture gives the park a distinctive immigrant-history layer beyond its natural recreation.', 'limited', 'https://www.ndtourism.com/cavalier/attractions-entertainment/family-fun/icelandic-state-park', null, 'America/Chicago', now()),
  ('Grand Forks County Historical Society', 'grand-forks-county-historical-society', 'museums', 47.8965, -97.02761, 'Grand Forks', 'ND', 'A cluster of historic structures and exhibits preserves Grand Forks County history outside the modern downtown core. Multiple buildings let visitors move through changing domestic, school and community spaces rather than viewing everything in one gallery.', 'limited', 'https://www.ndtourism.com/grand-forks/attractions-entertainment/educational-attractions/grand-forks-county-historical-society', null, 'America/Chicago', now()),
  ('North Dakota Museum of Art — Barton Benes Cabinet of Wonders', 'north-dakota-museum-of-art-barton-benes-cabinet-of-wonders', 'museums', 47.91904, -97.07367, 'Grand Forks', 'ND', 'Inside the state art museum is a recreated apartment environment associated with artist Barton Lidice Benes, whose work embraced collecting, relics and cabinet-of-curiosity presentation. It is one of North Dakota''s best true ''cabinet of wonders'' experiences.', 'open', 'https://www.ndtourism.com/grand-forks/attractions-entertainment/arts-attractions/north-dakota-museum-art', null, 'America/Chicago', now()),
  ('Roger Maris Museum', 'roger-maris-museum', 'museums', 46.8599, -96.84603, 'Fargo', 'ND', 'A small museum devoted to baseball star Roger Maris sits unexpectedly inside West Acres shopping mall. Memorabilia, video and recreated elements turn a retail corridor into a compact sports shrine.', 'open', 'https://www.ndtourism.com/fargo/history/museums/roger-maris-museum', null, 'America/Chicago', now()),
  ('Frontier Village', 'frontier-village', 'weird-history', 46.88858, -98.70135, 'Jamestown', 'ND', 'Historic and recreated frontier buildings line a small Old West-style village below Jamestown''s giant buffalo. The deliberately assembled streetscape includes shops and displays that make the hilltop feel like a prairie theme town.', 'limited', 'https://www.ndtourism.com/jamestown/attractions-entertainment/educational-attractions/frontier-village', null, 'America/Chicago', now()),
  ('North American Bison Discovery Center', 'north-american-bison-discovery-center', 'museums', 46.88843, -98.7012, 'Jamestown', 'ND', 'Exhibits interpret bison biology, history and their relationship with Indigenous peoples and Plains settlement. Its location beside live bison habitat and Dakota Thunder links the real animal to North Dakota''s giant concrete version next door.', 'open', 'https://www.ndtourism.com/jamestown/attractions-entertainment/arts-attractions/north-american-bison-discovery-center', null, 'America/Chicago', now()),
  ('Dakota Buttes Museum', 'dakota-buttes-museum', 'museums', 45.99816, -102.62786, 'Hettinger', 'ND', 'This local museum preserves southwestern North Dakota artifacts in a region shaped by ranching, railroads and badlands geology. Its strength is the concentration of place-specific material from communities that are easy to drive past.', 'limited', 'https://www.ndtourism.com/hettinger/attractions-entertainment/family-fun/dakota-buttes-historical-society-and-museum', null, 'America/Denver', now()),
  ('New Salem Historical Society / Custer Trail Museum', 'new-salem-historical-society-custer-trail-museum', 'museums', 46.85127, -101.41806, 'New Salem', 'ND', 'Local artifacts and Custer Trail material interpret the military and settlement routes that crossed the area around New Salem. The museum provides historical context to a town better known to highway travelers for the enormous cow on the hill.', 'limited', 'https://www.ndtourism.com/new-salem/history/lewis-clark-trail/new-salem-historical-societycuster-trail-museum', null, 'America/Chicago', now()),
  ('Scandinavian Heritage Park', 'scandinavian-heritage-park', 'roadside-oddities', 48.226, -101.2983, 'Minot', 'ND', 'This outdoor park gathers replicas and monuments representing Norway, Sweden, Denmark, Finland and Iceland, including a stave-church replica and the giant Dala horse. The concentration of transplanted Nordic architectural forms makes it a particularly unusual urban park.', 'open', 'https://www.ndtourism.com/minot/attractions-entertainment/educational-attractions/scandinavian-heritage-park', null, 'America/Chicago', now()),
  ('Assumption Abbey Benedictine Monastery and Historic Church', 'assumption-abbey-benedictine-monastery-and-historic-church', 'roadside-oddities', 46.88897, -102.32004, 'Richardton', 'ND', 'Twin church towers rise over the prairie at this Benedictine monastery, creating one of western North Dakota''s most unexpected architectural silhouettes. Visitors should respect worship, residential and monastic areas and follow posted access rules.', 'limited', 'https://www.ndtourism.com/richardton/attractions-entertainment/hidden-gem-attractions/assumption-abbey-benedictine-monastery-and-historic-church', null, 'America/Chicago', now()),
  ('Hutmacher Farm', 'hutmacher-farm', 'roadside-oddities', 47.2851, -102.92618, 'Manning', 'ND', 'This historic German-Russian farmstead preserves buildings constructed from locally available earth and stone rather than standard frame construction. The earthen architecture makes the property an unusually direct response to the treeless prairie environment.', 'limited', 'https://www.ndtourism.com/manning/attractions-entertainment/educational-attractions/hutmacher-farm', null, 'America/Chicago', now()),
  ('Lewis and Clark Trail Museum', 'lewis-and-clark-trail-museum', 'museums', 47.84564, -103.64164, 'Alexander', 'ND', 'A small museum in northwestern North Dakota interprets regional homesteading and the Lewis and Clark story with local collections. It is a compact historical stop in a part of the state where long distances separate formal museums.', 'limited', 'https://www.ndtourism.com/alexander/attractions-entertainment/educational-attractions/lewis-and-clark-trail-museum', null, 'America/Chicago', now()),
  ('Buffalo Trails Museum', 'buffalo-trails-museum', 'museums', 48.27987, -103.35817, 'Epping', 'ND', 'This small community museum preserves frontier and homestead artifacts in Epping, including material tied to the surrounding ranch country. Its remote setting and locally assembled collection fit the OddWay preference for specific, place-rooted museums.', 'limited', 'https://www.ndtourism.com/epping/attractions-entertainment/arts-attractions/buffalo-trails-museum', null, 'America/Chicago', now()),
  ('Missouri-Yellowstone Confluence Interpretive Center', 'missouri-yellowstone-confluence-interpretive-center', 'roadside-oddities', 47.98509, -103.98883, 'Williston', 'ND', 'Exhibits overlook the landscape where the Yellowstone River meets the Missouri, a geographic junction central to Indigenous travel, exploration, trade and military history. The center sits about half a mile east of Fort Buford and should be treated as a distinct stop.', 'open', 'https://www.ndtourism.com/williston/attractions-entertainment/educational-attractions/missouri-yellowstone-confluence-interpretive-center-mycic', null, 'America/Chicago', now()),
  ('Billings County Courthouse Museum', 'billings-county-courthouse-museum', 'museums', 46.91303, -103.5227, 'Medora', 'ND', 'Medora''s former courthouse preserves courtroom fixtures, jail-related material and county history inside a civic building from the Badlands'' early settlement era. The scale is intimate enough that the old governmental spaces remain part of the experience.', 'limited', 'https://www.ndtourism.com/medora/attractions-entertainment/hidden-gem-attractions/billings-county-courthouse-museum', null, 'America/Denver', now()),
  ('Von Hoffman House', 'von-hoffman-house', 'roadside-oddities', 46.91401, -103.52179, 'Medora', 'ND', 'This preserved 1880s house is connected to the family of Medora de Vallombrosa, namesake of the town. Its domestic rooms provide a smaller and more personal counterpart to the grand Chateau de Mores nearby.', 'limited', 'https://www.ndtourism.com/medora/history/historic-sites/von-hoffman-house', null, 'America/Denver', now()),
  ('Harold Schafer Heritage Center', 'harold-schafer-heritage-center', 'weird-history', 46.91438, -103.5226, 'Medora', 'ND', 'The museum tells the story of entrepreneur Harold Schafer, whose Gold Seal Company produced products such as Mr. Bubble and who helped reinvent Medora as a tourist destination. It is an unusual intersection of household-brand history and manufactured Old West tourism.', 'open', 'https://www.ndtourism.com/medora/attractions-entertainment/educational-attractions/harold-schafer-heritage-center', null, 'America/Denver', now()),
  ('North Dakota Cowboy Hall of Fame', 'north-dakota-cowboy-hall-of-fame', 'museums', 46.91386, -103.52607, 'Medora', 'ND', 'Galleries interpret ranching, rodeo, Native American horse culture and the mythology of the northern Plains cowboy. Its location in Medora places the curated version of the West directly beside a town built around that same legend.', 'open', 'https://www.ndtourism.com/medora/attractions-entertainment/family-fun/north-dakota-cowboy-hall-fame', null, 'America/Denver', now()),
  ('Lewis and Clark Interpretive Center', 'lewis-and-clark-interpretive-center', 'museums', 47.30201, -101.04166, 'Washburn', 'ND', 'Large exhibits interpret the Corps of Discovery''s 1804-05 winter and its relationships with Mandan and Hidatsa communities. Outside, oversized steel figures of Lewis, Clark and Chief Sheheke extend the interpretation into monumental roadside art.', 'open', 'https://www.ndtourism.com/washburn/attractions-entertainment/arts-attractions/lewis-and-clark-interpretive-center', null, 'America/Chicago', now()),
  ('Fort Abraham Lincoln State Park', 'fort-abraham-lincoln-state-park', 'weird-history', 46.7661, -100.84791, 'Mandan', 'ND', 'North Dakota''s oldest state park combines reconstructed military buildings, the Custer House area and On-A-Slant''s earthlodges in one unusually dense historical landscape. This entry represents the broader grounds and museum system rather than either of those distinct component stops.', 'open', 'https://www.parkrec.nd.gov/fort-abraham-lincoln-state-park', null, 'America/Chicago', now()),
  ('North Dakota State Capitol', 'north-dakota-state-capitol', 'roadside-oddities', 46.8207, -100.78275, 'Bismarck', 'ND', 'North Dakota''s Art Deco capitol rises as a narrow high-rise rather than the domed classical building expected of most statehouses, earning the nickname ''Skyscraper on the Prairie.'' Public access uses the south entrance with security screening, and guided tours are offered on posted schedules.', 'limited', 'https://www.omb.nd.gov/capitol-complex/schedule-tour', null, 'America/Chicago', now()),
  ('White Butte', 'white-butte', 'roadside-oddities', 46.39492, -103.3014, 'Amidon', 'ND', 'At 3,506 feet, White Butte is North Dakota''s highest natural point, rising from privately owned ranchland and pale badlands formations. Follow the established access arrangement, respect the property and avoid treating the summit approach as unrestricted public land.', 'limited', 'https://www.ndtourism.com/amidon/attractions-entertainment/family-fun/white-butte', null, 'America/Denver', now()),
  ('International Peace Garden', 'international-peace-garden', 'roadside-oddities', 48.99918, -100.0583, 'Dunseith', 'ND', 'This vast formal garden physically straddles the United States-Canada border, allowing visitors to move through a landscape designed around an international boundary and peace symbolism. The combination of border monuments, formal gardens and remote Turtle Mountain setting makes it more unusual than a standard botanical garden.', 'open', 'https://www.ndtourism.com/dunseith/attractions-entertainment/landmark-attractions/international-peace-garden', null, 'America/Chicago', now()),
  ('Hilltop Viking Statue on Pyramid Hill', 'hilltop-viking-statue-on-pyramid-hill', 'roadside-oddities', 46.52389, -97.92051, 'Fort Ransom', 'ND', 'A roughly 25-foot black Viking warrior stands on Pyramid Hill above Fort Ransom, erected in 1972 as a monument to Scandinavian ancestry in the region. The hill is steep and the statue is best approached only by established lawful access; the odd silhouette is visible from below.', 'limited', 'https://www.ndtourism.com/articles/north-dakotas-larger-life-sculptures', null, 'America/Chicago', now()),
  ('Cannonball Concretions', 'cannonball-concretions', 'roadside-oddities', 47.5964, -103.332, 'Watford City', 'ND', 'Huge nearly spherical rocks appear to have rolled out of the badlands at this North Unit pullout in Theodore Roosevelt National Park. They formed as minerals cemented sediment around a core, and all rocks and other resources must remain where they are.', 'open', 'https://www.nps.gov/places/cannonball-concretions.htm', null, 'America/Chicago', now()),
  ('Painted Canyon Visitor Center Overlook', 'painted-canyon-visitor-center-overlook', 'roadside-oddities', 46.89539, -103.38165, 'Medora', 'ND', 'An I-94 exit suddenly opens onto striped, eroded badlands that can look almost detached from the surrounding prairie. The overlook and visitor center provide one of the easiest lawful places to see Theodore Roosevelt National Park''s bizarre erosion forms without a long hike.', 'open', 'https://www.ndtourism.com/medora/nature-outdoor-activities/national-state-parks/theodore-roosevelt-national-park-painted-canyon-visitor-center', null, 'America/Denver', now()),
  ('Petrified Forest Loop Trailhead', 'petrified-forest-loop-trailhead', 'museums', 46.98221, -103.53773, 'Medora', 'ND', 'A remote trail leads to one of the highest concentrations of petrified wood in the United States, including large fossilized stumps from a swampy Paleocene landscape. NPS changed the legal driving approach in 2026; follow the current approved route and never remove fossil wood or stone.', 'limited', 'https://www.nps.gov/places/petrified-forest-north.htm', null, 'America/Denver', now()),
  ('Buck Hill', 'buck-hill', 'roadside-oddities', 46.92575, -103.38885, 'Medora', 'ND', 'A short climb reaches one of the highest and most exposed viewpoints in Theodore Roosevelt National Park''s South Unit. The hill gives a close view of the caprock, clay and deeply eroded forms that make the badlands appear almost extraterrestrial.', 'limited', 'https://www.nps.gov/thro/learn/nature/geologicformations.htm', null, 'America/Denver', now()),
  ('Lake Region Heritage Center Museum', 'lake-region-heritage-center-museum', 'museums', 48.11143, -98.85841, 'Devils Lake', 'ND', 'The regional museum occupies a historic building and combines changing art exhibitions with collections tied to Devils Lake and the surrounding communities. Its local-history focus provides context for a city whose name and rapidly changing lake have long attracted stories and curiosity.', 'limited', 'https://www.ndtourism.com/devils-lake/attractions-entertainment/arts-attractions/lake-region-heritage-center-museum', null, 'America/Chicago', now()),
  ('Theodore Roosevelt Center', 'theodore-roosevelt-center', 'museums', 46.88269, -102.80023, 'Dickinson', 'ND', 'Dickinson State University''s Roosevelt Center is building a vast digital archive of Theodore Roosevelt material and interprets his life through documents, early motion pictures and historic audio. Hearing and seeing a nineteenth-century president through surviving technology gives the collection an unusual media-history angle.', 'limited', 'https://www.ndtourism.com/dickinson/attractions-entertainment/arts-attractions/theodore-roosevelt-center', null, 'America/Chicago', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  timezone      = excluded.timezone,
  verified_at   = excluded.verified_at;

select count(*) as north_dakota from public.stops where state = 'ND';
