-- Ohio, part two.
--
-- Heavy on institutional buildings that found a second life: two county
-- infirmaries, a poor farm, a jail, a school and a Civil War veterans' home,
-- all now running ghost tours. That is a pattern rather than a coincidence —
-- these buildings are expensive to keep and impossible to sell, and the
-- paranormal trade pays the roof bill.
--
-- Eleven are 'limited' for that reason: booking a specific event, not turning
-- up. Getting that wrong sends somebody to a locked door.
--
-- Checked against all 455 rows: no slug collisions, nothing within 500 metres
-- of an existing stop.
--
-- 30 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone, verified_at)
values
  ('Madison Seminary', 'madison-seminary', 'haunted', 41.79051, -81.04554, 'Madison', 'OH', 'Built in 1847 as a school, Madison Seminary later served as a home for Civil War veterans and their families before passing through several institutional uses. The restored building is now best known as a paranormal investigation venue, with tours and overnight ghost hunts offered by reservation rather than normal walk-in access.', 'limited', 'https://www.madisonseminary.com/', 'America/New_York', now()),
  ('Twin City Opera House', 'twin-city-opera-house', 'haunted', 39.649, -81.85349, 'McConnelsville', 'OH', 'Twin City Opera House opened in 1892 and still operates as a theater and movie house in downtown McConnelsville. Decades of reports involving footsteps, voices and apparitions have made it a major Ohio paranormal site, and the theater offers scheduled public ghost hunts and private investigations rather than unrestricted after-hours access.', 'limited', 'https://hauntedtwincityoperahouse.com/', 'America/New_York', now()),
  ('The Bellaire House', 'the-bellaire-house', 'haunted', 40.00279, -80.74478, 'Bellaire', 'OH', 'This Belmont Street house has become one of eastern Ohio''s best-known dedicated paranormal investigation properties, with stories involving apparitions, voices and other unexplained activity. It operates as a ticketed paranormal attraction with tours and overnight investigations, so visitors need to book access and should not treat the residential property as an open walk-in site.', 'limited', 'https://www.bellairehousetours.com/', 'America/New_York', now()),
  ('Historic Buxton Inn', 'historic-buxton-inn', 'haunted', 40.0674, -82.51625, 'Granville', 'OH', 'The Buxton Inn traces its history to an 1812 tavern and stagecoach stop and has operated in Granville for more than two centuries. Stories of former owners, guests and even a ghostly cat have become part of the inn''s identity; it remains an active hospitality property, so public access is through its current lodging, dining and event operations.', 'open', 'https://www.buxtoninn.com/history', 'America/New_York', now()),
  ('Wood County Museum', 'wood-county-museum', 'weird-history', 41.35028, -83.61586, 'Bowling Green', 'OH', 'The Wood County Museum occupies the county''s former nineteenth-century infirmary and poor farm complex. Visitors can explore exhibits on the people who lived and died there along with the grounds, paupers cemetery, former Lunatic Asylum site and Pestilence House, making it far stranger than a typical county history museum.', 'open', 'https://woodcountyhistory.org/visit/', 'America/New_York', now()),
  ('The Castle Historic House Museum', 'the-castle-historic-house-museum', 'haunted', 39.42054, -81.45502, 'Marietta', 'OH', 'This Gothic Revival mansion was completed in 1855 and is now preserved as a historic house museum in Marietta. The property also hosts ghost tours built around reported sightings, unexplained sounds and local stories associated with the house, while normal historical tours provide daytime access.', 'open', 'https://mariettaohio.org/events/the-castle-ghost-tour/', 'America/New_York', now()),
  ('Historic Zoar Village Ghost Tours', 'historic-zoar-village-ghost-tours', 'haunted', 40.61232, -81.42259, 'Zoar', 'OH', 'Zoar was founded in 1817 by German religious Separatists who created a communal village that survives today as a collection of historic museum buildings. Seasonal lantern ghost tours use stories of unexplained encounters reported by residents, staff and visitors, so the paranormal version of the stop requires a scheduled ticket.', 'limited', 'https://historiczoarvillage.com/events/ghost-tours/', 'America/New_York', now()),
  ('Poasttown Elementary School', 'poasttown-elementary-school', 'haunted', 39.54838, -84.38132, 'Middletown', 'OH', 'The former Poasttown Elementary School has been converted into a dedicated paranormal investigation destination rather than demolished or repurposed as a conventional museum. Visitors can enter during scheduled flashlight tours, public investigations and private bookings, but the building is not open for casual exploration.', 'limited', 'https://poasttownschool.com/flashlight-tours/', 'America/New_York', now()),
  ('Cincinnati Music Hall', 'cincinnati-music-hall', 'haunted', 39.10939, -84.51922, 'Cincinnati', 'OH', 'Cincinnati Music Hall opened in 1878 and remains one of the city''s major performance venues, but its long history has also produced persistent stories of apparitions and unexplained activity. The building can be entered for performances and official tours, including occasional behind-the-scenes experiences that discuss its unusual history.', 'open', 'https://www.cincinnatiarts.org/plan-your-visit/visit-music-hall/tours-1', 'America/New_York', now()),
  ('Landoll''s Mohican Castle Ghost Walk', 'landolls-mohican-castle-ghost-walk', 'haunted', 40.57289, -82.23377, 'Loudonville', 'OH', 'Landoll''s Mohican Castle runs guided haunted-history walks that lead visitors through the property, nearby Heyd Cemetery and a replica nineteenth-century cabin. The experience combines documented local history with the area''s ghost stories and is offered only on scheduled dates, so advance booking is required.', 'limited', 'https://landollsmohicancastle.com/events/ghost-walk-haunted-history-tours/', 'America/New_York', now()),
  ('Fairfield County Infirmary', 'fairfield-county-infirmary', 'haunted', 39.7394, -82.5881, 'Lancaster', 'OH', 'The former Fairfield County Infirmary is a large institutional building associated with generations of poor-farm and county-home residents. It now operates as a paranormal and historical venue offering scheduled tours, photography sessions, public ghost hunts and private investigations rather than everyday walk-in access.', 'limited', 'https://visitfairfieldcounty.org/listings/fairfield-county-infirmary/', 'America/New_York', now()),
  ('Brownella Cottage', 'brownella-cottage', 'haunted', 40.73298, -82.79176, 'Galion', 'OH', 'Brownella Cottage was built in 1887 and later became the home of Bishop William Montgomery Brown and his wife Ella, with much of the house''s original character and furnishings preserved. The Galion History Center now offers scheduled paranormal investigations and ghost tours in the cottage, including recurring public investigation dates.', 'limited', 'https://galion.squarespace.com/paranormal', 'America/New_York', now()),
  ('Historic Jail and Sheriff''s Residence', 'historic-jail-and-sheriffs-residence', 'haunted', 40.3018, -83.0689, 'Delaware', 'OH', 'Delaware County''s brick jail and attached sheriff''s residence were completed in 1878 and continued holding prisoners until 1988. The preserved complex now operates as a historic site with scheduled tours and seasonal lights-out ghost hunts, so visitors need to attend an official opening or event rather than entering on their own.', 'limited', 'https://www.visitdelohio.com/events/ghost-hunts-at-the-historic-jail-and-sheriffs-residence/', 'America/New_York', now()),
  ('The Anchorage Mansion', 'the-anchorage-mansion', 'haunted', 39.41441, -81.46333, 'Marietta', 'OH', 'The Anchorage, originally called Putnam Villa, was built in 1859 and survives as one of Marietta''s imposing nineteenth-century houses. Hidden Marietta uses the property for guided haunted-history tours, flashlight tours and paranormal investigations, with entry limited to scheduled programs and reservations.', 'limited', 'https://hiddenmarietta.com/the-anchorage-mansion', 'America/New_York', now()),
  ('Aullwood Giant Trolls', 'aullwood-giant-trolls', 'roadside-oddities', 39.88121, -84.27081, 'Dayton', 'OH', 'Artist Thomas Dambo created three enormous trolls named Bo, Bodil and Bibbi from reclaimed wood for Aullwood Audubon, turning the preserve into a giant-creature scavenger hunt. The trolls remain on the nature trails even though the original giant nest was removed in 2025; admission is required and reaching all of them involves roughly one to two miles of walking.', 'limited', 'https://www.audubon.org/aullwood/explore/troll-hatched-egg-exhibit', 'America/New_York', now()),
  ('Haserot Angel', 'haserot-angel', 'roadside-oddities', 41.51302, -81.59038, 'Cleveland', 'OH', 'The Haserot family memorial in Lake View Cemetery features a life-sized bronze angel created by sculptor Herman Matzen in 1919. Weathering has produced dark streaks beneath its eyes that make the figure appear to cry black tears, earning it the nickname Angel of Death; visitors can see it in Section 9 during cemetery hours.', 'open', 'https://www.atlasobscura.com/places/the-haserot-angel', 'America/New_York', now()),
  ('Paul A. Johnson Pencil Sharpener Museum', 'paul-a-johnson-pencil-sharpener-museum', 'museums', 39.53632, -82.44459, 'Logan', 'OH', 'This tiny museum beside the Hocking Hills Regional Welcome Center holds thousands of pencil sharpeners collected by the late Paul A. Johnson and later expanded through additional donations. The display ranges from ordinary desk sharpeners to novelty designs shaped like animals, landmarks and household objects and can be visited during welcome-center hours.', 'open', 'https://www.explorehockinghills.com/things-to-do/arts-museums/museums/pencil-sharpener-museum/', 'America/New_York', now()),
  ('Merry-Go-Round Museum', 'merry-go-round-museum', 'museums', 41.45393, -82.7129, 'Sandusky', 'OH', 'The Merry-Go-Round Museum opened in 1990 inside Sandusky''s former post office to preserve the art and history of carousel carving. Visitors can see restored and in-progress carousel figures, watch carving demonstrations when available and ride the museum''s working indoor carousel.', 'open', 'https://merrygoroundmuseum.org/', 'America/New_York', now()),
  ('Castle Noel', 'castle-noel', 'museums', 41.13689, -81.86363, 'Medina', 'OH', 'Castle Noel is a year-round Christmas museum built around an enormous collection of Hollywood holiday-movie props, costumes, department-store displays and animated window scenes. It opened in Medina in 2013 and operates as a guided ticketed attraction, so reservations are recommended even though it is not limited to the Christmas season.', 'open', 'https://castlenoel.com/', 'America/New_York', now()),
  ('Ernest Warther Museum & Gardens', 'ernest-warther-museum-gardens', 'museums', 40.52566, -81.48804, 'Dover', 'OH', 'Master carver Ernest "Mooney" Warther spent decades creating extraordinarily detailed working models of steam engines from wood, ivory and other materials. His workshop, family home, carvings, button collection and gardens are preserved together as a museum complex that visitors can tour during posted hours.', 'open', 'https://thewarthermuseum.com/', 'America/New_York', now()),
  ('BibleWalk', 'biblewalk', 'museums', 40.78577, -82.49666, 'Mansfield', 'OH', 'BibleWalk is a wax museum containing more than 300 figures arranged in dozens of life-sized scenes drawn from the Bible. Built largely through the work of the neighboring church congregation, it now offers multiple self-guided ticketed tours alongside smaller free exhibits.', 'open', 'https://biblewalk.us/', 'America/New_York', now()),
  ('The Secret Chamber House of Oddities and Artwork', 'the-secret-chamber-house-of-oddities-and-artwork', 'roadside-oddities', 39.82179, -84.02197, 'Fairborn', 'OH', 'The Secret Chamber is an oddities shop and gallery packed with sideshow-style specimens, skeletons, unusual taxidermy, purported haunted objects and macabre artwork. It opened in 2017 and remains a public retail stop, making it an easy detour for travelers who want something stranger than a conventional museum.', 'open', 'https://www.atlasobscura.com/places/the-secret-chamber-house-of-oddities-and-artwork', 'America/New_York', now()),
  ('Jungle Jim''s International Market', 'jungle-jims-international-market', 'roadside-oddities', 39.33508, -84.52425, 'Fairfield', 'OH', 'Jungle Jim''s is a massive international grocery store that doubles as a roadside attraction, filling its aisles with oversized decorations, animatronics, themed storefronts and deliberately bizarre displays. Travelers can shop normally while finding features such as singing characters and the famous faux portable-toilet entrance to the restrooms.', 'open', 'https://junglejims.com/', 'America/New_York', now()),
  ('Buzzard Roost', 'buzzard-roost', 'folklore', 41.21561, -81.70902, 'Hinckley Township', 'OH', 'Hinckley has celebrated the supposed annual return of turkey vultures every March since the 1950s, creating one of Ohio''s strangest recurring local traditions. Buzzard Roost in Hinckley Reservation is the public viewing area associated with the event, where Cleveland Metroparks continues to welcome visitors looking for the returning birds.', 'open', 'https://www.clevelandmetroparks.com/parks/visit/parks/hinckley-reservation/buzzard-roost', 'America/New_York', now()),
  ('Helltown at Boston Mill', 'helltown-at-boston-mill', 'folklore', 41.26259, -81.56031, 'Boston Township', 'OH', 'Federal land purchases around the former village of Boston in the 1970s left vacant buildings that helped fuel later urban legends about "Helltown," including stories of satanic churches, chemical disasters and mutant creatures. Most of the sensational landmarks described in those stories are gone or were never what the legends claimed, so Boston Mill Visitor Center in Cuyahoga Valley National Park is the legal public anchor for the story and visitors should not trespass on closed structures or private land.', 'open', 'https://en.wikipedia.org/wiki/Helltown,_Ohio', 'America/New_York', now()),
  ('Otherworld', 'otherworld', 'museums', 39.92214, -82.83583, 'Columbus', 'OH', 'Otherworld is a 32,000-square-foot immersive art attraction made up of dozens of interconnected rooms filled with large-scale installations, secret passages, surreal creatures and interactive technology. The Columbus experience opened in 2019 and operates as a ticketed indoor attraction during posted sessions.', 'open', 'https://www.otherworld.com/', 'America/New_York', now()),
  ('The Ohio Museum of Horror', 'the-ohio-museum-of-horror', 'museums', 40.73362, -82.78674, 'Galion', 'OH', 'The Ohio Museum of Horror is a year-round multi-floor collection devoted to horror films, true crime, occult material and macabre artifacts. Displays include movie memorabilia, Ouija boards, anatomical and funerary objects and other intentionally unsettling pieces, with public admission during posted museum hours.', 'open', 'https://www.natethompsonvideo.com/ohio', 'America/New_York', now()),
  ('The Sanctuary Museum', 'the-sanctuary-museum', 'museums', 41.47671, -81.77833, 'Lakewood', 'OH', 'Formerly known as the Museum of Divine Statues, the Sanctuary Museum preserves statues, stained glass and other sacred artwork rescued largely from closed or altered Catholic churches. The collection includes elaborate saints, relic-related objects and large architectural pieces and can be visited during its limited posted public hours.', 'open', 'https://www.thesanctuarymuseum.org/', 'America/New_York', now()),
  ('Victoria Theatre', 'victoria-theatre', 'haunted', 39.76223, -84.19174, 'Dayton', 'OH', 'Victoria Theatre opened in 1866 and has accumulated several long-running ghost stories during more than a century and a half of performances. The best-known involves the legendary "Miss Vicki," whose presence is associated with rose perfume, footsteps and a face in a dressing-room mirror; the theater remains an active public performance venue.', 'open', 'https://www.destinationdayton.org/blog/post/uncovering-eerie-legends-5-haunted-places-in-dayton-with-tales-to-know-about/', 'America/New_York', now()),
  ('Screaming Bridge of Maud Hughes Road', 'screaming-bridge-of-maud-hughes-road', 'haunted', 39.39449, -84.4104, 'Liberty Township', 'OH', 'The railroad overpass on Maud Hughes Road has accumulated decades of local stories involving screams, apparitions and a phantom train, alongside a documented history of serious accidents in the area. The old bridge was replaced and the roadway realigned in 2015, but the legend remains attached to the crossing; there is no pedestrian facility, so do not stop or park on the bridge or enter the railroad property.', 'roadside', 'https://www.ohioexploration.com/information/media/journalnews1/', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  verified_at   = excluded.verified_at;
