-- Ohio, part three.
--
-- World's Largest Horseshoe Crab is excluded. This list places it in
-- Hillsboro, which is where it used to be; it moved to Alabama around 2021 and
-- we corrected that record earlier today.
--
-- It nearly slipped through, and the reason is worth writing down: the
-- duplicate check compares slugs, and two different slug functions have been
-- used in this project. One turns an apostrophe into a dash, the other removes
-- it. So world-s-largest-horseshoe-crab and worlds-largest-horseshoe-crab are
-- the same object and do not look alike to a string comparison. Caught by
-- reading the list, not by the check.
--
-- Two coordinate flags, both fine: Alan Freed's grave is 238 metres from the
-- Haserot Angel, which is two graves in the same Cleveland cemetery, and the
-- Statehouse fossils are 243 metres from the World's Largest Gavel, which is
-- two things in downtown Columbus.
--
-- 49 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone, verified_at)
values
  ('Jacques the World''s Largest Bobblehead', 'jacques-the-worlds-largest-bobblehead', 'roadside-oddities', 40.64728, -82.54066, 'Bellville', 'OH', 'Jacques is a roughly 35-foot-tall fiberglass chef standing outside the Buckeye Express Diner along Route 97. The giant figure was restored after weather damage and remains an easy public-facing stop on the diner property.', 'open', 'https://www.atlasobscura.com/places/jacques-worlds-largest-bobblehead', 'America/New_York', now()),
  ('Center of the World', 'center-of-the-world', 'weird-history', 41.228, -80.91, 'Leavittsburg', 'OH', 'The tiny crossroads community called Center of the World was named in the 1840s by businessman Randall D. Wilmot, who hoped the stagecoach stop would become an important settlement. The dream never materialized, but an official green highway sign still marks the oddly named place near the junction of OH-82 and OH-5/OH-534; view it safely from a legal roadside position.', 'roadside', 'https://www.roadsideamerica.com/story/66691', 'America/New_York', now()),
  ('Lucky Cat Museum', 'lucky-cat-museum', 'museums', 39.12722, -84.49917, 'Cincinnati', 'OH', 'The Lucky Cat Museum contains thousands of maneki-neko, the Japanese beckoning-cat figures associated with good fortune, inside Cincinnati''s Essex Studios. The collection moved into its current first-floor space in 2016 and is free to visit, but current visits are by appointment during limited afternoon hours.', 'limited', 'https://www.visitcincy.com/listing/lucky-cat-museum/6267/', 'America/New_York', now()),
  ('Early Television Museum', 'early-television-museum', 'museums', 40.03451, -83.16161, 'Hilliard', 'OH', 'The Early Television Museum preserves more than 150 television sets and related artifacts spanning mechanical television, early electronic sets, color television and broadcast history. Visitors can see restored equipment and rare experimental technology during the museum''s posted weekend hours.', 'open', 'https://www.earlytelevision.org/museum.html', 'America/New_York', now()),
  ('Hollow Earth Monument', 'hollow-earth-monument', 'weird-history', 39.39477, -84.56241, 'Hamilton', 'OH', 'This unusual monument marks the grave of John Cleves Symmes Jr., the nineteenth-century Army officer who argued that the Earth was hollow and accessible through enormous openings near the poles. His son erected the stone topped with a hollow globe, and it remains publicly accessible in Hamilton''s Ludlow Park.', 'open', 'https://www.atlasobscura.com/places/hollow-earth-monument', 'America/New_York', now()),
  ('Goodyear Airdock', 'goodyear-airdock', 'weird-history', 41.03194, -81.47083, 'Akron', 'OH', 'Completed in 1929, the Goodyear Airdock was built to construct and house enormous lighter-than-air craft and was once one of the world''s largest buildings without interior supports. The industrial facility is not a public attraction, but the immense black hangar can be viewed from surrounding public roads without entering the secured property.', 'roadside', 'https://www.atlasobscura.com/places/goodyear-airdock', 'America/New_York', now()),
  ('World''s Largest Our Lady of Guadalupe Statue', 'worlds-largest-our-lady-of-guadalupe-statue', 'roadside-oddities', 41.56818, -80.99522, 'Windsor', 'OH', 'The Servants of Mary Center for Peace is home to a roughly 50-foot statue of Our Lady of Guadalupe rising above the rural grounds. The religious complex welcomes visitors to its outdoor devotional areas, making the towering figure a publicly accessible roadside destination rather than something that needs to be viewed from private land.', 'open', 'https://www.atlasobscura.com/places/servants-of-mary-center-for-peace', 'America/New_York', now()),
  ('World''s Largest Pumpkin Water Tower', 'worlds-largest-pumpkin-water-tower', 'roadside-oddities', 39.58834, -82.94297, 'Circleville', 'OH', 'Circleville''s one-million-gallon water tower was painted in 1997 to resemble a giant orange pumpkin, reflecting the city''s famous annual Pumpkin Show. The tower remains part of the working water system and is best viewed and photographed from surrounding public streets rather than approached as a walk-in attraction.', 'roadside', 'https://www.atlasobscura.com/places/worlds-largest-pumpkin-water-tower', 'America/New_York', now()),
  ('Gates of Hell', 'gates-of-hell', 'folklore', 40.01839, -83.01199, 'Columbus', 'OH', 'A large storm-drain tunnel beneath North High Street has acquired the nickname Gates of Hell and a collection of urban legends involving deaths, strange noises and supposedly supernatural encounters. The tunnel itself is drainage infrastructure and should not be entered; treat this as a view-from-public-ground folklore stop only.', 'roadside', 'https://www.atlasobscura.com/places/gates-of-hell', 'America/New_York', now()),
  ('Ohio Caverns', 'ohio-caverns', 'roadside-oddities', 40.23853, -83.69922, 'West Liberty', 'OH', 'Ohio Caverns was discovered in 1897 and contains extensive passageways filled with stalactites, stalagmites and other mineral formations, including the enormous white formation known as the Crystal King. The privately operated attraction offers guided underground tours during posted hours.', 'open', 'https://www.atlasobscura.com/places/ohio-caverns', 'America/New_York', now()),
  ('Crystal Cave', 'crystal-cave', 'roadside-oddities', 41.64661, -82.82672, 'Put-in-Bay', 'OH', 'Crystal Cave was discovered in 1887 beneath what is now Heineman''s Winery and is actually the interior of an enormous celestite geode. Visitors can descend into the sparkling blue-purple chamber on seasonal guided tours, generally during the Lake Erie island tourism season.', 'limited', 'https://www.atlasobscura.com/places/crystal-cave', 'America/New_York', now()),
  ('Benson Ford Shiphouse', 'benson-ford-shiphouse', 'roadside-oddities', 41.65072, -82.83951, 'Put-in-Bay', 'OH', 'The forward section of the 1924 lake freighter Benson Ford was removed from the ship and placed on a South Bass Island bluff in 1986, creating a private residence that looks like a ship sailing through the trees. The house is not normally open to the public except for occasional announced charity tours, so view it only from legal public areas and do not enter the property.', 'private', 'https://www.shiponthebay.com/', 'America/New_York', now()),
  ('ASM International Geodesic Dome', 'asm-international-geodesic-dome', 'roadside-oddities', 41.46009, -81.29941, 'Novelty', 'OH', 'ASM International''s headquarters is covered by a huge open-air geodesic dome built in the late 1950s from an aluminum framework. The office building itself is not a general tourist attraction, but the landscaped Materials Park and exterior dome can be viewed during the property''s posted public-ground hours.', 'open', 'https://www.atlasobscura.com/places/asm-international-materials-park', 'America/New_York', now()),
  ('Judy''s Jungle', 'judys-jungle', 'roadside-oddities', 41.68056, -81.32993, 'Mentor', 'OH', 'Judy''s Jungle is a collection of large fiberglass animals gathered outside an industrial property in Mentor, including elephants, giraffes and other oversized creatures. The quirky display is intentionally visible to passersby and visitors can stop to see the figures without entering restricted industrial areas.', 'open', 'https://www.atlasobscura.com/places/judys-jungle', 'America/New_York', now()),
  ('Topiary Park', 'topiary-park', 'roadside-oddities', 39.96115, -82.98762, 'Columbus', 'OH', 'Topiary Park recreates Georges Seurat''s painting A Sunday Afternoon on the Island of La Grande Jatte using sculpted shrubs instead of paint. More than 50 human figures along with boats, animals and landscape forms fill the public park, which can be walked during normal park hours.', 'open', 'https://www.atlasobscura.com/places/the-topiary-park', 'America/New_York', now()),
  ('Alan Freed''s Jukebox Grave', 'alan-freeds-jukebox-grave', 'weird-history', 41.51413, -81.59282, 'Cleveland', 'OH', 'Disc jockey Alan Freed, who helped popularize the term rock and roll, was reinterred at Lake View Cemetery in 2016 after his ashes had previously been displayed at the Rock & Roll Hall of Fame. His grave is marked by a distinctive jukebox-shaped monument that can be visited during cemetery hours.', 'open', 'https://www.atlasobscura.com/places/grave-of-alan-freed', 'America/New_York', now()),
  ('Arnold Schwarzenegger Statue', 'arnold-schwarzenegger-statue', 'roadside-oddities', 39.9721, -83.00225, 'Columbus', 'OH', 'An approximately eight-foot bronze statue of Arnold Schwarzenegger in a bodybuilding pose stands outside the Greater Columbus Convention Center. The sculpture honors Schwarzenegger''s long connection to Columbus and the Arnold Sports Festival and is freely visible from the public plaza.', 'open', 'https://www.atlasobscura.com/places/arnold-schwarzenegger-statue', 'America/New_York', now()),
  ('Merchant Ball', 'merchant-ball', 'folklore', 40.57664, -83.12201, 'Marion', 'OH', 'The Merchant family grave at Marion Cemetery is topped by a roughly 5,200-pound granite sphere that has slowly rotated on its pedestal over the decades. No definitive supernatural explanation is needed for the movement, but the visibly shifting stone has become a longstanding cemetery mystery; visit respectfully during cemetery hours.', 'open', 'https://www.atlasobscura.com/places/merchant-ball', 'America/New_York', now()),
  ('World''s Largest Tomato Soup Can', 'worlds-largest-tomato-soup-can', 'roadside-oddities', 41.40161, -84.10084, 'Napoleon', 'OH', 'A huge Campbell''s tomato-soup-can water tower rises above the company''s Napoleon-area processing plant and is commonly promoted as the world''s largest representation of the familiar can. The tower is inside an active industrial property, so photograph it from a safe public roadside location and do not enter the factory grounds without permission.', 'roadside', 'https://www.ohiomagazine.com/ohio-life/article/giant-tomato-soup-can', 'America/New_York', now()),
  ('GE Chandelier', 'ge-chandelier', 'roadside-oddities', 41.50068, -81.68159, 'Cleveland', 'OH', 'Playhouse Square''s outdoor chandelier was installed in 2014 above East 14th Street and was promoted as the largest outdoor chandelier in North America. Thousands of crystals and LED lights hang above the theater district, and visitors can walk beneath it from the public sidewalk and plaza.', 'open', 'https://www.playhousesquare.org/news/detail/all-about-our-ge-chandelier', 'America/New_York', now()),
  ('Cardboard Boat Museum', 'cardboard-boat-museum', 'museums', 38.95218, -84.28484, 'New Richmond', 'OH', 'The Cardboard Boat Museum calls itself the world''s only museum devoted entirely to boats made from cardboard and preserves vessels, photographs and history connected to New Richmond''s famous cardboard-boat races. Admission is free during its posted seasonal or weekend hours.', 'open', 'https://cardboardboatmuseum.com/visitors/', 'America/New_York', now()),
  ('National Barber Museum and Hall of Fame', 'national-barber-museum-and-hall-of-fame', 'museums', 39.84087, -82.81024, 'Canal Winchester', 'OH', 'The National Barber Museum preserves barber chairs, razors, signs, poles, tools and other material from the history of barbering in America. The collection dates back to the museum''s founding in 1988, but current public hours are limited, so check the museum''s schedule or appointment information before routing here.', 'limited', 'https://www.nationalbarbermuseum.com/', 'America/New_York', now()),
  ('Piatt Castle Mac-A-Cheek', 'piatt-castle-mac-a-cheek', 'roadside-oddities', 40.25106, -83.72691, 'West Liberty', 'OH', 'Mac-A-Cheek is an elaborate nineteenth-century stone mansion built by the Piatt family and filled with unusual carved woodwork, painted ceilings and family collections. It survives as the publicly toured half of the Piatt Castles property, with access generally limited to seasonal scheduled hours.', 'limited', 'https://www.atlasobscura.com/places/piatt-castles', 'America/New_York', now()),
  ('USS Maine Bathtub', 'uss-maine-bathtub', 'weird-history', 41.0374, -83.6561, 'Findlay', 'OH', 'The Hancock Historical Museum preserves a bathtub recovered from the wreckage of the USS Maine, whose 1898 destruction in Havana Harbor helped push the United States toward the Spanish-American War. The oddly domestic survivor is displayed inside the museum and can be seen during regular public hours.', 'open', 'https://www.ohiomagazine.com/ohio-life/article/bathtub-from-the-uss-maine-findlay', 'America/New_York', now()),
  ('Wyandot Popcorn Museum', 'wyandot-popcorn-museum', 'museums', 40.58705, -83.12685, 'Marion', 'OH', 'The Wyandot Popcorn Museum fills a large historic building with antique popcorn wagons, peanut roasters and other equipment from the history of America''s popcorn industry. The museum is seasonal and closes for part of the year, so visitors should check current hours before making it a route stop.', 'limited', 'https://www.marionhistory.com/explore/wyandot-popcorn-museum/', 'America/New_York', now()),
  ('National Cleveland-Style Polka Hall of Fame', 'national-cleveland-style-polka-hall-of-fame', 'museums', 41.59907, -81.52569, 'Euclid', 'OH', 'This small museum documents Cleveland-style polka and the musicians, accordions, recordings and immigrant communities that shaped it. Exhibits and the hall of fame are open only on limited weekly hours, making it a niche but very specific destination rather than an anytime stop.', 'limited', 'https://clevelandstyle.com/', 'America/New_York', now()),
  ('Kelleys Island Glacial Grooves', 'kelleys-island-glacial-grooves', 'weird-history', 41.61363, -82.70539, 'Kelleys Island', 'OH', 'A retreating Ice Age glacier carved enormous parallel grooves into the limestone of Kelleys Island, leaving some of the largest and most accessible glacial striations in the world. A walkway surrounds the protected geological feature, but reaching it requires travel to the Lake Erie island, with ferry service varying by season and weather.', 'limited', 'https://kelleysisland.com/listing/glacial-grooves/', 'America/New_York', now()),
  ('Worden''s Ledges', 'wordens-ledges', 'roadside-oddities', 41.20362, -81.71882, 'Hinckley Township', 'OH', 'Hidden among sandstone ledges in Hinckley Reservation are faces, animals, religious imagery and other figures carved into the rock by Noble Stuart in the mid-twentieth century. The carvings are reached on a short wooded trail, so this is a hike rather than a roadside pull-off.', 'limited', 'https://www.atlasobscura.com/places/wordens-ledges', 'America/New_York', now()),
  ('Leo Petroglyph', 'leo-petroglyph', 'weird-history', 39.15091, -82.67472, 'Ray', 'OH', 'The Leo Petroglyph contains dozens of prehistoric figures carved into a sandstone outcrop, including humans, animals and abstract forms associated with Indigenous people of the region. A protective shelter covers the carvings and the state historic site is accessible to visitors from the adjoining public area.', 'open', 'https://www.atlasobscura.com/places/leo-petroglyph', 'America/New_York', now()),
  ('Vasehenge', 'vasehenge', 'roadside-oddities', 39.93945, -82.01552, 'Zanesville', 'OH', 'Vasehenge was a circle of enormous painted ceramic vases installed as a tribute to Zanesville''s pottery heritage. The installation has been removed and is no longer accessible, but the former location is worth recording as a closed OddWay stop rather than sending travelers there expecting the giant vases to remain.', 'closed', 'https://www.atlasobscura.com/places/vasehenge', 'America/New_York', now()),
  ('Squire''s Castle', 'squires-castle', 'haunted', 41.57994, -81.41926, 'Willoughby Hills', 'OH', 'Squire''s Castle is the stone gatehouse of an estate that Standard Oil executive Feargus B. Squire planned but never completed. Stories later developed about the ghost of Squire''s wife haunting the building, although the tale does not match the documented family history; the castle itself remains freely accessible in Cleveland Metroparks during park hours.', 'open', 'https://www.atlasobscura.com/places/squires-castle', 'America/New_York', now()),
  ('Kelleys Island Winery Ruins', 'kelleys-island-winery-ruins', 'weird-history', 41.60142, -82.72943, 'Kelleys Island', 'OH', 'Stone ruins from Kelleys Island''s nineteenth-century wine industry survive near Maple Drive, remnants of an era when Lake Erie islands were major American grape-growing centers. The ruins are on private property, so they should be viewed only from the public road without entering the site.', 'private', 'https://www.atlasobscura.com/places/kelleys-island-winery-ruins', 'America/New_York', now()),
  ('Hotel Victory Ruins', 'hotel-victory-ruins', 'weird-history', 41.64556, -82.83816, 'Put-in-Bay', 'OH', 'The enormous Hotel Victory opened on South Bass Island in the 1890s and burned in 1919, leaving behind foundations, portions of its pool and scattered structural remains. The ruins lie around South Bass Island State Park''s campground area, and some are within camper-only sections, so visitors should follow park access rules rather than wandering through occupied campsites.', 'limited', 'https://www.atlasobscura.com/places/hotel-victory-ruins', 'America/New_York', now()),
  ('Zanesville Y-Bridge', 'zanesville-y-bridge', 'roadside-oddities', 39.94042, -82.01431, 'Zanesville', 'OH', 'Zanesville''s bridge over the confluence of the Licking and Muskingum rivers splits into three directions, creating the unusual Y shape that has defined the crossing for generations. The current structure is the fifth bridge at the location and can be driven across or viewed from nearby public riverfront areas.', 'roadside', 'https://www.atlasobscura.com/places/zanesville-ybridge', 'America/New_York', now()),
  ('Avrocar', 'avrocar', 'ufos', 39.78225, -84.10767, 'Dayton', 'OH', 'The Avrocar was a real Cold War attempt to build a disc-shaped vertical-takeoff aircraft that looked remarkably like the flying saucers dominating UFO culture at the time. One surviving example is displayed inside the National Museum of the United States Air Force, where admission is free during museum hours.', 'open', 'https://www.atlasobscura.com/places/avrocar', 'America/New_York', now()),
  ('Percy Skuy Collection on the History of Contraception', 'percy-skuy-collection-on-the-history-of-contraception', 'museums', 41.50596, -81.60844, 'Cleveland', 'OH', 'The Dittrick Medical History Center holds the Percy Skuy Collection, roughly 1,100 historical contraceptive devices, prototypes, packaging pieces and related artifacts assembled into one of the most extensive collections of its kind. The museum is free and open to the public, but as of 2026 its regular gallery hours are limited to Fridays and Saturdays.', 'limited', 'https://artsci.case.edu/dittrick/collections/aritfacts/contraception-collection/', 'America/New_York', now()),
  ('Hillandale Bridge', 'hillandale-bridge', 'weird-history', 41.59097, -81.49117, 'Euclid', 'OH', 'This abandoned concrete bridge was built for a 1920s residential development that never materialized, leaving a substantial bridge standing alone in the woods. It can be reached from trails in the Hillandale Park area, but the structure is weathered and damaged, so visitors should stay on established legal access routes and avoid climbing unsafe sections.', 'limited', 'https://www.atlasobscura.com/places/hillandale-bridge', 'America/New_York', now()),
  ('Hopkins Hall Handprint', 'hopkins-hall-handprint', 'folklore', 40.00098, -83.0116, 'Columbus', 'OH', 'Ohio State folklore says an art student became trapped in a Hopkins Hall elevator overnight and left frantic handprints behind while trying to escape. Versions of the story claim a mysterious handprint still reappears on the exterior of the building; the site is on a public university campus, though visitors should not disrupt classes or enter closed spaces looking for it.', 'open', 'https://artsandsciences.osu.edu/news/campus-legends-horrors-and-lore', 'America/New_York', now()),
  ('The Girl in Blue Grave', 'the-girl-in-blue-grave', 'weird-history', 41.63921, -81.4115, 'Willoughby', 'OH', 'An unidentified young woman dressed entirely in blue was struck and killed by a train in Willoughby on Christmas Eve 1933, and local residents paid for her burial and a marker reading "Unknown but not forgotten." She was identified decades later as Josephine "Sophie" Klimczak, and a second marker now gives her name beside the original grave in Willoughby Village Cemetery.', 'open', 'https://www.atlasobscura.com/places/the-girl-in-blue-willoughby-ohio', 'America/New_York', now()),
  ('Ohio Statehouse Fossils', 'ohio-statehouse-fossils', 'weird-history', 39.9601, -82.99946, 'Columbus', 'OH', 'The limestone used throughout the Ohio Statehouse contains visible fossils from ancient seas, including corals, brachiopods, sponges and other marine life hundreds of millions of years old. Visitors can use the state''s fossil guide to hunt for them in public portions of the Capitol building during open hours.', 'open', 'https://www.atlasobscura.com/places/ohio-statehouse-fossils', 'America/New_York', now()),
  ('Langsdon Mineral Collection', 'langsdon-mineral-collection', 'museums', 40.55122, -84.57146, 'Celina', 'OH', 'The Mercer County District Library displays the Ron and Ruth Langsdon Mineral Collection, containing hundreds of colorful and rare mineral specimens from around the world. The collection is free to view during library hours, with occasional guided programs offering a closer look at the specimens.', 'open', 'https://mercerlibrary.org/', 'America/New_York', now()),
  ('Anti-Saloon League Museum', 'anti-saloon-league-museum', 'museums', 40.12295, -82.92939, 'Westerville', 'OH', 'Westerville was national headquarters of the Anti-Saloon League, one of the organizations most responsible for pushing the United States toward Prohibition. The Westerville History Museum occupies part of the League''s former headquarters and preserves its propaganda, publications and archives; walk-in visitors can view current exhibits during library museum hours.', 'open', 'https://westervillelibrary.org/museum/', 'America/New_York', now()),
  ('Fernald Preserve Visitors Center', 'fernald-preserve-visitors-center', 'weird-history', 39.28805, -84.68354, 'Hamilton', 'OH', 'The Fernald site produced uranium metal for the U.S. nuclear weapons program during the Cold War before shutting down production in 1989 and undergoing a massive environmental cleanup. It is now a Department of Energy nature preserve, and the free visitor center contains exhibits on uranium production, contamination, remediation and the site''s transformation into public trails and habitat.', 'open', 'https://www.energy.gov/lm/fernald-preserve-ohio-site', 'America/New_York', now()),
  ('Cathedral Tower', 'cathedral-tower', 'weird-history', 41.14894, -81.50628, 'Cuyahoga Falls', 'OH', 'Televangelist Rex Humbard began building a 750-foot tower in 1971 that was supposed to contain a revolving restaurant and support television broadcasting from his Cathedral of Tomorrow complex. Construction abruptly stopped when the concrete shaft reached 494 feet, and the unfinished tower still dominates the skyline as a communications structure; view it from public roads and do not enter the fenced property.', 'roadside', 'https://www.summitmemory.org/digital/collection/ABJarchives/id/2497/', 'America/New_York', now()),
  ('Chef Boyardee''s Grave', 'chef-boyardees-grave', 'weird-history', 41.59212, -81.26771, 'Chardon', 'OH', 'Hector Boiardi, the Italian-born chef whose name became the Chef Boyardee brand, is entombed in the Crucifixion Mausoleum at All Souls Cemetery. Visitors can find his crypt in the Sacred Heart aisle during cemetery and mausoleum access hours, but this remains an active burial place and should be visited respectfully.', 'open', 'https://www.atlasobscura.com/places/grave-of-chef-boyardee', 'America/New_York', now()),
  ('Cincinnati Subway', 'cincinnati-subway', 'weird-history', 39.13663, -84.53281, 'Cincinnati', 'OH', 'Cincinnati began building an underground rapid-transit system in the 1920s using the former Miami and Erie Canal route, but the project was abandoned before any trains ever ran. Sections of tunnel and four unfinished stations still survive beneath the city, but official tours ended years ago and the sealed tunnels are illegal and unsafe to enter; record this as a closed historical stop only.', 'closed', 'https://www.atlasobscura.com/places/the-cincinnati-subway-cincinnati-ohio', 'America/New_York', now()),
  ('Porter Creek Bridge Ruins', 'porter-creek-bridge-ruins', 'weird-history', 41.48764, -81.93649, 'Bay Village', 'OH', 'Concrete bridge piers from an early-twentieth-century electric railway still rise from the wooded Porter Creek valley after the line was abandoned and dismantled. The ruins can be reached legally on foot from the Lake Erie Nature & Science Center area using public paths, but visitors need to hike into the valley rather than drive directly to them.', 'limited', 'https://www.atlasobscura.com/places/porter-creek-bridge-ruins', 'America/New_York', now()),
  ('Morgan County Dungeon', 'morgan-county-dungeon', 'weird-history', 39.64924, -81.86208, 'Malta', 'OH', 'An underground holding cell used for prisoners in the 1830s was forgotten for more than a century before being rediscovered during excavation in 1964. The dungeon survives near the county jail complex with a historical marker and artifacts, but interior access is not a normal anytime attraction and should be confirmed locally before visiting.', 'limited', 'https://www.atlasobscura.com/places/morgan-county-dungeon-ohio', 'America/New_York', now()),
  ('Dawes Arboretum Hedge Letters', 'dawes-arboretum-hedge-letters', 'roadside-oddities', 39.98013, -82.4131, 'Newark', 'OH', 'More than a thousand northern white cedars planted beginning in 1942 form enormous letters spelling out DAWES ARBORETUM across the landscape. Visitors can walk near the hedge and climb the arboretum''s observation tower for a better view, with entry subject to the arboretum''s current admission and operating hours.', 'open', 'https://www.atlasobscura.com/places/dawes-arboretum-hedge-letters', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  verified_at   = excluded.verified_at;
