-- Ohio, part one.
--
-- Ohio had ten stops, four of them world's-largest objects and three of them
-- Halloween attractions. This is the state as it actually is: the Loveland
-- Frogman, the Ohio State Reformatory, Franklin Castle, a lake monster in a
-- reservoir, and a mural of a python that escaped in 1944 and was never found.
--
-- Two dropped as already present under other names: the Sugarcreek cuckoo
-- clock (260 metres from the existing record) and the Warren drumsticks, which
-- we hold as World's Largest Drumsticks rather than Dave Grohl Alley.
--
-- The World's Largest Gavel is 346 metres from Fear Columbus and stays: two
-- unrelated things a few blocks apart in downtown Columbus.
--
-- 42 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, phone, opening_hours, timezone, verified_at)
values
  ('Loveland Frogman Riverfront', 'loveland-frogman-riverfront', 'cryptids', 39.26984, -84.25816, 'Loveland', 'OH', 'The Loveland Frogman, a human-sized frog-like creature associated with the Little Miami River, has been part of local folklore since reported encounters beginning in 1955. Loveland now treats the creature as an official city mascot, and Nisbet Park gives travelers a public riverfront stop directly tied to the legend and the city''s recurring Return of the Frogman celebration.', 'open', 'https://lovelandoh.gov/491/City-Mascot', null, null, null, 'America/New_York', now()),
  ('Salt Fork Bigfoot Search', 'salt-fork-bigfoot-search', 'cryptids', 40.10593, -81.52868, 'Jefferson Township', 'OH', 'Salt Fork State Park is one of Ohio''s best-known Bigfoot areas, with decades of reported sightings of the creature sometimes called the Ohio Grassman. Salt Fork Lodge actively embraces the legend: visitors can pick up a Bigfoot sightings map at the front desk and search the surrounding public park trails, and the lodge hosts the annual Ohio Bigfoot Conference.', 'open', 'https://www.saltforkparklodge.com/things-to-do/onsite-activities', null, null, null, 'America/New_York', now()),
  ('Charles Mill Lake Monster', 'charles-mill-lake-monster', 'cryptids', 40.76533, -82.37155, 'Mifflin Township', 'OH', 'In 1959, three teenagers reported encountering a large armless humanoid with glowing green eyes and webbed feet near Charles Mill Lake, creating the legend of the Charles Mill Lake Monster. Charles Mill Marina has displayed the story for visitors behind its counter, giving the otherwise localized cryptid report a specific destination; the marina operates seasonally.', 'limited', 'https://www.richlandsource.com/2015/10/29/what-monster-lurks-at-charles-mill-lake/', null, null, null, 'America/New_York', now()),
  ('Peninsula Python Mural', 'peninsula-python-mural', 'cryptids', 41.2397, -81.55402, 'Peninsula', 'OH', 'In 1944, reports of a roughly 15-to-18-foot snake supposedly loose around Peninsula triggered searches and national attention, although the Peninsula Python was never found. The large 1964 mural on the front of Peninsula Library maps the winding Cuyahoga River valley and has become physically associated with the monster-snake legend, making it an easy public stop in town.', 'open', 'https://peninsulalibrary.org/about/mural/', null, null, null, 'America/New_York', now()),
  ('Devil''s Backbone Marker', 'devils-backbone-marker', 'folklore', 39.6258, -84.6705, 'Camden', 'OH', 'This rocky cliff along Paint Creek has been called the Devil''s Backbone since at least 1877 and has accumulated stories involving Bigfoot, hidden mines, missing skunks and a supposed curse. A Legends & Lore marker now stands at Herbert & Patricia Wagers Memorial Park, where visitors can also use the public walking and hiking trails.', 'open', 'https://www.wgpfoundation.org/historic-markers/devils-backbone/', null, null, null, 'America/New_York', now()),
  ('Mary''s Ghost at the Friends Home', 'marys-ghost-at-the-friends-home', 'haunted', 39.53116, -84.08986, 'Waynesville', 'OH', 'Local legend says a young girl named Mary disappeared after her parents became ill in the early nineteenth century and that her laughing spirit still waits for her mother at what is now the Museum at the Friends Home. A Legends & Lore marker stands at the museum, where stories describe Mary rocking inside or appearing on the front porch; interior access follows the museum''s schedule.', 'limited', 'https://www.wgpfoundation.org/historic-markers/marys-ghost/', null, null, null, 'America/New_York', now()),
  ('Harry S. Thobe Ghost Marker', 'harry-s-thobe-ghost-marker', 'folklore', 39.50051, -84.74575, 'Oxford', 'OH', 'Harry Thobe was a stonemason and famous Miami University superfan who built the house at this location and maintained a stone fountain on campus until his death in 1950. Legend says that calling Thobe''s name near the former fountain site may produce an answering echo; the Legends & Lore marker is at his former Chestnut Street home, so view it from the public right-of-way and do not disturb the residence.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/harry-s-thobe/', null, null, null, 'America/New_York', now()),
  ('Ohio State Reformatory', 'ohio-state-reformatory', 'haunted', 40.78373, -82.50275, 'Mansfield', 'OH', 'The Ohio State Reformatory was built beginning in 1886 and operated as a prison until 1990 before becoming a museum and preservation site. Beyond its use as a filming location for The Shawshank Redemption, the enormous cellblocks have a major paranormal reputation and the reformatory offers both regular tours and structured ghost-hunting programs.', 'open', 'https://www.mrps.org/visit/', null, null, null, 'America/New_York', now()),
  ('Franklin Castle', 'franklin-castle', 'haunted', 41.48611, -81.71611, 'Cleveland', 'OH', 'Built for German immigrant Hannes Tiedemann in the early 1880s, Franklin Castle became one of Cleveland''s most persistent haunted-house legends after a series of deaths and later stories of apparitions and hidden rooms. The restored private venue offers scheduled tours, storytelling events and overnight experiences, but it is not a casual walk-in attraction.', 'limited', 'https://thefranklincastle.com/stay-the-night/', null, null, null, 'America/New_York', now()),
  ('Punderson Manor', 'punderson-manor', 'haunted', 41.45108, -81.20787, 'Newbury Township', 'OH', 'The Tudor-style Punderson Manor operates as the lodge at Punderson State Park and has accumulated long-running stories of footsteps, children''s laughter, moving objects and other unexplained activity. It remains a working state-park lodge and restaurant, so visitors can experience the building normally without entering restricted guest areas.', 'open', 'https://www.ohiotraveler.com/punderson-manor/', null, null, null, 'America/New_York', now()),
  ('Fairport Harbor Ghost Cat Lighthouse', 'fairport-harbor-ghost-cat-lighthouse', 'haunted', 41.75709, -81.27734, 'Fairport Harbor', 'OH', 'The 1871 Fairport Harbor lighthouse and keeper''s house now operate as a seasonal marine museum, but their strangest resident is said to be a ghostly gray cat seen darting through the former living quarters. During renovation work, a mummified gray cat was found in a crawl space and is now part of the museum''s story; the museum and tower are seasonal.', 'limited', 'https://en.wikipedia.org/wiki/Fairport_Harbor_Light', null, null, null, 'America/New_York', now()),
  ('Collingwood Arts Center', 'collingwood-arts-center', 'haunted', 41.66874, -83.55621, 'Toledo', 'OH', 'The massive building now known as the Collingwood Arts Center began as a convent and school complex associated with the Ursuline order and later became an arts facility. Its old dormitories, theater and corridors have generated enough paranormal reports that the center offers scheduled public and private ghost hunts; tours and investigations require arranging access rather than wandering the building.', 'limited', 'https://www.collingwoodartscenter.org/services', null, null, null, 'America/New_York', now()),
  ('South Bass Island Lighthouse', 'south-bass-island-lighthouse', 'haunted', 41.6291, -82.8414, 'Put-in-Bay Township', 'OH', 'The South Bass Island Lighthouse was completed in 1897, and tragedy arrived almost immediately when assistant keeper Harry Anderson died during the island''s 1898 smallpox outbreak. The lighthouse later developed stories of unexplained activity connected to its keepers; the grounds can be viewed publicly, while interior and tower access is limited to scheduled open houses or tours.', 'limited', 'https://www.visitputinbay.org/haunted-spirits-put-in-bay/', null, null, null, 'America/New_York', now()),
  ('Loveland Castle', 'loveland-castle', 'roadside-oddities', 39.28358, -84.266, 'Loveland', 'OH', 'Harry Andrews began building Château Laroche, better known as Loveland Castle, along the Little Miami River in the 1920s using stone and hand-formed construction methods. The medieval-style castle became headquarters for his Knights of the Golden Trail and now operates as a museum where visitors can explore the rooms, towers and grounds during posted hours.', 'open', 'https://lovelandcastle.com/', null, null, null, 'America/New_York', now()),
  ('Licking County Historic Jail', 'licking-county-historic-jail', 'haunted', 40.0562, -82.40139, 'Newark', 'OH', 'The Licking County Historic Jail opened in 1889 and held prisoners until 1987, preserving its original cells and sheriff''s residence in downtown Newark. Deaths, a notorious 1910 lynching and decades of incarceration helped create its paranormal reputation, and the building now hosts scheduled historical tours, paranormal investigations and the seasonal Jail of Terror attraction.', 'limited', 'https://www.newarkjail.com/about.html', null, null, null, 'America/New_York', now()),
  ('Thurber House', 'thurber-house', 'haunted', 39.96578, -82.98522, 'Columbus', 'OH', 'Humorist James Thurber lived in this house as a child, and unexplained noises experienced by his family helped inspire his story "The Night the Ghost Got In." The restored house is now a literary museum with regular weekend hours, and it also permits scheduled private ghost investigations.', 'open', 'https://www.thurberhouse.org/', null, null, null, 'America/New_York', now()),
  ('Imogene Remus Ghost at Spring House Gazebo', 'imogene-remus-ghost-at-spring-house-gazebo', 'haunted', 39.11422, -84.49353, 'Cincinnati', 'OH', 'Bootlegger George Remus fatally shot his wife Imogene near Eden Park''s Spring House Gazebo in 1927 while she was on her way to divorce proceedings. Local legend says a woman dressed in black still appears around the gazebo and former reflecting pool, which remain freely accessible within the public park during park hours.', 'open', 'https://en.wikipedia.org/wiki/Spring_House_Gazebo', null, null, null, 'America/New_York', now()),
  ('Majestic Theatre', 'majestic-theatre', 'haunted', 39.33489, -82.98105, 'Chillicothe', 'OH', 'Chillicothe''s Majestic Theatre traces its history to the nineteenth century and is tied in local lore to the devastating 1918 influenza epidemic at nearby Camp Sherman. Stories claim the theater was used to hold bodies during the crisis and now hosts apparitions and voices; it remains an active theater, with access through performances, scheduled tours and occasional ghost hunts.', 'limited', 'https://www.majesticchillicothe.net/wp-content/uploads/Haunted-Majestic-Ghost-Hunt.pdf', null, null, null, 'America/New_York', now()),
  ('Moonville Tunnel', 'moonville-tunnel', 'haunted', 39.30722, -82.32222, 'Brown Township', 'OH', 'Moonville was a remote mining and railroad settlement whose last residents left in the twentieth century, leaving behind its cemetery, foundations and brick-lined railroad tunnel. Numerous deaths along the old rail line produced stories of a spectral brakeman carrying a lantern and other apparitions; the tunnel is reached on the public Moonville Rail Trail, which is open from 6 a.m. to 11 p.m. and remains rugged in places.', 'limited', 'https://visitvintonohio.com/history/moonville-tunnel/', null, null, null, 'America/New_York', now()),
  ('The Ridges', 'the-ridges', 'haunted', 39.32026, -82.1094, 'Athens', 'OH', 'The Athens Lunatic Asylum opened in 1874 and eventually became the enormous complex now called The Ridges, which Ohio University acquired after the hospital era ended. The grounds and trails are public and parts of the complex now house university facilities and the Kennedy Museum, while abandoned or restricted buildings are off-limits; the site''s institutional history has made it one of Athens'' best-known paranormal locations.', 'limited', 'https://www.ohio.edu/ridges/visit', null, null, null, 'America/New_York', now()),
  ('Gretchen''s Lock', 'gretchens-lock', 'haunted', 40.7076, -80.59396, 'St. Clair Township', 'OH', 'Gretchen''s Lock is a surviving ruin of the nineteenth-century Sandy and Beaver Canal inside Beaver Creek State Park. Legend says canal engineer E.H. Gill temporarily entombed his young daughter Gretchen in the lock after her death before attempting to return her body to Europe, and visitors still tell stories of her spirit near the stones; reaching the lock requires a park trail hike.', 'limited', 'https://www.carnegie.lib.oh.us/gretchen', null, null, null, 'America/New_York', now()),
  ('Lafayette Hotel', 'lafayette-hotel', 'haunted', 39.41076, -81.45234, 'Marietta', 'OH', 'The current Lafayette Hotel opened in 1918 after fire destroyed the earlier Bellevue Hotel at the riverfront site. Guests and staff have reported phantom footsteps, unexplained lights and apparitions including a former manager and a woman in dark clothing, while the building continues to operate as a normal hotel and public hospitality business.', 'open', 'https://www.ohiomagazine.com/travel/article/haunted-ohio-the-lafayette-hotel', null, null, null, 'America/New_York', now()),
  ('Witch''s Tower', 'witchs-tower', 'haunted', 39.70992, -84.18012, 'Kettering', 'OH', 'The stone Lookout Tower at Hills & Dales MetroPark, commonly called the Witch''s Tower or Frankenstein''s Castle, was completed in 1941. A teenage girl was killed by lightning at the tower in 1967, after which stories of ghostly figures became attached to it; the tower''s entrance is sealed, but hikers can reach and view the exterior from the park trail.', 'limited', 'https://www.daytondailynews.com/what-to-do/the-ghostly-tales-behind-hills-dales-witchs-tower/M55XOSN3I5CTJKSAAITLOOPG4E/', null, null, null, 'America/New_York', now()),
  ('Buckland Museum of Witchcraft and Magick', 'buckland-museum-of-witchcraft-and-magick', 'museums', 41.43812, -81.69976, 'Cleveland', 'OH', 'Raymond Buckland created the collection that became the Buckland Museum of Witchcraft and Magick, one of the oldest collections of its kind in the United States. The Cleveland museum displays ritual objects, occult artifacts and material connected to modern witchcraft and ceremonial magic, and visitors can enter during ticketed public hours.', 'open', 'https://bucklandmuseum.org/', null, null, null, 'America/New_York', now()),
  ('Troll Hole Museum', 'troll-hole-museum', 'museums', 40.92191, -81.10204, 'Alliance', 'OH', 'The Troll Hole Museum is devoted to trolls and houses a collection recognized for its enormous number of troll dolls and related artifacts. Guided visits wind through themed rooms, troll displays and a fantasy-style troll cave, making it one of Ohio''s more deliberately strange museums.', 'open', 'https://www.thetrollhole.com/', null, null, null, 'America/New_York', now()),
  ('Field of Corn', 'field-of-corn', 'roadside-oddities', 40.08501, -83.12333, 'Dublin', 'OH', 'Field of Corn, also known as Cornhenge, consists of 109 human-sized concrete ears of corn arranged in rows in Frantz Park. The public artwork was commissioned in 1993 as a reference to the area''s agricultural history and remains free to walk around during park hours.', 'open', 'https://www.dublinarts.org/fieldofcorn', null, null, null, 'America/New_York', now()),
  ('Temple of Tolerance', 'temple-of-tolerance', 'roadside-oddities', 40.56866, -84.18397, 'Wapakoneta', 'OH', 'Jim Bowsher began assembling the Temple of Tolerance from enormous stones, found objects and historic artifacts in his Wapakoneta backyard in 1981. Despite looking like a private residential property from the street, the stone sanctuary is intentionally open to the public for free; visitors should use the designated entrance and stay within the areas opened for guests.', 'open', 'https://jimbowsher.com/visit/', null, null, null, 'America/New_York', now()),
  ('Hartman Rock Garden', 'hartman-rock-garden', 'roadside-oddities', 39.90498, -83.83247, 'Springfield', 'OH', 'Ben Hartman began building this elaborate folk-art garden in 1932 after losing his job during the Great Depression. Miniature castles, cathedrals, historical scenes and hundreds of figures made from concrete, stone, glass and other materials fill the yard, which is preserved as a free public attraction from dawn to dusk.', 'open', 'https://hartmanrocks.org/visit/', null, null, null, 'America/New_York', now()),
  ('Big Muskie Bucket', 'big-muskie-bucket', 'roadside-oddities', 39.69927, -81.73128, 'Bristol Township', 'OH', 'Big Muskie was once the world''s largest dragline excavator, working Ohio coal country from 1969 until 1991 before the machine was dismantled. Its enormous surviving bucket now sits at Miner''s Memorial Park, where visitors can walk directly up to it, climb inside and see the mining memorials and overlook.', 'open', 'https://www.visitmorgancountyohio.com/Explore/Destinations/Miner-s-Memorial-Park-Big-Muskie-Bucket-68/', null, null, null, 'America/New_York', now()),
  ('World''s Largest Washboard', 'worlds-largest-washboard', 'roadside-oddities', 39.53993, -82.41385, 'Logan', 'OH', 'A giant washboard measuring roughly two stories tall is mounted on the Columbus Washboard Company building in Logan, advertising a factory that still produces traditional washboards. The exterior landmark can be seen at any time from public ground, while the factory store and any interior access follow business hours.', 'open', 'https://www.atlasobscura.com/places/worlds-largest-washboard', null, null, null, 'America/New_York', now()),
  ('Longaberger Basket Building', 'longaberger-basket-building', 'roadside-oddities', 40.06376, -82.34646, 'Newark', 'OH', 'Longaberger opened this seven-story headquarters in 1997 in the shape of one of the company''s Medium Market Baskets, complete with enormous handles. The office building has spent years largely vacant and was again being marketed for sale in 2026, so treat it as an exterior roadside stop unless an officially announced tour or event specifically allows entry.', 'roadside', 'https://www.axios.com/local/columbus/2026/07/10/longaberger-basket-building-history-for-sale-newark', null, null, null, 'America/New_York', now()),
  ('American Sign Museum', 'american-sign-museum', 'museums', 39.14354, -84.53986, 'Cincinnati', 'OH', 'The American Sign Museum preserves more than a century of American commercial signage, from hand-painted storefronts and roadside signs to enormous glowing neon displays. Visitors can walk through recreated streetscapes and see neon craftsmanship during regular museum hours.', 'open', 'https://www.americansignmuseum.org/visit/', null, null, null, 'America/New_York', now()),
  ('Carlisle Futuro House', 'carlisle-futuro-house', 'roadside-oddities', 39.58866, -84.33806, 'Carlisle', 'OH', 'This flying-saucer-shaped residence is an example of the Futuro, the late-1960s prefabricated plastic house designed by Finnish architect Matti Suuronen. The Carlisle property is privately owned, so it should be viewed only from a legal public roadside position without entering the driveway, yard or property.', 'private', 'https://www.ohiomagazine.com/ohio-life/article/-the-futuro-house', null, null, null, 'America/New_York', now()),
  ('Serpent Mound', 'serpent-mound', 'weird-history', 39.02414, -83.4296, 'Bratton Township', 'OH', 'Serpent Mound is a massive prehistoric effigy earthwork shaped like an undulating snake and is one of the most distinctive archaeological sites in North America. Visitors can follow the path around the protected mound, use the observation tower and visit the museum during posted hours; climbing on the earthwork or entering the site after the gates close is prohibited.', 'open', 'https://www.ohiohistory.org/visit/browse-historical-sites/serpent-mound/', null, null, null, 'America/New_York', now()),
  ('Historic Prospect Place', 'historic-prospect-place', 'haunted', 40.13466, -82.01325, 'Trinway', 'OH', 'Prospect Place is an 1856 mansion built for abolitionist George W. Adams and is now preserved by a nonprofit historical organization. Its legends and reported paranormal activity are incorporated into scheduled flashlight tours and ghost hunts, while free daylight tours are offered seasonally from March through November.', 'limited', 'https://www.historicprospectplace.org/', null, null, null, 'America/New_York', now()),
  ('Ceely Rose House at Malabar Farm', 'ceely-rose-house-at-malabar-farm', 'haunted', 40.65021, -82.39502, 'Monroe Township', 'OH', 'In 1896, Celia "Ceely" Rose poisoned her parents and brother at the family home in Pleasant Valley after becoming fixated on a local man, creating one of Richland County''s most infamous stories. The house survives within Malabar Farm State Park and can be viewed from the park road or walking route, but the interior is not open to the public; local tradition also associates the house and nearby cemetery with Ceely''s ghost.', 'limited', 'https://malabarfarm.org/local-history/', null, null, null, 'America/New_York', now()),
  ('Hope Furnace Ghost', 'hope-furnace-ghost', 'haunted', 39.33194, -82.34028, 'Brown Township', 'OH', 'Hope Furnace was built in 1853-54 to smelt iron and operated until 1874, leaving a large stone furnace stack beside present-day Lake Hope State Park. Local legend says a night watchman who died at the furnace still appears carrying a lantern during storms, while the surviving furnace and historical marker remain publicly accessible.', 'open', 'https://visitvintonohio.com/what-to-do/paranormal-investigation/', null, null, null, 'America/New_York', now()),
  ('Leatherlips Monument', 'leatherlips-monument', 'roadside-oddities', 40.11702, -83.11057, 'Dublin', 'OH', 'This 12-foot stone portrait of Wyandot leader Leatherlips was created by artist Ralph Helmick and installed at Scioto Park in 1990 near the area traditionally associated with Leatherlips'' 1810 execution. Visitors can walk into the limestone sculpture and look through it toward the Scioto River; the City of Dublin and Wyandotte Nation have also worked to correct a later, inaccurate "curse" legend attached to his name.', 'open', 'https://www.dublinarts.org/leatherlips', null, null, null, 'America/New_York', now()),
  ('The Free Stamp', 'the-free-stamp', 'roadside-oddities', 41.5055, -81.69245, 'Cleveland', 'OH', 'Claes Oldenburg and Coosje van Bruggen designed this enormous steel office stamp for Standard Oil of Ohio in the 1980s, but it spent years in storage before finally being installed in Willard Park. The sculpture measures roughly 28 feet tall and 48 feet long and spells out "FREE," making it one of downtown Cleveland''s easiest oversized-object stops.', 'open', 'https://clevelandhistorical.org/items/show/571', null, null, null, 'America/New_York', now()),
  ('Cincinnati Mushroom House', 'cincinnati-mushroom-house', 'roadside-oddities', 39.14118, -84.42371, 'Cincinnati', 'OH', 'Architect and University of Cincinnati professor Terry Brown spent more than a decade transforming a small Hyde Park house into an organic structure covered with warped shingles, stained glass, porthole windows and a bright spiral staircase. It remains private property, so OddWay visitors should admire and photograph the exterior only from the public sidewalk without entering the lot or stairs.', 'private', 'https://www.ohiomagazine.com/ohio-life/article/mushroom-house-cincinnati', null, null, null, 'America/New_York', now()),
  ('World''s Largest Gavel', 'worlds-largest-gavel', 'roadside-oddities', 39.9595, -83.0022, 'Columbus', 'OH', 'A giant stainless-steel gavel lies beside the Thomas J. Moyer Ohio Judicial Center in downtown Columbus. The oversized public sculpture is commonly promoted as the world''s largest gavel and can be viewed from the public plaza without entering the court building.', 'open', 'https://www.worldrecordacademy.org/2023/5/worlds-largest-steel-gavel-sculpture-world-record-in-columbus-ohio-423215', null, null, null, 'America/New_York', now()),
  ('Golden Lamb Ghosts', 'golden-lamb-ghosts', 'haunted', 39.4336, -84.20846, 'Lebanon', 'OH', 'The Golden Lamb has operated in Lebanon since 1803 and is Ohio''s longest continually operating business, with a restaurant, guestrooms and fourth-floor historical displays. Staff and guests have long reported apparitions associated with figures including Sarah Stubbs and politician Clement Vallandigham, who accidentally shot himself at the inn in 1871; the property itself publishes and preserves these ghost stories.', 'open', 'https://www.goldenlamb.com/news/does-the-golden-lamb-have-ghostly-uninvited-guests/', null, null, null, 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  phone         = excluded.phone,
  opening_hours = excluded.opening_hours,
  verified_at   = excluded.verified_at;
