-- Pennsylvania, third batch.
--
-- Five dropped as duplicates of the first batch: Schaefer's Auto Art, the
-- PennDOT sign garden, the Living Dead Museum, Columcille and the Clothespin.
-- Both the slug check and the coordinate check flagged all five, which is what
-- they are supposed to do — the horseshoe crab got through because only one
-- fired.
--
-- Note Schaefer's is 7 metres and the Clothespin 9 metres from the existing
-- records rather than zero. Two people locating the same object independently
-- land a few metres apart, which is exactly why the coordinate check uses a
-- radius rather than looking for an exact match.
--
-- 35 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone, verified_at)
values
  ('Mad Anthony Wayne Blockhouse', 'mad-anthony-wayne-blockhouse', 'weird-history', 42.14003, -80.07432, 'Erie', 'PA', 'This reconstructed blockhouse marks the Fort Presque Isle site where Revolutionary War general Anthony Wayne died in 1796 and was first buried. When his son later came to move the body east, Wayne''s partially decomposed remains were boiled so the bones could be transported, leaving Erie associated with one of the strangest posthumous journeys in American military history; interior access is limited, but the grounds can be visited.', 'limited', 'https://historicsitemarkers.com/marker/anthony-wayne', 'America/New_York', now()),
  ('Johnson-Shaw Stereoscopic Museum', 'johnson-shaw-stereoscopic-museum', 'museums', 41.63738, -80.1469, 'Meadville', 'PA', 'Meadville was once home to the Keystone View Company, which became one of the world''s largest producers of stereoscopic photographs. This small museum preserves cameras, viewers and three-dimensional image sets from that industry and is normally open Saturdays from April through November, with other visits by appointment.', 'limited', 'https://www.johnsonshawmuseum.org/', 'America/New_York', now()),
  ('Sherman Memorial Lighthouse', 'sherman-memorial-lighthouse', 'roadside-oddities', 41.49008, -79.45822, 'Tionesta', 'PA', 'A 75-foot lighthouse rises beside the Allegheny River in inland Forest County, far from any place where a navigation lighthouse would normally be needed. Jack Sherman built it as a family memorial and filled its seven floors with lighthouse-related exhibits; Peace Park and the exterior are freely accessible, while tower tours are offered only on selected dates.', 'limited', 'https://pabucketlist.com/exploring-the-sherman-memorial-lighthouse-in-forest-county/', 'America/New_York', now()),
  ('Wild Geese: Flock Together', 'wild-geese-flock-together', 'roadside-oddities', 40.59749, -77.57718, 'Lewistown', 'PA', 'Five-foot fiberglass geese painted by local artists are scattered around the Juniata River Valley in honor of the region''s Goose Day tradition. This pin marks one of the public sculptures in Lewistown, and a separate tracker map can be used to hunt down the rest of the flock.', 'roadside', 'https://www.atlasobscura.com/places/geese-flock-together', 'America/New_York', now()),
  ('Giant Quarter', 'giant-quarter', 'roadside-oddities', 40.01599, -78.36026, 'Everett', 'PA', 'Students at Bedford County Technical Center built this roughly 20-foot-wide quarter as a tribute to George Washington''s connections to Bedford County. The nearly one-ton coin stands near Down River Golf Course and makes an easy oversized-object photo stop from the public-facing area.', 'roadside', 'https://www.atlasobscura.com/places/giant-quarter-everett-pennsylvania', 'America/New_York', now()),
  ('Jenny Globe', 'jenny-globe', 'roadside-oddities', 40.0151, -79.07583, 'Somerset', 'PA', 'A huge rotating fiberglass globe has stood outside Jenny Products since the late 1960s, built to celebrate the company''s growth as a maker of pressure-washing equipment. It resembles a water tower but is actually a giant spinning advertisement, with parking available at the business for visitors who want a closer look.', 'roadside', 'https://www.atlasobscura.com/places/jenny-globe', 'America/New_York', now()),
  ('The Little Village', 'the-little-village', 'roadside-oddities', 40.19536, -78.64417, 'Pleasantville', 'PA', 'A miniature roadside settlement of tiny buildings includes a school, diner, filling station and other hand-built structures beside Route 56. The display sits on private residential property, so admire it from the public roadside and do not enter the lawn unless the owners explicitly invite visitors in.', 'private', 'https://www.atlasobscura.com/places/little-village-pennsylvania', 'America/New_York', now()),
  ('Beasts of Beaver Meadows', 'beasts-of-beaver-meadows', 'roadside-oddities', 40.93178, -75.92267, 'Beaver Meadows', 'PA', 'Dragons, dinosaurs, owls and other monsters made from concrete, scrap metal and old vehicle parts line Route 93 north of Beaver Meadows. The sculptures were created by Joseph J. Woitko and sit on private land, so they should be viewed from the road without wandering onto the property.', 'private', 'https://www.atlasobscura.com/places/beaver-meadows-roadside-scuptures', 'America/New_York', now()),
  ('Pioneer Mom and Daughter Roadside Statue', 'pioneer-mom-and-daughter-roadside-statue', 'roadside-oddities', 40.77563, -76.2256, 'Frackville', 'PA', 'This roughly 15-foot roadside figure of a bonneted mother holding a pie beside her daughter became a famously unsettling piece of Pennsylvania roadside kitsch outside a former motel. The attraction is now listed as permanently closed and no longer reliably accessible, but its former location is worth recording as part of the state''s roadside-history layer.', 'closed', 'https://www.atlasobscura.com/places/pioneer-mom-and-daughter-roadside-statue', 'America/New_York', now()),
  ('Duquesne Brewery Clock', 'duquesne-brewery-clock', 'roadside-oddities', 40.42615, -79.97652, 'Pittsburgh', 'PA', 'This enormous 60-foot-square clock was built in 1933 and later moved onto the former Duquesne Brewing Company building. Its face and hands dwarf those of many traditional clock towers, and it remains visible from surrounding public streets and bridges even though the old brewery itself is not a visitor attraction.', 'roadside', 'https://www.atlasobscura.com/places/duquesne-brewery-clock', 'America/New_York', now()),
  ('The Weeping Glass', 'the-weeping-glass', 'roadside-oddities', 40.42162, -79.994, 'Pittsburgh', 'PA', 'Pittsburgh''s long-running oddities shop sells and displays taxidermy, bones, funeral objects, anatomical pieces, strange artwork and other macabre curiosities. It operates as a normal storefront on East Warrington Avenue during posted weekly hours, so visitors can browse without an appointment.', 'open', 'https://www.visitpittsburgh.com/blog/occult-shops/', 'America/New_York', now()),
  ('Evans City Cemetery — Night of the Living Dead', 'evans-city-cemetery-night-of-the-living-dead', 'weird-history', 40.76239, -80.064, 'Evans City', 'PA', 'The opening cemetery sequence in George A. Romero''s 1968 Night of the Living Dead was filmed here, including the first zombie attack on Johnny and Barbra. The cemetery is still active and open to respectful visitors, so stay on cemetery roads and paths and avoid disturbing graves while looking for recognizable filming locations.', 'open', 'https://filmoblivion.com/2021/10/20/night-of-the-living-dead-1968/', 'America/New_York', now()),
  ('Archbald Pothole', 'archbald-pothole', 'roadside-oddities', 41.51175, -75.57408, 'Archbald', 'PA', 'A glacial waterfall drilled this enormous vertical pothole into bedrock thousands of years ago, leaving a cavity roughly large enough to hold dozens of fire trucks'' worth of water. A viewing platform inside Archbald Pothole State Park lets visitors look directly into the formation during park hours.', 'open', 'https://www.atlasobscura.com/places/archbald-pothole', 'America/New_York', now()),
  ('Concrete City', 'concrete-city', 'weird-history', 41.18852, -75.97528, 'Hanover Township', 'PA', 'Twenty reinforced-concrete houses were built here in 1911 as experimental company housing for coal workers, then abandoned little more than a decade later. The roofless shells still stand in the woods near Nanticoke, but reaching them requires walking from the public access area and the structures are deteriorated, so do not climb unstable walls or enter restricted land.', 'limited', 'https://en.wikipedia.org/wiki/Concrete_City', 'America/New_York', now()),
  ('Devil''s Hole Ruins', 'devils-hole-ruins', 'weird-history', 41.1403, -75.336, 'Paradise Township', 'PA', 'Deep in State Game Lands 221 are stone fireplaces, foundations and mechanical remnants from a large building whose exact purpose remains disputed, with stories ranging from a ski lodge to a Prohibition-era speakeasy. Reaching the ruins requires a secluded hike with multiple stream crossings, and hunters use the surrounding state game lands seasonally.', 'limited', 'https://www.atlasobscura.com/places/devils-hole-ruins', 'America/New_York', now()),
  ('Cave of Kelpius', 'cave-of-kelpius', 'folklore', 40.0238, -75.2016, 'Philadelphia', 'PA', 'Tradition connects this stone-lined chamber in the Wissahickon to Johannes Kelpius and his seventeenth-century community of mystics, who believed the end of the world was imminent. Historians debate whether the structure was actually Kelpius''s cave or a later springhouse, but visitors can reach it on foot from the public park trails.', 'limited', 'https://www.atlasobscura.com/places/cave-of-kelpius', 'America/New_York', now()),
  ('Mount Moriah Cemetery', 'mount-moriah-cemetery', 'weird-history', 39.93106, -75.23583, 'Philadelphia', 'PA', 'Once one of Pennsylvania''s largest Victorian cemeteries, Mount Moriah fell into severe abandonment after its old cemetery association disappeared, leaving mausoleums and graves swallowed by vegetation. Volunteers have reopened substantial sections, but public access is normally limited to weather-dependent weekend gate hours and visitors should stay on cleared routes.', 'limited', 'https://friendsofmountmoriahcemetery.org/visit/', 'America/New_York', now()),
  ('Mummers Museum', 'mummers-museum', 'museums', 39.93345, -75.14757, 'Philadelphia', 'PA', 'Philadelphia''s elaborate Mummers tradition fills this museum with feathered costumes, sequined suits, parade props, photographs and artifacts from more than a century of New Year''s performances. The collection explains one of the city''s strangest long-running civic traditions and is open during posted museum hours.', 'open', 'https://mummersmuseum.com/', 'America/New_York', now()),
  ('The Dowager Empress Crystal Ball', 'the-dowager-empress-crystal-ball', 'museums', 39.9494, -75.1916, 'Philadelphia', 'PA', 'A massive rock-crystal sphere once owned by China''s Dowager Empress Cixi sits inside the Penn Museum under heavy security. The ball was famously stolen in 1988 and later recovered, adding a bizarre crime story to an already unusual object that visitors can see with normal museum admission.', 'open', 'https://www.atlasobscura.com/places/crystal-ball-dowager-empress-penn-museum', 'America/New_York', now()),
  ('Green Man''s Tunnel', 'green-mans-tunnel', 'folklore', 40.27259, -79.96914, 'South Park Township', 'PA', 'Western Pennsylvania''s Green Man legend grew from the real life of Raymond Robinson, a badly disfigured man whose nighttime walks inspired generations of frightening stories about a glowing figure called Charlie No-Face. The legend was later attached to this abandoned railroad tunnel even though Robinson did not live there; view the tunnel from the legal road or trail area and do not enter blocked infrastructure or storage areas.', 'roadside', 'https://www.atlasobscura.com/places/green-man-s-tunnel', 'America/New_York', now()),
  ('Rehmeyer''s Hollow Hex House', 'rehmeyers-hollow-hex-house', 'weird-history', 39.80208, -76.64471, 'Stewartstown', 'PA', 'Powwow practitioner Nelson Rehmeyer was murdered inside this house in 1928 by men who believed he had placed a hex on one of them, producing the sensational case remembered as the York Witch Trial. The house survives, but it no longer has dependable public tour hours, so treat it as private property and view only from the public road unless an official event specifically grants access.', 'private', 'https://www.atlasobscura.com/places/rehmeyers-hollow', 'America/New_York', now()),
  ('White Cliffs of Conoy', 'white-cliffs-of-conoy', 'weird-history', 40.07237, -76.65304, 'Conoy Township', 'PA', 'These stark white cliffs above the Susquehanna are not natural limestone bluffs but piles of industrial waste left by a nineteenth- and twentieth-century quarry operation. They are reached by walking or cycling the Northwest Lancaster County River Trail, with additional ruins from the former company town of Billmyer nearby.', 'limited', 'https://www.discovermariettapa.org/business-directory/white-cliffs-of-conoy', 'America/New_York', now()),
  ('Conewago Potholes at Falmouth', 'conewago-potholes-at-falmouth', 'roadside-oddities', 40.11921, -76.70916, 'Conoy Township', 'PA', 'When the Susquehanna River drops low enough, the exposed diabase bedrock at Conewago Falls reveals deep circular potholes, sculpted channels and ripple-like forms carved by powerful water and sediment. The formations are only safely visible at low river levels; use the public boat-launch access and never walk onto exposed river rock during high or rising water.', 'limited', 'https://www.atlasobscura.com/places/conewago-potholes', 'America/New_York', now()),
  ('Frost Entomological Museum', 'frost-entomological-museum', 'museums', 40.80296, -77.86241, 'State College', 'PA', 'Penn State''s entomology museum maintains a research collection of more than one million arthropod specimens representing thousands of species. A free public gallery displays insects, collecting equipment and other entomological material on weekdays during university operating hours.', 'open', 'https://ento.psu.edu/about/facilities/frost/visit', 'America/New_York', now()),
  ('Woodward Cave', 'woodward-cave', 'roadside-oddities', 40.88944, -77.38819, 'Haines Township', 'PA', 'Woodward Cave contains large limestone rooms, active cave formations and the roughly 14-foot Tower of Babel, described as Pennsylvania''s largest known free-standing stalagmite. Guided tours operate seasonally, and visitors cannot enter the cave outside the attraction''s tour schedule.', 'limited', 'https://www.atlasobscura.com/places/woodward-cave', 'America/New_York', now()),
  ('Lincoln Caverns', 'lincoln-caverns', 'roadside-oddities', 40.50735, -78.07132, 'Porter Township', 'PA', 'Lincoln Caverns and adjoining Whisper Rocks contain passageways filled with flowstone, crystals and other limestone formations discovered during road construction in the 1930s. Guided underground tours operate from the visitor center, with special black-light and themed programs offered on selected dates.', 'open', 'https://lincolncaverns.com/', 'America/New_York', now()),
  ('Laurel Caverns', 'laurel-caverns', 'roadside-oddities', 39.7996, -79.7113, 'Wharton Township', 'PA', 'Pennsylvania''s largest cave system by volume extends beneath Chestnut Ridge in Fayette County. The underground caverns are open only from mid-April through late October for guided and self-guided experiences, closing each winter to protect hibernating bats.', 'limited', 'https://www.pa.gov/agencies/dcnr/recreation/where-to-go/state-parks/find-a-park/laurel-caverns-state-park', 'America/New_York', now()),
  ('Lost Children of the Alleghenies Monument', 'lost-children-of-the-alleghenies-monument', 'folklore', 40.29476, -78.60351, 'Pavia', 'PA', 'Brothers George and Joseph Cox disappeared from their Bedford County home in 1856 and were found dead in the mountains after a massive search, a tragedy later surrounded by stories of a local man''s prophetic dreams helping locate them. A stone memorial now stands near the place they were found, reached by a rough seasonal dirt road and a short walk into State Game Lands 26.', 'limited', 'https://pabucketlist.com/visiting-the-lost-children-of-the-alleghenies-monument-in-bedford-county/', 'America/New_York', now()),
  ('Seven Tubs Recreation Area', 'seven-tubs-recreation-area', 'roadside-oddities', 41.23544, -75.81026, 'Plains Township', 'PA', 'Glacial meltwater and Kitchen Creek carved a chain of smooth bowls, chutes and potholes into the bedrock here, creating the formations known as the Seven Tubs. The features are reached on foot from the public recreation-area parking lot, and wet rock around the creek can be extremely slippery.', 'limited', 'https://pennsylvaniastateparks.reserveamerica.com/camping/pinchot-state-forest/r/facilityDetails.do?contractCode=PA&parkId=880252', 'America/New_York', now()),
  ('Hickory Run Boulder Field', 'hickory-run-boulder-field', 'roadside-oddities', 41.0501, -75.6436, 'Kidder Township', 'PA', 'A roughly 16-acre field of bare sandstone boulders stretches across Hickory Run State Park with almost no soil or vegetation between the rocks. The formation dates to cold-climate conditions near the end of the Ice Age; a gravel road reaches it in warmer months, while winter closures can require a much longer hike.', 'limited', 'https://www.pa.gov/agencies/dcnr/recreation/where-to-go/state-parks/find-a-park/hickory-run-state-park', 'America/New_York', now()),
  ('Howard Tunnel', 'howard-tunnel', 'weird-history', 39.89148, -76.7496, 'North Codorus Township', 'PA', 'Built in the 1830s, Howard Tunnel is one of the oldest surviving railroad tunnels in the United States and remains part of an active rail corridor. The York County Heritage Rail Trail passes beside and through the historic corridor, so visitors should use the designated trail and never walk on the active tracks.', 'limited', 'https://www.atlasobscura.com/places/howard-tunnel', 'America/New_York', now()),
  ('Castle Halloween Museum', 'castle-halloween-museum', 'museums', 40.50766, -78.40791, 'Altoona', 'PA', 'More than 35,000 Halloween and macabre objects fill this private museum, ranging from nineteenth-century decorations and costumes to funeral-related pieces and modern holiday collectibles. Tours are arranged in advance rather than offered as normal daily walk-in admission.', 'limited', 'https://www.atlasobscura.com/places/castle-halloween-museum', 'America/New_York', now()),
  ('Cresson Sanatorium and Prison', 'cresson-sanatorium-and-prison', 'haunted', 40.4563, -78.5642, 'Lilly', 'PA', 'This sprawling mountaintop complex began as a tuberculosis sanatorium, later became a state hospital and then a prison before closing in 2013. Its empty cellblocks, medical buildings and tunnels are now used for scheduled historical tours, photography and paranormal investigations; the property is controlled and should never be entered outside an authorized event.', 'limited', 'https://www.atlasobscura.com/places/cresson-sanatorium-and-prison', 'America/New_York', now()),
  ('Donora Smog Museum', 'donora-smog-museum', 'museums', 40.1777, -79.85649, 'Donora', 'PA', 'The museum documents the deadly 1948 Donora smog, when industrial air pollution became trapped over the Monongahela Valley and sickened thousands of residents. Photographs, newspapers and artifacts explain the disaster''s role in the development of modern American air-pollution law; public hours are limited, so check before traveling.', 'limited', 'https://www.donorahistoricalsociety.org/donora-smog-museum/', 'America/New_York', now()),
  ('Carbondale UFO Marker', 'carbondale-ufo-marker', 'ufos', 41.56985, -75.5034, 'Carbondale', 'PA', 'A city historical marker records the November 1974 incident in which teenagers reported a glowing object flying low over Carbondale and crashing into a silt pond near Russell Park. Crowds and investigators descended on the site before a lantern was eventually recovered from the water, but the case remains a major piece of local UFO folklore and now inspires the annual Carbondalien Festival.', 'roadside', 'https://www.hmdb.org/m.asp?m=135019', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  verified_at   = excluded.verified_at;
