-- Pennsylvania, added by hand.
--
-- The first of a state-by-state pass to fill the gaps the OpenStreetMap scan
-- could not. A keyword search finds things whose names contain the keyword;
-- it cannot find the Albatwitch at Chickies Rock, or a road named for a
-- murder that never happened, because nothing in the map data says so.
--
-- North Park Gravity Hill is absent: it is already in the index, 12 metres
-- from where this list put it.
--
-- 30 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Presque Isle Beach 6 UFO Encounter', 'presque-isle-beach-6-ufo-encounter', 'ufos', 42.14441, -80.13804, 'Erie', 'PA', 'On July 31, 1966, witnesses stranded at Beach 6 reported a luminous metallic object descending near the beach, an incident later investigated as Project Blue Book case 10798. Beach 6 is still an ordinary public beach at Presque Isle State Park—there is no UFO monument—so the physical stop is the location associated with the documented Erie UFO story.', 'open', 'https://www.eriereader.com/article/eerie-erie-', 'https://www.pa.gov/agencies/dcnr/recreation/where-to-go/state-parks/find-a-park/presque-isle-state-park/swimming', 'America/New_York', now()),
  ('Gudgeonville Bridge Ghost Site', 'gudgeonville-bridge-ghost-site', 'haunted', 41.9824, -80.26681, 'Girard Township', 'PA', 'The 1868 Gudgeonville Covered Bridge developed generations of folklore about phantom hoofbeats and ghostly figures around Elk Creek. Arson destroyed the historic covered portion in 2008 and the crossing was rebuilt, so travelers now visit the same folklore location rather than the original covered bridge.', 'roadside', 'https://www.eriereader.com/article/the-erie-experience-spooky-urban-legends-folktales-and-lore', null, 'America/New_York', now()),
  ('Axe Murder Hollow', 'axe-murder-hollow', 'folklore', 42.03042, -80.15298, 'Millcreek Township', 'PA', 'For generations, Erie-area teenagers called the woods off Thomas Road "Axe Murder Hollow," telling stories about an axe murderer and ghosts haunting the hollow. Erie Reader''s archival investigation found no evidence that the legendary family massacre occurred; much of the old hollow is now residential private property, so experience the location only from public roads and **do not enter the woods or neighboring property**.', 'private', 'https://www.eriereader.com/article/exhuming-the-hollow', null, 'America/New_York', now()),
  ('Schaefer''s Auto Art', 'schaefers-auto-art', 'roadside-oddities', 42.04365, -80.13418, 'Erie', 'PA', 'Richard Schaefer transformed discarded automotive parts into an outdoor collection of enormous bugs, a rocket, "Automan," and a two-headed dinosaur along Hershey Road. The installation has existed for more than 25 years and SPACES still lists it as extant; there is a small roadside pull-off, but visitors should not park in the driveway.', 'roadside', 'https://www.spacesarchives.org/explore/search-the-online-collection/richard-schaefer/', null, 'America/New_York', now()),
  ('The Brewerie at Union Station — Haunted History', 'the-brewerie-at-union-station-haunted-history', 'haunted', 42.12082, -80.0822, 'Erie', 'PA', 'Erie''s Union Station opened in 1927, and the Brewerie''s own history preserves the local legend of "Clara," a child said to have died on its marble stairs and linger in the station afterward. The Brewerie has operated here since 2006 as a normal restaurant and brewpub, with ticketed Haunted History Tours offered on selected dates.', 'open', 'https://www.brewerie.com/history.html', 'https://www.brewerie.com/tours.html', 'America/New_York', now()),
  ('Roy Peters'' Dinosaur Park', 'roy-peters-dinosaur-park', 'roadside-oddities', 42.21561, -79.83422, 'North East', 'PA', 'Metalworker Roy Peters filled the property around his North East-area shop with enormous homemade dinosaur and animal sculptures, creating an accidental prehistoric roadside art environment. SPACES currently lists the installation as extant, but the sculptures occupy private property, so OddWay should treat this as a **look-from-public-ground** stop rather than invite people onto the lawn.', 'private', 'https://spacesarchives.org/explore/search-the-online-collection/roy-peters-dinosaur-park/', null, 'America/New_York', now()),
  ('Lawrence Park Dinor', 'lawrence-park-dinor', 'weird-history', 42.15071, -80.01431, 'Lawrence Park Township', 'PA', 'This prefabricated Silk City "dinor" arrived in Lawrence Park in 1948 and retains much of its original mid-century diner architecture. It is listed on the National Register, still serves breakfast and lunch, and preserves the peculiar **dinor-with-an-o** spelling that became a Northwestern Pennsylvania tradition.', 'open', 'https://www.eriereader.com/article/prefab-but-uniquely-erie', 'https://www.thelpdinor.com/', 'America/New_York', now()),
  ('Waldameer Whacky Shack', 'waldameer-whacky-shack', 'weird-history', 42.10864, -80.15767, 'Erie', 'PA', 'Dark-ride designer Bill Tracy built Waldameer''s Whacky Shack in 1970, filling the tracked ride with blacklight monsters, optical gags and old-school funhouse effects. It is still operating at Waldameer and is a rare surviving example of Tracy''s once-widespread amusement-park work, but it is available only when the seasonal park is operating.', 'limited', 'https://www.weirderie.com/the-wacky-shack', null, 'America/New_York', now()),
  ('Waldameer Pirates Cove', 'waldameer-pirates-cove', 'weird-history', 42.1083, -80.1581, 'Erie', 'PA', 'Bill Tracy created this walk-through pirate funhouse for Waldameer in 1972, combining tilted rooms, blacklight figures, optical illusions and deliberately disorienting passages. It remains an operating piece of vintage amusement architecture inside the seasonal park rather than a modern haunted-house attraction.', 'limited', 'https://www.weirderie.com/pirates-cove', null, 'America/New_York', now()),
  ('PennDOT Road Sign Sculpture Garden', 'penndot-road-sign-sculpture-garden', 'roadside-oddities', 41.62086, -80.16704, 'Vernon Township', 'PA', 'A roughly quarter-mile art wall outside PennDOT''s Crawford County offices turns retired road signs into barns, animals, a Ferris wheel, a roller coaster, oil wells and other Pennsylvania scenes. It grew from a collaboration between PennDOT employees and Allegheny College artists; there is no dedicated attraction parking, so it works best as a roadside view along Smock Highway.', 'roadside', 'https://paroute6.com/art-culture/penndot-road-sign-sculpture-garden/', null, 'America/New_York', now()),
  ('Serenity Glass Park', 'serenity-glass-park', 'roadside-oddities', 41.811, -78.28001, 'Port Allegany', 'PA', 'Dedicated in 2017, this small public park uses etched glass-block towers, a glass castle and other artwork to tell Port Allegany''s glassmaking, lumber and natural-gas story. Travelers can walk through it freely at Route 6 and Mill Street.', 'open', 'https://visitanf.com/serenity-glass-park/', null, 'America/New_York', now()),
  ('Zippo/Case Museum & Flagship Store', 'zippo-case-museum-flagship-store', 'museums', 41.94339, -78.65071, 'Bradford Township', 'PA', 'The current Zippo/Case museum opened in 1997 after an earlier museum proved too small for the growing collection. Visitors now find the first Zippo lighter, rare Case knives, military and advertising exhibits, the working Zippo Repair Clinic and an enormous Zippo-and-knife display outside; admission is free.', 'open', 'https://zippo.com/pages/zippo-case-museum-flagship-store', null, 'America/New_York', now()),
  ('Mars Flying Saucer', 'mars-flying-saucer', 'roadside-oddities', 40.69615, -80.01032, 'Mars', 'PA', 'Mars embraces its name with a nearly 3,000-pound flying-saucer sculpture assembled from industrial tanks and displayed downtown. The statue was already documented by 1989 and has become one of Butler County''s recognizable roadside landmarks, sitting in a public downtown space for easy photographs.', 'open', 'https://www.atlasobscura.com/places/mars-flying-saucer', null, 'America/New_York', now()),
  ('Playthings Etc. Spaceship Toy Store', 'playthings-etc-spaceship-toy-store', 'roadside-oddities', 40.96719, -79.96891, 'Clay Township', 'PA', 'Playthings Etc. opened in 2005 inside a purpose-built futuristic building the business itself describes as spaceship-shaped, complete with "engine doors." More than 7,000 toys fill the interior and many are available to try, making the strange building an actual walk-in destination rather than just novelty architecture.', 'open', 'https://playthings-etc.com/about/', null, 'America/New_York', now()),
  ('Coudersport Ice Mine', 'coudersport-ice-mine', 'roadside-oddities', 41.75456, -77.95533, 'Sweden Township', 'PA', 'Billy O''Neil discovered this strange cavity in 1894 while prospecting, and it became famous because ice forms inside as outside temperatures rise and retreats again as the weather cools. After decades as a roadside attraction and a long closure beginning in 1990, new owners restored and reopened it in 2014; visitation remains seasonal.', 'limited', 'https://coudersporticemineonline.com/pages/about-the-coudersport-ice-mine', null, 'America/New_York', now()),
  ('Albatwitch — Chickies Rock', 'albatwitch-chickies-rock', 'cryptids', 40.05231, -76.52491, 'West Hempfield Township', 'PA', 'Lancaster County folklore places the Albatwitch—a roughly four-foot hairy "apple-snitch" sometimes described as a miniature Bigfoot—in the woods surrounding Chickies Rock, where stories say it stole apples and threw the cores back at picnickers. The legend has been recorded in the area for generations and now has its own annual celebration; travelers can visit its traditional territory by hiking to the public Chickies Rock Overlook.', 'limited', 'https://susquehannagreenway.org/news-and-stories/susquehanna-greenway-ghouls-legends/', null, 'America/New_York', now()),
  ('Blue Mist Road Trail', 'blue-mist-road-trail', 'folklore', 40.62551, -80.00662, 'Pine Township', 'PA', 'The closed section of Irwin Road through Irwin Run Conservation Area is better known as Blue Mist Road, a longstanding Pittsburgh-area urban-legend location associated with ghosts, strange lights and a blue-tinged mist. The old road is now primarily a walking and biking trail rather than a spooky drive; the usual route is about 3.8 miles out and back, and the more sensational stories remain folklore rather than established history.', 'limited', 'https://myhikes.org/trails/blue-mist-road-trail', null, 'America/New_York', now()),
  ('Seven Gates of Hell — Trout Run Road', 'seven-gates-of-hell-trout-run-road', 'folklore', 40.03967, -76.66169, 'Hellam Township', 'PA', 'York County''s Seven Gates of Hell legend claims that a chain of gates hidden around Hellam Township leads eventually to an entrance to hell, with versions involving either a burned asylum or an eccentric doctor. The alleged asylum never existed and the land connected to the story is private property; this is strictly a **public-road folklore stop, not an invitation to search the woods**.', 'private', 'https://en.wikipedia.org/wiki/Seven\_Gates\_of\_Hell', null, 'America/New_York', now()),
  ('Trundle Manor', 'trundle-manor', 'museums', 40.42274, -79.88053, 'Swissvale', 'PA', 'Trundle Manor is an inhabited private home turned appointment-only museum of taxidermy, medical devices, bizarre art and miscellaneous unsettling objects. Visitors can tour the bottom-floor collection, but **appointments are required** and the owners specifically ask people not to simply appear at the house.', 'limited', 'https://trundlemanor.com/', null, 'America/New_York', now()),
  ('Mütter Museum', 'mutter-museum', 'museums', 39.95333, -75.17639, 'Philadelphia', 'PA', 'The Mütter began with surgeon Thomas Dent Mütter''s 1859 donation of 1,700 objects and money to establish a permanent medical teaching collection. It has grown to more than 25,000 objects covering medical history, anatomical specimens and pathology, with ticketed public galleries at the College of Physicians.', 'open', 'https://muttermuseum.org/about/overview/', null, 'America/New_York', now()),
  ('Living Dead Museum', 'living-dead-museum', 'museums', 40.42916, -79.79536, 'Monroeville', 'PA', 'The Living Dead Museum sits inside Monroeville Mall, the shopping center used for George A. Romero''s 1978 *Dawn of the Dead*. The museum follows zombies through cinema and pop culture with props, memorabilia and interactive displays, turning an actual horror-film location into part of the exhibit.', 'open', 'https://monroevillemall.com/store/living\_dead\_museum', null, 'America/New_York', now()),
  ('Pennhurst Asylum', 'pennhurst-asylum', 'haunted', 40.19463, -75.56188, 'Spring City', 'PA', 'Pennhurst State School became nationally important after its abusive conditions were exposed and legal challenges helped push the disability-rights movement forward. Parts of the surviving campus now offer scheduled daytime history tours and museum interpretation alongside photography, paranormal and seasonal haunted-attraction experiences, so travelers need tickets for a specific event rather than wandering the property.', 'limited', 'https://pennhurstasylum.com/visit/', null, 'America/New_York', now()),
  ('Sachs Covered Bridge', 'sachs-covered-bridge', 'haunted', 39.79742, -77.2762, 'Cumberland Township', 'PA', 'Built in the 1850s, Sachs Covered Bridge carried both Union and Confederate troops during the Gettysburg campaign and is now preserved as a pedestrian bridge. It later accumulated extensive ghost lore involving apparitions, phantom sounds and Civil War soldiers, making it one of Gettysburg''s better-known paranormal stops while still being a legitimate historic structure visitors can walk across.', 'open', 'https://www.gettysburgbattlefieldtours.com/the-ghosts-of-gettysburg/', null, 'America/New_York', now()),
  ('Ringing Rocks County Park', 'ringing-rocks-county-park', 'roadside-oddities', 40.56448, -75.12997, 'Bridgeton Township', 'PA', 'This county park contains a field of unusual diabase boulders that produce bell-like metallic tones when struck, turning the rocks themselves into a natural percussion instrument. A trail from the parking area reaches the boulder field, with High Falls elsewhere in the 128-acre park; bring a small hammer if you want to test the rocks yourself.', 'limited', 'https://www.buckscounty.gov/Facilities/Facility/Details/Ringing-Rocks-Park-5', null, 'America/New_York', now()),
  ('Haines Shoe House', 'haines-shoe-house', 'roadside-oddities', 39.99899, -76.63714, 'Hellam Township', 'PA', 'Shoe magnate Mahlon Haines built this five-level work-boot-shaped house in 1948–49 as an enormous advertisement and promotional guesthouse for his shoe business. It is now a short-term rental rather than a public museum: **only registered guests may enter**, although the owners explicitly welcome photographs from the public roadside.', 'private', 'https://www.hainesshoehouse.com/history', null, 'America/New_York', now()),
  ('Mister Ed''s Elephant Museum & Candy Emporium', 'mister-eds-elephant-museum-candy-emporium', 'museums', 39.89843, -77.43013, 'Orrtanna', 'PA', 'Ed and Pat Gotwalt opened the original Mister Ed''s roadside store in 1975, and its later incarnation turned Ed''s growing elephant collection into an entire museum-and-candy-store destination. Visitors now find roughly 12,000 elephant objects, a teapot museum, whimsical gardens and a huge candy selection, with free museum admission.', 'open', 'https://mistereds.com/pages/visit', null, 'America/New_York', now()),
  ('Bedford Coffee Pot', 'bedford-coffee-pot', 'roadside-oddities', 40.02303, -78.51759, 'Bedford Township', 'PA', 'Bert Koontz built this 18-foot coffee-pot-shaped building in 1927 to lure Lincoln Highway motorists into his adjacent service station and lunch business. Saved from demolition, it was moved to the Bedford County Fairgrounds and restored in 2003–04; the exterior and historical marker are always the attraction, while the interior has no dependable regular public hours.', 'roadside', 'https://www.bedboro.com/about-us/', null, 'America/New_York', now()),
  ('Reading Pagoda', 'reading-pagoda', 'weird-history', 40.33609, -75.90567, 'Reading', 'PA', 'William Abbott Witman constructed Reading''s Japanese-inspired Pagoda in 1908 as the centerpiece of a proposed mountaintop resort, but the resort plan collapsed after he failed to secure a liquor license. The city acquired it for $1 in 1911; following a major restoration, the grounds are open daily while the building itself currently opens only for selected ticketed walkthroughs and arranged group tours.', 'limited', 'https://www.readingpagoda.com/visit', null, 'America/New_York', now()),
  ('Columcille Megalith Park', 'columcille-megalith-park', 'roadside-oddities', 40.92692, -75.20227, 'Bangor', 'PA', 'This privately owned but publicly accessible sanctuary contains more than 90 large stone settings spread across more than 20 wooded acres, with most placed between 1980 and 2005. Visitors can wander several miles of rough trails from dawn to dusk for free; climbing the stones is prohibited and organized activities require permission.', 'open', 'https://www.columcille.org/visitingthepark', null, 'America/New_York', now()),
  ('Clothespin', 'clothespin', 'roadside-oddities', 39.9524, -75.1657, 'Philadelphia', 'PA', 'Claes Oldenburg installed *Clothespin* in 1976, turning an ordinary spring clothespin into monumental public art opposite Philadelphia City Hall. It stands directly above the downtown transit concourse at 15th and Market and is freely visible from the public plaza at any time.', 'open', 'https://www.philart.net/art/Clothespin/75.html', null, 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;
