-- Pennsylvania, second batch.
--
-- Three dropped as exact duplicates of the first batch, all at zero metres:
-- the Zippo/Case Museum, Ringing Rocks County Park and the Reading Pagoda.
--
-- Crystal Cave is inserted as crystal-cave-kutztown rather than crystal-cave,
-- because Ohio already holds that slug for the cave at Put-in-Bay. Two
-- different caves with the same name in different states, and the upsert would
-- have replaced one with the other without complaint.
--
-- Slugs were checked against both conventions used in this project — one turns
-- an apostrophe into a dash, the other removes it — since a mismatch there is
-- how a duplicate horseshoe crab nearly reached the index.
--
-- Heavily industrial: four coal mines, two blast furnace complexes, the first
-- oil well, a dam that failed, and a mine rescue site. Pennsylvania's strange
-- places are mostly its working past, left standing.
--
-- 47 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone, verified_at)
values
  ('Bayernhof Museum', 'bayernhof-museum', 'museums', 40.49839, -79.91589, 'O''Hara Township', 'PA', 'This eccentric mansion was built by Charles Brown III and hides secret doors, concealed passages, unusual architecture and a large collection of antique automatic music machines. Tours are by advance appointment only, so this is a planned stop rather than a walk-in museum.', 'limited', 'https://www.bayernhofmuseum.com/', 'America/New_York', now()),
  ('Saint Anthony Chapel', 'saint-anthony-chapel', 'museums', 40.46489, -79.98369, 'Pittsburgh', 'PA', 'Saint Anthony Chapel in Troy Hill houses more than 5,000 religious relics, one of the largest publicly accessible collections outside the Vatican. The active Catholic chapel is open during posted hours, and visitors can see reliquaries containing remains and objects associated with hundreds of saints.', 'open', 'https://saintanthonyschapel.org/', 'America/New_York', now()),
  ('Bicycle Heaven', 'bicycle-heaven', 'museums', 40.45631, -80.03241, 'Pittsburgh', 'PA', 'Bicycle Heaven combines a working bike shop with a sprawling museum packed with vintage bicycles, rare models, movie bikes and unusual cycling memorabilia. The collection fills multiple rooms and is open to visitors during posted business hours.', 'open', 'https://www.bicycleheaven.org/', 'America/New_York', now()),
  ('Randyland', 'randyland', 'roadside-oddities', 40.45793, -80.00975, 'Pittsburgh', 'PA', 'Artist Randy Gilson transformed his North Side property into a brightly painted outdoor folk-art environment beginning in the 1990s. Visitors can walk through courtyards filled with murals, mannequins, mirrors, signs and repurposed objects during posted hours.', 'open', 'https://randy.land/', 'America/New_York', now()),
  ('Big Mac Museum', 'big-mac-museum', 'museums', 40.32091, -79.69198, 'North Huntingdon Township', 'PA', 'This McDonald''s contains a small museum devoted to the Big Mac, which was created by western Pennsylvania franchisee Jim Delligatti in 1967. Displays include memorabilia and an oversized Big Mac sculpture inside an otherwise operating restaurant.', 'open', 'https://www.atlasobscura.com/places/big-mac-museum', 'America/New_York', now()),
  ('Carrie Blast Furnaces', 'carrie-blast-furnaces', 'weird-history', 40.40757, -79.8867, 'Rankin', 'PA', 'Carrie Furnaces 6 and 7 are surviving pieces of the enormous Homestead Works steel complex that once dominated the Monongahela Valley. Rivers of Steel preserves the furnaces and offers scheduled industrial-history tours, but visitors cannot freely enter the site outside authorized programs.', 'limited', 'https://riversofsteel.com/attractions/carrie-furnaces/', 'America/New_York', now()),
  ('Old Economy Village', 'old-economy-village', 'weird-history', 40.59611, -80.23194, 'Ambridge', 'PA', 'The Harmony Society established Economy in 1824 as a highly organized religious communal settlement while its members awaited the Second Coming. Seventeen historic buildings, gardens and original artifacts survive as a state historic site, with public access during its seasonal operating schedule.', 'limited', 'https://www.pa.gov/agencies/phmc/historic-sites-and-museums/rural-farm-and-village-history-trail/old-economy', 'America/New_York', now()),
  ('Nemacolin Castle', 'nemacolin-castle', 'haunted', 40.02258, -79.8837, 'Brownsville', 'PA', 'Nemacolin Castle grew from an eighteenth-century trading-post site into an elaborate nineteenth-century mansion overlooking the Monongahela River. The Brownsville Historical Society opens the castle for scheduled tours and events, including programs built around longstanding reports of unexplained activity.', 'limited', 'https://www.nemacolincastle.net/', 'America/New_York', now()),
  ('Meadowcroft Rockshelter', 'meadowcroft-rockshelter', 'weird-history', 40.28618, -80.49063, 'Jefferson Township', 'PA', 'Meadowcroft preserves a rock shelter containing evidence of human occupation dating back thousands of years and central to debates about the earliest settlement of North America. The archaeological site is protected beneath a modern enclosure and can be seen on guided tours during the museum''s operating season.', 'limited', 'https://www.heinzhistorycenter.org/visit/meadowcroft/', 'America/New_York', now()),
  ('Historic Pithole City', 'historic-pithole-city', 'weird-history', 41.52089, -79.58699, 'Cornplanter Township', 'PA', 'Pithole exploded into a booming oil town after nearby wells struck petroleum in 1865 and collapsed almost as quickly when the boom moved elsewhere. Little of the original city remains above ground, but paths, foundations, interpretation and a seasonal visitor center preserve one of Pennsylvania''s most dramatic ghost towns.', 'limited', 'https://www.drakewell.org/plan-your-visit/what-to-see-and-do', 'America/New_York', now()),
  ('Austin Dam Ruins', 'austin-dam-ruins', 'weird-history', 41.65272, -78.08592, 'Keating Township', 'PA', 'The broken concrete walls in Austin Dam Memorial Park are the remains of the dam that failed catastrophically in 1911, sending water and debris through the valley and killing dozens of people. Visitors can walk among the enormous tilted sections of concrete and see interpretive material in the public park.', 'open', 'https://www.austindam.net/', 'America/New_York', now()),
  ('Kinzua Bridge Skywalk and Tornado Ruins', 'kinzua-bridge-skywalk-and-tornado-ruins', 'roadside-oddities', 41.75952, -78.58694, 'Hamlin Township', 'PA', 'The Kinzua Viaduct once stretched more than 2,000 feet across Kinzua Gorge before a tornado tore away much of the structure in 2003. The surviving towers now form a public skywalk with a glass viewing area, while the twisted fallen towers remain visible across the valley below.', 'open', 'https://www.pa.gov/agencies/dcnr/recreation/where-to-go/state-parks/find-a-park/kinzua-bridge-state-park', 'America/New_York', now()),
  ('Drake Well Museum and Park', 'drake-well-museum-and-park', 'weird-history', 41.61128, -79.65827, 'Titusville', 'PA', 'Edwin Drake''s successful 1859 oil well at this site helped launch the modern petroleum industry. The museum preserves a replica well house, operating historic oil-field equipment and exhibits explaining the chaotic oil boom that transformed northwestern Pennsylvania.', 'open', 'https://www.drakewell.org/', 'America/New_York', now()),
  ('Quecreek Mine Rescue Site', 'quecreek-mine-rescue-site', 'weird-history', 40.07781, -79.08605, 'Somerset', 'PA', 'Nine miners were trapped underground by flooding at Quecreek in July 2002 and were brought out alive after a highly publicized 77-hour rescue. The rescue field is now Monument for Life Memorial Park, where visitors can see the rescue shaft, a miner statue and outdoor memorials; the educational center has separate operating hours.', 'open', 'https://www.quecreekrescue.org/', 'America/New_York', now()),
  ('Eckley Miners'' Village', 'eckley-miners-village', 'weird-history', 40.99525, -75.85606, 'Foster Township', 'PA', 'Eckley is a remarkably intact nineteenth-century anthracite company town with miners'' houses, churches, a company store and other surviving structures. The village itself can be walked or driven through from dawn to dusk, while the museum and building interiors follow posted hours.', 'open', 'https://eckleyminersvillage.com/', 'America/New_York', now()),
  ('Pioneer Tunnel Coal Mine', 'pioneer-tunnel-coal-mine', 'museums', 40.77821, -76.35255, 'Ashland', 'PA', 'Pioneer Tunnel has taken visitors into an authentic anthracite mine since 1962. Seasonal tours ride underground in mine cars, and a separate narrow-gauge steam train follows the mountainside above Ashland.', 'limited', 'https://www.pioneertunnel.com/', 'America/New_York', now()),
  ('Tour-Ed Mine', 'tour-ed-mine', 'museums', 40.61677, -79.7592, 'Tarentum', 'PA', 'Tour-Ed Mine preserves a former western Pennsylvania coal mine as an underground educational attraction. Guides take visitors into the mine to see equipment, tunnels and demonstrations of historic mining work, with tours operating on a seasonal schedule.', 'limited', 'https://tour-edmine.com/', 'America/New_York', now()),
  ('Houdini Museum', 'houdini-museum', 'museums', 41.4326, -75.66307, 'Scranton', 'PA', 'This Scranton museum is devoted to escape artist and magician Harry Houdini, with memorabilia, photographs, props and material examining his career and his campaigns against fraudulent spiritualists. Visits are structured as scheduled museum-and-magic experiences rather than ordinary anytime walk-in admission.', 'limited', 'https://www.houdinimuseum.net/', 'America/New_York', now()),
  ('Lackawanna Coal Mine Tour', 'lackawanna-coal-mine-tour', 'museums', 41.4167, -75.71524, 'Taylor', 'PA', 'Visitors descend roughly 300 feet underground into a former anthracite mine beneath McDade Park. Guides lead groups through old gangways and coal veins while explaining the dangerous work of northeastern Pennsylvania miners; tours operate seasonally.', 'limited', 'https://www.visitnepa.org/things-to-do/attractions/lackawanna-coal-mine-tour/', 'America/New_York', now()),
  ('National Watch and Clock Museum', 'national-watch-and-clock-museum', 'museums', 40.03699, -76.50223, 'Columbia', 'PA', 'The National Watch and Clock Museum houses thousands of timekeeping objects ranging from early sundials and tall clocks to pocket watches and modern precision devices. Its galleries make the mechanics and strange variety of human timekeeping the focus of a dedicated public museum.', 'open', 'https://www.nawcc.org/index.php/museum/', 'America/New_York', now()),
  ('Julius Sturgis Pretzel Bakery', 'julius-sturgis-pretzel-bakery', 'weird-history', 40.15655, -76.3013, 'Lititz', 'PA', 'Julius Sturgis opened his commercial pretzel bakery here in 1861, and the historic stone building still operates as a visitor attraction. Guided bakery tours explain early pretzel making and let visitors try forming the traditional pretzel shape by hand.', 'open', 'https://juliussturgis.com/', 'America/New_York', now()),
  ('Mercer Museum', 'mercer-museum', 'museums', 40.3079, -75.12734, 'Doylestown', 'PA', 'Archaeologist and collector Henry Chapman Mercer filled this castle-like concrete museum with tools and objects documenting preindustrial American life. Thousands of artifacts hang from balconies, walls and ceilings in a towering central atrium, including wagons, boats and machinery suspended overhead.', 'open', 'https://www.mercermuseum.org/visit/mercer-museum/', 'America/New_York', now()),
  ('Fonthill Castle', 'fonthill-castle', 'roadside-oddities', 40.32113, -75.12293, 'Doylestown Township', 'PA', 'Henry Chapman Mercer built Fonthill between 1908 and 1912 as an experimental reinforced-concrete home filled with handmade tiles and architectural fragments. Guided tours wind through dozens of irregular rooms, stairways, terraces and alcoves in one of Pennsylvania''s strangest private homes turned museum.', 'open', 'https://www.mercermuseum.org/visit/fonthill-castle/', 'America/New_York', now()),
  ('Fort Mifflin', 'fort-mifflin', 'haunted', 39.87545, -75.21289, 'Philadelphia', 'PA', 'Fort Mifflin is a surviving Revolutionary-era fort on the Delaware River and saw intense bombardment during the 1777 defense of Philadelphia. The historic site is open for tours and events and has also developed a major paranormal reputation involving voices, footsteps and apparitions reported in its old barracks and casemates.', 'open', 'https://www.fortmifflin.us/', 'America/New_York', now()),
  ('Edgar Allan Poe National Historic Site', 'edgar-allan-poe-national-historic-site', 'museums', 39.962, -75.15, 'Philadelphia', 'PA', 'Edgar Allan Poe lived in this Philadelphia house during one of the most productive periods of his writing career in the 1840s. The National Park Service preserves the empty rooms and exhibits about Poe''s work, including the dark stories that helped define American horror literature.', 'open', 'https://www.nps.gov/edal/', 'America/New_York', now()),
  ('Laurel Hill Cemetery', 'laurel-hill-cemetery', 'weird-history', 40.00483, -75.19018, 'Philadelphia', 'PA', 'Laurel Hill opened in 1836 as one of America''s early rural cemeteries and became a landscape of elaborate mausoleums, sculptures and graves of prominent Philadelphians. The cemetery welcomes self-guided visitors every day and also hosts historical, architectural and macabre-themed tours and events.', 'open', 'https://thelaurelhillcemetery.org/', 'America/New_York', now()),
  ('Logan Inn', 'logan-inn', 'haunted', 40.3635, -74.9517, 'New Hope', 'PA', 'The Logan Inn traces its history to 1727 and is one of New Hope''s oldest continuously used buildings. Its long-running ghost lore centers on rooms and hallways where guests have reported apparitions and unexplained activity, while the property remains an active hotel and restaurant.', 'open', 'https://www.loganinn.com/press-blogs', 'America/New_York', now()),
  ('Black Bass Hotel', 'black-bass-hotel', 'haunted', 40.40677, -75.03756, 'Lumberville', 'PA', 'The Black Bass Hotel has served travelers along the Delaware River for centuries and incorporates stories of unexplained visitors into its documented history and folklore. It remains a functioning hotel and restaurant, so travelers can visit normally without entering private guest spaces.', 'open', 'https://www.blackbasshotel.com/history/', 'America/New_York', now()),
  ('Historic Hotel Bethlehem', 'historic-hotel-bethlehem', 'haunted', 40.62009, -75.38244, 'Bethlehem', 'PA', 'Hotel Bethlehem stands on a historic Main Street site associated with hospitality going back to Bethlehem''s early years. Guests and staff have reported ghost stories throughout the building, including persistent lore surrounding Room 932, while the property remains a fully operating hotel.', 'open', 'https://www.hotelbethlehem.com/', 'America/New_York', now()),
  ('Baker Mansion History Museum', 'baker-mansion-history-museum', 'museums', 40.4906, -78.4083, 'Altoona', 'PA', 'Ironmaster Elias Baker completed this imposing Greek Revival mansion in 1849 after construction costs pushed him close to financial ruin. The Blair County Historical Society now fills the house with period rooms and regional artifacts, with public tours offered during its seasonal museum schedule.', 'limited', 'https://www.blairhistory.org/baker-mansion.html', 'America/New_York', now()),
  ('Philadelphia''s Magic Gardens', 'philadelphias-magic-gardens', 'roadside-oddities', 39.94274, -75.15941, 'Philadelphia', 'PA', 'Artist Isaiah Zagar transformed buildings and vacant lots along South Street into a dense mosaic environment of mirrors, tiles, bottles, bicycle wheels and found objects. The nonprofit attraction preserves a multi-level indoor and outdoor labyrinth that visitors can enter with a timed ticket.', 'open', 'https://www.phillymagicgardens.org/', 'America/New_York', now()),
  ('The Stoogeum', 'the-stoogeum', 'museums', 40.17797, -75.22414, 'Lower Gwynedd Township', 'PA', 'The Stoogeum is a museum devoted entirely to the Three Stooges, with thousands of photographs, costumes, props, posters, toys and personal artifacts. Public openings are limited and irregular compared with a conventional museum, so travelers should confirm an open house or appointment before routing here.', 'limited', 'https://stoogeum.com/', 'America/New_York', now()),
  ('American Treasure Tour Museum', 'american-treasure-tour-museum', 'museums', 40.12749, -75.45356, 'Upper Providence Township', 'PA', 'The American Treasure Tour fills a huge former industrial building with automatic music machines, classic automobiles, animated store displays, advertisements and other pieces of American popular culture. Much of the collection is seen from a guided tram ride through rows of densely packed artifacts.', 'open', 'https://americantreasuretour.com/', 'America/New_York', now()),
  ('Wagner Free Institute of Science', 'wagner-free-institute-of-science', 'museums', 39.9806, -75.1629, 'Philadelphia', 'PA', 'The Wagner Free Institute preserves a nineteenth-century natural-history museum that has changed remarkably little since its displays were arranged in the 1800s. Thousands of fossils, shells, minerals, skeletons and taxidermy specimens remain in wooden cases under the original gallery structure.', 'open', 'https://www.wagnerfreeinstitute.org/', 'America/New_York', now()),
  ('Columbus Chapel and Boal Mansion Museum', 'columbus-chapel-and-boal-mansion-museum', 'museums', 40.77906, -77.79929, 'Boalsburg', 'PA', 'The Boal estate contains an imported European chapel associated with the Columbus family along with an unusually eclectic collection of historic objects. Guided tours include claims of Columbus-family artifacts, religious pieces, weapons, carriages and other material gathered by generations of the Boal family.', 'limited', 'https://boalmuseum.com/', 'America/New_York', now()),
  ('Crystal Cave', 'crystal-cave-kutztown', 'roadside-oddities', 40.52614, -75.84249, 'Richmond Township', 'PA', 'Crystal Cave was discovered in 1871 and became one of Pennsylvania''s earliest commercial show caves. Seasonal guided tours descend into passages filled with stalactites, stalagmites and crystalline formations, with additional exhibits and attractions above ground.', 'limited', 'https://crystalcavepa.com/', 'America/New_York', now()),
  ('Rausch Gap Ghost Town', 'rausch-gap-ghost-town', 'weird-history', 40.49953, -76.59774, 'Cold Spring Township', 'PA', 'Rausch Gap was a nineteenth-century railroad and coal settlement that disappeared after industry moved away, leaving foundations, a cemetery and other traces in the forest. The abandoned town site is reached on foot along the Appalachian Trail and related trails, so it requires a hike rather than a roadside visit.', 'limited', 'https://en.wikipedia.org/wiki/Rausch_Gap,_Pennsylvania', 'America/New_York', now()),
  ('Sideling Hill Tunnel on the Abandoned Pennsylvania Turnpike', 'sideling-hill-tunnel-on-the-abandoned-pennsylvania-turnpike', 'weird-history', 40.04851, -78.12915, 'Fulton County', 'PA', 'Sideling Hill Tunnel is a 6,782-foot former Pennsylvania Turnpike tunnel abandoned when the highway was rerouted in 1968. It is now part of the informal Pike2Bike route; reaching it requires hiking or cycling, and the interior is completely unlit, wet and rough, so visitors need lights and should use the established access points.', 'limited', 'https://highways.dot.gov/highway-history/general-highway-history/back-time/abandoned-pennsylvania-turnpike', 'America/New_York', now()),
  ('Glencairn Museum', 'glencairn-museum', 'museums', 40.13694, -75.06389, 'Bryn Athyn', 'PA', 'Glencairn is a castle-like former residence built between the 1920s and 1930s for the Pitcairn family and now used as a museum of religious art and history. Its galleries contain medieval stained glass, ancient artifacts and objects from religious traditions around the world, with access through the museum''s posted visit schedule.', 'open', 'https://www.glencairnmuseum.org/', 'America/New_York', now()),
  ('Jennie Wade House', 'jennie-wade-house', 'haunted', 39.82332, -77.23079, 'Gettysburg', 'PA', 'Twenty-year-old Jennie Wade was killed inside this house by a stray bullet during the Battle of Gettysburg, making her the battle''s only civilian fatality killed by direct fire. The preserved house operates as a museum and has also accumulated stories of apparitions, voices and other paranormal activity.', 'open', 'https://www.gettysburgmuseum.com/jennie-wade-house/', 'America/New_York', now()),
  ('Jean Bonnet Tavern', 'jean-bonnet-tavern', 'haunted', 40.04243, -78.56058, 'Napier Township', 'PA', 'The stone Jean Bonnet Tavern dates to the eighteenth century and served travelers along the historic Forbes Road and Lincoln Highway corridor. The owners openly document generations of ghost stories involving apparitions and unexplained activity, while the building continues to operate as a tavern and inn.', 'open', 'https://www.jeanbonnettavern.com/ghosts/', 'America/New_York', now()),
  ('Roadside America Miniature Village', 'roadside-america-miniature-village', 'roadside-oddities', 40.51667, -76.11806, 'Shartlesville', 'PA', 'Roadside America was a massive hand-built miniature landscape that grew for decades into an elaborate model of small-town America filled with trains, buildings, lights and moving figures. The attraction permanently closed in 2020 and the collection was dispersed, so the former location is worth recording historically but there is nothing to enter today.', 'closed', 'https://en.wikipedia.org/wiki/Roadside_America', 'America/New_York', now()),
  ('Fort Roberdeau', 'fort-roberdeau', 'weird-history', 40.58272, -78.27379, 'Tyrone Township', 'PA', 'Fort Roberdeau reconstructs a Revolutionary War-era lead-mining fort built in 1778 to protect local mining operations. The palisade, cabins and grounds can be explored during its seasonal tour season, while the exterior grounds remain visible outside normal interior-tour hours.', 'limited', 'https://fortroberdeau.org/', 'America/New_York', now()),
  ('Bethlehem Steel Blast Furnaces at SteelStacks', 'bethlehem-steel-blast-furnaces-at-steelstacks', 'weird-history', 40.61487, -75.36953, 'Bethlehem', 'PA', 'Five enormous blast furnaces from the former Bethlehem Steel plant loom over the SteelStacks arts campus, preserving the scale of a company that once employed tens of thousands of workers. Visitors can view the furnaces freely from the public campus and Hoover-Mason Trestle, with guided industrial-history tours available separately.', 'open', 'https://www.historicbethlehem.org/visit-us/experience/rise-and-fall-of-bethlehem-steel-walking-tour/', 'America/New_York', now()),
  ('Penn''s Cave', 'penns-cave', 'roadside-oddities', 40.88256, -77.61223, 'Gregg Township', 'PA', 'Penn''s Cave is a limestone cavern explored almost entirely by boat, with tours traveling along an underground stream before emerging onto the property''s lake. The attraction operates on a seasonal schedule and also includes wildlife and farm tours above ground.', 'limited', 'https://www.pennscave.com/', 'America/New_York', now()),
  ('Old Jail Museum Handprint', 'old-jail-museum-handprint', 'haunted', 40.86384, -75.74649, 'Jim Thorpe', 'PA', 'The former Carbon County Jail opened in 1871 and is infamous for the executions of men accused of belonging to the Molly Maguires. Cell 17 contains a dark handprint that local lore says repeatedly returned after attempts to remove it, and visitors can see it on seasonal guided tours of the jail.', 'limited', 'https://theoldjailmuseum.com/', 'America/New_York', now()),
  ('No. 9 Coal Mine and Museum', 'no-9-coal-mine-and-museum', 'museums', 40.82867, -75.89693, 'Lansford', 'PA', 'No. 9 operated as an anthracite mine from the nineteenth century until 1972 and was later reopened as a preserved underground attraction. Seasonal tours take visitors about 1,600 feet into the mountain by rail before a guided walk past the mine shaft, mule way and underground hospital.', 'limited', 'https://no9coalmine.com/', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  verified_at   = excluded.verified_at;
