-- OddWay events: cryptid, UFO and paranormal festivals, 2026.
--
-- Researched by hand. Roughly half the dates are estimates based on prior-year
-- patterns rather than confirmed announcements, and date_confidence records
-- which is which. The site must never present an estimate as fact: someone
-- driving four hours to a field on the wrong weekend is the failure this
-- column exists to prevent.
--
-- Coordinates are null for now and filled in by a later geocoding pass. The
-- listing works without them; only distance-from-you needs them.

insert into public.events
  (name, slug, city, state, category, start_date, days, display_date,
   date_confidence, website, contact, notes)
values
  ('Beast of Busco Turtle Days', 'beast-of-busco-turtle-days', 'Churubusco', 'IN', 'cryptid', '2026-06-10', 4, 'June 10-13, 2026 (confirmed)', 'confirmed', 'turtledays.org', 'turtledaysfestival@aol.com (Pres. Nathan Van Horn); vendor/parade: turtledaysparade@gmail.com', 'Dates confirmed via official site (74th annual, longest-running festival in Indiana). Attendance is a rough estimate (multi-day town-wide event); no single official count published.'),
  ('Big Muddy Monster Festival', 'big-muddy-monster-festival', 'Murphysboro', 'IL', 'cryptid', '2026-06-20', 1, '~June 20, 2026 (based on 2025 pattern)', 'estimated', null, 'Facebook page only: facebook.com/profile.php?id=100094542990087', 'ESTIMATE: date based on prior-year (June 21, 2025) timing; no dedicated website found. Attendance is a rough estimate.'),
  ('Bigfoot at the 40 (formerly Honobia Bigfoot Festival & Conference)', 'bigfoot-at-the-40-formerly-honobia-bigfoot-festival-conference', 'Honobia', 'OK', 'cryptid', '2026-10-02', 3, 'October 2-4, 2026 (confirmed pattern - first weekend of Oct)', 'confirmed', 'bigfootcapitalevents.com / nobrobigfoot.org', 'Artie Carnes, Director, (918) 942-8869', 'Event was renamed ''Bigfoot at the 40'' after an organizer transition; held annually the first weekend of October at Christ''s 40 Acres. Attendance estimated.'),
  ('Bigfoot Daze', 'bigfoot-daze', 'Willow Creek', 'CA', 'cryptid', '2026-06-27', 1, 'June 27, 2026 (confirmed)', 'confirmed', null, 'Facebook page: facebook.com/bigfootdazewc/', 'Date confirmed via event Facebook page (65th annual, running since 1960). Attendance is an estimate; no official count published.'),
  ('Blue Bridge Squatch Fest', 'blue-bridge-squatch-fest', 'Owensboro', 'KY', 'cryptid', '2026-09-26', 1, 'September 26, 2026 (confirmed)', 'confirmed', null, 'Coverage/contact via Owensboro Times article and organizer Fred Chism''s Facebook event page', 'Date confirmed via Owensboro Times news coverage. Inaugural (2026) event, no prior-year data; organizer quoted hoping for ''thousands.'' Attendance is a conservative first-year estimate.'),
  ('Champ Day', 'champ-day', 'Port Henry', 'NY', 'cryptid', '2026-08-01', 1, 'August 1, 2026 (first Saturday of August, recurring)', 'confirmed', null, 'Contact via Town of Moriah / Port Henry, NY local government', 'Date confirmed as a recurring pattern (Wikipedia: ''first Saturday of every August''). No official festival website found; attendance is an estimate.'),
  ('Contact in the Desert', 'contact-in-the-desert', 'Joshua Tree', 'CA', 'ufo', '2026-05-28', 5, 'May 28 - June 1, 2026 (confirmed)', 'confirmed', 'contactinthedesert.com', 'Use ''Contact Us'' form at contactinthedesert.com (no public email located)', 'Dates confirmed via official event site. Billed as ''largest UFO conference in the world''; attendance is an estimate, no official figure published.'),
  ('Covington Cryptid Block Party', 'covington-cryptid-block-party', 'Covington', 'KY', 'cryptid', '2026-10-24', 1, 'October 24, 2026 (confirmed)', 'confirmed', 'cryptidcov.blog', 'Contact via cryptidcov.blog site / Facebook page (no public email located)', 'Date confirmed via event site. Attendance is an estimate for this newer (est. 2024-25) event.'),
  ('Cryptid Con', 'cryptid-con', 'Elizabethtown', 'KY', 'cryptid', '2026-11-07', 2, 'Estimated Nov 2026 (historically held in November)', 'estimated', 'cryptidcon.com', 'Use contact form at cryptidcon.com (no public email located)', 'ESTIMATE: exact 2026 date not confirmed at time of research; based on historical November timing. Attendance estimated.'),
  ('Estes Park Bigfoot Days', 'estes-park-bigfoot-days', 'Estes Park', 'CO', 'cryptid', '2026-04-24', 2, 'April 24-25, 2026 (confirmed)', 'confirmed', 'visitestespark.com/events-calendar/spring-events/bigfoot-days', 'Contact via Visit Estes Park (visitestespark.com contact page)', 'Dates confirmed via local news coverage; described as one of the country''s largest Bigfoot festivals. Attendance is an estimate (''thousands'').'),
  ('Flatwoods Monster Festival', 'flatwoods-monster-festival', 'Sutton/Flatwoods', 'WV', 'cryptid', '2026-09-12', 1, 'Estimated September 2026', 'estimated', null, 'Facebook page: facebook.com/Flatwoods-Monster-Fest-1254538164701000', 'ESTIMATE: historically a September event; exact 2026 date not confirmed. Attendance estimated.'),
  ('Forest County Bigfoot Festival', 'forest-county-bigfoot-festival', 'Marienville (Allegheny NF)', 'PA', 'cryptid', '2026-06-12', 3, 'June 12-14, 2026 (confirmed)', 'confirmed', 'forestcountybigfootfestival.com', 'Vendor applications via forestcountybigfootfestival.com (no public email located; 501(c)(3) nonprofit)', 'Dates confirmed. Newer, fast-growing event on the festival circuit; attendance estimated.'),
  ('Fouke Monster Festival', 'fouke-monster-festival', 'Fouke', 'AR', 'cryptid', '2026-04-25', 1, 'April 25, 2026 (confirmed)', 'confirmed', 'Eventbrite listing (no standalone site found)', 'Presented by Craig Woolheater - contact via Eventbrite listing page', 'Date confirmed via Eventbrite listing. Attendance estimated; no official figure published.'),
  ('Frogman Festival (Official)', 'frogman-festival-official', 'Loveland', 'OH', 'cryptid', '2026-03-07', 1, 'March 7, 2026 (confirmed)', 'confirmed', 'frogmanfestival.org', 'Contact via frogmanfestival.org site / Facebook page (no public email located)', 'Date confirmed. Indoor conference-center event (Oasis Conference Center); attendance estimated.'),
  ('Georgia Bigfoot Conference', 'georgia-bigfoot-conference', 'Clayton', 'GA', 'cryptid', '2026-09-12', 2, 'Estimated fall 2026', 'estimated', 'georgiabigfootconference.org', 'dr.john.stamey@gmail.com (vendor tables, per official site)', 'ESTIMATE: exact 2026 date not confirmed at time of research. Attendance estimated from event''s typical scale (50+ vendors, 400+ seats).'),
  ('Glide Sasquatch Festival', 'glide-sasquatch-festival', 'Glide', 'OR', 'cryptid', '2026-07-25', 2, 'Estimated summer 2026', 'estimated', 'glidesasquatchfestival.com', 'Contact via glidesasquatchfestival.com (hosted by Glide Revitalization nonprofit; no public email located)', 'ESTIMATE: exact 2026 date not confirmed; 2023-24 actual attendance reported at 4,000+, used as basis for 2026 estimate.'),
  ('Grafton Monster Festival', 'grafton-monster-festival', 'Grafton', 'WV', 'cryptid', '2026-06-12', 2, 'Estimated June 12-13, 2026', 'estimated', null, 'Official Grafton Monster Festival Facebook page (organized with Black Cat Rookery Book Store / Grafton Monster Museum)', 'ESTIMATE: date based on prior-year pattern (2nd annual was June 13-14, 2025); newer event, high estimated growth rate.'),
  ('Great Florida Bigfoot Conference', 'great-florida-bigfoot-conference', 'Ocala', 'FL', 'cryptid', '2026-06-13', 1, 'June 13, 2026 (confirmed)', 'confirmed', 'bigfootFL.com / gatherupevents.com/florida-bigfoot-conference', 'Gather Up Events, (423) 584-3513', 'Date confirmed via organizer''s Facebook page and Gather Up Events site. 3,000+ actual attendance confirmed via news coverage (Fox 35 Orlando).'),
  ('Green Eyes Festival', 'green-eyes-festival', 'Chickamauga', 'GA', 'cryptid', '2026-10-17', 1, 'Estimated mid-October 2026', 'estimated', null, 'Contact via City of Chickamauga Economic Development & Events Director (organized in partnership with the city)', 'ESTIMATE: exact 2026 date not confirmed; prior years held mid/late October. 2025 actual attendance reported at ~4,500 (Walker Rocks).'),
  ('Hocking Hills Bigfoot Festival', 'hocking-hills-bigfoot-festival', 'Logan/Vinton County', 'OH', 'cryptid', '2026-08-14', 2, 'August 14-15, 2026 (confirmed)', 'confirmed', null, 'Facebook page: facebook.com/OhioBigfootConference', 'Dates confirmed (moved to Vinton County Fairgrounds for 2026). Attendance estimated.'),
  ('Lake Worth Monster Bash', 'lake-worth-monster-bash', 'Lake Worth', 'TX', 'cryptid', '2026-10-10', 1, 'Estimated October 2026', 'estimated', null, 'Facebook page: facebook.com/LakeWorthMonsterBash', 'ESTIMATE: exact 2026 date not confirmed; historically an October event. Attendance estimated.'),
  ('Lurch Fest', 'lurch-fest', 'Philippi', 'WV', 'paranormal', '2026-07-18', 1, 'Estimated summer 2026', 'estimated', null, 'Contact via Barbour County Historical Museum, Philippi, WV', 'ESTIMATE: small local festival (Ted Cassidy/''Lurch'' tribute, cryptid-adjacent paranormal circuit); date and attendance estimated.'),
  ('Mothman Festival', 'mothman-festival', 'Point Pleasant', 'WV', 'cryptid', '2026-09-19', 2, 'September 19-20, 2026 (confirmed)', 'confirmed', 'mothmanfestival.com', 'Mothman Museum, (304) 812-5211; use contact form at mothmanfestival.com (public email not fully legible on site)', 'Dates confirmed via official site. 2023 actual attendance reported at 15,000+ (Wikipedia); 2026 figure is an estimate off that base.'),
  ('Ozark Mountain UFO Conference', 'ozark-mountain-ufo-conference', 'Eureka Springs', 'AR', 'ufo', '2026-04-10', 3, 'April 10-12, 2026 (confirmed)', 'confirmed', 'ozarkufoconference.com', 'info@ozarkmt.com, (479) 738-2348', 'Dates confirmed. Mature (30-year) niche conference; attendance estimated, low/flat growth assumed.'),
  ('Roswell UFO Festival', 'roswell-ufo-festival', 'Roswell', 'NM', 'ufo', '2026-07-02', 3, 'July 2-4, 2026 (confirmed)', 'confirmed', 'ufofestival.com', 'ufofestival@roswell-nm.gov', 'Dates and attendance (12,000+, preliminary) confirmed via KRQE News coverage of the actual 2026 event.'),
  ('Sasquatch Summer Fest', 'sasquatch-summer-fest', 'Oakridge', 'OR', 'cryptid', '2026-07-10', 2, 'July 10-11, 2026 (confirmed)', 'confirmed', 'sasquatchsummerfest.com', 'Contact via sasquatchsummerfest.com (no public email located)', 'Dates confirmed via official event site. Attendance estimated for this newer event.'),
  ('Smoky Mountain Bigfoot Festival', 'smoky-mountain-bigfoot-festival', 'Townsend', 'TN', 'cryptid', '2026-08-22', 1, 'Estimated August 2026 (6th annual)', 'estimated', 'thebigfest.com', 'Organized by Gather Up Events, (423) 584-3513', 'ESTIMATE: exact 2026 date not confirmed at time of research; historically an August event. Attendance estimated.'),
  ('South Carolina Bigfoot Festival', 'south-carolina-bigfoot-festival', 'Pickens/Liberty area', 'SC', 'cryptid', '2026-10-10', 1, 'Estimated October 2026 (7th year)', 'estimated', 'scbigfootfestival.com', 'Contact via scbigfootfestival.com (no public email located)', 'ESTIMATE: exact 2026 date not confirmed; historically a fall event. Attendance estimated.'),
  ('Squonkapalooza', 'squonkapalooza', 'Johnstown', 'PA', 'cryptid', '2026-08-01', 1, 'Estimated August 1, 2026', 'estimated', 'squonkapalooza.com', 'Contact via squonkapalooza.com (no public email located)', 'ESTIMATE: date based on 2025 pattern (Aug 2, 2025); newer event, high estimated growth rate.'),
  ('Texas Bigfoot Film Festival', 'texas-bigfoot-film-festival', 'Marshall', 'TX', 'cryptid', '2026-09-19', 1, 'Estimated fall 2026', 'estimated', 'bigfootfilmfestival.com', 'Founded/presented by Craig Woolheater - contact via bigfootfilmfestival.com', 'ESTIMATE: small film-focused event; exact date and attendance not officially published.'),
  ('Upper Cumberland Bigfoot Festival', 'upper-cumberland-bigfoot-festival', 'Cookeville', 'TN', 'cryptid', '2026-10-17', 2, 'October 17-18, 2026 (confirmed)', 'confirmed', 'centerhillevents.com', 'Center Hill Events - vendor applications at centerhillevents.com (no public email located)', 'Dates confirmed (new organizer, Center Hill Events, expanded to 2 days for 2026). Attendance estimated.'),
  ('Veggie Man Day', 'veggie-man-day', 'Fairmont', 'WV', 'cryptid', '2026-07-11', 1, 'Estimated July 11, 2026', 'estimated', null, 'Frank & Jane Gabor WV Folklife Center, Fairmont State University; organized with ''Mothboys'' podcast - contact via Facebook event page', 'ESTIMATE: date based on prior-year pattern (2nd Saturday of July); small, newer event, attendance estimated.'),
  ('West Virginia Bigfoot Festival', 'west-virginia-bigfoot-festival', 'Sutton (Nicholas Co. Veterans Memorial Park)', 'WV', 'cryptid', '2026-10-09', 3, 'October 9-11, 2026 (confirmed)', 'confirmed', 'wvbigfootmuseum.org/about-the-festival', 'Contact via West Virginia Bigfoot Museum site (wvbigfootmuseum.org)', 'Date confirmed via official West Virginia Bigfoot Museum site - moved to Nicholas County Veterans Memorial Park for 2026 with camping/RV sites. One of WV''s largest cryptid festivals; attendance estimated.'),
  ('Yakima Valley Bigfoot Con', 'yakima-valley-bigfoot-con', 'Yakima', 'WA', 'cryptid', '2026-10-17', 1, 'Estimated October 2026', 'estimated', null, 'Facebook page: facebook.com/Bigfoot-CON-2022-Yakima-121038510172676', 'ESTIMATE: exact 2026 date not confirmed; historically an October event. Attendance estimated.')
on conflict (slug) do update set
  city            = excluded.city,
  state           = excluded.state,
  category        = excluded.category,
  start_date      = excluded.start_date,
  days            = excluded.days,
  display_date    = excluded.display_date,
  date_confidence = excluded.date_confidence,
  website         = excluded.website,
  contact         = excluded.contact,
  notes           = excluded.notes,
  updated_at      = now();
