-- South Carolina, three batches.
--
-- Eight dropped as duplicates, all of them inside the submission rather than
-- against the existing index. The final batch repeats places from the first
-- two under fuller names: Woods Bay State Park and Woods Bay State Park —
-- Carolina Bay are the same park.
--
-- Three are the harder case. Guignard Brick Works, the Macaulay Museum of
-- Dental History and Blenheim Mineral Springs each arrived twice under an
-- identical name with coordinates metres apart, so neither a name comparison
-- nor a position comparison alone caught both copies of all three.
--
-- For those the copy with the better citation is kept — the South Carolina
-- Picture Project and the Medical University's own library rather than a
-- travel guide. Choosing which duplicate survives is a chance to improve a
-- source rather than a coin toss.
--
-- One more dropped against the existing index rather than within the batch:
-- World's Largest Sweet Tea is already here, 22 metres away, under a slug
-- differing only in how the apostrophe was written. Apostrophes have now
-- hidden four duplicates across five states, which is why the position check
-- runs at all.
--
-- The generator now refuses to run if a preferred source matches no copy. The
-- first version of this dropped Blenheim entirely, because the source I
-- assumed it had was not the source it had, and the only symptom was one slug
-- missing from a list of a hundred and eleven.
--
-- 111 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Angel Oak', 'angel-oak', 'roadside-oddities', 32.72144, -80.08239, 'Johns Island', 'SC', 'This enormous Southern live oak spreads massive limbs across more than 17,000 square feet of shade, with some branches resting on the ground before rising again. Estimates place it at several centuries old, and local folklore has also attached ghost stories to the tree. The City of Charleston operates the surrounding park with set visiting hours.', 'limited', 'https://www.atlasobscura.com/places/the-angel-oak-tree-johns-island-south-carolina', 'https://www.charleston-sc.gov/153/Angel-Oak', 'America/New_York', now()),
  ('Pearl Fryar Topiary Garden', 'pearl-fryar-topiary-garden', 'roadside-oddities', 34.20577, -80.27101, 'Bishopville', 'SC', 'Self-taught artist Pearl Fryar transformed rescued and discarded shrubs into hundreds of sweeping, abstract topiary sculptures across his three-acre yard. Fryar died in April 2026, but the nonprofit preserving his work continues to operate the garden as a free public attraction and living memorial.', 'limited', 'https://www.pearlfryargarden.org/home', null, 'America/New_York', now()),
  ('Devil’s Kitchen at Caesars Head', 'devils-kitchen-at-caesars-head', 'folklore', 35.10586, -82.62611, 'Cleveland', 'SC', 'A narrow passage splits a massive rock formation near the Caesars Head overlook. Local legend claims the Devil accidentally carved the opening after burning his dinner and angrily stomping on the rock, while geology offers a less supernatural explanation.', 'limited', 'https://www.atlasobscura.com/places/devils-kitchen-at-caesars-head', null, 'America/New_York', now()),
  ('Old Slave Mart Museum', 'old-slave-mart-museum', 'weird-history', 32.77795, -79.92842, 'Charleston', 'SC', 'This building is part of the only known surviving complex once used as a commercial slave auction facility in South Carolina. The museum confronts Charleston’s central role in the domestic slave trade through artifacts, documents, and interpretation of the people bought and sold here.', 'limited', 'https://www.charleston-sc.gov/160/Old-Slave-Mart-Museum', null, 'America/New_York', now()),
  ('Old Sheldon Church Ruins', 'old-sheldon-church-ruins', 'weird-history', 32.61853, -80.78044, 'Yemassee', 'SC', 'Brick columns and walls from an 18th-century church stand roofless beneath live oaks in the Lowcountry. The building was damaged during the Revolutionary War, rebuilt, and later left in ruins after the Civil War, producing one of South Carolina’s most atmospheric roadside historic sites.', 'open', 'https://www.scpictureproject.org/beaufort-county/old-sheldon-church.html', null, 'America/New_York', now()),
  ('Yogi Bear’s Honey Fried Chicken', 'yogi-bears-honey-fried-chicken', 'roadside-oddities', 34.36918, -80.07085, 'Hartsville', 'SC', 'Nearly every location in the short-lived Yogi Bear fast-food chain disappeared decades ago, but Hartsville still has the last operating Yogi Bear’s Honey Fried Chicken restaurant. The surviving cartoon-branded restaurant is an improbable piece of 1960s and 1970s franchise history that remains open in 2026.', 'open', 'https://visithartsvillesc.com/listings/eat/eat-family-restaurants/', null, 'America/New_York', now()),
  ('Poinsett Bridge', 'poinsett-bridge', 'roadside-oddities', 35.12941, -82.38432, 'Landrum', 'SC', 'Built in 1820, this stone bridge features a distinctive Gothic arch and is commonly identified as South Carolina’s oldest surviving bridge. Its isolated forest setting has also accumulated ghost stories and legends involving unexplained lights and sounds.', 'open', 'https://greenvillerec.com/parks/poinsett-bridge/', null, 'America/New_York', now()),
  ('Old Charleston City Jail', 'old-charleston-city-jail', 'haunted', 32.7785, -79.93717, 'Charleston', 'SC', 'Charleston’s old jail held criminals, pirates, enslaved people, and prisoners of war during more than a century of operation. Its grim history has given it one of the city’s strongest paranormal reputations, and guided haunted-jail tours continue to enter the building in 2026.', 'limited', 'https://www.charlestoncvb.com/plan-your-trip/tours-attractions~204/historic-sites~1146/haunted-jail-tour-at-the-old-city-jail~33433.html', null, 'America/New_York', now()),
  ('Mars Bluff Atomic Bomb Accident Marker', 'mars-bluff-atomic-bomb-accident-marker', 'weird-history', 34.19668, -79.66327, 'Florence', 'SC', 'In 1958, a U.S. Air Force B-47 accidentally dropped a nuclear weapon near Mars Bluff. The nuclear capsule was not inside the bomb, but its conventional explosives detonated and blasted a crater roughly 50 to 70 feet across while injuring members of the Gregg family. This pin is the public historical marker; the actual crater nearby is on private property and should not be entered without permission. Artifacts: https://www.flocomuseum.org/featured-objects/mars-bluff-bomb/', 'roadside', 'https://www.hmdb.org/m.asp?m=132036', null, 'America/New_York', now()),
  ('Stumphouse Tunnel', 'stumphouse-tunnel', 'weird-history', 34.76482, -83.06404, 'Walhalla', 'SC', 'Workers began boring this railroad tunnel through Stumphouse Mountain in the 1850s as part of an ambitious route through the Blue Ridge, but construction ended before the tunnel was completed. Visitors can walk into part of the dark unfinished passage, which later became useful for aging Clemson blue cheese.', 'limited', 'https://www.stumphousetunnel.com/', null, 'America/New_York', now()),
  ('God’s Acre Healing Springs', 'gods-acre-healing-springs', 'folklore', 33.39197, -81.27346, 'Blackville', 'SC', 'Local tradition says wounded British soldiers recovered after drinking from these springs during the Revolutionary War, creating a long-lasting belief in the water’s healing properties. In 1944 the surrounding land was deeded to “God Almighty” so the spring would remain freely accessible to the public.', 'open', 'https://discoversouthcarolina.com/articles/history-and-culture-at-the-healing-springs-in-blackville', null, 'America/New_York', now()),
  ('Tunnelvision', 'tunnelvision', 'roadside-oddities', 34.0072, -81.03252, 'Columbia', 'SC', 'Artist Blue Sky painted a remarkably convincing tunnel entrance on the flat wall of a downtown building. The perspective and painted roadway create an optical illusion that can briefly make the brick wall look like an actual passage through the structure.', 'open', 'https://www.atlasobscura.com/places/tunnelvision', null, 'America/New_York', now()),
  ('Colonial Dorchester State Historic Site', 'colonial-dorchester-state-historic-site', 'weird-history', 32.94812, -80.17008, 'Summerville', 'SC', 'The ruins of the colonial town of Dorchester include brick foundations, an old church tower, cemetery, fortifications, and traces of streets from a settlement largely abandoned after the Revolutionary era. The preserved landscape functions like an archaeological ghost town beside the Ashley River.', 'limited', 'https://southcarolinaparks.com/colonial-dorchester', null, 'America/New_York', now()),
  ('Unitarian Church Cemetery', 'unitarian-church-cemetery', 'weird-history', 32.77857, -79.93444, 'Charleston', 'SC', 'Dense vegetation, leaning stones, elaborate monuments, and deliberately overgrown paths give this historic churchyard a distinctive appearance. Charleston folklore connects the cemetery with ghost stories, including traditions surrounding the mysterious “Lady in White.”', 'limited', 'https://www.atlasobscura.com/places/unitarian-church-cemetery', 'https://charlestonuu.org/cemetery/', 'America/New_York', now()),
  ('Morgan Island — “Monkey Island”', 'morgan-island-monkey-island', 'roadside-oddities', 32.47741, -80.51955, 'Morgan Island', 'SC', 'Thousands of free-ranging rhesus macaques live on this isolated Lowcountry island, earning it the nickname Monkey Island. The colony exists for research purposes, and the island is not open to public landing; travelers should view it only legally from the water and keep their distance.', 'roadside', 'https://www.atlasobscura.com/places/morgan-island', null, 'America/New_York', now()),
  ('Woods Bay State Park', 'woods-bay-state-park', 'roadside-oddities', 33.94599, -79.99285, 'Olanta', 'SC', 'This state park protects one of the mysterious elliptical depressions known as Carolina bays. The origin of the thousands of similarly shaped wetlands scattered across the coastal plain has inspired scientific debate and fringe theories for generations.', 'open', 'https://southcarolinaparks.com/woods-bay', null, 'America/New_York', now()),
  ('Oyotunji African Village', 'oyotunji-african-village', 'roadside-oddities', 32.60994, -80.80291, 'Seabrook', 'SC', 'Founded in 1970, Oyotunji was created as a Yoruba cultural and religious community in rural South Carolina. Shrines, ceremonial spaces, traditional artwork, festivals, and an unusual political structure make the village unlike virtually any other community in the United States.', 'limited', 'https://www.atlasobscura.com/places/oyotunji-african-village', 'https://www.oyotunji.org/', 'America/New_York', now()),
  ('Charleston Tea Garden', 'charleston-tea-garden', 'roadside-oddities', 32.61814, -80.18522, 'Wadmalaw Island', 'SC', 'Rows of tea plants spread across hundreds of acres at one of the few large-scale tea-growing operations in the continental United States. Visitors can see tea being processed and tour the fields, making an ordinarily imported drink into an unexpected Lowcountry agricultural attraction.', 'open', 'https://charlestonteagarden.com/', null, 'America/New_York', now()),
  ('H.L. Hunley Submarine', 'hl-hunley-submarine', 'roadside-oddities', 32.85625, -79.95827, 'North Charleston', 'SC', 'The Confederate submarine H.L. Hunley became the first combat submarine to sink an enemy warship and then vanished with its crew in 1864. After being recovered from the ocean floor in 2000, the real vessel was placed in a conservation tank where weekend visitors can see it alongside recovered artifacts.', 'limited', 'https://www.hunley.org/', null, 'America/New_York', now()),
  ('Landsford Canal State Park', 'landsford-canal-state-park', 'weird-history', 34.78118, -80.87858, 'Catawba', 'SC', 'Ruins of a 19th-century canal system sit along the Catawba River, including stonework left from an attempt to bypass dangerous rapids for commercial traffic. In late spring the river also becomes famous for enormous blooms of rare Rocky Shoals spider lilies.', 'limited', 'https://southcarolinaparks.com/landsford-canal', null, 'America/New_York', now()),
  ('St. Helena Parish Chapel of Ease Ruins', 'st-helena-parish-chapel-of-ease-ruins', 'weird-history', 32.37528, -80.57667, 'Saint Helena Island', 'SC', 'Tabby walls are all that remain of a chapel built in the 1700s for plantation families who lived too far from Beaufort’s main parish church. Fire destroyed the chapel after the Civil War, leaving a stark shell and adjoining cemetery beneath Lowcountry trees.', 'open', 'https://www.atlasobscura.com/places/st-helena-parish-chapel-of-ease-ruins', null, 'America/New_York', now()),
  ('Neverbust Chain', 'neverbust-chain', 'weird-history', 34.0056, -81.03498, 'Columbia', 'SC', 'A heavy iron chain displayed near the South Carolina State House carries an old story that it was once stretched across the Congaree River and advertised as impossible to break. Whether every part of the legend is accurate or not, the surviving chain became a peculiar local monument.', 'open', 'https://www.atlasobscura.com/places/neverbust-chain', null, 'America/New_York', now()),
  ('South of the Border', 'south-of-the-border', 'roadside-oddities', 34.49778, -79.30972, 'Hamer', 'SC', 'This sprawling Interstate 95 tourist complex is impossible to miss thanks to its giant sombrero tower, neon signs, oversized animals, fiberglass figures, shops, motel, and aggressively kitschy Mexican-themed architecture. Decades of highway advertising make the attraction part roadside stop and part surreal landmark.', 'open', 'https://www.sobpedro.com/', null, 'America/New_York', now()),
  ('Button Museum', 'button-museum', 'roadside-oddities', 34.24581, -80.3339, 'Bishopville', 'SC', 'Dalton Stevens, the “Button King,” covered a suit, car, hearse, coffin, piano, toilet, and numerous other objects with thousands of buttons after insomnia led him into an obsessive art project. His family continues to preserve the collection in a small museum that remains free and open to visitors.', 'open', 'https://apnews.com/article/a5c8456bb621110922eee99cc221df71', null, 'America/New_York', now()),
  ('King Neptune Sundial', 'king-neptune-sundial', 'roadside-oddities', 32.1805, -80.72867, 'Hilton Head Island', 'SC', 'A huge bronze Neptune towers over Shelter Cove Harbour while also functioning as part of a working sundial. The sculpture’s scale, trident, and unusual practical purpose make it far stranger than a standard waterfront monument.', 'open', 'https://www.atlasobscura.com/places/king-neptune-sundial', null, 'America/New_York', now()),
  ('Forty Acre Rock Heritage Preserve', 'forty-acre-rock-heritage-preserve', 'roadside-oddities', 34.66748, -80.52569, 'Kershaw', 'SC', 'Despite its name, the centerpiece is an exposed granite outcrop of roughly 14 acres rather than forty. Shallow pools on the almost lunar-looking stone support rare plants, while the preserve also contains trails, a waterfall, cave-like formations, and other granite exposures.', 'limited', 'https://www.sctrails.net/trails/trail/forty-acre-rock', null, 'America/New_York', now()),
  ('Gaffney Peachoid', 'gaffney-peachoid', 'roadside-oddities', 35.09527, -81.68588, 'Gaffney', 'SC', 'A 135-foot water tower painted as a gigantic peach looms beside Interstate 85, complete with leaf, stem, and a carefully modeled crease. The Peachoid honors the region’s peach industry and became nationally recognizable after appearing in House of Cards.', 'roadside', 'https://discoversouthcarolina.com/products/1470', null, 'America/New_York', now()),
  ('Upper Room Chapel', 'upper-room-chapel', 'roadside-oddities', 35.06235, -80.90259, 'Fort Mill', 'SC', 'This chapel survives from the enormous Heritage USA televangelist complex once operated by Jim and Tammy Faye Bakker. Modeled after the traditional Upper Room in Jerusalem, it continues to host worship services even though most of the surrounding Christian theme-park empire disappeared. Current services: https://www.btbab.net/about-1', 'limited', 'https://upperroomchapel.com/', null, 'America/New_York', now()),
  ('Blenheim Mineral Springs', 'blenheim-mineral-springs', 'weird-history', 34.50999, -79.64756, 'Blenheim', 'SC', 'Mineral water from this site became famous in the 1800s and eventually inspired Blenheim Ginger Ale, one of South Carolina’s oldest soft-drink traditions. The historic spring area remains routeable, although water flow and site condition can vary and visitors should not assume the spring is always running.', 'open', 'https://www.findaspring.com/spring/locations/north-america/usa/south-carolina/blenheim-mineral-spring/', null, 'America/New_York', now()),
  ('Thelma and Louise — Giant Pink and Gray Elephants', 'thelma-and-louise-giant-pink-and-gray-elephants', 'roadside-oddities', 32.2762, -81.08203, 'Hardeeville', 'SC', 'Two enormous fiberglass elephants known as Thelma and Louise have long served as roadside mascots for Crazy Joe’s fireworks businesses. The pair have moved over the years; this pin reflects their current Hardeeville-area home rather than an older location still repeated by some travel listings.', 'roadside', 'https://www.roadsideamerica.com/location/sc', null, 'America/New_York', now()),
  ('Giant’s Causeway Pillar', 'giants-causeway-pillar', 'roadside-oddities', 32.77744, -79.93128, 'Charleston', 'SC', 'A genuine basalt column removed from Northern Ireland’s Giant’s Causeway stands thousands of miles away in Charleston. The strange transplanted piece of geology gives visitors a small physical fragment of one of Europe’s most famous natural formations.', 'limited', 'https://www.atlasobscura.com/places/giants-causeway-pillar-section', null, 'America/New_York', now()),
  ('Kazoobie Kazoo Museum', 'kazoobie-kazoo-museum', 'museums', 32.43468, -80.72016, 'Beaufort', 'SC', 'Hundreds of kazoos and related instruments trace the surprisingly elaborate history of one of the world’s simplest musical devices. Visitors can see unusual novelty kazoos, historic examples, and the manufacturing operation that still produces the instruments.', 'open', 'https://www.atlasobscura.com/places/kazoo-museum', 'https://kazoomuseum.org/', 'America/New_York', now()),
  ('Alice Flagg’s Grave', 'alice-flaggs-grave', 'haunted', 33.46732, -79.1386, 'Pawleys Island', 'SC', 'A plain stone marked only “Alice” is associated with one of the Lowcountry’s best-known romantic ghost legends. Tradition says Alice Flagg died after her family opposed a secret engagement, and visitors still leave rings and tokens while searching for her supposed apparition.', 'open', 'https://www.atlasobscura.com/places/alice-flagg-s-grave', null, 'America/New_York', now()),
  ('Atalaya Castle', 'atalaya-castle', 'roadside-oddities', 33.50179, -79.06767, 'Murrells Inlet', 'SC', 'Industrialist Archer Huntington and sculptor Anna Hyatt Huntington built this sprawling Moorish-inspired winter residence in the 1930s. Its stark brick corridors, enclosed courtyards, ironwork, studios, and strange floor plan feel more like an abandoned Mediterranean fortress than a South Carolina beach house.', 'limited', 'https://www.atlasobscura.com/places/atalaya', null, 'America/New_York', now()),
  ('Horseshoe Falls at Musgrove Mill', 'horseshoe-falls-at-musgrove-mill', 'roadside-oddities', 34.5933, -81.85279, 'Clinton', 'SC', 'A short trail leads to a broad horseshoe-shaped waterfall inside a Revolutionary War historic site. The unusual combination of battlefield interpretation and a photogenic curved cascade makes it more than a standard history stop.', 'limited', 'https://southcarolinaparks.com/musgrove-mill', null, 'America/New_York', now()),
  ('Barnwell Sundial', 'barnwell-sundial', 'roadside-oddities', 33.24362, -81.36484, 'Barnwell', 'SC', 'A freestanding vertical sundial erected in the 1800s still occupies a traffic circle in downtown Barnwell. Its highly visible location and uncommon design turn an old timekeeping device into the town’s defining roadside monument.', 'open', 'https://www.scpictureproject.org/barnwell-county/barnwell-sundial.html', null, 'America/New_York', now()),
  ('Edisto Mystery Tree', 'edisto-mystery-tree', 'roadside-oddities', 32.55092, -80.28033, 'Edisto Island', 'SC', 'For years, passing motorists have decorated this roadside tree with an ever-changing collection of seasonal props, signs, toys, and costumes. No single display lasts forever, so the fun is seeing what bizarre version of the tree happens to exist when you arrive.', 'roadside', 'https://www.roadsideamerica.com/location/sc', null, 'America/New_York', now()),
  ('Christy Buchanan’s SHE Garden & Gallery', 'christy-buchanans-she-garden-gallery', 'roadside-oddities', 34.3929, -81.10282, 'Winnsboro', 'SC', 'Artist Christy Buchanan has filled her property with a bottle house, sculptural figures, decorated vehicles, arches, found-object art, and other handmade installations. The garden is on private property, with the gallery generally open on weekends or by appointment, so visitors should respect posted access.', 'limited', 'https://www.roadsideamerica.com/tip/68124', null, 'America/New_York', now()),
  ('Walterboro Water Tower — Former Jail', 'walterboro-water-tower-former-jail', 'roadside-oddities', 32.90235, -80.6623, 'Walterboro', 'SC', 'This historic water tower has several tiny jail cells built into its base, creating the unusual combination of municipal water infrastructure and lockup. Local stories also claim the cells were later used as emergency lodging for stranded travelers, although that part of the history is less certain.', 'roadside', 'https://www.scpictureproject.org/colleton-county/walterboro-water-tower.html', null, 'America/New_York', now()),
  ('Cemetery Island — Ghost Island', 'cemetery-island-ghost-island', 'weird-history', 34.59182, -82.85603, 'Townville', 'SC', 'When Lake Hartwell was created, a hill containing the Harris family cemetery remained above the rising water and became an island. Dozens of graves now sit isolated by the lake, and local stories have added ghost legends to the already eerie setting. The island is most practically reached by boat or kayak.', 'limited', 'https://www.atlasobscura.com/places/cemetery-island', null, 'America/New_York', now()),
  ('Stede Bonnet Hanging Site', 'stede-bonnet-hanging-site', 'weird-history', 32.77003, -79.92978, 'Charleston', 'SC', 'A small monument marks the area where the “Gentleman Pirate” Stede Bonnet and members of his crew were executed in 1718. Bonnet’s strange career—from wealthy plantation owner to inept pirate associate of Blackbeard—makes the quiet waterfront location unusually rich in pirate history.', 'open', 'https://www.atlasobscura.com/places/pirate-hanging-site-monument', null, 'America/New_York', now()),
  ('Guignard Brick Works', 'guignard-brick-works', 'weird-history', 33.9883, -81.05023, 'Cayce', 'SC', 'Beehive kilns and industrial remains survive from a brickworks that once produced huge quantities of building material near the Congaree River. The preserved circular kilns look almost like small ruined fortifications and are visible from the Three Rivers Greenway area.', 'open', 'https://www.scpictureproject.org/lexington-county/guignard-brickworks.html', null, 'America/New_York', now()),
  ('Prince Frederick’s Chapel Ruins', 'prince-fredericks-chapel-ruins', 'weird-history', 33.5056, -79.1803, 'Plantersville', 'SC', 'Only the Gothic Revival front wall and tower remain from a church begun just before the Civil War and completed years afterward. The main body was demolished in 1966 after becoming unsafe. The National Register property is privately owned, so visitors should view it only where lawful and not assume public entry.', 'private', 'https://www.nationalregister.sc.gov/georgetown/S10817722008/index.htm', null, 'America/New_York', now()),
  ('Mt. Atlanticus Minotaur Goff', 'mt-atlanticus-minotaur-goff', 'roadside-oddities', 33.69337, -78.88364, 'Myrtle Beach', 'SC', 'A giant minotaur-like figure named Goff presides over the wildly themed Mt. Atlanticus miniature golf complex. Its mythological creatures, faux ruins, towers, and rooftop course turn a beach-town mini-golf stop into a deliberately surreal environment.', 'open', 'https://www.atlasobscura.com/places/mt-atlanticus-minotaur-goff', null, 'America/New_York', now()),
  ('The Gay Dolphin', 'the-gay-dolphin', 'roadside-oddities', 33.69324, -78.8783, 'Myrtle Beach', 'SC', 'Opened in 1946, this enormous oceanfront souvenir store is a maze of rooms crammed with seashells, odd gifts, statues, toys, pirate merchandise, fossils, and beach kitsch. Its sprawling inventory and decades-old atmosphere make shopping here feel like exploring a commercial cabinet of curiosities.', 'open', 'https://www.atlasobscura.com/places/the-gay-dolphin', 'https://www.gaydolphin.com/', 'America/New_York', now()),
  ('Venus Flytraps at Lewis Ocean Bay Heritage Preserve', 'venus-flytraps-at-lewis-ocean-bay-heritage-preserve', 'roadside-oddities', 33.80624, -78.88964, 'Conway', 'SC', 'Wild Venus flytraps grow naturally in this protected landscape near Myrtle Beach, within the plant’s remarkably small native range in the Carolinas. Visitors must stay on legitimate access routes and never remove or disturb the carnivorous plants.', 'limited', 'https://www.dnr.sc.gov/mlands/managedland?p_id=105', null, 'America/New_York', now()),
  ('Apollo Moonprints in Cement', 'apollo-moonprints-in-cement', 'weird-history', 33.70645, -78.87417, 'Myrtle Beach', 'SC', 'Concrete slabs preserve boot impressions made by Apollo astronauts during appearances connected with Myrtle Beach’s former convention-hall Walk of Fame. They turn something as ordinary as footprints in wet cement into a strange relic of the Moon-landing era.', 'limited', 'https://www.atlasobscura.com/places/apollo-moonprints-in-cement', null, 'America/New_York', now()),
  ('Mice on Main Street', 'mice-on-main-street', 'roadside-oddities', 34.85202, -82.39998, 'Greenville', 'SC', 'Nine tiny bronze mice are hidden along several blocks of downtown Greenville’s Main Street. The sculptures were inspired by the children’s book Goodnight Moon and create a miniature scavenger hunt that rewards travelers for paying attention to curbs, planters, and storefronts.', 'open', 'https://www.atlasobscura.com/places/mice-on-main-street', null, 'America/New_York', now()),
  ('South Carolina Cotton Museum — Lizard Man Exhibit', 'south-carolina-cotton-museum-lizard-man-exhibit', 'cryptids', 34.2205, -80.24694, 'Bishopville', 'SC', 'The museum’s lobby preserves the story of the Lizard Man of Scape Ore Swamp, the reptilian creature whose alleged 1988 encounters turned Bishopville into a cryptid destination. The current exhibit covers the original sightings and ensuing “Lizardmania,” making this the most concrete public stop for South Carolina’s signature cryptid.', 'open', 'https://sccotton.org/notable-mentions', 'https://www.sccotton.org/', 'America/New_York', now()),
  ('Tomb of Julia Legare', 'tomb-of-julia-legare', 'folklore', 32.57996, -80.30819, 'Edisto Island', 'SC', 'A brick mausoleum at the ruins of the old Presbyterian church is tied to the legend of Julia Legare, who was supposedly mistakenly declared dead and buried alive. Folklore says the tomb’s heavy door repeatedly opened or was moved despite attempts to secure it. The buried-alive story is legend rather than established fact, but the unusual tomb is real.', 'open', 'https://www.scpictureproject.org/charleston-county/tomb-of-julia-legare.html', null, 'America/New_York', now()),
  ('1938 Police Station Archway', '1938-police-station-archway', 'roadside-oddities', 33.56005, -81.7209, 'Aiken', 'SC', 'A decorative archway in downtown Aiken survives from a tiny police station built as a New Deal-era project in 1938. The station itself is gone, but the entrance structure remains tucked into the pedestrian lanes around The Alley like a doorway to a vanished building.', 'open', 'https://www.roadsideamerica.com/tip/66815', null, 'America/New_York', now()),
  ('Atomic Waste Container Art', 'atomic-waste-container-art', 'roadside-oddities', 33.55915, -81.7221, 'Aiken', 'SC', 'Aiken’s long relationship with the nearby Savannah River Site inspired this unusual piece of public art made to resemble a radioactive-waste shipping container. The sculpture turns one of the region’s most consequential industries into an unexpectedly playful downtown object.', 'open', 'https://www.roadsideamerica.com/tip/55488', null, 'America/New_York', now()),
  ('Alligator Adventure', 'alligator-adventure', 'roadside-oddities', 33.79974, -78.73738, 'North Myrtle Beach', 'SC', 'This reptile park at Barefoot Landing holds an enormous collection of alligators, crocodiles, snakes, lizards, and other unusual animals. Its residents have included exceptionally large crocodilians, making it a far stranger stop than a conventional small coastal zoo.', 'limited', 'https://alligatoradventure.com/', null, 'America/New_York', now()),
  ('Center for Birds of Prey', 'center-for-birds-of-prey', 'roadside-oddities', 32.91844, -79.70683, 'Awendaw', 'SC', 'Dozens of eagles, owls, hawks, falcons, vultures, and other raptors are housed at this avian conservation center outside Charleston. Scheduled programs include live flight demonstrations that bring large birds of prey surprisingly close to visitors.', 'limited', 'https://thecenterforbirdsofprey.org/center-for-birds-of-prey/', null, 'America/New_York', now()),
  ('Bush Bug', 'bush-bug', 'roadside-oddities', 33.29725, -81.0345, 'Bamberg', 'SC', 'A Volkswagen Beetle covered in artificial greenery has been transformed into a rolling-looking topiary known as the Bush Bug. The plant-covered car is one of those simple roadside objects that becomes considerably stranger the longer you look at it.', 'roadside', 'https://www.roadsideamerica.com/tip/52101', null, 'America/New_York', now()),
  ('Doc Blanchard Memorial', 'doc-blanchard-memorial', 'weird-history', 34.22018, -80.24617, 'Bishopville', 'SC', 'Bishopville honors Felix “Doc” Blanchard, the 1945 Heisman Trophy winner and West Point football star, with a downtown monument. Blanchard later became an Air Force pilot, giving the small town an unusually substantial memorial to a local sports legend.', 'open', 'https://www.scpictureproject.org/lee-county/doc-blanchard-memorial.html', null, 'America/New_York', now()),
  ('Bessie the Giant Cow', 'bessie-the-giant-cow', 'roadside-oddities', 32.78155, -79.98988, 'Charleston', 'SC', 'A huge fiberglass cow named Bessie has watched over the St. Andrews shopping area for decades. She once rotated atop a dairy store and held a giant milk bottle; current reports say she remains in place even though the rotating mechanism and bottle are gone.', 'roadside', 'https://www.roadsideamerica.com/tip/14236', null, 'America/New_York', now()),
  ('Poogan’s Grave', 'poogans-grave', 'weird-history', 32.77813, -79.93194, 'Charleston', 'SC', 'A small grave outside Poogan’s Porch honors the neighborhood dog for whom the restaurant was named. Poogan reportedly wandered from porch to porch before adopting the restaurant as his home, and staff and guests have since attached ghost stories to the beloved canine’s memory. Restaurant: https://www.poogansporch.com/', 'open', 'https://www.roadsideamerica.com/location/sc/all', null, 'America/New_York', now()),
  ('Dizzy Gillespie Birthplace Park', 'dizzy-gillespie-birthplace-park', 'weird-history', 34.6987, -79.8929, 'Cheraw', 'SC', 'A small park and historical marker occupy the area associated with the birthplace of jazz trumpeter Dizzy Gillespie. The site celebrates the musician famous for his bent trumpet, puffed cheeks, and enormous influence on bebop.', 'open', 'https://www.hmdb.org/m.asp?m=28273', null, 'America/New_York', now()),
  ('I Love You Hand Sculpture', 'i-love-you-hand-sculpture', 'roadside-oddities', 33.99862, -81.0374, 'Columbia', 'SC', 'A large metal hand forms the American Sign Language gesture for “I love you” near Columbia’s convention-center district. Its oversized scale makes the familiar hand sign into a quick, unmistakable downtown photo stop.', 'open', 'https://www.roadsideamerica.com/tip/67330', null, 'America/New_York', now()),
  ('10-Foot-High Robot Head', '10-foot-high-robot-head', 'roadside-oddities', 34.00043, -81.0163, 'Columbia', 'SC', 'A huge metal robot head rises beside Harden Street in Five Points, staring out over passing cars without a body attached. The deliberately oversized face looks like the remains of a buried machine or a prop from a forgotten science-fiction movie.', 'roadside', 'https://www.roadsideamerica.com/tip/85881', null, 'America/New_York', now()),
  ('Eddie — World’s Biggest Kid', 'eddie-worlds-biggest-kid', 'roadside-oddities', 33.99723, -81.04819, 'Columbia', 'SC', 'Inside EdVenture stands Eddie, a roughly 40-foot-tall child that visitors can actually climb through. His internal organs, bones, stomach, brain, and other body systems become tunnels and exhibits, essentially turning a giant human body into a playground. Museum: https://www.edventure.org/', 'limited', 'https://www.roadsideamerica.com/story/12960', null, 'America/New_York', now()),
  ('Martian Brick Head', 'martian-brick-head', 'roadside-oddities', 34.009, -81.021, 'Columbia', 'SC', 'A brick building sprouts an enormous three-dimensional face assembled directly into its masonry. The strange expression and exaggerated features make the head look as though a giant stone creature is pushing outward through the wall.', 'roadside', 'https://www.roadsideamerica.com/tip/63982', null, 'America/New_York', now()),
  ('Hootie & the Blowfish Monument', 'hootie-the-blowfish-monument', 'weird-history', 33.99846, -81.01598, 'Columbia', 'SC', 'A large stainless-steel monument in Five Points commemorates Hootie & the Blowfish, whose members met while attending the University of South Carolina. Lyrics, names, and references to the band are incorporated into a sculpture that is much larger than the average hometown music plaque.', 'open', 'https://www.atlasobscura.com/places/hootie-the-blowfish-monument-columbia', null, 'America/New_York', now()),
  ('POW / Hanoi Hilton Monument', 'pow-hanoi-hilton-monument', 'roadside-oddities', 33.99515, -81.01408, 'Columbia', 'SC', 'This unusually severe-looking monument incorporates a fragment associated with Hanoi’s infamous Hỏa Lò Prison, nicknamed the “Hanoi Hilton” by American prisoners of war. The memorial honors South Carolinians held captive during the Vietnam War.', 'open', 'https://www.roadsideamerica.com/tip/70839', null, 'America/New_York', now()),
  ('Smiley Face Water Tank', 'smiley-face-water-tank', 'roadside-oddities', 33.9431, -80.98965, 'Columbia', 'SC', 'A spherical blue water tank at Columbia’s wastewater facility wears a huge white line-art smile. Security fencing prevents close access, but the absurdly cheerful face remains visible from the public approach along Simon Tree Lane.', 'roadside', 'https://www.roadsideamerica.com/tip/9975', null, 'America/New_York', now()),
  ('George Washington Statue with a Broken Cane', 'george-washington-statue-with-a-broken-cane', 'weird-history', 34.00032, -81.03313, 'Columbia', 'SC', 'The George Washington statue at the South Carolina State House still bears damage from Union occupation of Columbia during the Civil War. Soldiers broke off part of Washington’s walking cane, and the damaged monument was deliberately left unrepaired as part of its history.', 'open', 'https://www.scstatehouse.gov/studentpage/Explore/grounds.shtml', null, 'America/New_York', now()),
  ('Travelers Chapel', 'travelers-chapel', 'roadside-oddities', 33.80261, -79.00689, 'Conway', 'SC', 'This miniature roadside church was built as a quiet place for travelers to stop, pray, or simply look inside. Only a handful of people can fit in the tiny sanctuary at once, making it look like a full-size church that has somehow been shrunk. Current status: https://www.roadsideamerica.com/location/sc/all', 'limited', 'https://www.atlasobscura.com/places/tavelers-chapel', null, 'America/New_York', now()),
  ('Bee City Zoo & Honey Bee Farm', 'bee-city-zoo-honey-bee-farm', 'roadside-oddities', 32.97455, -80.46585, 'Cottageville', 'SC', 'What began around honey-bee education has grown into an interactive rural zoo with lemurs, monkeys, giraffes, kangaroos, reptiles, farm animals, and other species. Feeding opportunities and safari-style rides make it more hands-on than a conventional roadside animal park.', 'limited', 'https://www.beecityzoo.com/contact', null, 'America/New_York', now()),
  ('Darlington Raceway Stock Car Museum', 'darlington-raceway-stock-car-museum', 'museums', 34.29732, -79.90515, 'Darlington', 'SC', 'Beside one of NASCAR’s oldest major tracks, this museum preserves historic race cars, trophies, memorabilia, engines, and artifacts from stock-car racing history. The collection makes a good OddWay stop even when no race is taking place.', 'limited', 'https://www.darlingtonraceway.com/museum/', null, 'America/New_York', now()),
  ('Big Turkey Statues', 'big-turkey-statues', 'roadside-oddities', 33.7895, -81.92985, 'Edgefield', 'SC', 'Edgefield celebrates its connection to the National Wild Turkey Federation with oversized fiberglass turkeys scattered around town. Several were decorated as public art, turning the community into an informal turkey-statue scavenger hunt.', 'open', 'https://www.roadsideamerica.com/tip/29075', null, 'America/New_York', now()),
  ('Dr. DeVore’s Trapdoor Grave', 'dr-devores-trapdoor-grave', 'weird-history', 33.7922, -81.9342, 'Edgefield', 'SC', 'The grave of Dr. William DeVore is associated with an unusual above-ground structure traditionally described as having a trapdoor or access hatch. Local stories offer competing explanations for the grave’s peculiar construction, helping turn a single burial into a longstanding Edgefield curiosity.', 'open', 'https://www.roadsideamerica.com/tip/46027', null, 'America/New_York', now()),
  ('Elloree Heritage Museum — Animatronic Mr. Snider and Stuffed Mule', 'elloree-heritage-museum-animatronic-mr-snider-and-stuffed-mule', 'museums', 33.5299, -80.5739, 'Elloree', 'SC', 'Elloree’s local-history museum contains an unexpectedly theatrical recreation of an old general store featuring an animatronic shopkeeper, Mr. Snider, along with a preserved mule and other artifacts. The moving figure gives the small-town museum a distinctly OddWay quality.', 'limited', 'https://www.elloreemuseum.org/', null, 'America/New_York', now()),
  ('Big Blue Teapot', 'big-blue-teapot', 'roadside-oddities', 33.52984, -80.57455, 'Elloree', 'SC', 'A building shaped like an enormous blue teapot once housed thousands of teapots collected by Julian and Sybil Boland. The museum closed in 2020, but the giant teapot remains; a June 2026 visitor report confirms it is still standing, although visibly deteriorated.', 'roadside', 'https://www.roadsideamerica.com/tip/33987', null, 'America/New_York', now()),
  ('Mars Bluff Atomic Bomb Fragments', 'mars-bluff-atomic-bomb-fragments', 'weird-history', 34.19592, -79.76643, 'Florence', 'SC', 'The Florence County Museum preserves fragments and objects connected with the 1958 Mars Bluff nuclear-bomb accident, when a weapon accidentally fell from a B-47 and its conventional explosives detonated near a family home. These artifacts complement the public marker included in South Carolina Part 1.', 'limited', 'https://www.flocomuseum.org/featured-objects/mars-bluff-bomb/', null, 'America/New_York', now()),
  ('Grave of Florena Budwin', 'grave-of-florena-budwin', 'weird-history', 34.18509, -79.75433, 'Florence', 'SC', 'Florena Budwin is traditionally identified as a woman who disguised herself as a man in order to accompany her husband into Confederate military service. Captured and imprisoned, she died in 1865 and is buried at Florence National Cemetery; elements of her story remain debated, but the grave has become a local historical curiosity. Cemetery: https://www.cem.va.gov/cems/nchp/florence.asp', 'open', 'https://www.roadsideamerica.com/tip/36204', null, 'America/New_York', now()),
  ('Baseball Water Tower', 'baseball-water-tower', 'roadside-oddities', 35.05409, -80.95757, 'Fort Mill', 'SC', 'Fort Mill’s water tower is painted to resemble an enormous baseball, complete with curved red stitching visible across the white tank. It turns ordinary municipal infrastructure into a giant sports object hanging over town.', 'roadside', 'https://fotospot.com/attractions/south-carolina/baseball-water-tower', null, 'America/New_York', now()),
  ('Peg Leg Bates Statue', 'peg-leg-bates-statue', 'weird-history', 34.69478, -82.20036, 'Fountain Inn', 'SC', 'A statue honors Clayton “Peg Leg” Bates, the Fountain Inn native who lost a leg in a cotton-gin accident and became a celebrated one-legged tap dancer. Bates later appeared repeatedly on national television and operated a major Black-owned resort in New York.', 'open', 'https://www.scpictureproject.org/greenville-county/peg-leg-bates.html', null, 'America/New_York', now()),
  ('Rudolf Anderson F-86 Sabre Memorial', 'rudolf-anderson-f-86-sabre-memorial', 'weird-history', 34.84623, -82.38762, 'Greenville', 'SC', 'A jet displayed in Cleveland Park honors Greenville native Rudolf Anderson Jr., the only American killed by enemy fire during the Cuban Missile Crisis. Anderson was shot down while flying a U-2 reconnaissance mission over Cuba in 1962.', 'open', 'https://www.roadsideamerica.com/tip/24858', null, 'America/New_York', now()),
  ('Shoeless Joe Jackson Museum', 'shoeless-joe-jackson-museum', 'museums', 34.84121, -82.40841, 'Greenville', 'SC', 'The former home of baseball legend “Shoeless” Joe Jackson was moved beside Fluor Field and transformed into a museum. Exhibits cover Jackson’s remarkable playing career and the enduring controversy surrounding the 1919 Black Sox scandal.', 'limited', 'https://www.shoelessjoejackson.org/', null, 'America/New_York', now()),
  ('Our Lady of Vietnam Park', 'our-lady-of-vietnam-park', 'roadside-oddities', 35.04504, -82.26243, 'Greer', 'SC', 'A striking Marian shrine created by South Carolina’s Vietnamese Catholic community includes a large statue of Our Lady of La Vang and landscaped devotional spaces. The elaborate monument looks unexpectedly transported from a major pilgrimage site into suburban Upstate South Carolina.', 'open', 'https://www.scpictureproject.org/greenville-county/our-lady-of-vietnam-park.html', null, 'America/New_York', now()),
  ('Francis Marion — Swamp Fox Statue', 'francis-marion-swamp-fox-statue', 'roadside-oddities', 33.81715, -79.4497, 'Johnsonville', 'SC', 'An unusual statue of Revolutionary War commander Francis Marion stands near Johnsonville, depicting the guerrilla leader remembered as the “Swamp Fox.” The figure’s stylized appearance makes the monument considerably stranger than the average military statue.', 'roadside', 'https://www.roadsideamerica.com/tip/38025', null, 'America/New_York', now()),
  ('Ronald E. McNair Memorial Park', 'ronald-e-mcnair-memorial-park', 'weird-history', 33.87067, -79.75157, 'Lake City', 'SC', 'Lake City honors hometown astronaut Ronald McNair, who died aboard Space Shuttle Challenger in 1986, with a dedicated memorial park. The site connects a small South Carolina community directly to one of the defining tragedies of the American space program.', 'open', 'https://www.scpictureproject.org/florence-county/ronald-mcnair-memorial-park.html', null, 'America/New_York', now()),
  ('Campbell’s Covered Bridge', 'campbells-covered-bridge', 'roadside-oddities', 35.08583, -82.26417, 'Landrum', 'SC', 'Built in 1909, Campbell’s Covered Bridge is the only surviving historic covered bridge in South Carolina. Its bright red wooden enclosure spans Beaverdam Creek beside old mill remnants and walking trails.', 'open', 'https://greenvillerec.com/parks/campbells-covered-bridge/', null, 'America/New_York', now()),
  ('Early Cotton Press', 'early-cotton-press', 'roadside-oddities', 34.33811, -79.52364, 'Latta', 'SC', 'A massive wooden screw press survives as a rare example of the machinery once used to compress cotton into transportable bales. Its oversized timbers and primitive mechanical design make the structure look almost like a wooden siege engine.', 'open', 'https://www.scpictureproject.org/dillon-county/early-cotton-press.html', null, 'America/New_York', now()),
  ('Michael and Alex Smith Memorial at John D. Long Lake', 'michael-and-alex-smith-memorial-at-john-d-long-lake', 'weird-history', 34.775, -81.511, 'Union', 'SC', 'A memorial near John D. Long Lake remembers Michael and Alex Smith, the two young boys killed by their mother Susan Smith in 1994 after she rolled her car into the lake with them strapped inside. The location became the center of an internationally covered murder case and should be treated respectfully. Lake access: https://www.dnr.sc.gov/lakes/state/johndlong/index.html', 'open', 'https://www.roadsideamerica.com/tip/67321', null, 'America/New_York', now()),
  ('Vintage Car on Top of a Laundromat', 'vintage-car-on-top-of-a-laundromat', 'roadside-oddities', 34.22685, -80.70115, 'Lugoff', 'SC', 'An old automobile sits on the roof of a laundromat at the former Boykin Studebaker building. The car was restored to the roof after local residents missed the landmark when it was temporarily removed, preserving an eccentric piece of the building’s automotive past.', 'roadside', 'https://www.roadsideamerica.com/tip/30265', null, 'America/New_York', now()),
  ('Amelia Bedelia Statue', 'amelia-bedelia-statue', 'roadside-oddities', 33.69963, -80.21083, 'Manning', 'SC', 'A bronze statue honors the famously literal-minded children’s-book character Amelia Bedelia and her creator, Peggy Parish, who was born in Manning. The sculpture turns misunderstandings like “dust the furniture” and “dress the chicken” into a permanent piece of hometown literary history.', 'open', 'https://www.scpictureproject.org/clarendon-county/amelia-bedelia-statue.html', null, 'America/New_York', now()),
  ('Mepkin Abbey Tree Carvings', 'mepkin-abbey-tree-carvings', 'roadside-oddities', 33.11534, -79.94447, 'Moncks Corner', 'SC', 'The grounds of this Trappist monastery contain large sculptural figures carved directly from dead or damaged trees. Faces, religious imagery, and other forms emerge from trunks around the property, adding an unexpected folk-art layer to the quiet abbey landscape. Oddity listing: https://www.roadsideamerica.com/location/sc/all', 'limited', 'https://mepkinabbey.org/', null, 'America/New_York', now()),
  ('The Big Mo Drive-In', 'the-big-mo-drive-in', 'roadside-oddities', 33.85247, -81.59898, 'Monetta', 'SC', 'Originally opened in 1951, this rural drive-in theater was revived after years of closure and now operates multiple screens. A giant peach structure houses projection equipment and concessions, giving the already nostalgic theater an unmistakably South Carolina roadside centerpiece.', 'limited', 'https://thebigmo.com/', null, 'America/New_York', now()),
  ('USS Yorktown', 'uss-yorktown', 'roadside-oddities', 32.7919, -79.90943, 'Mount Pleasant', 'SC', 'The enormous Essex-class aircraft carrier USS Yorktown is permanently docked at Patriots Point and open for exploration. Visitors can walk through crew spaces, hangar areas, the flight deck, and exhibits filled with historic aircraft.', 'limited', 'https://www.patriotspoint.org/exhibits/uss-yorktown/', null, 'America/New_York', now()),
  ('Vietnam Experience at Patriots Point', 'vietnam-experience-at-patriots-point', 'roadside-oddities', 32.78956, -79.9056, 'Mount Pleasant', 'SC', 'Patriots Point recreates a Vietnam-era brown-water Navy support base and Marine artillery position with bunkers, helicopters, vehicles, equipment, and immersive environments. The land-based exhibit can easily be overlooked by visitors focused only on the nearby ships.', 'limited', 'https://www.patriotspoint.org/exhibits/vietnam-experience/', null, 'America/New_York', now()),
  ('Cold War Submarine Memorial', 'cold-war-submarine-memorial', 'weird-history', 32.79408, -79.90427, 'Mount Pleasant', 'SC', 'A memorial near Patriots Point commemorates Cold War submarine crews and features the sail and rudder of the nuclear-powered attack submarine USS Lewis and Clark. The preserved submarine pieces rise from the landscape like parts of a vessel still submerged underground.', 'open', 'https://www.hmdb.org/m.asp?m=19581', null, 'America/New_York', now()),
  ('Warbird Park', 'warbird-park', 'roadside-oddities', 33.66086, -78.92828, 'Myrtle Beach', 'SC', 'Several retired military aircraft are displayed outdoors near the former Myrtle Beach Air Force Base. Interpretive markers connect the jets to the crews and units that operated from the site during the Cold War and later conflicts.', 'open', 'https://www.cityofmyrtlebeach.com/departments/parks_recreation_sports_tourism/parks/warbird_park.php', null, 'America/New_York', now()),
  ('WonderWorks Upside-Down Building', 'wonderworks-upside-down-building', 'roadside-oddities', 33.71686, -78.88433, 'Myrtle Beach', 'SC', 'WonderWorks looks as though a giant laboratory was ripped from the ground, flipped upside down, and dropped onto Broadway at the Beach. The inverted facade leads into an interactive science-and-amusement attraction filled with optical illusions and hands-on exhibits.', 'limited', 'https://www.wonderworksonline.com/myrtle-beach/location-info/', null, 'America/New_York', now()),
  ('Chaser the Border Collie Statue', 'chaser-the-border-collie-statue', 'roadside-oddities', 34.9495, -81.93296, 'Spartanburg', 'SC', 'A bronze statue honors Chaser, the Border Collie who learned the names of more than 1,000 toys during groundbreaking canine-cognition research. Her work with psychologist John Pilley made her one of the most scientifically famous dogs in the world.', 'open', 'https://www.roadsideamerica.com/location/sc/all', null, 'America/New_York', now()),
  ('Edgar Allan Poe Library in a Military Bunker', 'edgar-allan-poe-library-in-a-military-bunker', 'roadside-oddities', 32.75965, -79.84058, 'Sullivan’s Island', 'SC', 'The island’s public library occupies part of Battery Gadsden, a former coastal-defense bunker, and is named for Edgar Allan Poe. Poe was stationed on Sullivan’s Island as a young soldier, and the setting later influenced stories including “The Gold-Bug.”', 'limited', 'https://sullivansisland.sc.gov/node/120', null, 'America/New_York', now()),
  ('Tuskegee Airmen Monument', 'tuskegee-airmen-monument', 'weird-history', 32.91635, -80.63761, 'Walterboro', 'SC', 'A memorial at the former Walterboro Army Airfield honors the Tuskegee Airmen who trained here during World War II. The site preserves the connection between this quiet Lowcountry airfield and the pioneering Black pilots whose service helped challenge segregation in the U.S. military.', 'open', 'https://www.scpictureproject.org/colleton-county/tuskegee-airmen-monument.html', null, 'America/New_York', now()),
  ('Greek Revival Folk Art Chicken Coop', 'greek-revival-folk-art-chicken-coop', 'roadside-oddities', 34.88295, -82.42159, 'Greenville', 'SC', 'Behind an antique shop and artist studios sits a chicken coop built to resemble a miniature Southern Greek Revival mansion. Look closely and the formal architecture turns into folk art: golf clubs, alphabet blocks, toy cars, seashells and other found objects are worked into the structure. Because the coop is in the back garden of an operating shop/studio property, visit only during business hours and respect any access restrictions.', 'limited', 'https://www.atlasobscura.com/places/greek-revival-folk-art-chicken-coop', null, 'America/New_York', now()),
  ('Mad Century Studios and the House of the Improbable', 'mad-century-studios-and-the-house-of-the-improbable', 'museums', 34.91043, -82.35939, 'Taylors', 'SC', 'This eccentric studio and folk-art environment mixes oddities, preserved specimens, found-object sculptures, fairy-garden spaces, interactive art and a collection that deliberately blurs the line between museum and backyard art project. Visitors have been encouraged to make or add art to the environment rather than simply look at it. It is run by local artists at a residential-scale property, so OddWay visitors should check ahead before arriving. Secondary source: https://www.scartshub.com/venues/mad-century-studios-and-the-house-of-the-improbable/', 'limited', 'https://www.atlasobscura.com/places/mad-century-studios-and-the-house-of-the-improbable-south-carolina', null, 'America/New_York', now()),
  ('Macaulay Museum of Dental History', 'macaulay-museum-of-dental-history', 'museums', 32.78673, -79.94735, 'Charleston', 'SC', 'MUSC''s dental-history museum contains historic tools, dental chairs, a nineteenth-century dental-office display and a traveling dentist''s chest from the Civil War era. Among its stranger artifacts is an instrument attributed to silversmith and Revolutionary War figure Paul Revere. The museum is accessed through the Waring Historical Library; appointments are strongly encouraged and required for larger groups.', 'limited', 'https://waring.library.musc.edu/exhibits/macaulay/index.php', 'https://waring.library.musc.edu/exhibits/macaulay/', 'America/New_York', now()),
  ('Museum of York County — Stans African Halls', 'museum-of-york-county-stans-african-halls', 'museums', 35.01014, -81.06237, 'Rock Hill', 'SC', 'The Museum of York County grew around the Stans African animal collection, a huge assemblage of full-mounted African specimens displayed in immersive dioramas. Its Naturalist Center now adds more than 2,000 specimens that visitors can study, while the larger museum also covers fossils, regional natural history and a planetarium. The dense taxidermy halls give this otherwise conventional science museum a distinctly old-school cabinet-of-natural-history feel. Secondary source: https://chmuseums.org/collections/', 'limited', 'https://chmuseums.org/myco/', 'https://chmuseums.org/myco/', 'America/New_York', now()),
  ('Mepkin Abbey Oak-Wood Sculptures', 'mepkin-abbey-oak-wood-sculptures', 'roadside-oddities', 33.11596, -79.95091, 'Moncks Corner', 'SC', 'The public grounds of this working Trappist monastery contain a series of unusual oak-wood sculptures incorporated into the abbey landscape. Mepkin''s own visitor map identifies the sculptures as a point of interest alongside its gardens, cemeteries, labyrinth and historic sites. The coordinates route to the Reception Center parking area; visitors should obtain a map there and respect all areas marked for monastic or limited access.', 'limited', 'https://www.mepkinapp.org/virtual-tour/', 'https://mepkinabbey.org/day-visits/', 'America/New_York', now()),
  ('Old Saluda Factory Ruins', 'old-saluda-factory-ruins', 'weird-history', 34.01058, -81.08136, 'West Columbia', 'SC', 'Blue-granite foundations and old waterworks survive along the Saluda River from one of the South''s early textile mills, begun in 1834. The site later became Camp Sorghum, where roughly 1,300 Union prisoners were held during the Civil War; the factory was burned in 1865, rebuilt, and destroyed by another fire in 1884. The ruins are visible along the River Trail at Riverbanks Zoo and Botanical Garden, so access follows the surrounding attraction and trail rules.', 'limited', 'https://www.scpictureproject.org/lexington-county/old-saluda-factory.html', null, 'America/New_York', now()),
  ('Old Lebanon Church Ruins', 'old-lebanon-church-ruins', 'weird-history', 34.38974, -81.17967, 'Winnsboro', 'SC', 'Isolated along Old Airport Road are the stone remains of the original Lebanon Presbyterian Church, a congregation organized in 1774. The surviving stone sanctuary was erected around 1780 and served for more than a century before being judged unsafe and abandoned when the congregation moved in 1893. An old graveyard surrounds the ruins; treat the site as a historic cemetery and obey any fencing or posted restrictions.', 'limited', 'https://www.scpictureproject.org/fairfield-county/old-lebanon-church.html', null, 'America/New_York', now()),
  ('Black Creek Baptist Church Ruins', 'black-creek-baptist-church-ruins', 'weird-history', 34.38642, -79.90811, 'Dovesville', 'SC', 'Three enormous brick columns stand in Black Creek Cemetery as the surviving pieces of a Greek Revival church destroyed by an accidental fire on Easter Sunday in 1922. Four columns originally survived, but one later fell after vandalism connected to rumors that a time capsule had been sealed inside. The active cemetery predates the ruins and should be visited respectfully during lawful access hours.', 'limited', 'https://www.scpictureproject.org/darlington-county/black-creek-baptist-church-ruins.html', null, 'America/New_York', now()),
  ('Lonnie Holloway''s Pontiac Grave — Rock Hill Baptist Church Cemetery', 'lonnie-holloways-pontiac-grave-rock-hill-baptist-church-cemetery', 'weird-history', 33.99269, -81.75749, 'Saluda', 'SC', 'When Lonnie Holloway died at age 90 in 2009, his unusual burial instructions were carried out: he was placed in the driver''s seat of his green 1973 Pontiac Catalina and the entire car was buried with him. His gun collection was reportedly placed on the passenger seat because he did not want the firearms to fall into the wrong hands. The car itself is underground, so this is a cemetery-history stop rather than a visible-car attraction.', 'limited', 'https://www.roadsideamerica.com/story/76517', null, 'America/New_York', now()),
  ('Four Holes Swamp Bridge Historic Site', 'four-holes-swamp-bridge-historic-site', 'weird-history', 33.14267, -80.35209, 'Dorchester', 'SC', 'A tiny park squeezed into the junction of U.S. 78 and 178 marks a surprisingly layered piece of South Carolina history. A causeway crossed Four Holes Swamp here by 1753, a bridge followed in the 1770s, and Patriot and Loyalist forces fought around the crossing during the Revolutionary War. Just beyond the memorial area is a small hilltop cemetery containing several Confederate veterans'' graves.', 'open', 'https://www.scpictureproject.org/dorchester-county/four-holes-swamp-bridge.html', null, 'America/New_York', now()),
  ('Crybaby Bridge — Old High Shoals Road Bridge', 'crybaby-bridge-old-high-shoals-road-bridge', 'haunted', 34.44718, -82.60219, 'Anderson', 'SC', 'An abandoned iron truss bridge sits beside the modern High Shoals Road crossing and has become one of South Carolina''s better-known "Crybaby Bridge" legend sites. Local stories describe a woman in white appearing on or near the old bridge while searching for someone, although the haunting is folklore rather than documented history. View the old structure only from safe, lawful public areas and do not climb onto the abandoned bridge. Coordinate check: https://maps.apple.com/place?place-id=ID331ABBFDABFF029', 'roadside', 'https://www.hauntedplaces.org/item/cry-baby-bridge-2/', null, 'America/New_York', now()),
  ('Jacksonboro Light', 'jacksonboro-light', 'folklore', 32.80321, -80.40098, 'Near Hollywood / Jacksonboro', 'SC', 'Lowcountry legend says a lantern-like light appears along Parkers Ferry Road, carried by the ghost of a preacher eternally searching for his missing daughter after he was killed by a train. Stories sometimes add the sound of a phantom train whistle to the moving light. This is a folklore route point only: remain on public roads, never enter railroad property and never stop where doing so would be unsafe or illegal.', 'roadside', 'https://www.hauntedplaces.org/item/jacksonboro-light/', null, 'America/New_York', now()),
  ('Huey Cooper Lucky Rabbit''s Foot Statue', 'huey-cooper-lucky-rabbits-foot-statue', 'folklore', 33.87287, -79.75429, 'Lake City', 'SC', 'A bronze statue preserves the memory of Huey Cooper, a beloved Lake City character remembered for sitting at the corner of Acline and Main and letting passersby rub his lucky rabbit''s foot for a nickel. Sculptor Alex Palkovich installed the figure in 2014 at Cooper''s old corner. The statue still holds out the rabbit''s foot and even includes a slot in its pocket so visitors can continue the nickel tradition. Secondary source: https://saintteresacoe.org/tour/huey-cooper-statue/', 'open', 'https://www.visitlakecitysc.com/public-art/huey-cooper', null, 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;

select count(*) as south_carolina from public.stops where state = 'SC';
