-- Vermont, both batches.
--
-- Vermont held one stop before this, which made it among the last real gaps in
-- the northeast.
--
-- The Tallest Filing Cabinet is dropped: already in the index from the
-- OpenStreetMap scan, 26 metres away.
--
-- The two batches were also checked against each other rather than only
-- against the database, since nothing prevents the same place appearing in
-- both halves of the same state's research.
--
-- A note on sources. A large share of these cite Atlas Obscura or Roadside
-- America. Those are now credited by name without a link — the reader can see
-- exactly where a claim came from and go and check it, but OddWay does not
-- hand a competing guide the click. Where a place has its own site or a state
-- historic sites page, that is used instead and does link.
--
-- Vermont has no timezone complications: the whole state is America/New_York.
--
-- 99 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Ben & Jerry''s Flavor Graveyard', 'ben-jerrys-flavor-graveyard', 'roadside-oddities', 44.35292, -72.74019, 'Waterbury', 'VT', 'Behind Ben & Jerry''s Waterbury factory, faux headstones memorialize discontinued ice-cream flavors with names, dates and rhyming epitaphs. The hillside cemetery turns failed and retired products into one of Vermont''s most recognizable corporate oddities.', 'limited', 'https://www.atlasobscura.com/places/ben-jerrys-flavor-graveyard', null, 'America/New_York', now()),
  ('Dog Chapel', 'dog-chapel', 'roadside-oddities', 44.43553, -71.98185, 'St. Johnsbury', 'VT', 'Artist Stephen Huneck created this small hilltop chapel as a place for people to remember dogs they have lost. Its walls are covered with thousands of handwritten memorial notes, while dog-themed carvings and sculptures fill the surrounding grounds.', 'open', 'https://www.atlasobscura.com/places/dog-chapel', null, 'America/New_York', now()),
  ('Bread and Puppet Museum and Theater', 'bread-and-puppet-museum-and-theater', 'museums', 44.68416, -72.17799, 'Glover', 'VT', 'Bread and Puppet Theater preserves decades of enormous masks, political puppets and handmade performance figures inside a converted barn. The collection is dense, theatrical and intentionally rough-edged, with seasonal performances continuing on the surrounding farm.', 'limited', 'https://www.atlasobscura.com/places/bread-and-puppet-museum-and-theater', null, 'America/New_York', now()),
  ('Museum of Everyday Life', 'museum-of-everyday-life', 'museums', 44.6409, -72.20582, 'Glover', 'VT', 'This self-service museum gives ordinary objects the kind of attention normally reserved for fine art or major historical artifacts. Rotating exhibits have examined everything from pencils and matches to locks, toothbrushes and other objects people usually overlook.', 'open', 'https://www.atlasobscura.com/places/museum-of-everyday-life', null, 'America/New_York', now()),
  ('Hope Cemetery', 'hope-cemetery', 'weird-history', 44.21072, -72.49942, 'Barre', 'VT', 'Barre''s granite industry turned this cemetery into an outdoor gallery of unusually elaborate gravestones carved by local stoneworkers. Memorials include life-size figures, airplanes, soccer balls, race cars and other personalized sculptures cut from local granite.', 'open', 'https://www.atlasobscura.com/places/hope-cemetery', null, 'America/New_York', now()),
  ('Bellows Falls Petroglyphs', 'bellows-falls-petroglyphs', 'weird-history', 43.13528, -72.44028, 'Bellows Falls', 'VT', 'Humanlike faces were carved into rock beside the Connecticut River long before modern Bellows Falls developed around the site. Their exact age and meaning remain uncertain, and travelers should view the protected carvings only from safe, permitted public areas rather than climbing onto the riverbank rocks.', 'limited', 'https://www.atlasobscura.com/places/bellows-falls-petroglyphs', null, 'America/New_York', now()),
  ('Floating Bridge of Brookfield', 'floating-bridge-of-brookfield', 'roadside-oddities', 44.04263, -72.60478, 'Brookfield', 'VT', 'A bridge has floated across Sunset Lake at this location in several different forms since the nineteenth century because the deep lakebed made conventional supports difficult. The present structure preserves the unusual floating-crossing tradition while serving as a distinctive village landmark.', 'open', 'https://www.atlasobscura.com/places/floating-bridge-brookfield-vt', null, 'America/New_York', now()),
  ('Wilson Castle', 'wilson-castle', 'haunted', 43.61218, -73.02763, 'Proctor', 'VT', 'This sprawling nineteenth-century mansion mixes Scottish, Romanesque, Dutch and Queen Anne architectural elements into an improbable Vermont castle. Seasonal tours explore its stained glass, antiques and eccentric rooms, while dedicated paranormal tours draw on the property''s long-running ghost stories.', 'limited', 'https://www.atlasobscura.com/places/wilson-castle', null, 'America/New_York', now()),
  ('Fairbanks Museum and Planetarium', 'fairbanks-museum-and-planetarium', 'museums', 44.42005, -72.01985, 'St. Johnsbury', 'VT', 'Founded from Franklin Fairbanks''s Victorian natural-history collection, this museum still feels like an enormous old curiosity cabinet. Tens of thousands of specimens include taxidermy, birds, insects, ethnographic material and scientific objects displayed inside an equally distinctive nineteenth-century building.', 'open', 'https://www.atlasobscura.com/places/fairbanks-museum-and-planetarium', null, 'America/New_York', now()),
  ('Emily''s Bridge', 'emilys-bridge', 'haunted', 44.44023, -72.67998, 'Stowe', 'VT', 'The 1844 Gold Brook covered bridge is better known as Emily''s Bridge because of a local ghost story about a young woman who supposedly died there after being abandoned by her lover. Tales of scratches, voices and other activity are folklore rather than established history, but the bridge remains one of Vermont''s best-known haunted landmarks.', 'open', 'https://www.atlasobscura.com/places/emilys-bridge', null, 'America/New_York', now()),
  ('Burlington Earth Clock', 'burlington-earth-clock', 'roadside-oddities', 44.45311, -73.22957, 'Burlington', 'VT', 'A ring of large stones at Oakledge Park forms a modern megalithic calendar designed to mark solar and seasonal events. Visitors can stand among the stones and use their alignments to observe the sun in a setting that resembles a miniature Vermont Stonehenge.', 'open', 'https://www.atlasobscura.com/places/burlington-earth-clock', null, 'America/New_York', now()),
  ('Flying Monkey Sculptures', 'flying-monkey-sculptures', 'roadside-oddities', 44.47579, -73.21951, 'Burlington', 'VT', 'Winged monkey figures perch above Burlington''s former Union Station, a strange architectural reference to The Wizard of Oz. The sculptures are easily visible from public areas around the station and have become a small but unmistakable downtown oddity.', 'roadside', 'https://www.atlasobscura.com/places/flying-monkey-sculptures', null, 'America/New_York', now()),
  ('Miniature Castles of South Hero', 'miniature-castles-of-south-hero', 'roadside-oddities', 44.64532, -73.30235, 'South Hero', 'VT', 'A collection of small stone castles, towers and miniature architectural structures is scattered around South Hero. Many sit on or near private property, so they are best treated as a roadside viewing hunt rather than places to enter or explore closely.', 'private', 'https://www.atlasobscura.com/places/miniature-castles-of-south-hero', null, 'America/New_York', now()),
  ('Witch Windows of Craftsbury', 'witch-windows-of-craftsbury', 'folklore', 44.63672, -72.37261, 'Craftsbury', 'VT', 'Vermont is known for occasional windows installed diagonally beneath rooflines, commonly called witch windows. Folklore claims the crooked openings were meant to prevent witches from flying through them, though practical architectural explanations are far more likely; the pin represents a Craftsbury area where examples can be spotted from public roads.', 'roadside', 'https://www.atlasobscura.com/places/witch-windows', null, 'America/New_York', now()),
  ('Old Round Church', 'old-round-church', 'folklore', 44.39888, -72.99907, 'Richmond', 'VT', 'Built in the early nineteenth century, this rare many-sided meetinghouse looks almost circular from a distance. Local lore says its shape left the devil no corner in which to hide, adding a supernatural explanation to one of Vermont''s most unusual historic buildings.', 'limited', 'https://www.atlasobscura.com/places/old-round-church', null, 'America/New_York', now()),
  ('Haskell Free Library and Opera House', 'haskell-free-library-and-opera-house', 'weird-history', 45.00573, -72.09767, 'Derby Line', 'VT', 'The international boundary between the United States and Canada runs directly through this library and opera house, with a marked line crossing the interior. Border procedures changed in 2025 and a separate Canadian entrance opened in 2026, so visitors must use the proper entrance for the country from which they arrive and cannot treat the building as a border crossing.', 'limited', 'https://www.atlasobscura.com/places/haskell-free-library-and-opera-house', null, 'America/New_York', now()),
  ('Jennings Hall — Hill House Inspiration', 'jennings-hall-hill-house-inspiration', 'folklore', 42.92037, -73.23583, 'North Bennington', 'VT', 'This secluded stone mansion on the Bennington College campus is often identified as a possible visual inspiration for Shirley Jackson''s The Haunting of Hill House. The connection is literary lore rather than proven fact, but Jackson lived in North Bennington and the building''s isolated setting closely fits the association.', 'limited', 'https://www.atlasobscura.com/places/jennings-hall', null, 'America/New_York', now()),
  ('Stone Man of Bowman Family Crypt', 'stone-man-of-bowman-family-crypt', 'weird-history', 43.48574, -72.87974, 'Shrewsbury', 'VT', 'A life-size marble figure appears to creep eternally up the steps of the Bowman family mausoleum in a rural cemetery. The strange composition is part of an elaborate nineteenth-century family memorial and gives the crypt a far more theatrical appearance than the surrounding graves.', 'open', 'https://www.atlasobscura.com/places/stone-man-of-bowman-family-crypt', null, 'America/New_York', now()),
  ('Phineas Gage Memorial', 'phineas-gage-memorial', 'weird-history', 43.38215, -72.60939, 'Cavendish', 'VT', 'A marker commemorates the 1848 accident in which railroad foreman Phineas Gage survived an iron tamping rod passing through his skull. His survival and subsequent behavioral changes became one of the most famous cases in the history of neuroscience.', 'open', 'https://www.atlasobscura.com/places/phineas-gage-memorial', null, 'America/New_York', now()),
  ('Lake Champlain Monster Monument', 'lake-champlain-monster-monument', 'cryptids', 44.47347, -73.22155, 'Burlington', 'VT', 'A waterfront monument recognizes Champ, the long-necked creature said to inhabit Lake Champlain. Reports and legends surrounding Champ stretch back generations, making the lake monster one of the Northeast''s best-known cryptids even though no conclusive evidence has established its existence.', 'open', 'https://www.atlasobscura.com/places/lake-champlain-monster-monument', null, 'America/New_York', now()),
  ('Lincoln Square — The Lottery Inspiration', 'lincoln-square-the-lottery-inspiration', 'weird-history', 42.929, -73.24207, 'North Bennington', 'VT', 'This small village square is associated with Shirley Jackson''s years in North Bennington and is commonly identified as an inspiration for the setting of her disturbing short story The Lottery. Jackson lived nearby while writing the story, making the ordinary-looking square a useful literary-horror stop.', 'open', 'https://www.atlasobscura.com/places/lincoln-square-lottery', null, 'America/New_York', now()),
  ('Grave of Timothy Clark Smith', 'grave-of-timothy-clark-smith', 'weird-history', 44.11322, -73.16346, 'New Haven', 'VT', 'Doctor Timothy Clark Smith feared being buried alive, so his nineteenth-century grave was built with a window that allowed people above ground to look into the burial chamber. The unusual design survives in Evergreen Cemetery as a physical reminder of Victorian fears surrounding premature burial.', 'open', 'https://www.atlasobscura.com/places/grave-of-timothy-clark-smith', null, 'America/New_York', now()),
  ('Grave of Amum-Her-Khepesh-Ef', 'grave-of-amum-her-khepesh-ef', 'weird-history', 44.00654, -73.17805, 'Middlebury', 'VT', 'A Middlebury cemetery contains the burial place of an ancient Egyptian mummy once owned by Middlebury College. After deterioration made the remains unsuitable for continued display, the thousands-of-years-old individual was given a modern Vermont burial.', 'open', 'https://www.atlasobscura.com/places/grave-of-amum-her-khepesh-ef', null, 'America/New_York', now()),
  ('Dummerston Vine', 'dummerston-vine', 'folklore', 42.93529, -72.57698, 'Dummerston', 'VT', 'A nineteenth-century legend blamed the deaths of several members of the Spaulding family on a cursed vine creeping through their cemetery plot. The story likely grew from tuberculosis deaths, but the row of family graves in Dummerston Center Cemetery remains the physical location connected with the tale.', 'open', 'https://www.atlasobscura.com/places/dummerston-vine', null, 'America/New_York', now()),
  ('''Snowflake'' Bentley Exhibit', 'snowflake-bentley-exhibit', 'museums', 44.50468, -72.99952, 'Jericho', 'VT', 'Wilson Bentley became the first person to successfully photograph a single snow crystal in 1885 and went on to create thousands of images. The Old Red Mill preserves his equipment, photographs and story in the Vermont community where his fascination with snow began.', 'limited', 'https://www.atlasobscura.com/places/snowflake-bentley', null, 'America/New_York', now()),
  ('Five Elm Arches', 'five-elm-arches', 'roadside-oddities', 43.62362, -72.54845, 'Woodstock', 'VT', 'Artist Dan Ladd trained living elm trees into a sequence of architectural arches, using the trees themselves as a slowly changing sculptural material. Only part of the original work survives, but it remains visible at the Sculpturefest site in Woodstock.', 'limited', 'https://www.atlasobscura.com/places/five-elm-arches', null, 'America/New_York', now()),
  ('Fire Hydrant Jack', 'fire-hydrant-jack', 'roadside-oddities', 44.37951, -73.22762, 'Shelburne', 'VT', 'A giant version of the children''s toy jack has been welded together from numerous retired fire hydrants beside Route 7. Artist Chris Sharp created the growing sculpture partly as a tribute to firefighters, turning familiar pieces of street infrastructure into an oversized roadside object.', 'roadside', 'https://www.atlasobscura.com/places/fire-hydrant-jack', null, 'America/New_York', now()),
  ('''Reverence'' — Whale Tails', 'reverence-whale-tails', 'roadside-oddities', 44.4455, -73.14314, 'South Burlington', 'VT', 'Two enormous black-granite whale tails appear to dive into a grassy field beside Interstate 89. Jim Sardonis created the sculpture in 1989, and its marine subject has become particularly memorable in landlocked Vermont.', 'open', 'https://www.atlasobscura.com/places/whale-tails', null, 'America/New_York', now()),
  ('Cold Hollow Sculpture Park', 'cold-hollow-sculpture-park', 'roadside-oddities', 44.85986, -72.76238, 'Enosburg Falls', 'VT', 'More than 70 large-scale sculptures by David Stromeyer are spread across roughly 200 acres of fields and woods. The seasonal park lets visitors wander among massive steel forms in a landscape that functions as both sculpture garden and outdoor gallery.', 'limited', 'https://www.coldhollowsculpturepark.com/', null, 'America/New_York', now()),
  ('Vermontasaurus', 'vermontasaurus', 'roadside-oddities', 43.88636, -72.25079, 'Thetford', 'VT', 'This enormous dinosaur-like folk sculpture was assembled from scrap lumber near the Post Mills Airport. The roughly 122-foot-long creature became locally famous after a dispute over whether something this large counted as art or as a building requiring a permit.', 'limited', 'https://www.atlasobscura.com/places/vermontasaurus', null, 'America/New_York', now()),
  ('Smugglers'' Notch', 'smugglers-notch', 'weird-history', 44.52097, -72.77416, 'Stowe', 'VT', 'The narrow mountain pass is filled with enormous glacial boulders and a twisting road so tight that large vehicles cannot safely pass through. Its name comes from stories of nineteenth-century smuggling through the Green Mountains, and the road closes seasonally when snow makes the notch impassable.', 'limited', 'https://www.atlasobscura.com/places/smugglers-notch', null, 'America/New_York', now()),
  ('Joseph Smith Birthplace Memorial', 'joseph-smith-birthplace-memorial', 'weird-history', 43.82347, -72.47308, 'Royalton', 'VT', 'A tall polished-granite monument marks the Vermont birthplace of Joseph Smith, founder of the Latter Day Saint movement. The memorial rises dramatically from a wooded hillside near the site of the Smith family''s former home.', 'open', 'https://www.atlasobscura.com/places/joseph-smith-birthplace-memorial', null, 'America/New_York', now()),
  ('Main Street Museum', 'main-street-museum', 'museums', 43.64997, -72.31902, 'White River Junction', 'VT', 'This small museum operates more like a cabinet of curiosities than a conventional historical collection. Its eclectic holdings mix local artifacts, natural-history specimens, odd objects, ephemera and items whose significance comes largely from the stories attached to them.', 'limited', 'https://www.atlasobscura.com/places/main-street-museum', null, 'America/New_York', now()),
  ('Estey Organ Museum', 'estey-organ-museum', 'museums', 42.84738, -72.56655, 'Brattleboro', 'VT', 'Brattleboro once produced hundreds of thousands of reed and pipe organs under the Estey name. The museum occupies part of the old factory complex and preserves instruments, manufacturing history and machinery from a company whose organs were shipped around the world.', 'limited', 'https://www.atlasobscura.com/places/estey-organ-museum', null, 'America/New_York', now()),
  ('American Society of Dowsers Headquarters', 'american-society-of-dowsers-headquarters', 'folklore', 44.40934, -72.13748, 'Danville', 'VT', 'The American Society of Dowsers maintains its headquarters in Danville for practitioners of the centuries-old practice of using rods, pendulums and other methods to locate water or other hidden targets. The organization remains active in 2026, although the headquarters should be treated as a limited-access organizational stop rather than a walk-in museum.', 'limited', 'https://dowsers.org/', null, 'America/New_York', now()),
  ('Ricker Basin Ghost Settlement', 'ricker-basin-ghost-settlement', 'weird-history', 44.38984, -72.76728, 'Waterbury', 'VT', 'Forest trails in Little River State Park pass cellar holes, stone walls, cemeteries and other remains of settlements that once occupied the Ricker Basin. Flood-control projects and changing rural life eventually emptied the area, leaving a walkable archaeological landscape in the woods.', 'limited', 'https://www.atlasobscura.com/places/ricker-basin', null, 'America/New_York', now()),
  ('Greenbank''s Hollow', 'greenbanks-hollow', 'weird-history', 44.37726, -72.12217, 'Danville', 'VT', 'A once-busy mill village largely disappeared after a destructive nineteenth-century fire. Today interpretive signs, foundations and landscape remnants allow visitors to walk through the remains of a Vermont community that effectively vanished.', 'open', 'https://www.atlasobscura.com/places/greenbanks-hollow', null, 'America/New_York', now()),
  ('Retreat Tower', 'retreat-tower', 'haunted', 42.85755, -72.56599, 'Brattleboro', 'VT', 'Patients from the nearby Brattleboro Retreat built this stone observation tower in the nineteenth century as part of therapeutic outdoor work. The tower itself is no longer intended for climbing, but surrounding public trails reach the structure, which has accumulated grim local legends and ghost stories.', 'open', 'https://www.atlasobscura.com/places/retreat-tower', null, 'America/New_York', now()),
  ('Birds of Vermont Museum', 'birds-of-vermont-museum', 'museums', 44.35161, -73.00664, 'Huntington', 'VT', 'Hundreds of life-size wooden bird carvings fill this small museum, each painstakingly shaped and painted to represent species found in Vermont and beyond. The collection blurs the line between natural-history display and obsessive folk craftsmanship.', 'limited', 'https://birdsofvermont.org/', null, 'America/New_York', now()),
  ('Vermont''s Marble Mansions', 'vermonts-marble-mansions', 'roadside-oddities', 43.59395, -73.26772, 'Fair Haven', 'VT', 'Fair Haven''s marble industry left the town with several striking homes built or faced with the same stone that made the region famous. The unusual cluster gives ordinary residential architecture the appearance of small civic monuments; most buildings should be viewed from public streets.', 'roadside', 'https://www.atlasobscura.com/places/vermonts-marble-mansions', null, 'America/New_York', now()),
  ('Stellafane Observatory', 'stellafane-observatory', 'weird-history', 43.27677, -72.51657, 'Springfield', 'VT', 'Amateur telescope makers have gathered on Breezy Hill for the Stellafane Convention since the 1920s. The site preserves the clubhouse and observing traditions of one of America''s oldest organized communities devoted to building telescopes by hand, with access centered around scheduled events.', 'limited', 'https://stellafane.org/', null, 'America/New_York', now()),
  ('East Corinth — Beetlejuice Filming Location', 'east-corinth-beetlejuice-filming-location', 'weird-history', 44.06398, -72.22223, 'Corinth', 'VT', 'East Corinth stood in for the fictional Connecticut town of Winter River in Tim Burton''s 1988 film Beetlejuice. The village landscape and recognizable road views remain, but OddWay visitors should remember that most individual buildings are private homes rather than film attractions.', 'roadside', 'https://www.atlasobscura.com/places/east-corinth', null, 'America/New_York', now()),
  ('The Finger', 'the-finger', 'roadside-oddities', 44.64177, -73.01529, 'Westford', 'VT', 'Three enormous wooden middle fingers rise beside Route 128 as the product of a long-running local zoning dispute. The display sits on private property, but a roadside pull-off allows visitors to see the deliberately confrontational sculptures without entering the property.', 'roadside', 'https://www.atlasobscura.com/places/the-finger', null, 'America/New_York', now()),
  ('Grave of William French', 'grave-of-william-french', 'weird-history', 43.07158, -72.45524, 'Westminster', 'VT', 'William French was killed during the 1775 Westminster confrontation between local protesters and New York authorities. His unusually direct gravestone inscription condemns King George III and his supporters, and French''s death became part of the political chain of events preceding Vermont''s declaration of independence.', 'open', 'https://www.atlasobscura.com/places/william-french-grave-westminster-vermont', null, 'America/New_York', now()),
  ('Freedlyville Quarry', 'freedlyville-quarry', 'weird-history', 43.28726, -73.01682, 'Dorset', 'VT', 'An abandoned marble quarry cuts deep into the mountain near Dorset, leaving underground workings where winter ice formations can develop. The quarry is not a maintained tourist cave, so access conditions, land permissions and underground hazards should be checked before any visit.', 'limited', 'https://www.atlasobscura.com/places/freedlyville-quarry', null, 'America/New_York', now()),
  ('Shelburne Museum', 'shelburne-museum', 'museums', 44.37325, -73.23227, 'Shelburne', 'VT', 'Rather than fitting its collection into one building, Shelburne Museum spreads art, Americana and historic structures across a large campus. Its stranger holdings include an entire steamboat brought inland, a lighthouse, circus material, historic houses and other full-size structures collected as museum objects.', 'limited', 'https://shelburnemuseum.org/', null, 'America/New_York', now()),
  ('Manchester Vampire Marker', 'manchester-vampire-marker', 'folklore', 43.17706, -73.0505, 'Manchester Center', 'VT', 'A historical marker near Factory Point Cemetery records the story of Rachel Harris Burton, whose body was reportedly exhumed and burned around 1792 after townspeople feared she had become a vampire. The episode belongs to the documented New England vampire panic surrounding tuberculosis and other unexplained illness.', 'open', 'https://www.wgpfoundation.org/historic-markers/manchester-vampire/', null, 'America/New_York', now()),
  ('Nature Museum Feejee Mermaid', 'nature-museum-feejee-mermaid', 'museums', 43.17025, -72.61053, 'Grafton', 'VT', 'The Nature Museum keeps an old Feejee-mermaid-style specimen made from combined animal remains, part of the long tradition of sideshow creatures presented as impossible zoological discoveries. It is not always on regular display, so visitors interested specifically in the mermaid should contact the museum before traveling.', 'limited', 'https://www.atlasobscura.com/places/the-nature-museum-feejee-mermaid-grafton-vermont', null, 'America/New_York', now()),
  ('Wampahoofus Trail', 'wampahoofus-trail', 'cryptids', 44.50574, -72.84764, 'Underhill', 'VT', 'This rugged Mount Mansfield trail is named for the wampahoofus, a mythical Green Mountain creature said to have legs shorter on one side so it could circle steep hillsides. Reaching the trail requires a mountain hike from the Stevensville area, and mud, snow and ice can make access seasonal.', 'limited', 'https://www.atlasobscura.com/places/wampahoofus-trail', null, 'America/New_York', now()),
  ('Largest Zipper in America — Unzipping the Earth', 'largest-zipper-in-america-unzipping-the-earth', 'roadside-oddities', 44.1992, -72.5035, 'Barre', 'VT', 'Artist Chris Miller carved a 74-foot granite zipper into the ground along North Main Street, making it look as though the city itself is being unzipped. The piece, titled Unzipping the Earth, turns Barre''s signature stone into an oversized piece of public art.', 'open', 'https://www.roadsideamerica.com/tip/40682', null, 'America/New_York', now()),
  ('The Whispering Statue — Youth Triumphant', 'the-whispering-statue-youth-triumphant', 'roadside-oddities', 44.19716, -72.50146, 'Barre', 'VT', 'This 1924 war memorial includes a curved granite bench with an acoustic trick: a whisper at one end can be heard clearly at the other. The effect makes the solemn monument double as one of Barre''s strangest interactive landmarks.', 'open', 'https://www.waymarking.com/waymarks/wmC9VB_The_Whispering_Statue_Youth_Triumphant_Barre_Vermont', null, 'America/New_York', now()),
  ('Vermont Granite Museum', 'vermont-granite-museum', 'museums', 44.2117, -72.52115, 'Barre', 'VT', 'Housed in a former granite manufacturing shed, this museum explains how Barre stone was quarried, carved and shipped around the country. Tools, machinery and stoneworking displays make it a useful companion stop to the city''s unusual granite monuments and cemeteries.', 'limited', 'https://www.vtgranitemuseum.org/', null, 'America/New_York', now()),
  ('Rock of Ages Granite Quarry', 'rock-of-ages-granite-quarry', 'weird-history', 44.15673, -72.49142, 'Graniteville', 'VT', 'Rock of Ages operates one of the world''s largest deep-hole dimension-granite quarries, where sheer gray walls descend hundreds of feet into water. Seasonal tours overlook the active quarry, and the visitor center even includes an outdoor granite bowling lane.', 'limited', 'https://www.atlasobscura.com/places/rock-of-ages-granite-quarry', null, 'America/New_York', now()),
  ('The American Spirit Lincoln Statue', 'the-american-spirit-lincoln-statue', 'roadside-oddities', 42.88335, -73.20945, 'Bennington', 'VT', 'A monumental Abraham Lincoln stands outside the Bennington Museum in an unusually theatrical composition that also includes a small nude figure. Clyde du Vernet Hunt''s sculpture, known as The American Spirit, has become locally famous for Lincoln''s distinctive hat and imposing pose.', 'limited', 'https://www.roadsideamerica.com/story/32720', null, 'America/New_York', now()),
  ('Bennington Battle Monument', 'bennington-battle-monument', 'weird-history', 42.88922, -73.21562, 'Bennington', 'VT', 'The 306-foot obelisk is the tallest structure in Vermont and commemorates the 1777 Battle of Bennington. One of the odd historical details is that the battle carrying Bennington''s name was actually fought several miles away across the present-day New York state line.', 'limited', 'https://historicsites.vermont.gov/bennington-battle-monument', null, 'America/New_York', now()),
  ('Bennington Centre Cemetery', 'bennington-centre-cemetery', 'weird-history', 42.88348, -73.21272, 'Bennington', 'VT', 'One of Vermont''s oldest cemeteries contains the graves of Revolutionary War soldiers, political figures and poet Robert Frost. Signs also identify the work of early local stone carvers, turning the burial ground into an outdoor archive of changing gravestone styles.', 'open', 'https://www.atlasobscura.com/places/bennington-centre-cemetery', null, 'America/New_York', now()),
  ('Lord''s Prayer Rock', 'lords-prayer-rock', 'roadside-oddities', 44.1295, -73.06956, 'Bristol', 'VT', 'A large roadside boulder bears the Lord''s Prayer carved directly into its face. The labor-intensive inscription has made the rock a long-standing local landmark along the road outside Bristol.', 'roadside', 'https://www.roadsideamerica.com/story/9784', null, 'America/New_York', now()),
  ('Dry Land Dock and Boat', 'dry-land-dock-and-boat', 'roadside-oddities', 44.03436, -72.599, 'Brookfield', 'VT', 'A full-size boat sits permanently ''docked'' on dry land in a deliberately nautical roadside display. The joke works especially well in rural Vermont, where the vessel looks spectacularly out of place away from any navigable water.', 'roadside', 'https://www.roadsideamerica.com/tip/22092', null, 'America/New_York', now()),
  ('Ben & Jerry''s First Store Plaque', 'ben-jerrys-first-store-plaque', 'weird-history', 44.47694, -73.21417, 'Burlington', 'VT', 'A plaque marks the downtown location where Ben Cohen and Jerry Greenfield opened their first ice-cream shop in a renovated gas station in 1978. The original building is gone, making the marker the physical reminder of where the Vermont brand began.', 'open', 'https://www.roadsideamerica.com/story/11912', null, 'America/New_York', now()),
  ('Stopping Stones Memorial', 'stopping-stones-memorial', 'weird-history', 44.47576, -73.21563, 'Burlington', 'VT', 'Small brass markers embedded in the sidewalk commemorate Lavinia Parker and her son Francis, who were enslaved in nineteenth-century Burlington. The memorial follows the concept of European stumbling stones, using an easily overlooked street-level marker to force attention toward a difficult local history.', 'open', 'https://www.atlasobscura.com/places/stopping-stone-marker-of-enslaved-vermonters', null, 'America/New_York', now()),
  ('Starlight Inn and Sunset Drive-In', 'starlight-inn-and-sunset-drive-in', 'roadside-oddities', 44.53813, -73.25171, 'Colchester', 'VT', 'This cinema-themed motel sits beside the seasonal Sunset Drive-In and leans fully into old-school movie culture. The combination of themed rooms and a functioning outdoor theater makes it more than a standard roadside motel stop.', 'limited', 'https://starlightinnvt.com/', null, 'America/New_York', now()),
  ('Great Vermont Corn Maze', 'great-vermont-corn-maze', 'roadside-oddities', 44.49905, -72.09134, 'Danville', 'VT', 'Each season, this farm builds an enormous multi-acre corn maze intended to take visitors hours rather than minutes to solve. The attraction changes annually and has also featured smaller mazes and nighttime or blacklight experiences.', 'limited', 'https://www.vermontcornmaze.com/', null, 'America/New_York', now()),
  ('President Chester A. Arthur State Historic Site', 'president-chester-a-arthur-state-historic-site', 'weird-history', 44.81445, -72.9324, 'Fairfield', 'VT', 'The site preserves a reconstructed house long promoted as Chester A. Arthur''s birthplace even though later research showed that the exact birthplace remains disputed and the replica is not on the original house site. That historical uncertainty is now part of the interpretation.', 'limited', 'https://historicsites.vermont.gov/chester-arthur', null, 'America/New_York', now()),
  ('Fairlee Drive-In Theater and Motel', 'fairlee-drive-in-theater-and-motel', 'roadside-oddities', 43.9225, -72.12611, 'Fairlee', 'VT', 'Fairlee combines a classic seasonal drive-in theater with an adjacent motel, preserving a kind of roadside entertainment landscape that has disappeared from most of the country. Guests and visitors can still experience movies on the outdoor screen during the operating season.', 'limited', 'https://fairleedrivein.com/', null, 'America/New_York', now()),
  ('Giant Maple Syrup Jug at Dakin Farm', 'giant-maple-syrup-jug-at-dakin-farm', 'roadside-oddities', 44.24348, -73.2304, 'Ferrisburgh', 'VT', 'An oversized maple-syrup jug advertises Dakin Farm along Route 7, turning Vermont''s best-known food product into literal roadside architecture. It is a quick exterior photo stop attached to an active Vermont specialty-food business.', 'roadside', 'https://www.roadsideamerica.com/tip/39047', null, 'America/New_York', now()),
  ('Theodore Roosevelt''s ''McKinley Shot'' Marker', 'theodore-roosevelts-mckinley-shot-marker', 'weird-history', 44.84677, -73.36417, 'Isle La Motte', 'VT', 'A marker identifies the Fisk home where Vice President Theodore Roosevelt was visiting when word arrived that President William McKinley had been shot in 1901. Roosevelt soon left Vermont as the national crisis deepened, eventually becoming president after McKinley''s death.', 'open', 'https://oakcrestheritage.com/markers/vermont/grand-isle-county/theodore-roosevelt-s-visit-to-isle-la-motte', null, 'America/New_York', now()),
  ('Queen Connie', 'queen-connie', 'roadside-oddities', 43.88442, -73.10325, 'Leicester', 'VT', 'A roughly 19-foot concrete gorilla stands beside Route 7 while holding an old Volkswagen Beetle high above the ground. The absurd King Kong-inspired sculpture has become one of Vermont''s most recognizable roadside giants.', 'roadside', 'https://www.atlasobscura.com/places/queen-connie', null, 'America/New_York', now()),
  ('The Puking Pig', 'the-puking-pig', 'roadside-oddities', 44.53612, -72.01268, 'Lyndon Center', 'VT', 'A bronze pig fountain spits a stream of water from its mouth, giving the otherwise decorative animal its memorable local nickname. Dedicated in 1912, the sculpture is modeled on the famous Florentine Porcellino tradition.', 'open', 'https://www.roadsideamerica.com/tip/21367', null, 'America/New_York', now()),
  ('Anti-Gravity Monument', 'anti-gravity-monument', 'roadside-oddities', 44.01018, -73.17542, 'Middlebury', 'VT', 'A granite monument on the Middlebury College campus promotes the eccentric dream of defeating or controlling gravity. It was connected with Roger Babson''s Gravity Research Foundation, an organization that funded unconventional gravity research and placed similar monuments at colleges around the country.', 'open', 'https://middleburymagazine.com/essays/editors-note/the-gravity-of-it-all/', null, 'America/New_York', now()),
  ('Frisbee Dog Statue', 'frisbee-dog-statue', 'roadside-oddities', 44.00985, -73.17782, 'Middlebury', 'VT', 'A bronze dog catches a flying disc in a sculpture celebrating the Frisbee''s connection to Middlebury. The statue plays on the story that students helped popularize throwing pie tins and similar discs long before the modern plastic Frisbee became ubiquitous.', 'open', 'https://www.roadsideamerica.com/story/11914', null, 'America/New_York', now()),
  ('Henry Sheldon Museum of Vermont History', 'henry-sheldon-museum-of-vermont-history', 'museums', 44.01255, -73.16998, 'Middlebury', 'VT', 'Founded in 1882, this long-running local museum grew from Henry Sheldon''s intensely personal collecting habits. Its holdings mix documents, household objects, art and regional artifacts into the kind of broad nineteenth-century collection that predates today''s highly specialized museums.', 'limited', 'https://www.henrysheldonmuseum.org/', null, 'America/New_York', now()),
  ('Clothespin Grave Marker', 'clothespin-grave-marker', 'weird-history', 44.31501, -72.6593, 'Middlesex', 'VT', 'A roughly five-foot granite clothespin marks the grave of Jack Crowell, associated with Vermont''s once-significant wooden clothespin industry. The monument turns an ordinary household object into an unexpectedly literal piece of funerary art.', 'open', 'https://www.roadsideamerica.com/tip/10414', null, 'America/New_York', now()),
  ('Green Mount Cemetery', 'green-mount-cemetery', 'weird-history', 44.25703, -72.59742, 'Montpelier', 'VT', 'This hillside cemetery is packed with elaborate Victorian funerary art, including carved stairways, sculpted figures and the locally notorious Hubbard memorial. Ghost and curse stories have attached themselves to some of the monuments, but the carvings themselves are the documented attraction.', 'open', 'https://www.atlasobscura.com/places/green-mount-cemetery', null, 'America/New_York', now()),
  ('Hubbard Tower', 'hubbard-tower', 'roadside-oddities', 44.26539, -72.57808, 'Montpelier', 'VT', 'A five-story stone observation tower rises above Montpelier from Hubbard Park after a construction process that stretched across many years. The rough stone structure looks much older than its twentieth-century completion date and can be reached by park trails.', 'open', 'https://www.roadsideamerica.com/tip/48334', null, 'America/New_York', now()),
  ('Space Shuttle Challenger Memorial', 'space-shuttle-challenger-memorial', 'weird-history', 44.25644, -72.59164, 'Montpelier', 'VT', 'A small granite monument memorializes the seven astronauts killed in the 1986 Challenger disaster despite Vermont having little direct connection to the shuttle program. The understated memorial has survived relocation and remains an unexpectedly space-themed landmark in the state capital.', 'open', 'https://www.atlasobscura.com/places/challenger-memorial-park', null, 'America/New_York', now()),
  ('Park-McCullough Children''s Play House', 'park-mccullough-childrens-play-house', 'roadside-oddities', 42.92848, -73.24658, 'North Bennington', 'VT', 'On the grounds of the Park-McCullough Historic Governor''s Mansion is an elaborate child-sized Victorian playhouse built with far more architectural ambition than an ordinary backyard toy. Access follows the historic estate''s public schedule and rules.', 'limited', 'https://www.roadsideamerica.com/tip/27710', null, 'America/New_York', now()),
  ('Experimental Balloon and Airship Museum', 'experimental-balloon-and-airship-museum', 'museums', 43.88372, -72.25208, 'Post Mills', 'VT', 'The late balloonist and inventor Brian Boland assembled an eccentric collection of experimental balloons, airships, machinery and aviation debris at Post Mills Airport. Public access is limited, but the surviving collection remains a remarkable monument to homemade flight and mechanical experimentation.', 'limited', 'https://www.roadsideamerica.com/story/70883', null, 'America/New_York', now()),
  ('Santa''s Land USA', 'santas-land-usa', 'roadside-oddities', 43.01038, -72.46962, 'Putney', 'VT', 'Opened in 1957, Santa''s Land is a classic Christmas-themed roadside park filled with vintage storybook buildings, figures and holiday attractions. The property has gone through multiple closures and revivals, so visitors should verify the current 2026 operating schedule before making it a dedicated stop.', 'limited', 'https://www.santaslandusa.com/', null, 'America/New_York', now()),
  ('Whale Dance', 'whale-dance', 'roadside-oddities', 43.94253, -72.62638, 'Randolph', 'VT', 'Two enormous bronze whale tails rise from the landscape in Jim Sardonis''s Whale Dance. The sculpture echoes the artist''s better-known granite whale tails near Burlington while creating another deliberately oceanic landmark in landlocked Vermont.', 'open', 'https://www.roadsideamerica.com/tip/66176', null, 'America/New_York', now()),
  ('Aldis Hill Wolf Monument', 'aldis-hill-wolf-monument', 'weird-history', 44.81549, -73.06676, 'St. Albans', 'VT', 'A heavy stone monument marks the place where Lawrence Brainerd reportedly killed an exceptionally large gray wolf in 1839. The monument was restored and reinstalled near the trail in recent years, preserving a strange local episode of human-wildlife history.', 'open', 'https://www.atlasobscura.com/places/aldis-hill-wolf-monument', null, 'America/New_York', now()),
  ('St. Albans Raid Marker', 'st-albans-raid-marker', 'weird-history', 44.81137, -73.08328, 'St. Albans', 'VT', 'A historical marker recalls the 1864 St. Albans Raid, when Confederate operatives crossed from Canada and robbed local banks before fleeing north. The attack is remembered as the northernmost major land action associated with the American Civil War.', 'open', 'https://oakcrestheritage.com/markers/vermont/franklin-county/st-albans-raid', null, 'America/New_York', now()),
  ('Royal Swans of Swanton', 'royal-swans-of-swanton', 'roadside-oddities', 44.91848, -73.12498, 'Swanton', 'VT', 'Swans have been kept in the village park since the early 1960s, when the community''s original pair arrived through an arrangement associated with Queen Elizabeth II. Today''s birds are successors rather than the original royal pair, but the unusual local tradition continues.', 'open', 'https://www.roadsideamerica.com/tip/48674', null, 'America/New_York', now()),
  ('Path of Life Sculpture Garden', 'path-of-life-sculpture-garden', 'roadside-oddities', 43.51296, -72.39999, 'Windsor', 'VT', 'Large outdoor sculptures are arranged along a riverside route to symbolize stages and experiences across a human lifetime. The walk includes conceptual pieces and landscape installations rather than a conventional formal sculpture garden.', 'open', 'https://www.greatriveroutfitters.com/path-of-life', null, 'America/New_York', now()),
  ('Sugarbush Farm Tiny Church', 'sugarbush-farm-tiny-church', 'roadside-oddities', 43.66508, -72.46732, 'Woodstock', 'VT', 'A tiny rustic chapel sits along the walking route at Sugarbush Farm, tucked among the woods and maple-sugaring landscape. The small structure adds an unexpected roadside miniature to a working Vermont farm that is open to visitors.', 'open', 'https://sugarbushfarm.com/hours-directions/', null, 'America/New_York', now()),
  ('American Precision Museum', 'american-precision-museum', 'museums', 43.47476, -72.38939, 'Windsor', 'VT', 'Inside a nineteenth-century armory, this museum preserves early machine tools and manufacturing technology tied to interchangeable parts and precision production. The dense collection of unusual industrial machinery makes it one of Vermont''s strongest mechanical-history stops.', 'limited', 'https://americanprecision.org/', null, 'America/New_York', now()),
  ('Goodsell Ridge Fossil Preserve', 'goodsell-ridge-fossil-preserve', 'weird-history', 44.85319, -73.33975, 'Isle La Motte', 'VT', 'Exposed limestone at this preserve contains remnants of the roughly 480-million-year-old Chazy fossil reef, one of the oldest known reef ecosystems. Trails and interpretive material let visitors literally walk across rock containing traces of an ancient tropical sea.', 'open', 'https://www.lclt.org/goodsell-and-fisk-quarry-preserves/', null, 'America/New_York', now()),
  ('Harvey''s Lake — Jacques Cousteau''s Early Dive Site', 'harveys-lake-jacques-cousteaus-early-dive-site', 'weird-history', 44.30387, -72.13894, 'Barnet', 'VT', 'Harvey''s Lake is locally associated with Jacques Cousteau''s childhood and is promoted as the place where the future ocean explorer had his first significant diving experience while attending summer camp. The unlikely inland Vermont connection makes the lake a peculiar landmark in diving history.', 'open', 'https://www.atlasobscura.com/places/harveys-lake-home-of-jacques-cousteaus-first-dive', null, 'America/New_York', now()),
  ('American Museum of Fly Fishing', 'american-museum-of-fly-fishing', 'museums', 43.168, -73.06713, 'Manchester', 'VT', 'This specialized museum preserves rods, reels, flies, art and archival material documenting the history of angling. Its intense focus on a single outdoor pastime makes it a strong niche museum stop rather than a general regional-history museum.', 'limited', 'https://amff.org/', null, 'America/New_York', now()),
  ('Vermont Ski and Snowboard Museum', 'vermont-ski-and-snowboard-museum', 'museums', 44.47528, -72.70222, 'Stowe', 'VT', 'Historic skis, snowboards, clothing, photographs and Hall of Fame material trace Vermont''s unusually important role in American snow sports. The museum documents both technological changes and the personalities who turned skiing into a defining part of the state''s identity.', 'limited', 'https://www.vtssm.org/', null, 'America/New_York', now()),
  ('Steampunk Locomotive Built of Junk', 'steampunk-locomotive-built-of-junk', 'roadside-oddities', 43.60576, -72.98174, 'Rutland', 'VT', 'A full-size locomotive-like sculpture assembled from scrap metal and discarded industrial parts stands near Rutland''s train station. Its deliberately mechanical, steampunk appearance makes the piece look like a fantasy engine built from the remains of real machinery.', 'open', 'https://www.roadsideamerica.com/tip/41233', null, 'America/New_York', now()),
  ('Grave of Mr. Barbo', 'grave-of-mr-barbo', 'weird-history', 43.16603, -73.11764, 'Manchester', 'VT', 'Near the summit of Equinox Mountain is the granite grave of Mr. Barbo, the beloved dog of industrialist Joseph George Davidson. The unusually elaborate canine memorial recounts how Barbo was killed by a hunter in 1955; reaching it requires seasonal access on Skyline Drive.', 'limited', 'https://www.atlasobscura.com/places/grave-of-mr-barbo', null, 'America/New_York', now()),
  ('Cooper''s Cabin', 'coopers-cabin', 'roadside-oddities', 43.63539, -72.87023, 'Mendon', 'VT', 'A rough stone-and-timber shelter sits high in the Killington backcountry along the Appalachian and Long Trail system. The primitive cabin is open to hikers but requires a real mountain approach rather than a roadside visit, so weather and trail conditions matter.', 'limited', 'https://www.atlasobscura.com/places/coopers-cabin', null, 'America/New_York', now()),
  ('Crown Point Bridge — What Lies Beneath Location', 'crown-point-bridge-what-lies-beneath-location', 'weird-history', 44.03612, -73.41892, 'Addison', 'VT', 'The Lake Champlain crossing at Crown Point played a prominent role in the 2000 supernatural film What Lies Beneath. The original bridge seen in the movie was demolished in 2009 and replaced, so today''s crossing is both a film-location stop and a reminder of a vanished landmark.', 'open', 'https://www.atlasobscura.com/places/crown-point-bridge', null, 'America/New_York', now()),
  ('The Leash Sculpture', 'the-leash-sculpture', 'roadside-oddities', 43.60644, -72.97962, 'Rutland', 'VT', 'Patrick Villiers Farrow''s bronze sculpture shows a dog straining against an invisible leash attached to an old-style parking meter. The surreal downtown piece has been a Rutland landmark since the 1980s and now stands in Depot Park.', 'open', 'https://siris-artinventories.si.edu/ipac20/ipac.jsp?uri=full%3D3100001~%21309420%210', null, 'America/New_York', now()),
  ('Frozen GI — Rutland County Vietnam Veterans Memorial', 'frozen-gi-rutland-county-vietnam-veterans-memorial', 'weird-history', 43.60524, -72.97209, 'Rutland', 'VT', 'A helmeted soldier appears half-embedded in a block of marble in this unusual Vietnam veterans memorial. The sculpture was begun by veteran John Reno and later completed by another veteran after Reno''s death, producing a memorial that looks almost like a figure frozen inside stone.', 'open', 'https://www.roadsideamerica.com/story/11616', null, 'America/New_York', now()),
  ('Clarendon Gorge Suspension Bridge', 'clarendon-gorge-suspension-bridge', 'roadside-oddities', 43.52123, -72.92547, 'Shrewsbury', 'VT', 'A narrow cable suspension footbridge carries the Appalachian and Long Trail high above the Mill River gorge. The bridge was rebuilt after a deadly 1973 flood and reopened after repairs in 2025; the surrounding cliffs remain hazardous and require normal hiking caution.', 'limited', 'https://www.atlasobscura.com/places/clarendon-gorge-bridge', null, 'America/New_York', now()),
  ('Cornish-Windsor Covered Bridge', 'cornish-windsor-covered-bridge', 'weird-history', 43.47368, -72.38395, 'Windsor', 'VT', 'Built in 1866, this 449-foot covered bridge crosses the Connecticut River between Windsor and Cornish, New Hampshire. It remains one of the longest surviving wooden covered bridges in the United States and still carries road traffic across the state line.', 'open', 'https://www.loc.gov/pictures/item/nh0177/', null, 'America/New_York', now()),
  ('Shelburne Farms', 'shelburne-farms', 'weird-history', 44.39547, -73.24712, 'Shelburne', 'VT', 'This enormous former Vanderbilt-Webb country estate was laid out with landscape work by Frederick Law Olmsted and includes monumental barns, an inn and more than a thousand acres along Lake Champlain. The scale and theatrical design make the property feel closer to a self-contained Gilded Age world than an ordinary Vermont farm.', 'limited', 'https://www.atlasobscura.com/places/shelburne-farms', null, 'America/New_York', now()),
  ('Giant Stick of Butter', 'giant-stick-of-butter', 'roadside-oddities', 44.14445, -72.8432, 'Warren', 'VT', 'An old shipping container at Cloud Water Farm has been painted into an enormous yellow stick of butter. Created as a playful celebration of food and farm culture, it became an instant Route 100 roadside photo stop.', 'roadside', 'https://www.roadsideamerica.com/tip/89492', null, 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;

select count(*) as vermont from public.stops where state = 'VT';
