-- Virginia, second batch.
--
-- Twenty-three dropped as duplicates of the first batch. That is a high
-- proportion, and worth recording why the check nearly missed two of them:
-- the Kiptopeke concrete fleet was 596 metres from its existing record and
-- Mount Trashmore 384 metres, both outside the 300 metre radius that has been
-- sufficient until now.
--
-- Large sites are the problem. A shipwreck fleet and a landfill park are big
-- enough that two people pinning them independently land half a kilometre
-- apart, which does not happen with a statue. The radius has to suit the
-- thing, and no single number does.
--
-- Kept despite being flagged: Hollensbury Spite House, 226 metres from
-- Gadsby's Tavern, and the Giant Cootie, 184 metres from American Celebration
-- on Parade. Both are genuinely separate objects standing near something else.
--
-- 27 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Blackbeard''s Severed Head Marker', 'blackbeards-severed-head-marker', 'weird-history', 37.01663, -76.34278, 'Hampton', 'VA', 'After Blackbeard was killed off North Carolina in 1718, his severed head was brought back to Virginia and displayed at the mouth of the Hampton River as a warning to other pirates. A modern historical marker at Blackbeard''s Point identifies the tradition and gives travelers a physical stop tied to one of the grimmest episodes in Virginia''s pirate history.', 'roadside', 'https://www.roadsideamerica.com/tip/70036', null, 'America/New_York', now()),
  ('Deep Throat Parking Garage Marker', 'deep-throat-parking-garage-marker', 'weird-history', 38.89601, -77.07308, 'Arlington', 'VA', 'During the Watergate investigation in 1972 and 1973, reporter Bob Woodward secretly met FBI official Mark Felt, later confirmed as "Deep Throat," in an underground garage in Rosslyn. A historical marker installed outside the complex in 2008 identifies the site; the garage remains an active parking facility, so OddWay visitors should use the exterior marker rather than wander through private parking levels.', 'roadside', 'https://www.atlasobscura.com/places/deep-throat-parking-garage', null, 'America/New_York', now()),
  ('Hollensbury Spite House', 'hollensbury-spite-house', 'weird-history', 38.80731, -77.04506, 'Alexandria', 'VA', 'John Hollensbury built this exceptionally narrow house in 1830 to fill an alley beside his home, reportedly after growing tired of people and wagons using the passage. The roughly seven-foot-wide residence still stands at 523 Queen Street, but it is a private home and should be viewed only from the public sidewalk.', 'private', 'https://www.atlasobscura.com/places/hollensbury-spite-house', null, 'America/New_York', now()),
  ('Dark Star Park', 'dark-star-park', 'roadside-oddities', 38.89375, -77.07176, 'Arlington', 'VA', 'Artist Nancy Holt designed Dark Star Park as Arlington''s first county-commissioned public artwork, and it was installed in 1984. Its concrete spheres, tunnels, poles and carefully placed shadows form a strange astronomical landscape, with a famous annual alignment occurring around 9:32 a.m. every August 1.', 'open', 'https://www.arlingtonva.us/Government/Departments/Parks-Recreation/Locations/Parks/Dark-Star-Park', null, 'America/New_York', now()),
  ('Shot Tower Historical State Park', 'shot-tower-historical-state-park', 'weird-history', 36.8838, -80.8529, 'Max Meadows', 'VA', 'This roughly 75-foot stone tower was built in the early 1800s to manufacture lead shot by dropping molten lead from the top so it formed into spheres while falling. The grounds are accessible as part of Virginia''s state park system, while entry into the tower itself is restricted to scheduled openings and programs.', 'limited', 'https://www.dcr.virginia.gov/state-parks/shot-tower', null, 'America/New_York', now()),
  ('Paulverizer — Cyborg Muffler Man', 'paulverizer-cyborg-muffler-man', 'roadside-oddities', 37.72855, -79.3581, 'Buena Vista', 'VA', 'Artist Mark Cline unveiled the 24-foot Paulverizer in 2013, transforming the familiar Muffler Man form into a giant science-fiction cyborg with a control pod and robotic details. It remains outside the Auto Recyclers property on Sycamore Avenue and can be appreciated as a roadside photo stop without interfering with the operating business.', 'roadside', 'https://www.roadsideamerica.com/story/40615', null, 'America/New_York', now()),
  ('Knights of the Golden Horseshoe Pyramid', 'knights-of-the-golden-horseshoe-pyramid', 'weird-history', 38.35781, -78.54741, 'Elkton', 'VA', 'A stone pyramid placed at Swift Run Gap in 1921 commemorates Governor Alexander Spotswood''s 1716 expedition across the Blue Ridge, later romanticized as the Knights of the Golden Horseshoe. The roadside monument preserves that colonial legend, although claims that the party "discovered" the region ignore Indigenous occupation and earlier European travel through the area.', 'roadside', 'https://www.atlasobscura.com/places/knights-of-the-golden-horseshoe-markers', null, 'America/New_York', now()),
  ('Oldest Metal Bridge in Virginia', 'oldest-metal-bridge-in-virginia', 'weird-history', 37.23912, -80.2249, 'Elliston', 'VA', 'Built in 1878, this metal truss bridge carried traffic until 1971 before being preserved at the northbound Ironto Safety Rest Area on Interstate 81. It has been restored as a pedestrian bridge, turning a highway rest stop into an unexpectedly good piece of surviving nineteenth-century transportation history.', 'open', 'https://www.roadsideamerica.com/tip/40448', null, 'America/New_York', now()),
  ('Brunswick Stew Origin Marker', 'brunswick-stew-origin-marker', 'weird-history', 36.98743, -77.96328, 'Blackstone', 'VA', 'Virginia tradition says camp cook Jimmy Matthews created an early Brunswick stew during an 1828 hunting trip in Brunswick County, originally using squirrel, butter, onions, bread and seasoning. A Virginia historical marker erected in 1997 preserves the claim, though competing origin stories exist elsewhere, making this a suitably odd food-history roadside stop.', 'roadside', 'https://www.hmdb.org/m.asp?m=107700', null, 'America/New_York', now()),
  ('Ghost Church at Polegreen', 'ghost-church-at-polegreen', 'weird-history', 37.6452, -77.32927, 'Mechanicsville', 'VA', 'Polegreen Church was destroyed by Confederate artillery in 1864 during the Civil War. In 2012, a stark white framework was erected on the footprint of the vanished meetinghouse, creating a skeletal "Ghost Church" that visitors can walk around during daylight hours.', 'open', 'https://www.roadsideamerica.com/tip/59428', 'https://historicpolegreen.org/', 'America/New_York', now()),
  ('Tombstone House', 'tombstone-house', 'weird-history', 37.20209, -77.42703, 'Petersburg', 'VA', 'Oswald Young built this house in 1934 using pieces of thousands of discarded government headstones that had once marked Union graves at nearby Poplar Grove National Cemetery. The strange stone residence still survives on Youngs Road, but it is private property and should be viewed only from the public roadway.', 'private', 'https://www.atlasobscura.com/places/the-tombstone-house', null, 'America/New_York', now()),
  ('Grave of Doctor Pepper', 'grave-of-doctor-pepper', 'weird-history', 36.89056, -81.28028, 'Rural Retreat', 'VA', 'Dr. Charles T. Pepper is buried in Mountain View Cemetery, and a long-running local story connects him to the naming of the Dr Pepper soft drink through pharmacist Wade Morrison. The exact origin of the beverage''s name remains disputed, but the grave gives travelers a physical stop for one of Virginia''s most persistent soda-history stories.', 'open', 'https://www.roadsideamerica.com/tip/9262', null, 'America/New_York', now()),
  ('Grand Kugel', 'grand-kugel', 'roadside-oddities', 37.56064, -77.46627, 'Richmond', 'VA', 'The Grand Kugel outside the Science Museum of Virginia is a roughly 29-ton granite globe that appears to float and rotate on an extremely thin layer of pressurized water. The current globe replaced an earlier damaged version, and visitors can still push the enormous stone sphere by hand when the fountain system is operating.', 'open', 'https://www.atlasobscura.com/places/the-grand-kugel-richmond-virginia', 'https://smv.org/', 'America/New_York', now()),
  ('Largest Shotgun Shell', 'largest-shotgun-shell', 'roadside-oddities', 37.68458, -77.45387, 'Ashland', 'VA', 'A roughly 30-foot-tall green shotgun shell stands outside Green Top as a giant tribute to the area''s hunting culture. Built by Hudson Sheet Metal, the oversized shell is positioned along the store property and works as a quick roadside photo stop during normal access to the commercial site.', 'roadside', 'https://www.roadsideamerica.com/tip/84714', 'https://www.greentophuntfish.com/', 'America/New_York', now()),
  ('Apple Basket Water Tower', 'apple-basket-water-tower', 'roadside-oddities', 38.7538, -78.6436, 'Mount Jackson', 'VA', 'Mount Jackson turned an otherwise ordinary municipal water tower into an enormous basket of apples as a tribute to the Shenandoah Valley''s apple-growing heritage. The painted tower has been a roadside landmark for decades and remains easily visible from Interstate 81 and nearby public roads.', 'roadside', 'https://www.roadsideamerica.com/tip/30023', null, 'America/New_York', now()),
  ('Hot Air Balloon Water Tower', 'hot-air-balloon-water-tower', 'roadside-oddities', 36.96459, -81.07928, 'Wytheville', 'VA', 'Wytheville''s municipal water tower has been painted to resemble a colorful hot-air balloon, turning a piece of utility infrastructure into a highway landmark. The balloon design has become a recognizable local oddity and is best treated as a drive-by or public-road photo stop rather than a site to approach directly.', 'roadside', 'https://fotospot.com/attractions/virginia/hot-air-balloon-water-tower', null, 'America/New_York', now()),
  ('Pest House Medical Museum', 'pest-house-medical-museum', 'museums', 37.4157, -79.15795, 'Lynchburg', 'VA', 'Lynchburg''s Pest House served as a quarantine facility for contagious patients and later became closely associated with Civil War-era medical history. The building was moved to Old City Cemetery in 1987 and now contains period medical displays that visitors can examine as part of the cemetery''s historic grounds.', 'open', 'https://www.atlasobscura.com/places/pest-house-medical-museum', 'https://gravegarden.org/', 'America/New_York', now()),
  ('Pocahontas Exhibition Coal Mine', 'pocahontas-exhibition-coal-mine', 'museums', 37.30725, -81.34627, 'Pocahontas', 'VA', 'Coal mining began at Pocahontas in the 1880s, helping launch the region''s industrial boom and feed the Norfolk and Western Railway. Part of the historic mine is now preserved as the Pocahontas Exhibition Mine, where seasonal tours take visitors underground to see mining equipment, coal seams and the working environment of early miners.', 'limited', 'https://www.atlasobscura.com/places/pocahontas-exhibition-coal-mine', 'https://www.pocahontasva.org/', 'America/New_York', now()),
  ('Edgar Cayce A.R.E. Headquarters', 'edgar-cayce-are-headquarters', 'weird-history', 36.8928, -75.98994, 'Virginia Beach', 'VA', 'Psychic Edgar Cayce and his supporters founded the Association for Research and Enlightenment in 1931 to preserve and study material from his thousands of claimed psychic readings. The Virginia Beach headquarters now includes a large metaphysical library, bookstore, meditation garden, historic hospital building and public programs on Cayce''s work.', 'open', 'https://edgarcayce.org/about-us/our-organization/', 'https://edgarcayce.org/', 'America/New_York', now()),
  ('Mr. Peanut Statue — Suffolk Visitor Center', 'mr-peanut-statue-suffolk-visitor-center', 'roadside-oddities', 36.73745, -76.58227, 'Suffolk', 'VA', 'Mr. Peanut''s familiar character traces back to a 1916 Planters logo contest won by a young Suffolk-area boy, linking the advertising icon directly to the city''s peanut history. A Mr. Peanut statue at the Suffolk Visitor Center gives travelers an easy public photo stop while the center interprets Suffolk''s broader agricultural story.', 'open', 'https://www.visitsuffolkva.com/itineraries/all-about-mr-peanut-itinerary/', 'https://www.visitsuffolkva.com/', 'America/New_York', now()),
  ('Misty of Chincoteague Statue', 'misty-of-chincoteague-statue', 'folklore', 37.93425, -75.37678, 'Chincoteague', 'VA', 'Marguerite Henry''s 1947 book Misty of Chincoteague turned the island''s pony culture and the real mare Misty into an enduring American children''s legend. A bronze Misty statue donated in 2006 stands along Main Street, giving visitors a physical stop connected to both the famous book and Chincoteague''s pony tradition.', 'open', 'https://www.hmdb.org/m.asp?m=181179', null, 'America/New_York', now()),
  ('Fighter Jet in Pennies', 'fighter-jet-in-pennies', 'roadside-oddities', 38.87275, -77.16028, 'Falls Church', 'VA', 'Artist Courtney Stevens Hengerer created "Pennies from Heaven" in 2008 by covering a miniature fiberglass F-14 jet with roughly 14,000 pennies as part of a public-art project. The sculpture was later moved to Falls Church and now sits in the open-air plaza between office buildings at Seven Corners.', 'open', 'https://www.roadsideamerica.com/tip/60805', null, 'America/New_York', now()),
  ('Roanoke Bunyan Muffler Man', 'roanoke-bunyan-muffler-man', 'roadside-oddities', 37.29893, -79.94041, 'Roanoke', 'VA', 'This roughly 25-foot fiberglass Paul Bunyan figure has served as a Williamson Road landmark for decades, with local accounts placing a giant figure at the site by the mid-twentieth century. The statue has been repeatedly repainted and still stands outside the auto-service property, where it is easily visible from the public road.', 'roadside', 'https://www.roadsideamerica.com/story/11784', null, 'America/New_York', now()),
  ('Big Leaping Bass', 'big-leaping-bass', 'roadside-oddities', 37.719, -77.4532, 'Ashland', 'VA', 'A fiberglass bass roughly 27 feet tall leaps from an equally oversized faux splash at the entrance to the Winding Brook development. The sculpture was installed as a commercial landmark in the early 2010s and remains visible from the surrounding public roads near Interstate 95.', 'roadside', 'https://www.roadsideamerica.com/tip/33429', null, 'America/New_York', now()),
  ('Assassin''s End — John Wilkes Booth Marker', 'assassins-end-john-wilkes-booth-marker', 'weird-history', 38.14009, -77.2286, 'Port Royal', 'VA', 'John Wilkes Booth was cornered at Richard Garrett''s farm and fatally shot on April 26, 1865, twelve days after assassinating Abraham Lincoln. The farm buildings are gone and the actual site lies in a posted highway median with no public access, so OddWay should route travelers only to the roadside "Assassin''s End" historical marker and pull-off.', 'roadside', 'https://www.atlasobscura.com/places/assassins-end', null, 'America/New_York', now()),
  ('Big High Heel at Craddock Terry', 'big-high-heel-at-craddock-terry', 'roadside-oddities', 37.4115, -79.1375, 'Lynchburg', 'VA', 'The Craddock Terry complex grew from Lynchburg''s shoe-manufacturing industry, which began here in the late nineteenth century and once produced thousands of pairs a day. A giant red high-heel sculpture with a built-in seat now stands outside the converted hotel, turning that industrial history into a deliberately oversized photo stop.', 'open', 'https://www.roadsideamerica.com/tip/58033', 'https://www.craddockterryhotel.com/', 'America/New_York', now()),
  ('Giant Cootie', 'giant-cootie', 'roadside-oddities', 38.71444, -78.66767, 'Shenandoah Caverns', 'VA', 'This enormous version of the classic Cootie toy began life as a parade float and was later retired to the Shenandoah Caverns complex. The colorful bug now sits outside near American Celebration on Parade, where it can be seen as a roadside curiosity even when the neighboring museum is closed.', 'roadside', 'https://www.roadsideamerica.com/tip/68787', null, 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;
