-- Virginia, first batch.
--
-- One dropped: the World's Largest Apple at Winchester is already in the index
-- from the OpenStreetMap scan, 7 metres away. Both checks agreed on it, which
-- is the pattern when a duplicate is real rather than two things standing close
-- together.
--
-- Virginia had six stops, four of them Lover's Leaps. This is the state it
-- actually is: the Bunny Man Bridge, a witch statue in Pungo, a Woodbooger
-- sanctuary in Norton, Stonewall Jackson's arm buried by itself, and his horse
-- stuffed and on display forty miles away.
--
-- Note the Civil War medical thread — two apothecary museums, a field hospital
-- museum, and the arm. Virginia's strange places are frequently its medical and
-- military history, preserved with an unusual literalness.
--
-- 49 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone, verified_at)
values
  ('Bunny Man Bridge', 'bunny-man-bridge', 'folklore', 38.78989, -77.36238, 'Clifton', 'VA', 'This narrow railroad overpass on Colchester Road became the center of Northern Virginia''s Bunny Man legend after reports of a man in a rabbit suit threatening people with an axe or hatchet circulated in 1970. The bridge remains an active public road, so view it while passing through or from a safe legal spot nearby and never stop inside the one-lane tunnel or trespass along the tracks.', 'roadside', 'https://www.fotospot.com/attractions/virginia/bunny-man-bridge', 'America/New_York', now()),
  ('Witch of Pungo Statue', 'witch-of-pungo-statue', 'folklore', 36.86612, -76.13182, 'Virginia Beach', 'VA', 'This bronze statue honors Grace Sherwood, the Virginia woman convicted of witchcraft after a 1706 ducking trial in what was then Princess Anne County. The monument depicts Sherwood with a raccoon and stands on publicly accessible grounds near Sentara Bayside Hospital, giving the famous Witch of Pungo story a specific modern stop.', 'open', 'https://www.roadsideamerica.com/tip/34645', 'America/New_York', now()),
  ('Fairy Stone State Park', 'fairy-stone-state-park', 'folklore', 36.78439, -80.09372, 'Stuart', 'VA', 'The park is famous for naturally occurring staurolite crystals shaped like crosses, which local legend says formed from the tears of fairies who learned of Christ''s crucifixion. Visitors can hike, camp and search designated areas for the distinctive stones while the state park interprets both the geology and folklore.', 'open', 'https://www.dcr.virginia.gov/state-parks/fairy-stone', 'America/New_York', now()),
  ('Lake Drummond and the Phantom Lovers', 'lake-drummond-and-the-phantom-lovers', 'folklore', 36.60283, -76.46974, 'Chesapeake', 'VA', 'Lake Drummond lies deep within the Great Dismal Swamp and has inspired generations of supernatural stories, most famously the Phantom Lovers tale of a young man searching the lake for his dead bride. Reaching the lake requires using refuge roads, trails or waterways rather than a normal roadside pull-off, and access can vary with refuge conditions.', 'limited', 'https://www.fws.gov/refuge/great-dismal-swamp', 'America/New_York', now()),
  ('Woodbooger Statue and Sanctuary', 'woodbooger-statue-and-sanctuary', 'cryptids', 36.91951, -82.62718, 'Norton', 'VA', 'After Animal Planet''s Finding Bigfoot filmed in Southwest Virginia, Norton embraced its local Bigfoot-like creature known as the Woodbooger and designated Flag Rock Recreation Area as a Woodbooger Sanctuary. A large creature statue now stands just beyond the parking area on the footpath toward Flag Rock Overlook.', 'open', 'https://www.nortonva.gov/455/Woodbooger-Sanctuary', 'America/New_York', now()),
  ('St. Albans Sanatorium', 'st-albans-sanatorium', 'haunted', 37.13972, -80.57806, 'Fairlawn', 'VA', 'The property began as a boys'' school before becoming St. Albans psychiatric hospital in 1916, and its long institutional history has made it one of Virginia''s best-known paranormal investigation sites. The building is private and entry is allowed only through authorized tours, haunted events or scheduled investigations; never enter outside an official event.', 'limited', 'https://stalbans-sanatorium.com/', 'America/New_York', now()),
  ('Major Graham Mansion', 'major-graham-mansion', 'haunted', 36.91532, -80.87226, 'Max Meadows', 'VA', 'This 19th-century Wythe County mansion has accumulated stories of apparitions, voices and other reported paranormal activity tied to generations of the Graham family and the property''s history. Access is event-based and has included history tours, seasonal haunted attractions and paranormal investigations, so verify an authorized date before traveling.', 'limited', 'http://majorgrahammansion.com/', 'America/New_York', now()),
  ('Exchange Hotel Civil War Medical Museum', 'exchange-hotel-civil-war-medical-museum', 'haunted', 38.13266, -78.18566, 'Gordonsville', 'VA', 'The Exchange Hotel became a receiving hospital during the Civil War and treated tens of thousands of sick and wounded soldiers before later serving other purposes. Today it operates as a museum with medical and wartime displays, while reported apparitions, voices and unexplained activity have made it a frequent paranormal destination.', 'open', 'https://www.theexchangehotelmuseum.org/', 'America/New_York', now()),
  ('Gadsby''s Tavern Museum', 'gadsbys-tavern-museum', 'haunted', 38.80561, -77.04364, 'Alexandria', 'VA', 'These historic tavern buildings hosted travelers, political figures and social events in early Alexandria and are now preserved as a city museum. The site is also bound to the Female Stranger mystery, whose unidentified young woman allegedly died here in 1816 and is said in local lore to still haunt the building.', 'open', 'https://www.alexandriava.gov/museums/location/visit-gadsbys-tavern-museum', 'America/New_York', now()),
  ('Grave of the Female Stranger', 'grave-of-the-female-stranger', 'folklore', 38.79985, -77.05652, 'Alexandria', 'VA', 'A white marble table tomb in St. Paul''s Cemetery marks the grave of an unidentified 23-year-old woman who died in Alexandria in 1816. Her true identity remains unknown and later legends have connected her to figures such as Theodosia Burr Alston; the grave is the third on the right after entering the St. Paul''s section and should be visited respectfully during cemetery hours.', 'open', 'https://www.alexandriava.gov/index.php/historic-alexandria/womens-history-in-alexandria', 'America/New_York', now()),
  ('Bacon''s Castle', 'bacons-castle', 'weird-history', 37.10905, -76.72231, 'Surry', 'VA', 'Built in 1665, this extraordinary brick house acquired its misleading name after followers of Nathaniel Bacon seized and fortified it during Bacon''s Rebellion in 1676. The historic house is open for scheduled tours during its operating season, while the grounds generally have broader daytime access.', 'limited', 'https://preservationvirginia.org/historic-sites/bacons-castle/', 'America/New_York', now()),
  ('Ferry Plantation House', 'ferry-plantation-house', 'haunted', 36.86194, -76.11806, 'Virginia Beach', 'VA', 'The current Federal-style house dates to about 1830 on a property whose history reaches back to a 17th-century ferry and an earlier courthouse site near the famous Grace Sherwood witch trial. It operates as a historic house museum on limited weekly tour hours and has also become well known locally for reported paranormal activity.', 'limited', 'https://www.visitvirginiabeach.com/listing/ferry-plantation-house/531/', 'America/New_York', now()),
  ('Historic Avenel', 'historic-avenel', 'haunted', 37.33792, -79.52444, 'Bedford', 'VA', 'Built around 1838, Avenel remained in only two families for nearly 150 years and is now preserved by the Avenel Foundation. The house has long-standing stories of a spectral woman known as the White Lady and other unexplained activity, but visits to the interior must be arranged through scheduled tours or events.', 'limited', 'https://www.historicavenel.com/', 'America/New_York', now()),
  ('Peyton Randolph House', 'peyton-randolph-house', 'haunted', 37.27242, -76.70001, 'Williamsburg', 'VA', 'This restored Colonial Williamsburg house was home to prominent revolutionary-era statesman Peyton Randolph and generations of enslaved and free residents. Its long and sometimes violent history has produced some of Colonial Williamsburg''s most persistent ghost stories, and interior access is through the living-history site''s ticketed schedule.', 'limited', 'https://www.colonialwilliamsburg.org/locations/peyton-randolph-house/', 'America/New_York', now()),
  ('Martha Washington Inn', 'martha-washington-inn', 'haunted', 36.7096, -81.97539, 'Abingdon', 'VA', 'Built as a private home in 1832, the building later became a women''s college, served as a Civil War hospital and opened as a hotel in 1935. Stories of a ghostly violinist, wounded soldiers and a riderless horse remain part of the inn''s lore, while the property continues to operate as a hotel, restaurant and spa.', 'open', 'https://themartha.com/abingdon-hotel-history/', 'America/New_York', now()),
  ('Swannanoa Palace', 'swannanoa-palace', 'roadside-oddities', 37.9614, -78.8542, 'Afton', 'VA', 'Built beginning in 1912 as a lavish marble estate for James and Sallie Dooley, Swannanoa resembles a European palace unexpectedly planted atop Virginia''s Blue Ridge. The property is privately owned and is not a normal daily attraction, but occasional scheduled tours and open-house dates have allowed public access; do not enter outside an advertised event.', 'limited', 'https://www.atlasobscura.com/places/swannanoa-palace', 'America/New_York', now()),
  ('Aquia Church', 'aquia-church', 'weird-history', 38.46463, -77.40303, 'Stafford', 'VA', 'The present Aquia Church was completed in 1757 after its nearly finished predecessor burned, and the building later survived use by Union soldiers as a stable, hospital and campsite during the Civil War. It remains an active Episcopal church with remarkably preserved colonial woodwork, and historical tours should be arranged with the church office rather than treated as unrestricted sightseeing.', 'limited', 'https://aquiachurch.org/about/history/', 'America/New_York', now()),
  ('Church Hill Tunnel Eastern Portal', 'church-hill-tunnel-eastern-portal', 'weird-history', 37.52719, -77.41489, 'Richmond', 'VA', 'The Church Hill railroad tunnel catastrophically collapsed on October 2, 1925 while crews were attempting to reopen it, entombing a locomotive and an uncertain number of workers underground. The tunnel was sealed and remains unsafe and inaccessible; only view the surviving portal area from legal public ground and never attempt to enter.', 'roadside', 'https://www.rva.gov/press-releases-and-announcements/news/city-commemorates-church-hill-tunnel-collapse', 'America/New_York', now()),
  ('W. W. Pool Mausoleum — Richmond Vampire Tomb', 'w-w-pool-mausoleum-richmond-vampire-tomb', 'folklore', 37.53755, -77.45412, 'Richmond', 'VA', 'The ornate mausoleum of bookkeeper W. W. Pool in Hollywood Cemetery became attached to Richmond''s vampire legend after the 1925 Church Hill Tunnel disaster. There is no evidence Pool was a vampire, but the tomb remains the physical focus of the story; visit only during cemetery hours and do not damage or enter the structure.', 'open', 'https://www.atlasobscura.com/places/hollywood-cemetery', 'America/New_York', now()),
  ('Edgar Allan Poe Museum', 'edgar-allan-poe-museum', 'museums', 37.53216, -77.42608, 'Richmond', 'VA', 'Richmond''s Poe Museum holds the world''s largest collection of Edgar Allan Poe manuscripts, letters, first editions, personal belongings and memorabilia. The museum opened in 1922 in Richmond''s oldest surviving residential building and includes the atmospheric Enchanted Garden inspired by Poe''s writing.', 'open', 'https://poemuseum.org/', 'America/New_York', now()),
  ('Cursed Self-Rocking Cradle', 'cursed-self-rocking-cradle', 'folklore', 37.41382, -79.14416, 'Lynchburg', 'VA', 'According to an 1839 Lynchburg legend, this mahogany cradle repeatedly rocked with no one touching it and would begin moving when a local minister challenged the unseen force to rock it. The actual cradle resurfaced through descendants of its original owners and was donated to the Lynchburg Museum in 2021, where visitors can now see the artifact behind the story.', 'open', 'https://lynchburgmuseum.org/2021-10-1-the-early-family-rocking-cradle/', 'America/New_York', now()),
  ('Stonewall Jackson''s Arm Grave', 'stonewall-jacksons-arm-grave', 'weird-history', 38.31803, -77.73239, 'Locust Grove', 'VA', 'After Stonewall Jackson was accidentally shot by Confederate troops at Chancellorsville in 1863, surgeons amputated his left arm and a chaplain buried it in the Lacy family cemetery at Ellwood Manor. Jackson himself died days later and was buried in Lexington, leaving this small marked arm grave as one of Virginia''s strangest Civil War burial sites; access follows National Park Service and Ellwood hours.', 'limited', 'https://www.nps.gov/places/000/stonewall-jackson-arm.htm', 'America/New_York', now()),
  ('Little Sorrel — Stonewall Jackson''s Stuffed Horse', 'little-sorrel-stonewall-jacksons-stuffed-horse', 'museums', 37.79006, -79.4358, 'Lexington', 'VA', 'Stonewall Jackson''s small sorrel horse survived the Civil War and lived for decades after the general''s death before being preserved by a taxidermist. Little Sorrel is now displayed at the VMI Museum, where visitors can see the actual mounted horse rather than a replica.', 'open', 'https://www.vmi.edu/museums-and-archives/vmi-museum/', 'America/New_York', now()),
  ('Cornwallis Cave', 'cornwallis-cave', 'folklore', 37.23503, -76.50513, 'Yorktown', 'VA', 'For generations, local tradition claimed British General Cornwallis used this riverside cave as his headquarters during the 1781 Siege of Yorktown. Historians have since rejected that story and identify the cave as a later ammunition-storage site, making the debunked legend itself part of the stop; the opening is gated and should not be entered.', 'open', 'https://www.nps.gov/york/learn/historyculture/cornwallis-cave.htm', 'America/New_York', now()),
  ('Dinosaur Land', 'dinosaur-land', 'roadside-oddities', 39.06003, -78.13997, 'White Post', 'VA', 'Opened in the early 1960s, Dinosaur Land is an old-school roadside attraction filled with more than 50 large prehistoric creature statues. Its deliberately dated dinosaurs, giant shark, octopus and other oversized beasts preserve the feel of mid-century American roadside tourism.', 'open', 'https://dinosaurlandva.com/', 'America/New_York', now()),
  ('Dinosaur Kingdom II', 'dinosaur-kingdom-ii', 'roadside-oddities', 37.64899, -79.52483, 'Natural Bridge', 'VA', 'Artist Mark Cline''s Dinosaur Kingdom II imagines an alternate Civil War in which Union soldiers discover dinosaurs and attempt to use them as weapons. The walk-through attraction is packed with life-size fiberglass dinosaurs, soldiers and absurd battle scenes and operates seasonally rather than year-round.', 'limited', 'https://www.dinosaurkingdomii.com/', 'America/New_York', now()),
  ('Great Stalacpipe Organ at Luray Caverns', 'great-stalacpipe-organ-at-luray-caverns', 'roadside-oddities', 38.66407, -78.48383, 'Luray', 'VA', 'The Great Stalacpipe Organ is a working musical instrument that uses rubber-tipped strikers to play carefully selected stalactites spread through Luray Caverns. Built in the 1950s, it turns the cave itself into the instrument and can be heard as part of the normal cavern tour.', 'open', 'https://luraycaverns.com/discover/caverns/', 'America/New_York', now()),
  ('American Celebration on Parade', 'american-celebration-on-parade', 'museums', 38.71551, -78.66929, 'Quicksburg', 'VA', 'A warehouse beside Shenandoah Caverns is packed with enormous retired parade floats from presidential inaugurations, Rose Parades and other major celebrations. Visitors walk among giant genies, animals, patriotic displays and repurposed float pieces on seasonal guided tours, generally from Memorial Day through Labor Day with selected additional dates.', 'limited', 'https://shenandoahcaverns.com/attractions/american-celebration-on-parade/', 'America/New_York', now()),
  ('Camera Heritage Museum', 'camera-heritage-museum', 'museums', 38.14964, -79.07276, 'Staunton', 'VA', 'This independent museum has assembled thousands of cameras spanning the history of photography, including espionage cameras disguised as everyday objects, early daguerreotype equipment and hundreds of Brownie models. The collection also includes historic photographs and material connected to figures such as John Wilkes Booth.', 'open', 'https://cameraheritagemuseum.org/', 'America/New_York', now()),
  ('World''s Oldest Edible Ham', 'worlds-oldest-edible-ham', 'museums', 36.98208, -76.63111, 'Smithfield', 'VA', 'A Smithfield ham cured in 1902 was forgotten in storage until meat magnate Pembroke Gwaltney Jr. turned it into a publicity object and carried it to events. The famously ancient ham is now displayed at the Isle of Wight County Museum alongside the museum''s equally odd World''s Oldest Peanut.', 'open', 'https://www.historicisleofwight.com/isle-of-wight-county-museum.html', 'America/New_York', now()),
  ('Stabler-Leadbeater Apothecary Museum', 'stabler-leadbeater-apothecary-museum', 'museums', 38.80472, -77.0425, 'Alexandria', 'VA', 'This remarkably preserved pharmacy operated from 1792 until 1933 and reopened almost immediately as a museum, leaving shelves, bottles, medical ingredients and equipment largely frozen in place. Visitors can see thousands of historical medical and commercial objects on scheduled museum tours.', 'limited', 'https://www.alexandriava.gov/museums/location/visit-stabler-leadbeater-apothecary-museum', 'America/New_York', now()),
  ('Hugh Mercer Apothecary Shop', 'hugh-mercer-apothecary-shop', 'museums', 38.30409, -77.45987, 'Fredericksburg', 'VA', 'This restored 18th-century apothecary interprets medicine from an era when treatments included bloodletting, leeches, lancets, snakeroot and other remedies that look alarming by modern standards. Costumed interpretation and demonstrations make the small museum much stranger than a conventional colonial house tour.', 'limited', 'https://washingtonheritagemuseums.org/hugh-mercer-apothecary-shop/', 'America/New_York', now()),
  ('Roanoke Pinball Museum', 'roanoke-pinball-museum', 'museums', 37.27156, -79.93956, 'Roanoke', 'VA', 'The Roanoke Pinball Museum preserves dozens of playable machines tracing pinball from early mechanical games through modern electronic tables. Admission is built around actually playing the collection rather than viewing it behind glass, making it an interactive history of arcade technology.', 'open', 'https://roanokepinball.org/', 'America/New_York', now()),
  ('Museum of the Middle Appalachians', 'museum-of-the-middle-appalachians', 'museums', 36.88002, -81.76386, 'Saltville', 'VA', 'Saltville''s museum tells an unusually broad story that stretches from Ice Age animals and archaeological finds to salt production, Civil War battles and the town''s chemical industry. Fossils and prehistoric remains from the region make it especially useful as an OddWay stop rather than a standard local-history museum.', 'open', 'https://www.museumofthemiddleappalachians.org/', 'America/New_York', now()),
  ('Simpson Funeral Museum', 'simpson-funeral-museum', 'museums', 36.82576, -79.39869, 'Chatham', 'VA', 'Tucked into a working funeral home, this small museum preserves antique caskets, embalming equipment, hearses, burial clothing and other artifacts from the funeral profession. Because it is attached to an active business rather than a conventional attraction, visitors should verify hours before making a special trip.', 'limited', 'https://www.roadsideamerica.com/tip/10262', 'America/New_York', now()),
  ('DEA Museum', 'dea-museum', 'museums', 38.86467, -77.05821, 'Arlington', 'VA', 'The Drug Enforcement Administration''s museum documents the history of illicit drugs, federal enforcement and major investigations through seized objects, undercover material and unusual artifacts. Admission is free, but the museum is inside a federal building and adult visitors must meet current government identification and security-screening requirements.', 'open', 'https://museum.dea.gov/visit', 'America/New_York', now()),
  ('Air Power Park', 'air-power-park', 'museums', 37.04272, -76.36602, 'Hampton', 'VA', 'This free city park displays aircraft, rockets, missiles and space hardware outdoors in a landscape tied closely to Hampton''s aerospace history. The outdoor collection is accessible daily during park hours, while the indoor museum adds exhibits on aviation and space exploration.', 'open', 'https://www.hampton.gov/4233/Air-Power-Park', 'America/New_York', now()),
  ('Kiptopeke Concrete Fleet', 'kiptopeke-concrete-fleet', 'weird-history', 37.16463, -75.97825, 'Kiptopeke', 'VA', 'Nine concrete cargo ships built during World War II were deliberately sunk off Kiptopeke in 1948 to form a protective breakwater for the former ferry terminal. Their decaying hulls still rise from Chesapeake Bay and can be viewed from Kiptopeke State Park, with kayaks offering a closer look when conditions permit.', 'open', 'https://www.dcr.virginia.gov/state-parks/kiptopeke', 'America/New_York', now()),
  ('Mount Trashmore', 'mount-trashmore', 'roadside-oddities', 36.83096, -76.12425, 'Virginia Beach', 'VA', 'Virginia Beach converted an abandoned landfill into this 165-acre public park beginning in the 1970s, covering compacted layers of trash with soil to form its signature artificial hills. What was once a dump is now a landscaped recreation area with trails, playgrounds, lakes and one of the most literal odd-place names in the state.', 'open', 'https://parks.virginiabeach.gov/outdoors/city-parks/mount-trashmore-park', 'America/New_York', now()),
  ('King Neptune Statue', 'king-neptune-statue', 'roadside-oddities', 36.85963, -75.9773, 'Virginia Beach', 'VA', 'A massive bronze King Neptune rises over the Virginia Beach Boardwalk at 31st Street, surrounded by sculpted sea creatures and holding an enormous trident. Installed in 2005, the roughly 12-ton monument has become one of the city''s defining roadside-scale photo stops.', 'open', 'https://www.visitvirginiabeach.com/listing/king-neptune-statue/1173/', 'America/New_York', now()),
  ('Roanoke Star', 'roanoke-star', 'roadside-oddities', 37.25083, -79.9325, 'Roanoke', 'VA', 'Built in 1949 as a temporary Christmas-season publicity stunt, the 88.5-foot neon star on Mill Mountain proved so popular that it became permanent. It remains the world''s largest freestanding illuminated man-made star and overlooks Roanoke from a public park and scenic viewpoint.', 'open', 'https://www.playroanoke.com/parks-facilities/mill-mountain-park/', 'America/New_York', now()),
  ('Big Walker Lookout', 'big-walker-lookout', 'roadside-oddities', 37.04567, -81.22843, 'Wytheville', 'VA', 'This privately operated mountain stop combines a country store with a 100-foot observation tower perched high on Big Walker Mountain. The attraction has been family-run for more than 75 years and hosts seasonal craftspeople and music; tower and store access follow business hours rather than being a 24-hour overlook.', 'limited', 'https://www.scenicbeauty-va.com/', 'America/New_York', now()),
  ('Bealeton''s Giant Roller Skate', 'bealetons-giant-roller-skate', 'roadside-oddities', 38.53652, -77.72916, 'Bealeton', 'VA', 'An enormous fiberglass roller skate has stood outside the former skating-rink property since the roller-disco era of the 1980s. The weathered oversized shoe remains visible from the public-facing commercial area and is best treated as a quick roadside photo stop.', 'roadside', 'https://www.fotospot.com/attractions/virginia/bealetons-giant-roller-skate', 'America/New_York', now()),
  ('Rotting President Heads', 'rotting-president-heads', 'roadside-oddities', 37.38258, -76.75431, 'Croaker', 'VA', 'Forty-two enormous presidential busts rescued from the failed Presidents Park now decay together in a field on private industrial property near Williamsburg. The heads cannot be seen through normal walk-in access and trespassing is prohibited; visits are allowed only during occasional pre-ticketed tours and photography events.', 'limited', 'https://www.roadsideamerica.com/tip/2502', 'America/New_York', now()),
  ('Foamhenge at Cox Farms', 'foamhenge-at-cox-farms', 'roadside-oddities', 38.88162, -77.4863, 'Centreville', 'VA', 'Artist Mark Cline built this full-size Stonehenge replica from giant Styrofoam blocks in 2004, and it later moved from Natural Bridge to Cox Farms. Foamhenge is on private property and is accessible only during designated Cox Farms seasons and hours, including Fall Festival and very limited shuttle access at other times.', 'limited', 'https://coxfarmsva.com/about/foamhenge/', 'America/New_York', now()),
  ('Humpback Covered Bridge', 'humpback-covered-bridge', 'weird-history', 37.80054, -80.04711, 'Covington', 'VA', 'Built in 1857, this wooden bridge arches noticeably higher at its center than at either end, giving it the humpback profile that makes it unique. It is Virginia''s oldest surviving covered bridge and now stands in a public wayside park where travelers can walk through it rather than drive across it.', 'open', 'https://www.loc.gov/pictures/item/va0239/', 'America/New_York', now()),
  ('Natural Tunnel State Park', 'natural-tunnel-state-park', 'roadside-oddities', 36.69698, -82.73858, 'Duffield', 'VA', 'A naturally carved limestone tunnel about 850 feet long and up to roughly 100 feet high forms the centerpiece of this Southwest Virginia state park, with an active railroad still passing through it. Visitors can hike or use the seasonal chairlift toward the gorge and observation areas, but the railroad tunnel itself is not a pedestrian passage.', 'open', 'https://www.dcr.virginia.gov/state-parks/natural-tunnel', 'America/New_York', now()),
  ('Doumar''s Original Waffle Cone Machine', 'doumars-original-waffle-cone-machine', 'weird-history', 36.86616, -76.28485, 'Norfolk', 'VA', 'Doumar''s still uses the original-style four-iron waffle machine associated with founder Abe Doumar, who helped popularize the rolled waffle ice-cream cone at the 1904 St. Louis World''s Fair. The century-old drive-in remains in business, and visitors can often watch cones being made on the historic machine while ordering from the restaurant.', 'open', 'https://www.atlasobscura.com/places/doumar-s-barbecue', 'America/New_York', now()),
  ('Blue Ridge Tunnel', 'blue-ridge-tunnel', 'weird-history', 38.03009, -78.85297, 'Afton', 'VA', 'Engineer Claudius Crozet''s 4,273-foot railroad tunnel opened in 1858 after nearly nine years of difficult construction through the Blue Ridge Mountains. The abandoned bore reopened as a pedestrian and bicycle trail in 2020, but it is completely dark inside and the walk to and through it requires a flashlight and appropriate trail access.', 'limited', 'https://www.nelsoncounty-va.gov/2020/11/20/claudius-crozet-blue-ridge-tunnel-open/', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  verified_at   = excluded.verified_at;
