-- West Virginia, first batch.
--
-- The state OddWay started with, and until now the thinnest relative to what
-- is actually there: nine stops, mostly Mothman.
--
-- No duplicates. Five coordinate flags, all genuinely separate things sitting
-- close together — the Bigfoot Museum shares Sutton's Main Street with the
-- Flatwoods Monster Museum, and Grave Creek Mound faces the Moundsville
-- penitentiary across the road.
--
-- Note how much of this is the coal industry rather than folklore: company
-- towns, a mine wars museum, the Matewan massacre marker, Whipple company
-- store, and the Hawks Nest tunnel memorial, where several hundred men died of
-- silicosis in the 1930s. The Hatfield graves are here too. West Virginia's
-- strange places are largely its labour history, which is a harder and better
-- story than the monsters.
--
-- 50 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone, verified_at)
values
  ('TNT Area', 'tnt-area', 'cryptids', 38.92977, -82.07616, 'Point Pleasant', 'WV', 'The abandoned World War II explosives complex north of Point Pleasant is inseparable from the original Mothman story, with many early sightings reported around the old TNT bunkers in 1966–67. Portions can be explored on foot, but the former industrial landscape includes remediated Superfund land and mixed property boundaries, so visitors should stay on established public paths.', 'limited', 'https://www.atlasobscura.com/places/tnt-area', 'America/New_York', now()),
  ('West Virginia Bigfoot Museum', 'west-virginia-bigfoot-museum', 'museums', 38.6643, -80.70776, 'Sutton', 'WV', 'Opened in 2021, this downtown Sutton museum is dedicated entirely to Bigfoot research and Appalachian sightings. Inside are footprint casts, hair samples, reports, photographs and other Sasquatch material, including what West Virginia tourism describes as the largest collection of its kind in the Mid-Atlantic.', 'open', 'https://wvbigfootmuseum.org/virtual-tour', 'America/New_York', now()),
  ('Archive of the Afterlife: The National Museum of the Paranormal', 'archive-of-the-afterlife-the-national-museum-of-the-paranormal', 'museums', 39.82631, -80.56853, 'Cameron', 'WV', 'This small paranormal museum houses allegedly haunted and unusual artifacts collected by investigator Steve Hummel, with displays built around the stories attached to each object. Its official information lists an April–November tour season but currently also displays a temporary-closure notice, so it should be verified before OddWay actively routes someone there.', 'limited', 'https://archive-afterlife.weebly.com/hours--admission.html', 'America/New_York', now()),
  ('Lake Shawnee Abandoned Amusement Park', 'lake-shawnee-abandoned-amusement-park', 'haunted', 37.40548, -81.14382, 'Rock', 'WV', 'The amusement park opened in 1926 and closed in the 1960s after multiple deaths, leaving behind a Ferris wheel, swings and other decaying structures that have since become the center of extensive paranormal lore. The property is private and visits are only permitted through scheduled tours, events or investigations—do not enter without an appointment.', 'limited', 'https://www.wvlakeshawnee.com/', 'America/New_York', now()),
  ('Brandy Gap Tunnel No. 2', 'brandy-gap-tunnel-no-2', 'haunted', 39.29296, -80.50363, 'Salem', 'WV', 'Also called the Flinderation Tunnel, this roughly Civil War-era railroad tunnel is now reached from the North Bend Rail Trail and has accumulated stories of ghostly voices and unexplained figures. The tunnel is dark enough that a flashlight is necessary, and reaching it requires trail travel rather than simply pulling off the highway.', 'limited', 'https://www.atlasobscura.com/places/brandy-gap-tunnel-2', 'America/New_York', now()),
  ('The Haunted Blennerhassett Hotel', 'the-haunted-blennerhassett-hotel', 'haunted', 39.26477, -81.56154, 'Parkersburg', 'WV', 'The Blennerhassett opened in 1889 and remains an operating historic hotel in downtown Parkersburg. Guests and paranormal tours have attached numerous apparition, voice and unexplained-activity stories to the building, making it one of the city''s best-known haunted landmarks.', 'open', 'https://www.hauntedparkersburgtours.com/13-haunted-places-near-parkersburg', 'America/New_York', now()),
  ('Greenbrier Ghost Historical Marker', 'greenbrier-ghost-historical-marker', 'folklore', 37.98912, -80.413, 'Smoot', 'WV', 'This roadside marker commemorates the extraordinary 1897 Greenbrier Ghost case, in which Zona Heaster Shue''s mother claimed her daughter''s ghost revealed that Zona had been murdered. The resulting murder conviction made the story one of America''s most famous cases in which alleged supernatural testimony played a role in bringing attention to a crime.', 'roadside', 'https://wvencprod.wvnet.edu/entries/2107', 'America/New_York', now()),
  ('Greenbrier County Courthouse', 'greenbrier-county-courthouse', 'weird-history', 37.80323, -80.44514, 'Lewisburg', 'WV', 'This is the courthouse where Erasmus Shue was tried for the 1897 murder of his wife Zona, the crime at the center of the Greenbrier Ghost legend. The building remains a functioning courthouse, so it is a legitimate historical stop rather than a paranormal attraction and visitors should behave accordingly during business hours.', 'open', 'https://greenbrierwv.com/places/greenbrier-county-courthouse', 'America/New_York', now()),
  ('Mount Wood Castle and Cemetery', 'mount-wood-castle-and-cemetery', 'roadside-oddities', 40.08042, -80.72227, 'Wheeling', 'WV', 'This unfinished stone mansion above Wheeling was begun in the 1920s by a physician whose grand plans collapsed after legal trouble, leaving a castle-like shell overlooking the Ohio Valley. The city-owned Mount Wood Cemetery and overlook can be visited, but the deteriorating ruins and steep overgrown areas should be treated as look-don''t-climb features.', 'limited', 'https://www.atlasobscura.com/places/mount-wood-castle-and-cemetery', 'America/New_York', now()),
  ('Mummies of Philippi', 'mummies-of-philippi', 'museums', 39.15342, -80.04246, 'Philippi', 'WV', 'In 1888, amateur scientist Graham Hamrick experimented with embalming two cadavers and produced a pair of remarkably preserved mummies that later traveled with sideshows. They eventually returned to Philippi and are now displayed at the Barbour County Historical Museum, whose schedule is more limited than a conventional year-round museum.', 'limited', 'https://www.hmdb.org/m.asp?m=211802', 'America/New_York', now()),
  ('John Henry Historical Park', 'john-henry-historical-park', 'folklore', 37.64958, -80.76673, 'Talcott', 'WV', 'The park commemorates the legendary steel-driving man John Henry and the story of his race against a steam drill during construction of the nearby Big Bend Tunnel. Visitors now find a large John Henry statue, interpretive displays and walking areas at the location traditionally associated with the legend.', 'open', 'https://www.johnhenrypark.com/', 'America/New_York', now()),
  ('Summersville Lake Lighthouse', 'summersville-lake-lighthouse', 'roadside-oddities', 38.19965, -80.86446, 'Mount Nebo', 'WV', 'Built from a recycled wind-turbine tower and dedicated in 2012, this 104-foot lighthouse is an intentionally landlocked oddity overlooking Summersville Lake. The tower can be climbed during its operating season, while off-season access may require a reservation and is weather dependent.', 'limited', 'https://www.atlasobscura.com/places/summersville-lake-lighthouse', 'America/New_York', now()),
  ('Kenova Pumpkin House', 'kenova-pumpkin-house', 'roadside-oddities', 38.39974, -82.56686, 'Kenova', 'WV', 'What began with a handful of carved pumpkins in 1978 has grown into an annual display covering the historic Griffith house and grounds with roughly 3,000 jack-o''-lanterns. It is a private residence transformed into a public attraction around Halloween, so this should only route travelers during the seasonal display.', 'limited', 'https://wvtourism.com/the-pumpkin-house-how-this-small-town-home-became-a-national-attraction/', 'America/New_York', now()),
  ('Blenko Man', 'blenko-man', 'roadside-oddities', 39.03852, -80.46659, 'Weston', 'WV', 'This strange life-size glass figure was constructed from Blenko glass pieces by sculptor John Zidek and is distinctive enough that even its two right feet have become part of the story. It now stands inside the Museum of American Glass, where visitors can see it along with a much broader collection of American glassware.', 'open', 'https://www.atlasobscura.com/places/blenko-man', 'America/New_York', now()),
  ('Greenbrier Congressional Bunker', 'greenbrier-congressional-bunker', 'weird-history', 37.78456, -80.30886, 'White Sulphur Springs', 'WV', 'Hidden beneath the Greenbrier resort during the Cold War, Project Greek Island was a massive fallout shelter designed to house the entire United States Congress after a nuclear attack. Its existence was exposed publicly in 1992, and the declassified bunker can now be visited only on scheduled guided tours.', 'limited', 'https://www.greenbrier.com/activities/bunker-tours/', 'America/New_York', now()),
  ('Nuttallburg', 'nuttallburg', 'weird-history', 38.05019, -81.03976, 'Nuttallburg', 'WV', 'Nuttallburg was once a major New River Gorge coal town and later became associated with Henry Ford''s attempt to control his own industrial supply chain. Today the National Park Service preserves mine structures, foundations and the enormous coal conveyor, but getting into the site involves narrow roads, trails and steep terrain.', 'limited', 'https://www.nps.gov/neri/learn/historyculture/nuttallburg.htm', 'America/New_York', now()),
  ('Thurmond Historic District', 'thurmond-historic-district', 'weird-history', 37.95712, -81.07879, 'Thurmond', 'WV', 'Once one of the busiest railroad towns in the New River Gorge, Thurmond declined until its preserved commercial district became an almost ghost-town-like National Park Service site. Visitors can walk past the old bank, hotel buildings and rail structures, while the restored depot operates seasonally as a visitor center.', 'open', 'https://www.nps.gov/neri/learn/historyculture/thurmond.htm', 'America/New_York', now()),
  ('Volcano Historic Boomtown Ruins', 'volcano-historic-boomtown-ruins', 'weird-history', 39.23138, -81.29039, 'Walker', 'WV', 'Volcano exploded into existence during the 1860s West Virginia oil boom and was largely destroyed by fire in 1879. Scattered industrial and community remains survive in the woods near Mountwood Park, but reaching them requires a moderately challenging hike rather than a roadside stop.', 'limited', 'https://www.atlasobscura.com/places/ghost-town-volcano-west-virginia', 'America/New_York', now()),
  ('Lost World Caverns', 'lost-world-caverns', 'roadside-oddities', 37.83265, -80.44684, 'Lewisburg', 'WV', 'Discovered through a surface opening and developed as a show cave, Lost World Caverns takes visitors through a huge underground chamber filled with stalactites and other formations. The standard attraction is self-guided, while a separate wild-cave experience goes much deeper and requires advance arrangements.', 'open', 'https://www.showcaves.com/english/usa/showcaves/LostWorld.html', 'America/New_York', now()),
  ('Smoke Hole Caverns', 'smoke-hole-caverns', 'roadside-oddities', 38.98614, -79.26592, 'Cabins', 'WV', 'These commercial caverns descend beneath the mountains of Pendleton County and feature flowstone, underground pools and other formations. Access to the cave itself is by guided tour, making it a limited stop even though the associated visitor facilities are open to the public.', 'limited', 'https://www.smokehole.com/contact.html', 'America/New_York', now()),
  ('Thorny Mountain Fire Tower', 'thorny-mountain-fire-tower', 'roadside-oddities', 38.31345, -79.94589, 'Dunmore', 'WV', 'The 65-foot Thorny Mountain Fire Tower rises above Seneca State Forest and has been converted into one of West Virginia''s strangest overnight accommodations. It can be reserved during the May–October season, with a climb to a small elevated cab and wraparound views of the forest.', 'limited', 'https://wvstateparks.com/wp-content/uploads/2020/07/WVSP_InspirationGuide.pdf', 'America/New_York', now()),
  ('Green Bank Telescope', 'green-bank-telescope', 'roadside-oddities', 38.43312, -79.83984, 'Green Bank', 'WV', 'The Robert C. Byrd Green Bank Telescope is one of the largest fully steerable radio telescopes on Earth and dominates the landscape inside the National Radio Quiet Zone. Visitors can explore Green Bank Observatory through its science center and public programs, although access immediately around the telescope itself is controlled rather than a casual walk-up.', 'open', 'https://greenbankobservatory.org/portal/gbt/instruments/', 'America/New_York', now()),
  ('West Virginia State Farm Museum', 'west-virginia-state-farm-museum', 'museums', 38.92043, -82.08964, 'Point Pleasant', 'WV', 'This sprawling museum recreates a historic West Virginia farming community with relocated buildings, farm machinery and unusual collections spread over dozens of acres. One of its stranger highlights is “General,” an enormous taxidermied horse once reported to weigh 2,850 pounds; the museum operates seasonally from spring into fall.', 'limited', 'https://www.wvfarmmuseum.org/', 'America/New_York', now()),
  ('Museum of Radio and Technology', 'museum-of-radio-and-technology', 'museums', 38.40129, -82.47315, 'Huntington', 'WV', 'This volunteer-run museum fills roughly 10,000 square feet with vintage radios, televisions, broadcast equipment, computers and other pieces of communication technology. It maintains regular weekend public hours and is free to visit, making it an unusually substantial stop for a specialized collection.', 'open', 'https://www.radiomuseum.org/museum/usa/museum-of-radio-and-technology-huntington-wv/', 'America/New_York', now()),
  ('Prabhupada''s Palace of Gold', 'prabhupadas-palace-of-gold', 'roadside-oddities', 39.96199, -80.60407, 'New Vrindaban', 'WV', 'Started in the 1970s as a residence for ISKCON founder A. C. Bhaktivedanta Swami Prabhupada, the project evolved into an ornate gold-covered palace decorated with stained glass, marble and elaborate interior work. It now operates as a public attraction within the New Vrindaban community and looks wildly out of place in rural West Virginia.', 'open', 'https://www.palaceofgold.com/', 'America/New_York', now()),
  ('Sweeney Punch Bowl', 'sweeney-punch-bowl', 'roadside-oddities', 40.10422, -80.66643, 'Wheeling', 'WV', 'This enormous cut-glass punch bowl was produced in the 1840s and weighs roughly 225 pounds, with a height of about five feet when assembled. It spent decades associated with the Sweeney family grave before being moved to the Oglebay Glass Museum in 1949, where it can now be seen indoors.', 'open', 'https://www.atlasobscura.com/places/sweeney-punch-bowl', 'America/New_York', now()),
  ('Billy Bob''s Wonderland Rock-afire Explosion', 'billy-bobs-wonderland-rock-afire-explosion', 'roadside-oddities', 38.41523, -82.25553, 'Barboursville', 'WV', 'Billy Bob''s Wonderland is a family entertainment center that preserves a working Rock-afire Explosion animatronic band, the characters made famous by ShowBiz Pizza Place in the 1980s. It has become a destination for animatronic enthusiasts because very few complete public shows remain in operation.', 'open', 'https://billybobs-wonderland.com/', 'America/New_York', now()),
  ('Cliff''s Museum of Car Memorabilia', 'cliffs-museum-of-car-memorabilia', 'museums', 39.21006, -81.05037, 'Harrisville', 'WV', 'This privately owned collection packs thousands of pieces of automobile, gasoline-station and roadside memorabilia into a roughly 13,000-square-foot building. The owner welcomes visitors without a normal admission charge, but the museum operates largely by appointment or when someone is available, so call before making a detour.', 'limited', 'https://cliffwvathebuilding.com/', 'America/New_York', now()),
  ('George Washington''s Bathtub', 'george-washingtons-bathtub', 'roadside-oddities', 39.62556, -78.22694, 'Berkeley Springs', 'WV', 'A small stone-lined outdoor bath in Berkeley Springs State Park marks the tradition of George Washington bathing in the warm mineral springs here during the 18th century. The present structure is a reconstruction rather than Washington''s literal surviving bathtub, but it has become one of the state''s most photographed historical oddities.', 'open', 'https://washingtonheritagetrail.com/morgan-county/george-washingtons-bathtub/', 'America/New_York', now()),
  ('Tu-Endie-Wei State Park and Battle Monument', 'tu-endie-wei-state-park-and-battle-monument', 'weird-history', 38.83919, -82.14081, 'Point Pleasant', 'WV', 'At the confluence of the Ohio and Kanawha rivers, this small state park preserves the site and memory of the 1774 Battle of Point Pleasant. Visitors find an imposing granite monument, historical markers and the seasonal Mansion House museum, all just a short distance from Point Pleasant''s Mothman attractions.', 'open', 'https://wvstateparks.com/parks/tu-endie-wei-state-park/park-history/', 'America/New_York', now()),
  ('James Rumsey Monument', 'james-rumsey-monument', 'weird-history', 39.43288, -77.79913, 'Shepherdstown', 'WV', 'This 75-foot monument honors inventor James Rumsey, who demonstrated an early steam-powered boat on the Potomac River at Shepherdstown in 1787. The monument stands in a public park overlooking the river and marks one of America''s lesser-known early experiments with steam navigation.', 'open', 'https://www.canaltrust.org/pyv/james-rumsey-monument-and-park/', 'America/New_York', now()),
  ('The Weeping Woman of Riverview Cemetery', 'the-weeping-woman-of-riverview-cemetery', 'folklore', 39.27477, -81.55457, 'Parkersburg', 'WV', 'A melancholy female statue in Riverview Cemetery has collected local legends claiming she weeps, changes position or grants wishes to visitors who approach her correctly. The monument is in an operating cemetery open during daytime hours, so this is a folklore stop that needs respectful cemetery behavior rather than nighttime ghost hunting.', 'open', 'https://www.atlasobscura.com/places/the-weeping-woman', 'America/New_York', now()),
  ('Thomas Bullitt''s Lone Grave', 'thomas-bullitts-lone-grave', 'weird-history', 38.33835, -81.62033, 'Charleston', 'WV', 'A single 18th-century grave sits by itself inside a modern Charleston park, the burial place of colonial-era surveyor and soldier Thomas Bullitt. The isolated stone is an unusual survival from a much earlier landscape and can be visited from the park during public hours.', 'open', 'https://www.atlasobscura.com/places/the-grave-of-thomas-bullitt', 'America/New_York', now()),
  ('Hanging Rock Raptor Observatory', 'hanging-rock-raptor-observatory', 'roadside-oddities', 37.50448, -80.45293, 'Waiteville', 'WV', 'This former fire lookout sits on a narrow ridge reached by roughly a 1.2-mile hike and became a famous place for watching migrating hawks and other raptors. The trail remains open, but the tourism authority currently reports the observation structure itself as temporarily closed, so check status before building a route around it.', 'limited', 'https://visitwv.com/partners/hanging-rock-raptor-observatory/', 'America/New_York', now()),
  ('Mortar Man', 'mortar-man', 'roadside-oddities', 38.34931, -81.63556, 'Charleston', 'WV', 'High on a downtown Charleston wall is an absurdly tiny human figure only a few inches tall, installed in a mortar joint by artist P. Joseph Mullins. It is around twelve feet above street level and intended to be spotted from the public sidewalk rather than approached or climbed toward.', 'roadside', 'https://www.atlasobscura.com/places/mortar-man', 'America/New_York', now()),
  ('Blennerhassett Island Historical State Park', 'blennerhassett-island-historical-state-park', 'weird-history', 39.27194, -81.62472, 'Parkersburg', 'WV', 'Harman and Margaret Blennerhassett built an extravagant estate on this Ohio River island, which later became tangled in Aaron Burr''s mysterious western political schemes. A reconstructed mansion and historical grounds can be toured today, but normal visitor access depends on the seasonal sternwheel boat from Parkersburg.', 'limited', 'https://wvstateparks.com/parks/blennerhassett-island-historical-state-park/', 'America/New_York', now()),
  ('Kaymoor Mine Site', 'kaymoor-mine-site', 'weird-history', 38.04529, -81.06775, 'Fayetteville', 'WV', 'Kaymoor was one of the New River Gorge''s major coal operations, and its abandoned mine complex, coke ovens and town remains survive on the gorge wall. These coordinates route to the Kaymoor Top trailhead; reaching the mine requires a steep hike, and access conditions can change during trail rehabilitation.', 'limited', 'https://www.nps.gov/neri/learn/historyculture/visiting-kaymoor.htm', 'America/New_York', now()),
  ('Grave Creek Mound Archaeological Complex', 'grave-creek-mound-archaeological-complex', 'weird-history', 39.91686, -80.74472, 'Moundsville', 'WV', 'Built by Adena people around 250–150 B.C., Grave Creek Mound is one of the largest surviving conical burial mounds of its culture and required the movement of tens of thousands of tons of earth. A free state museum beside the mound interprets West Virginia archaeology and the people who built it.', 'open', 'https://wvculture.org/explore/grave-creek-mound/', 'America/New_York', now()),
  ('Beckley Exhibition Coal Mine', 'beckley-exhibition-coal-mine', 'weird-history', 37.78434, -81.19614, 'Beckley', 'WV', 'Visitors ride a mine car roughly 1,500 feet into a historic drift mine while veteran miners explain the equipment and working conditions of West Virginia coal mining. The surrounding complex includes relocated coal-camp buildings, but the underground attraction operates seasonally.', 'limited', 'https://beckley.org/coal-mine/', 'America/New_York', now()),
  ('Hawks Nest Workers Memorial and Grave Site', 'hawks-nest-workers-memorial-and-grave-site', 'weird-history', 38.23447, -80.85269, 'Lookout', 'WV', 'This memorial marks the burial area associated with African American workers who died after being exposed to enormous concentrations of silica dust during construction of the Hawks Nest Tunnel in the early 1930s. The National Park Service describes the project as one of America''s worst industrial tragedies.', 'open', 'https://home.nps.gov/places/hawks-nest-workers-memorial-and-grave-site.htm', 'America/New_York', now()),
  ('Devil Anse Hatfield Grave', 'devil-anse-hatfield-grave', 'folklore', 37.70447, -81.99245, 'Sarah Ann', 'WV', 'Hatfield clan patriarch Anderson “Devil Anse” Hatfield is buried in the family cemetery beneath a life-size marble statue imported from Italy. The cemetery is publicly visited as part of Hatfield-McCoy heritage tourism, but reaching the graves requires a steep climb and visitors should use care on the slope.', 'limited', 'https://www.hmdb.org/m.asp?Result=1&m=49912', 'America/New_York', now()),
  ('Devil Anse Hatfield Homeplace & Museum', 'devil-anse-hatfield-homeplace-museum', 'museums', 37.69978, -81.99419, 'Sarah Ann', 'WV', 'This museum occupies the Hatfield homeplace area and preserves family material connected with Devil Anse, the famous feud and later generations of the family. It operates with varying hours and visitors should call ahead.', 'limited', 'https://hatfieldmccoyfoundation.org/devil-anse-homeplace-museum/', 'America/New_York', now()),
  ('Matewan Massacre Historical Marker', 'matewan-massacre-historical-marker', 'weird-history', 37.62283, -82.1655, 'Matewan', 'WV', 'This downtown marker identifies the setting of the May 19, 1920 gunfight between Baldwin-Felts agents, local officials and miners during the struggle to unionize the southern West Virginia coalfields. Ten men were killed, and the confrontation helped trigger the escalation that ultimately led toward the Battle of Blair Mountain.', 'open', 'https://www.hmdb.org/m.asp?m=169678', 'America/New_York', now()),
  ('West Virginia Mine Wars Museum', 'west-virginia-mine-wars-museum', 'museums', 37.62277, -82.16538, 'Matewan', 'WV', 'Founded in 2015, this museum preserves the story of the violent early-20th-century struggles between coal miners, mine guards and coal companies, including Matewan and Blair Mountain. Its current Matewan location contains artifacts, weapons, photographs, firsthand accounts and other material from the Mine Wars.', 'open', 'https://wvminewars.org/visit-the-museum', 'America/New_York', now()),
  ('Whipple Company Store', 'whipple-company-store', 'weird-history', 37.95882, -81.1656, 'Whipple', 'WV', 'Built in the 1890s, this unusual coal-company store once served the surrounding mining community and later operated as a museum interpreting company-town life. The museum closed and the building was sold to a private owner in 2018, so OddWay travelers should only view the exterior from the public road unless a new authorized access program is announced.', 'private', 'https://www.hmdb.org/m.asp?m=140168', 'America/New_York', now()),
  ('Anna Jarvis Birthplace Museum', 'anna-jarvis-birthplace-museum', 'museums', 39.29458, -80.04447, 'Webster', 'WV', 'Anna Jarvis, the woman who successfully campaigned for the creation of Mother''s Day, was born at this house in Webster in 1864. The restored home now interprets Jarvis''s life as well as its Civil War connection to Union General George B. McClellan, but it is a small attraction with a limited operating season.', 'limited', 'https://www.nps.gov/people/anna-maria-jarvis.htm', 'America/New_York', now()),
  ('Hawks Nest Tunnel Disaster Overlook', 'hawks-nest-tunnel-disaster-overlook', 'weird-history', 38.12267, -81.12752, 'Ansted', 'WV', 'From the Hawks Nest State Park overlook area, visitors can follow interpretation connected with the three-mile tunnel whose construction exposed thousands of workers to dangerous silica dust beginning in 1930. The National Park Service directs visitors here as a formal stop for understanding the disaster.', 'open', 'https://home.nps.gov/places/hawks-nest-tunnel-disaster.htm', 'America/New_York', now()),
  ('Williamson Coal House', 'williamson-coal-house', 'roadside-oddities', 37.67194, -82.27778, 'Williamson', 'WV', 'Built in 1933 from roughly 65 tons of local bituminous coal, this small downtown building is quite literally constructed from blocks of coal. It survived a damaging 2010 fire, was restored and now houses the Tug Valley Chamber of Commerce and visitor information center.', 'open', 'https://wvtourism.com/town-guide-williamson/', 'America/New_York', now()),
  ('International Mother''s Day Shrine', 'international-mothers-day-shrine', 'weird-history', 39.34073, -80.01854, 'Grafton', 'WV', 'The former Andrews Methodist Episcopal Church hosted the first official Mother''s Day observance on May 10, 1908 after Anna Jarvis began campaigning for a holiday honoring mothers. The 1873 church became the International Mother''s Day Shrine in 1962 and now operates as a seasonal historic attraction and museum.', 'limited', 'https://www.internationalmothersdayshrine.org/about-us', 'America/New_York', now()),
  ('Silver Run Tunnel', 'silver-run-tunnel', 'haunted', 39.20769, -81.19664, 'Cairo', 'WV', 'Tunnel No. 19 on the North Bend Rail Trail is associated with the “White Woman of Silver Run,” a ghost said to have appeared on the former B&O tracks in front of passing trains. The 1,376-foot tunnel is publicly reachable from the rail trail, but it is dark, damp and requires a walk or bike ride to reach, so visitors should bring a light.', 'limited', 'https://wvtourism.com/the-west-virginia-paranormal-trail-just-got-spookier-with-these-4-new-locations/', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  verified_at   = excluded.verified_at;
