-- West Virginia, second batch.
--
-- Paul Bunyan and Babe goes in as paul-bunyan-and-babe-nitro rather than
-- paul-bunyan-and-babe, which belongs to the pair at Trees of Mystery in
-- Klamath, California. Same name, different statues, 2,400 miles apart — and
-- the upsert would have moved the Californian one to West Virginia without
-- complaint.
--
-- Eight coordinate flags, all of them small towns where several stops sit
-- within a few hundred metres: Lewisburg's courthouse, theatre and Carnegie
-- Hall are all on the same few blocks, and Moundsville's penitentiary, mound
-- and glass museum face each other.
--
-- 40 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, timezone, verified_at)
values
  ('Apollo Civic Theatre', 'apollo-civic-theatre', 'haunted', 39.45798, -77.96218, 'Martinsburg', 'WV', 'This historic downtown theatre is one of the stops on West Virginia''s Paranormal Trail, with stories of unexplained activity tied to the old performance space. Visitors can see the building during scheduled performances and special haunted events, while paranormal investigations are offered only at selected times or by arrangement.', 'limited', 'https://wvtourism.com/west-virginia-paranormal-trail/', 'America/New_York', now()),
  ('Carnegie Hall', 'carnegie-hall', 'haunted', 37.80212, -80.44822, 'Lewisburg', 'WV', 'Built in 1902, Lewisburg''s Carnegie Hall has accumulated reports of footsteps, whispers, lights and other unexplained activity inside the historic arts venue. It remains an operating performance hall, so visitors should attend a scheduled event or view the exterior rather than treating it as an unrestricted investigation site.', 'limited', 'https://wvtourism.com/west-virginia-paranormal-trail/', 'America/New_York', now()),
  ('Greenbrier Valley Theatre', 'greenbrier-valley-theatre', 'folklore', 37.80017, -80.44284, 'Lewisburg', 'WV', 'Greenbrier Valley Theatre keeps the Greenbrier Ghost story alive through performances and displays connected with the famous Zona Heaster Shue case. The theatre is an active arts venue, so interior access follows box-office and performance schedules rather than open exploration.', 'limited', 'https://wvtourism.com/west-virginia-paranormal-trail/', 'America/New_York', now()),
  ('Ghost Tours of Harpers Ferry', 'ghost-tours-of-harpers-ferry', 'haunted', 39.32282, -77.73116, 'Harpers Ferry', 'WV', 'This guided walking tour uses the historic streets around Harpers Ferry to tell local ghost stories, Civil War tales and legends attached to the town''s old buildings. Tours meet near St. Peter''s Roman Catholic Church and run on a scheduled basis, so reservations are recommended.', 'limited', 'https://wvtourism.com/west-virginia-paranormal-trail/', 'America/New_York', now()),
  ('Hotel Morgan', 'hotel-morgan', 'haunted', 39.62849, -79.95761, 'Morgantown', 'WV', 'The restored Hotel Morgan is an operating downtown hotel with decades of guest stories about unexplained sounds and apparitions. It is included on West Virginia''s Paranormal Trail, but it remains a functioning hotel rather than a dedicated ghost attraction, so visit as a guest, diner or respectful sightseer.', 'open', 'https://wvtourism.com/west-virginia-paranormal-trail/', 'America/New_York', now()),
  ('The Old Hospital on College Hill', 'the-old-hospital-on-college-hill', 'haunted', 37.67495, -82.27287, 'Williamson', 'WV', 'Opened as a hospital in 1928, this large hilltop building served medical and later office uses before becoming a public historic and paranormal-tour destination in 2021. Current visits are through scheduled tours, investigations and special events; it is not a daily walk-in attraction.', 'limited', 'https://www.collegehillhospital.com/', 'America/New_York', now()),
  ('Shepherdstown Ghost Tours', 'shepherdstown-ghost-tours', 'haunted', 39.43067, -77.80492, 'Shepherdstown', 'WV', 'These guided evening walks explore reported hauntings and darker stories around one of West Virginia''s oldest towns. Tours operate on scheduled dates and require booking rather than offering unrestricted access to the buildings discussed along the route.', 'limited', 'https://www.smalltownghosttours.net/', 'America/New_York', now()),
  ('Shepherdstown Mystery Walks', 'shepherdstown-mystery-walks', 'haunted', 39.43075, -77.80591, 'Shepherdstown', 'WV', 'Shepherdstown Mystery Walks leads visitors through the historic district while recounting local ghost stories, strange incidents and town legends. Walks meet near the town''s visitor area and operate on scheduled dates, so check the current calendar before routing here.', 'limited', 'https://shepherdstownmysterywalks.com/', 'America/New_York', now()),
  ('The Haunted Haymond', 'the-haunted-haymond', 'haunted', 38.6625, -80.70917, 'Sutton', 'WV', 'This century-old Sutton house is promoted for paranormal tours and overnight investigations centered on stories of former residents William and Emma Haymond. It is not a normal walk-in museum; tours and overnight access are by appointment or scheduled event.', 'limited', 'https://wvtourism.com/west-virginia-paranormal-trail/', 'America/New_York', now()),
  ('Historic Glen Ferris Inn', 'historic-glen-ferris-inn', 'haunted', 38.15025, -81.21472, 'Glen Ferris', 'WV', 'The riverside Glen Ferris Inn dates to the nineteenth century and has long been associated with stories of a resident spirit commonly called "The Colonel." It remains an operating inn and restaurant, so travelers can visit normally without needing a paranormal event.', 'open', 'https://www.glenferrisinn.com/', 'America/New_York', now()),
  ('Elk River Bigfoot Statue', 'elk-river-bigfoot-statue', 'cryptids', 38.54886, -80.99986, 'Ivydale', 'WV', 'Clay County students built this roughly 10.5-foot, 1,800-pound Bigfoot sculpture for the Elk River Trail, giving the rail-trail its own Sasquatch landmark. The statue stands near Mile Marker 47 about two miles upstream from the Ivydale trailhead, so reaching it requires walking or biking the trail.', 'limited', 'https://wvtourism.com/west-virginia-paranormal-trail/', 'America/New_York', now()),
  ('Hempfield Tunnel', 'hempfield-tunnel', 'haunted', 40.07285, -80.71221, 'Wheeling', 'WV', 'This former railroad tunnel is now part of Wheeling''s trail system and has become associated with reports of voices, figures and other unexplained activity. It is publicly reachable on the trail, but the tunnel is dark and should be approached with a light and normal trail precautions.', 'limited', 'https://wvtourism.com/west-virginia-paranormal-trail/', 'America/New_York', now()),
  ('Charlie the Coal Miner', 'charlie-the-coal-miner', 'roadside-oddities', 39.38024, -80.31443, 'Shinnston', 'WV', 'Charlie is a 21-foot scrap-metal coal miner with a lunch pail and a working light in his helmet, unveiled in 1999 as a memorial to local miners. He stands outside the Repair King property at 253 Lincoln Drive and can be photographed from the parking-area approach without entering any restricted industrial space.', 'roadside', 'https://www.atlasobscura.com/places/charlie-coal-miner', 'America/New_York', now()),
  ('Alderson Lion Historical Marker', 'alderson-lion-historical-marker', 'folklore', 37.72538, -80.64115, 'Alderson', 'WV', 'This marker preserves the bizarre local story of "French," a lion kept in Alderson between 1890 and 1894 after being adopted from a traveling circus. According to the marker, the lion was allowed to roam until it frightened a salesman into the Greenbrier River, prompting the town to require lions to be leashed.', 'roadside', 'https://www.wgpfoundation.org/historic-markers/alderson-lion/', 'America/New_York', now()),
  ('Gary Bowling''s House of Art', 'gary-bowlings-house-of-art', 'museums', 37.26753, -81.22354, 'Bluefield', 'WV', 'This Appalachian art center occupies the former Ramsey School, a 1926 hillside building with entrances on seven different levels. Inside are rotating works by regional artists, but hours are limited and appointment visits are also used, so check before making a dedicated detour.', 'limited', 'https://visitmercercounty.com/company/gary-bowlings-house-of-art/', 'America/New_York', now()),
  ('Patriot Fireworks Mega Missile', 'patriot-fireworks-mega-missile', 'roadside-oddities', 39.33426, -78.06315, 'Bunker Hill', 'WV', 'A tall grain silo beside Patriot Fireworks has been transformed into a fake missile labeled as a giant roadside weapon. The "Mega Missile" is visible from the road and business parking area, making it a quick photo stop rather than an attraction that requires entering the structure.', 'roadside', 'https://www.roadsideamerica.com/tip/63258', 'America/New_York', now()),
  ('Katherine Johnson Statue', 'katherine-johnson-statue', 'weird-history', 38.38023, -81.76765, 'Institute', 'WV', 'West Virginia State University unveiled this seven-foot bronze statue of NASA mathematician and alumna Katherine Johnson in 2018. It stands on the university campus as a public monument to the woman whose calculations helped make early American spaceflight possible.', 'open', 'https://wvstateu.edu/news/west-virginia-state-university-alumnus-creates-las/', 'America/New_York', now()),
  ('Big Apple Time Capsule', 'big-apple-time-capsule', 'roadside-oddities', 39.45754, -77.97133, 'Martinsburg', 'WV', 'This oversized fiberglass apple was installed in 1990 as a Community Pride Project honoring Berkeley County''s apple-growing history. The base contains a time capsule intended to remain sealed until 2040, while the apple itself is a permanent public photo stop.', 'open', 'https://www.atlasobscura.com/places/big-apple-time-capsule', 'America/New_York', now()),
  ('Hillbilly Hot Dogs', 'hillbilly-hot-dogs', 'roadside-oddities', 38.50659, -82.29823, 'Lesage', 'WV', 'This deliberately over-the-top roadside restaurant is built around buses, junkyard art, hand-painted signs and hillbilly-themed structures along the Ohio River. It has been operating for more than two decades and remains a working restaurant, so visitors can explore the public grounds while stopping for food.', 'open', 'https://www.hillbillyhotdogs.com/', 'America/New_York', now()),
  ('Medical Exhibit of Yesteryear', 'medical-exhibit-of-yesteryear', 'museums', 39.47521, -77.98086, 'Martinsburg', 'WV', 'Inside Berkeley Medical Center is a small display of antique medical equipment, old nursing uniforms, wooden wheelchairs, handmade crutches and other artifacts from earlier eras of medicine. Because the exhibit is inside an operating hospital, visit only during permitted public hours and do not interfere with patients or staff.', 'limited', 'https://www.roadsideamerica.com/tip/40978', 'America/New_York', now()),
  ('Belle Boyd House', 'belle-boyd-house', 'museums', 39.45966, -77.96177, 'Martinsburg', 'WV', 'Built in 1853, this was the childhood home of Confederate spy Belle Boyd, one of the Civil War''s most notorious civilian intelligence figures. The restored house now serves as a historical museum and visitor center with exhibits on Boyd, local history and the surrounding region.', 'open', 'https://www.cityofmartinsburg.org/about-us/belle-boyd-house', 'America/New_York', now()),
  ('Don Knotts Statue', 'don-knotts-statue', 'roadside-oddities', 39.63075, -79.95524, 'Morgantown', 'WV', 'Morgantown unveiled this life-size bronze statue of hometown actor Don Knotts in 2016 outside the Metropolitan Theatre. The sculpture includes references to his best-known roles and is freely accessible from the downtown sidewalk area.', 'open', 'https://www.atlasobscura.com/places/statue-of-don-knotts', 'America/New_York', now()),
  ('Morgantown Personal Rapid Transit', 'morgantown-personal-rapid-transit', 'weird-history', 39.62953, -79.9559, 'Morgantown', 'WV', 'Morgantown''s Personal Rapid Transit system is a 1970s federal transportation experiment that became a permanent part of West Virginia University. Small automated cars move riders between stations on a dedicated guideway, making the system itself an unusual piece of living transportation history; rides follow WVU''s current operating schedule.', 'open', 'https://www.atlasobscura.com/places/morgantown-prt', 'America/New_York', now()),
  ('Paul Bunyan and Babe', 'paul-bunyan-and-babe-nitro', 'roadside-oddities', 38.44557, -81.8231, 'Nitro', 'WV', 'A giant fiberglass Paul Bunyan and blue Babe the Ox stand along First Avenue outside a local supply business in Nitro. These classic oversized advertising figures are visible from the road and are best treated as a quick public-road photo stop.', 'roadside', 'https://fotospot.com/attractions/west-virginia/paul-bunyan-and-babe', 'America/New_York', now()),
  ('Hank Williams Death Monument', 'hank-williams-death-monument', 'weird-history', 37.97603, -81.14121, 'Oak Hill', 'WV', 'A small monument in Oak Hill marks the city where driver Charles Carr discovered that country singer Hank Williams had died in the back seat of his Cadillac on New Year''s Day 1953. The marker gives travelers a physical stop tied to one of American music''s most famous and grim road-trip stories.', 'open', 'https://www.wvencyclopedia.org/entries/2277', 'America/New_York', now()),
  ('Upper Big Branch Miners Memorial', 'upper-big-branch-miners-memorial', 'weird-history', 37.97968, -81.53437, 'Whitesville', 'WV', 'This public memorial honors the 29 miners killed in the Upper Big Branch Mine disaster on April 5, 2010. Dedicated in 2012, its long granite wall includes life-size silhouettes and the names of the victims, with parking and year-round public access.', 'open', 'https://www.ubbminersmemorial.com/', 'America/New_York', now()),
  ('Shoney''s Big Boy Museum', 'shoneys-big-boy-museum', 'roadside-oddities', 38.36651, -81.6663, 'Charleston', 'WV', 'At the site where Alex Schoenbaum opened the Parkette Drive-In in 1947 stands a small outdoor monument and display telling the story of the chain that became Shoney''s Big Boy. It is more roadside kiosk than full museum, but the Big Boy-topped structure and vintage display panels remain accessible from the public parking area.', 'roadside', 'https://www.roadsideamerica.com/tip/34673', 'America/New_York', now()),
  ('Kruger Street Toy & Train Museum', 'kruger-street-toy-train-museum', 'museums', 40.04055, -80.65832, 'Wheeling', 'WV', 'Opened to the public in 1998 inside a former 1906 schoolhouse, this museum is packed with model trains, dolls, games, toys and pop-culture collectibles. It maintains regular seasonal public hours and is a substantial stop rather than a single roadside display.', 'open', 'https://www.toyandtrain.com/', 'America/New_York', now()),
  ('O''Hurley''s General Store', 'ohurleys-general-store', 'weird-history', 39.42788, -77.80427, 'Shepherdstown', 'WV', 'O''Hurley''s operates as an old-fashioned general store filled with hardware, household goods, musical instruments and objects that feel pulled from an earlier version of the town. The working store is open to visitors and is also known for recurring traditional music gatherings.', 'open', 'https://www.ohurleys.com/', 'America/New_York', now()),
  ('Heritage Farm Museum & Village', 'heritage-farm-museum-village', 'museums', 38.37643, -82.46994, 'Huntington', 'WV', 'Heritage Farm recreates an Appalachian village with historic-style buildings, craft demonstrations, machinery and multiple museums devoted to regional life. The attraction first opened in the 1990s and now operates on a seasonal schedule, so check current dates before routing travelers there.', 'limited', 'https://www.heritagefarmwv.com/', 'America/New_York', now()),
  ('Griffith & Feil Soda Fountain', 'griffith-feil-soda-fountain', 'weird-history', 38.39953, -82.57819, 'Kenova', 'WV', 'Griffith & Feil traces its pharmacy roots to 1892 and still operates an old-fashioned soda fountain inside the working business. Visitors can sit at the counter for ice cream and diner food while surrounded by a surviving piece of small-town pharmacy history.', 'open', 'https://gfsodafountain.com/', 'America/New_York', now()),
  ('Fostoria Glass Museum', 'fostoria-glass-museum', 'museums', 39.91956, -80.74539, 'Moundsville', 'WV', 'This museum preserves glass made by the Fostoria Glass Company, which moved from Ohio to Moundsville in 1891 and became one of the city''s major manufacturers. Displays include tableware, specialty pieces and company history, with limited seasonal afternoon hours rather than daily year-round access.', 'limited', 'https://www.fostoriaglass.org/', 'America/New_York', now()),
  ('Our Lady of the Pines', 'our-lady-of-the-pines', 'roadside-oddities', 39.25242, -79.49874, 'Eglon', 'WV', 'Built in 1958, this tiny stone church measures only about 24 by 12 feet and was once promoted as the smallest church in the 48 contiguous states. Six small pews, an altar and religious statuary fit inside, and the carefully maintained building remains a peaceful roadside curiosity open to respectful visitors.', 'open', 'https://www.atlasobscura.com/places/our-lady-of-the-pines', 'America/New_York', now()),
  ('Abandoned Lock No. 19', 'abandoned-lock-no-19', 'weird-history', 39.25509, -81.69157, 'Washington', 'WV', 'Built in 1916, Lock and Dam No. 19 once helped move river traffic past a wicket dam on the Ohio River before the system was replaced in 1968. Ruins of the old powerhouse remain near a public boat ramp, but the structure is deteriorated and should be viewed without climbing; the former lock houses uphill are private property and should not be approached.', 'limited', 'https://www.atlasobscura.com/places/abandoned-lock-no-19', 'America/New_York', now()),
  ('Blue Sulphur Springs Pavilion', 'blue-sulphur-springs-pavilion', 'folklore', 37.82791, -80.63852, 'Blue Sulphur Springs', 'WV', 'This Greek Revival pavilion is the lone major survivor of a nineteenth-century resort built around a mineral spring once advertised for its healing properties. After extensive restoration, the pavilion was rededicated in 2023 and is now open to the public daily during posted daytime hours.', 'open', 'https://greenbrierhistorical.org/preservation/blue-sulphur-springs-pavillion/', 'America/New_York', now()),
  ('Luther Elkins Petroglyphs', 'luther-elkins-petroglyphs', 'weird-history', 37.68156, -81.66492, 'Clear Fork', 'WV', 'These rock carvings are genuine Indigenous petroglyphs generally attributed to Native peoples of the region, although they became famous in the 1980s after fringe claims tried to reinterpret them as ancient Irish writing. The site is undeveloped and reached through rough terrain near private property; stay on the legitimate access route and never touch, chalk or trace the carvings.', 'limited', 'https://www.atlasobscura.com/places/luther-elkins-petroglyphs', 'America/New_York', now()),
  ('Dingess Tunnel', 'dingess-tunnel', 'weird-history', 37.86902, -82.17847, 'Dingess', 'WV', 'The 3,327-foot Dingess Tunnel opened in 1892 as part of the Norfolk & Western Railway and later became a one-lane county-road tunnel after the rail route was abandoned. It was substantially rehabilitated in 2019 with lighting, drainage and paving, and travelers can still drive through this unusually long former railroad bore today.', 'open', 'https://www.wvencyclopedia.org/entries/1867', 'America/New_York', now()),
  ('Cass Scenic Railroad State Park', 'cass-scenic-railroad-state-park', 'weird-history', 38.39682, -79.91429, 'Cass', 'WV', 'Cass preserves a former lumber-company town and the steam railroad that once hauled timber out of the surrounding mountains. Visitors can explore the historic town area, while the famous Shay-locomotive train rides operate on scheduled, ticketed departures rather than as an always-available attraction.', 'limited', 'https://wvstateparks.com/parks/cass-scenic-railroad-state-park/', 'America/New_York', now()),
  ('Neighborhood Menagerie', 'neighborhood-menagerie', 'roadside-oddities', 37.79443, -81.18773, 'Beckley', 'WV', 'Dozens of fiberglass animals, dinosaurs and a Bigfoot fill several residential yards along Conway Street, all part of a collection owned by the same local resident. The owner has welcomed visitors, but these are still private residential properties, so OddWay travelers should view the figures from the public street unless they receive clear permission to enter a yard.', 'private', 'https://www.roadsideamerica.com/tip/69799', 'America/New_York', now()),
  ('The Poky Dot', 'the-poky-dot', 'roadside-oddities', 39.47057, -80.155, 'Fairmont', 'WV', 'The Poky Dot was a famously colorful Fairmont diner known for enormous desserts, including a nine-pound banana split, and an interior that looked more like a carnival than a conventional restaurant. The business is now permanently closed, so this is a record of a vanished roadside institution; view the former location only from public ground and do not attempt to enter.', 'closed', 'https://www.atlasobscura.com/places/the-poky-dot', 'America/New_York', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  verified_at   = excluded.verified_at;
