-- Wyoming. The state had four stops.
--
-- Nothing dropped: none of the four existing stops appears in this batch.
--
-- One rename. Alpine, New Jersey holds devils-tower for a stone folly built by
-- a man whose wife fell from it, so Wyoming's monolith goes in as
-- devils-tower-wyoming. New Jersey got there first, which is the rule.
--
-- Very well sourced: nps.gov leads with 47, then travelwyoming.com, blm.gov
-- and the state parks service.
--
-- Three proximity flags kept, all Yellowstone thermal features that genuinely
-- sit that close — Liberty Cap is 41 metres from the Mammoth lower terraces
-- because it stands at the foot of them.
--
-- Roughly a third of this batch is Yellowstone, which raises a question worth
-- noting rather than solving here: a single park now has more entries than
-- eight states do. It is defensible — people plan whole trips around it — but
-- worth watching if it starts crowding the map.
--
-- The whole state is Mountain time.
--
-- 126 stops, every one with a source.

insert into public.stops
  (name, slug, category, latitude, longitude, city, state, description,
   public_access, source, website, timezone, verified_at)
values
  ('Old Faithful Geyser', 'old-faithful-geyser', 'roadside-oddities', 44.46031, -110.8283, 'Yellowstone National Park', 'WY', 'Yellowstone''s best-known cone geyser, famous for frequent, comparatively predictable eruptions from the Upper Geyser Basin.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Grand Prismatic Spring', 'grand-prismatic-spring', 'roadside-oddities', 44.525, -110.83806, 'Yellowstone National Park', 'WY', 'A massive rainbow-ringed hot spring whose vivid microbial mats make it one of the strangest natural sights in the park.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Excelsior Geyser Crater', 'excelsior-geyser-crater', 'roadside-oddities', 44.5263, -110.83679, 'Yellowstone National Park', 'WY', 'An enormous blue thermal crater beside Grand Prismatic that once produced some of the largest known geyser eruptions.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Fountain Paint Pot', 'fountain-paint-pot', 'roadside-oddities', 44.55058, -110.8062, 'Yellowstone National Park', 'WY', 'A boardwalk basin where bubbling mud pots, hot springs, fumaroles and geysers occur in one compact stop.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Great Fountain Geyser', 'great-fountain-geyser', 'roadside-oddities', 44.53642, -110.7999, 'Yellowstone National Park', 'WY', 'A large fountain-type geyser in the Lower Geyser Basin that erupts from a terraced sinter platform.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('White Dome Geyser', 'white-dome-geyser', 'roadside-oddities', 44.53931, -110.803, 'Yellowstone National Park', 'WY', 'A roadside geyser with a tall white cone that looks unusually sculptural even when the vent is quiet.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Artists Paintpots', 'artists-paintpots', 'roadside-oddities', 44.69271, -110.73799, 'Yellowstone National Park', 'WY', 'A hillside thermal area of pastel mud pots, steaming vents and hot springs reached by a short trail and boardwalk.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Mud Volcano', 'mud-volcano', 'roadside-oddities', 44.62432, -110.4345, 'Yellowstone National Park', 'WY', 'A violently bubbling acidic mud feature in one of Yellowstone''s most sulfurous-smelling thermal areas.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Dragon''s Mouth Spring', 'dragons-mouth-spring', 'roadside-oddities', 44.62516, -110.4349, 'Yellowstone National Park', 'WY', 'Steam and surging water pulse from a cave-like opening, creating the roaring effect that inspired the spring''s name.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Black Dragon''s Caldron', 'black-dragons-caldron', 'roadside-oddities', 44.62019, -110.4352, 'Yellowstone National Park', 'WY', 'A dark, churning mud pot that appeared suddenly in the 1940s and remains one of the Mud Volcano area''s stranger features.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Sulphur Caldron', 'sulphur-caldron', 'roadside-oddities', 44.62838, -110.4334, 'Yellowstone National Park', 'WY', 'An extremely acidic hot spring overlooking the Yellowstone River, with bright mineral staining and constant sulfur fumes.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Abyss Pool', 'abyss-pool', 'roadside-oddities', 44.41821, -110.5725, 'Yellowstone National Park', 'WY', 'A remarkably deep blue hot spring in West Thumb Geyser Basin whose apparent depth gives it an almost bottomless look.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Black Pool', 'black-pool', 'roadside-oddities', 44.41822, -110.5718, 'Yellowstone National Park', 'WY', 'Despite its name, this West Thumb pool is now intensely blue after hotter water altered the microbes that once darkened it.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Fishing Cone', 'fishing-cone', 'roadside-oddities', 44.41727, -110.5703, 'Yellowstone National Park', 'WY', 'A hot-spring cone at Yellowstone Lake once associated with the old story of anglers cooking freshly caught fish without leaving the line.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Castle Geyser', 'castle-geyser', 'roadside-oddities', 44.46344, -110.8367, 'Yellowstone National Park', 'WY', 'One of Yellowstone''s largest geyser cones, built by thousands of years of mineral deposits into a castle-like formation.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Grand Geyser', 'grand-geyser', 'roadside-oddities', 44.46665, -110.8369, 'Yellowstone National Park', 'WY', 'The world''s tallest predictable fountain-type geyser, capable of sending powerful bursts high above the Upper Geyser Basin.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Daisy Geyser', 'daisy-geyser', 'roadside-oddities', 44.47017, -110.8442, 'Yellowstone National Park', 'WY', 'A frequently erupting geyser whose angled jets sweep across the basin rather than firing straight upward.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Riverside Geyser', 'riverside-geyser', 'roadside-oddities', 44.47347, -110.8408, 'Yellowstone National Park', 'WY', 'A geyser on the Firehole River that throws its eruption in a graceful arc over the water.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Grotto Geyser', 'grotto-geyser', 'roadside-oddities', 44.4718, -110.84176, 'Yellowstone National Park', 'WY', 'Its bizarre, knobby cone encloses old tree stumps and resembles a stone grotto assembled by hand.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Morning Glory Pool', 'morning-glory-pool', 'roadside-oddities', 44.47503, -110.8435, 'Yellowstone National Park', 'WY', 'A famous flower-shaped hot spring whose colors record both natural microbial growth and past human damage to the vent.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Beehive Geyser', 'beehive-geyser', 'roadside-oddities', 44.46264, -110.8299, 'Yellowstone National Park', 'WY', 'A narrow cone geyser near Old Faithful known for forceful eruptions and a small indicator vent that may precede activity.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Steamboat Geyser', 'steamboat-geyser', 'roadside-oddities', 44.72368, -110.7032, 'Yellowstone National Park', 'WY', 'The world''s tallest active geyser, with rare major eruptions that can exceed the height of Old Faithful by a wide margin.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Echinus Geyser', 'echinus-geyser', 'roadside-oddities', 44.72211, -110.70217, 'Yellowstone National Park', 'WY', 'An acidic geyser in Norris Basin with a name referring to the spiny appearance of mineral deposits around its vent.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Porcelain Basin', 'porcelain-basin', 'roadside-oddities', 44.72828, -110.70397, 'Yellowstone National Park', 'WY', 'A stark, steaming expanse of milky mineral ground and intensely colored hot springs in Norris Geyser Basin.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Liberty Cap', 'liberty-cap', 'roadside-oddities', 44.97283, -110.7044, 'Mammoth Hot Springs', 'WY', 'A 37-foot dormant hot-spring cone whose shape reminded early visitors of the peaked caps associated with the French Revolution.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Palette Spring', 'palette-spring', 'roadside-oddities', 44.97247, -110.70526, 'Mammoth Hot Springs', 'WY', 'Flowing thermal water paints steep travertine terraces with shifting white, orange and brown mineral and microbial bands.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Mammoth Hot Springs Lower Terraces', 'mammoth-hot-springs-lower-terraces', 'roadside-oddities', 44.97266, -110.70394, 'Mammoth Hot Springs', 'WY', 'A constantly changing landscape of travertine steps, steaming pools and mineral formations unlike Yellowstone''s silica geyser basins.', 'limited', 'https://www.nps.gov/yell/learn/nature/hydrothermal-features.htm', null, 'America/Denver', now()),
  ('Roaring Mountain', 'roaring-mountain', 'roadside-oddities', 44.77719, -110.728, 'Yellowstone National Park', 'WY', 'A mountainside studded with fumaroles; early visitors described the combined steam vents as loud enough to roar.', 'limited', 'https://www.nps.gov/yell/index.htm', null, 'America/Denver', now()),
  ('Sheepeater Cliff', 'sheepeater-cliff', 'roadside-oddities', 44.8912, -110.72997, 'Yellowstone National Park', 'WY', 'Columnar basalt forms a wall of tightly packed stone pillars named for the Tukadeka, or Sheepeater, people of the region.', 'limited', 'https://www.nps.gov/yell/index.htm', null, 'America/Denver', now()),
  ('Tower Fall', 'tower-fall', 'roadside-oddities', 44.89383, -110.38718, 'Yellowstone National Park', 'WY', 'A 132-foot waterfall framed by eroded volcanic pinnacles that give the area its ''tower'' name.', 'limited', 'https://www.nps.gov/yell/index.htm', null, 'America/Denver', now()),
  ('Petrified Tree', 'petrified-tree', 'roadside-oddities', 44.9163, -110.4394, 'Yellowstone National Park', 'WY', 'A standing fossilized redwood relative left from ancient volcanic burial; one of the park''s most accessible petrified-tree remnants.', 'limited', 'https://www.nps.gov/yell/index.htm', null, 'America/Denver', now()),
  ('Obsidian Cliff', 'obsidian-cliff', 'weird-history', 44.82167, -110.72778, 'Yellowstone National Park', 'WY', 'A major natural exposure of volcanic glass that Indigenous peoples quarried and traded across vast distances for thousands of years.', 'limited', 'https://www.nps.gov/yell/index.htm', null, 'America/Denver', now()),
  ('Natural Bridge', 'natural-bridge', 'roadside-oddities', 44.5263, -110.45582, 'Yellowstone National Park', 'WY', 'A 51-foot rhyolite rock bridge reached by trail near Bridge Bay, carved by erosion rather than built by people.', 'limited', 'https://www.nps.gov/yell/index.htm', null, 'America/Denver', now()),
  ('Beryl Spring', 'beryl-spring', 'roadside-oddities', 44.67875, -110.74628, 'Yellowstone National Park', 'WY', 'One of Yellowstone''s hottest springs sits almost directly beside the Grand Loop Road, steaming vividly against the forest.', 'limited', 'https://www.nps.gov/yell/learn/photosmultimedia/sounds-berylspring.htm', null, 'America/Denver', now()),
  ('Old Faithful Inn', 'old-faithful-inn', 'weird-history', 44.45992, -110.83121, 'Yellowstone National Park', 'WY', 'A monumental log hotel built in 1903-04 around a towering rustic lobby, directly beside the Old Faithful geyser basin.', 'limited', 'https://www.yellowstonenationalparklodges.com/lodgings/hotel/old-faithful-inn/', null, 'America/Denver', now()),
  ('Devils Tower', 'devils-tower-wyoming', 'roadside-oddities', 44.59052, -104.71516, 'Devils Tower', 'WY', 'A sheer igneous monolith sacred to multiple Indigenous nations and later made America''s first national monument.', 'open', 'https://www.nps.gov/deto/index.htm', null, 'America/Denver', now()),
  ('Fossil Butte National Monument', 'fossil-butte-national-monument', 'roadside-oddities', 41.85635, -110.76248, 'Kemmerer', 'WY', 'Exceptionally detailed fossils from a 52-million-year-old lake include fish, reptiles, plants, birds and mammals.', 'open', 'https://www.nps.gov/fobu/index.htm', null, 'America/Denver', now()),
  ('Red Gulch Dinosaur Tracksite', 'red-gulch-dinosaur-tracksite', 'roadside-oddities', 44.46243, -107.81564, 'Shell', 'WY', 'Hundreds of Middle Jurassic dinosaur footprints cross an ancient tidal-flat surface at Wyoming''s largest documented tracksite.', 'limited', 'https://www.blm.gov/visit/red-gulch-dinosaur-tracksite', null, 'America/Denver', now()),
  ('Medicine Lodge Rock Art & Archaeological Site', 'medicine-lodge-rock-art-archaeological-site', 'weird-history', 44.29924, -107.54133, 'Hyattville', 'WY', 'A sandstone cliff holds hundreds of petroglyphs and pictographs above archaeological deposits documenting more than 10,000 years of human use.', 'open', 'https://wyoparks.wyo.gov/', null, 'America/Denver', now()),
  ('Legend Rock Petroglyph Site', 'legend-rock-petroglyph-site', 'weird-history', 43.80026, -108.59716, 'Hot Springs County', 'WY', 'A long sandstone cliff preserves hundreds of Indigenous petroglyph figures, including examples of the Dinwoody tradition.', 'limited', 'https://www.nps.gov/articles/visit-indigenous-landscapes.htm', null, 'America/Denver', now()),
  ('Vore Buffalo Jump', 'vore-buffalo-jump', 'weird-history', 44.53583, -104.15667, 'Beulah', 'WY', 'A natural sinkhole used as a communal bison kill site, preserving dense layers of bones and archaeological evidence.', 'limited', 'https://vorebuffalojump.org/', null, 'America/Denver', now()),
  ('White Mountain Petroglyphs', 'white-mountain-petroglyphs', 'weird-history', 41.88955, -109.25976, 'Sweetwater County', 'WY', 'Sandstone panels preserve carved figures and handprints associated with centuries of Indigenous use of the Green River region.', 'limited', 'https://www.blm.gov/visit/white-mountain-petroglyphs', null, 'America/Denver', now()),
  ('Cedar Canyon Petroglyphs', 'cedar-canyon-petroglyphs', 'weird-history', 41.89203, -109.0928, 'Sweetwater County', 'WY', 'A remote BLM rock-art site with historic-era petroglyphs reached by rough backcountry roads; high clearance is recommended.', 'limited', 'https://www.blm.gov/visit/cedar-canyon-petroglyphs', null, 'America/Denver', now()),
  ('Castle Gardens Petroglyph Site', 'castle-gardens-petroglyph-site', 'weird-history', 42.9293, -107.6137, 'Fremont County', 'WY', 'Wind-carved sandstone ''castles'' surround protected Native American petroglyph panels at this remote BLM site.', 'limited', 'https://www.blm.gov/visit/castle-gardens-petroglyph-site', null, 'America/Denver', now()),
  ('The Sinks', 'the-sinks', 'roadside-oddities', 42.74735, -108.80953, 'Sinks Canyon', 'WY', 'The Popo Agie River disappears into a limestone cavern here, beginning an underground route that still is not fully mapped.', 'open', 'https://wyoparks.wyo.gov/', null, 'America/Denver', now()),
  ('The Rise', 'the-rise', 'roadside-oddities', 42.75266, -108.80557, 'Sinks Canyon', 'WY', 'Water from the disappearing Popo Agie resurfaces downstream in a large trout-filled pool after traveling through the canyon''s subsurface system.', 'open', 'https://wyoparks.wyo.gov/', null, 'America/Denver', now()),
  ('Periodic Spring', 'periodic-spring', 'roadside-oddities', 42.74674, -110.84935, 'Afton', 'WY', 'One of the world''s largest rhythmic springs periodically stops and restarts its flow, likely because of a natural siphon system underground.', 'limited', 'https://www.fs.usda.gov/r04/bridger-teton/recreation/periodic-spring-picnic-site', null, 'America/Denver', now()),
  ('Parting of the Waters', 'parting-of-the-waters', 'roadside-oddities', 44.04134, -110.17491, 'Teton Wilderness', 'WY', 'At Two Ocean Pass, a creek divides so that water can ultimately reach both the Atlantic and Pacific drainage systems.', 'limited', 'https://travelwyoming.com/blog/stories/post/10-strange-and-wild-landmarks-in-wyoming/', null, 'America/Denver', now()),
  ('Killpecker Sand Dunes', 'killpecker-sand-dunes', 'roadside-oddities', 41.96113, -109.08057, 'Sweetwater County', 'WY', 'A huge field of active sand dunes includes one of the largest moving-dune systems in North America and a designated open-play area.', 'limited', 'https://www.blm.gov/visit/killpecker-sand-dunes-open-play-area', null, 'America/Denver', now()),
  ('Boar''s Tusk', 'boars-tusk', 'roadside-oddities', 41.96136, -109.19964, 'Sweetwater County', 'WY', 'A 400-foot volcanic neck rises abruptly from the Killpecker plain; BLM prohibits climbing and recommends high-clearance access.', 'limited', 'https://www.blm.gov/visit/boars-tusk', null, 'America/Denver', now()),
  ('Vedauwoo Rock Formations', 'vedauwoo-rock-formations', 'roadside-oddities', 41.1394, -105.3772, 'Albany County', 'WY', 'Massive weathered granite outcrops create stacked, rounded forms that look improbably balanced above the high plains.', 'open', 'https://main.wsgs.wyo.gov/outreach/cultural-geology/guide-vedauwoo', null, 'America/Denver', now()),
  ('Hell''s Half Acre', 'hells-half-acre', 'roadside-oddities', 43.03802, -107.09312, 'Natrona County', 'WY', 'A maze of eroded badlands, ravines and spires beside US 20/26 whose name matches its harsh, otherworldly appearance.', 'roadside', 'https://travelwyoming.com/blog/stories/post/10-strange-and-wild-landmarks-in-wyoming/', null, 'America/Denver', now()),
  ('Heart Mountain', 'heart-mountain', 'roadside-oddities', 44.66598, -109.11881, 'Park County', 'WY', 'An isolated mountain formed from a gigantic prehistoric landslide block, a classic geologic puzzle rising above the Bighorn Basin.', 'limited', 'https://travelwyoming.com/blog/stories/post/10-strange-and-wild-landmarks-in-wyoming/', null, 'America/Denver', now()),
  ('Medicine Wheel / Medicine Mountain', 'medicine-wheel-medicine-mountain', 'weird-history', 44.82611, -107.92222, 'Bighorn National Forest', 'WY', 'A large Indigenous stone medicine wheel and sacred landscape on Medicine Mountain; visitors should follow all cultural-respect restrictions.', 'limited', 'https://www.fs.usda.gov/r02/bighorn', null, 'America/Denver', now()),
  ('Ayres Natural Bridge', 'ayres-natural-bridge', 'roadside-oddities', 42.73476, -105.61111, 'Converse County', 'WY', 'LaPrele Creek passes beneath a naturally eroded rock arch in a small county park hidden below the surrounding plains.', 'limited', 'https://travelwyoming.com/blog/stories/post/10-strange-and-wild-landmarks-in-wyoming/', null, 'America/Denver', now()),
  ('Teapot Rock', 'teapot-rock', 'weird-history', 43.23332, -106.31099, 'Natrona County', 'WY', 'The namesake rock formation for the Teapot Dome oil field, forever tied to one of the most notorious political scandals of the 1920s.', 'roadside', 'https://www.nps.gov/state/wy/list.htm?program=all', null, 'America/Denver', now()),
  ('Rainbow Terraces', 'rainbow-terraces', 'roadside-oddities', 43.65342, -108.19527, 'Thermopolis', 'WY', 'Hot mineral water builds and stains broad travertine terraces in Hot Springs State Park, creating constantly changing bands of color.', 'open', 'https://travelwyoming.com/blog/stories/post/10-strange-and-wild-landmarks-in-wyoming/', null, 'America/Denver', now()),
  ('Teepee Fountain', 'teepee-fountain', 'roadside-oddities', 43.65222, -108.20008, 'Thermopolis', 'WY', 'Mineral water has coated an old cooling structure for decades, building a bulbous travertine formation that resembles a natural sculpture.', 'open', 'https://travelwyoming.com/blog/stories/post/10-strange-and-wild-landmarks-in-wyoming/', null, 'America/Denver', now()),
  ('Hobo Hot Pool', 'hobo-hot-pool', 'roadside-oddities', 41.45005, -106.80248, 'Saratoga', 'WY', 'A free municipal soaking pool fed by natural hot springs, traditionally open around the clock rather than operating like a typical spa.', 'open', 'https://www.townofsaratoga.org/205/Hobo-Pool', null, 'America/Denver', now()),
  ('Adobe Town Wilderness Study Area', 'adobe-town-wilderness-study-area', 'roadside-oddities', 41.25154, -108.28559, 'Sweetwater County', 'WY', 'Remote badlands contain bizarre erosional forms, abundant Eocene fossils and dense archaeological resources spanning roughly 12,000 years.', 'limited', 'https://www.blm.gov/programs/national-conservation-lands/wyoming/adobe-town-wsa', null, 'America/Denver', now()),
  ('Outlaw Cave', 'outlaw-cave', 'folklore', 43.58902, -106.94734, 'Johnson County', 'WY', 'A steep trail descends toward a cave long associated with Butch Cassidy and Wild Bunch outlaw lore in the Middle Fork Powder River country.', 'limited', 'https://www.blm.gov/visit/outlaw-cave-trail', null, 'America/Denver', now()),
  ('Crookston Ranch Cultural Site', 'crookston-ranch-cultural-site', 'weird-history', 41.9566, -109.08241, 'Sweetwater County', 'WY', 'A preserved ranch site in the Killpecker area where BLM interpretation connects local ranch history with stories of Butch Cassidy passing through.', 'limited', 'https://www.blm.gov/visit/crookston-ranch-cultural-site', null, 'America/Denver', now()),
  ('Tri-Territory Site', 'tri-territory-site', 'weird-history', 42, -108.91714, 'Sweetwater County', 'WY', 'A monument marks the surveyed point where the Louisiana Purchase, Oregon Country and Mexican Cession once converged.', 'limited', 'https://www.wyohistory.org/encyclopedia/tri-territory-site-outpost-invisible-empires', null, 'America/Denver', now()),
  ('Colter''s Hell', 'colters-hell', 'weird-history', 44.51472, -109.11722, 'Cody', 'WY', 'A largely dormant thermal area whose early reports by John Colter helped fuel frontier stories about a strange ''hell'' of steam and hot water.', 'roadside', 'https://npgallery.nps.gov/AssetDetail/NRIS/73001937', null, 'America/Denver', now()),
  ('South Pass City', 'south-pass-city', 'weird-history', 42.46632, -108.80032, 'South Pass City', 'WY', 'A remarkably preserved gold-rush town with original buildings and major ties to Wyoming''s mining and women''s-suffrage history.', 'limited', 'https://travelwyoming.com/blog/stories/post/5-wyoming-ghost-towns-you-need-to-explore/', null, 'America/Denver', now()),
  ('Carissa Gold Mine', 'carissa-gold-mine', 'weird-history', 42.47411, -108.79378, 'South Pass City', 'WY', 'The restored gold mine above South Pass City preserves hoisting, milling and mining infrastructure from the district''s boom years.', 'limited', 'https://www.loc.gov/item/wy0072/', null, 'America/Denver', now()),
  ('Miner''s Delight', 'miners-delight', 'weird-history', 42.50431, -108.68118, 'Fremont County', 'WY', 'One of the three principal communities of the South Pass gold district survives as a remote collection of cabins and mining-era remains.', 'limited', 'https://www.loc.gov/pictures/item/wy0065/', null, 'America/Denver', now()),
  ('Atlantic City Historic Mining Town', 'atlantic-city-historic-mining-town', 'weird-history', 42.49523, -108.71883, 'Atlantic City', 'WY', 'A tiny surviving mining settlement where modern residents, old structures and surrounding gold-rush remnants overlap.', 'limited', 'https://travelwyoming.com/blog/stories/post/5-wyoming-ghost-towns-you-need-to-explore/', null, 'America/Denver', now()),
  ('Kirwin Ghost Town', 'kirwin-ghost-town', 'weird-history', 43.87635, -109.29787, 'Park County', 'WY', 'A high-elevation mining town abandoned after an avalanche, reached by a rough road deep in the Absaroka Mountains.', 'limited', 'https://travelwyoming.com/blog/stories/post/5-wyoming-ghost-towns-you-need-to-explore/', null, 'America/Denver', now()),
  ('Double D Ranch / Amelia Earhart Cabin Site', 'double-d-ranch-amelia-earhart-cabin-site', 'weird-history', 43.93551, -109.21209, 'Park County', 'WY', 'Remote ranch remains are tied to Amelia Earhart, who planned a cabin in the Kirwin country before her 1937 disappearance.', 'limited', 'https://travelwyoming.com/blog/stories/post/5-wyoming-ghost-towns-you-need-to-explore/', null, 'America/Denver', now()),
  ('Piedmont Ghost Town', 'piedmont-ghost-town', 'weird-history', 41.21606, -110.62739, 'Uinta County', 'WY', 'Ruins mark a railroad and timber settlement that faded after Union Pacific rerouted its line away from the community.', 'limited', 'https://travelwyoming.com/blog/stories/post/5-wyoming-ghost-towns-you-need-to-explore/', null, 'America/Denver', now()),
  ('Piedmont Charcoal Kilns', 'piedmont-charcoal-kilns', 'weird-history', 41.21992, -110.61944, 'Uinta County', 'WY', 'Three surviving beehive-shaped stone kilns once converted local timber into charcoal for regional smelting operations.', 'limited', 'https://travelwyoming.com/blog/stories/post/5-wyoming-ghost-towns-you-need-to-explore/', null, 'America/Denver', now()),
  ('Gebo-Crosby Historic Mining District', 'gebo-crosby-historic-mining-district', 'weird-history', 43.78935, -108.22916, 'Hot Springs County', 'WY', 'Abandoned coal-camp remains, foundations and cemetery traces survive in a remote BLM-managed mining district; old workings are unsafe to enter.', 'limited', 'https://www.blm.gov/visit/gebo-crosby-historic-mining-district', null, 'America/Denver', now()),
  ('Reliance Tipple', 'reliance-tipple', 'weird-history', 41.668, -109.19683, 'Reliance', 'WY', 'A rare surviving wooden coal-loading tipple preserves the industrial scale of Sweetwater County''s early coal-mining communities.', 'limited', 'https://npgallery.nps.gov/GetAsset/9c2c7f1f-3dbd-4c84-9992-2f1de1897a99', null, 'America/Denver', now()),
  ('Fort Laramie National Historic Site', 'fort-laramie-national-historic-site', 'weird-history', 42.20302, -104.54591, 'Fort Laramie', 'WY', 'A major fur-trade post and military fort on the Oregon, California and Mormon Pioneer trail corridor, with extensive preserved structures.', 'open', 'https://www.nps.gov/fola/index.htm', null, 'America/Denver', now()),
  ('Independence Rock', 'independence-rock', 'weird-history', 42.49361, -107.12944, 'Natrona County', 'WY', 'A huge granite landmark where generations of emigrants carved names while traveling the overland trails west.', 'open', 'https://www.nps.gov/cali/planyourvisit/independence-rock.htm', null, 'America/Denver', now()),
  ('Register Cliff', 'register-cliff', 'weird-history', 42.2476, -104.71136, 'Guernsey', 'WY', 'Thousands of emigrants passed this sandstone cliff, leaving carved names and dates that survive beside the North Platte River.', 'open', 'https://www.nps.gov/places/000/register-cliff-historic-site.htm', null, 'America/Denver', now()),
  ('Oregon Trail Ruts', 'oregon-trail-ruts', 'weird-history', 42.2559, -104.7483, 'Guernsey', 'WY', 'Repeated wagon traffic physically cut deep grooves into the sandstone, leaving some of the clearest surviving Oregon Trail ruts.', 'open', 'https://www.nps.gov/places/000/oregon-trail-ruts-state-historic-site.htm', null, 'America/Denver', now()),
  ('Devil''s Gate', 'devils-gate', 'weird-history', 42.441, -107.221, 'Natrona County', 'WY', 'The Sweetwater River slices through a narrow granite gorge that became one of the most memorable landmarks on the emigrant trails.', 'limited', 'https://www.nps.gov/cali/planyourvisit/devils-gate.htm', null, 'America/Denver', now()),
  ('Fort Caspar Museum', 'fort-caspar-museum', 'weird-history', 42.83599, -106.37162, 'Casper', 'WY', 'A reconstructed frontier post sits at an important North Platte crossing used by emigrant trails, ferries and the Pony Express.', 'limited', 'https://www.nps.gov/places/upper-platte-ferry-1847.htm', null, 'America/Denver', now()),
  ('Quebec-01 Missile Alert Facility', 'quebec-01-missile-alert-facility', 'weird-history', 41.54306, -104.90278, 'Cheyenne', 'WY', 'A preserved Peacekeeper missile command facility offers access to one of the underground control centers once tied to Wyoming''s nuclear arsenal.', 'limited', 'https://www.nps.gov/places/quebec-one.htm', null, 'America/Denver', now()),
  ('Big Sandy Crossing Historical Marker', 'big-sandy-crossing-historical-marker', 'weird-history', 42.10795, -109.45324, 'Farson', 'WY', 'A highway turnout marks the public-accessible Fort Bridger route crossing of the Big Sandy used by multiple national historic trails.', 'roadside', 'https://www.nps.gov/places/big-sandy-crossing.htm', null, 'America/Denver', now()),
  ('Little Sandy Crossing', 'little-sandy-crossing', 'weird-history', 42.19648, -109.37839, 'Sublette County', 'WY', 'An overland-trail crossing associated with emigrant travel and the meeting of Jim Bridger and Brigham Young.', 'limited', 'https://www.blm.gov/visit/little-sandy-crossing', null, 'America/Denver', now()),
  ('False Parting of the Ways', 'false-parting-of-the-ways', 'weird-history', 42.28446, -109.05896, 'Sweetwater County', 'WY', 'A signed trail junction recalls how emigrant routes split across the high desert—and why this spot was long confused with the true Parting of the Ways.', 'limited', 'https://www.blm.gov/visit/false-parting-ways', null, 'America/Denver', now()),
  ('Emigrant Gap Interpretive Site', 'emigrant-gap-interpretive-site', 'weird-history', 42.84461, -106.53889, 'Natrona County', 'WY', 'A BLM interpretive stop marks an important passage through the terrain used by overland emigrants approaching the North Platte corridor.', 'limited', 'https://www.blm.gov/visit/emigrant-gap-interpretive-site', null, 'America/Denver', now()),
  ('National Historic Trails Interpretive Center', 'national-historic-trails-interpretive-center', 'museums', 42.86633, -106.33715, 'Casper', 'WY', 'Immersive exhibits interpret the Oregon, California, Mormon Pioneer and Pony Express routes that converged through central Wyoming.', 'open', 'https://www.blm.gov/visit/national-historic-trails-interpretive-center', null, 'America/Denver', now()),
  ('Superior Air Mail Arrow', 'superior-air-mail-arrow', 'weird-history', 41.67158, -108.94119, 'Sweetwater County', 'WY', 'A giant concrete navigation arrow survives from the era when ground markers guided early airmail pilots across the West.', 'limited', 'https://www.blm.gov/visit/superior-mail-arrow', null, 'America/Denver', now()),
  ('Pilot Butte Overlook & Replica Emigrant Graves', 'pilot-butte-overlook-replica-emigrant-graves', 'weird-history', 41.99916, -109.62291, 'Sweetwater County', 'WY', 'A heart-shaped interpretive loop beside trail ruts uses two replica emigrant graves to interpret death and burial on the overland trails.', 'roadside', 'https://home.nps.gov/places/pilot-butte-overlook.htm', null, 'America/Denver', now()),
  ('Pacific Creek Homestead Interpretive Site', 'pacific-creek-homestead-interpretive-site', 'weird-history', 42.33303, -108.94598, 'Sweetwater County', 'WY', 'Dilapidated homestead buildings survive beside an interpretive stop; BLM specifically warns visitors not to enter the structures.', 'limited', 'https://www.blm.gov/visit/pacific-creek-interp-site', null, 'America/Denver', now()),
  ('Oregon Buttes Interpretive Site', 'oregon-buttes-interpretive-site', 'weird-history', 42.35557, -108.85176, 'Sweetwater County', 'WY', 'A remote interpretive site marks the Oregon Buttes, a stark Red Desert landmark that helped emigrants navigate after crossing the Continental Divide.', 'limited', 'https://www.blm.gov/visit/oregon-buttes', null, 'America/Denver', now()),
  ('Names Hill', 'names-hill', 'weird-history', 42.17197, -110.18783, 'Lincoln County', 'WY', 'A sandstone bluff beside the emigrant-trail corridor preserves historic carved names and dates, including the well-known ''J. Bridger 1844'' inscription.', 'roadside', 'https://www.nps.gov/state/wy/list.htm?program=all', null, 'America/Denver', now()),
  ('Fort Bridger State Historic Site', 'fort-bridger-state-historic-site', 'weird-history', 41.31813, -110.39127, 'Fort Bridger', 'WY', 'Jim Bridger''s trading-post site later became a military fort and major stopping point on western emigrant routes.', 'limited', 'https://wyoparks.wyo.gov/', null, 'America/Denver', now()),
  ('Fort Phil Kearny', 'fort-phil-kearny', 'weird-history', 44.53219, -106.826, 'Banner', 'WY', 'A reconstructed stockade footprint and visitor center interpret the short-lived 1860s fort at the center of Red Cloud''s War.', 'limited', 'https://wyoparks.wyo.gov/', null, 'America/Denver', now()),
  ('Fetterman Fight Battlefield', 'fetterman-fight-battlefield', 'weird-history', 44.57152, -106.84131, 'Johnson County', 'WY', 'The site marks the 1866 battle in which 81 U.S. soldiers and civilians were killed after leaving Fort Phil Kearny.', 'limited', 'https://wyoparks.wyo.gov/', null, 'America/Denver', now()),
  ('Wagon Box Fight Battlefield', 'wagon-box-fight-battlefield', 'weird-history', 44.55528, -106.89456, 'Johnson County', 'WY', 'Interpretive markers cover the 1867 fight where soldiers and civilians defended a corral made from detached wagon boxes.', 'limited', 'https://wyoparks.wyo.gov/', null, 'America/Denver', now()),
  ('Connor Battlefield', 'connor-battlefield', 'weird-history', 44.90875, -107.16389, 'Ranchester', 'WY', 'A state historic site interprets the 1865 Battle of Tongue River, also known as the Connor Battle, within a public park.', 'open', 'https://wyoparks.wyo.gov/', null, 'America/Denver', now()),
  ('Ames Monument', 'ames-monument', 'roadside-oddities', 41.13108, -105.39814, 'Albany County', 'WY', 'A 60-foot granite pyramid stands alone near the former highest point of the original transcontinental railroad route.', 'open', 'https://www.loc.gov/pictures/item/wy0049/', null, 'America/Denver', now()),
  ('Point of Rocks Stage Station', 'point-of-rocks-stage-station', 'weird-history', 41.6747, -108.79098, 'Point of Rocks', 'WY', 'A surviving Overland Stage station preserves the lonely scale of long-distance coach travel across southern Wyoming.', 'limited', 'https://www.loc.gov/resource/hhh.wy0030.sheet?st=gallery', null, 'America/Denver', now()),
  ('Wyoming Territorial Prison', 'wyoming-territorial-prison', 'weird-history', 41.3125, -105.60889, 'Laramie', 'WY', 'The restored territorial prison once held Butch Cassidy and now preserves cells, guard spaces and penal-industry exhibits.', 'limited', 'https://wyoparks.wyo.gov/', null, 'America/Denver', now()),
  ('Wyoming Frontier Prison', 'wyoming-frontier-prison', 'weird-history', 41.79293, -107.24234, 'Rawlins', 'WY', 'Wyoming''s first state penitentiary preserves cell blocks, the gallows area and execution history; it is also the subject of long-running ghost stories.', 'limited', 'https://www.wyomingcarboncounty.com/things-to-do/museums/wyoming-frontier-prison', null, 'America/Denver', now()),
  ('Fort Fred Steele', 'fort-fred-steele', 'weird-history', 41.77885, -106.9463, 'Carbon County', 'WY', 'Ruins and surviving buildings mark the 1868 military post built to protect workers and traffic along the first transcontinental railroad.', 'limited', 'https://wyoparks.wyo.gov/', null, 'America/Denver', now()),
  ('Wyoming Dinosaur Center', 'wyoming-dinosaur-center', 'museums', 43.64321, -108.20052, 'Thermopolis', 'WY', 'A major dinosaur museum paired with active fossil dig sites, including exceptionally large and unusual mounted specimens.', 'open', 'https://wyomingdinosaurcenter.org/', null, 'America/Denver', now()),
  ('Museum of the Mountain Man', 'museum-of-the-mountain-man', 'museums', 42.8693, -109.852, 'Pinedale', 'WY', 'Artifacts and exhibits focus on the fur-trade rendezvous era, mountain men and the violent, strange logistics of early Rocky Mountain travel.', 'limited', 'https://museumofthemountainman.com/', null, 'America/Denver', now()),
  ('National Museum of Military Vehicles', 'national-museum-of-military-vehicles', 'museums', 43.4735, -109.49623, 'Dubois', 'WY', 'A vast private collection displays hundreds of U.S. military vehicles in an unexpectedly large museum complex outside tiny Dubois.', 'open', 'https://nmmv.org/', null, 'America/Denver', now()),
  ('Museum of Flight & Aerial Firefighting', 'museum-of-flight-aerial-firefighting', 'museums', 44.51056, -108.08549, 'Greybull', 'WY', 'An outdoor aircraft collection at a former air-tanker base preserves large firefighting planes and unusual aviation equipment.', 'limited', 'https://www.museumofflight.us/', null, 'America/Denver', now()),
  ('Old Trail Town', 'old-trail-town', 'museums', 44.51564, -109.10422, 'Cody', 'WY', 'Historic cabins, frontier buildings, graves and outlaw-associated structures were relocated here to create a concentrated Old West streetscape.', 'limited', 'https://oldtrailtown.org/', null, 'America/Denver', now()),
  ('Cody Dug Up Gun Museum', 'cody-dug-up-gun-museum', 'museums', 44.52647, -109.06373, 'Cody', 'WY', 'The collection centers on corroded, broken and excavated firearms recovered from battlefields, settlements, ranches and archaeological contexts.', 'limited', 'https://codydugupgunmuseum.com/', null, 'America/Denver', now()),
  ('Carbon County Museum — Big Nose George Artifacts', 'carbon-county-museum-big-nose-george-artifacts', 'museums', 41.79093, -107.24716, 'Rawlins', 'WY', 'Local-history collections include artifacts connected to outlaw Big Nose George Parrott, whose corpse became part of one of Wyoming''s most macabre stories.', 'open', 'https://www.carboncountymuseum.org/', null, 'America/Denver', now()),
  ('Campbell County Rockpile Museum', 'campbell-county-rockpile-museum', 'museums', 44.29312, -105.51479, 'Gillette', 'WY', 'The museum grew around Gillette''s literal landmark rockpile and now combines regional history with outdoor rail, ranch and industrial exhibits.', 'open', 'https://campbellcountywy.gov/2351/Rockpile-Museum', null, 'America/Denver', now()),
  ('Jackalope Square', 'jackalope-square', 'folklore', 42.75943, -105.38413, 'Douglas', 'WY', 'Douglas embraces its claim as the jackalope''s hometown with a large horned-rabbit statue and town-square tribute to the invented creature.', 'open', 'https://www.cityofdouglas.org/facilities/facility/details/Jackalope-Square-18', null, 'America/Denver', now()),
  ('Greater Green River Intergalactic Spaceport', 'greater-green-river-intergalactic-spaceport', 'ufos', 41.45796, -109.4902, 'Green River', 'WY', 'The municipal airfield gained the tongue-in-cheek ''Intergalactic Spaceport'' designation as a refuge for potential stranded extraterrestrials.', 'roadside', 'https://www.grwyo.org/DocumentCenter/View/2559/Green-River-Airport-Master-Plan?bidId=', null, 'America/Denver', now()),
  ('Mama Mimi Giant Troll', 'mama-mimi-giant-troll', 'roadside-oddities', 43.50197, -110.84322, 'Wilson', 'WY', 'Thomas Dambo''s enormous recycled-wood troll crouches in R Park, turning a public nature area into a literal giant-creature hunt.', 'open', 'https://jhpublicart.org/art/mama-mimi', null, 'America/Denver', now()),
  ('Grand Encampment Museum Two-Story Outhouse', 'grand-encampment-museum-two-story-outhouse', 'museums', 41.20403, -106.78903, 'Encampment', 'WY', 'The museum''s preserved two-story outhouse was designed so the upper level could remain usable when winter snow buried the lower entrance.', 'limited', 'https://gemuseum.com/', null, 'America/Denver', now()),
  ('Lincoln Monument', 'lincoln-monument', 'roadside-oddities', 41.23693, -105.43626, 'Albany County', 'WY', 'A gigantic bronze bust of Abraham Lincoln sits atop a 30-foot granite pedestal at the highest point of Interstate 80.', 'open', 'https://travelwyoming.com/blog/stories/post/10-strange-and-wild-landmarks-in-wyoming/', null, 'America/Denver', now()),
  ('Fossil Bone Cabin', 'fossil-bone-cabin', 'roadside-oddities', 41.86517, -106.0732, 'Medicine Bow', 'WY', 'A 1930s roadside cabin was built from thousands of dinosaur bones collected around Como Bluff; the historic attraction itself is closed.', 'roadside', 'https://www.wyohistory.org/field-trips/como-bluff', null, 'America/Denver', now()),
  ('Mother Featherlegs Monument', 'mother-featherlegs-monument', 'weird-history', 42.62618, -104.53123, 'Niobrara County', 'WY', 'A remote grave marker remembers Charlotte ''Mother Featherlegs'' Shepard, a roadhouse operator murdered in 1879 and wrapped into local outlaw lore.', 'roadside', 'https://www.hmdb.org/m.asp?m=98303', null, 'America/Denver', now()),
  ('World''s Largest Elkhorn Arch', 'worlds-largest-elkhorn-arch', 'roadside-oddities', 42.72432, -110.93356, 'Afton', 'WY', 'A huge arch spanning US 89 is assembled from thousands of elk antlers and serves as the defining landmark of downtown Afton.', 'open', 'https://travelwyoming.com/blog/stories/post/10-strange-and-wild-landmarks-in-wyoming/', null, 'America/Denver', now()),
  ('Occidental Hotel', 'occidental-hotel', 'haunted', 44.3473, -106.69884, 'Buffalo', 'WY', 'The restored 1880s hotel and saloon preserves Old West interiors and is frequently associated with reported ghost stories, including a child spirit.', 'limited', 'https://travelwyoming.com/blog/stories/post/haunted-places-to-visit-in-wyoming/', null, 'America/Denver', now()),
  ('Irma Hotel', 'irma-hotel', 'haunted', 44.52575, -109.06444, 'Cody', 'WY', 'Buffalo Bill Cody''s 1902 hotel retains its ornate cherrywood bar and is the subject of recurring reports of unexplained activity.', 'limited', 'https://travelwyoming.com/blog/stories/post/haunted-places-to-visit-in-wyoming/', null, 'America/Denver', now()),
  ('Historic Plains Hotel', 'historic-plains-hotel', 'haunted', 41.13318, -104.81445, 'Cheyenne', 'WY', 'A landmark 1911 downtown hotel with long-running local ghost legends attached to its rooms, halls and early-20th-century history.', 'limited', 'https://travelwyoming.com/blog/stories/post/haunted-places-to-visit-in-wyoming/', null, 'America/Denver', now()),
  ('Sweetwater County Library', 'sweetwater-county-library', 'haunted', 41.53014, -109.46469, 'Green River', 'WY', 'This working public library is repeatedly featured in local paranormal lore involving apparitions, voices and unexplained movement after hours.', 'limited', 'https://travelwyoming.com/blog/stories/post/haunted-places-to-visit-in-wyoming/', null, 'America/Denver', now()),
  ('Virginian Hotel', 'virginian-hotel', 'haunted', 41.89564, -106.20017, 'Medicine Bow', 'WY', 'A 1911 hotel tied to Owen Wister''s ''The Virginian'' remains a functioning lodging property with a reputation for reported hauntings.', 'limited', 'https://travelwyoming.com/blog/stories/post/haunted-places-to-visit-in-wyoming/', null, 'America/Denver', now()),
  ('Sheridan Inn', 'sheridan-inn', 'haunted', 44.8066, -106.95387, 'Sheridan', 'WY', 'The 1893 hotel is associated with Buffalo Bill Cody and with the frequently retold ghost story of longtime employee Miss Kate Arnold.', 'limited', 'https://travelwyoming.com/blog/stories/post/haunted-places-to-visit-in-wyoming/', null, 'America/Denver', now()),
  ('Chugwater Soda Fountain', 'chugwater-soda-fountain', 'roadside-oddities', 41.75688, -104.82159, 'Chugwater', 'WY', 'A surviving small-town soda fountain preserves an unusually intact early drugstore-and-fountain atmosphere along the old highway.', 'limited', 'https://travelwyoming.com/blog/stories/post/10-strange-and-wild-landmarks-in-wyoming/', null, 'America/Denver', now()),
  ('Aladdin General Store', 'aladdin-general-store', 'roadside-oddities', 44.64006, -104.18264, 'Aladdin', 'WY', 'An operating 1896 mercantile retains original woodwork, cabinetry, bins and an antique-filled upper floor in one of Wyoming''s tiniest communities.', 'limited', 'https://travelwyoming.com/listing/aladdin-general-store/24/', null, 'America/Denver', now()),
  ('Heart Mountain Interpretive Center', 'heart-mountain-interpretive-center', 'museums', 44.67035, -108.9414, 'Powell', 'WY', 'The museum and surviving structures interpret the World War II incarceration of Japanese Americans at the Heart Mountain confinement site.', 'limited', 'https://heartmountain.org/visit/', null, 'America/Denver', now())
on conflict (slug) do update set
  description   = excluded.description,
  public_access = excluded.public_access,
  source        = excluded.source,
  website       = excluded.website,
  verified_at   = excluded.verified_at;

select count(*) as wyoming from public.stops where state = 'WY';
